# -*- coding: utf-8 -*-
"""
法人Web 請求書（CW_BILL）の画面設計書データ。元：本物の Web（app/corp/bills/page.tsx・app/corp/bills/[no]/page.tsx・lib/corp/docs/{logic,types,fromDomain}.ts・lib/corp/areas/corp-docs.ts・lib/domain/invoiceTax.ts・lib/domain/seed/billing.ts）。
決定：docs/決定台帳.md E（2026-10-05：状態は 確定／請求済み＋再請求バッジ・Bill One はバッジ1つ・一覧は P-LIST（請求月・請求先・状態、10件）・「固定額」「ご利用実績の精算」・発行日 降順）。
コードがまだ決定に追いついていないところは demo_ok（受付簿 No.78・74）。版 1.4 で、この設計書に残っていた demo_ok はなくなった（コードが追いついた）。
版 1.1（2026-10-05・hong の版 1.0 レビュー、台帳 E「法人Web 版 1.0 のレビュー（棚卸報告・請求書）」⑧⑨）：Bill One の送付エラーは法人に出さない（「送付済み」だけ）・見つからないときは標準の空表示（戻るボタンつき）。コードは対応済（受付簿 No.153）。
版 1.3（2026-10-05・hong 承認、台帳 E「法人Web 版 1.1 のレビュー（…請求書）」④、受付簿 No.156）：一覧の見出しを「請求書一覧」に・詳細の金額内訳を「請求金額」の1つの表（税率の列＋合計・右寄せ）に・請求書の情報を4列×2行に・明細は区分を見出しの行に。コードは対応済。
版 1.4（2026-10-05・hong 承認、台帳 E「法人Web 版 1.1 のレビュー 2回目」、受付簿 No.157）：状態の色は共通の表に従う（確定＝青・請求済み＝緑・送付済み＝緑）・「請求済」→「請求済み」・再請求のバッジは「再請求分を含む（INV-旧）」「再請求済み（→INV-新）」・一覧は検索条件とページを詳細から戻っても保つ・並びは発行日の降順に固定・読み込めなかったときの表示 E346・請求書が1通もないときの表示 I227。demo_ok を削除（コードは対応済み）。
"""

TITLE = ["請求書（CW_BILL）", "Hóa đơn (CW_BILL)"]
SHEET = ["請求書", "Hóa đơn"]
BASENAME = "画面設計書_CW_BILL_請求書"
IMG_PREFIX = "CW_BILL"
OUT_DIR = "CW_BILL_請求書"
CODE_NOTE = ["Screen Code は台帳 E 2026-10-05 の決まり：CW_<機能略>_<3桁>", "Screen Code theo 台帳 E 2026-10-05: CW_<機能略>_<3 chữ số>"]
SITE = "corp"
SYSTEM = {"ja": "法人Web", "vi": "Web pháp nhân (法人Web)"}
AUTHOR = "Claude／確認：hong"
CREATED = "2026-10-05"
DEMO_FILE = "http://localhost:3000"
LOGIN = {"site": "corp", "loginId": "CU00001"}

DECISIONS = [
    {"date": "2026-10-05", "target": "CW_BILL_001 No.3.7",
     "q": ["法人Web の請求書の状態の出し方", "Cách hiển thị trạng thái hóa đơn trên 法人Web"],
     "a": ["確定／請求済み の表示だけ（未確定は一覧に出ない）。入金済・未入金は出さない（入金の消込は取り込まないため）。再請求はバッジで示す", "Chỉ hiện 確定 / 請求済み (未確定 không ra danh sách). Không hiện 入金済・未入金 (không nhập dữ liệu đối chiếu thanh toán). Tái lập hóa đơn thể hiện bằng badge"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-B1）"},
    {"date": "2026-10-05", "target": "CW_BILL_001 No.3.8",
     "q": ["Bill One の送付の状態と記録を法人に見せるか", "Có cho pháp nhân xem trạng thái và nhật ký gửi Bill One không"],
     "a": ["バッジ1つだけ（送付済み／送付できませんでした）。送付の記録（開封など）は運営だけ", "Chỉ 1 badge (送付済み / 送付できませんでした). Nhật ký gửi (đã mở…) chỉ 運営 xem"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-B2）"},
    {"date": "2026-10-05", "target": "CW_BILL_001 No.2",
     "q": ["請求書の一覧に検索・ページ送りを付けるか", "Danh sách hóa đơn có tìm kiếm / phân trang không"],
     "a": ["付ける（P-LIST）。検索条件は 請求月・請求先・状態。1ページ 10件。初期の並びは発行日の降順", "Có (P-LIST). Điều kiện: 請求月・請求先・状態. 10 dòng / trang. Thứ tự ban đầu: 発行日 giảm dần"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-B3・Q-O9）"},
    {"date": "2026-10-05", "target": "CW_BILL_002 No.15.1",
     "q": ["「固定額（前払い）」「ご利用実績の精算（後払い）」の表示名", "Tên hiển thị của \"固定額（前払い）\" và \"ご利用実績の精算（後払い）\""],
     "a": ["「固定額」「ご利用実績の精算」。「前払い」「後払い」は画面にも請求書にも出さない", "\"固定額\" và \"ご利用実績の精算\". Không hiện \"前払い\" / \"後払い\" trên màn hình lẫn hóa đơn"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-B4、台帳 B 2026-10-03）"},
    {"date": "2026-10-05", "target": "CW_BILL_001 No.1.3",
     "q": ["CSV出力ボタンを請求書に置くか", "Có đặt nút CSV出力 ở 請求書 không"],
     "a": ["置く（CSV入出力_定義どおり）", "Có (theo CSV入出力_定義)"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-C3）"},
    {"date": "2026-10-05", "target": "CW_BILL_002 No.12",
     "q": ["文言の中の「ESキッチン」「ES STATION」の使い分け", "Cách dùng \"ESキッチン\" và \"ES STATION\" trong câu chữ"],
     "a": ["「ESキッチン」＝お客様（運営会社）の名前、「ES STATION」＝システムの名前（「ESSTATION」は使わない）", "\"ESキッチン\" = tên khách hàng (công ty vận hành), \"ES STATION\" = tên hệ thống (không dùng \"ESSTATION\")"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-C1）"},
    {"date": "2026-10-05", "target": "CW_BILL_001 全体",
     "q": ["解約後（参照のみ）のアカウントで請求書を見られるか", "Tài khoản sau hủy hợp đồng (chỉ xem) có xem hóa đơn không"],
     "a": ["見られる（参照のみ。最終請求書まで）。編集・お申し込みはできない", "Xem được (chỉ xem, đến hóa đơn cuối). Không sửa / đăng ký"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-C2、請求ルール 3-7）"},
    # ---- 版 1.1（hong の版 1.0 レビュー 2026-10-05）
    {"date": "2026-10-05", "target": "CW_BILL_001 No.3.8",
     "q": ["Bill One の送付エラー（送付できませんでした）を法人に見せるか（Q-B2 の見直し）", "Có cho pháp nhân thấy lỗi gửi Bill One (送付できませんでした) không (xem lại Q-B2)"],
     "a": ["見せない。バッジは「送付済み」だけ、それ以外（送付前・送付できなかった）は「—」。エラーは運営が直して送り直す。Q-B2「送付済み／送付できませんでした の2つ」を置き換え",
           "Không. Chỉ có badge \"送付済み\"; còn lại (chưa gửi, gửi lỗi) là \"—\". Lỗi do 運営 sửa và gửi lại. Thay thế Q-B2 \"2 badge 送付済み / 送付できませんでした\""],
     "src": "hong 回答 2026-10-05 版1.0レビュー ⑧"},
    {"date": "2026-10-05", "target": "CW_BILL_002 No.26",
     "q": ["請求書が見つからないときの表示", "Hiển thị khi không tìm thấy hóa đơn"],
     "a": ["標準の空表示（EmptyState：アイコン・タイトル「請求書が見つかりません」・本文・ボタン「請求書の一覧へ戻る」）", "Khung trống chuẩn (EmptyState: icon, tiêu đề \"請求書が見つかりません\", nội dung, nút \"請求書の一覧へ戻る\")"],
     "src": "hong 回答 2026-10-05 版1.0レビュー ⑨"},
    # ---- 版 1.3（hong の版 1.1 レビュー 2026-10-05・受付簿 No.156）
    {"date": "2026-10-05", "target": "CW_BILL_001 No.2・3",
     "q": ["請求書の一覧の見出し（「発行した請求書」）", "Tiêu đề danh sách hóa đơn (\"発行した請求書\")"],
     "a": ["「請求書一覧」にする（「発行した請求書」は使わない）。検索の「請求月」も「ご請求月」に揃える", "Đổi thành \"請求書一覧\" (không dùng \"発行した請求書\"). Nhãn tìm \"請求月\" cũng thống nhất thành \"ご請求月\""],
     "src": "hong 承認 2026-10-05（台帳 E 法人Web 版1.1のレビュー ④、受付簿 No.156）"},
    {"date": "2026-10-05", "target": "CW_BILL_002 No.13・15・16",
     "q": ["請求書詳細の金額の内訳の見せ方（「請求金額」の枠と、明細の下の小計・消費税の行が縦に長い）", "Cách hiển thị chi tiết số tiền ở màn chi tiết hóa đơn (khung \"請求金額\" và các dòng tạm tính / thuế dưới chi tiết quá dài theo chiều dọc)"],
     "a": ["内訳（固定額・ご利用実績の精算・消費税・再請求・請求金額）は、右寄せの1つの表にまとめて縦を短くする（列＝税率＋合計）。明細の下には出さない。「前払い」「後払い」は画面にも請求書にも出さない（固定額・ご利用実績の精算）", "Gộp phần chi tiết số tiền (固定額・ご利用実績の精算・消費税・再請求・請求金額) vào 1 bảng căn phải để ngắn theo chiều dọc (cột = thuế suất + tổng). Không hiện dưới chi tiết. Không hiện \"前払い\" / \"後払い\" trên màn hình lẫn hóa đơn (dùng 固定額・ご利用実績の精算)"],
     "src": "hong 承認 2026-10-05（台帳 E 法人Web 版1.1のレビュー ④、受付簿 No.156）"},
    {"date": "2026-10-05", "target": "CW_BILL_001 No.3.7・11.3・24",
     "q": ["請求書の状態の色（確定・請求済み・送付済み）と「請求済」の書き方", "Màu trạng thái hóa đơn (確定・請求済み・送付済み) và cách ghi 「請求済」"],
     "a": ["共通の状態の色の表に従う：確定＝青（発行前）／請求済み＝緑／送付済み＝緑。書き方は「請求済み」", "Theo bảng màu trạng thái chung: 確定 = xanh dương (trước phát hành) / 請求済み = xanh lá / 送付済み = xanh lá. Cách ghi 「請求済み」"],
     "src": "hong 回答 2026-10-05（台帳 E「法人Web 版 1.1 のレビュー 2回目」・受付簿 No.157）"},
    {"date": "2026-10-05", "target": "CW_BILL_001 No.3.7・24",
     "q": ["再請求のバッジの書き方", "Cách ghi badge tái lập hóa đơn"],
     "a": ["再請求した新しい請求書＝「再請求分を含む（INV-旧）」、再請求された古い請求書＝「再請求済み（→INV-新）」", "Hóa đơn mới tái lập = 「再請求分を含む（INV-cũ）」, hóa đơn cũ bị tái lập = 「再請求済み（→INV-mới）」"],
     "src": "hong 回答 2026-10-05（台帳 E「法人Web 版 1.1 のレビュー 2回目」・受付簿 No.157）"},
    {"date": "2026-10-05", "target": "CW_BILL_001 No.3",
     "q": ["請求書一覧に並べ替えの選択を付けるか", "Có thêm lựa chọn sắp xếp cho danh sách hóa đơn không"],
     "a": ["付けない。発行日の降順に固定（同じ日は法人あて → 拠点あて）", "Không thêm. Cố định 発行日 giảm dần (cùng ngày: 法人あて rồi 拠点あて)"],
     "src": "QA レビュー（受付簿 No.157）。Claude の案：hong の確認待ち"},
]

CHANGES = [
    {"ver": "1.4", "date": "2026-10-05", "no": ["2", "2.1", "2.2", "2.4"], "type": "変更",
     "before": ["一覧の検索・ページ送りはコードにまだなく「コードを直す宿題」という注記（demo_ok）", "Tìm kiếm / phân trang của danh sách chưa có trong code, ghi chú demo_ok \"việc sửa code còn tồn\""],
     "after": ["注記を削除。コードは検索（ご請求月・請求先・状態）と 10件ずつのページ送りができている", "Xóa ghi chú. Code đã có tìm kiếm (ご請求月・請求先・状態) và phân trang 10 dòng"],
     "reason": ["注記が古い（コードは直っている）。hong 回答 2026-10-05（受付簿 No.157）：demo_ok を残さない", "Ghi chú đã cũ (code đã sửa). hong trả lời 2026-10-05 (受付簿 No.157): không để lại demo_ok"],
     "impact": ["画面設計書の注記だけ。コードの変更なし", "Chỉ sửa ghi chú trong tài liệu thiết kế. Không đổi code"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "3", "type": "変更",
     "before": ["一覧の説明に「並べ替えあり（P-LIST）」（初期値は発行日の降順）と注記（demo_ok）", "Mô tả danh sách ghi \"có 並べ替え (P-LIST)\" (mặc định 発行日 giảm dần) và ghi chú demo_ok"],
     "after": ["並べ替えの選択は付けず、発行日の降順に固定（同じ日は法人あて → 拠点あて）と明記。注記を削除", "Không có lựa chọn sắp xếp, cố định 発行日 giảm dần (cùng ngày: 法人あて rồi 拠点あて). Xóa ghi chú"],
     "reason": ["QA レビュー：P-LIST の「並べ替え」とコードの食い違い。並べ替えは付けず固定にする案（受付簿 No.157。hong の確認待ち）", "Review QA: lệch giữa \"並べ替え\" của P-LIST và code. Phương án: không thêm sắp xếp, cố định thứ tự (受付簿 No.157, chờ hong xác nhận)"],
     "impact": ["コードの変更なし（billRows が発行日の降順で並べている）", "Không đổi code (billRows đã xếp theo 発行日 giảm dần)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["3.1", "11.4"], "type": "変更",
     "before": ["詳細から一覧へ戻ると、検索条件・ページは初期値に戻る", "Từ chi tiết quay lại danh sách thì điều kiện tìm kiếm / trang về mặc định"],
     "after": ["詳細を開いて戻ると、検索条件・ページ・件数を戻す（P-LIST。棚卸一覧と同じ）", "Mở chi tiết rồi quay lại thì khôi phục điều kiện tìm kiếm, trang và số dòng (P-LIST, giống 棚卸一覧)"],
     "reason": ["QA レビュー（P-LIST の決まりと食い違い）。hong 回答 2026-10-05（受付簿 No.157）", "Review QA (lệch với quy tắc P-LIST). hong trả lời 2026-10-05 (受付簿 No.157)"],
     "impact": ["コード：app/corp/bills/page.tsx がタブの中（sessionStorage）に検索条件・ページ・件数を覚える", "Code: app/corp/bills/page.tsx lưu điều kiện tìm kiếm / trang / số dòng trong tab (sessionStorage)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["2.3", "3.7", "4", "11.3", "24"], "type": "変更",
     "before": ["状態の名前は「請求済」。確定と請求済が同じ緑（コード）。再請求のバッジは新旧どちらも「再請求（INV-…）」", "Tên trạng thái 「請求済」. 確定 và 請求済 cùng màu xanh lá (code). Badge tái lập cả hóa đơn mới và cũ đều là 「再請求（INV-…）」"],
     "after": ["状態の名前は「請求済み」。色は共通の状態の色の表に従う（確定＝青／請求済み＝緑）。再請求のバッジは、再請求した新しい請求書＝「再請求分を含む（INV-旧）」、再請求された古い請求書＝「再請求済み（→INV-新）」", "Tên trạng thái 「請求済み」. Màu theo bảng màu trạng thái chung (確定 = xanh dương / 請求済み = xanh lá). Badge tái lập: hóa đơn mới tái lập = 「再請求分を含む（INV-cũ）」, hóa đơn cũ bị tái lập = 「再請求済み（→INV-mới）」"],
     "reason": ["hong 回答 2026-10-05（版 1.1 のレビュー 2回目・受付簿 No.157）", "hong trả lời 2026-10-05 (review bản 1.1 lần 2, 受付簿 No.157)"],
     "impact": ["コード：lib/format/status.ts（確定を「予定・これから」＝青に、請求済み・送付済みを緑に。運営Web の請求で「確定」を出すバッジも青になる）、lib/corp/docs（BillState・billTone・rebillBadge）、拠点詳細・法人情報の請求タブの表記（lib/corp/sites）。共通データの子契約の billStatus「請求済」は変えない（運営Web の画面を壊さないため。法人Web の表示だけ「請求済み」）。CSV の「状態」の値も「請求済み」", "Code: lib/format/status.ts (確定 sang nhóm 予定 = xanh dương; 請求済み・送付済み xanh lá; badge 「確定」 ở 請求 của 運営Web cũng thành xanh dương), lib/corp/docs (BillState・billTone・rebillBadge), cách ghi ở tab hóa đơn của chi tiết chi nhánh / 法人情報 (lib/corp/sites). Giữ nguyên billStatus 「請求済」 của hợp đồng con trong dữ liệu chung (để không hỏng màn hình 運営Web); chỉ hiển thị trên 法人Web là 「請求済み」. Giá trị cột 「状態」 của CSV cũng là 「請求済み」"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "3.8", "type": "変更",
     "before": ["送付済みのバッジの色は青（説明）。コードも青（info）", "Màu badge 送付済み là xanh dương (mô tả); code cũng xanh dương (info)"],
     "after": ["送付済みのバッジは緑（共通の状態の色の表：送付済み＝緑）", "Badge 送付済み màu xanh lá (bảng màu trạng thái chung: 送付済み = xanh lá)"],
     "reason": ["hong 回答 2026-10-05（版 1.1 のレビュー 2回目・受付簿 No.157）", "hong trả lời 2026-10-05 (review bản 1.1 lần 2, 受付簿 No.157)"],
     "impact": ["コード：一覧・詳細のバッジを success に（共通の表に「送付済み」を追加）", "Code: badge ở danh sách / chi tiết là success (thêm 「送付済み」 vào bảng chung)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "9", "type": "変更",
     "before": ["請求書が1通もないときも、検索で0件のときも I01「表示するデータがありません。」", "Cả khi chưa có hóa đơn nào lẫn khi tìm kiếm ra 0 dòng đều hiện I01 \"表示するデータがありません。\""],
     "after": ["請求書が1通もないときは I227「まだ請求書はありません。／請求書は、毎月25日の確定のあと、翌月1日にお送りします。」。検索で0件のときは I01", "Khi chưa có hóa đơn nào hiện I227 \"まだ請求書はありません。\"; khi tìm kiếm ra 0 dòng hiện I01"],
     "reason": ["QA レビュー（「まだない」と「検索で0件」を同じ文言にしない）。hong 回答 2026-10-05（受付簿 No.157）", "Review QA (không dùng cùng một câu cho \"chưa có\" và \"tìm ra 0 dòng\"). hong trả lời 2026-10-05 (受付簿 No.157)"],
     "impact": ["共通メッセージに I227 を追加。コード：app/corp/bills/page.tsx", "Thêm I227 vào thông điệp chung. Code: app/corp/bills/page.tsx"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["3", "26"], "type": "追加",
     "after": ["読み込めなかったとき（通信・サーバーのエラー）の表示：白い画面にせず、E346「読み込めませんでした。／時間をおいて再度お試しください。」と「再読み込み」ボタンを出す（請求書詳細では「見つかりません」E328 とは別。一覧へ戻るボタンも）。読み込み中は「読み込み中…」", "Hiển thị khi không tải được dữ liệu (lỗi mạng / máy chủ): không để trắng màn hình mà hiện E346 kèm nút 「再読み込み」 (ở chi tiết hóa đơn khác với 「見つかりません」 E328, có thêm nút về danh sách). Khi đang tải hiện 「読み込み中…」"],
     "reason": ["QA レビュー（API エラーで白い画面・詳細でエラーと「見つかりません」が区別されない）。hong 回答 2026-10-05（受付簿 No.157）", "Review QA (lỗi API làm trắng màn hình; ở chi tiết không phân biệt lỗi với 「見つかりません」). hong trả lời 2026-10-05 (受付簿 No.157)"],
     "impact": ["コード：app/corp/_docs/ds.tsx に LoadingState・LoadError を追加。E346 は共通メッセージの既存の文言。画像はない（見本データではエラーを起こせない）", "Code: thêm LoadingState・LoadError vào app/corp/_docs/ds.tsx. E346 là câu có sẵn trong thông điệp chung. Không có ảnh (dữ liệu mẫu không tạo được lỗi)"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["13.2", "13.5", "13.6", "13.7", "13.8", "13.9"], "type": "変更",
     "before": ["「請求書の情報」は 9欄（番号・ご請求月・宛先・発行日・入金期限・支払方法・固定額の対象・ご利用実績の精算の対象・請求書の送付先）を1列に並べる（13.1〜13.9）", "「請求書の情報」 9 ô (số, tháng, nơi nhận, ngày phát hành, hạn, phương thức, kỳ 固定額, kỳ 精算, nơi gửi) xếp 1 cột (13.1〜13.9)"],
     "after": ["番号・ご請求月・宛先は上の見出しにあるので外し、6欄（13.1 発行日・13.2 入金期限・13.3 支払方法・13.4 固定額の対象・13.5 ご利用実績の精算の対象・13.6 請求書の送付先）を左の枠に2列で出す。13.7〜13.9 は欠番", "Bỏ số / tháng / nơi nhận vì đã có ở tiêu đề; còn 6 ô (13.1 ngày phát hành, 13.2 hạn thanh toán, 13.3 phương thức, 13.4 kỳ 固定額, 13.5 kỳ 精算, 13.6 nơi gửi) hiện 2 cột ở khung trái. 13.7〜13.9 để trống số"],
     "reason": ["縦に長いため。請求金額の表を右の枠に置いて2列にした（台帳 F・版 1.1 のレビュー④）", "Do trang quá dài. Đặt bảng 請求金額 ở khung phải thành 2 cột (台帳 F, review bản 1.1 ④)"],
     "impact": ["項目番号を付け直す（旧 13.2 発行日 → 13.1、旧 13.5 支払方法 → 13.3 など）。内容は変えない", "Đánh lại số mục (13.2 発行日 cũ → 13.1, 支払方法 cũ → 13.3 …). Nội dung không đổi"]},
    {"ver": "1.3", "date": "2026-10-05", "no": "16.13", "type": "削除",
     "before": ["明細の注記（費目は請求書に載る名前・税抜・消費税の計算・プラン料金の2行／1行・再請求）", "Ghi chú của 明細 (tên khoản mục, chưa thuế, cách tính thuế, 2 dòng / 1 dòng phí gói, 再請求)"],
     "after": ["削除（注記は一覧・詳細の下の箇条書きにまとめ、「税率の例は書かない」）", "Bỏ (ghi chú gộp thành danh sách gạch đầu dòng dưới trang, không nêu ví dụ thuế suất)"],
     "reason": ["税率の直書きをやめるため。台帳「請求書は税率マスタのどの率でも」", "Bỏ ghi trực tiếp thuế suất. 台帳 \"hóa đơn dùng mọi thuế suất của master\""],
     "impact": ["詳細の明細の下の注記の文言を短くする", "Rút gọn câu ghi chú dưới 明細"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["2", "2.1", "3"], "type": "変更", "before": ["見出し「発行した請求書」／検索の項目名「請求月」", "Tiêu đề \"発行した請求書\" / nhãn tìm \"請求月\""], "after": ["見出し「請求書一覧」／検索の項目名「ご請求月」（表の列と同じ名前）", "Tiêu đề \"請求書一覧\" / nhãn tìm \"ご請求月\" (trùng tên cột của bảng)"], "reason": ["「発行した請求書」は使わない。条件と列の名前を揃える", "Không dùng \"発行した請求書\"; thống nhất tên điều kiện và tên cột"], "impact": ["カードの見出し・検索の選択肢の先頭（ご請求月：すべて）・CSV の条件名を変える。法人情報・拠点詳細の請求タブの見出しも「請求書一覧」にする", "Đổi tiêu đề thẻ, lựa chọn đầu của ô tìm (ご請求月：すべて) và tên điều kiện trong CSV. Tiêu đề ở tab hóa đơn của 法人情報 / 拠点詳細 cũng thành \"請求書一覧\""]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["1.3"], "type": "変更", "before": ["0件のときもボタンが押せる", "Khi 0 dòng nút vẫn bấm được"], "after": ["0件のときは押せない。拠点アカウントは自分の拠点の明細だけを CSV に出す", "Khi 0 dòng thì không bấm được. Tài khoản chi nhánh chỉ xuất các dòng của chi nhánh mình"], "reason": ["P-CSV-OUT（0件は出力しない）。他拠点の明細を CSV に漏らさない", "P-CSV-OUT (0 dòng thì không xuất). Không để lộ dòng của chi nhánh khác trong CSV"], "impact": ["ボタンに disabled を付け、サーバーの出力の絞り込み（lib/server/access.ts）で拠点アカウントの法人あて請求書の明細を自分の拠点だけにする", "Thêm disabled cho nút; ở phía server (lib/server/access.ts) lọc các dòng của hóa đơn 法人あて của tài khoản chi nhánh chỉ còn chi nhánh mình"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["4"], "type": "変更", "before": ["状態の説明：「確定」は25日に確定した発行前の請求書、「請求済」は発行済みの請求書", "Giải thích trạng thái: \"確定\" là hóa đơn chốt ngày 25 trước phát hành, \"請求済\" là hóa đơn đã phát hành"], "after": ["「請求済」＝請求書をメールでお送りしたもの、「確定」＝請求内容が確定済みでまだお送りしていないもの", "\"請求済\" = hóa đơn đã gửi qua email, \"確定\" = nội dung hóa đơn đã chốt nhưng chưa gửi"], "reason": ["Bill One での送付と状態の関係を、お客様にわかる言葉で", "Nói quan hệ giữa việc gửi qua Bill One và trạng thái bằng từ ngữ dễ hiểu cho khách"], "impact": ["一覧の注記の文言だけ", "Chỉ đổi câu chữ ghi chú dưới danh sách"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["10"], "type": "変更", "before": ["トースト S210（意味が通らない番号）", "Toast S210 (số không khớp)"], "after": ["トースト S12「CSVを出力しました（{n}行・{ファイル名}）。」。共通メッセージ S12 の文言を実際の表示に合わせた", "Toast S12 \"CSVを出力しました（{n}行・{tên file}）。\". Đã sửa câu S12 trong thông điệp chung cho khớp với hiển thị thực tế"], "reason": ["S210 は誤り。CSV出力の完了は S12（_共通_メッセージ.py）。コードのトースト（行数とファイル名）と文言を一致させた", "S210 là nhầm; thông báo hoàn tất xuất CSV là S12 (_共通_メッセージ.py). Thống nhất câu chữ với toast của code (số dòng và tên file)"], "impact": ["_共通_メッセージ.py の S12（日本語・ベトナム語）を更新。ほかの画面の CSV出力のトーストも同じ文言になる", "Cập nhật S12 (tiếng Nhật và Việt) trong _共通_メッセージ.py. Toast xuất CSV của các màn hình khác cũng cùng câu"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["11.3"], "type": "変更", "before": ["宛先の説明は No.13.4 にあった", "Giải thích nơi nhận nằm ở No.13.4"], "after": ["宛先・ご請求月は見出し（11.3）に出し、宛先の説明もここに移した", "Nơi nhận và tháng hóa đơn hiển thị ở tiêu đề (11.3), phần giải thích nơi nhận cũng chuyển về đây"], "reason": ["請求書の情報の欄と見出しで同じ項目が重なっていたため", "Vì ô \"請求書の情報\" và tiêu đề trùng cùng một mục"], "impact": ["説明文の移動だけ", "Chỉ chuyển câu giải thích"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["13"], "type": "変更", "before": ["請求書の情報は3列×3行（番号・発行日・ご請求月・宛先・送付先・支払方法・入金期限・固定額の対象・ご利用実績の精算の対象）", "\"請求書の情報\" 3 cột × 3 hàng (số, ngày phát hành, tháng, nơi nhận, nơi gửi, thanh toán, hạn, đối tượng 固定額, kỳ ご利用実績の精算)"], "after": ["4列×2行。請求書番号・ご請求月・宛先は見出しにあるため外す（6項目）。送付先は3列ぶんの幅", "4 cột × 2 hàng. Bỏ số hóa đơn, tháng hóa đơn, nơi nhận vì đã có ở tiêu đề (còn 6 mục). Nơi gửi rộng bằng 3 cột"], "reason": ["見出しと重なる項目を外し、縦に短くする", "Bỏ các mục trùng với tiêu đề và rút ngắn theo chiều dọc"], "impact": ["docs.css の .cb-g4（4列）を使う（スマホは1列）。項目番号は 13.1〜13.6 に振り直し（旧 13.1・13.3・13.4 は削除、旧 13.2→13.1、13.7→13.2、13.6→13.3、13.8→13.4、13.9→13.5、13.5→13.6）", "Dùng .cb-g4 (4 cột) trong docs.css (điện thoại 1 cột). Đánh số lại 13.1〜13.6 (xóa 13.1, 13.3, 13.4 cũ; 13.2→13.1, 13.7→13.2, 13.6→13.3, 13.8→13.4, 13.9→13.5, 13.5→13.6 cũ)"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["13.1", "13.3", "13.4"], "type": "削除", "reason": ["旧 13.1 請求書番号・旧 13.3 ご請求月・旧 13.4 宛先：見出し（No.11.2・11.3）に出しているため、情報の欄では重ねない", "13.1 (số hóa đơn), 13.3 (tháng hóa đơn), 13.4 (nơi nhận) cũ: đã hiển thị ở tiêu đề (No.11.2, 11.3) nên không lặp lại trong ô thông tin"], "impact": ["旧の番号を指す（上の No.13 の項目番号の振り直しも参照）。新しい 13.1・13.3・13.4 は別の項目（発行日・支払方法・固定額の対象）", "Chỉ các số cũ (xem thêm việc đánh số lại ở No.13 phía trên). 13.1, 13.3, 13.4 mới là mục khác (ngày phát hành, thanh toán, đối tượng 固定額)"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["15"], "type": "変更", "before": ["「請求金額」は固定額・ご利用実績の精算・消費税・再請求・請求金額を入力欄（Ro）で縦に並べた枠。明細の下にも小計・税率ごとの対象額・消費税・請求金額の行", "\"請求金額\" là khung xếp dọc các ô (Ro) 固定額・ご利用実績の精算・消費税・再請求・請求金額. Dưới chi tiết còn các dòng tạm tính, số tiền chịu thuế theo thuế suất, thuế, tổng hóa đơn"], "after": ["「請求金額」は1つの表（右寄せ・縦に短く）。列＝請求書の税率（小さい率から）＋合計。行＝固定額（税抜）・ご利用実績の精算（税抜）・小計（税抜）・消費税・再請求（税込）・請求金額（税込）。明細は下（No.16）", "\"請求金額\" là 1 bảng (căn phải, ngắn theo chiều dọc). Cột = thuế suất của hóa đơn (từ nhỏ) + 合計. Hàng = 固定額（税抜）・ご利用実績の精算（税抜）・小計（税抜）・消費税・再請求（税込）・請求金額（税込）. Chi tiết ở dưới (No.16)"], "reason": ["請求金額と明細の下の合計が二重で縦に長い（hong 承認 2026-10-05 版1.1レビュー ④）。税率を8%・10%に固定せず請求書の率で列を作る", "Số tiền hiển thị trùng 2 chỗ nên quá dài theo chiều dọc (hong duyệt 2026-10-05, review bản 1.1 ④). Cột thuế suất tạo từ thuế suất của hóa đơn, không cố định 8%・10%"], "impact": ["請求書詳細の表示だけ（金額の計算は運営Web の請求書と同じ）。区分×税率の集計（byKind）を詳細のデータに足し、消費税の四捨五入は lib/domain/invoiceTax.ts の taxOfRate にそろえた", "Chỉ đổi hiển thị của chi tiết hóa đơn (cách tính tiền giống hóa đơn 運営Web). Thêm tổng hợp phân loại × thuế suất (byKind) vào dữ liệu chi tiết; làm tròn thuế thống nhất theo taxOfRate trong lib/domain/invoiceTax.ts"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["15.1", "15.2", "15.3", "15.4", "15.5", "15.6", "15.7"], "type": "追加", "after": ["表の見出し（税率の列・合計）／固定額（税抜）／ご利用実績の精算（税抜）／小計（税抜）／消費税／再請求（税込）／請求金額（税込）", "Hàng tiêu đề bảng (cột thuế suất, tổng) / 固定額（税抜）/ ご利用実績の精算（税抜）/ 小計（税抜）/ 消費税 / 再請求（税込）/ 請求金額（税込）"], "reason": ["No.15 を1つの表にしたため、行ごとに項目を立てた", "Vì No.15 thành 1 bảng nên lập mục cho từng hàng"], "impact": ["新しい項目。旧 15.1〜15.5（固定額・ご利用実績の精算・消費税・再請求（税込）・請求金額（税込）の入力欄）は削除", "Mục mới. 15.1〜15.5 cũ (các ô nhập 固定額・ご利用実績の精算・消費税・再請求（税込）・請求金額（税込）) bị xóa"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["15.1", "15.2", "15.3", "15.4", "15.5"], "type": "削除", "reason": ["旧 15.1 固定額・旧 15.2 ご利用実績の精算・旧 15.3 消費税・旧 15.4 再請求（税込）・旧 15.5 請求金額（税込）の入力欄：No.15 の表の行（新 15.2〜15.7）に置き換えた", "15.1 固定額, 15.2 ご利用実績の精算, 15.3 消費税, 15.4 再請求（税込）, 15.5 請求金額（税込） cũ (các ô nhập): được thay bằng các hàng của bảng No.15 (15.2〜15.7 mới)"], "impact": ["旧の番号を指す。新 15.1〜15.5 は上の追加の項目", "Chỉ các số cũ. 15.1〜15.5 mới là các mục thêm ở trên"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["16", "16.1"], "type": "変更", "before": ["明細の列：区分・（拠点）・費目・対象・数量・税抜金額・税率。区分は列。区分名に「（前払い）（後払い）」が付くことがあり、再請求の行も区分が別名", "Cột chi tiết: 区分・(chi nhánh)・費目・対象・数量・税抜金額・税率. 区分 là một cột, tên có thể kèm \"（前払い）（後払い）\"; dòng tái lập có phân loại riêng"], "after": ["列：（拠点）・費目・数量・税抜金額・税率。区分（固定額／ご利用実績の精算／調整）は灰色の見出しの行。「前払い」「後払い」は出さない", "Cột: (chi nhánh)・費目・数量・税抜金額・税率. 区分 (固定額 / ご利用実績の精算 / 調整) là hàng tiêu đề xám. Không hiện \"前払い\" / \"後払い\""], "reason": ["縦に短く・区分を見出しにして見やすくする（hong 承認 2026-10-05 版1.1レビュー ④。台帳 B：前払い・後払いは出さない）", "Ngắn theo chiều dọc, dùng phân loại làm tiêu đề cho dễ nhìn (hong duyệt 2026-10-05, review bản 1.1 ④. 台帳 B: không hiện 前払い・後払い)"], "impact": ["明細の表示だけ。再請求は区分「調整」の行（バッジ「再請求」）。demo_ok（コードが追いついていない）の注記は不要になった", "Chỉ đổi hiển thị chi tiết. 再請求 là dòng thuộc phân loại \"調整\" (badge \"再請求\"). Chú thích demo_ok (code chưa theo kịp) không còn cần"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["16.4", "16.5", "16.6", "16.7", "16.8"], "type": "変更", "before": ["旧 16.5 数量・16.6 税抜金額・16.7 税率・16.8 再請求の行・16.13 明細の注記", "16.5 数量, 16.6 税抜金額, 16.7 税率, 16.8 再請求の行, 16.13 明細の注記 cũ"], "after": ["番号を振り直し：数量 16.4・税抜金額 16.5・税率 16.6・再請求の行 16.7・明細の注記 16.8。税率は「再請求＝税込のまま」。注記から「企業負担分・ご利用実績の精算は 8%、それ以外は 10%」を外し、「10%」の既定表示もなくした", "Đánh số lại: 数量 16.4, 税抜金額 16.5, 税率 16.6, dòng tái lập 16.7, ghi chú 16.8. Thuế suất của dòng tái lập là \"税込のまま\". Bỏ câu \"企業負担分・ご利用実績の精算は 8%、それ以外は 10%\" khỏi ghi chú và bỏ hiển thị mặc định \"10%\""], "reason": ["税率マスタのどの率でも請求できる（台帳 E 2026-10-05）。画面に税率の数字を直書きしない", "Có thể lập hóa đơn với mọi thuế suất của master (台帳 E 2026-10-05). Không viết cứng con số thuế suất trên màn hình"], "impact": ["旧 16.4 対象・旧 16.9〜16.12（小計・税率ごとの対象額・消費税・再請求・請求金額の行）は削除（対象は No.13.4・13.5 と同じ内容で、金額の行は No.15 の表に移した）", "Xóa 16.4 対象 và 16.9〜16.12 cũ (các dòng tạm tính, số tiền chịu thuế theo thuế suất, thuế, tái lập, tổng hóa đơn): 対象 trùng với No.13.4・13.5, các dòng số tiền đã chuyển sang bảng No.15"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["16.4", "16.9", "16.10", "16.11", "16.12"], "type": "削除", "reason": ["旧 16.4 対象（No.13.4・13.5 と重なる）・旧 16.9 小計・旧 16.10 税率ごとの対象額・消費税・旧 16.11 再請求・旧 16.12 請求金額：明細の表から外し、No.15 の表へ", "16.4 対象 cũ (trùng No.13.4・13.5), 16.9 tạm tính, 16.10 số tiền chịu thuế và thuế theo thuế suất, 16.11 tái lập, 16.12 tổng hóa đơn cũ: bỏ khỏi bảng chi tiết, chuyển sang bảng No.15"], "impact": ["旧の番号を指す。新 16.4 は数量（旧 16.5）", "Chỉ các số cũ. 16.4 mới là 数量 (16.5 cũ)"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["18"], "type": "変更", "before": ["列：区分・費目・対象・数量・税抜金額・税率", "Cột: 区分・費目・対象・数量・税抜金額・税率"], "after": ["列：費目・数量・税抜金額・税率（区分は見出しの行）", "Cột: 費目・数量・税抜金額・税率 (phân loại là hàng tiêu đề)"], "reason": ["No.16 に合わせた", "Cho khớp No.16"], "impact": ["説明文だけ", "Chỉ đổi câu giải thích"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["19.1"], "type": "追加", "after": ["拠点の画面から法人あての請求書を開いたとき、請求金額の見出しを「請求金額（この拠点の分・参考）」にする", "Khi mở hóa đơn 法人あて từ màn chi nhánh, tiêu đề bảng số tiền là \"請求金額（この拠点の分・参考）\""], "reason": ["hong 承認 2026-10-05 版1.1レビュー ④：法人の請求書の一部であることを表の見出しでわかるようにする", "hong duyệt 2026-10-05 (review bản 1.1 ④): cho biết qua tiêu đề bảng rằng đây chỉ là một phần của hóa đơn pháp nhân"], "impact": ["新しい項目（拠点アカウントの法人あての内訳だけ）", "Mục mới (chỉ với 内訳 hóa đơn 法人あて của tài khoản chi nhánh)"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["16.3"], "type": "変更", "before": ["費目の例「実績精算・後払い分（…）」", "Ví dụ khoản mục \"実績精算・後払い分（…）\""], "after": ["費目の例「ご利用実績の精算（2026/08/21〜2026/09/20）」（見本データの費目名も同じ）", "Ví dụ khoản mục \"ご利用実績の精算（2026/08/21〜2026/09/20）\" (tên khoản mục trong dữ liệu mẫu cũng đổi theo)"], "reason": ["台帳 B・E：「前払い」「後払い」は画面にも請求書にも出さない", "台帳 B・E: không hiện \"前払い\" / \"後払い\" trên màn hình lẫn hóa đơn"], "impact": ["見本データ（lib/domain/seed/billing.ts）の費目名と説明の例だけ", "Chỉ đổi tên khoản mục trong dữ liệu mẫu (lib/domain/seed/billing.ts) và ví dụ trong mô tả"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["3.8", "11.3", "14", "22"], "type": "変更",
     "before": ["Bill One のバッジは 送付済み（青）／送付できませんでした（赤）の2つ。送付できなかったときは送り直しの注記を No.12 に足す", "2 badge Bill One: 送付済み (xanh) / 送付できませんでした (đỏ). Gửi lỗi thì thêm ghi chú gửi lại vào No.12"],
     "after": ["バッジは「送付済み」だけ。送付前・送付できなかったときは「—」（法人にエラーは出さない。運営が直して送り直す）", "Chỉ badge \"送付済み\". Chưa gửi / gửi lỗi là \"—\" (không hiện lỗi cho pháp nhân; 運営 sửa và gửi lại)"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー ⑧：Bill One の送付エラーは法人に出さない", "hong trả lời 2026-10-05 (review bản 1.0) ⑧: không hiện lỗi gửi Bill One cho pháp nhân"],
     "impact": ["一覧・詳細の送付のバッジを 送付済み だけにし、エラー・準備中・開封済みと送付の記録の表、送り直しの注記を法人Web から外す（受付簿 No.153）", "Badge gửi ở danh sách / chi tiết chỉ còn 送付済み; bỏ lỗi, 準備中, 開封済み, bảng nhật ký và ghi chú gửi lại khỏi 法人Web (受付簿 No.153)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["23"], "type": "削除",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー ⑧：送付できなかったときの送り直しの案内は法人に出さない", "hong trả lời 2026-10-05 (review bản 1.0) ⑧: không hiện thông báo gửi lại cho pháp nhân"],
     "impact": ["p.note「送り直します」を外す", "Bỏ p.note \"送り直します\""]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["26"], "type": "変更",
     "before": ["E328 を枠（EmptyState）で出し、「戻る」で一覧へ", "Hiện E328 trong khung (EmptyState), \"戻る\" về danh sách"],
     "after": ["標準の空表示（EmptyState）：アイコン・タイトル「請求書が見つかりません」・本文（E328）・ボタン「請求書の一覧へ戻る」。見出しの「戻る」は出さない", "Khung trống chuẩn (EmptyState): icon, tiêu đề \"請求書が見つかりません\", nội dung (E328), nút \"請求書の一覧へ戻る\". Không hiện \"戻る\" ở tiêu đề"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー ⑨：見つからないときは標準の空表示（戻るボタンつき）。E328 の文言もタイトルに合わせた", "hong trả lời 2026-10-05 (review bản 1.0) ⑨: không tìm thấy thì dùng khung trống chuẩn (có nút quay lại). Câu E328 cũng sửa theo tiêu đề"],
     "impact": ["EmptyState の部品にアイコン・本文・ボタンを足し、見つからないときはそれだけを出す（受付簿 No.153）", "Thêm icon, nội dung, nút vào EmptyState và chỉ hiện nó khi không tìm thấy (受付簿 No.153)"]},
]

HIDE_ALWAYS = [".es-demo-bar", ".es-chatbot", ".es-chatbot__fab", "#es-review"]
STATIC_CSS = ".corp{height:auto!important}.corp-main{overflow:visible!important}.es-sidenav{height:auto!important;min-height:100vh}"
VIEWER_CSS = STATIC_CSS

SCREENS = [
    {"code": "CW_BILL_001", "ja": "請求書", "vi": "Hóa đơn"},
    {"code": "CW_BILL_002", "ja": "請求書詳細", "vi": "Chi tiết hóa đơn"},
]

_JS_CSV = "const cb=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='CSV出力'); cb&&cb.click(); await new Promise(r=>setTimeout(r,800)); "

VIEWS = [
    # ============================================================ CW_BILL_001 請求書（一覧）
    {"id": "001", "code": "CW_BILL_001", "state": ["法人アカウント", "Tài khoản pháp nhân"],
     "url": "/corp/bills", "full": True, "wait": 600, "setup": "",
     "note": ["法人アカウント（CU00001）。請求先が法人の請求書（法人あて）と、請求先が拠点の請求書（拠点あて）をすべて出す。",
              "Tài khoản pháp nhân (CU00001). Hiện mọi hóa đơn gửi pháp nhân (法人あて) và hóa đơn gửi chi nhánh (拠点あて)."],
     "items": [
         {"no": "1", "ja": "ページ見出し", "vi": "Tiêu đề trang", "sel": ".cb-bills", "kind": "area", "trig": "view"},
         {"no": "1.1", "ja": "画面名", "vi": "Tên màn hình", "sel": "h1.es-pagehead__title", "kind": "label", "trig": "view",
          "init": ["請求書", "\"請求書\""]},
         {"no": "1.2", "ja": "法人名・権限・件数", "vi": "Tên pháp nhân, quyền, số lượng", "sel": ".cb-bills .stat", "kind": "label", "trig": "view",
          "init": ["株式会社サンプル　権限 法人アカウント（請求先が法人の請求書と、請求先が拠点の請求書をすべて表示）　件数 n件", "株式会社サンプル, quyền: tài khoản pháp nhân (hiện mọi hóa đơn gửi pháp nhân và gửi chi nhánh), số lượng n件"],
          "detail": ["法人アカウント＝法人名と見える範囲、拠点アカウント＝拠点名と「この拠点の請求書だけ表示」。件数は検索条件に合う請求書の数。", "Tài khoản pháp nhân = tên pháp nhân và phạm vi xem; tài khoản chi nhánh = tên chi nhánh và \"この拠点の請求書だけ表示\". Số lượng = số hóa đơn khớp điều kiện tìm."]},
         {"no": "1.3", "ja": "CSV出力", "vi": "Nút \"CSV出力\"", "sel": "button::CSV出力", "kind": "button", "trig": "click", "pattern": "P-CSV-OUT", "err": ["S12"],
          "detail": ["検索条件に合う請求書の全件を CSV に出す（1行＝請求書の1明細）。0件のときはボタンを押せない（グレー）。拠点アカウントは、法人あての請求書でも自分の拠点の明細だけを出す。列：請求書番号・発行日・ご請求月・請求先・金額（税込）・この拠点の分（参考）・入金期限・状態・最終請求書・請求書のメール送付（Bill One）＋明細の列（CSV入出力_定義）。",
                     "Xuất CSV toàn bộ hóa đơn khớp điều kiện tìm (1 dòng = 1 dòng chi tiết của hóa đơn). Khi 0 dòng thì nút bị vô hiệu (màu xám). Tài khoản chi nhánh chỉ xuất các dòng của chi nhánh mình, kể cả với hóa đơn 法人あて. Cột: 請求書番号・発行日・ご請求月・請求先・金額（税込）・この拠点の分（参考）・入金期限・状態・最終請求書・請求書のメール送付（Bill One） + các cột chi tiết (CSV入出力_定義)."]},
         {"no": "2", "ja": "検索", "vi": "Tìm kiếm", "sel": "h2::請求書一覧^", "kind": "area", "trig": "view", "pattern": "P-LIST",
          "detail": ["請求月・請求先・状態で絞り込む。「検索」か Enter で反映（P-LIST）。", "Lọc theo 請求月・請求先・状態. Áp dụng khi bấm \"検索\" hoặc Enter (P-LIST)."]},
         {"no": "2.1", "ja": "ご請求月", "vi": "Tháng hóa đơn (ご請求月)", "sel": "h2::請求書一覧^", "kind": "month", "trig": "select", "req": "－", "len": "年月",
          "init": ["指定なし", "Không chỉ định"], "ex": ["2026-10", "Tháng phát hành YYYY-MM"],
          "detail": ["ご請求月（発行月）が一致する請求書。選択肢は「ご請求月：すべて」＋各ご請求月。", "Hóa đơn có tháng hóa đơn (tháng phát hành) trùng. Lựa chọn: \"ご請求月：すべて\" + từng tháng hóa đơn."]},
         {"no": "2.2", "ja": "請求先", "vi": "Nơi nhận hóa đơn", "sel": "h2::請求書一覧^", "kind": "select", "trig": "select", "req": "－", "len": "選択",
          "init": ["すべて", "Tất cả"], "ex": ["法人あて", "Chọn: すべて / 法人あて / 拠点あて（各拠点名）"],
          "cond": ["法人アカウントだけ出す（拠点アカウントは自分の拠点の分だけのため）", "Chỉ hiện với tài khoản pháp nhân (tài khoản chi nhánh chỉ có phần của mình)"]},
         {"no": "2.3", "ja": "状態", "vi": "Trạng thái", "sel": "h2::請求書一覧^", "kind": "select", "trig": "select", "req": "－", "len": "選択",
          "init": ["すべて", "Tất cả"], "ex": ["請求済み", "Chọn: すべて / 確定 / 請求済み"]},
         {"no": "2.4", "ja": "検索", "vi": "Nút \"検索\"", "sel": "h2::請求書一覧^", "kind": "button", "trig": "click",
          "detail": ["条件を反映して1ページ目へ。0件は I01。", "Áp dụng điều kiện và về trang 1. 0 dòng: I01."], "err": ["I01"]},
         {"no": "3", "err": ["E346"], "ja": "請求書一覧", "vi": "Danh sách hóa đơn", "sel": "h2::請求書一覧^2", "kind": "table", "trig": "view", "pattern": "P-LIST",
          "init": ["発行日の降順（同じ日は法人あて → 拠点あて）", "発行日 giảm dần (cùng ngày: 法人あて rồi 拠点あて)"],
          "detail": ["法人アカウント：法人あて（請求先が法人の拠点をまとめた1通）＋拠点あて（請求先が拠点の拠点ごとの1通）。拠点アカウント：自分の拠点の分だけ（請求先が法人なら、法人あての請求書のうちこの拠点の分＝内訳・参考）。取消した請求書は出さない。1ページ 10件（P-LIST）。並べ替えの選択はなく、発行日の降順に固定（同じ日は法人あて → 拠点あて。hong 2026-10-05・受付簿 No.157）。 読み込めなかったとき（通信・サーバーのエラー）は白い画面にせず、E346「読み込めませんでした。／時間をおいて再度お試しください。」と「再読み込み」ボタンを出す（画像なし：見本データではエラーを起こせない）。", "Tài khoản pháp nhân: 法人あて (1 hóa đơn gộp các chi nhánh có nơi nhận = pháp nhân) + 拠点あて (từng chi nhánh có nơi nhận = chi nhánh). Tài khoản chi nhánh: chỉ phần của mình (nơi nhận = pháp nhân thì là phần chi nhánh trong hóa đơn 法人あて = 内訳, tham khảo). Không hiện hóa đơn đã hủy. 10 dòng / trang (P-LIST). Không có lựa chọn sắp xếp, cố định theo 発行日 giảm dần (cùng ngày: 法人あて rồi 拠点あて; hong 2026-10-05, 受付簿 No.157). Khi không tải được dữ liệu (lỗi mạng / máy chủ) thì không để trắng màn hình mà hiện E346 \"読み込めませんでした。\" kèm nút \"再読み込み\" (không có ảnh: dữ liệu mẫu không tạo được lỗi)."]},
         {"no": "3.1", "ja": "請求書番号", "vi": "Số hóa đơn", "sel": "th::請求書番号", "kind": "link", "trig": "click",
          "detail": ["INV-YYYYMM + 4桁。押すと請求書詳細（CW_BILL_002）へ。最終請求書（解約した拠点の最後の1通）は番号の下に灰色のバッジ「最終請求書」。 詳細を開いて戻ると、検索条件・ページ・件数を戻す（P-LIST）。", "INV-YYYYMM + 4 chữ số. Bấm để mở chi tiết (CW_BILL_002). Hóa đơn cuối (của chi nhánh đã hủy) có badge xám \"最終請求書\" dưới số. Mở chi tiết rồi quay lại thì khôi phục điều kiện tìm kiếm, trang và số dòng (P-LIST)."]},
         {"no": "3.2", "ja": "発行日", "vi": "Ngày phát hành", "sel": "th::発行日", "kind": "label", "trig": "view",
          "detail": ["YYYY-MM-DD。毎月1日に発行。", "YYYY-MM-DD. Phát hành ngày 1 hằng tháng."]},
         {"no": "3.3", "ja": "ご請求月", "vi": "Tháng hóa đơn", "sel": "th::ご請求月", "kind": "label", "trig": "view",
          "detail": ["YYYY-MM（発行月）。", "YYYY-MM (tháng phát hành)."]},
         {"no": "3.4", "ja": "請求先", "vi": "Nơi nhận hóa đơn", "sel": "th::請求先", "kind": "label", "trig": "view",
          "detail": ["「法人あて（{法人名}）」／「拠点あて（{拠点名}）」／拠点アカウントで請求先が法人：「法人あて（{法人名}）のうち この拠点の分」。", "\"法人あて（{法人名}）\" / \"拠点あて（{拠点名}）\" / tài khoản chi nhánh có nơi nhận = pháp nhân: \"法人あて（{法人名}）のうち この拠点の分\"."]},
         {"no": "3.5", "ja": "金額（税込）", "vi": "Số tiền (gồm thuế)", "sel": "th::金額（税込）", "kind": "label", "trig": "view",
          "detail": ["請求書の合計（税込・再請求を含む）。「n,nnn円」右寄せ。拠点アカウントで請求先が法人の拠点は、法人あての請求書のうちこの拠点の分（税込）を出し、下に「この拠点の分（参考）」。", "Tổng hóa đơn (gồm thuế, gồm tái lập). \"n,nnn円\" căn phải. Tài khoản chi nhánh có nơi nhận = pháp nhân: hiện phần chi nhánh trong hóa đơn 法人あて (gồm thuế), bên dưới ghi \"この拠点の分（参考）\"."]},
         {"no": "3.6", "ja": "入金期限", "vi": "Hạn thanh toán", "sel": "th::入金期限", "kind": "label", "trig": "view",
          "detail": ["YYYY-MM-DD。請求先の支払いの決まり（請求月の27日／翌月27日）。", "YYYY-MM-DD. Theo quy tắc thanh toán của nơi nhận (ngày 27 tháng hóa đơn / ngày 27 tháng sau)."]},
         {"no": "3.7", "ja": "状態", "vi": "Trạng thái", "sel": "th::状態", "kind": "label", "trig": "view",
          "detail": ["バッジ：確定（青・25日に確定、発行前）／請求済み（緑・発行済み）。色は共通の状態の色の表に従う（確定＝青／請求済み＝緑）。前の請求書を再請求した新しい請求書には黄のバッジ「再請求分を含む（INV-旧）」、再請求された古い請求書には黄のバッジ「再請求済み（→INV-新）」を添える（相手の請求書番号つき）。入金済・未入金は出さない。", "Badge: 確定 (xanh dương, chốt ngày 25, trước phát hành) / 請求済み (xanh lá, đã phát hành). Màu theo bảng màu trạng thái chung (確定 = xanh dương / 請求済み = xanh lá). Hóa đơn mới tái lập hóa đơn cũ có badge vàng \"再請求分を含む（INV-cũ）\", hóa đơn cũ bị tái lập có badge vàng \"再請求済み（→INV-mới）\" (kèm số hóa đơn đối ứng). Không hiện 入金済・未入金."]},
         {"no": "3.8", "ja": "請求書のメール送付（Bill One）", "vi": "Gửi hóa đơn qua email (Bill One)", "sel": "th::メール送付", "kind": "label", "trig": "view",
          "detail": ["Bill One で送付できた請求書だけ緑のバッジ「送付済み」。送付前・送付できなかった請求書は「—」（送付のエラーは法人に出さない。ESキッチンが宛先を直して送り直す）。", "Chỉ hóa đơn đã gửi qua Bill One có badge xanh lá \"送付済み\". Chưa gửi / gửi lỗi là \"—\" (không hiện lỗi gửi cho pháp nhân; ESキッチン sửa nơi nhận và gửi lại)."]},
         {"no": "4", "ja": "一覧の注記", "vi": "Ghi chú dưới danh sách", "sel": "ul.cb-notes", "kind": "label", "trig": "view",
          "detail": ["請求書番号を押すと明細を確認できる／毎月20日までのご利用分を集計し、25日に確定、翌月1日にお送りする／請求書（PDF）は Bill One からメールで届く／固定額＝ご利用月の前にお支払いいただく月額、ご利用実績の精算＝在庫の差額などをあとからご精算いただくもの／状態の「請求済み」＝請求書をメールでお送りしたもの、「確定」＝請求内容が確定済みでまだお送りしていないもの／法人アカウント：請求先が法人の拠点の分は法人あてにまとめて入り、請求先が拠点の拠点は拠点ごとに請求書が出る。",
                     "Bấm số hóa đơn để xem chi tiết / Tổng hợp sử dụng đến ngày 20, chốt ngày 25, gửi ngày 1 tháng sau / PDF hóa đơn gửi qua email từ Bill One / 固定額 = phí tháng trả trước tháng sử dụng, ご利用実績の精算 = chênh lệch tồn kho… thanh toán sau / Trạng thái \"請求済み\" = hóa đơn đã gửi qua email, \"確定\" = nội dung hóa đơn đã chốt nhưng chưa gửi / Tài khoản pháp nhân: chi nhánh có nơi nhận = pháp nhân gộp vào hóa đơn 法人あて, chi nhánh có nơi nhận = chi nhánh có hóa đơn riêng."]},
     ]},
    {"id": "002", "code": "CW_BILL_001", "state": ["拠点アカウント（請求先＝法人・この拠点の分）", "Tài khoản chi nhánh (nơi nhận = pháp nhân, phần của chi nhánh)"],
     "url": "/corp/bills", "full": True, "login": "CU00871", "wait": 600, "setup": "",
     "note": ["拠点アカウント（CU00871 大阪支店・請求先＝法人）。法人あての請求書のうち、この拠点の分だけを内訳（参考）として出す。", "Tài khoản chi nhánh (CU00871 大阪支店, nơi nhận = pháp nhân). Chỉ hiện phần của chi nhánh trong hóa đơn 法人あて (内訳, tham khảo)."],
     "items": [
         {"no": "5", "ja": "拠点名・権限（拠点アカウント）", "vi": "Tên chi nhánh, quyền (tài khoản chi nhánh)", "sel": ".cb-bills .stat", "kind": "label", "trig": "view",
          "init": ["株式会社サンプル 大阪支店　権限 拠点アカウント（この拠点の請求書だけ表示）", "株式会社サンプル 大阪支店, quyền: tài khoản chi nhánh (chỉ hóa đơn của chi nhánh này)"]},
         {"no": "6", "ja": "この拠点の分（参考）", "vi": "Phần của chi nhánh (tham khảo)", "sel": ".es-field__msg::この拠点の分（参考）", "kind": "label", "trig": "view",
          "detail": ["金額の下に出す。請求先が法人の拠点は、法人あての請求書のうちこの拠点の明細の合計（税込）。消費税は拠点の分で税率ごとに四捨五入するため、法人の請求書と1円ずれることがある。", "Hiện dưới số tiền. Chi nhánh có nơi nhận = pháp nhân: tổng các dòng của chi nhánh trong hóa đơn 法人あて (gồm thuế). Thuế làm tròn theo từng thuế suất trên phần chi nhánh nên có thể lệch 1 yên so với hóa đơn pháp nhân."]},
         {"no": "7", "ja": "注記（請求先が法人の拠点）", "vi": "Ghi chú (chi nhánh có nơi nhận = pháp nhân)", "sel": "ul.cb-notes li::この拠点の請求先は法人のため", "kind": "label", "trig": "view",
          "detail": ["「この拠点の請求先は法人のため、請求書は法人あてにまとめて発行されます。金額は、法人あての請求書のうちこの拠点の分（参考・税込）です。」", "\"この拠点の請求先は法人のため、請求書は法人あてにまとめて発行されます。金額は、法人あての請求書のうちこの拠点の分（参考・税込）です。\""]},
     ]},
    {"id": "003", "code": "CW_BILL_001", "state": ["拠点アカウント（請求先＝拠点）", "Tài khoản chi nhánh (nơi nhận = chi nhánh)"],
     "url": "/corp/bills", "full": True, "login": "CU00961", "wait": 600, "setup": "",
     "note": ["拠点アカウント（CU00961 千葉営業所・請求先＝この拠点）。拠点あての請求書だけ。", "Tài khoản chi nhánh (CU00961 千葉営業所, nơi nhận = chi nhánh). Chỉ hóa đơn 拠点あて."],
     "items": [
         {"no": "8", "ja": "請求先「拠点あて」", "vi": "Nơi nhận \"拠点あて\"", "sel": "td::拠点あて", "kind": "label", "trig": "view",
          "detail": ["「拠点あて（{拠点名}）」。金額は請求書の合計そのまま（参考の注記なし）。", "\"拠点あて（{拠点名}）\". Số tiền là tổng hóa đơn (không có ghi chú tham khảo)."]},
     ]},
    {"id": "004", "code": "CW_BILL_001", "state": ["0件", "0 dòng"],
     "url": "/corp/bills", "full": True, "login": "CU00012", "wait": 600, "setup": "",
     "note": ["まだ請求書がないアカウント（見本：CU00071 みちのく商事・お試し 2026-10 から。見本データで請求書がある場合は、検索条件で 0件にして撮る＝その場合は I227 でなく I01）。一覧の中に I227。", "Tài khoản chưa có hóa đơn (mẫu: CU00071 みちのく商事, dùng thử từ 2026-10. Nếu dữ liệu mẫu có hóa đơn thì lọc để ra 0 dòng rồi chụp). Hiện I227 trong danh sách."],
     "items": [
         {"no": "9", "ja": "0件の表示", "vi": "Hiển thị 0 dòng", "sel": ".es-empty", "kind": "label", "trig": "view", "err": ["I227", "I01"],
          "detail": ["請求書が1通もないアカウントは、一覧の中に「まだ請求書はありません。／請求書は、毎月25日の確定のあと、翌月1日にお送りします。」（I227）を出す。検索で0件になったときは I01「表示するデータがありません。」。CSV出力は押せない（P-CSV-OUT）。", "Tài khoản chưa có hóa đơn nào hiện trong danh sách \"まだ請求書はありません。\" (I227). Khi tìm kiếm ra 0 dòng thì hiện I01. Không bấm được CSV出力 (P-CSV-OUT)."]},
     ]},
    {"id": "005", "code": "CW_BILL_001", "state": ["CSV出力", "Xuất CSV"],
     "url": "/corp/bills", "full": True, "wait": 400, "setup": _JS_CSV,
     "note": ["「CSV出力」を押した直後。ファイルを下ろし、トースト S12 を出す。", "Ngay sau khi bấm \"CSV出力\". Tải file và hiện toast S12."],
     "items": [
         {"no": "10", "ja": "CSV出力のトースト", "vi": "Toast xuất CSV", "sel": ".hd-toast", "kind": "toast", "trig": "show", "err": ["S12"],
          "detail": ["S12「CSVを出力しました（{n}行・{ファイル名}）。」（行数とファイル名）。ファイル名は 請求書_<yyyymmdd_hhmm>.csv。", "S12 \"CSVを出力しました（{n}行・{tên file}）。\" (số dòng và tên file). Tên file 請求書_<yyyymmdd_hhmm>.csv."]},
     ]},
    # ============================================================ CW_BILL_002 請求書詳細
    {"id": "006", "code": "CW_BILL_002", "state": ["法人あて（拠点列・再請求あり）", "Gửi pháp nhân (có cột chi nhánh, có tái lập)"],
     "url": "/corp/bills/INV-2026100001?from=bills", "full": True, "wait": 600, "setup": "",
     "note": ["法人あての請求書（INV-2026100001・2026-10 発行）。請求先が法人の拠点（本社・大阪支店）をまとめ、8月発行分（INV-2026080001）の再請求を含む。", "Hóa đơn gửi pháp nhân (INV-2026100001, phát hành 2026-10). Gộp các chi nhánh có nơi nhận = pháp nhân (本社・大阪支店), gồm tái lập hóa đơn tháng 8 (INV-2026080001)."],
     "items": [
         {"no": "11", "ja": "ページ見出し", "vi": "Tiêu đề trang", "sel": ".es-pagehead", "kind": "area", "trig": "view"},
         {"no": "11.1", "ja": "パンくず", "vi": "Breadcrumb", "sel": ".es-breadcrumb", "kind": "link", "trig": "click",
          "detail": ["「請求書 / 請求書詳細」。法人情報・拠点詳細の請求タブから開いたときは「法人情報 / 請求書詳細」「拠点管理 / 拠点詳細 {拠点ID} / 請求書詳細」（?from=）。", "\"請求書 / 請求書詳細\". Mở từ tab hóa đơn của 法人情報 / 拠点詳細 thì là \"法人情報 / 請求書詳細\" hoặc \"拠点管理 / 拠点詳細 {拠点ID} / 請求書詳細\" (?from=)."]},
         {"no": "11.2", "ja": "画面名・請求書番号", "vi": "Tên màn hình, số hóa đơn", "sel": "h1.es-pagehead__title", "kind": "label", "trig": "view",
          "init": ["請求書詳細 INV-2026100001", "\"請求書詳細\" + số hóa đơn INV-2026100001"],
          "detail": ["最終請求書なら番号の右に灰色のバッジ「最終請求書」。", "Hóa đơn cuối có badge xám \"最終請求書\" bên phải số."]},
         {"no": "11.3", "ja": "宛先・ご請求月・状態・送付", "vi": "Nơi nhận, tháng, trạng thái, gửi", "sel": ".es-pagehead .stat", "kind": "label", "trig": "view",
          "init": ["株式会社サンプル 経理部 御中　ご請求月 2026-10　状態 請求済み　再請求分を含む（INV-2026080001）　送付 送付済み", "株式会社サンプル 経理部 御中, ご請求月 2026-10, 状態 請求済み + 再請求分を含む（INV-2026080001）, 送付 送付済み"],
          "detail": ["宛先：法人あて＝請求先法人名 御中／拠点あて＝拠点名 御中／拠点の画面から法人あて＝「{請求先法人名} 御中（法人あてにまとめて発行）」。ご請求月は YYYY-MM。状態は 確定（青）／請求済み（緑）のバッジ（再請求があれば、No.3.7 の黄のバッジ「再請求分を含む（INV-旧）」「再請求済み（→INV-新）」）。送付は Bill One で送付できたときだけバッジ「送付済み」、それ以外は「—」（No.3.8 と同じ）。", "Nơi nhận: 法人あて = tên pháp nhân nhận hóa đơn + 御中 / 拠点あて = tên chi nhánh + 御中 / từ màn chi nhánh mở 法人あて = \"{tên pháp nhân nhận hóa đơn} 御中（法人あてにまとめて発行）\". Tháng hóa đơn dạng YYYY-MM. Trạng thái là badge 確定 (xanh dương) / 請求済み (xanh lá) (có tái lập thì thêm badge vàng \"再請求分を含む（INV-cũ）\" / \"再請求済み（→INV-mới）\" như No.3.7). Gửi: chỉ khi đã gửi qua Bill One mới có badge \"送付済み\", còn lại \"—\" (giống No.3.8)."]},
         {"no": "11.4", "ja": "戻る", "vi": "Nút \"戻る\"", "sel": "button::戻る", "kind": "button", "trig": "click",
          "detail": ["開いた元（請求書の一覧／法人情報の請求タブ／拠点詳細の請求タブ）へ戻る。 一覧から開いたときは、戻ると一覧の検索条件・ページを戻す（P-LIST）。", "Quay về nơi đã mở (danh sách hóa đơn / tab hóa đơn của 法人情報 / tab hóa đơn của 拠点詳細). Khi mở từ danh sách, quay lại thì khôi phục điều kiện tìm kiếm và trang của danh sách (P-LIST)."]},
         {"no": "12", "ja": "Bill One の案内", "vi": "Thông báo về Bill One", "sel": ".es-inline strong::Bill One^2", "kind": "label", "trig": "view",
          "detail": ["「請求書（PDF）は Bill One からお届けします」：この画面は ES STATION に登録されている請求の内容を確認するためのもの。原本（PDF）の受け取り・保存は Bill One からのメールで。拠点の画面から法人あてを開いたときは「法人の請求書の内訳（参考）として、この拠点の分だけを出しています」を足す。",
                     "\"請求書（PDF）は Bill One からお届けします\": màn hình này để xem nội dung hóa đơn đã đăng ký trong ES STATION; nhận / lưu bản gốc (PDF) qua email từ Bill One. Mở hóa đơn 法人あて từ màn chi nhánh thì thêm \"法人の請求書の内訳（参考）として、この拠点の分だけを出しています\"."]},
         {"no": "13", "ja": "請求書の情報", "vi": "Thông tin hóa đơn", "sel": "h2::請求書の情報^2", "kind": "area", "trig": "view",
          "detail": ["4列×2行。請求書番号・ご請求月・宛先・状態・送付は上の見出し（No.11.2・11.3・14）に出しているため、ここでは重ねない。", "Bố cục 4 cột × 2 hàng. Số hóa đơn, tháng hóa đơn, nơi nhận, trạng thái, gửi đã hiển thị ở tiêu đề phía trên (No.11.2, 11.3, 14) nên không lặp lại ở đây."]},
         {"no": "13.1", "ja": "発行日", "vi": "Ngày phát hành", "sel": "label.es-field__label::発行日^", "kind": "label", "trig": "view", "init": ["2026-10-01", "2026-10-01"]},
         {"no": "13.2", "ja": "入金期限", "vi": "Hạn thanh toán", "sel": "label.es-field__label::入金期限^", "kind": "label", "trig": "view", "init": ["2026-10-27", "2026-10-27"]},
         {"no": "13.3", "ja": "支払方法", "vi": "Phương thức thanh toán", "sel": "label.es-field__label::支払方法^", "kind": "label", "trig": "view", "init": ["銀行振込", "銀行振込 (chuyển khoản)"]},
         {"no": "13.4", "ja": "固定額の対象", "vi": "Đối tượng của 固定額", "sel": "label.es-field__label::固定額の対象^", "kind": "label", "trig": "view",
          "init": ["2026-11分", "2026-11分 (chu kỳ tháng 11)"],
          "detail": ["固定額（月額）の対象のサイクル月。", "Chu kỳ tháng mà 固定額 (phí tháng) áp dụng."]},
         {"no": "13.5", "ja": "ご利用実績の精算の対象", "vi": "Kỳ của ご利用実績の精算", "sel": "label.es-field__label::ご利用実績の精算の対象^", "kind": "label", "trig": "view",
          "init": ["2026-08-21〜09-20", "2026-08-21〜09-20"],
          "detail": ["前々月21日〜前月20日。実績精算がない請求書は「—」。", "Từ ngày 21 của 2 tháng trước đến ngày 20 tháng trước. Không có thanh toán thực tế thì \"—\"."]},
         {"no": "13.6", "ja": "請求書の送付先", "vi": "Nơi gửi hóa đơn", "sel": "label.es-field__label::請求書の送付先^", "kind": "label", "trig": "view",
          "init": ["請求担当者：{氏名} ／ {メールアドレス}", "請求担当者：{họ tên} ／ {email}"],
          "detail": ["2行目に3列ぶんの幅で出す。請求担当者の氏名とメールアドレス（Bill One の送付先）。法人あて＝法人の請求担当者、拠点あて＝拠点の請求担当者。", "Hiển thị ở hàng 2, rộng bằng 3 cột. Họ tên và email của 請求担当者 (nơi Bill One gửi). 法人あて = của pháp nhân, 拠点あて = của chi nhánh."]},
         {"no": "14", "ja": "請求書のメール送付（Bill One）", "vi": "Gửi hóa đơn qua email (Bill One)", "sel": ".es-pagehead .stat span::送付", "kind": "label", "trig": "view",
          "detail": ["法人には見出しのバッジ「送付済み」（No.11.3）だけで、この表（日時・状態・内容の記録）は出さない。送付できなかったことも法人には出さない（ESキッチンが宛先を直して送り直す）。",
                     "Pháp nhân chỉ thấy badge \"送付済み\" ở tiêu đề (No.11.3), không hiện bảng này (nhật ký ngày giờ, trạng thái, nội dung). Gửi lỗi cũng không hiện cho pháp nhân (ESキッチン sửa nơi nhận và gửi lại)."]},
         {"no": "15", "ja": "請求金額", "vi": "Số tiền hóa đơn", "sel": "h2::請求金額^2", "kind": "area", "trig": "view",
          "detail": ["請求金額は1つの表（右寄せ・縦に短く）。列＝請求書にある税率（小さい率から。例：8%対象・10%対象）＋合計。行＝固定額（税抜）・ご利用実績の精算（税抜）・小計（税抜）・消費税・再請求（税込）・請求金額（税込）。数字は右寄せ「n,nnn円」、0円のセルは「—」。税率の列は請求書の税率から作る（税率マスタのどの率でも。列を固定で持たない）。拠点の画面から法人あてを開いたときは、見出しを「請求金額（この拠点の分・参考）」にする（No.19.1）。",
                     "Số tiền hóa đơn là 1 bảng duy nhất (căn phải, ngắn theo chiều dọc). Cột = các thuế suất có trong hóa đơn (từ nhỏ đến lớn, ví dụ: 8%対象・10%対象) + 合計. Hàng = 固定額（税抜）・ご利用実績の精算（税抜）・小計（税抜）・消費税・再請求（税込）・請求金額（税込）. Số căn phải \"n,nnn円\", ô 0 yên hiện \"—\". Cột thuế suất tạo từ thuế suất của hóa đơn (mọi thuế suất của master; không cố định cột). Khi mở hóa đơn 法人あて từ màn chi nhánh thì đổi tiêu đề thành \"請求金額（この拠点の分・参考）\" (No.19.1)."]},
         {"no": "15.1", "ja": "表の見出し（税率の列・合計）", "vi": "Hàng tiêu đề bảng (cột thuế suất, tổng)", "sel": ".cb-sum thead", "kind": "label", "trig": "view",
          "init": ["　／8%対象／10%対象／合計", "(trống) / 8%対象 / 10%対象 / 合計"],
          "detail": ["「{税率}%対象」の列を、請求書にある税率の数だけ小さい率から並べ、最後に「合計」。", "Các cột \"{thuế suất}%対象\" theo số thuế suất có trong hóa đơn, từ nhỏ đến lớn, cuối cùng là \"合計\"."]},
         {"no": "15.2", "ja": "固定額（税抜）", "vi": "固定額 (chưa thuế)", "sel": ".cb-sum td::固定額（税抜）^", "kind": "label", "trig": "view",
          "init": ["n,nnn円（税率の列ごと・合計）", "n,nnn円 (theo từng cột thuế suất và tổng)"],
          "detail": ["プラン料金・オプション・設備・値引き・スポットなど固定額の明細の対象額（税抜）。値引きはマイナス。", "Số tiền chịu thuế (chưa thuế) của các dòng 固定額: phí gói, option, thiết bị, giảm giá, phí lẻ. Giảm giá là số âm."]},
         {"no": "15.3", "ja": "ご利用実績の精算（税抜）", "vi": "ご利用実績の精算 (chưa thuế)", "sel": ".cb-sum td::ご利用実績の精算（税抜）^", "kind": "label", "trig": "view",
          "cond": ["ご利用実績の精算の明細があるときだけ（なければ行ごと出さない）", "Chỉ khi có dòng ご利用実績の精算 (không có thì ẩn cả hàng)"],
          "init": ["n,nnn円（税率の列ごと・合計）", "n,nnn円 (theo từng cột thuế suất và tổng)"],
          "detail": ["在庫差額・現金回収差額などの対象額（税抜）。", "Số tiền chịu thuế (chưa thuế) của chênh lệch tồn kho, chênh lệch thu tiền mặt…"]},
         {"no": "15.4", "ja": "小計（税抜）", "vi": "Tạm tính (chưa thuế)", "sel": ".cb-sum td::小計（税抜）^", "kind": "label", "trig": "view",
          "detail": ["固定額＋ご利用実績の精算（再請求を除く）。税率の列ごと（その税率の対象額）と合計。", "固定額 + ご利用実績の精算 (không gồm tái lập). Theo từng cột thuế suất (số tiền chịu thuế của thuế suất đó) và tổng."]},
         {"no": "15.5", "ja": "消費税", "vi": "Thuế tiêu dùng", "sel": ".cb-sum td::消費税^", "kind": "label", "trig": "view",
          "detail": ["税率の列ごと＝その税率の対象額 × 税率を1円未満四捨五入（lib/domain/invoiceTax.ts の taxOfRate。請求書ごと・税率ごと）。合計の列＝運営Web の請求書の消費税。", "Theo từng cột thuế suất = số tiền chịu thuế × thuế suất, làm tròn dưới 1 yên (taxOfRate trong lib/domain/invoiceTax.ts; theo từng hóa đơn, từng thuế suất). Cột 合計 = thuế của hóa đơn trên 運営Web."]},
         {"no": "15.6", "ja": "再請求（税込）", "vi": "Tái lập (gồm thuế)", "sel": ".cb-sum td::再請求（税込）^", "kind": "label", "trig": "view",
          "cond": ["前の請求書の再請求を含むときだけ", "Chỉ khi hóa đơn gồm tái lập hóa đơn trước"],
          "init": ["再請求（税込） INV-2026080001　90,000円", "再請求（税込） INV-2026080001, 90,000円 (số hóa đơn bị tái lập đi kèm)"],
          "detail": ["入金が確認できなかった前月以前の請求書の金額（税込のまま・再課税なし）。ラベルの横に前の請求書の番号。合計の列だけに出す（税率の列は空）。", "Số tiền (gồm thuế, không tính thuế lại) của hóa đơn trước chưa thanh toán. Cạnh nhãn có số hóa đơn trước. Chỉ hiện ở cột 合計 (các cột thuế suất để trống)."]},
         {"no": "15.7", "ja": "請求金額（税込）", "vi": "Tổng hóa đơn (gồm thuế)", "sel": ".cb-sum td::請求金額（税込）^", "kind": "label", "trig": "view",
          "detail": ["太字。小計（税抜）＋消費税＋再請求（税込）。運営Web の請求書と同じ金額。合計の列だけに出す。", "In đậm. 小計（税抜）+ 消費税 + 再請求（税込）. Bằng số tiền trên hóa đơn ở 運営Web. Chỉ hiện ở cột 合計."]},
         {"no": "16", "ja": "明細", "vi": "Chi tiết", "sel": "h2::明細^2", "kind": "table", "trig": "view",
          "detail": ["請求書に載る明細。列：（拠点）・費目・数量・税抜金額・税率。福利厚生の適用 OFF の子契約はプラン料金を1行にまとめて出す（ON は「基本料金」「福利厚生（企業負担分）」の2行）。並べ替え・ページ送りなし。小計・消費税・請求金額は上の「請求金額」の表（No.15）に出し、明細の下には出さない。", "Các dòng in trên hóa đơn. Cột: (chi nhánh)・費目・数量・税抜金額・税率. Hợp đồng con tắt 福利厚生 thì phí gói gộp 1 dòng (bật thì 2 dòng \"基本料金\" và \"福利厚生（企業負担分）\"). Không sắp xếp / phân trang. Tạm tính, thuế, tổng hóa đơn nằm ở bảng \"請求金額\" phía trên (No.15), không hiện dưới chi tiết."]},
         {"no": "16.1", "ja": "区分の見出しの行", "vi": "Hàng tiêu đề phân loại", "sel": "tr.cb-grp th::固定額", "kind": "label", "trig": "view",
          "detail": ["区分ごとの見出しの行（灰色）：固定額（プラン料金・オプション・設備・値引き・スポット。解約時の違約金・残った在庫の買取も）／ご利用実績の精算／調整。調整は再請求の行があるときだけ（再請求は調整の種類の1つ。バッジ「再請求」）。「前払い」「後払い」は出さない（契約_06 ③、hong 2026-10-05 B-24）", "Hàng tiêu đề (xám) theo từng phân loại: 固定額 (phí gói, option, thiết bị, giảm giá, phí lẻ; cả 違約金 và mua lại tồn kho khi hủy) / ご利用実績の精算 / 調整. 調整 chỉ hiện khi có dòng tái lập (再請求 là một loại của 調整, kèm badge \"再請求\"). Không hiện \"前払い\" / \"後払い\" (契約_06 ③, hong 2026-10-05 B-24)"]},
         {"no": "16.2", "ja": "拠点", "vi": "Chi nhánh", "sel": "th::拠点", "kind": "label", "trig": "view",
          "cond": ["法人あての請求書だけ（拠点あて・拠点の内訳では出さない）", "Chỉ hóa đơn 法人あて (拠点あて và 内訳 của chi nhánh không có)"],
          "detail": ["明細の拠点名。再請求の行は「—」。", "Tên chi nhánh của dòng. Dòng tái lập là \"—\"."]},
         {"no": "16.3", "ja": "費目", "vi": "Khoản mục", "sel": "th::費目", "kind": "label", "trig": "view",
          "detail": ["請求書に載る名前（例：50プラン（ESライト（冷蔵庫）） プラン料金（11月分）／ご利用実績の精算（2026/08/21〜2026/09/20）／自販機月額料金）。", "Tên in trên hóa đơn (ví dụ: 50プラン（ESライト（冷蔵庫）） プラン料金（11月分） / ご利用実績の精算（2026/08/21〜2026/09/20） / 自販機月額料金)."]},
         {"no": "16.4", "ja": "数量", "vi": "Số lượng", "sel": "th::数量", "kind": "label", "trig": "view", "detail": ["右寄せ。", "Căn phải."]},
         {"no": "16.5", "ja": "税抜金額", "vi": "Số tiền chưa thuế", "sel": "th::税抜金額", "kind": "label", "trig": "view",
          "detail": ["「n,nnn円」右寄せ。値引きはマイナス（−）。", "\"n,nnn円\" căn phải. Giảm giá là số âm (−)."]},
         {"no": "16.6", "ja": "税率", "vi": "Thuế suất", "sel": "th::税率", "kind": "label", "trig": "view",
          "detail": ["請求書の行に付いた税率（税率マスタの率。例 10%・8%）。まとめた行は「10%・8%」。再請求は「税込のまま」。決まった税率の文は画面に書かない。", "Thuế suất gắn với dòng hóa đơn (thuế suất theo master, ví dụ 10%, 8%). Dòng gộp là \"10%・8%\". Tái lập là \"税込のまま\". Không viết cố định thuế suất trong câu chữ trên màn hình."]},
         {"no": "16.7", "ja": "再請求の行", "vi": "Dòng tái lập", "sel": "td::前月以前のご請求の再請求", "kind": "label", "trig": "view",
          "cond": ["再請求があるときだけ", "Chỉ khi có tái lập"],
          "detail": ["見出し「調整」の下。費目「前月以前のご請求の再請求（{番号}）」＋黄のバッジ「再請求」、数量 1、税込の金額、税率「税込のまま」。区分は「調整」（再請求は調整の種類）。", "Dưới tiêu đề \"調整\". Khoản mục \"前月以前のご請求の再請求（{số}）\" + badge vàng \"再請求\", số lượng 1, số tiền gồm thuế, thuế suất \"税込のまま\". Phân loại là \"調整\" (再請求 là một loại của 調整)."]},
         {"no": "16.8", "ja": "明細の注記", "vi": "Ghi chú chi tiết", "sel": "p.note::費目は請求書に載る名前です", "kind": "label", "trig": "view",
          "detail": ["費目は請求書に載る名前／金額は税抜、消費税は請求書ごとに税率ごとにまとめて計算し1円未満は四捨五入／プラン料金は福利厚生の適用 ON なら2行、OFF なら1行（どちらも費目ごとの税率で計算）／再請求があるときは「入金が確認できなかった前月以前の請求書は、この請求書に「調整（再請求）」として税込のまま加えて再請求します」。税率の数字（8%・10%）は書かない。",
                     "Khoản mục là tên in trên hóa đơn / Số tiền chưa thuế, thuế gộp theo thuế suất trên từng hóa đơn và làm tròn dưới 1 yên / Phí gói: bật 福利厚生 thì 2 dòng, tắt thì 1 dòng (đều tính theo thuế suất của từng khoản mục) / Có tái lập thì thêm \"入金が確認できなかった前月以前の請求書は、この請求書に「調整（再請求）」として税込のまま加えて再請求します\". Không viết con số thuế suất (8%・10%)."]},
     ]},
    {"id": "007", "code": "CW_BILL_002", "state": ["拠点あて", "Gửi chi nhánh"],
     "url": "/corp/bills/INV-2026100015?site=CU00961&from=bills", "full": True, "wait": 600, "setup": "",
     "note": ["拠点あての請求書（INV-2026100015・千葉営業所・請求先＝この拠点）。明細に拠点の列はない。", "Hóa đơn gửi chi nhánh (INV-2026100015, 千葉営業所, nơi nhận = chi nhánh). Chi tiết không có cột chi nhánh."],
     "items": [
         {"no": "17", "ja": "宛先（拠点）", "vi": "Nơi nhận (chi nhánh)", "sel": ".es-pagehead .stat span::御中", "kind": "label", "trig": "view",
          "init": ["株式会社サンプル 千葉営業所 御中", "株式会社サンプル 千葉営業所 御中 (tên chi nhánh + 御中)"],
          "detail": ["請求書の送付先は拠点の請求担当者、支払方法は親契約の請求の設定。", "Nơi gửi là 請求担当者 của chi nhánh, phương thức thanh toán theo thiết lập hóa đơn của hợp đồng mẹ."]},
         {"no": "18", "ja": "明細（拠点列なし）", "vi": "Chi tiết (không có cột chi nhánh)", "sel": "h2::明細^2", "kind": "label", "trig": "view",
          "detail": ["列：費目・数量・税抜金額・税率（区分は見出しの行）。", "Cột: 費目・数量・税抜金額・税率 (phân loại là hàng tiêu đề)."]},
     ]},
    {"id": "008", "code": "CW_BILL_002", "state": ["法人あての内訳（参考・拠点から）", "内訳 của hóa đơn gửi pháp nhân (tham khảo, từ chi nhánh)"],
     "url": "/corp/bills/INV-2026100001?site=CU00871&from=bills", "full": True, "login": "CU00871", "wait": 600, "setup": "",
     "note": ["拠点アカウント（大阪支店・請求先＝法人）が法人あての請求書を開いた状態。この拠点の明細だけを内訳（参考）として出す。", "Tài khoản chi nhánh (大阪支店, nơi nhận = pháp nhân) mở hóa đơn 法人あて. Chỉ hiện các dòng của chi nhánh này (内訳, tham khảo)."],
     "items": [
         {"no": "19", "ja": "内訳（参考）の案内", "vi": "Thông báo 内訳 (tham khảo)", "sel": ".es-inline strong::Bill One^2", "kind": "label", "trig": "view",
          "detail": ["No.12 に「この拠点の分は法人あての請求書にまとめて入るため、ここでは法人の請求書の内訳（参考）として、この拠点の分だけを出しています。」を足す。", "Thêm vào No.12: \"この拠点の分は法人あての請求書にまとめて入るため、ここでは法人の請求書の内訳（参考）として、この拠点の分だけを出しています。\""]},
         {"no": "19.1", "ja": "請求金額の見出し（この拠点の分・参考）", "vi": "Tiêu đề bảng số tiền (phần chi nhánh, tham khảo)", "sel": "h2::この拠点の分・参考^2", "kind": "area", "trig": "view",
          "init": ["請求金額（この拠点の分・参考）", "\"請求金額（この拠点の分・参考）\""],
          "detail": ["拠点アカウントが法人あての請求書を開いたとき、請求金額の表（No.15）の見出しに「（この拠点の分・参考）」を付ける。表はこの拠点の明細だけで計算（再請求の行は出さない）。", "Khi tài khoản chi nhánh mở hóa đơn 法人あて, tiêu đề bảng số tiền (No.15) có thêm \"（この拠点の分・参考）\". Bảng chỉ tính từ các dòng của chi nhánh này (không hiện dòng tái lập)."]},
         {"no": "20", "ja": "宛先（法人あてにまとめて発行）", "vi": "Nơi nhận (gộp vào hóa đơn pháp nhân)", "sel": ".es-pagehead .stat span::まとめて発行", "kind": "label", "trig": "view",
          "init": ["株式会社サンプル 経理部 御中（法人あてにまとめて発行）", "株式会社サンプル 経理部 御中 + \"（法人あてにまとめて発行）\" (gộp vào hóa đơn pháp nhân)"],
          "detail": ["金額はこの拠点の明細だけで計算（再請求は出さない）。明細に拠点の列はない。", "Số tiền tính từ các dòng của chi nhánh (không hiện tái lập). Không có cột chi nhánh."]},
         {"no": "21", "ja": "1円のずれの注記", "vi": "Ghi chú lệch 1 yên", "sel": "p.note::1円ずれることがあります", "kind": "label", "trig": "view",
          "detail": ["「この画面は法人の請求書の内訳（参考）です。この拠点の分の消費税も、法人の請求書と同じ規則（税率ごとに合計して1円未満を四捨五入）で求めています。法人の請求書の消費税は請求書全体で計算するため、拠点ごとの合計と1円ずれることがあります。」",
                     "\"この画面は法人の請求書の内訳（参考）です。…拠点ごとの合計と1円ずれることがあります。\" (thuế của phần chi nhánh làm tròn riêng nên có thể lệch 1 yên so với hóa đơn pháp nhân)."]},
     ]},
    {"id": "009", "code": "CW_BILL_002", "state": ["送付待ち（まだ送付されていない）", "Chờ gửi (chưa gửi)"],
     "url": "/corp/bills/INV-2026100016?site=CU00950&from=bills", "full": True, "wait": 600, "setup": "",
     "note": ["Bill One でまだ送付されていない請求書。見本は送付できなかった請求書（INV-2026100016・横浜営業所。宛先のメールアドレスが見つからない）で、法人には送付前と同じ「—」を出す（赤のバッジ「送付できませんでした」は出さない。版 1.1）。",
              "Hóa đơn chưa gửi qua Bill One. Mẫu là hóa đơn gửi lỗi (INV-2026100016, 横浜営業所, không tìm thấy email người nhận); pháp nhân thấy \"—\" như trước khi gửi (không hiện badge đỏ \"送付できませんでした\", bản 1.1)."],
     "items": [
         {"no": "22", "ja": "送付の状態（送付待ち）", "vi": "Trạng thái gửi (chờ gửi)", "sel": ".es-pagehead .stat span::送付", "kind": "label", "trig": "view",
          "init": ["送付 —", "送付 — (không có badge)"],
          "detail": ["まだ送付されていない請求書（送付前・送付できなかった）は「—」でバッジなし。送付のエラーも送付の記録も法人には出さない（運営だけ。運営が宛先を直して送り直す）。", "Hóa đơn chưa gửi (trước khi gửi, gửi lỗi) hiện \"—\", không có badge. Lỗi gửi và nhật ký gửi không hiện cho pháp nhân (chỉ 運営; 運営 sửa nơi nhận và gửi lại)."]},
     ]},
    {"id": "010", "code": "CW_BILL_002", "state": ["繰越済（再請求された請求書）", "Đã chuyển kỳ (hóa đơn bị tái lập)"],
     "url": "/corp/bills/INV-2026080001?from=bills", "full": True, "wait": 600, "setup": "",
     "note": ["期日までに入金がなく、10月発行分（INV-2026100001）で再請求された8月の請求書。状態は「請求済み」＋バッジ「再請求済み（→INV-2026100001）」。", "Hóa đơn tháng 8 chưa thanh toán đúng hạn, đã tái lập ở hóa đơn tháng 10 (INV-2026100001). Trạng thái \"請求済み\" + badge \"再請求済み（→INV-2026100001）\"."],
     "items": [
         {"no": "24", "ja": "状態（再請求された請求書）", "vi": "Trạng thái (hóa đơn bị tái lập)", "sel": ".es-pagehead .stat .es-badge::再請求済み", "kind": "label", "trig": "view",
          "init": ["請求済み　再請求済み（→INV-2026100001）", "請求済み + 再請求済み（→INV-2026100001）"],
          "detail": ["状態のバッジは「請求済み」のまま、黄のバッジ「再請求済み（→{再請求した新しい請求書の番号}）」を添える。再請求した新しい側（No.11.3）は「再請求分を含む（{古い請求書の番号}）」。一覧（No.3.7）も同じ。", "Badge trạng thái vẫn \"請求済み\", thêm badge vàng \"再請求済み（→{số hóa đơn mới tái lập}）\". Phía hóa đơn mới (No.11.3) là \"再請求分を含む（{số hóa đơn cũ}）\". Danh sách (No.3.7) cũng vậy."]},
     ]},
    {"id": "011", "code": "CW_BILL_002", "state": ["最終請求書", "Hóa đơn cuối"],
     "url": "/corp/bills/INV-2026100001?from=bills", "full": True, "wait": 600, "setup": "",
     "note": ["解約した拠点の最後の1通（最終請求書）。見出しの番号の右と一覧の番号の下に灰色のバッジ「最終請求書」。見本データに最終請求書がないため、画像は通常の請求書詳細になる。", "Hóa đơn cuối của chi nhánh đã hủy. Badge xám \"最終請求書\" bên phải số ở tiêu đề và dưới số ở danh sách. Dữ liệu mẫu không có hóa đơn cuối nên ảnh là chi tiết hóa đơn bình thường."],
     "items": [
         {"no": "25", "ja": "最終請求書のバッジ", "vi": "Badge hóa đơn cuối", "sel": "h1.es-pagehead__title", "kind": "label", "trig": "view",
          "cond": ["解約した拠点の最終請求書だけ", "Chỉ hóa đơn cuối của chi nhánh đã hủy"],
          "detail": ["最終請求書は解約の在庫差額（最後の棚卸報告）を含む。解約後（参照のみ）のアカウントでも見られる。", "Hóa đơn cuối gồm chênh lệch tồn kho khi hủy (báo cáo kiểm kê cuối). Tài khoản sau hủy (chỉ xem) vẫn xem được."]},
     ]},
    {"id": "012", "code": "CW_BILL_002", "state": ["見つからない", "Không tìm thấy"],
     "url": "/corp/bills/INV-0000000000?from=bills", "full": True, "wait": 600, "setup": "",
     "note": ["ない番号、または見られない請求書（他社・他拠点）の URL を開いた状態。標準の空表示（EmptyState）だけを出す（版 1.1）。", "Mở URL của số không tồn tại hoặc hóa đơn không được xem (công ty / chi nhánh khác). Chỉ hiện khung trống chuẩn (EmptyState) (bản 1.1)."],
     "items": [
         {"no": "26", "ja": "見つからない表示（標準の空表示）", "vi": "Hiển thị không tìm thấy (khung trống chuẩn)", "sel": ".es-empty", "kind": "label", "trig": "view", "err": ["E346", "E328"],
          "detail": ["標準の空表示（EmptyState）：アイコン（書類）、タイトル「請求書が見つかりません」（E328 の前半）、本文「請求書番号をご確認いただくか、一覧へお戻りください。」（E328 の後半）、ボタン「請求書の一覧へ戻る」（請求書 CW_BILL_001 へ）。見出し（No.11）の請求書番号・状態・「戻る」は出さない。 通信・サーバーのエラーで読み込めなかったときは「見つかりません」とは別に、E346「読み込めませんでした。／時間をおいて再度お試しください。」と「再読み込み」「請求書の一覧へ戻る」を出す（画像なし：見本データではエラーを起こせない）。", "Khung trống chuẩn (EmptyState): icon (tài liệu), tiêu đề \"請求書が見つかりません\" (nửa đầu E328), nội dung \"請求書番号をご確認いただくか、一覧へお戻りください。\" (nửa sau E328), nút \"請求書の一覧へ戻る\" (về 請求書 CW_BILL_001). Không hiện số hóa đơn, trạng thái, \"戻る\" ở tiêu đề (No.11). Khi không tải được do lỗi mạng / máy chủ thì hiện riêng E346 \"読み込めませんでした。\" kèm nút \"再読み込み\" và \"請求書の一覧へ戻る\", khác với \"見つかりません\" (không có ảnh: dữ liệu mẫu không tạo được lỗi)."]},
     ]},
]
