# -*- coding: utf-8 -*-
"""
共通パターン（システム全体で1つ）。作業フォルダの「データ/_共通パターン.py」としてコピーして使う。
画面の項目に "pattern": "P-LIST" と書くと、その項目の詳細に【共通パターン P-LIST】が付き、
Excel の「共通パターン」シートにこの決まりが1回だけ出る。画面には「パターンと違うところ」だけ書く。

★ ES の決定（課題一覧 2026-10-01〜03、hong 回答）から作った。決まっていないものには「要確認」を残してあり、
  make.py --check が止める（使う前にユーザーに確認する）。ほかのプロジェクトで使うときは中身を確認し直す。
  入力の基準（文字数・数値・日付・ファイル）は references/input_standard.md。
"""

PATTERNS = {
    "P-LIST": {
        "name": ["一覧（検索・並べ替え・ページ送り）", "Danh sách (tìm kiếm, sắp xếp, phân trang)"],
        "rules": [
            ["検索条件は「検索」ボタンか Enter で反映する（入力中に一覧を変えない）。「未適用」の印は出さない（hong 2026-10-05：全部の一覧から外す）",
             "Điều kiện chỉ áp dụng khi nhấn \"検索\" hoặc Enter (không đổi danh sách khi đang nhập). Không hiện dấu \"未適用\" (hong 2026-10-05: bỏ ở mọi danh sách)."],
            ["検索条件の枠は ES Kitchen デザインシステムの es-search（マスタ一覧と同じ）：条件の欄を左に折り返し、右に「クリア」「検索」と並べ替え。欄が2行以上に折り返すときだけ開閉のボタンを出す（hong 2026-10-05：全部の一覧でそろえる）",
             "Khung điều kiện dùng es-search của ES Kitchen design system (như マスタ一覧): ô điều kiện bên trái (xuống dòng), bên phải là クリア・検索 và sắp xếp. Chỉ hiện nút đóng/mở khi ô xuống ≥2 dòng (hong 2026-10-05: đồng nhất mọi danh sách)."],
            ["1ページ 10件", "Mỗi trang 10 dòng."],
            ["並べ替えは検索欄の右の「並べ替え」ボタン1つ（デザインシステムの見本どおり）。押すとメニューが開き、上に「昇順／降順」、下に項目（初期の順を持つ一覧は先頭に「初期の順」）。選ぶとすぐ効く（検索ボタンは不要）・1ページ目に戻る。ボタンの文字は「並べ替え」（選んだあとは「並べ替え：項目（昇順）」）。項目は一覧の全列。初期の並びは画面ごとに書く（共通部品 components/SortMenu.tsx。hong 2026-10-08「全画面同様」）", "Sắp xếp bằng một nút 「並べ替え」 bên phải ô tìm kiếm (theo mẫu design system). Bấm sẽ mở menu, phía trên 「昇順／降順」, phía dưới các mục (danh sách có thứ tự ban đầu thì đầu tiên là 「初期の順」). Chọn là có hiệu lực ngay (không cần nút tìm kiếm), quay về trang 1. Chữ trên nút là 「並べ替え」 (sau khi chọn: 「並べ替え：mục（昇順）」). Mục = mọi cột của danh sách. Thứ tự ban đầu ghi theo từng màn hình (thành phần chung components/SortMenu.tsx; hong 2026-10-08 「全画面同様」)."],
            ["削除済みは既定で出さない。検索条件で「削除済」も出せる（バッジ灰色）", "Mặc định không hiện dữ liệu đã xóa; chọn điều kiện thì hiện \"削除済み\" (badge xám)."],
            ["0件のときは I01 を一覧の中に出す", "Khi 0 dòng: hiện I01 trong danh sách."],
            ["一覧の操作（編集・削除）とヘッダーのボタン（新規登録・CSV取込）は、その機能の権限がない役割には出さない。CSV出力は閲覧できる役割すべてに出す（運営Web_権限表）",
             "Nút thao tác (sửa, xóa) và nút đầu trang (新規登録, CSV取込) không hiện với vai trò không có quyền. CSV出力 hiện với mọi vai trò xem được (運営Web_権限表)."],
            ["詳細から一覧に戻ったとき、検索条件・ページ・表示件数を戻す（タブの中だけ覚える）", "Quay lại từ chi tiết thì khôi phục điều kiện tìm kiếm, trang, số dòng (nhớ trong tab)."],
                    ["初期の並びは画面ごとに書く。書いていなければ更新日時の降順。マスタ（件数が少なく ID で探す一覧）は ID の昇順（hong 2026-10-05）",
             "Thứ tự ban đầu ghi theo từng màn hình; không ghi thì theo 更新日時 giảm dần. Master (ít dòng, tìm theo ID) thì ID tăng dần (hong 2026-10-05)."],
            ['詳細の中の表（貸出・適用・履歴など）の絞り込みは表の上のドロップダウン（既定値あり）。「○○も表示」のトグルボタンは使わない。行が多い表は一覧と同じページ送り（10／20／50件）。合計は表の全件から出す（hong 2026-10-05 共通）',
             'Lọc bảng trong màn chi tiết (cho mượn, áp dụng, lịch sử…) bằng dropdown trên bảng (có giá trị mặc định); không dùng nút toggle「○○も表示」. Bảng nhiều dòng thì phân trang 10/20/50 như danh sách. Tổng tính từ toàn bộ dòng (hong 2026-10-05, chung).'],
            ['金額の列は右寄せ（単位 円 は見出しか列の右）',
             'Cột số tiền căn phải (đơn vị 円 ở tiêu đề hoặc bên phải cột).'],
        ],
        "msgs": ["I01"],
    },
    "P-FORMBOX": {
        "name": ["保存時のチェック（まとめて表示：マスタ）", "Kiểm tra khi lưu (hiện gộp: màn hình master)"],
        "rules": [
            ["「登録」「保存」で全項目をまとめてチェックする。エラーの項目は赤枠にし、項目の下にその文言を出す（必須は E01。hong 2026/10/05）。見出しの下の赤い枠は「保存できません（n件）。赤い項目を確認してください」の1行だけ（エラーの一覧は出さない・二重に出さない。hong 2026/10/05 A 案）",
             "Nhấn 登録/保存 kiểm tra mọi mục cùng lúc. Mục lỗi viền đỏ và câu lỗi hiện ngay dưới mục (bắt buộc = E01, hong 2026/10/05). Khung đỏ dưới tiêu đề chỉ 1 dòng 「保存できません（n件）。赤い項目を確認してください」 (không liệt kê lỗi, không hiện trùng; hong 2026/10/05 phương án A)."],
            ["最初のエラーの項目がほかのタブにあれば、そのタブを開く。エラーのあるタブの見出しは赤い印を付ける", "Nếu mục lỗi đầu tiên ở tab khác thì mở tab đó. Tab có lỗi được đánh dấu đỏ ở tiêu đề tab."],
            ["エラーがなければ保存し、S01 のトーストを出して詳細へ戻る（新規登録は採番した ID の詳細へ）", "Không lỗi thì lưu, hiện toast S01 và về chi tiết (新規登録 thì về chi tiết của ID vừa cấp)."],
            ["保存ボタンは押したら無効にする（二重送信を防ぐ）。前後の空白を取り、全角の数字・英字・ハイフンは半角に直す。最大文字数を超えたら E04（切り詰めない）",
             "Khóa nút lưu sau khi nhấn. Bỏ khoảng trắng đầu/cuối, đổi toàn góc sang nửa góc. Quá độ dài thì E04 (không tự cắt)."],
            ["ほかの人が先に保存していたら E31（警告のモーダル。「上書きして保存」で自分の内容で保存できる・Message List No.43）。保存のときにログインが切れていたら、その場でログインの小窓 → ログイン後に保存を続ける",
             "Người khác lưu trước thì E31 (modal cảnh báo; 「上書きして保存」 thì lưu theo nội dung của mình, Message List No.43). Hết phiên khi lưu thì hiện cửa sổ đăng nhập rồi lưu tiếp."],
            ["入力を変えたあとに キャンセル・ほかの画面への移動・ブラウザを閉じる／再読み込み をしたら Q02（キャンセル／破棄）。hong 決定 2026-10-05",
             "Đã sửa mà nhấn キャンセル, chuyển màn hình, đóng/tải lại trình duyệt thì hiện Q02 (キャンセル／破棄). hong quyết định 2026-10-05."],
        ],
        "msgs": ["S01", "E04", "E31", "Q02"],
    },
    "P-CSV": {
        "name": ["CSV取込（画面・2ステップ）", "Nhập CSV (màn hình, 2 bước)"],
        "rules": [
            ["CSV取込は一覧の「CSV取込」から開く1つの画面（モーダルではない・hong 2026/10/05）。列の定義（テンプレート：列名・必須・長さ・チェック・データ例）は画面には出さず、画面設計書の項目定義に入力画面と同じ形で書く（hong 2026/10/05）。旧：画面の上に「CSVの列（テンプレートの定義）」の表（列名・必須・形式・値の決まり）、その下に手順「1 ファイルを選ぶ → 2 確認・登録」。UTF-8 の CSV、5,000行まで。列は CSV出力と同じ（ひな形が要るときは CSV出力を使う。テンプレート・いまのデータのボタンは置かない）。テンプレートの写しは docs/05_画面設計書/CSVテンプレート/",
             "CSV取込 là 1 màn hình mở từ nút CSV取込 ở danh sách (không phải modal, hong 2026/10/05). Định nghĩa cột template (tên, bắt buộc, độ dài, kiểm tra, ví dụ) không hiện trên màn hình mà ghi trong 設計書 như màn nhập (hong 2026/10/05). Cũ: Trên cùng là bảng 「CSVの列（テンプレートの定義）」 (tên cột, bắt buộc, định dạng, quy tắc), dưới là 2 bước: 1 chọn tệp → 2 xác nhận・đăng ký. CSV UTF-8, tối đa 5.000 dòng. Cột giống CSV出力 (cần mẫu thì dùng CSV出力; không có nút template). Bản sao template ở docs/05_画面設計書/CSVテンプレート/."],
            ["キーが一致する行は上書き、キーが空欄の行は新規（採番）。空欄のセルは今の値のまま、消すときは「-」を書く。削除は画面から（CSV ではしない）",
             "Dòng trùng khóa thì ghi đè, khóa trống thì tạo mới (cấp ID). Ô trống giữ giá trị cũ, muốn xóa giá trị thì ghi \"-\". Xóa bản ghi làm trên màn hình."],
            ["確認のステップで、件数（新規／更新／変更なし／エラー）と、エラーの行（行番号・列・内容。エラー一覧CSV も出せる）、登録する内容（前 → 後）、警告を見せる。「登録」でエラー以外の行（新規・更新）だけ登録し、エラーの行は取り込まない（hong 2026/10/05・マスタ項目一覧 一覧画面 #8。旧：1行でもエラーなら何も登録しない）。ファイル全体のエラー（列が違う・文字コード）と登録できる行がないときだけ止める。警告があるときは「警告を確認しました」のチェックが要る。登録できたら S03、できなければ E34",
             "Bước xác nhận hiện số lượng (mới / cập nhật / không đổi / lỗi), các dòng lỗi (số dòng, cột, nội dung; xuất được エラー一覧CSV), nội dung sẽ đăng ký (trước → sau), cảnh báo. Nhấn 登録 thì chỉ đăng ký các dòng không lỗi (mới, cập nhật); dòng lỗi bỏ qua (hong 2026/10/05, マスタ項目一覧 #8; cũ: 1 dòng lỗi thì không đăng ký gì). Chỉ dừng khi lỗi cả tệp (sai cột, mã ký tự) hoặc không có dòng nào đăng ký được. Có cảnh báo thì phải check 「警告を確認しました」. Xong hiện S03, lỗi hiện E34."],
            ["CSV取込のボタンは、その機能の CSV取込 の権限がある役割だけに出す", "Nút CSV取込 chỉ hiện với vai trò có quyền CSV取込."],
            ["他の列の値で入力できない列（例：支払方法が口座振替でないのに、口座振替の手続きステータスに値がある）に値があれば、その行はエラー（E109）。画面で入力欄が無効になる列と同じ決まり",
             "Cột không được nhập theo giá trị của cột khác (ví dụ: 支払方法 không phải 口座振替 mà cột trạng thái thủ tục 口座振替 có giá trị) thì dòng đó lỗi (E109). Cùng quy tắc với ô bị vô hiệu trên màn hình."],
            ["1つの対象（法人・拠点）に複数の担当者がいるときは、同じ{対象}IDの行を並べる（1行＝1人）。2行目以降の{対象}の列は空欄でよく、入れるなら1行目と同じ値（違えば E116）",
             "1 đối tượng (pháp nhân / chi nhánh) có nhiều người phụ trách thì xếp các dòng cùng ID {đối tượng} (1 dòng = 1 người). Các cột của {đối tượng} từ dòng 2 trở đi để trống được; nếu điền phải giống dòng 1 (khác thì E116)."],
            ["担当者は「区分＋メールアドレス」で突き合わせる：あれば更新、なければ追加。CSV では担当者を削除しない（削除は画面から）",
             "Người phụ trách được đối chiếu theo 「区分 + địa chỉ email」: có thì cập nhật, chưa có thì thêm. Không xóa người phụ trách bằng CSV (xóa làm trên màn hình)."],
        ],
        "msgs": ["S03", "E34", "E109", "E116"],
    },
    "P-DEL": {
        "name": ["削除", "Xóa"],
        "rules": [
            ["「削除」で Q01 を出し、「削除する」で削除して S02。失敗は E30", "Nhấn \"Xóa\" hiện Q01; \"削除する\" thì xóa và hiện S02. Lỗi: E30."],
            ["論理削除（データは残し、ステータスを「削除済」にする）", "Xóa logic (giữ dữ liệu, trạng thái \"削除済み\")."],
            ["契約・請求書・申請は削除しない（ステータスで扱う）", "Hợp đồng, hóa đơn, đơn đăng ký không xóa (xử lý bằng trạng thái)."],
        ],
        "msgs": ["Q01", "S02", "E30"],
    },
    "P-FORM": {
        "name": ["登録・編集フォーム（入力チェックと保存）", "Form đăng ký / sửa (kiểm tra nhập và lưu)"],
        "rules": [
            ["「保存」ですべての項目をまとめてチェックし、エラーの項目は赤枠と文言（項目の下）。必須が空なら必須のエラーだけ出す",
             "Nhấn \"Lưu\" kiểm tra mọi mục cùng lúc; mục lỗi viền đỏ, thông báo dưới mục. Mục bắt buộc để trống thì chỉ báo lỗi bắt buộc."],
            ["前後の空白を取り、全角の数字・英字・ハイフンは半角に直してからチェック・保存する", "Bỏ khoảng trắng đầu/cuối, đổi số/chữ/gạch toàn góc sang nửa góc rồi mới kiểm tra và lưu."],
            ["最大文字数を超えたらエラー（切り詰めない）。絵文字は受け付けない（E13）", "Quá số ký tự thì báo lỗi (không tự cắt). Không nhận emoji (E13)."],
            ["保存ボタンは押したら無効にする（二重送信を防ぐ）。保存できたら S01", "Khóa nút Lưu sau khi nhấn (chống gửi 2 lần). Lưu xong hiện S01."],
            ["ほかの人が開いていれば I02 を出す（ロックしない）。あとから保存した方は E31", "Người khác đang mở thì hiện I02 (không khóa). Người lưu sau bị E31."],
            ["保存のときにログインが切れていたら、その場でログインの小窓を出し、ログイン後に保存を続ける（運営で許可IPの外なら OTP も）。下書きは保存しない",
             "Khi lưu mà hết phiên: hiện cửa sổ đăng nhập ngay trên trang, đăng nhập xong thì lưu tiếp (運営 ngoài IP whitelist thì có OTP). Không lưu nháp."],
            ["入力を変えたあとに キャンセル・ほかの画面への移動・ブラウザを閉じる／再読み込み をしたら Q02 を出す（キャンセル／破棄）。hong 決定 2026-10-05",
             "Sau khi đã sửa mà nhấn キャンセル, chuyển màn hình, đóng/tải lại trình duyệt thì hiện Q02 (キャンセル／破棄). hong quyết định 2026-10-05."],
                    ["備考・説明など複数行の欄は3列分の幅（1行）にし、セクションの最後に置く（hong 2026-10-05・全画面共通）",
             "Ô nhiều dòng (備考, 説明) rộng 3 cột (1 hàng) và đặt cuối section (hong 2026-10-05, chung mọi màn hình)."],
            ["保存のエラーは項目の下の文言（インライン）で出す。運営のマスタだけ P-FORMBOX（項目の下の文言＋見出しの下に「保存できません（n件）」の1行の枠。hong 2026-10-05 同日の2回目）",
             "Lỗi khi lưu hiện inline dưới mục. Riêng master 運営 dùng P-FORMBOX (câu dưới mục + khung 1 dòng 「保存できません（n件）」 dưới tiêu đề, hong 2026-10-05 lần 2)."],
            ['詳細画面は表示だけ：入力欄・カードごとの保存ボタンを置かない。編集・新規登録の保存は画面の上の「登録／保存」1つ（カードや表ごとに保存しない。hong 2026-10-05 共通）',
             'Màn chi tiết chỉ xem: không có ô nhập hay nút lưu riêng trong card. Sửa / đăng ký mới lưu bằng 1 nút 登録／保存 ở đầu trang (không lưu theo card / bảng; hong 2026-10-05, chung).'],
            ['対象を複数から選ぶ欄（コース・機種区分・プランなど）は、チェックの先頭に「すべて」を置き既定で ON。外すと個別を選べ、1つも選ばないと E02。一覧・詳細では「すべて」と出す（hong 2026-10-05 共通）',
             'Ô chọn nhiều đối tượng (course, loại thiết bị, plan…): checkbox đầu tiên là「すべて」mặc định bật; bỏ thì chọn riêng, không chọn gì → E02. Danh sách / chi tiết hiện「すべて」(hong 2026-10-05, chung).'],
            ['金額の欄は右寄せ（単位 円 は欄の右）',
             'Ô số tiền căn phải (đơn vị 円 bên phải ô).'],
            ['編集・新規登録の画面は、見出し（画面名・キャンセル・保存）を画面の上に固定し、スクロールしても保存を押せるようにする（運営A 法人・拠点 2026-10-05。台帳 F）',
             'Màn sửa / đăng ký mới: cố định phần đầu (tên màn hình, キャンセル, 保存) ở trên cùng để cuộn vẫn bấm được 保存 (運営A 法人・拠点 2026-10-05, sổ quyết định F).'],
            ['保存できないときは、見出しの下に「保存できません（n件）。赤い項目を確認してください」を1行だけ出す。タブのある画面では、エラーのあるタブの見出しにその件数を出す（例：基本情報 2）。最初のエラーのタブを開く',
             'Khi không lưu được, dưới phần đầu hiện 1 dòng 「保存できません（n件）。赤い項目を確認してください」. Màn có tab thì hiện số lỗi ở tiêu đề tab có lỗi (ví dụ: 基本情報 2) và mở tab lỗi đầu tiên.'],
        ],
        "msgs": ["S01", "E31", "I02", "E13", "Q02"],
    },
    "P-TAB": {"name": ["タブ", "Tab"], "rules": [["タブは URL（?tab=）に持ち、再読み込み・戻るでも同じタブを開く", "Tab giữ trong URL (?tab=); tải lại / Back vẫn mở đúng tab."], ["件数があるタブは名前の後ろに件数を出す（例：要対応 3）", "Tab có số đếm thì hiện sau tên (ví dụ: 要対応 3)."], ["入力中にタブを変えても入力は消さない（保存は画面全体で1回）", "Đổi tab khi đang nhập không mất nội dung (lưu 1 lần cho cả màn hình)."]], "msgs": []},
    "P-HIST": {"name": ["変更履歴（表示だけ）", "Lịch sử thay đổi (chỉ xem)"], "rules": [["列：日時・操作した人・操作（登録／変更／削除／CSV取込／一括変更）・項目・変更前・変更後・理由（あれば）。「影響した拠点数」「バージョン」の列は持たない（マスタを変えても契約・拠点には影響しない。契約は設定した時点のマスタの値を持つ・hong 2026-10-05 共通）", "Cột: 日時, người thao tác, thao tác (登録／変更／削除／CSV取込／一括変更), mục, trước, sau, lý do (nếu có). Không có cột「影響した拠点数」「バージョン」(đổi master không ảnh hưởng hợp đồng / điểm; hợp đồng giữ giá trị lúc thiết lập, hong 2026-10-05, chung)."], ["新しいものが上。直せない・消せない", "Mới nhất ở trên. Không sửa, không xóa được."], ["1回の保存で変わった項目は1つの操作としてまとめる（項目ごとに行を分けない）", "Các mục đổi trong 1 lần lưu gộp thành 1 thao tác (không tách dòng theo mục)."]], "msgs": []},
    "P-MASTER": {
        "name": ["マスタ共通（システム定義の行・区分マスタ）", "Master chung (dòng hệ thống định nghĩa, master loại)"],
        "rules": [
            ["システムが先に定義して動きが決まる行（A型のオプション・自動で付く値引き など）は、要件（オプション・値引き_定義 §10・§11 のような一覧）で定義する。運営は作る・消すができず、直せるのは 表示名・金額・公開ステータス・利用状態・説明 だけ。一覧・詳細に「削除」を出さず、新規登録ではその種類を選べない（hong 2026-10-05 共通）",
             "Các dòng do hệ thống định nghĩa sẵn (option loại A, giảm giá tự gắn…) phải liệt kê trong yêu cầu (như オプション・値引き_定義 §10, §11). 運営 không tạo / xóa; chỉ sửa tên hiển thị, số tiền, công khai, trạng thái, mô tả. Không có nút 削除 ở danh sách / chi tiết; màn mới không chọn được loại đó (hong 2026-10-05, chung)."],
            ["「区分」（オプション区分・値引き区分 など）は固定の選択肢にせず、運営が足せる区分マスタ（名前・並び順・使用中／終了）から選ぶ。選択肢・請求書の並びは 区分の並び順 → ID。初期値は要件に書く（hong 2026-10-05 共通）",
             "「区分」(loại option, loại giảm giá…) không hard-code; chọn từ master loại mà 運営 thêm được (tên, thứ tự, đang dùng / kết thúc). Thứ tự lựa chọn và trên hóa đơn: thứ tự loại → ID. Giá trị ban đầu ghi trong yêu cầu (hong 2026-10-05, chung)."],
            ["マスタの既定の行（初期データ）と CSVテンプレートの列は、画面設計書の追加のシート「初期データ」「CSVテンプレート」に書く（seed と同じに保つ）",
             "Dòng mặc định của master (dữ liệu ban đầu) và cột CSV template ghi ở sheet bổ sung「初期データ」「CSVテンプレート」của 設計書 (giữ giống seed)."],
        ],
        "msgs": ["E02"],
    },
    "P-DETAIL-AUX": {
        "name": ["詳細画面の補助機能（検索・目次・編集できる項目だけ）", "Chức năng phụ ở màn chi tiết (tìm mục, mục lục, chỉ mục sửa được)"],
        "rules": [
            ["項目を検索：入力した文字に合う項目名・値のあるカードだけを残す（入力するたびに絞る。空にすると戻る）",
             "Tìm mục: chỉ giữ các card có tên mục / giá trị khớp với chữ nhập (lọc mỗi khi nhập; xóa trống thì quay lại)."],
            ["「すべて閉じる」「すべて開く」：カードの開閉をまとめて切り替える。個別の開閉も残す",
             "「すべて閉じる」「すべて開く」: đóng / mở đồng loạt các card; vẫn đóng / mở riêng từng card."],
            ["カード目次：カードの名前を並べ、押すとそのカードへ移動する（スクロールしても見える位置に置く）",
             "Mục lục card: liệt kê tên các card, nhấn thì cuộn tới card đó (đặt ở vị trí luôn nhìn thấy khi cuộn)."],
            ["「編集できる項目だけ」のチェック：編集ボタンのある詳細画面にだけ出す（編集できる役割の画面）。ON にすると、編集で直せる項目だけを残す。編集ボタンのない詳細（参照だけの役割・取消などで編集できない状態）には出さない（台帳 F 2026-10-05）",
             "Checkbox 「編集できる項目だけ」: chỉ hiện ở màn chi tiết có nút 編集 (vai trò sửa được). Bật thì chỉ giữ các mục sửa được ở màn sửa. Không hiện ở chi tiết không có nút 編集 (vai trò chỉ xem, trạng thái không sửa được như 取消) (sổ quyết định F 2026-10-05)."],
        ],
        "msgs": [],
    },
    "P-STATUS-COLORS": {
        "name": ["ステータスのバッジの色（1つの表）", "Màu badge trạng thái (1 bảng duy nhất)"],
        "rules": [
            ["バッジの色は全画面で次の1つの表を使う：緑＝有効、青＝予定、黄＝対応待ち、灰＝終了（削除済み・取消・閉鎖など）、赤＝エラー・警告（台帳 M-1。input_standard の「表示の共通」と同じ）。拠点・契約・アカウント・法人など、対象ごとの色の表は作らない",
             "Màu badge mọi màn hình dùng 1 bảng sau: xanh lá = 有効, xanh dương = 予定, vàng = 対応待ち, xám = 終了 (削除済み・取消・閉鎖…), đỏ = lỗi・cảnh báo (sổ quyết định M-1; giống mục「表示の共通」của input_standard). Không tạo bảng màu riêng cho từng đối tượng (chi nhánh, hợp đồng, tài khoản, pháp nhân…)."],
            ["各ステータスがどの色になるかは、画面ごとの「ステータスの色」の項目に書く（色の意味はこの表から変えない）",
             "Trạng thái nào ra màu nào ghi ở mục「ステータスの色」của từng màn hình (không đổi ý nghĩa màu so với bảng này)."],
        ],
        "msgs": [],
    },
    "P-PAGESIZE": {
        "name": ["表示件数（人ごと・一覧ごとに覚える）", "Số dòng hiển thị (nhớ theo từng người, từng danh sách)"],
        "rules": [
            ["ページごとの表示件数（10／20／50／100件）は、利用者ごと・一覧ごとに覚える。次に開いたときも同じ件数で出す（別のブラウザ・端末でも同じ）。一覧が違えば件数も別",
             "Số dòng mỗi trang (10 / 20 / 50 / 100) được nhớ theo từng người dùng và từng danh sách; lần mở sau vẫn dùng số đó (kể cả trình duyệt / thiết bị khác). Danh sách khác thì số dòng riêng."],
            ["覚える対象は表示件数だけ。検索条件・ページ番号は P-LIST（タブの中だけ覚える）",
             "Chỉ nhớ số dòng hiển thị. Điều kiện tìm kiếm và số trang theo P-LIST (chỉ nhớ trong tab)."],
        ],
        "msgs": [],
    },
    "P-MODAL-SAVE": {
        "name": ["別操作で即保存する小窓（編集中は非活性）", "Cửa sổ nhỏ lưu ngay bằng thao tác riêng (khóa khi đang sửa)"],
        "rules": [
            ["編集画面の中にあっても、押した時点で別に保存する操作（例：拠点の請求先を一括変更・お試しの延長・子契約を先まで作る）は、画面に編集中の未保存の内容があるとボタンを非活性にする。理由は E104（ボタンのそばかツールチップで出す）",
             "Thao tác lưu ngay riêng biệt dù nằm trong màn sửa (ví dụ: đổi hàng loạt bên nhận hóa đơn của chi nhánh, gia hạn dùng thử, tạo hợp đồng con tới tháng sau) thì khóa nút khi màn hình còn nội dung sửa chưa lưu. Lý do hiện bằng E104 (cạnh nút hoặc tooltip)."],
            ["編集中の内容を保存する（または破棄する）と、ボタンは使えるようになる。小窓の保存では、画面で編集中の内容は保存しない（巻き込まない）",
             "Lưu (hoặc hủy) nội dung đang sửa thì nút dùng lại được. Khi lưu ở cửa sổ nhỏ không lưu kèm nội dung đang sửa trên màn hình."],
        ],
        "msgs": ["E104"],
    },
    "P-CSV-OUT": {
        "name": ["CSV出力", "Xuất CSV"],
        "rules": [
            ["検索条件のとおりの全件（ページに関係なく）を UTF-8（BOM あり）・CRLF で出す。日付 yyyy-mm-dd、日時 yyyy-mm-dd HH:MM、複数の値は「;」でつなぐ",
             "Xuất toàn bộ dòng theo điều kiện tìm kiếm (không phụ thuộc trang) dạng UTF-8 (có BOM), CRLF. Ngày yyyy-mm-dd, ngày giờ yyyy-mm-dd HH:MM, nhiều giá trị nối bằng「;」."],
            ["ファイル名＝画面名＋条件＋日時。出力は出力の記録に残る。終わったらトーストで件数とファイル名を出す。CSV出力の権限（閲覧できる役割すべて）",
             "Tên tệp = tên màn hình + điều kiện + ngày giờ. Lần xuất được ghi vào lịch sử xuất. Xong thì toast hiện số dòng và tên tệp. Quyền CSV出力 = mọi vai trò xem được."],
        ],
        "msgs": [],
    },
    # ---- 仕入先Web・委託配送先Web・ドライバーアプリの3サイトで共通（phiên gộp 2026-10-07）。出どころは台帳 F 2026-10-07 と、確認メモ SW・TW・DW の B 段階
    "P-AUTH": {
        "name": ["ログイン・パスワード再設定（仕入先・委託配送先・ドライバー共通）", "Đăng nhập・đặt lại mật khẩu (chung cho nhà cung cấp・đối tác giao hàng・tài xế)"],
        "rules": [
            ["ログインは「ログインID＋パスワード」。誤りは E53（どちらが違うかは言わない）。誤入力が続いてもアカウントをロックしない。入力回数の上限も設けない（台帳 F 2026-10-07）",
             "Đăng nhập bằng \"ID đăng nhập + mật khẩu\". Sai thì E53 (không nói cái nào sai). Nhập sai liên tiếp vẫn không khóa tài khoản và không đặt giới hạn số lần nhập (台帳 F 2026-10-07)."],
            ["ログインの有効期限は全サイト1日（台帳 K）。切れた状態で操作したら E58 を出してログインへ戻す。入力途中の内容は下書きに残さない。保存のときに切れていたら、その場でログインの小窓を出し、ログイン後に保存を続ける（P-FORM）",
             "Thời hạn đăng nhập là 1 ngày ở mọi site (台帳 K). Hết hạn mà thao tác thì hiện E58 và quay về đăng nhập. Không lưu nháp phần đang nhập. Nếu hết hạn lúc lưu thì hiện cửa sổ đăng nhập ngay tại chỗ, đăng nhập xong thì lưu tiếp (P-FORM)."],
            ["パスワードの再設定は4ステップ。① ログインID＋メールアドレス（組み合わせが違えば E59。ドライバーアプリはログインID だけを入れ、登録のメールアドレスへ送る：E433・E434）→ ② 認証コード（送ったあとの案内 I11・再送 S13・誤り E54・期限切れ E55）→ ③ 新しいパスワード（形式 E56・確認用との不一致 E57）→ ④ 完了 S14",
             "Đặt lại mật khẩu gồm 4 bước. ① ID đăng nhập + email (sai tổ hợp thì E59; app tài xế chỉ nhập ID đăng nhập, mã gửi tới email đã đăng ký: E433・E434) → ② mã xác thực (hướng dẫn sau khi gửi I11・gửi lại S13・sai E54・hết hạn E55) → ③ mật khẩu mới (định dạng E56・không khớp xác nhận E57) → ④ hoàn tất S14."],
            ["認証コードは4桁の数字・有効期限5分（全サイト共通）。ロックはかけない。入力回数の上限・再送の間隔は定義しない（台帳 F 2026-10-07。台帳 K「パスワードの再設定」と同じ）",
             "Mã xác thực là 4 chữ số, hiệu lực 5 phút (chung mọi site). Không khóa. Không định nghĩa giới hạn số lần nhập và khoảng cách gửi lại (台帳 F 2026-10-07, giống 台帳 K「パスワードの再設定」)."],
            ["パスワードの形式は「8文字以上・英字と数字を含む」（初期パスワードも同じ）。最大文字数は画面ごとに書く（そろえる決定はまだない：確認メモ_3サイト_hong確認表）",
             "Định dạng mật khẩu: \"từ 8 ký tự, gồm chữ cái và chữ số\" (mật khẩu ban đầu cũng vậy). Số ký tự tối đa ghi theo từng màn hình (chưa có quyết định thống nhất: 確認メモ_3サイト_hong確認表)."],
            ["ログイン中のパスワード変更の画面は置かない。変えたいときはログイン画面の「パスワードを忘れた方」から再設定する。プロフィール・アカウントの画面にパスワードの項目・ボタンを置かない",
             "Không có màn hình đổi mật khẩu khi đang đăng nhập. Muốn đổi thì đặt lại từ 「パスワードを忘れた方」 ở màn đăng nhập. Không đặt mục/nút mật khẩu ở màn hồ sơ・tài khoản."],
            ["初期パスワードはシステムが作り、メイン担当者（登録のメールアドレス）へ送る。委託配送先の配送スタッフのアカウント一括発行は、各スタッフの登録メールアドレスへログインIDと初期パスワードを送る（P-BULK）",
             "Mật khẩu ban đầu do hệ thống tạo và gửi tới người phụ trách chính (email đã đăng ký). Với cấp tài khoản hàng loạt cho nhân viên giao hàng của đối tác: gửi ID đăng nhập và mật khẩu ban đầu tới email đã đăng ký của từng nhân viên (P-BULK)."],
            ["停止・利用できないアカウントの文言は、委託配送先 E401（ESキッチンへ問い合わせ）とドライバー E431（所属先へ問い合わせ）で連絡先が違うため別の ID。仕入先は状態によらず E53（存在を明かさない）",
             "Câu cho tài khoản bị tạm dừng/không dùng được: đối tác giao hàng E401 (liên hệ ESキッチン) và tài xế E431 (liên hệ đơn vị trực thuộc) khác nơi liên hệ nên tách ID. Nhà cung cấp luôn E53 (không lộ sự tồn tại)."],
            ["ログインの本番は Cognito、開発（いまのコード）は自前（台帳 F 2026-10-07・仕入先で決定）。動き（4桁・5分・ロックなし・8文字以上）は同じ",
             "Môi trường production dùng Cognito, dev (code hiện tại) tự xây (台帳 F 2026-10-07, quyết định ở nhà cung cấp). Hành vi (4 chữ số・5 phút・không khóa・từ 8 ký tự) như nhau."],
        ],
        "msgs": ["E53", "E54", "E55", "E56", "E57", "E58", "E59", "I11", "S13", "S14"],
    },
    "P-HELP-LINK": {
        "name": ["外部の文書へのリンク（操作マニュアル・規約）", "Liên kết tới tài liệu bên ngoài (hướng dẫn thao tác・điều khoản)"],
        "rules": [
            ["操作マニュアルのリンク（URL）は運営Web の設定画面に置き、システム管理が変える（ドライバー用・仕入先用：台帳 F 2026-10-07。委託配送先・法人Web も同じ置き方にそろえる）。いまのコードの法人Web は環境変数 NEXT_PUBLIC_CORP_HELP_URL を読む",
             "URL liên kết hướng dẫn thao tác đặt ở màn hình cài đặt Web 運営, quản trị hệ thống thay đổi (cho tài xế・nhà cung cấp: 台帳 F 2026-10-07; đối tác giao hàng・Web pháp nhân cũng thống nhất cách đặt này). Code hiện tại của Web pháp nhân đọc biến môi trường NEXT_PUBLIC_CORP_HELP_URL."],
            ["URL が空のときは、リンクもボタンも出さない（法人Web・ドライバー・仕入先・委託配送先で同じ）",
             "Khi URL rỗng thì không hiện liên kết lẫn nút (giống nhau ở Web pháp nhân・tài xế・nhà cung cấp・đối tác giao hàng)."],
            ["リンクは別のタブで開く（アプリの画面を離れない）。画面の中に文書の本文は置かない",
             "Liên kết mở ở tab khác (không rời màn hình app). Không đặt nội dung tài liệu trong màn hình."],
            ["申込の同意の書面（取引条件・契約書・個人情報の取り扱い）のリンクは、いまは環境変数から取る（例 NEXT_PUBLIC_SUPPLIER_TERMS_URL）。空のときは出さない。のちに運営Web の設定画面へ移す（台帳 F 2026-10-07 仕入先）",
             "Liên kết văn bản đồng ý khi đăng ký (điều khoản giao dịch・hợp đồng・xử lý thông tin cá nhân) hiện lấy từ biến môi trường (ví dụ NEXT_PUBLIC_SUPPLIER_TERMS_URL). Rỗng thì không hiện. Sau này chuyển sang màn cài đặt Web 運営 (台帳 F 2026-10-07 nhà cung cấp)."],
            ["仕入先の「操作マニュアル」は専用の画面（メニュー項目）を持つので、リンクがないときもメニューは残し、画面に「準備中です。」（I402）と出す（台帳 S 2026-10-08・SW_MANU）。ドライバー・委託配送先・法人はリンクもボタンも出さない",
             "「操作マニュアル」 của nhà cung cấp có màn hình riêng (mục menu) nên khi không có liên kết vẫn giữ menu và hiện \"Đang chuẩn bị.\" (I402) trong màn hình (台帳 S 2026-10-08・SW_MANU). Tài xế・đối tác giao hàng・pháp nhân không hiện liên kết lẫn nút."],
        ],
        "msgs": ["I402"],
    },
    "P-ADDRESS": {
        "name": ["住所検索（郵便番号 → 住所）", "Tìm địa chỉ (mã bưu điện → địa chỉ)"],
        "rules": [
            ["住所を入力する画面には「住所検索」ボタンを置く。全サイト（法人・委託配送先・仕入先・運営）共通で、隠さない・あとの段階にしない（台帳 F 2026-10-07）。ドライバーアプリは住所を入力する画面がないので対象なし",
             "Màn hình nhập địa chỉ đều có nút 「住所検索」. Chung mọi site (pháp nhân・đối tác giao hàng・nhà cung cấp・運営), không ẩn, không để phase sau (台帳 F 2026-10-07). App tài xế không có màn nhập địa chỉ nên không áp dụng."],
            ["郵便番号（数字7桁・形式違いは E05）を入れて押すと、都道府県・市区町村・町域を住所の欄に入れる。番地・建物は自分で入れる。見つからないときは何も変えない",
             "Nhập mã bưu điện (7 chữ số, sai định dạng E05) rồi bấm thì điền tỉnh・quận/huyện・khu vực vào ô địa chỉ. Số nhà・tòa nhà tự nhập. Không tìm thấy thì không đổi gì."],
            ["ボタンは郵便番号の欄の横に置く。郵便番号の欄がない住所（例：仕入先の出荷元の住所）には置かない。編集できない（参照だけの）ときは出さない",
             "Nút đặt cạnh ô mã bưu điện. Không đặt ở địa chỉ không có ô mã bưu điện (ví dụ: địa chỉ nơi xuất hàng của nhà cung cấp). Không hiện khi chỉ xem (không sửa được)."],
            ["住所のデータの出どころは、日本郵便が公開している郵便番号データ（無料）をシステムに取り込む（台帳 S 2026-10-08・hong 回答 H-14）。全サイト共通。つなぐ時期は決まっていない（決まるまでもボタンは出す）",
             "Nguồn dữ liệu địa chỉ: nhập dữ liệu mã bưu điện do Japan Post công bố (miễn phí) vào hệ thống (台帳 S 2026-10-08・hong trả lời H-14). Chung mọi site. Thời điểm nối chưa quyết (trong lúc chờ vẫn hiện nút)."],
        ],
        "msgs": ["E05"],
    },
    "P-CARD": {
        "name": ["カード一覧（スマホ・ドライバーアプリ）", "Danh sách dạng thẻ (điện thoại・app tài xế)"],
        "rules": [
            ["一覧は1件1枚のカード（スマホは1列）。押すと詳細へ。状態はバッジで出す（色は全サイト共通の状態の表）",
             "Danh sách mỗi mục một thẻ (điện thoại 1 cột). Bấm vào thẻ thì sang chi tiết. Trạng thái hiện bằng badge (màu theo bảng trạng thái chung mọi site)."],
            ["検索は部分一致で、入力した文字で即座に絞る（検索ボタンはない。P-LIST の「検索」ボタンは使わない）。タブを切り替えると検索の文字は空に戻す",
             "Tìm kiếm khớp một phần, lọc ngay theo chữ đang nhập (không có nút tìm kiếm; không dùng nút 「検索」 của P-LIST). Chuyển tab thì ô tìm kiếm về trống."],
            ["絞り込みは、ボタンを押すと下から出る「絞り込みシート」で選ぶ。選ぶとすぐ一覧に反映し、選んだ内容をボタンの文字に出す。背景を押すか「閉じる」で閉じる（選んだ内容は残る）",
             "Lọc bằng \"sheet lọc\" hiện từ dưới lên khi bấm nút. Chọn xong áp dụng ngay vào danh sách và hiện nội dung đã chọn trên chữ của nút. Bấm nền hoặc 「閉じる」 để đóng (giữ nội dung đã chọn)."],
            ["並べ替え・ページ送りは台帳 F の標準（1ページ10件：10／20／50）。初期の並びは画面ごとに書く。1日分で件数が限られる一覧を全件表示にするときは、画面に書く",
             "Sắp xếp・phân trang theo chuẩn 台帳 F (10 dòng/trang: 10/20/50). Thứ tự ban đầu ghi theo từng màn hình. Danh sách ít dòng (dữ liệu 1 ngày) mà hiện toàn bộ thì ghi trong màn hình."],
            ["0件のときは I01 を一覧の中に出す", "Khi 0 mục: hiện I01 trong danh sách."],
        ],
        "msgs": ["I01"],
    },
    "P-OFFLINE": {
        "name": ["オフライン・未送信（ドライバーアプリ）", "Offline・chưa gửi (app tài xế)"],
        "rules": [
            ["電波がなくて送れなかった完了・報告・登録は、内容を端末のブラウザ（IndexedDB・写真も）に保存して「未送信」にし、W311 を出す。電波が戻ると送る（台帳 F 2026-10-07）",
             "Hoàn tất・báo cáo・đăng ký không gửi được do mất sóng thì lưu nội dung (cả ảnh) vào trình duyệt của thiết bị (IndexedDB), đánh dấu \"未送信\" và hiện W311. Có sóng lại thì gửi (台帳 F 2026-10-07)."],
            ["全画面の上に帯「オフライン・未送信 N件」（電波が戻ると「オンライン・未送信 N件」）を出す。未送信があるときは「再送する」ボタン。成功は S16、まだ通信できないときは E445",
             "Phía trên mọi màn hình có dải 「オフライン・未送信 N件」 (có sóng lại thì 「オンライン・未送信 N件」). Khi có mục chưa gửi thì có nút 「再送する」. Thành công S16, vẫn chưa kết nối được thì E445."],
            ["未送信は、ログインの期限切れ・ログアウトでも消さない。ログインし直すと再送する。未送信が残ったままログアウトするときは Q317、ログイン画面には W312 を出す",
             "Mục chưa gửi không bị xóa khi hết hạn đăng nhập hay đăng xuất. Đăng nhập lại thì gửi lại. Đăng xuất khi còn mục chưa gửi thì Q317, màn đăng nhập hiện W312."],
            ["一覧・詳細の札には状態のバッジ「未送信」を並べる。二度押しで二重に送らない",
             "Thẻ ở danh sách・chi tiết có badge trạng thái \"未送信\". Bấm hai lần không gửi trùng."],
            ["保持の制限（hong 受け入れ済み）：ブラウザのデータ削除・プライベートモードでは消える。iPhone の Safari は約7日使わないと消える。iPhone は裏での自動再送ができない（Android の Chrome は可）",
             "Giới hạn lưu giữ (hong đã chấp nhận): bị mất khi xóa dữ liệu trình duyệt hoặc dùng chế độ riêng tư. Safari trên iPhone bị xóa nếu khoảng 7 ngày không dùng. iPhone không tự gửi lại ở nền (Chrome Android thì được)."],
        ],
        "msgs": ["W311", "W312", "S16", "E445", "Q317"],
    },
    "P-PHOTO": {
        "name": ["写真の添付（ドライバーアプリ）", "Đính kèm ảnh (app tài xế)"],
        "rules": [
            ["端末のカメラ（撮影）かギャラリー（選択）から入れる。複数枚をまとめて選べる。位置情報は取得しない",
             "Chọn từ camera (chụp) hoặc thư viện ảnh của thiết bị. Chọn được nhiều ảnh cùng lúc. Không lấy thông tin vị trí."],
            ["最大20枚（K-30）・形式は JPG／PNG／HEIC（PDF は不可）・1枚 5MB まで（超える写真はアプリで縮小して送る）。守れないときは E441",
             "Tối đa 20 ảnh (K-30), định dạng JPG/PNG/HEIC (không nhận PDF), mỗi ảnh tối đa 5MB (ảnh vượt thì app thu nhỏ rồi gửi). Vi phạm thì E441."],
            ["入れた写真は縮小して見せ、×で消せる", "Ảnh đã thêm hiện dạng thu nhỏ, xóa được bằng ×."],
            ["必須かどうか・最低枚数は画面ごとに書く（陳列の前後・納品は最低1枚、トラブルは任意、駐車のレシートは1枚で必須）。トラブルの写真は運営の配送詳細で見られ、12ヶ月保存する",
             "Bắt buộc hay không và số ảnh tối thiểu ghi theo từng màn hình (trước/sau trưng bày・giao hàng tối thiểu 1 ảnh, sự cố tùy chọn, biên lai đỗ xe 1 ảnh bắt buộc). Ảnh sự cố xem được ở chi tiết giao hàng của 運営, lưu 12 tháng."],
        ],
        "msgs": ["E441"],
    },
    "P-ACK": {
        "name": ["「ESキッチンへ連絡済みです」の確認（ドライバーアプリ）", "Xác nhận \"đã liên hệ ESキッチン\" (app tài xế)"],
        "rules": [
            ["一部の荷物が未確認・差異あり・未配送のまま完了（報告完了）するときは、確認のモーダルを出す（受取 Q310・COOL便 Q311・陳列 Q312）。内容はトラブル（箱数不足・商品不足・誤配送・未配送）として運営に自動で報告されることを伝える",
             "Khi hoàn tất (báo cáo xong) mà còn hàng chưa xác nhận・có chênh lệch・chưa giao thì hiện modal xác nhận (nhận hàng Q310・COOL便 Q311・trưng bày Q312). Nói rõ nội dung được tự động báo cho 運営 dưới dạng sự cố (thiếu thùng・thiếu hàng・giao nhầm・chưa giao)."],
            ["モーダルに「ESキッチンへ連絡済みです。」のチェックを置く。チェックしないと完了のボタンは押せない（台帳 E「連絡済みが必須」）。受取は「未受取分は、ESキッチンへ連絡済みです。」",
             "Trong modal có ô tick 「ESキッチンへ連絡済みです。」. Không tick thì không bấm được nút hoàn tất (台帳 E「連絡済みが必須」). Với nhận hàng: 「未受取分は、ESキッチンへ連絡済みです。」."],
            ["「ESへ電話する」は端末の電話を発信する（発信した事実を記録する）。番号は 050-5784-2777（台帳 F 2026-10-07）",
             "「ESへ電話する」 gọi điện bằng điện thoại của thiết bị (ghi lại việc đã gọi). Số điện thoại 050-5784-2777 (台帳 F 2026-10-07)."],
            ["すべてそろっているときは確認なしで完了する", "Khi mọi thứ đầy đủ thì hoàn tất, không hiện xác nhận."],
        ],
        "msgs": ["Q310", "Q311", "Q312"],
    },
    "P-STEPPER": {
        "name": ["数量の＋／−入力（ドライバーアプリ）", "Nhập số lượng bằng nút ＋/− (app tài xế)"],
        "rules": [
            ["＋／−のボタンで1ずつ増減する（0 未満にはならない）。数字を入れるときは 0〜9,999 の整数（全角は半角に直す）。範囲の外は E12",
             "Tăng/giảm từng 1 bằng nút ＋/− (không xuống dưới 0). Khi nhập số thì là số nguyên 0〜9,999 (toàn góc đổi sang nửa góc). Ngoài khoảng thì E12."],
            ["初期値は画面ごとに書く：廃棄数＝0、棚卸しの実在庫＝理論在庫、陳列の実際数＝予定数。実在庫が理論在庫より多くても送信を止めない（台帳 F 2026-10-07）",
             "Giá trị ban đầu ghi theo từng màn hình: số hủy = 0, tồn thực khi kiểm kê = tồn lý thuyết, số thực tế khi trưng bày = số dự kiến. Tồn thực nhiều hơn tồn lý thuyết vẫn không chặn gửi (台帳 F 2026-10-07)."],
            ["画面ごとの上限（例：廃棄数は理論在庫まで）は画面に書く", "Giới hạn riêng của từng màn hình (ví dụ: số hủy tối đa bằng tồn lý thuyết) ghi trong màn hình."],
        ],
        "msgs": ["E12"],
    },
    "P-BULK": {
        "name": ["一括操作（選択 → 確認 → 結果）", "Thao tác hàng loạt (chọn → xác nhận → kết quả)"],
        "rules": [
            ["一覧の行をチェックして選ぶ。選べない状態の行はチェック欄を無効にし、理由を吹き出し（ツールチップ）で出す。選ぶと「n件選択中」と「選択解除」を出し、1件以上選ぶと一括のボタンが押せる（「すべて選択」は表示中のページだけ）",
             "Chọn bằng cách tick các dòng trong danh sách. Dòng ở trạng thái không chọn được thì vô hiệu ô tick và hiện lý do bằng tooltip. Khi chọn hiện 「n件選択中」 và 「選択解除」, chọn từ 1 dòng thì nút hàng loạt bấm được (「すべて選択」 chỉ áp dụng trang đang hiện)."],
            ["一括のボタンを押すと確認の画面（モーダル）を出す。対象の件数と一覧を見せ、実行できない行は灰色にして理由を添える（例：I303〜I305）。実行できない行があるときは表の上に「エラー：n件」を出す。上書きになる行があれば警告の枠に出す（例：W301）",
             "Bấm nút hàng loạt thì hiện màn hình xác nhận (modal). Hiện số lượng và danh sách đối tượng; dòng không thực hiện được thì tô xám kèm lý do (ví dụ I303〜I305). Có dòng không thực hiện được thì hiện 「エラー：n件」 phía trên bảng. Có dòng bị ghi đè thì hiện trong khung cảnh báo (ví dụ W301)."],
            ["確認のあとの実行は、押したら二重に押せなくする。実行できる行だけを実行する画面（アカウント一括発行）と、1件でも実行できなければ何も変えない画面（配送スタッフの一括設定・E409）は、画面ごとに書く",
             "Sau khi xác nhận, khóa nút khi đã bấm (chống bấm hai lần). Màn hình chỉ thực hiện các dòng làm được (cấp tài khoản hàng loạt) và màn hình không đổi gì nếu có 1 dòng không làm được (gán nhân viên hàng loạt・E409) thì ghi theo từng màn hình."],
            ["結果は、全件成功なら S11「{n}件を{操作名}しました。」、一部が失敗なら W10「n件のうちm件は処理できませんでした」と、失敗した行と理由の一覧を出す。失敗した行は処理しない（メールも送らない）。ボタンは「完了」「再度実行」",
             "Kết quả: tất cả thành công thì S11 「{n}件を{操作名}しました。」, một phần thất bại thì W10 「n件のうちm件は処理できませんでした」 cùng danh sách dòng lỗi và lý do. Dòng lỗi không được xử lý (cũng không gửi email). Nút 「完了」「再度実行」."],
            ["一括のボタンは、その機能の権限がない役割には出さない（P-LIST と同じ）",
             "Nút hàng loạt không hiện với vai trò không có quyền của chức năng đó (giống P-LIST)."],
        ],
        "msgs": ["Q11", "S11", "W10", "E02"],
    },
}
