# -*- coding: utf-8 -*-
"""
画面設計書のデータ：運営管理者Web ＞ マスタ管理 ＞ 委託配送先（一覧・CSV取込）
元：本物の Web（app/ops/masters/consignees・app/ops/_general/gen.ts の consign・lib/csv/master.ts（carriers））、台帳 138・一括変更・運営Web_権限表（委託配送管理）・CSV入出力_定義
番号は画面ごとに通し。タブ・モーダルの状態では、その状態で増える・変わる項目だけ書く。
（運営H2：hong の確認前の提案を含む。提案は DECISIONS で「提案」と書き、open に確認先を残してある）
"""

TITLE = ["委託配送先マスタ（AW_CNSG）", "Master đơn vị vận chuyển ủy thác (AW_CNSG)"]
SHEET = ["委託配送先マスタ", "Master đơn vị vận chuyển ủy thác"]
BASENAME = "画面設計書_AW_CNSG_委託配送先"
IMG_PREFIX = "AW_CNSG"
OUT_DIR = "AW_CNSG_委託配送先"
CODE_NOTE = ["画面コードは規約 <Module(2)>_<Feature(4)>_<Seq(3)>（docs/01_仕様/画面コード規約_20261005.md）。AW＝運営管理者Web、CNSG＝委託配送先",
             "Mã màn hình theo quy ước <Module(2)>_<Feature(4)>_<Seq(3)>. AW = Admin Web, CNSG = Đơn vị vận chuyển ủy thác"]
SITE = "ops"
SYSTEM = {"ja": "運営管理者Web", "vi": "Web quản trị vận hành"}
AUTHOR = "Claude（cloud）／確認：hong"
CREATED = "2026-10-06"
DEMO_FILE = "http://localhost:3000"
LOGIN = {"site": "ops", "loginId": "Ad00010"}
CODE_PATHS = "[\"app/ops/masters/consignees\", \"app/ops/_general\", \"lib/csv/master.ts\", \"lib/ops/general/fromDomain.ts\"]"

DECISIONS = [
    {"date": "2026-10-06", "target": "登録・編集のしかた", "q": ["運営の画面で新規登録・編集の画面（フォーム）を作るか", "Có tạo màn hình đăng ký mới/chỉnh sửa (biểu mẫu) trong màn hình vận hành hay không"], "a": ["作る（プランマスタと同じ：一覧 → 詳細（表示だけ）→ 登録・編集）。CSV取込も残す（一括）。これまでの案「CSV取込だけ」は置き換え。配送スタッフも作る（台帳「ドライバーのログインID」：運営には新規登録の画面を作らず CSV取込 → 置き換え）", "Làm mới (giống master gói dịch vụ: danh sách → chi tiết (chỉ hiển thị) → đăng ký/sửa). Vẫn giữ nhập CSV (hàng loạt). Phương án trước đây 「chỉ nhập CSV」 được thay thế. Cũng làm cho nhân viên giao hàng (「台帳」 'ID đăng nhập của tài xế': trước đây vận hành không có màn hình đăng ký mới mà chỉ nhập CSV → được thay thế)"], "src": "hong 回答 2026-10-06（運営H2 A＝C）・台帳 F・受付簿 No.167"},
    {"date": "2026-10-06", "target": "削除と無効の扱い", "q": ["削除のしかたと、削除・無効にしたときのログイン", "Cách xóa, và việc đăng nhập khi đã xóa hoặc vô hiệu hóa"], "a": ["論理削除（状態＝削除済）。削除できない条件を置く（使用中は削除できない。条件の中身は仕入先＝進行中の発注／倉庫＝在庫・利用中の契約／委託配送先＝利用中の契約・配送予定・所属スタッフ／配送スタッフ＝割り当て済みの配送。hong 確認 2026-10-06）。状態が「削除済」「無効」のアカウントはログインできない", "Xóa logic (trạng thái 削除済). Có điều kiện chặn xóa (đang sử dụng thì không xóa được; nội dung điều kiện: 仕入先 = đơn đặt hàng đang xử lý / 倉庫 = tồn kho・hợp đồng đang dùng / 委託配送先 = hợp đồng・lịch giao đang dùng・nhân viên trực thuộc / 配送スタッフ = lượt giao đã phân công; hong xác nhận 2026-10-06). Tài khoản ở trạng thái 「削除済」「無効」 không đăng nhập được."], "src": "hong 回答 2026-10-06（運営H2 B）・台帳 F・受付簿 No.167"},
    {"date": "2026-10-06", "target": "委託配送先のアカウント案内メール", "q": ["アカウント一括発行のメール", "Email cấp tài khoản hàng loạt"], "a": ["Mail List No.29「委託配送先のアカウント発行」を足した（メイン担当者へ。仕入先の No.26 と同じ形。Excel は hong が貼る）", "Đã thêm Mail List No.29 「委託配送先のアカウント発行」 (gửi cho người phụ trách chính; cùng dạng với No.26 của nhà cung cấp. hong sẽ dán vào Excel)."], "src": "hong 回答 2026-10-06（運営H2）・受付簿 No.168"},
    {"date": "2026-10-06", "target": "区分の書き方", "q": ["区分「路線」の表記（一覧は「路線（中継あり）」・CSV は「路線」）", "Cách ghi phân loại 「路線」 (danh sách ghi 「路線（中継あり）」, CSV ghi 「路線」)"], "a": ["画面もCSVも「路線（中継あり）」にそろえる。取込は短い「路線」も受け付ける", "Thống nhất 「路線（中継あり）」 ở cả màn hình lẫn CSV. Khi nhập vẫn nhận dạng ngắn 「路線」"], "src": "hong 回答 2026-10-06（運営H2 #5）"},
    {"date": "2026-10-06", "target": "アカウント一括発行の文言", "q": ["アカウント一括発行の確認・結果の文言", "Câu chữ xác nhận và kết quả của cấp tài khoản hàng loạt"], "a": ["確認 Q170・成功 S172・発行できなかった行は E240 のモーダルで理由つき（無効／発行済／メールアドレスがない／申込中／却下）", "Xác nhận Q170, thành công S172, các dòng không cấp được hiện ở modal E240 kèm lý do (無効／発行済／メールアドレスがない／申込中／却下)"], "src": "hong 回答 2026-10-06（運営H2 #2）"},
    {"date": "2026-10-06", "target": "権限", "q": ["だれが見られる・操作できるか", "Ai được xem và thao tác"], "a": ["フル権限・システム管理・物流＝CRUD、ほか＝R。一括変更は「一括変更」の権限", "Toàn quyền・quản trị hệ thống・logistics = CRUD, các vai trò khác = R. Thay đổi hàng loạt dùng quyền 「一括変更」"], "src": "運営Web_権限表（委託配送管理）・台帳「一括変更」"},
    {"date": "2026-10-05", "target": "アカウント一括発行", "q": ["委託配送先・仕入先のアカウント一括発行", "Cấp tài khoản hàng loạt cho đơn vị vận chuyển ủy thác・nhà cung cấp"], "a": ["フェーズ2でやる（運営の一覧の「アカウント一括発行」）", "Làm ở giai đoạn 2 (「アカウント一括発行」 trong danh sách phía vận hành)"], "src": "台帳 138"},
    {"date": "2026-10-06", "target": "画面コード", "q": ["画面コード", "Mã màn hình"], "a": ["AW_CNSG_001〜002", "AW_CNSG_001〜002"], "src": "画面コード規約（Feature は Claude 案・hong 確認待ち）"},
]
CHANGES = [{"ver": "1.11", "date": "2026-10-06", "no": "*", "type": "追加", "reason": ["委託配送先マスタの画面設計書を新規に作成（hong の確認済み・受付簿 No.164〜168）", "Tạo mới tài liệu thiết kế màn hình Master đơn vị vận chuyển ủy thác (đã được hong xác nhận, 受付簿 No.164〜168)"], "impact": ["一覧・詳細・登録／編集・CSV取込・アカウント一括発行（Q170・S172・E240）。区分は「路線（中継あり）」にそろえる。削除条件 E243。実装済（受付簿 No.164・167）", "Danh sách, chi tiết, đăng ký/sửa, nhập CSV, cấp tài khoản hàng loạt (Q170・S172・E240). Thống nhất 区分 là 「路線（中継あり）」. Điều kiện xóa E243. Đã triển khai (受付簿 No.164・167)"]}, {"ver": "1.12", "date": "2026-10-06", "no": ["1", "2"], "type": "追加", "reason": ["役割レビュー（BA・QC・UI/UX）の指摘への対応", "Xử lý các góp ý từ review vai trò (BA・QC・UI/UX)"], "impact": ["表示の確認のための状態。動きは変更なし", "Trạng thái để kiểm tra hiển thị. Hành vi không đổi"]}, {"ver": "1.12", "date": "2026-10-06", "no": ["1.4", "1.14", "1.15"], "type": "変更", "reason": ["役割レビュー（BA・QC・UI/UX）の指摘への対応", "Xử lý các góp ý từ review vai trò (BA・QC・UI/UX)"], "impact": ["動きは変更なし（番号の場所と説明の追記）", "Hành vi không đổi (chỉ tách vị trí đánh số và bổ sung mô tả)"], "before": ["「キャンセル／登録・保存」を1項目", "Gộp 「キャンセル／登録・保存」 thành 1 mục"], "after": ["「キャンセル」と「登録・保存」を分ける／新規登録に P-FORM", "Tách 「キャンセル」 và 「登録・保存」 / nút đăng ký mới theo P-FORM"]}, {"ver": "1.17", "date": "2026-10-07", "no": ["1.1", "1.2"], "type": "追加", "reason": ["hong の回答（2026-10-07）への対応", "Xử lý trả lời của hong (2026-10-07)"], "impact": ["パスワード送信のメールを確定（仕入先・委託配送先は Mail List No.30、配送スタッフは No.3 の認証コード）。委託配送先のアカウント発行は Mail List No.29。履歴の変更者はログイン中のアカウント。実装済（受付簿 No.190）", "Chốt email gửi mật khẩu (nhà cung cấp・đơn vị vận chuyển dùng Mail List No.30, nhân viên giao hàng dùng mã xác thực No.3). Cấp tài khoản đơn vị vận chuyển dùng Mail List No.29. Người thay đổi trong lịch sử là tài khoản đang đăng nhập. Đã triển khai (受付簿 No.190)"]}]
HIDE_ALWAYS = []
STATIC_CSS = ""
VIEWER_CSS = ""

SCREENS = [
    {"code": "AW_CNSG_001", "ja": "委託配送先一覧", "vi": "Danh sách đơn vị vận chuyển ủy thác"},
    {"code": "AW_CNSG_002", "ja": "委託配送先 CSV取込", "vi": "Nhập CSV đơn vị vận chuyển ủy thác"},
    {"code": "AW_CNSG_003", "ja": "委託配送先詳細", "vi": "Chi tiết đơn vị vận chuyển ủy thác"},
    {"code": "AW_CNSG_004", "ja": "委託配送先の登録・編集", "vi": "Đăng ký / sửa đơn vị vận chuyển ủy thác"},
]

H = (
    "const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));"
    "const tab=(t)=>[...document.querySelectorAll('.tabs button')].find(b=>(b.textContent||'').trim()===t)?.click();"
    "const clickText=(sel,t,i)=>{const b=[...document.querySelectorAll(sel)].filter(x=>(x.textContent||'').includes(t))[i||0];b&&b.click();};"
)



def V(id, code, ja, vi, url, items, setup="", note=None, full=True, wait=600, login=None):
    v = {"id": id, "code": code, "state": [ja, vi], "url": url, "setup": (H + setup) if setup else "", "full": full, "wait": wait, "note": note or ["", ""], "items": items}
    if login:
        v["login"] = login
    return v


I1 = [
    {"no": "1", "ja": "ヘッダー", "vi": "Header", "sel": ".ph", "kind": "area", "trig": "view", "detail": ["パンくず：マスタ管理 ＞ 委託配送先。見られるのは運営の全役割（フル権限・システム管理・物流は操作もできる。ほかは閲覧のみ：権限表「委託配送管理」）。", "Breadcrumb: マスタ管理 ＞ 委託配送先. Tất cả các vai trò vận hành đều xem được (toàn quyền・quản trị hệ thống・logistics có thể thao tác. Các vai trò khác chỉ xem: bảng quyền 「委託配送管理」)."]},
    {"no": "1.1", "ja": "アカウント一括発行", "vi": "Cấp tài khoản hàng loạt", "sel": ".ph", "kind": "button", "trig": "click", "err": ["Q170", "S172", "E240", "E30"], "detail": ["選んだ委託配送先にアカウントを一括で発行する（一覧の左のチェックで選ぶ。選ばないと押せない。件数を表示）。メイン担当者のメールに、Mail List No.29「委託配送先のアカウント発行」でログイン案内を送る。押すと確認（Q170：「選んだ{n}件のアカウントを発行し、担当者にログイン案内メールを送ります。よろしいですか？」「キャンセル」「発行する」）。成功したら S172（「{n}件のアカウントを発行しました。」）。発行できなかった行があれば、続けて E240 のモーダル（「{m}件は発行できませんでした。」）に一覧で理由を出す：無効／発行済／メールアドレスがない／申込中（承認で発行）／却下。押せるのは作成（create）の権限がある役割だけ。", "Cấp tài khoản hàng loạt cho các đơn vị vận chuyển ủy thác đã chọn (chọn bằng ô tick bên trái; chưa chọn thì không nhấn được; hiện số lượng). Gửi hướng dẫn đăng nhập tới email người phụ trách chính bằng Mail List No.29 「委託配送先のアカウント発行」. Nhấn thì hiện xác nhận (Q170: 「Sẽ cấp {n} tài khoản đã chọn và gửi email hướng dẫn đăng nhập cho người phụ trách. Xác nhận?」 nút 「キャンセル」「発行する」). Thành công hiện S172 (「Đã cấp {n} tài khoản.」). Nếu có dòng không cấp được thì hiện tiếp modal E240 (「Có {m} mục không cấp được.」) liệt kê lý do từng dòng: 無効／発行済／メールアドレスがない／申込中 (duyệt thì cấp)／却下. Chỉ vai trò có quyền tạo (create) mới nhấn được."]},
    {"no": "1.2", "ja": "CSV出力", "vi": "Xuất CSV", "sel": ".ph", "kind": "button", "trig": "click", "pattern": "P-CSV-OUT", "detail": ["ヘッダーの右。委託配送先の全項目（CSV取込と同じ列）（検索条件のとおりの全件）。見られる役割には全員に出す。", "Bên phải header. Toàn bộ mục của đơn vị vận chuyển ủy thác (cùng cột với nhập CSV) (toàn bộ số bản ghi theo điều kiện tìm kiếm). Hiển thị cho tất cả các vai trò được phép xem."]},
    {"no": "1.3", "ja": "CSV取込", "vi": "Nhập CSV", "sel": ".ph", "kind": "button", "trig": "click", "pattern": "P-CSV", "detail": ["CSV取込の画面（/ops/masters/consignees/import）へ。CSV取込の権限（フル権限・システム管理）がない役割には出さない。", "Chuyển đến màn hình nhập CSV (/ops/masters/consignees/import). Không hiển thị với vai trò không có quyền nhập CSV (toàn quyền・quản trị hệ thống)."]},
    {"no": "1.4", "ja": "新規登録", "vi": "Đăng ký mới", "sel": ".ph .btn.pri", "kind": "button", "trig": "click", "pattern": "P-FORM", "detail": ["委託配送先の登録（AW_CNSG_004）へ。登録の権限（フル権限・システム管理）がない役割には出さない。", "Chuyển đến đăng ký đơn vị vận chuyển ủy thác (AW_CNSG_004). Không hiển thị với vai trò không có quyền đăng ký (toàn quyền, quản trị hệ thống)."]},
    {"no": "2", "ja": "検索条件", "vi": "Điều kiện tìm kiếm", "sel": ".card", "kind": "area", "trig": "view", "pattern": "P-LIST", "detail": ["キーワード（委託配送先ID・委託配送先名・住所）／ステータス（本登録・未発行・無効）。区分・対応エリアなどの絞り込みは一覧から外した（列を減らしたため。詳細で見る）。", "Từ khóa (ID đơn vị giao hàng ủy thác・tên đơn vị giao hàng ủy thác・địa chỉ) / Trạng thái (đăng ký chính thức・chưa cấp・vô hiệu). Bộ lọc theo phân loại・khu vực phục vụ... đã bỏ khỏi danh sách (do giảm bớt cột, xem ở chi tiết)."]},
    {"no": "3", "ja": "一覧", "vi": "Danh sách", "sel": ".tbl", "kind": "table", "trig": "view", "pattern": "P-LIST", "err": ["I01"], "detail": ["初期の並びは委託配送先IDの昇順。1ページ 10件。0件は I01。左端のチェックで行を選ぶ（アカウント一括発行用。作成の権限がある役割だけ。無効の行は選べない）。", "Thứ tự ban đầu là ID đơn vị vận chuyển ủy thác tăng dần. 10 dòng mỗi trang. Khi 0 kết quả hiển thị I01. Chọn dòng bằng ô tích ngoài cùng bên trái (dùng cho cấp tài khoản hàng loạt. Chỉ vai trò có quyền tạo. Dòng vô hiệu không chọn được)."]},
    {"no": "3.1", "ja": "委託配送先ID", "vi": "ID đơn vị vận chuyển ủy thác", "sel": ".tbl th::委託配送先ID", "kind": "label", "trig": "view", "detail": ["DE＋5桁（システムが採番）。DE00000＝自社（ES配送便）は一覧に出さない。", "DE + 5 chữ số (hệ thống tự cấp số). DE00000 = nội bộ (ES配送便) không hiển thị trong danh sách."]},
    {"no": "3.2", "ja": "委託配送先名", "vi": "Tên đơn vị vận chuyển ủy thác", "sel": ".tbl .lnk", "kind": "link", "trig": "click", "detail": ["名前は下線つきのリンク。押すと詳細（AW_CNSG_003）へ。", "Tên là liên kết có gạch chân. Nhấn vào sẽ chuyển đến chi tiết (AW_CNSG_003)."]},
    {"no": "3.8b", "ja": "住所", "vi": "Địa chỉ", "sel": ".tbl th::住所", "kind": "label", "trig": "view", "detail": ["委託配送先の住所。長いと一行で切って表示。", "Địa chỉ của điểm giao hàng ủy thác. Nếu dài thì cắt hiển thị trên một dòng."]},
    {"no": "3.8", "ja": "担当者名", "vi": "Tên người phụ trách", "sel": ".tbl th::担当者名", "kind": "label", "trig": "view", "detail": ["メイン担当者の名前。", "Tên của người phụ trách chính."]},
    {"no": "3.9", "ja": "担当者の電話番号", "vi": "Số điện thoại người phụ trách", "sel": ".tbl th::担当者の電話番号", "kind": "label", "trig": "view", "detail": ["半角の数字とハイフン。", "Chữ số và dấu gạch ngang bán góc."]},
    {"no": "3.10", "ja": "ステータス", "vi": "Trạng thái", "sel": ".tbl th::ステータス", "kind": "label", "trig": "view", "detail": ["バッジ：本登録（アカウント有効）／未発行／無効。", "Badge: đã đăng ký chính thức (tài khoản có hiệu lực)／chưa cấp／vô hiệu."]},
    {"no": "3.12", "ja": "操作（契約の一括変更）", "vi": "Thao tác (thay đổi hàng loạt hợp đồng)", "sel": ".tbl .act", "kind": "button", "trig": "click", "detail": ["この配送先の契約を一括変更（無効でない行だけ）。押すと共通の「一括変更」のモーダル（台帳「一括変更」）。中身は共通の設計で書く。押せるのは「一括変更」の権限がある役割だけ。", "Thay đổi hàng loạt hợp đồng của đơn vị giao hàng này (chỉ các dòng không vô hiệu). Bấm vào sẽ mở modal 「一括変更」 chung (「台帳」「一括変更」). Nội dung được viết trong thiết kế chung. Chỉ vai trò có quyền 「一括変更」 mới bấm được."]},
    {"no": "3.13", "ja": "操作（編集・削除）", "vi": "Thao tác (sửa・xóa)", "sel": ".tbl .act", "kind": "button", "trig": "click", "pattern": "P-DEL", "err": ["Q01", "S02", "E30"], "detail": ["鉛筆＝編集（AW_CNSG_004）、ごみ箱＝削除（確認 Q01 → 論理削除して S02）。利用中の契約・配送予定、または所属する配送スタッフがあるときは削除できない（E243）。削除（と状態「無効」）にするとアカウントはログインできなくなる。削除済の行には出さない。操作の権限がない役割には出さない。", "Bút chì = sửa (AW_CNSG_004), thùng rác = xóa (xác nhận Q01 → xóa logic rồi hiện S02). Nếu có hợp đồng・lịch giao hàng đang sử dụng, hoặc có nhân viên giao hàng trực thuộc thì không thể xóa (E243). Khi xóa (và trạng thái 「無効」) thì tài khoản không thể đăng nhập. Không hiển thị ở dòng đã xóa. Không hiển thị với vai trò không có quyền thao tác."]},
    {"no": "4", "ja": "ページ送り", "vi": "Phân trang", "sel": ".pager", "kind": "area", "trig": "view", "pattern": "P-LIST", "detail": ["P-LIST のとおり（10／20／50件）。", "Theo P-LIST (10／20／50 dòng)."]},
]

I2 = [
    {"no": "1", "ja": "ヘッダー", "vi": "Header", "sel": ".ph", "kind": "area", "trig": "view", "pattern": "P-CSV", "err": ["S03", "E34"], "detail": ["見出し「委託配送先 CSV取込」。キャンセルで一覧へ戻る（何も登録しない）。CSV取込の権限（フル権限・システム管理）がある役割だけが開ける（ほかは一覧へ）。モーダルではなく画面（P-CSV）。", "Tiêu đề 「委託配送先 CSV取込」. Hủy thì quay lại danh sách (không đăng ký gì). Chỉ vai trò có quyền nhập CSV (toàn quyền・quản trị hệ thống) mới mở được (vai trò khác bị chuyển về danh sách). Là màn hình chứ không phải modal (P-CSV)."]},
    {"no": "2", "ja": "CSVテンプレートの列（定義。画面には出さない）", "vi": "Các cột của mẫu CSV (định nghĩa. Không hiển thị trên màn hình)", "sel": "-", "kind": "area", "trig": "view", "detail": ["取り込むファイルの列の定義（1行目の見出し・この順。CSV出力と同じ列）。自社（ES配送便）は含まない。", "Định nghĩa các cột của tệp nhập (tiêu đề dòng 1・theo thứ tự này. Cùng cột với xuất CSV). Không bao gồm nội bộ (ES配送便)."]},
    {"no": "2.1", "ja": "委託配送先ID", "vi": "ID đơn vị vận chuyển ủy thác", "sel": "-", "kind": "label", "trig": "view", "detail": ["【空欄＝新規（DE＋5桁で採番）】キー。", "[Để trống = mới (cấp số DE + 5 chữ số)] Khóa."]},
    {"no": "2.2", "ja": "委託配送先名", "vi": "Tên đơn vị vận chuyển ủy thác", "sel": "-", "kind": "label", "trig": "view", "len": "文字列 50", "detail": ["【新規は必須】", "[Bắt buộc khi mới]"]},
    {"no": "2.3", "ja": "区分", "vi": "Phân loại", "sel": "-", "kind": "label", "trig": "view", "detail": ["【新規は必須】委託・引き取り／路線（中継あり）。一覧の表示と同じ書き方。取込では短い「路線」も「路線（中継あり）」として受け付ける。CSV出力は常に「路線（中継あり）」。", "[Bắt buộc khi tạo mới] 委託・引き取り／路線（中継あり）. Cùng cách ghi với danh sách. Khi nhập cũng nhận dạng ngắn 「路線」 như 「路線（中継あり）」. CSV xuất luôn ghi 「路線（中継あり）」."]},
    {"no": "2.4", "ja": "対応エリア", "vi": "Khu vực phụ trách", "sel": "-", "kind": "label", "trig": "view", "detail": ["【任意】都道府県（複数）。これまでの地方名（関東など）を書いたときは、その地方の都道府県に展開して取り込む。", "[Tùy chọn] Tỉnh/thành (nhiều giá trị). Nếu nhập tên vùng trước đây (như Kanto) thì khai triển thành các tỉnh/thành của vùng đó khi nhập vào."]},
    {"no": "2.5", "ja": "配送不可曜日", "vi": "Ngày không giao hàng", "sel": "-", "kind": "label", "trig": "view", "detail": ["【任意】月〜日・祝日（複数）。これまでの「対応曜日」を置き換え。", "[Tùy chọn] Thứ Hai〜Chủ Nhật・ngày lễ (nhiều giá trị). Thay thế 「対応曜日」 trước đây."]},
    {"no": "2.6", "ja": "対応エリアに関する備考", "vi": "Ghi chú về khu vực phục vụ", "sel": "-", "kind": "label", "trig": "view", "len": "文字列 500", "detail": ["【任意】", "[Tùy chọn]"]},
    {"no": "2.7", "ja": "保有車両", "vi": "Phương tiện sở hữu", "sel": "-", "kind": "label", "trig": "view", "detail": ["【任意】軽四車両／保冷車あり／冷凍車あり ほか（複数）。", "[Tùy chọn] Xe tải nhẹ (kei)／có xe lạnh／có xe đông lạnh, v.v. (nhiều giá trị)."]},
    {"no": "2.8", "ja": "冷凍ボックスのレンタル希望", "vi": "Mong muốn thuê hộp đông lạnh", "sel": "-", "kind": "label", "trig": "view", "detail": ["【任意】不要／要。", "[Tùy chọn] Không cần／Cần."]},
    {"no": "2.9", "ja": "冷蔵ボックスのレンタル希望", "vi": "Mong muốn thuê hộp lạnh", "sel": "-", "kind": "label", "trig": "view", "detail": ["【任意】不要／要。", "[Tùy chọn] Không cần／Cần."]},
    {"no": "2.10", "ja": "冷蔵保管スペース", "vi": "Không gian bảo quản lạnh", "sel": "-", "kind": "label", "trig": "view", "detail": ["【任意】あり／なし。", "[Tùy chọn] Có／Không."]},
    {"no": "2.11", "ja": "車両・設備情報に関する備考", "vi": "Ghi chú về phương tiện・thiết bị", "sel": "-", "kind": "label", "trig": "view", "len": "文字列 500", "detail": ["【任意】", "[Tùy chọn]"]},
    {"no": "2.12", "ja": "支払条件", "vi": "Điều kiện thanh toán", "sel": "-", "kind": "label", "trig": "view", "detail": ["【任意】月末締め翌月末払い ほか。", "[Tùy chọn] Chốt cuối tháng, thanh toán cuối tháng sau, v.v."]},
    {"no": "2.13", "ja": "温度帯", "vi": "Nhóm nhiệt độ", "sel": "-", "kind": "label", "trig": "view", "detail": ["【任意】冷蔵／冷凍／常温／資材（複数）。", "[Tùy chọn] Lạnh／đông lạnh／thường／vật tư (nhiều giá trị)."]},
    {"no": "2.14", "ja": "1件の支払額", "vi": "Số tiền chi trả cho mỗi đơn", "sel": "-", "kind": "label", "trig": "view", "detail": ["【任意】金額。これから納品する区間に使う（納品済みの区間は納品したときの額のまま。取込の確認で注意を出す）。", "[Tùy chọn] Số tiền. Áp dụng cho chặng sắp giao (chặng đã giao giữ nguyên số tiền tại thời điểm giao. Có cảnh báo ở bước xác nhận khi nhập)."]},
    {"no": "2.15", "ja": "エリア別の支払額", "vi": "Số tiền chi trả theo khu vực", "sel": "-", "kind": "label", "trig": "view", "detail": ["【任意】例：関東:2000・中部:2300。空欄＝なし。", "[Tùy chọn] Ví dụ: 関東:2000・中部:2300. Để trống = không có."]},
    {"no": "2.16", "ja": "追跡URLのひな形", "vi": "Mẫu URL theo dõi", "sel": "-", "kind": "label", "trig": "view", "len": "文字列 255", "detail": ["【任意】http:// か https:// で始まる（E10）。", "[Tùy chọn] Bắt đầu bằng http:// hoặc https:// (E10)."]},
    {"no": "2.17", "ja": "状態", "vi": "Trạng thái", "sel": "-", "kind": "label", "trig": "view", "detail": ["【任意】有効／無効。", "[Tùy chọn] Có hiệu lực／vô hiệu."]},
    {"no": "2.18", "ja": "担当者名", "vi": "Tên người phụ trách", "sel": "-", "kind": "label", "trig": "view", "detail": ["【読取専用】書いても無視。", "[Chỉ đọc] Có ghi cũng bị bỏ qua."]},
    {"no": "2.19", "ja": "アカウントの状態", "vi": "Trạng thái tài khoản", "sel": "-", "kind": "label", "trig": "view", "detail": ["【読取専用】書いても無視（未発行／本登録など）。", "[Chỉ đọc] Có ghi cũng bị bỏ qua (chưa cấp／đã đăng ký chính thức, v.v.)."]},
]

I3 = [
    {"no": "1", "ja": "ヘッダー", "vi": "Header", "sel": "-", "kind": "area", "trig": "view", "detail": ["パンくず：マスタ管理 ＞ 委託配送先 ＞ 委託配送先詳細。タイトル「委託配送先詳細 ID」。右に「削除」「パスワード送信」「編集」（権限のある役割だけ。削除済の委託配送先には出さない）。", "Breadcrumb: Quản lý master ＞ Đơn vị giao hàng ủy thác ＞ Chi tiết đơn vị giao hàng ủy thác. Tiêu đề 「委託配送先詳細 ID」. Bên phải có 「削除」「パスワード送信」「編集」 (chỉ vai trò có quyền; không hiển thị với đơn vị đã xóa)."]},
    {"no": "1.1", "ja": "削除", "vi": "Xóa", "sel": "-", "kind": "button", "trig": "click", "pattern": "P-DEL", "err": ["Q01", "S02", "E30"], "detail": ["削除の確認（Q01）→ 論理削除（P-DEL）。使用中は削除できない。削除すると、この委託配送先のアカウントはログインできなくなる。", "Xác nhận xóa (Q01) → xóa logic (P-DEL). Đang sử dụng thì không xóa được. Sau khi xóa, tài khoản của đơn vị giao hàng ủy thác này không đăng nhập được."]},
    {"no": "1.2", "ja": "パスワード送信", "vi": "Gửi mật khẩu", "sel": "-", "kind": "button", "trig": "click", "err": ["Q173", "S173", "E30"], "cond": ["アカウントが有効（または発行済・ログイン前）のとき", "Khi tài khoản có hiệu lực (hoặc đã cấp・chưa đăng nhập)"], "detail": ["メイン担当者のメールアドレスへ、パスワード設定のご案内を送る（仕入先・委託配送先は Mail List No.30。配送スタッフはドライバーアプリの再設定と同じ認証コード＝No.3）。押すと確認（Q173）→ 送ったら S173。アカウントが「未発行」「無効」「削除済」のときは押せない。", "Gửi hướng dẫn đặt mật khẩu tới email người phụ trách chính (nhà cung cấp・đơn vị vận chuyển ủy thác dùng Mail List No.30; nhân viên giao hàng dùng mã xác thực giống đặt lại mật khẩu trên app tài xế = No.3). Nhấn thì hiện xác nhận (Q173) → gửi xong hiện S173. Không nhấn được khi tài khoản là 「未発行」「無効」「削除済」."]},
    {"no": "1.3", "ja": "編集", "vi": "Sửa", "sel": "-", "kind": "button", "trig": "click", "detail": ["登録・編集の画面（編集）へ。編集の権限がない役割には出さない。", "Chuyển sang màn hình đăng ký・sửa (sửa). Không hiển thị với vai trò không có quyền sửa."]},
    {"no": "2", "ja": "タブ", "vi": "Tab", "sel": "-", "kind": "tab", "trig": "click", "pattern": "P-TAB", "detail": ["タブ：基本情報・ES配送費・変更履歴。初期は「基本情報」。", "Tab: Thông tin cơ bản・Phí giao hàng ES・Lịch sử thay đổi. Mặc định là 「基本情報」."]},
    {"no": "3", "ja": "基本情報（表示）", "vi": "Thông tin cơ bản (hiển thị)", "sel": "-", "kind": "area", "trig": "view", "detail": ["委託配送先ID・名・カナ・ステータス・区分・温度帯・追跡URLのひな形・支払条件・備考・保冷バッグ（貸与中の数）。すべて表示だけ。", "ID điểm giao hàng ủy thác・tên・kana・trạng thái・loại・nhóm nhiệt độ・mẫu URL theo dõi・điều kiện thanh toán・ghi chú・túi giữ lạnh (số đang cho mượn). Tất cả chỉ hiển thị."]},
    {"no": "4", "ja": "対応エリア（表示）", "vi": "Khu vực đáp ứng (hiển thị)", "sel": "-", "kind": "area", "trig": "view", "detail": ["対応エリア（都道府県のチップ）・配送不可曜日・対応エリアに関する備考。", "Khu vực đáp ứng (chip tỉnh/thành)・thứ không giao được・ghi chú về khu vực đáp ứng."]},
    {"no": "5", "ja": "車両・設備情報（表示）", "vi": "Thông tin phương tiện・thiết bị (hiển thị)", "sel": "-", "kind": "area", "trig": "view", "detail": ["保有車両・冷凍ボックスのレンタル希望・冷蔵ボックスのレンタル希望・冷蔵保管スペース・車両・設備情報に関する備考。", "Phương tiện sở hữu・mong muốn thuê hộp đông lạnh・mong muốn thuê hộp lạnh・chỗ bảo quản lạnh・ghi chú về thông tin phương tiện・thiết bị."]},
    {"no": "6", "ja": "住所（表示）", "vi": "Địa chỉ (hiển thị)", "sel": "-", "kind": "area", "trig": "view", "detail": ["郵便番号・都道府県・市区町村・町域・番地・建物・部屋番号・電話番号・Fax番号。", "Mã bưu điện・tỉnh/thành・quận/huyện・phường/xã・số nhà・tòa nhà・số phòng・số điện thoại・số Fax."]},
    {"no": "7", "ja": "担当者（表示）", "vi": "Người phụ trách (hiển thị)", "sel": "-", "kind": "area", "trig": "view", "detail": ["メイン担当者・サブ担当者の行（区分・担当者名・フリガナ・メールアドレス・TEL）。", "Các dòng người phụ trách chính・phụ (phân loại・tên người phụ trách・furigana・email・TEL)."]},
    {"no": "8", "ja": "この配送先の契約を一括変更", "vi": "Thay đổi hợp đồng hàng loạt cho điểm giao hàng này", "sel": "-", "kind": "area", "trig": "view", "detail": ["詳細に置く既存のボタン（共通の「一括変更」モーダル）。", "Nút có sẵn đặt ở chi tiết (modal 「一括変更」 dùng chung)."]},
]

I4 = [
    {"no": "1", "ja": "登録・編集の画面", "vi": "Màn hình đăng ký・sửa", "sel": "-", "kind": "area", "trig": "view", "pattern": "P-FORM", "err": ["Q02", "S01", "E30", "E31"], "detail": ["タイトル「委託配送先の登録」「委託配送先の編集」。一覧の「新規登録」と、詳細の「編集」（一覧の鉛筆）から開く。タブは置かない（詳細だけ）。保存は画面の 登録／保存 の1つだけ。入力を変えてキャンセルしたら Q02。成功したら S01 を出して詳細へ戻る（新規は登録した ID の詳細）。", "Tiêu đề 「委託配送先の登録」「委託配送先の編集」. Mở từ 「新規登録」 ở danh sách và 「編集」 ở chi tiết (biểu tượng bút chì ở danh sách). Không đặt tab (chỉ có ở chi tiết). Lưu chỉ bằng 1 nút trên màn hình: Đăng ký / Lưu. Nếu đã thay đổi nhập liệu rồi hủy thì hiện Q02. Thành công thì hiện S01 và quay về chi tiết (đăng ký mới thì về chi tiết của ID vừa đăng ký)."]},
    {"no": "2", "ja": "基本情報", "vi": "Thông tin cơ bản", "sel": "-", "kind": "area", "trig": "view", "detail": ["基本情報のカード。", "Thẻ thông tin cơ bản."]},
    {"no": "2.1", "ja": "委託配送先ID", "vi": "ID đơn vị vận chuyển ủy thác", "sel": "-", "kind": "label", "trig": "view", "detail": ["DE＋5桁（システムが採番）。登録のときは表示しない。DE00000＝自社（ES配送便）は対象外。", "DE + 5 chữ số (hệ thống tự cấp số). Không hiển thị khi đăng ký. DE00000 = tự công ty (ES配送便) nằm ngoài đối tượng."]},
    {"no": "2.2", "ja": "委託配送先名", "vi": "Tên đơn vị vận chuyển ủy thác", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E04"], "req": "○", "len": "文字列 60", "ex": ["〇〇運送株式会社", "Ví dụ của mục 'Tên đơn vị vận chuyển ủy thác': tên công ty vận tải (dạng 'tên + công ty cổ phần vận tải')."], "detail": ["委託配送会社の名前。", "Tên của công ty giao hàng ủy thác."]},
    {"no": "2.3", "ja": "カナ", "vi": "Kana", "sel": "-", "kind": "text", "trig": "input", "err": ["E03", "E04"], "req": "－", "len": "文字列 60", "ex": ["マルマルウンソウカブシキガイシャ", "Marumaru Unsou Kabushiki Gaisha"], "detail": ["全角カタカナ。", "Katakana toàn chiều rộng."]},
    {"no": "2.4", "ja": "ステータス", "vi": "Trạng thái", "sel": "-", "kind": "select", "trig": "select", "err": ["E01"], "req": "○", "len": ["選択（有効／無効）", "Chọn (hiệu lực / vô hiệu)"], "ex": ["有効", "Hiệu lực"], "detail": ["新規は「有効」。「無効」にするとログインできなくなる。", "Đăng ký mới là 「有効」. Khi đặt 「無効」 thì không thể đăng nhập."]},
    {"no": "2.5", "ja": "区分", "vi": "Phân loại", "sel": "-", "kind": "select", "trig": "select", "err": ["E01"], "req": "○", "len": ["選択（委託・引き取り／路線（中継あり））", "Chọn (ủy thác, lấy hàng / tuyến (có trung chuyển))"], "ex": ["路線（中継あり）", "Ví dụ của mục 'Phân loại': giá trị chọn loại hình đơn vị vận chuyển, ở đây là tuyến (có trung chuyển)."], "detail": ["", ""]},
    {"no": "2.8", "ja": "温度帯", "vi": "Nhóm nhiệt độ", "sel": "-", "kind": "check", "trig": "check", "req": "－", "len": ["選択（複数）", "Chọn (nhiều)"], "ex": ["冷蔵", "Ví dụ của mục 'Dải nhiệt độ': dải nhiệt độ bảo quản mà đơn vị xử lý được, ở đây là lạnh (mát)."], "detail": ["冷蔵／冷凍／常温／資材。", "Lạnh (mát)／Đông lạnh／Nhiệt độ thường／Vật tư."]},
    {"no": "2.9", "ja": "追跡URLのひな形", "vi": "Mẫu URL theo dõi", "sel": "-", "kind": "text", "trig": "input", "err": ["E10"], "req": "－", "len": "文字列 255", "ex": ["https://track.example.jp/?no={追跡番号}", "Ví dụ của mục 'Mẫu URL theo dõi': mẫu URL trang theo dõi vận đơn, trong đó phần {追跡番号} (mã theo dõi) sẽ được thay bằng mã theo dõi thực tế."], "detail": ["荷物の追跡ページの URL のひな形。http:// か https:// で始まる。", "Mẫu URL của trang theo dõi hàng hóa. Bắt đầu bằng http:// hoặc https://."]},
    {"no": "2.10", "ja": "支払条件", "vi": "Điều kiện thanh toán", "sel": "-", "kind": "select", "trig": "select", "open": ["支払条件の選択肢の全部（月末締め翌月末払い以外は仮）", "hong"], "err": ["E01"], "req": "○", "len": ["選択（月末締め翌月末払い ほか）", "Chọn (chốt cuối tháng, trả cuối tháng sau, v.v.)"], "ex": ["月末締め翌月末払い", "Chốt cuối tháng, thanh toán cuối tháng sau"], "detail": ["選択式。確認済の選択肢は「月末締め翌月末払い」。ほかの選択肢は仮。", "Dạng chọn. Lựa chọn đã xác nhận là 「月末締め翌月末払い」. Các lựa chọn khác là tạm."]},
    {"no": "2.11", "ja": "備考", "vi": "Ghi chú", "sel": "-", "kind": "textarea", "trig": "input", "err": ["E04"], "req": "－", "len": "文字列 500", "ex": ["午前着の指定は前日までに連絡", "Giao buổi sáng thì liên hệ trước một ngày"], "detail": ["運営だけが見るメモ。複数行。", "Ghi chú chỉ bộ phận vận hành xem. Nhiều dòng."]},
    {"no": "3", "ja": "対応エリア", "vi": "Khu vực phụ trách", "sel": "-", "kind": "area", "trig": "view", "detail": ["配送会社の申込フォーム（ステップ2）と同じ項目（hong 2026-10-07）。", "Các mục giống với form đăng ký của công ty giao hàng (bước 2) (hong 2026-10-07)."]},
    {"no": "3.1", "ja": "対応エリア", "vi": "Khu vực phụ trách", "sel": "-", "kind": "check", "trig": "check", "err": ["E02"], "req": "○", "len": ["選択（複数・都道府県）", "Chọn (nhiều, tỉnh/thành)"], "ex": ["東京都・千葉県・神奈川県", "Tokyo・Chiba・Kanagawa"], "detail": ["地方ごとにまとめた都道府県のリストから選ぶ（北海道／東北／関東／中部／近畿（関西）／中国／四国／九州・沖縄）。選んだものはチップ（×で外す・多いと「+n件」）。地方の行のチェックで、その地方の都道府県をまとめて選ぶ。「すべて選択」「選択クリア」あり。※一部でも対応可能なエリアを選択してください。1つ以上必須。これまでの「地方」の単位を置き換え。", "Chọn từ danh sách tỉnh/thành gom theo vùng (Hokkaido／Tohoku／Kanto／Chubu／Kinki (Kansai)／Chugoku／Shikoku／Kyushu・Okinawa). Mục đã chọn hiển thị dạng chip (bấm × để bỏ・nếu nhiều thì hiện 「+n件」). Tick ở dòng vùng sẽ chọn gộp các tỉnh/thành của vùng đó. Có 「すべて選択」「選択クリア」. ※一部でも対応可能なエリアを選択してください. Bắt buộc từ 1 mục trở lên. Thay thế đơn vị 「地方」 trước đây."]},
    {"no": "3.2", "ja": "配送不可曜日", "vi": "Ngày không giao hàng", "sel": "-", "kind": "check", "trig": "check", "req": "－", "len": ["選択（月・火・水・木・金・土・日・祝日）", "Chọn (T2, T3, T4, T5, T6, T7, CN, ngày lễ)"], "ex": ["土・日・祝日", "Thứ Bảy・Chủ Nhật・Ngày lễ"], "detail": ["配送できない曜日。これまでの「対応曜日」を置き換え（反対の持ち方）。", "Các thứ không giao hàng được. Thay thế 「対応曜日」 trước đây (cách lưu ngược lại)."]},
    {"no": "3.3", "ja": "対応エリアに関する備考", "vi": "Ghi chú về khu vực phục vụ", "sel": "-", "kind": "textarea", "trig": "input", "err": ["E04"], "req": "－", "len": "文字列 500", "ex": ["小回り、配送の融通が利く", "Linh hoạt, giao hàng dễ điều chỉnh"], "detail": ["対応エリアの補足。複数行。", "Bổ sung về khu vực đáp ứng. Nhiều dòng."]},
    {"no": "4", "ja": "車両・設備情報", "vi": "Thông tin phương tiện・thiết bị", "sel": "-", "kind": "area", "trig": "view", "detail": ["配送会社の申込フォーム（ステップ2）と同じ項目。", "Các mục giống với form đăng ký của công ty giao hàng (bước 2)."]},
    {"no": "4.1", "ja": "保有車両", "vi": "Phương tiện sở hữu", "sel": "-", "kind": "check", "trig": "check", "open": ["保有車両の選択肢の全部（軽四車両・保冷車あり・冷凍車あり以外は仮）", "hong"], "err": ["E02"], "req": "○", "len": ["選択（複数）：軽四車両・保冷車あり・冷凍車あり ほか", "Chọn (nhiều): xe kei, có xe lạnh, có xe đông lạnh, v.v."], "ex": ["軽四車両・保冷車あり・冷凍車あり", "Xe tải nhẹ (kei)・Có xe lạnh・Có xe đông lạnh"], "detail": ["複数選べる（チップに×）。1つ以上必須。確認済の選択肢は「軽四車両」「保冷車あり」「冷凍車あり」。ほかの選択肢（普通車両・2tトラック・4tトラック）は仮。", "Chọn được nhiều (chip có ×). Bắt buộc từ 1 mục trở lên. Lựa chọn đã xác nhận là 「軽四車両」「保冷車あり」「冷凍車あり」. Các lựa chọn khác (xe thường・xe tải 2t・xe tải 4t) là tạm."]},
    {"no": "4.2", "ja": "冷凍ボックスのレンタル希望", "vi": "Mong muốn thuê hộp đông lạnh", "sel": "-", "kind": "select", "trig": "select", "err": ["E01"], "req": "○", "len": ["ラジオ（不要／要）", "Radio (không cần / cần)"], "ex": ["不要", "Không cần"], "detail": ["", ""]},
    {"no": "4.3", "ja": "冷蔵ボックスのレンタル希望", "vi": "Mong muốn thuê hộp lạnh", "sel": "-", "kind": "select", "trig": "select", "err": ["E01"], "req": "○", "len": ["ラジオ（不要／要）", "Radio (không cần / cần)"], "ex": ["不要", "Không cần"], "detail": ["", ""]},
    {"no": "4.4", "ja": "冷蔵保管スペース", "vi": "Không gian bảo quản lạnh", "sel": "-", "kind": "select", "trig": "select", "err": ["E01"], "req": "○", "len": ["ラジオ（あり／なし）", "Radio (có / không)"], "ex": ["あり", "Có"], "detail": ["", ""]},
    {"no": "4.5", "ja": "車両・設備情報に関する備考", "vi": "Ghi chú về phương tiện・thiết bị", "sel": "-", "kind": "textarea", "trig": "input", "err": ["E04"], "req": "－", "len": "文字列 500", "ex": ["小回り、配送の融通が利く", "Linh hoạt, giao hàng dễ điều chỉnh"], "detail": ["車両・設備の補足。複数行。", "Bổ sung về phương tiện・thiết bị. Nhiều dòng."]},
    {"no": "5", "ja": "住所", "vi": "Địa chỉ", "sel": "-", "kind": "area", "trig": "view", "detail": ["委託配送先の住所（1件）。", "Địa chỉ của đơn vị giao hàng ủy thác (1 mục)."]},
    {"no": "5.1", "ja": "郵便番号", "vi": "Mã bưu chính", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E05"], "req": "○", "len": "文字列 8", "ex": ["105-0011", "Ví dụ của mục 'Mã bưu điện': mã bưu điện 7 chữ số của Nhật, có dạng 3-4 chữ số cách nhau bằng gạch nối."], "detail": ["数字7桁。ハイフンは任意（保存は 123-4567）。", "7 chữ số. Dấu gạch nối là tùy chọn (khi lưu sẽ ở dạng 123-4567)."]},
    {"no": "5.1b", "ja": "住所検索", "vi": "Tìm địa chỉ", "sel": "-", "kind": "button", "trig": "click", "detail": ["郵便番号から、都道府県・市区町村・町域・番地を入れる（入れたあとも直せる）。見つからないとき I01。", "Từ mã bưu điện, tự điền tỉnh/thành・quận/huyện・phường/xã・số nhà (nhập xong vẫn sửa được). Nếu không tìm thấy thì I01."]},
    {"no": "5.2", "ja": "都道府県", "vi": "Tỉnh thành", "sel": "-", "kind": "select", "trig": "select", "err": ["E01"], "req": "○", "len": ["選択（47都道府県）", "Chọn (47 tỉnh)"], "ex": ["東京都", "Ví dụ của mục 'Tỉnh/thành phố (todofuken)': tên tỉnh/thành của Nhật (ở đây là một thành phố trực thuộc trung ương)."], "detail": ["", ""]},
    {"no": "5.3", "ja": "市区町村", "vi": "Quận huyện thành phố", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E04"], "req": "○", "len": "文字列 255", "ex": ["港区", "Ví dụ của mục 'Quận/huyện/thành phố': tên quận, thành phố hoặc thị trấn thuộc tỉnh/thành đã chọn."], "detail": ["", ""]},
    {"no": "5.4", "ja": "町域・番地", "vi": "Phường/xã・số nhà", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E04"], "req": "○", "len": "文字列 255", "ex": ["芝公園1-2-3", "Shibakoen 1-2-3"], "detail": ["", ""]},
    {"no": "5.5", "ja": "建物・部屋番号", "vi": "Tòa nhà・số phòng", "sel": "-", "kind": "text", "trig": "input", "err": ["E04"], "req": "－", "len": "文字列 255", "ex": ["〇〇ビル5F", "Tòa nhà XX tầng 5"], "detail": ["", ""]},
    {"no": "5.6", "ja": "電話番号", "vi": "Số điện thoại", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E06"], "req": "○", "len": "文字列 20", "ex": ["03-1234-5678", "Ví dụ của mục 'Số điện thoại': số điện thoại cố định của Nhật, gồm chữ số và dấu gạch nối (mã vùng-số)."], "detail": ["数字とハイフン。", "Chữ số và dấu gạch nối."]},
    {"no": "5.7", "ja": "Fax番号", "vi": "Số Fax", "sel": "-", "kind": "text", "trig": "input", "err": ["E06"], "req": "－", "len": "文字列 20", "ex": ["03-1234-5679", "03-1234-5679"], "detail": ["数字とハイフン。", "Chữ số và dấu gạch nối."]},
    {"no": "6", "ja": "担当者（表）", "vi": "Người phụ trách (dạng bảng)", "sel": "-", "kind": "area", "trig": "view", "detail": ["担当者を表で入れる。「メイン担当者」はちょうど1行（必須）、「サブ担当者」は0行以上（「行を追加」「行を削除」）。メイン担当者のメールアドレスがログイン案内・パスワード送信の宛先。", "Nhập người phụ trách dạng bảng. 「メイン担当者」 đúng 1 dòng (bắt buộc), 「サブ担当者」 từ 0 dòng trở lên (「行を追加」「行を削除」). Email của người phụ trách chính là địa chỉ nhận hướng dẫn đăng nhập và gửi mật khẩu."]},
    {"no": "6.1", "ja": "区分", "vi": "Phân loại", "sel": "-", "kind": "select", "trig": "select", "err": ["E01"], "req": "○", "len": ["選択（メイン担当者／サブ担当者）", "Chọn (người phụ trách chính / phụ)"], "ex": ["メイン担当者", "Người phụ trách chính"], "detail": ["メイン担当者は1行だけ。2行目からはサブ担当者。", "Người phụ trách chính chỉ có 1 dòng. Từ dòng thứ 2 là người phụ trách phụ."]},
    {"no": "6.2", "ja": "担当者名", "vi": "Tên người phụ trách", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E04"], "req": "○", "len": "文字列 60", "ex": ["担当 太郎", "Tanto Taro"], "detail": ["担当者の名前。", "Tên của người phụ trách."]},
    {"no": "6.3", "ja": "フリガナ", "vi": "Furigana", "sel": "-", "kind": "text", "trig": "input", "err": ["E03", "E04"], "req": "－", "len": "文字列 60", "ex": ["タントウ タロウ", "Tantou Tarou"], "detail": ["全角カタカナ。", "Katakana toàn chiều rộng."]},
    {"no": "6.4", "ja": "メールアドレス", "vi": "Địa chỉ email", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E07"], "req": "○", "len": "文字列 160", "ex": ["sample@example.jp", "sample@example.jp"], "detail": ["メール形式。メイン担当者のメールがアカウント案内の宛先。", "Định dạng email. Email của người phụ trách chính là địa chỉ nhận thông báo tài khoản."]},
    {"no": "6.5", "ja": "TEL", "vi": "TEL", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E06"], "req": "○", "len": "文字列 20", "ex": ["012-345-6789", "012-345-6789"], "detail": ["数字とハイフン。", "Chữ số và dấu gạch nối."]},
    {"no": "6.6", "ja": "行を追加／行を削除", "vi": "Thêm dòng / Xóa dòng", "sel": "-", "kind": "button", "trig": "click", "detail": ["サブ担当者の行を足す・消す（メイン担当者の行は消せない）。", "Thêm/xóa dòng người phụ trách phụ (không xóa được dòng người phụ trách chính)."]},
    {"no": "7", "ja": "キャンセル", "vi": "Hủy bỏ", "sel": "-", "kind": "button", "trig": "click", "err": ["Q02"], "detail": ["一覧へ戻る（編集のときは詳細へ）。入力を変えていたら Q02（キャンセル／破棄）。", "Quay về danh sách (khi đang sửa thì quay về chi tiết). Nếu đã thay đổi nội dung nhập thì hiển thị Q02 (Hủy / Bỏ thay đổi)."]},
    {"no": "8", "ja": "登録・保存", "vi": "Đăng ký・Lưu", "sel": "-", "kind": "button", "trig": "click", "err": ["S01", "E30", "E31"], "detail": ["押すとまとめてチェック（項目の下にエラー・赤枠。保存ボタンの横に「保存できません（n件）」）。エラーがなければ保存して S01。ボタンは押したら無効にする。ほかの人が先に保存していたら E31（P-FORM）。", "Khi bấm sẽ kiểm tra toàn bộ cùng lúc (lỗi và viền đỏ bên dưới từng mục; bên cạnh nút lưu hiển thị 「保存できません（n件）」). Nếu không có lỗi thì lưu và hiển thị S01. Nút bị vô hiệu hóa sau khi bấm. Nếu người khác đã lưu trước thì hiển thị E31 (P-FORM)."]},
]

I5 = [
    {"no": "1", "ja": "削除の確認", "vi": "Xác nhận xóa", "sel": ".modal", "kind": "modal", "trig": "click", "pattern": "P-DEL", "err": ["Q01", "S02", "E30"], "detail": ["タイトル「削除」。「キャンセル」「削除する」。「削除する」で論理削除（状態＝削除済）して S02。一覧から外れ、検索条件で「削除済」を選ぶと表示される。削除すると、この委託配送先のアカウントはログインできなくなる。", "Tiêu đề 「削除」. Có 「キャンセル」「削除する」. Khi nhấn 「削除する」 thì xóa logic (trạng thái = đã xóa) và hiện S02. Bị loại khỏi danh sách; chọn 「削除済」 ở điều kiện tìm kiếm thì sẽ hiển thị. Khi xóa, tài khoản của đơn vị vận chuyển ủy thác này không thể đăng nhập."]},
]

I6 = [
    {"no": "1", "ja": "削除できない", "vi": "Không thể xóa", "sel": ".ov .mbox", "kind": "modal", "trig": "click", "err": ["E243"], "detail": ["利用中の契約・配送予定、または所属する配送スタッフ（削除済を除く）が n件あるとき（E243）は削除できない。モーダルの「閉じる」で閉じる。条件は hong 確認済み（2026-10-06）。", "Khi có n hợp đồng/lịch giao đang dùng, hoặc nhân viên giao hàng trực thuộc (không tính đã xóa) (E243) thì không xóa được. Đóng modal bằng 「閉じる」. Điều kiện đã được hong xác nhận (2026-10-06)."]},
]

I7 = [
    {"no": "1", "ja": "ES配送費のタブ", "vi": "Tab phí giao hàng ES", "sel": "-", "kind": "tab", "trig": "click", "detail": ["詳細の「ES配送費」タブ。この委託配送先に払う配送費の表。", "Tab 「ES配送費」 ở chi tiết. Bảng phí giao hàng trả cho đơn vị giao hàng ủy thác này."]},
    {"no": "2", "ja": "絞り込み", "vi": "Bộ lọc", "sel": "-", "kind": "area", "trig": "view", "detail": ["都道府県名／市郡名／区町村名／類似住所の有無。", "Tên tỉnh/thành / tên thành phố・quận / tên phường・xã / có hay không địa chỉ tương tự."]},
    {"no": "3", "ja": "ES配送費の表", "vi": "Bảng phí giao hàng ES", "sel": "-", "kind": "table", "trig": "view", "pattern": "P-LIST", "err": ["I01"], "detail": ["列：都道府県名・市郡名・区町村名・実績有無・委託費用・地域加算（配送1回あたり）・地域加算（配送2回あたり）・備考欄。1ページ 10件。0件は I01。", "Cột: tên tỉnh/thành・tên thành phố・quận・tên phường・xã・có thực tích hay không・phí ủy thác・phụ phí khu vực (mỗi 1 lần giao)・phụ phí khu vực (mỗi 2 lần giao)・cột ghi chú. 10 dòng mỗi trang. 0 bản ghi hiện I01."]},
    {"no": "4", "ja": "ES配送費のCSV取込／出力", "vi": "Nhập／xuất CSV phí giao hàng ES", "sel": "-", "kind": "button", "trig": "click", "detail": ["ES配送費は CSV取込・CSV出力で更新する（画面で1行ずつは直さない）。変更は変更履歴に「CSV取込」で残る（hong 2026-10-07 確認済）。", "Phí giao hàng ES được cập nhật bằng nhập CSV・xuất CSV (không sửa từng dòng trên màn hình). Thay đổi được lưu vào lịch sử thay đổi với nhãn 「CSV取込」 (hong 2026-10-07 đã xác nhận)."]},
]

I8 = [
    {"no": "1", "ja": "タブ", "vi": "Tab", "sel": "-", "kind": "tab", "trig": "click", "pattern": "P-TAB", "detail": ["詳細の上のタブ。「基本情報」「変更履歴」（委託配送先は「ES配送費」も）。初期は「基本情報」。", "Tab phía trên chi tiết. 「基本情報」「変更履歴」 (đơn vị giao hàng ủy thác có thêm 「ES配送費」). Mặc định là 「基本情報」."]},
    {"no": "2", "ja": "変更履歴の表", "vi": "Bảng lịch sử thay đổi", "sel": "-", "kind": "table", "trig": "view", "pattern": "P-HIST", "err": ["I01"], "detail": ["列：変更日時・変更内容・変更者。新しい順。1ページ 10件。0件は I01。履歴に「影響した拠点数」「バージョン」は持たない（P-HIST）。変更者＝運営のアカウント名／「CSV取込」／委託配送先（プロフィールの変更）。表示だけ（直せない）。", "Cột: ngày giờ thay đổi・nội dung thay đổi・người thay đổi. Mới nhất trước. 10 dòng mỗi trang. 0 bản ghi hiện I01. Lịch sử không có 「影響した拠点数」「バージョン」 (P-HIST). Người thay đổi = tên tài khoản vận hành / 「CSV取込」 / đơn vị giao hàng ủy thác (thay đổi hồ sơ). Chỉ hiển thị (không sửa được)."]},
]

I9 = [
    {"no": "1", "ja": "0件の表示", "vi": "Hiển thị 0 bản ghi", "sel": ".tbl, .empty", "kind": "area", "trig": "view", "pattern": "P-LIST", "err": ["I01"], "detail": ["検索条件に合う委託配送先がないとき、一覧の中に I01「表示するデータがありません。」を出す（P-LIST）。ページ送りは出さない。条件は「クリア」で戻せる。", "Khi không có nơi giao hàng ủy thác nào khớp điều kiện tìm kiếm, hiển thị I01「表示するデータがありません。」trong danh sách (P-LIST). Không hiển thị phân trang. Có thể khôi phục điều kiện bằng 「クリア」."]},
]

I10 = [
    {"no": "1", "ja": "参照のみ（権限が閲覧だけの役割）", "vi": "Chỉ xem (vai trò chỉ có quyền xem)", "sel": ".ph", "kind": "area", "trig": "view", "cond": ["経理（委託配送先は閲覧のみ）", "Kế toán (「経理」) (nơi giao hàng ủy thác chỉ được xem)"], "detail": ["経理（委託配送先は閲覧のみ）。「新規登録」「CSV取込」「アカウント一括発行」は出さない。CSV出力は出す（P-LIST・権限表）。", "Kế toán (「経理」) (nơi giao hàng ủy thác chỉ được xem). Không hiển thị 「新規登録」「CSV取込」「アカウント一括発行」. Vẫn hiển thị xuất CSV (P-LIST・bảng quyền)."]},
    {"no": "2", "ja": "一覧の操作の列", "vi": "Cột thao tác của danh sách", "sel": ".tbl", "kind": "table", "trig": "view", "detail": ["行の鉛筆（編集）・ごみ箱（削除）・「契約の一括変更」は出さない。名前のリンクで詳細は開ける（詳細も「編集」「削除」を出さない）。", "Không hiển thị biểu tượng bút chì (sửa), thùng rác (xóa) ở từng dòng và 「契約の一括変更」. Vẫn mở được chi tiết bằng liên kết tên (trong chi tiết cũng không hiển thị 「編集」「削除」)."]},
]

I11 = [
    {"no": "1", "ja": "必須の入力エラー", "vi": "Lỗi nhập bắt buộc", "sel": ".emsg", "kind": "label", "trig": "view", "pattern": "P-FORM", "err": ["E01", "E04"], "detail": ["何も入れずに「登録」を押すと、必須の項目の下に E01 を出して赤枠にする（保存しない）。形式・文字数のエラーも同じ並びで項目の下に出す。最初のエラーの項目へスクロールする。保存ボタンの横に「保存できません（n件）」を出す。", "Nếu bấm 「登録」 khi chưa nhập gì, hiển thị E01 bên dưới các mục bắt buộc và tô viền đỏ (không lưu). Lỗi về định dạng・số ký tự cũng hiển thị bên dưới từng mục theo cùng thứ tự. Cuộn đến mục lỗi đầu tiên. Bên cạnh nút lưu hiển thị 「保存できません（n件）」."]},
]

I12 = [
    {"no": "1", "ja": "取り込みの手順（ステップ）", "vi": "Các bước nhập (bước)", "sel": ".steps", "kind": "area", "trig": "view", "pattern": "P-CSV", "detail": ["上に ①ファイルを選ぶ ②確認・登録 の2ステップ。いまは ② 。「ファイルを選び直す」で ① へ戻る（取り込んだ内容は捨てる）。", "Phía trên có 2 bước: ① Chọn file ② Xác nhận・đăng ký. Hiện đang ở bước ②. Nhấn 「ファイルを選び直す」 để quay lại ① (bỏ nội dung đã nhập)."]},
    {"no": "2", "ja": "ファイル名・件数", "vi": "Tên file・số bản ghi", "sel": ".badge", "kind": "label", "trig": "view", "detail": ["ファイル名と全体の件数。バッジで 新規／更新／変更なし／エラー の件数を出す。", "Tên file và tổng số bản ghi. Badge hiển thị số lượng Mới / Cập nhật / Không đổi / Lỗi."]},
    {"no": "3", "ja": "エラーの行（通知と表）", "vi": "Dòng lỗi (thông báo và bảng)", "sel": ".notice.ng", "kind": "area", "trig": "view", "err": ["E34"], "detail": ["エラーの行がある間は赤の通知「エラーの行 n件は取り込みません（行番号と内容は下の表）。ほかの行は「登録」で登録します。」と、エラー一覧（行番号・キー・列名・内容）を出す。エラー一覧は CSV でも出せる（「エラー一覧CSV」）。エラーの行は取り込まない（hong 2026/10/05）。", "Khi còn dòng lỗi, hiển thị thông báo đỏ 「エラーの行 n件は取り込みません（行番号と内容は下の表）。ほかの行は「登録」で登録します。」 và danh sách lỗi (số dòng・khóa・tên cột・nội dung). Danh sách lỗi cũng xuất được ra CSV (「エラー一覧CSV」). Dòng lỗi không được nhập (hong 2026/10/05)."]},
    {"no": "4", "ja": "登録する内容（前 → 後）", "vi": "Nội dung sẽ đăng ký (trước → sau)", "sel": ".tbl", "kind": "table", "trig": "view", "pattern": "P-LIST", "detail": ["列：行番号・区分（新規／更新）・キー・名前・変わる項目（前 → 後）。変わらない行は出さない。1ページ 10件。", "Cột: số dòng・phân loại (mới/cập nhật)・khóa・tên・mục thay đổi (trước → sau). Dòng không thay đổi thì không hiển thị. 10 dòng mỗi trang."]},
    {"no": "5", "ja": "登録", "vi": "Đăng ký", "sel": ".btn.pri.lg", "kind": "button", "trig": "click", "err": ["S03", "E34"], "cond": ["取り込めるデータが1行以上あるとき", "Khi có từ 1 dòng dữ liệu nhập được trở lên"], "detail": ["エラー以外の行を登録する。成功したら S03「n件を登録しました」を出して一覧へ。登録できる行が0件のときは押せない。取り込むとき変更履歴に「CSV取込」の名前で残る。", "Đăng ký các dòng không lỗi. Thành công thì hiện S03 「n件を登録しました」 và chuyển về danh sách. Không nhấn được khi số dòng có thể đăng ký là 0. Khi nhập, lịch sử thay đổi ghi lại với tên 「CSV取込」."]},
    {"no": "6", "ja": "ファイルを選び直す", "vi": "Chọn lại file", "sel": ".btn.out", "kind": "button", "trig": "click", "detail": ["① へ戻る。", "Quay lại ①."]},
]

VIEWS = [
    V("001", "AW_CNSG_001", "初期表示", "Hiển thị ban đầu", "/ops/masters/consignees", I1),
    V("002", "AW_CNSG_002", "初期表示（ステップ1 ファイルを選ぶ）", "Hiển thị ban đầu (Bước 1 Chọn tệp)", "/ops/masters/consignees/import", I2),
    V("003", "AW_CNSG_003", "詳細", "Chi tiết", "/ops/masters/consignees/DE00001", I3),
    V("004", "AW_CNSG_004", "登録・編集", "Đăng ký・sửa", "/ops/masters/consignees/new", I4),
    V("005", "AW_CNSG_001", "削除の確認", "Xác nhận xóa", "/ops/masters/consignees", I5, setup="document.querySelector('.tbl tbody tr .act button:last-child')?.click(); await sleep(300);"),
    V("006", "AW_CNSG_001", "削除できない（利用中）", "Không thể xóa (đang sử dụng)", "/ops/masters/consignees", I6, setup="document.querySelector('.tbl tbody tr .act button:last-child')?.click(); await sleep(300); [...document.querySelectorAll('.modal button')].find(b=>(b.textContent||'').includes('削除する'))?.click(); await sleep(500);"),
    V("010", "AW_CNSG_003", "詳細（ES配送費のタブ）", "Chi tiết (tab phí giao hàng ES)", "/ops/masters/consignees/DE00001?tab=fees", I7),
    V("011", "AW_CNSG_003", "詳細（変更履歴のタブ）", "Chi tiết (tab lịch sử thay đổi)", "/ops/masters/consignees/DE00001?tab=hist", I8),
    V("007", "AW_CNSG_001", "0件（検索結果なし）", "0 bản ghi (không có kết quả tìm kiếm)", "/ops/masters/consignees", I9, setup="const kw=document.querySelector('.es-search input'); if(kw){Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(kw,'zzzzzz'); kw.dispatchEvent(new Event('input',{bubbles:true})); await sleep(200); clickText('button','検索'); await sleep(600);}"),
    V("008", "AW_CNSG_001", "参照のみ（閲覧の権限だけ）", "Chỉ xem (chỉ có quyền xem)", "/ops/masters/consignees", I10, login="Ad00012"),
    V("009", "AW_CNSG_004", "入力エラー", "Lỗi nhập", "/ops/masters/consignees/new", I11, setup="clickText('.ph button','登録'); await sleep(500);"),
    V("012", "AW_CNSG_002", "確認・登録（ステップ2）", "Xác nhận・đăng ký (bước 2)", "/ops/masters/consignees/import", I12, setup="const res=await fetch('/api/domain/csv/export',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','x-es-site':'ops'},body:JSON.stringify({args:{entity:'carriers',scope:{site:'ops'}}})});const t=await res.json();const esc=v=>'\"'+String(v??'').replace(/\"/g,'\"\"')+'\"';const rows=[t.head,...t.rows];const r0=t.rows[0];const ni=t.head.findIndex(h=>/委託配送先名/.test(h));if(ni>=0)r0[ni]=r0[ni]+' X';const bad=t.rows[0].slice();bad[0]='XX999999';rows.push(bad);const text='\\ufeff'+rows.map(r=>r.map(esc).join(',')).join('\\r\\n');const inp=document.querySelector('input[type=file]');const dt=new DataTransfer();dt.items.add(new File([text],'取込テスト.csv',{type:'text/csv'}));inp.files=dt.files;inp.dispatchEvent(new Event('change',{bubbles:true}));await sleep(2500);", note=["ファイルを選んだ直後。見本は今のデータの CSV出力に、1行目の委託配送先名を変えた（更新の見本）と、キーが誤りの行を1つ足したもの（エラーの行の見本）。", "Ngay sau khi chọn file. File mẫu là CSV xuất từ dữ liệu hiện tại, đổi tên đơn vị giao hàng ủy thác ở dòng 1 (mẫu cập nhật) và thêm 1 dòng có khóa sai (mẫu dòng lỗi)."]),
]
