# -*- coding: utf-8 -*-
"""
画面設計書のデータ：運営管理者Web ＞ マスタ管理 ＞ 配送スタッフ（一覧・CSV取込）
元：本物の Web（app/ops/masters/drivers・app/ops/_general/gen.ts の driver・lib/csv/master.ts（drivers））、台帳 K・M-4・運営Web_権限表（委託配送管理）・CSV入出力_定義
番号は画面ごとに通し。タブ・モーダルの状態では、その状態で増える・変わる項目だけ書く。
（運営H2：hong の確認前の提案を含む。提案は DECISIONS で「提案」と書き、open に確認先を残してある）
"""

TITLE = ["配送スタッフ（AW_DRVR）", "Nhân viên giao hàng (AW_DRVR)"]
SHEET = ["配送スタッフ", "Nhân viên giao hàng"]
BASENAME = "画面設計書_AW_DRVR_配送スタッフ"
IMG_PREFIX = "AW_DRVR"
OUT_DIR = "AW_DRVR_配送スタッフ"
CODE_NOTE = ["画面コードは規約 <Module(2)>_<Feature(4)>_<Seq(3)>（docs/01_仕様/画面コード規約_20261005.md）。AW＝運営管理者Web、DRVR＝配送スタッフ",
             "Mã màn hình theo quy ước <Module(2)>_<Feature(4)>_<Seq(3)>. AW = Admin Web, DRVR = Nhân viên giao hàng"]
SITE = "ops"
SYSTEM = {"ja": "運営管理者Web", "vi": "Web quản trị vận hành"}
AUTHOR = "Claude（cloud）／確認：hong"
CREATED = "2026-10-06"
DEMO_FILE = "http://localhost:3000"
LOGIN = {"site": "ops", "loginId": "Ad00010"}
CODE_PATHS = "[\"app/ops/masters/drivers\", \"app/ops/_general\", \"lib/csv/master.ts\", \"lib/ops/general/fromDomain.ts\"]"

DECISIONS = [
    {"date": "2026-10-06", "target": "登録・編集のしかた", "q": ["運営の画面で新規登録・編集の画面（フォーム）を作るか", "Có tạo màn hình đăng ký mới/chỉnh sửa (biểu mẫu) trong màn hình vận hành hay không"], "a": ["作る（プランマスタと同じ：一覧 → 詳細（表示だけ）→ 登録・編集）。CSV取込も残す（一括）。これまでの案「CSV取込だけ」は置き換え。配送スタッフも作る（台帳「ドライバーのログインID」：運営には新規登録の画面を作らず CSV取込 → 置き換え）", "Làm mới (giống master gói dịch vụ: danh sách → chi tiết (chỉ hiển thị) → đăng ký/sửa). Vẫn giữ nhập CSV (hàng loạt). Phương án trước đây 「chỉ nhập CSV」 được thay thế. Cũng làm cho nhân viên giao hàng (「台帳」 'ID đăng nhập của tài xế': trước đây vận hành không có màn hình đăng ký mới mà chỉ nhập CSV → được thay thế)"], "src": "hong 回答 2026-10-06（運営H2 A＝C）・台帳 F・受付簿 No.167"},
    {"date": "2026-10-08", "target": "雇用形態・所属先・区分（一覧 No.3.4〜3.5b・CSV No.2.8b・詳細 No.3・登録編集 No.2.4〜2.5b）", "q": ["配送スタッフの雇用形態（社員／個人事業主）・所属先・区分を残すか（確認表 H-18）", "Có giữ hình thức tuyển dụng (nhân viên／cá nhân kinh doanh)・nơi trực thuộc không (bảng xác nhận H-18)"], "a": ["残す。雇用形態（社員／個人事業主）・所属先を、画面（一覧・詳細・登録編集）と CSV に置く（所属先は元からある。雇用形態を足す。区分は #475 で廃止）", "Giữ lại. Đặt hình thức tuyển dụng (社員／個人事業主), nơi trực thuộc trên màn hình (danh sách・chi tiết・đăng ký/sửa) và CSV (nơi trực thuộc đã có từ trước; thêm hình thức tuyển dụng; phân loại đã bỏ ở #475)"], "src": "hong 回答 2026-10-08（台帳 S「配送スタッフの雇用形態・所属先・区分（OW・運営）」・受付簿 #432）。配送_06 §12-3 の「所属先と配送区分『個人』は削除」は台帳 S で置き換え"},
    {"date": "2026-10-08", "target": "削除できない条件（登録編集の削除・一覧 No.3.8 の削除）", "q": ["運営の配送スタッフを削除できない条件（確認表 H-17）", "Điều kiện không xóa được nhân viên giao hàng của 運営 (bảng xác nhận H-17)"], "a": ["OW と同じ：担当中の配送（予定〜再配送待）がある、または未返却の保冷バッグ・保冷剤がある（E244 に足す。削除できないモーダルは E451）。未返却の数え方：返却数＜貸与数で、状態が紛失・廃棄ではないもの", "Giống OW: còn chuyến đang phụ trách (予定〜再配送待) hoặc còn túi/đá giữ lạnh chưa trả (thêm vào E244; modal không xóa được dùng E451). Cách đếm chưa trả: số trả < số mượn và trạng thái không phải 紛失・廃棄"], "src": "hong 回答 2026-10-08（台帳 S「運営の配送スタッフの削除できない条件（AW_DRVR）」・受付簿 #468、「未返却の数え方」#467）。置き換えた旧案：担当中の配送だけ（E244）"},
    {"date": "2026-10-09", "target": "区分（一覧 No.3.5・CSV No.2.8・登録編集 No.2.5・検索条件 No.2・詳細 No.3）", "q": ["配送スタッフの「区分」（個人／会社所属）を持つか", "Có giữ 「区分」 (cá nhân／thuộc công ty) của nhân viên giao hàng không"], "a": ["持たない。画面（一覧・詳細・登録編集）・検索条件・CSV の列から外す。「雇用形態」（社員／個人事業主）と「所属先」は残す。項目の番号 3.5・2.8・2.5 は欠番", "Không giữ. Bỏ khỏi màn hình (danh sách・chi tiết・đăng ký/sửa), điều kiện tìm kiếm và cột CSV. Giữ 「雇用形態」 (社員／個人事業主) và 「所属先」. Số mục 3.5・2.8・2.5 để trống"], "src": "hong 回答 2026-10-09（台帳 S「配送スタッフの区分を持たない」・受付簿 #475）。置き換えた旧案：区分は所属先から自動で決まる（#466・取り消し）"},
    {"date": "2026-10-06", "target": "削除と無効の扱い", "q": ["削除のしかたと、削除・無効にしたときのログイン", "Cách xóa, và việc đăng nhập khi đã xóa hoặc vô hiệu hóa"], "a": ["論理削除（状態＝削除済）。削除できない条件を置く（使用中は削除できない。条件の中身は仕入先＝進行中の発注／倉庫＝在庫・利用中の契約／委託配送先＝利用中の契約・配送予定・所属スタッフ／配送スタッフ＝割り当て済みの配送。hong 確認 2026-10-06）。状態が「削除済」「無効」のアカウントはログインできない", "Xóa logic (trạng thái 削除済). Có điều kiện chặn xóa (đang sử dụng thì không xóa được; nội dung điều kiện: 仕入先 = đơn đặt hàng đang xử lý / 倉庫 = tồn kho・hợp đồng đang dùng / 委託配送先 = hợp đồng・lịch giao đang dùng・nhân viên trực thuộc / 配送スタッフ = lượt giao đã phân công; hong xác nhận 2026-10-06). Tài khoản ở trạng thái 「削除済」「無効」 không đăng nhập được."], "src": "hong 回答 2026-10-06（運営H2 B）・台帳 F・受付簿 No.167"},
    {"date": "2026-10-06", "target": "権限", "q": ["だれが見られる・操作できるか", "Ai được xem và thao tác"], "a": ["フル権限・システム管理・物流＝CRUD、ほか＝R（閲覧・CSV出力）。システム管理は CRUD", "Toàn quyền・quản trị hệ thống・logistics = CRUD, các vai trò khác = R (xem・xuất CSV). Quản trị hệ thống là CRUD"], "src": "運営Web_権限表（委託配送管理）"},
    {"date": "2026-10-03", "target": "ID・登録", "q": ["配送スタッフのIDと登録", "ID và đăng ký của nhân viên giao hàng"], "a": ["ID は DR＋5桁の自動採番。免許がないスタッフにはアカウントを出さない。委託配送会社が自社スタッフを登録できる", "ID tự động cấp số dạng DR + 5 chữ số. Không cấp tài khoản cho nhân viên không có bằng lái. Công ty vận chuyển ủy thác có thể đăng ký nhân viên của mình"], "src": "台帳 K（スタッフの CSV 登録）・M-4（ID 表記 DR＋5桁）"},
    {"date": "2026-10-06", "target": "画面コード", "q": ["画面コード", "Mã màn hình"], "a": ["AW_DRVR_001〜002", "AW_DRVR_001〜002"], "src": "画面コード規約（Feature は Claude 案・hong 確認待ち）"},
]
CHANGES = [{"ver": "1.11", "date": "2026-10-06", "no": "*", "type": "追加", "reason": ["配送スタッフの画面設計書を新規に作成（hong の確認済み・受付簿 No.164〜168）", "Tạo mới tài liệu thiết kế màn hình Nhân viên giao hàng (đã được hong xác nhận, 受付簿 No.164〜168)"], "impact": ["一覧・詳細・登録／編集・CSV取込。削除条件 E244、無効／削除済はログイン不可。台帳の旧決定（運営に新規登録の画面を作らない）を変更。実装済（受付簿 No.167）", "Danh sách, chi tiết, đăng ký/sửa, nhập CSV. Điều kiện xóa E244, 無効/削除済 không đăng nhập được. Đổi quyết định cũ trong 台帳 (không làm màn đăng ký mới). Đã triển khai (受付簿 No.167)"]}, {"ver": "1.12", "date": "2026-10-06", "no": ["1", "2"], "type": "追加", "reason": ["役割レビュー（BA・QC・UI/UX）の指摘への対応", "Xử lý các góp ý từ review vai trò (BA・QC・UI/UX)"], "impact": ["表示の確認のための状態。動きは変更なし", "Trạng thái để kiểm tra hiển thị. Hành vi không đổi"]}, {"ver": "1.12", "date": "2026-10-06", "no": ["1.3", "1.12", "1.13"], "type": "変更", "reason": ["役割レビュー（BA・QC・UI/UX）の指摘への対応", "Xử lý các góp ý từ review vai trò (BA・QC・UI/UX)"], "impact": ["動きは変更なし（番号の場所と説明の追記）", "Hành vi không đổi (chỉ tách vị trí đánh số và bổ sung mô tả)"], "before": ["「キャンセル／登録・保存」を1項目", "Gộp 「キャンセル／登録・保存」 thành 1 mục"], "after": ["「キャンセル」と「登録・保存」を分ける／新規登録に P-FORM", "Tách 「キャンセル」 và 「登録・保存」 / nút đăng ký mới theo P-FORM"]}, {"ver": "1.17", "date": "2026-10-07", "no": ["1.2"], "type": "追加", "reason": ["hong の回答（2026-10-07）への対応", "Xử lý trả lời của hong (2026-10-07)"], "impact": ["パスワード送信のメールを確定（仕入先・委託配送先は Mail List No.30、配送スタッフは No.3 の認証コード）。委託配送先のアカウント発行は Mail List No.29。履歴の変更者はログイン中のアカウント。実装済（受付簿 No.190）", "Chốt email gửi mật khẩu (nhà cung cấp・đơn vị vận chuyển dùng Mail List No.30, nhân viên giao hàng dùng mã xác thực No.3). Cấp tài khoản đơn vị vận chuyển dùng Mail List No.29. Người thay đổi trong lịch sử là tài khoản đang đăng nhập. Đã triển khai (受付簿 No.190)"]}]
HIDE_ALWAYS = []
STATIC_CSS = ""
VIEWER_CSS = ""

SCREENS = [
    {"code": "AW_DRVR_001", "ja": "配送スタッフ一覧", "vi": "Danh sách nhân viên giao hàng"},
    {"code": "AW_DRVR_002", "ja": "配送スタッフ CSV取込", "vi": "Nhập CSV nhân viên giao hàng"},
    {"code": "AW_DRVR_003", "ja": "配送スタッフ詳細", "vi": "Chi tiết nhân viên giao hàng"},
    {"code": "AW_DRVR_004", "ja": "配送スタッフの登録・編集", "vi": "Đăng ký / sửa nhân viên giao hàng"},
]

H = (
    "const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));"
    "const tab=(t)=>[...document.querySelectorAll('.tabs button')].find(b=>(b.textContent||'').trim()===t)?.click();"
    "const clickText=(sel,t,i)=>{const b=[...document.querySelectorAll(sel)].filter(x=>(x.textContent||'').includes(t))[i||0];b&&b.click();};"
)



def V(id, code, ja, vi, url, items, setup="", note=None, full=True, wait=600, login=None):
    v = {"id": id, "code": code, "state": [ja, vi], "url": url, "setup": (H + setup) if setup else "", "full": full, "wait": wait, "note": note or ["", ""], "items": items}
    if login:
        v["login"] = login
    return v


I1 = [
    {"no": "1", "ja": "ヘッダー", "vi": "Header", "sel": ".ph", "kind": "area", "trig": "view", "detail": ["パンくず：マスタ管理 ＞ 配送スタッフ。見られるのは運営の全役割（フル権限・システム管理・物流は操作もできる。ほかは閲覧のみ：権限表「委託配送管理」）。", "Breadcrumb: マスタ管理 ＞ 配送スタッフ. Tất cả các vai trò vận hành đều xem được (toàn quyền・quản trị hệ thống・logistics có thể thao tác. Các vai trò khác chỉ xem: bảng quyền 「委託配送管理」)."]},
    {"no": "1.1", "ja": "CSV出力", "vi": "Xuất CSV", "sel": ".ph", "kind": "button", "trig": "click", "pattern": "P-CSV-OUT", "detail": ["ヘッダーの右。配送スタッフの全項目（CSV取込と同じ列）（検索条件のとおりの全件）。見られる役割には全員に出す。", "Bên phải header. Toàn bộ mục của nhân viên giao hàng (cùng cột với nhập CSV) (toàn bộ số bản ghi theo điều kiện tìm kiếm). Hiển thị cho tất cả các vai trò được phép xem."]},
    {"no": "1.2", "ja": "CSV取込", "vi": "Nhập CSV", "sel": ".ph", "kind": "button", "trig": "click", "pattern": "P-CSV", "detail": ["CSV取込の画面（/ops/masters/drivers/import）へ。CSV取込の権限（フル権限・システム管理）がない役割には出さない。", "Chuyển đến màn hình nhập CSV (/ops/masters/drivers/import). Không hiển thị với vai trò không có quyền nhập CSV (toàn quyền・quản trị hệ thống)."]},
    {"no": "1.3", "ja": "新規登録", "vi": "Đăng ký mới", "sel": ".ph .btn.pri", "kind": "button", "trig": "click", "pattern": "P-FORM", "detail": ["配送スタッフの登録（AW_DRVR_004）へ。登録の権限（フル権限・システム管理）がない役割には出さない。", "Chuyển đến đăng ký nhân viên giao hàng (AW_DRVR_004). Không hiển thị với vai trò không có quyền đăng ký (toàn quyền, quản trị hệ thống)."]},
    {"no": "2", "ja": "検索条件", "vi": "Điều kiện tìm kiếm", "sel": ".card", "kind": "area", "trig": "view", "pattern": "P-LIST", "detail": ["キーワード（所属先・配送スタッフ名）／ステータス（有効・無効・利用停止・免許未登録）。", "Từ khóa (đơn vị trực thuộc・tên nhân viên giao hàng) / trạng thái (hiệu lực・vô hiệu・tạm ngừng sử dụng・chưa đăng ký bằng lái)."], "demo_ok": ["コードの検索条件・一覧・CSV・登録編集に「区分」（staffKind）がある。コードを直す宿題：staffKind と CSV の区分の列を外し、画面の区分の表示・検索条件・入力欄をなくす（受付簿 #475）", "Điều kiện tìm kiếm・danh sách・CSV・đăng ký/sửa trong code có 「区分」 (staffKind). Việc sửa code còn tồn: bỏ staffKind và cột 区分 của CSV, bỏ hiển thị・điều kiện tìm kiếm・ô nhập 区分 trên màn hình (受付簿 #475)"]},
    {"no": "3", "ja": "一覧", "vi": "Danh sách", "sel": ".tbl", "kind": "table", "trig": "view", "pattern": "P-LIST", "err": ["I01"], "detail": ["初期の並びは配送スタッフIDの昇順。1ページ 10件。0件は I01。", "Thứ tự ban đầu là ID nhân viên giao hàng tăng dần. 10 dòng mỗi trang. Khi 0 kết quả hiển thị I01."]},
    {"no": "3.1", "ja": "免許", "vi": "Bằng lái", "sel": ".tbl th::免許", "kind": "label", "trig": "view", "detail": ["免許証の写真があるかをアイコンで表示（あり／なし）。写真の登録・確認はドライバーアプリ／委託配送先Web。", "Hiển thị bằng biểu tượng việc có ảnh bằng lái hay không (có／không). Việc đăng ký/xác nhận ảnh thực hiện trên ứng dụng tài xế / Web đơn vị vận chuyển ủy thác."]},
    {"no": "3.2", "ja": "配送スタッフID", "vi": "ID nhân viên giao hàng", "sel": ".tbl th::配送スタッフID", "kind": "label", "trig": "view", "detail": ["DR＋5桁（システムが採番。台帳）。右詰めでなく文字幅そろえ。", "DR + 5 chữ số (hệ thống tự cấp số. 「台帳」). Không căn phải mà căn đều độ rộng ký tự."]},
    {"no": "3.3", "ja": "配送スタッフ名", "vi": "Tên nhân viên giao hàng", "sel": ".tbl .lnk", "kind": "link", "trig": "click", "detail": ["名前は下線つきのリンク。押すと詳細（AW_DRVR_003）へ。", "Tên là liên kết có gạch chân. Nhấn vào sẽ chuyển đến chi tiết (AW_DRVR_003)."]},
    {"no": "3.4", "ja": "所属先", "vi": "Đơn vị trực thuộc", "sel": ".tbl th::所属先", "kind": "label", "trig": "view", "detail": ["所属する委託配送会社名（自社スタッフは「ES配送便」）。", "Tên công ty vận chuyển ủy thác trực thuộc (nhân viên nội bộ là 「ES配送便」)."]},
    {"no": "3.5b", "ja": "雇用形態", "vi": "Hình thức tuyển dụng", "sel": ".tbl th::雇用形態", "kind": "label", "trig": "view", "detail": ["社員／個人事業主（委託配送先Web と同じ値。台帳 S・受付簿 #432）。", "社員／個人事業主 (cùng giá trị với Web đối tác giao hàng. 台帳 S・受付簿 #432)."], "demo_ok": ["コードの運営の一覧・CSV に「雇用形態」の列がない（内部の自社／委託は所属先から決まる値で、画面には出していない）。足すのは宿題", "Danh sách・CSV của 運営 trong code chưa có cột 「雇用形態」 (giá trị nội bộ 自社／委託 do nơi trực thuộc quyết định, không hiện trên màn hình). Việc thêm còn tồn"]},
    {"no": "3.6", "ja": "電話番号", "vi": "Số điện thoại", "sel": ".tbl th::電話番号", "kind": "label", "trig": "view", "detail": ["半角の数字とハイフン。", "Chữ số và dấu gạch ngang bán góc."]},
    {"no": "3.7", "ja": "ステータス", "vi": "Trạng thái", "sel": ".tbl th::ステータス", "kind": "label", "trig": "view", "detail": ["バッジ：有効／無効／利用停止／免許未登録（免許がないスタッフにはアカウントを出さない：台帳 K）。", "Badge: có hiệu lực／vô hiệu／ngừng sử dụng／chưa đăng ký bằng lái (không cấp tài khoản cho nhân viên không có bằng lái: 「台帳」 K)."]},
    {"no": "3.8", "ja": "操作（編集・削除）", "vi": "Thao tác (sửa・xóa)", "sel": ".tbl .act", "kind": "button", "trig": "click", "pattern": "P-DEL", "err": ["Q01", "S02", "E30"], "detail": ["鉛筆＝編集（AW_DRVR_004）、ごみ箱＝削除（確認 Q01 → 論理削除して S02）。配送中・割り当て済みの配送が残っているときは削除できない（E244）。削除（と状態「無効」）にするとアカウントはログインできなくなる。削除済の行には出さない。操作の権限がない役割には出さない。", "Bút chì = sửa (AW_DRVR_004), thùng rác = xóa (xác nhận Q01 → xóa logic rồi hiện S02). Nếu còn đơn giao hàng đang giao hoặc đã được phân công thì không thể xóa (E244). Khi xóa (và trạng thái 「無効」) thì tài khoản không thể đăng nhập. Không hiển thị ở dòng đã xóa. Không hiển thị với vai trò không có quyền thao tác."]},
    {"no": "4", "ja": "ページ送り", "vi": "Phân trang", "sel": ".pager", "kind": "area", "trig": "view", "pattern": "P-LIST", "detail": ["P-LIST のとおり（10／20／50件）。", "Theo P-LIST (10／20／50 dòng)."]},
]

I2 = [
    {"no": "1", "ja": "ヘッダー", "vi": "Header", "sel": ".ph", "kind": "area", "trig": "view", "pattern": "P-CSV", "err": ["S03", "E34"], "detail": ["見出し「配送スタッフ CSV取込」。キャンセルで一覧へ戻る（何も登録しない）。CSV取込の権限（フル権限・システム管理）がある役割だけが開ける（ほかは一覧へ）。モーダルではなく画面（P-CSV）。", "Tiêu đề 「配送スタッフ CSV取込」. Hủy thì quay lại danh sách (không đăng ký gì). Chỉ vai trò có quyền nhập CSV (toàn quyền・quản trị hệ thống) mới mở được (vai trò khác bị chuyển về danh sách). Là màn hình chứ không phải modal (P-CSV)."]},
    {"no": "2", "ja": "CSVテンプレートの列（定義。画面には出さない）", "vi": "Các cột của mẫu CSV (định nghĩa. Không hiển thị trên màn hình)", "sel": "-", "kind": "area", "trig": "view", "detail": ["取り込むファイルの列の定義（1行目の見出し・この順。CSV出力と同じ列）。免許証の写真は CSV では送れない。", "Định nghĩa các cột của tệp nhập (tiêu đề dòng 1・theo thứ tự này. Cùng cột với xuất CSV). Ảnh bằng lái không thể gửi bằng CSV."]},
    {"no": "2.1", "ja": "配送スタッフID", "vi": "ID nhân viên giao hàng", "sel": "-", "kind": "label", "trig": "view", "detail": ["【空欄＝新規（DR＋5桁で採番）】キー。空欄の行は新規、入っていれば更新。", "[Để trống = mới (cấp số DR + 5 chữ số)] Khóa. Dòng để trống là mới, nếu có giá trị thì là cập nhật."]},
    {"no": "2.2", "ja": "所属先ID", "vi": "ID đơn vị trực thuộc", "sel": "-", "kind": "label", "trig": "view", "detail": ["【新規は必須】委託配送先ID（DE＋5桁）か自社。更新のときは CSV では変えられない（エラー「所属先は CSV では変えられません」）。", "[Bắt buộc khi mới] ID đơn vị vận chuyển ủy thác (DE + 5 chữ số) hoặc nội bộ. Khi cập nhật thì không thể đổi bằng CSV (lỗi 「所属先は CSV では変えられません」)."]},
    {"no": "2.3", "ja": "所属先名", "vi": "Tên đơn vị trực thuộc", "sel": "-", "kind": "label", "trig": "view", "detail": ["【読取専用】書いても無視（所属先IDから決まる）。", "[Chỉ đọc] Có ghi cũng bị bỏ qua (được xác định từ ID đơn vị trực thuộc)."]},
    {"no": "2.4", "ja": "氏名", "vi": "Họ tên", "sel": "-", "kind": "label", "trig": "view", "len": "文字列 50", "detail": ["【新規は必須】最大50文字。", "[Bắt buộc khi mới] Tối đa 50 ký tự."]},
    {"no": "2.5", "ja": "フリガナ", "vi": "Furigana", "sel": "-", "kind": "label", "trig": "view", "len": "文字列 60", "detail": ["【任意】全角カタカナ。", "[Tùy chọn] Katakana toàn góc."]},
    {"no": "2.6", "ja": "電話番号", "vi": "Số điện thoại", "sel": "-", "kind": "label", "trig": "view", "len": "文字列 20", "detail": ["【任意】半角の数字とハイフン（エラー：電話番号は半角の数字とハイフンで入れてください）。", "[Tùy chọn] Chữ số và dấu gạch ngang bán góc (lỗi: 電話番号は半角の数字とハイフンで入れてください)."]},
    {"no": "2.7", "ja": "メールアドレス", "vi": "Địa chỉ email", "sel": "-", "kind": "label", "trig": "view", "len": "文字列 160", "detail": ["【新規は必須】形式チェック（重複してよい：台帳 S #469。エラー：メールアドレスの形式が正しくありません）。", "[Bắt buộc khi mới] Kiểm tra định dạng (được trùng: 台帳 S #469; lỗi: メールアドレスの形式が正しくありません)."], "ask": "hong"},
    {"no": "2.8b", "ja": "雇用形態", "vi": "Hình thức tuyển dụng", "sel": "-", "kind": "label", "trig": "view", "detail": ["【任意】社員／個人事業主（台帳 S・受付簿 #432）。省くと更新のときは変えない。", "[Tùy chọn] 社員／個人事業主 (台帳 S・受付簿 #432). Bỏ trống khi cập nhật thì không đổi."], "demo_ok": ["コードの CSV に「雇用形態」の列がない。足すのは宿題", "CSV trong code chưa có cột 「雇用形態」. Việc thêm còn tồn"]},
    {"no": "2.9", "ja": "対応エリア", "vi": "Khu vực phụ trách", "sel": "-", "kind": "label", "trig": "view", "detail": ["【任意】複数はまとめて指定。", "[Tùy chọn] Nhiều khu vực thì chỉ định gộp lại."]},
    {"no": "2.10", "ja": "状態", "vi": "Trạng thái", "sel": "-", "kind": "label", "trig": "view", "detail": ["【任意】有効／無効／利用停止／免許未登録。委託の新規スタッフは「免許未登録」で登録しアカウントは発行しない（警告：委託のスタッフのため「免許未登録」で登録します（アカウントは発行しません））。", "[Tùy chọn] Có hiệu lực／vô hiệu／ngừng sử dụng／chưa đăng ký bằng lái. Nhân viên mới của đơn vị ủy thác được đăng ký với 「免許未登録」 và không cấp tài khoản (cảnh báo: 委託のスタッフのため「免許未登録」で登録します（アカウントは発行しません）)."]},
    {"no": "2.11", "ja": "アカウントの状態", "vi": "Trạng thái tài khoản", "sel": "-", "kind": "label", "trig": "view", "detail": ["【読取専用】書いても無視（アカウントの発行状態を表示）。", "[Chỉ đọc] Có ghi cũng bị bỏ qua (hiển thị trạng thái cấp tài khoản)."]},
]

I3 = [
    {"no": "1", "ja": "ヘッダー", "vi": "Header", "sel": "-", "kind": "area", "trig": "view", "detail": ["パンくず：マスタ管理 ＞ 配送スタッフ ＞ 配送スタッフ詳細。タイトル「配送スタッフ詳細 ID」。右に「削除」「パスワード送信」「編集」（権限のある役割だけ。削除済の配送スタッフには出さない）。", "Breadcrumb: マスタ管理 ＞ 配送スタッフ ＞ 配送スタッフ詳細. Tiêu đề 「配送スタッフ詳細 ID」. Bên phải có 「削除」「パスワード送信」「編集」 (chỉ vai trò có quyền; không hiển thị với nhân viên giao hàng đã xóa)."]},
    {"no": "1.1", "ja": "削除", "vi": "Xóa", "sel": "-", "kind": "button", "trig": "click", "pattern": "P-DEL", "err": ["Q01", "S02", "E30"], "detail": ["削除の確認（Q01）→ 論理削除（P-DEL）。使用中は削除できない。削除すると、この配送スタッフのアカウントはログインできなくなる。", "Xác nhận xóa (Q01) → xóa logic (P-DEL). Đang được sử dụng thì không xóa được. Khi xóa, tài khoản của nhân viên giao hàng này không thể đăng nhập nữa."]},
    {"no": "1.2", "ja": "パスワード送信", "vi": "Gửi mật khẩu", "sel": "-", "kind": "button", "trig": "click", "err": ["Q173", "S173", "E30"], "cond": ["アカウントが有効（または発行済・ログイン前）のとき", "Khi tài khoản có hiệu lực (hoặc đã cấp・chưa đăng nhập)"], "detail": ["メイン担当者のメールアドレスへ、パスワード設定のご案内を送る（仕入先・委託配送先は Mail List No.30。配送スタッフはドライバーアプリの再設定と同じ認証コード＝No.3）。押すと確認（Q173）→ 送ったら S173。アカウントが「未発行」「無効」「削除済」のときは押せない。", "Gửi hướng dẫn đặt mật khẩu tới email người phụ trách chính (nhà cung cấp・đơn vị vận chuyển ủy thác dùng Mail List No.30; nhân viên giao hàng dùng mã xác thực giống đặt lại mật khẩu trên app tài xế = No.3). Nhấn thì hiện xác nhận (Q173) → gửi xong hiện S173. Không nhấn được khi tài khoản là 「未発行」「無効」「削除済」."]},
    {"no": "1.3", "ja": "編集", "vi": "Sửa", "sel": "-", "kind": "button", "trig": "click", "detail": ["登録・編集の画面（編集）へ。編集の権限がない役割には出さない。", "Chuyển sang màn hình đăng ký・sửa (sửa). Không hiển thị với vai trò không có quyền sửa."]},
    {"no": "2", "ja": "タブ", "vi": "Tab", "sel": "-", "kind": "tab", "trig": "click", "pattern": "P-TAB", "detail": ["タブ：基本情報・変更履歴。初期は「基本情報」。", "Tab: Thông tin cơ bản・Lịch sử thay đổi. Mặc định là 「基本情報」."]},
    {"no": "3", "ja": "基本情報（表示）", "vi": "Thông tin cơ bản (hiển thị)", "sel": "-", "kind": "area", "trig": "view", "detail": ["配送スタッフID・名・名カナ・所属先・雇用形態・ステータス・電話番号・免許証（写真）。すべて表示だけ。", "ID nhân viên giao hàng, tên, tên Kana, đơn vị trực thuộc, hình thức tuyển dụng, trạng thái, số điện thoại, giấy phép lái xe (ảnh). Tất cả chỉ hiển thị."]},
    {"no": "4", "ja": "担当者（表示）", "vi": "Người phụ trách (hiển thị)", "sel": "-", "kind": "area", "trig": "view", "detail": ["ログインID・メールアドレス・最終ログイン日時。「パスワード送信」ボタン。", "ID đăng nhập, email, thời điểm đăng nhập lần cuối. Nút 「パスワード送信」."]},
]

I4 = [
    {"no": "1", "ja": "登録・編集の画面", "vi": "Màn hình đăng ký・sửa", "sel": "-", "kind": "area", "trig": "view", "pattern": "P-FORM", "err": ["Q02", "S01", "E30", "E31"], "detail": ["タイトル「配送スタッフの登録」「配送スタッフの編集」。一覧の「新規登録」と、詳細の「編集」（一覧の鉛筆）から開く。タブは置かない（詳細だけ）。保存は画面の 登録／保存 の1つだけ。入力を変えてキャンセルしたら Q02。成功したら S01 を出して詳細へ戻る（新規は登録した ID の詳細）。", "Tiêu đề 「配送スタッフの登録」「配送スタッフの編集」. Mở từ 「新規登録」 ở danh sách và từ 「編集」 ở chi tiết (biểu tượng bút chì ở danh sách). Không đặt tab (chỉ ở chi tiết). Chỉ có 1 nút lưu trên màn hình: Đăng ký/Lưu. Nếu đã sửa nhập liệu rồi bấm Hủy thì hiện Q02. Thành công thì hiện S01 và quay về chi tiết (đăng ký mới thì về chi tiết của ID vừa đăng ký)."]},
    {"no": "2", "ja": "基本情報", "vi": "Thông tin cơ bản", "sel": "-", "kind": "area", "trig": "view", "detail": ["基本情報のカード（参考画面：hong 2026-10-06）。", "Thẻ thông tin cơ bản (màn hình tham khảo: hong 2026-10-06)."]},
    {"no": "2.1", "ja": "配送スタッフID", "vi": "ID nhân viên giao hàng", "sel": "-", "kind": "label", "trig": "view", "detail": ["DR＋5桁（システムが採番）。登録のときは表示しない。", "DR + 5 chữ số (hệ thống tự cấp số). Không hiển thị khi đăng ký mới."]},
    {"no": "2.2", "ja": "配送スタッフ名", "vi": "Tên nhân viên giao hàng", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E04"], "req": "○", "len": "文字列 60", "ex": ["山岡 美幸", "Yamaoka Miyuki"], "detail": ["配送スタッフの名前。", "Tên của nhân viên giao hàng."]},
    {"no": "2.3", "ja": "配送スタッフ名カナ", "vi": "Tên nhân viên giao hàng (Kana)", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E03", "E04"], "req": "○", "len": "文字列 60", "ex": ["ヤマオカ ミユキ", "Yamaoka Miyuki"], "detail": ["全角カタカナ。必須（hong 2026-10-07）。", "Katakana full-width. Bắt buộc (hong 2026-10-07)."]},
    {"no": "2.4", "ja": "所属先", "vi": "Đơn vị trực thuộc", "sel": "-", "kind": "select", "trig": "select", "err": ["E01"], "req": "○", "len": ["選択（委託配送先マスタ／自社 ES配送便）", "Chọn (master đơn vị vận chuyển ủy thác / tự doanh)"], "ex": ["株式会社 三輝", "Công ty cổ phần Sanki"], "detail": ["配送を担当する会社。登録後は変えられない（CSV取込と同じ）。", "Công ty phụ trách giao hàng. Sau khi đăng ký không thể thay đổi (giống import CSV)."]},
    {"no": "2.5b", "ja": "雇用形態", "vi": "Hình thức tuyển dụng", "sel": "-", "kind": "select", "trig": "select", "err": ["E01"], "req": "○", "len": ["選択（社員／個人事業主）", "Chọn (nhân viên／cá nhân kinh doanh)"], "ex": ["社員", "Nhân viên"], "init": ["社員", "Nhân viên"], "detail": ["「社員」「個人事業主」。委託配送先Web の配送スタッフと同じ項目（台帳 S・受付簿 #432）。新規の初期値は「社員」。", "「社員」「個人事業主」. Cùng mục với nhân viên giao hàng ở Web đối tác giao hàng (台帳 S・受付簿 #432). Giá trị ban đầu khi đăng ký mới là 「社員」."], "demo_ok": ["コードの運営の登録・編集に「雇用形態」の欄がない。足すのは宿題", "Màn đăng ký・sửa của 運営 trong code chưa có ô 「雇用形態」. Việc thêm còn tồn"]},
    {"no": "2.6", "ja": "ステータス", "vi": "Trạng thái", "sel": "-", "kind": "select", "trig": "select", "err": ["E01"], "req": "○", "len": ["選択（有効／無効／利用停止／免許未登録）", "Chọn (hiệu lực / vô hiệu / tạm dừng / chưa đăng ký bằng lái)"], "ex": ["有効", "Hiệu lực"], "detail": ["新規は「有効」。委託の新規スタッフは「免許未登録」で登録しアカウントは発行しない。", "Đăng ký mới mặc định 「有効」. Nhân viên mới của bên ủy thác được đăng ký ở trạng thái 「免許未登録」 và không cấp tài khoản."]},
    {"no": "2.7", "ja": "電話番号", "vi": "Số điện thoại", "sel": "-", "kind": "text", "trig": "input", "err": ["E06"], "req": "－", "len": "文字列 20", "ex": ["050-1245-1245", "050-1245-1245"], "detail": ["数字とハイフン。", "Chữ số và dấu gạch nối."]},
    {"no": "2.8", "ja": "免許証", "vi": "Giấy phép lái xe", "sel": "-", "kind": "button", "trig": "click", "req": "－", "err": [], "detail": ["免許証の写真を運営の画面で登録・差し替えできる（点線の枠に画像を入れる。必須ではない。写真なしでも登録できる。台帳 P・2026-10-08）。写真がないときのステータスは「免許未登録」になり、アカウントは出さない。", "Bên vận hành có thể đăng ký・thay ảnh bằng lái trên màn hình (thả ảnh vào khung nét đứt. Không bắt buộc, đăng ký được dù chưa có ảnh. 台帳 P・2026-10-08). Khi không có ảnh, trạng thái là 「免許未登録」 và không cấp tài khoản."]},
    {"no": "3", "ja": "担当者", "vi": "Người phụ trách", "sel": "-", "kind": "area", "trig": "view", "detail": ["参考画面の「担当者」のカード。配送スタッフ本人のアカウントの情報。", "Thẻ 「担当者」 của màn hình tham khảo. Là thông tin tài khoản của chính nhân viên giao hàng."]},
    {"no": "3.1", "ja": "ログインID", "vi": "ID đăng nhập", "sel": "-", "kind": "label", "trig": "view", "detail": ["配送スタッフIDと同じ（DR＋5桁）。表示だけ。", "Giống ID nhân viên giao hàng (DR + 5 chữ số). Chỉ hiển thị."]},
    {"no": "3.2", "ja": "メールアドレス", "vi": "Địa chỉ email", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E07"], "req": "○", "len": "文字列 160", "ex": ["sample@email.com", "sample@email.com"], "detail": ["ログイン案内・パスワード再設定のメールの宛先。ほかのスタッフと同じアドレスでも登録できる（台帳 S #469。メールでログインする運営のアカウントは別で、重複不可）。", "Địa chỉ nhận email hướng dẫn đăng nhập và đặt lại mật khẩu. Có thể đăng ký cùng địa chỉ với nhân viên khác (台帳 S #469; tài khoản 運営 đăng nhập bằng email thì khác, không được trùng)."], "ask": "hong"},
    {"no": "3.3", "ja": "最終ログイン日時", "vi": "Thời điểm đăng nhập lần cuối", "sel": "-", "kind": "label", "trig": "view", "detail": ["最後にログインした日時。表示だけ（まだのときは「—」）。", "Thời điểm đăng nhập gần nhất. Chỉ hiển thị (chưa đăng nhập thì hiện 「—」)."]},
    {"no": "3.4", "ja": "パスワード送信", "vi": "Gửi mật khẩu", "sel": "-", "kind": "button", "trig": "click", "err": ["Q173", "S173", "E30"], "detail": ["メールアドレスへ、パスワード設定（再設定）の案内を送る。押すと確認（Q173）→ 送ったら S173。登録前・無効・削除済は押せない。", "Gửi hướng dẫn thiết lập (đặt lại) mật khẩu tới địa chỉ email. Bấm thì hiện xác nhận (Q173) → gửi xong hiện S173. Không bấm được khi chưa đăng ký, vô hiệu hoặc đã xóa."]},
    {"no": "4", "ja": "キャンセル", "vi": "Hủy bỏ", "sel": "-", "kind": "button", "trig": "click", "err": ["Q02"], "detail": ["一覧へ戻る（編集のときは詳細へ）。入力を変えていたら Q02（キャンセル／破棄）。", "Quay về danh sách (khi đang sửa thì quay về chi tiết). Nếu đã thay đổi nội dung nhập thì hiển thị Q02 (Hủy / Bỏ thay đổi)."]},
    {"no": "5", "ja": "登録・保存", "vi": "Đăng ký・Lưu", "sel": "-", "kind": "button", "trig": "click", "err": ["S01", "E30", "E31"], "detail": ["押すとまとめてチェック（項目の下にエラー・赤枠。保存ボタンの横に「保存できません（n件）」）。エラーがなければ保存して S01。ボタンは押したら無効にする。ほかの人が先に保存していたら E31（P-FORM）。", "Khi bấm sẽ kiểm tra toàn bộ cùng lúc (lỗi và viền đỏ bên dưới từng mục; bên cạnh nút lưu hiển thị 「保存できません（n件）」). Nếu không có lỗi thì lưu và hiển thị S01. Nút bị vô hiệu hóa sau khi bấm. Nếu người khác đã lưu trước thì hiển thị E31 (P-FORM)."]},
]

I5 = [
    {"no": "1", "ja": "削除の確認", "vi": "Xác nhận xóa", "sel": ".modal", "kind": "modal", "trig": "click", "pattern": "P-DEL", "err": ["Q01", "S02", "E30"], "detail": ["タイトル「削除」。「キャンセル」「削除する」。「削除する」で論理削除（状態＝削除済）して S02。一覧から外れ、検索条件で「削除済」を選ぶと表示される。削除すると、この配送スタッフのアカウントはログインできなくなる。", "Tiêu đề 「削除」. Có 「キャンセル」「削除する」. Khi nhấn 「削除する」 thì xóa logic (trạng thái = đã xóa) và hiện S02. Bị loại khỏi danh sách; chọn 「削除済」 ở điều kiện tìm kiếm thì sẽ hiển thị. Khi xóa, tài khoản của nhân viên giao hàng này không thể đăng nhập."]},
]

I6 = [
    {"no": "1", "ja": "削除できない", "vi": "Không thể xóa", "sel": ".ov .mbox", "kind": "modal", "trig": "click", "err": ["E244", "E451"], "detail": ["次のどちらかのときは削除できない：①担当中の配送（予定〜再配送待）がある（E244）②保冷バッグ・保冷剤の貸与で未返却がある（返却数＜貸与数で、状態が「紛失」「廃棄」ではないもの。紛失・廃棄は運営が記録した時点で処理済みなので数えない：E451）。両方あるときは両方の理由を並べる。モーダルの「閉じる」で閉じる。OW（OW_STAF No.13）と同じ条件（台帳 S・受付簿 #467・#468）。", "Không xóa được nếu thuộc một trong hai: ① còn chuyến đang phụ trách (予定〜再配送待) (E244) ② còn túi/đá giữ lạnh chưa trả (số trả < số mượn, trạng thái không phải 「紛失」「廃棄」; 紛失・廃棄 do 運営 ghi nhận là đã xử lý nên không tính: E451). Có cả hai thì xếp cả hai lý do. Đóng modal bằng 「閉じる」. Cùng điều kiện với OW (OW_STAF No.13) (台帳 S・受付簿 #467・#468)."]},
]

I7 = [
    {"no": "1", "ja": "0件の表示", "vi": "Hiển thị 0 bản ghi", "sel": ".tbl, .empty", "kind": "area", "trig": "view", "pattern": "P-LIST", "err": ["I01"], "detail": ["検索条件に合う配送スタッフがないとき、一覧の中に I01「表示するデータがありません。」を出す（P-LIST）。ページ送りは出さない。条件は「クリア」で戻せる。", "Khi không có nhân viên giao hàng nào khớp điều kiện tìm kiếm, hiển thị I01「表示するデータがありません。」trong danh sách (P-LIST). Không hiển thị phân trang. Có thể khôi phục điều kiện bằng 「クリア」."]},
]

I8 = [
    {"no": "1", "ja": "参照のみ（権限が閲覧だけの役割）", "vi": "Chỉ xem (vai trò chỉ có quyền xem)", "sel": ".ph", "kind": "area", "trig": "view", "cond": ["経理（配送スタッフは閲覧のみ）", "Kế toán (「経理」) (nhân viên giao hàng chỉ được xem)"], "detail": ["経理（配送スタッフは閲覧のみ）。「新規登録」「CSV取込」「アカウント一括発行」は出さない。CSV出力は出す（P-LIST・権限表）。", "Kế toán (「経理」) (nhân viên giao hàng chỉ được xem). Không hiển thị 「新規登録」「CSV取込」「アカウント一括発行」. Vẫn hiển thị xuất CSV (P-LIST・bảng quyền)."]},
    {"no": "2", "ja": "一覧の操作の列", "vi": "Cột thao tác của danh sách", "sel": ".tbl", "kind": "table", "trig": "view", "detail": ["行の鉛筆（編集）・ごみ箱（削除）・「契約の一括変更」は出さない。名前のリンクで詳細は開ける（詳細も「編集」「削除」を出さない）。", "Không hiển thị biểu tượng bút chì (sửa), thùng rác (xóa) ở từng dòng và 「契約の一括変更」. Vẫn mở được chi tiết bằng liên kết tên (trong chi tiết cũng không hiển thị 「編集」「削除」)."]},
]

I9 = [
    {"no": "1", "ja": "必須の入力エラー", "vi": "Lỗi nhập bắt buộc", "sel": ".emsg", "kind": "label", "trig": "view", "pattern": "P-FORM", "err": ["E01", "E04"], "detail": ["何も入れずに「登録」を押すと、必須の項目の下に E01 を出して赤枠にする（保存しない）。形式・文字数のエラーも同じ並びで項目の下に出す。最初のエラーの項目へスクロールする。保存ボタンの横に「保存できません（n件）」を出す。", "Nếu bấm 「登録」 khi chưa nhập gì, hiển thị E01 bên dưới các mục bắt buộc và tô viền đỏ (không lưu). Lỗi về định dạng・số ký tự cũng hiển thị bên dưới từng mục theo cùng thứ tự. Cuộn đến mục lỗi đầu tiên. Bên cạnh nút lưu hiển thị 「保存できません（n件）」."]},
]

I10 = [
    {"no": "1", "ja": "タブ", "vi": "Tab", "sel": "-", "kind": "tab", "trig": "click", "pattern": "P-TAB", "detail": ["詳細の上のタブ。「基本情報」「変更履歴」。初期は「基本情報」。", "Tab phía trên chi tiết. 「基本情報」「変更履歴」. Mặc định là 「基本情報」."]},
    {"no": "2", "ja": "変更履歴の表", "vi": "Bảng lịch sử thay đổi", "sel": "-", "kind": "table", "trig": "view", "pattern": "P-HIST", "err": ["I01"], "detail": ["列：変更日時・変更内容・変更者。新しい順。1ページ 10件。0件は I01。履歴に「影響した拠点数」「バージョン」は持たない（P-HIST）。変更者＝運営のアカウント名／「CSV取込」／委託配送先（自社スタッフの変更）。表示だけ（直せない）。", "Cột: thời điểm thay đổi, nội dung thay đổi, người thay đổi. Mới nhất lên trước. 10 dòng/trang. 0 dòng hiện I01. Lịch sử không có 「影響した拠点数」「バージョン」 (P-HIST). Người thay đổi = tên tài khoản vận hành / 「CSV取込」 / đơn vị giao hàng ủy thác (thay đổi nhân viên tự công ty). Chỉ hiển thị (không sửa được)."]},
]

I11 = [
    {"no": "1", "ja": "取り込みの手順（ステップ）", "vi": "Các bước nhập (bước)", "sel": ".steps", "kind": "area", "trig": "view", "pattern": "P-CSV", "detail": ["上に ①ファイルを選ぶ ②確認・登録 の2ステップ。いまは ② 。「ファイルを選び直す」で ① へ戻る（取り込んだ内容は捨てる）。", "Phía trên có 2 bước: ① Chọn file ② Xác nhận・đăng ký. Hiện đang ở bước ②. Nhấn 「ファイルを選び直す」 để quay lại ① (bỏ nội dung đã nhập)."]},
    {"no": "2", "ja": "ファイル名・件数", "vi": "Tên file・số bản ghi", "sel": ".badge", "kind": "label", "trig": "view", "detail": ["ファイル名と全体の件数。バッジで 新規／更新／変更なし／エラー の件数を出す。", "Tên file và tổng số bản ghi. Badge hiển thị số lượng Mới / Cập nhật / Không đổi / Lỗi."]},
    {"no": "3", "ja": "エラーの行（通知と表）", "vi": "Dòng lỗi (thông báo và bảng)", "sel": ".notice.ng", "kind": "area", "trig": "view", "err": ["E34"], "detail": ["エラーの行がある間は赤の通知「エラーの行 n件は取り込みません（行番号と内容は下の表）。ほかの行は「登録」で登録します。」と、エラー一覧（行番号・キー・列名・内容）を出す。エラー一覧は CSV でも出せる（「エラー一覧CSV」）。エラーの行は取り込まない（hong 2026/10/05）。", "Khi còn dòng lỗi, hiển thị thông báo đỏ 「エラーの行 n件は取り込みません（行番号と内容は下の表）。ほかの行は「登録」で登録します。」 và danh sách lỗi (số dòng・khóa・tên cột・nội dung). Danh sách lỗi cũng xuất được ra CSV (「エラー一覧CSV」). Dòng lỗi không được nhập (hong 2026/10/05)."]},
    {"no": "4", "ja": "登録する内容（前 → 後）", "vi": "Nội dung sẽ đăng ký (trước → sau)", "sel": ".tbl", "kind": "table", "trig": "view", "pattern": "P-LIST", "detail": ["列：行番号・区分（新規／更新）・キー・名前・変わる項目（前 → 後）。変わらない行は出さない。1ページ 10件。", "Cột: số dòng・phân loại (mới/cập nhật)・khóa・tên・mục thay đổi (trước → sau). Dòng không thay đổi thì không hiển thị. 10 dòng mỗi trang."]},
    {"no": "5", "ja": "登録", "vi": "Đăng ký", "sel": ".btn.pri.lg", "kind": "button", "trig": "click", "err": ["S03", "E34"], "cond": ["取り込めるデータが1行以上あるとき", "Khi có từ 1 dòng dữ liệu nhập được trở lên"], "detail": ["エラー以外の行を登録する。成功したら S03「n件を登録しました」を出して一覧へ。登録できる行が0件のときは押せない。取り込むとき変更履歴に「CSV取込」の名前で残る。", "Đăng ký các dòng không lỗi. Thành công thì hiện S03 「n件を登録しました」 và chuyển về danh sách. Không nhấn được khi số dòng có thể đăng ký là 0. Khi nhập, lịch sử thay đổi ghi lại với tên 「CSV取込」."]},
    {"no": "6", "ja": "ファイルを選び直す", "vi": "Chọn lại file", "sel": ".btn.out", "kind": "button", "trig": "click", "detail": ["① へ戻る。", "Quay lại ①."]},
]

VIEWS = [
    V("001", "AW_DRVR_001", "初期表示", "Hiển thị ban đầu", "/ops/masters/drivers", I1),
    V("002", "AW_DRVR_002", "初期表示（ステップ1 ファイルを選ぶ）", "Hiển thị ban đầu (Bước 1 Chọn tệp)", "/ops/masters/drivers/import", I2),
    V("003", "AW_DRVR_003", "詳細", "Chi tiết", "/ops/masters/drivers/DR00001", I3),
    V("004", "AW_DRVR_004", "登録・編集", "Đăng ký・sửa", "/ops/masters/drivers/new", I4),
    V("005", "AW_DRVR_001", "削除の確認", "Xác nhận xóa", "/ops/masters/drivers", I5, setup="document.querySelector('.tbl tbody tr .act button:last-child')?.click(); await sleep(300);"),
    V("006", "AW_DRVR_001", "削除できない（割り当て中）", "Không thể xóa (đang được phân công)", "/ops/masters/drivers", I6, setup="document.querySelector('.tbl tbody tr .act button:last-child')?.click(); await sleep(300); [...document.querySelectorAll('.modal button')].find(b=>(b.textContent||'').includes('削除する'))?.click(); await sleep(500);"),
    V("007", "AW_DRVR_001", "0件（検索結果なし）", "0 bản ghi (không có kết quả tìm kiếm)", "/ops/masters/drivers", I7, setup="const kw=document.querySelector('.es-search input'); if(kw){Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(kw,'zzzzzz'); kw.dispatchEvent(new Event('input',{bubbles:true})); await sleep(200); clickText('button','検索'); await sleep(600);}"),
    V("008", "AW_DRVR_001", "参照のみ（閲覧の権限だけ）", "Chỉ xem (chỉ có quyền xem)", "/ops/masters/drivers", I8, login="Ad00012"),
    V("009", "AW_DRVR_004", "入力エラー", "Lỗi nhập", "/ops/masters/drivers/new", I9, setup="clickText('.ph button','登録'); await sleep(500);"),
    V("011", "AW_DRVR_003", "詳細（変更履歴のタブ）", "Chi tiết (tab lịch sử thay đổi)", "/ops/masters/drivers/DR00001?tab=hist", I10),
    V("010", "AW_DRVR_002", "確認・登録（ステップ2）", "Xác nhận・đăng ký (bước 2)", "/ops/masters/drivers/import", I11, setup="const res=await fetch('/api/domain/csv/export',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','x-es-site':'ops'},body:JSON.stringify({args:{entity:'drivers',scope:{site:'ops'}}})});const t=await res.json();const esc=v=>'\"'+String(v??'').replace(/\"/g,'\"\"')+'\"';const rows=[t.head,...t.rows];const r0=t.rows[0];const ni=t.head.findIndex(h=>/配送スタッフ名|氏名|名前/.test(h));if(ni>=0)r0[ni]=r0[ni]+' X';const bad=t.rows[0].slice();bad[0]='XX999999';rows.push(bad);const text='\\ufeff'+rows.map(r=>r.map(esc).join(',')).join('\\r\\n');const inp=document.querySelector('input[type=file]');const dt=new DataTransfer();dt.items.add(new File([text],'取込テスト.csv',{type:'text/csv'}));inp.files=dt.files;inp.dispatchEvent(new Event('change',{bubbles:true}));await sleep(2500);", note=["ファイルを選んだ直後。見本は今のデータの CSV出力に、1行目の名前を変えた（更新の見本）と、キーが誤りの行を1つ足したもの（エラーの行の見本）。", "Ngay sau khi chọn file. File mẫu là CSV xuất từ dữ liệu hiện tại, đổi tên ở dòng 1 (mẫu cập nhật) và thêm 1 dòng có khóa sai (mẫu dòng lỗi)."]),
]
