# -*- coding: utf-8 -*-
"""
画面設計書のデータ：運営管理者Web ＞ マスタ管理 ＞ 仕入先マスタ（一覧・申込の確認・却下・CSV取込）
元：本物の Web（app/ops/masters/suppliers・app/ops/_general/gen.ts の supplier・lib/csv/master.ts（suppliers）・lib/ops/general/suppliers.ts）、台帳 I・138・運営Web_権限表（仕入先管理）・Mail List No.26・CSV入出力_定義
番号は画面ごとに通し。タブ・モーダルの状態では、その状態で増える・変わる項目だけ書く。
（運営H2：hong の確認前の提案を含む。提案は DECISIONS で「提案」と書き、open に確認先を残してある）
"""

TITLE = ["仕入先マスタ（AW_SUPP）", "Master nhà cung cấp (AW_SUPP)"]
SHEET = ["仕入先マスタ", "Master nhà cung cấp"]
BASENAME = "画面設計書_AW_SUPP_仕入先マスタ"
IMG_PREFIX = "AW_SUPP"
OUT_DIR = "AW_SUPP_仕入先マスタ"
CODE_NOTE = ["画面コードは規約 <Module(2)>_<Feature(4)>_<Seq(3)>（docs/01_仕様/画面コード規約_20261005.md）。AW＝運営管理者Web、SUPP＝仕入先マスタ",
             "Mã màn hình theo quy ước <Module(2)>_<Feature(4)>_<Seq(3)>. AW = Admin Web, SUPP = Master nhà cung cấp"]
SITE = "ops"
SYSTEM = {"ja": "運営管理者Web", "vi": "Web quản trị vận hành"}
AUTHOR = "Claude（cloud）／確認：hong"
CREATED = "2026-10-06"
DEMO_FILE = "http://localhost:3000"
LOGIN = {"site": "ops", "loginId": "Ad00010"}
CODE_PATHS = "[\"app/ops/masters/suppliers\", \"app/ops/_general\", \"lib/csv/master.ts\", \"lib/ops/general\"]"

DECISIONS = [
    {"date": "2026-10-06", "target": "登録・編集のしかた", "q": ["運営の画面で新規登録・編集の画面（フォーム）を作るか", "Có tạo màn hình đăng ký mới/chỉnh sửa (biểu mẫu) trong màn hình vận hành hay không"], "a": ["作る（プランマスタと同じ：一覧 → 詳細（表示だけ）→ 登録・編集）。CSV取込も残す（一括）。これまでの案「CSV取込だけ」は置き換え。配送スタッフも作る（台帳「ドライバーのログインID」：運営には新規登録の画面を作らず CSV取込 → 置き換え）", "Làm mới (giống master gói dịch vụ: danh sách → chi tiết (chỉ hiển thị) → đăng ký/sửa). Vẫn giữ nhập CSV (hàng loạt). Phương án trước đây 「chỉ nhập CSV」 được thay thế. Cũng làm cho nhân viên giao hàng (「台帳」 'ID đăng nhập của tài xế': trước đây vận hành không có màn hình đăng ký mới mà chỉ nhập CSV → được thay thế)"], "src": "hong 回答 2026-10-06（運営H2 A＝C）・台帳 F・受付簿 No.167"},
    {"date": "2026-10-06", "target": "削除と無効の扱い", "q": ["削除のしかたと、削除・無効にしたときのログイン", "Cách xóa, và việc đăng nhập khi đã xóa hoặc vô hiệu hóa"], "a": ["論理削除（状態＝削除済）。削除できない条件を置く（使用中は削除できない。条件の中身は仕入先＝進行中の発注／倉庫＝在庫・利用中の契約／委託配送先＝利用中の契約・配送予定・所属スタッフ／配送スタッフ＝割り当て済みの配送。hong 確認 2026-10-06）。状態が「削除済」「無効」のアカウントはログインできない", "Xóa logic (trạng thái 削除済). Có điều kiện chặn xóa (đang sử dụng thì không xóa được; nội dung điều kiện: 仕入先 = đơn đặt hàng đang xử lý / 倉庫 = tồn kho・hợp đồng đang dùng / 委託配送先 = hợp đồng・lịch giao đang dùng・nhân viên trực thuộc / 配送スタッフ = lượt giao đã phân công; hong xác nhận 2026-10-06). Tài khoản ở trạng thái 「削除済」「無効」 không đăng nhập được."], "src": "hong 回答 2026-10-06（運営H2 B）・台帳 F・受付簿 No.167"},
    {"date": "2026-10-06", "target": "仕入れ先区分", "q": ["仕入れ先区分の選択肢", "Các lựa chọn của phân loại nhà cung cấp"], "a": ["固定の3つ：通常商品／短消費期限商品／資材（仕入先Web の申込フォームと同じ。区分マスタにはしない）。運営の登録・編集でも同じ選択肢", "Cố định 3 loại: hàng thường / hàng hạn dùng ngắn / vật tư (giống form đăng ký của Web nhà cung cấp; không làm master phân loại). Khi vận hành đăng ký/sửa cũng dùng các lựa chọn này."], "src": "hong 確認 2026-10-06（運営H2）・コード（仕入先Web apply）"},
    {"date": "2026-10-06", "target": "アカウント一括発行の文言", "q": ["アカウント一括発行の確認・結果の文言", "Câu chữ xác nhận và kết quả của cấp tài khoản hàng loạt"], "a": ["確認 Q170・成功 S172・発行できなかった行は E240 のモーダルで理由つき。メールは Mail List No.26", "Xác nhận Q170, thành công S172, các dòng không cấp được hiện ở modal E240 kèm lý do. Email dùng Mail List No.26"], "src": "hong 回答 2026-10-06（運営H2 #2）"},
    {"date": "2026-10-06", "target": "申込の却下メール", "q": ["却下のメール", "Email từ chối"], "a": ["Mail List No.27「仕入先のお申込み結果（却下）」を使う（理由を「■ 理由：」に入れる）。新しいメールは作らない", "Dùng Mail List No.27 「仕入先のお申込み結果（却下）」 (đưa lý do vào 「■ 理由：」). Không tạo email mới."], "src": "Mail List No.27（hong 回答 2026-10-06 #3）"},
    {"date": "2026-10-06", "target": "権限", "q": ["だれが見られる・操作できるか", "Ai được xem và thao tác"], "a": ["フル権限・システム管理・商品開発＝CRUD、ほか＝R。申込の承認・却下は承認（approve）の権限", "Toàn quyền・quản trị hệ thống・phát triển sản phẩm = CRUD, các vai trò khác = R. Duyệt・từ chối đơn đăng ký dùng quyền duyệt (approve)"], "src": "運営Web_権限表（仕入先管理）"},
    {"date": "2026-10-01", "target": "仕入先のアカウントと申込", "q": ["仕入先のアカウント・申込", "Tài khoản và đơn đăng ký của nhà cung cấp"], "a": ["1社1アカウント。申込は仕入先マスタの「申込の確認」で承認。プロフィールの変更に運営の承認は挟まない。ID の頭文字は SP", "Mỗi công ty một tài khoản. Đơn đăng ký được duyệt trong 「申込の確認」 của nhà cung cấp master. Việc thay đổi hồ sơ không cần vận hành duyệt. Chữ cái đầu của ID là SP"], "src": "台帳 I（仕入先のアカウント・申込）・「仕入先の ID の頭文字」"},
    {"date": "2026-10-05", "target": "アカウント一括発行", "q": ["仕入先のアカウント一括発行", "Cấp tài khoản hàng loạt cho nhà cung cấp"], "a": ["フェーズ2でやる", "Làm ở giai đoạn 2"], "src": "台帳 138"},
    {"date": "2026-10-06", "target": "画面コード", "q": ["画面コード", "Mã màn hình"], "a": ["AW_SUPP_001〜004", "AW_SUPP_001〜004"], "src": "画面コード規約（Feature は Claude 案・hong 確認待ち）"},
]
CHANGES = [{"ver": "1.11", "date": "2026-10-06", "no": "*", "type": "追加", "reason": ["仕入先マスタの画面設計書を新規に作成（hong の確認済み・受付簿 No.164〜168）", "Tạo mới tài liệu thiết kế màn hình Master nhà cung cấp (đã được hong xác nhận, 受付簿 No.164〜168)"], "impact": ["一覧・詳細・登録／編集・申込の確認／却下・CSV取込。論理削除と使用中は削除不可（E241）、無効／削除済はログイン不可。実装済（受付簿 No.164・167）", "Danh sách, chi tiết, đăng ký/sửa, xác nhận/từ chối đơn đăng ký, nhập CSV. Xóa logic, không xóa khi đang dùng (E241), 無効/削除済 không đăng nhập được. Đã triển khai (受付簿 No.164・167)"]}, {"ver": "1.12", "date": "2026-10-06", "no": ["1", "2"], "type": "追加", "reason": ["役割レビュー（BA・QC・UI/UX）の指摘への対応", "Xử lý các góp ý từ review vai trò (BA・QC・UI/UX)"], "impact": ["表示の確認のための状態。動きは変更なし", "Trạng thái để kiểm tra hiển thị. Hành vi không đổi"]}, {"ver": "1.12", "date": "2026-10-06", "no": ["1.2", "1.3", "1.4", "1.12", "1.13"], "type": "変更", "reason": ["役割レビュー（BA・QC・UI/UX）の指摘への対応", "Xử lý các góp ý từ review vai trò (BA・QC・UI/UX)"], "impact": ["動きは変更なし（番号の場所と説明の追記）", "Hành vi không đổi (chỉ tách vị trí đánh số và bổ sung mô tả)"], "before": ["「キャンセル／登録・保存」を1項目", "Gộp 「キャンセル／登録・保存」 thành 1 mục"], "after": ["「キャンセル」と「登録・保存」を分ける／新規登録に P-FORM", "Tách 「キャンセル」 và 「登録・保存」 / nút đăng ký mới theo P-FORM"]}, {"ver": "1.17", "date": "2026-10-07", "no": ["1.2"], "type": "追加", "reason": ["hong の回答（2026-10-07）への対応", "Xử lý trả lời của hong (2026-10-07)"], "impact": ["パスワード送信のメールを確定（仕入先・委託配送先は Mail List No.30、配送スタッフは No.3 の認証コード）。委託配送先のアカウント発行は Mail List No.29。履歴の変更者はログイン中のアカウント。実装済（受付簿 No.190）", "Chốt email gửi mật khẩu (nhà cung cấp・đơn vị vận chuyển dùng Mail List No.30, nhân viên giao hàng dùng mã xác thực No.3). Cấp tài khoản đơn vị vận chuyển dùng Mail List No.29. Người thay đổi trong lịch sử là tài khoản đang đăng nhập. Đã triển khai (受付簿 No.190)"]}]
HIDE_ALWAYS = []
STATIC_CSS = ""
VIEWER_CSS = ""

SCREENS = [
    {"code": "AW_SUPP_001", "ja": "仕入先一覧", "vi": "Danh sách nhà cung cấp"},
    {"code": "AW_SUPP_002", "ja": "仕入先の申込の確認", "vi": "Xác nhận đơn đăng ký nhà cung cấp"},
    {"code": "AW_SUPP_003", "ja": "申込の却下", "vi": "Từ chối đơn đăng ký"},
    {"code": "AW_SUPP_004", "ja": "仕入先 CSV取込", "vi": "Nhập CSV nhà cung cấp"},
    {"code": "AW_SUPP_005", "ja": "仕入先詳細", "vi": "Chi tiết nhà cung cấp"},
    {"code": "AW_SUPP_006", "ja": "仕入先の登録・編集", "vi": "Đăng ký / sửa nhà cung cấp"},
    {"code": "AW_SUPP_007", "ja": "仕入先の申込の内容", "vi": "Nội dung đơn đăng ký nhà cung cấp"},
]

H = (
    "const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));"
    "const tab=(t)=>[...document.querySelectorAll('.tabs button')].find(b=>(b.textContent||'').trim()===t)?.click();"
    "const clickText=(sel,t,i)=>{const b=[...document.querySelectorAll(sel)].filter(x=>(x.textContent||'').includes(t))[i||0];b&&b.click();};"
)



def V(id, code, ja, vi, url, items, setup="", note=None, full=True, wait=600, login=None):
    v = {"id": id, "code": code, "state": [ja, vi], "url": url, "setup": (H + setup) if setup else "", "full": full, "wait": wait, "note": note or ["", ""], "items": items}
    if login:
        v["login"] = login
    return v


I1 = [
    {"no": "1", "ja": "ヘッダー", "vi": "Header", "sel": ".ph", "kind": "area", "trig": "view", "detail": ["パンくず：マスタ管理 ＞ 仕入先マスタ。見られるのは運営の全役割（フル権限・システム管理・商品開発は操作もできる。ほかは閲覧のみ：権限表「仕入先管理」）。", "Breadcrumb: マスタ管理 ＞ 仕入先マスタ. Tất cả các vai trò vận hành đều xem được (toàn quyền・quản trị hệ thống・phát triển sản phẩm có thể thao tác. Các vai trò khác chỉ xem: bảng quyền 「仕入先管理」)."]},
    {"no": "1.1", "ja": "アカウント一括発行", "vi": "Cấp tài khoản hàng loạt", "sel": ".ph", "kind": "button", "trig": "click", "err": ["Q170", "S172", "E240", "E30"], "detail": ["選んだ仕入先にアカウント（ログインID＝仕入先ID）を一括で発行する（左のチェックで選ぶ。選ばないと押せない。件数を表示）。担当者に Mail List No.26 のメールで知らせる。押すと確認（Q170：「選んだ{n}件のアカウントを発行し、担当者にログイン案内メールを送ります。よろしいですか？」「キャンセル」「発行する」）。成功したら S172（「{n}件のアカウントを発行しました。」）。発行できなかった行があれば、続けて E240 のモーダル（「{m}件は発行できませんでした。」）に一覧で理由を出す：無効／発行済／メールアドレスがない／申込中（承認で発行）／却下。押せるのは作成（create）の権限がある役割だけ。", "Cấp tài khoản hàng loạt (ID đăng nhập = ID nhà cung cấp) cho các nhà cung cấp đã chọn (chọn bằng ô tick bên trái; chưa chọn thì không nhấn được; hiện số lượng). Báo người phụ trách bằng email Mail List No.26. Nhấn thì hiện xác nhận (Q170: 「Sẽ cấp {n} tài khoản đã chọn và gửi email hướng dẫn đăng nhập cho người phụ trách. Xác nhận?」 nút 「キャンセル」「発行する」). Thành công hiện S172 (「Đã cấp {n} tài khoản.」). Nếu có dòng không cấp được thì hiện tiếp modal E240 (「Có {m} mục không cấp được.」) liệt kê lý do từng dòng: 無効／発行済／メールアドレスがない／申込中 (duyệt thì cấp)／却下. Chỉ vai trò có quyền tạo (create) mới nhấn được."]},
    {"no": "1.2", "ja": "CSV出力", "vi": "Xuất CSV", "sel": ".ph", "kind": "button", "trig": "click", "pattern": "P-CSV-OUT", "detail": ["ヘッダーの右。仕入先の全項目（CSV取込と同じ列）（検索条件のとおりの全件）。見られる役割には全員に出す。", "Bên phải header. Toàn bộ mục của nhà cung cấp (cùng cột với nhập CSV) (toàn bộ số bản ghi theo điều kiện tìm kiếm). Hiển thị cho tất cả các vai trò được phép xem."]},
    {"no": "1.3", "ja": "CSV取込", "vi": "Nhập CSV", "sel": ".ph", "kind": "button", "trig": "click", "pattern": "P-CSV", "detail": ["CSV取込の画面（/ops/masters/suppliers/import）へ。CSV取込の権限（フル権限・システム管理）がない役割には出さない。", "Chuyển đến màn hình nhập CSV (/ops/masters/suppliers/import). Không hiển thị với vai trò không có quyền nhập CSV (toàn quyền・quản trị hệ thống)."]},
    {"no": "1.4", "ja": "新規登録", "vi": "Đăng ký mới", "sel": ".ph .btn.pri", "kind": "button", "trig": "click", "pattern": "P-FORM", "detail": ["仕入先の登録（AW_SUPP_006）へ。登録の権限（フル権限・システム管理）がない役割には出さない。", "Chuyển đến đăng ký nhà cung cấp (AW_SUPP_006). Không hiển thị với vai trò không có quyền đăng ký (toàn quyền, quản trị hệ thống)."]},
    {"no": "2", "ja": "申込の確認の帯", "vi": "Thanh xác nhận đơn đăng ký", "sel": ".notice", "kind": "area", "trig": "view", "err": ["I01"], "detail": ["「仕入先からの取引の申込が n件あります（申込中）。内容を確認して、承認（アカウントを発行）か却下を選びます。」＋ボタン「申込を確認する」（押すと AW_SUPP_002）。0件のときは出さない。", "「Có n đơn đăng ký giao dịch từ nhà cung cấp (đang đăng ký). Hãy xác nhận nội dung và chọn duyệt (cấp tài khoản) hoặc từ chối.」 + nút 「申込を確認する」 (bấm vào sẽ mở AW_SUPP_002). Không hiển thị khi có 0 đơn."]},
    {"no": "3", "ja": "検索条件", "vi": "Điều kiện tìm kiếm", "sel": ".card", "kind": "area", "trig": "view", "pattern": "P-LIST", "detail": ["キーワード（仕入先ID・仕入先名）／ステータス（申込中・却下・本登録・未発行）／作れる商品／仕入れ先区分。発注方法・土日祝を営業日では絞らない（hong の参考画面に合わせて列と条件を減らした：2026-10-06）。", "Từ khóa (ID nhà cung cấp・tên nhà cung cấp) / Trạng thái (đang đăng ký・từ chối・đăng ký chính thức・chưa cấp) / Sản phẩm có thể làm / Phân loại nhà cung cấp. Không lọc theo phương thức đặt hàng・ngày làm việc thứ 7/CN/lễ (đã giảm cột và điều kiện theo màn hình tham khảo của hong: 2026-10-06)."]},
    {"no": "4", "ja": "一覧", "vi": "Danh sách", "sel": ".tbl", "kind": "table", "trig": "view", "pattern": "P-LIST", "err": ["I01"], "detail": ["初期の並びは仕入先IDの昇順。1ページ 10件。0件は I01。左端のチェックで行を選ぶ（アカウント一括発行用。作成の権限がある役割だけ。申込中・却下・無効・削除済の行は選べない）。削除済は出さない。", "Thứ tự ban đầu là ID nhà cung cấp tăng dần. 10 dòng mỗi trang. Khi 0 kết quả hiển thị I01. Chọn dòng bằng ô tích ngoài cùng bên trái (dùng cho cấp tài khoản hàng loạt. Chỉ vai trò có quyền tạo. Dòng đang đăng ký・từ chối・vô hiệu・đã xóa không chọn được). Không hiển thị dòng đã xóa."]},
    {"no": "4.1", "ja": "仕入先ID", "vi": "ID nhà cung cấp", "sel": ".tbl th::仕入先ID", "kind": "label", "trig": "view", "detail": ["SP＋5桁（システムが採番：台帳「仕入先の ID の頭文字」）。", "SP + 5 chữ số (hệ thống tự cấp số: 「台帳」「Chữ cái đầu của ID nhà cung cấp」)."]},
    {"no": "4.2", "ja": "仕入先名", "vi": "Tên nhà cung cấp", "sel": ".tbl .lnk", "kind": "link", "trig": "click", "detail": ["名前は下線つきのリンク。押すと詳細（AW_SUPP_005）へ。", "Tên là liên kết có gạch chân. Nhấn vào sẽ chuyển đến chi tiết (AW_SUPP_005)."]},
    {"no": "4.3", "ja": "本社住所", "vi": "Địa chỉ trụ sở chính", "sel": ".tbl th::本社住所", "kind": "label", "trig": "view", "detail": ["本社の住所。", "Địa chỉ trụ sở chính."]},
    {"no": "4.4", "ja": "担当者名", "vi": "Tên người phụ trách", "sel": ".tbl th::担当者名", "kind": "label", "trig": "view", "detail": ["担当者の名前。", "Tên của người phụ trách."]},
    {"no": "4.5", "ja": "担当者の電話番号", "vi": "Số điện thoại người phụ trách", "sel": ".tbl th::担当者の電話番号", "kind": "label", "trig": "view", "detail": ["半角の数字とハイフン。", "Chữ số và dấu gạch ngang bán góc."]},
    {"no": "4.9", "ja": "ステータス", "vi": "Trạng thái", "sel": ".tbl th::ステータス", "kind": "label", "trig": "view", "detail": ["バッジ：申込中／却下／本登録／未発行。", "Badge: đang đăng ký／từ chối／đã đăng ký chính thức／chưa cấp."]},
    {"no": "4.10", "ja": "操作（編集・削除）", "vi": "Thao tác (sửa・xóa)", "sel": ".tbl .act", "kind": "button", "trig": "click", "pattern": "P-DEL", "err": ["Q01", "S02", "E30"], "detail": ["鉛筆＝編集（AW_SUPP_006）、ごみ箱＝削除（確認 Q01 → 論理削除して S02）。進行中の発注があるときは削除できない（E241）。削除（と状態「無効」）にするとアカウントはログインできなくなる。削除済の行には出さない。操作の権限がない役割には出さない。", "Bút chì = sửa (AW_SUPP_006), thùng rác = xóa (xác nhận Q01 → xóa logic rồi hiện S02). Nếu có đơn đặt hàng đang tiến hành thì không thể xóa (E241). Khi xóa (và trạng thái 「無効」) thì tài khoản không thể đăng nhập. Không hiển thị ở dòng đã xóa. Không hiển thị với vai trò không có quyền thao tác."]},
    {"no": "5", "ja": "ページ送り", "vi": "Phân trang", "sel": ".pager", "kind": "area", "trig": "view", "pattern": "P-LIST", "detail": ["P-LIST のとおり（10／20／50件）。", "Theo P-LIST (10／20／50 dòng)."]},
]

I2 = [
    {"no": "1", "ja": "申込の確認モーダル（表）", "vi": "Modal xác nhận đơn đăng ký (bảng)", "sel": ".ov .mbox", "kind": "modal", "trig": "click", "err": ["I01"], "detail": ["タイトル「仕入先の申込の確認」（幅広）。申込中の仕入先を**表**で並べる（2件以上でも見やすい）。初期の並びは申込日時の古い順（先に来た申込から処理）。1ページ 10件。0件は I01「表示するデータがありません。」。", "Tiêu đề 「仕入先の申込の確認」 (rộng). Liệt kê các nhà cung cấp đang đăng ký dạng **bảng** (dễ xem kể cả từ 2 bản ghi). Thứ tự mặc định theo ngày giờ đăng ký cũ nhất trước (xử lý đơn đến trước). 10 dòng mỗi trang. 0 bản ghi hiện I01「表示するデータがありません。」."]},
    {"no": "1.1", "ja": "申込の一覧（表）", "vi": "Danh sách đơn đăng ký (bảng)", "sel": "-", "kind": "table", "trig": "view", "pattern": "P-LIST", "err": ["I01"], "detail": ["列：受付番号・申込日時・仕入先名・代表者・担当者・仕入れ先区分・作れる商品・操作。行の「内容を見る」か仕入先名のリンクで、その申込の内容（AW_SUPP_007）を開く。", "Cột: số tiếp nhận・ngày giờ đăng ký・tên nhà cung cấp・người đại diện・người phụ trách・phân loại nhà cung cấp・sản phẩm có thể làm・thao tác. Nhấn 「内容を見る」 ở dòng hoặc link tên nhà cung cấp để mở nội dung đơn (AW_SUPP_007)."]},
    {"no": "1.2", "ja": "内容を見る", "vi": "Xem nội dung", "sel": "-", "kind": "button", "trig": "click", "detail": ["その申込の内容（申込フォームに入れた全部の項目）を開く（AW_SUPP_007）。", "Mở nội dung đơn (toàn bộ mục đã nhập ở form đăng ký) (AW_SUPP_007)."]},
    {"no": "1.3", "ja": "説明", "vi": "Giải thích", "sel": "-", "kind": "label", "trig": "view", "detail": ["「承認するとアカウントを発行し、担当者にメールで知らせます。却下は理由を入れてメールで知らせます。発注方法（ESステーション／メール／外部）は承認のあと仕入先マスタで決めます。」", "「Khi duyệt sẽ cấp tài khoản và thông báo cho người phụ trách qua email. Khi từ chối sẽ nhập lý do và thông báo qua email. Phương thức đặt hàng (ESステーション／email／bên ngoài) được quyết định trong nhà cung cấp master sau khi duyệt.」"]},
    {"no": "1.4", "ja": "閉じる", "vi": "Đóng", "sel": ".mbox-f button::閉じる", "kind": "button", "trig": "click", "detail": ["モーダルを閉じる。", "Đóng modal."]},
]

I3 = [
    {"no": "1", "ja": "却下モーダル", "vi": "Modal từ chối", "sel": ".ov .mbox", "kind": "modal", "trig": "click", "pattern": "P-FORM", "err": ["S171", "E01", "E30"], "detail": ["タイトル「申込を却下する」。「戻る」「却下する」。", "Tiêu đề 「申込を却下する」. 「戻る」 và 「却下する」."]},
    {"no": "1.1", "ja": "理由（メールに書きます）", "vi": "Lý do (sẽ ghi trong email)", "sel": ".mbox textarea, .mbox input", "kind": "textarea", "trig": "input", "req": "○", "len": "文字列 500", "ex": ["取扱商品の区分が募集条件に合わないため", "Lý do từ chối đơn đăng ký, sẽ được ghi trong email gửi nhà cung cấp (văn bản tự do)"], "err": ["E01", "E04"], "detail": ["必須。500文字まで。仕入先へのメール（Mail List No.27「お申込み結果（却下）」の「■ 理由：」）にそのまま書く。", "Bắt buộc. Tối đa 500 ký tự. Ghi nguyên văn vào email gửi nhà cung cấp (mục 「■ 理由：」 trong Mail List No.27 「お申込み結果（却下）」)."]},
    {"no": "1.2", "ja": "戻る／却下する", "vi": "Quay lại／Từ chối", "sel": ".mbox-f button", "kind": "button", "trig": "click", "err": ["S171", "E01"], "cond": ["承認（approve）の権限がある役割だけ", "Chỉ vai trò có quyền duyệt (approve)"], "detail": ["「却下する」で状態を「却下」にし、理由を Mail List No.27 のメールで申込フォームの担当者に知らせて S171。理由が空なら E01（保存しない）。", "Nhấn 「却下する」 thì chuyển trạng thái sang 「却下」, báo lý do cho người phụ trách trong form đăng ký bằng email Mail List No.27 và hiện S171. Lý do để trống thì E01 (không lưu)."]},
]

I4 = [
    {"no": "1", "ja": "ヘッダー", "vi": "Header", "sel": ".ph", "kind": "area", "trig": "view", "pattern": "P-CSV", "err": ["S03", "E34"], "detail": ["見出し「仕入先マスタ CSV取込」。キャンセルで一覧へ戻る（何も登録しない）。CSV取込の権限（フル権限・システム管理）がある役割だけが開ける（ほかは一覧へ）。モーダルではなく画面（P-CSV）。", "Tiêu đề 「仕入先マスタ CSV取込」. Hủy thì quay lại danh sách (không đăng ký gì). Chỉ vai trò có quyền nhập CSV (toàn quyền・quản trị hệ thống) mới mở được (vai trò khác bị chuyển về danh sách). Là màn hình chứ không phải modal (P-CSV)."]},
    {"no": "2", "ja": "CSVテンプレートの列（定義。画面には出さない）", "vi": "Các cột của mẫu CSV (định nghĩa. Không hiển thị trên màn hình)", "sel": "-", "kind": "area", "trig": "view", "detail": ["取り込むファイルの列の定義（1行目の見出し・この順。CSV出力と同じ列）。", "Định nghĩa các cột của tệp nhập (tiêu đề dòng 1・theo thứ tự này. Cùng cột với xuất CSV)."]},
    {"no": "2.1", "ja": "仕入先ID", "vi": "ID nhà cung cấp", "sel": "-", "kind": "label", "trig": "view", "detail": ["【空欄＝新規（SP＋5桁で採番）】キー。申込中・却下の仕入先は「申込の確認から処理してください」（エラー）。", "[Để trống = mới (cấp số SP + 5 chữ số)] Khóa. Với nhà cung cấp đang đăng ký・từ chối thì báo lỗi 「申込の確認から処理してください」 (hãy xử lý từ phần xác nhận đơn đăng ký)."]},
    {"no": "2.2", "ja": "仕入先名", "vi": "Tên nhà cung cấp", "sel": "-", "kind": "label", "trig": "view", "len": "文字列 100", "detail": ["【新規は必須】エラー：仕入先名を入れてください。", "[Bắt buộc khi mới] Lỗi: 仕入先名を入れてください."]},
    {"no": "2.3", "ja": "本社住所", "vi": "Địa chỉ trụ sở chính", "sel": "-", "kind": "label", "trig": "view", "len": "文字列 255", "detail": ["【任意】", "[Tùy chọn]"]},
    {"no": "2.4", "ja": "担当者名", "vi": "Tên người phụ trách", "sel": "-", "kind": "label", "trig": "view", "len": "文字列 60", "detail": ["【任意】", "[Tùy chọn]"]},
    {"no": "2.5", "ja": "担当者の電話番号", "vi": "Số điện thoại người phụ trách", "sel": "-", "kind": "label", "trig": "view", "len": "文字列 20", "detail": ["【任意】半角の数字とハイフン（エラー：電話番号は半角の数字とハイフンで入れてください）。", "[Tùy chọn] Chữ số và dấu gạch ngang bán góc (lỗi: 電話番号は半角の数字とハイフンで入れてください)."]},
    {"no": "2.6", "ja": "土日祝を営業日", "vi": "Thứ Bảy, Chủ nhật, ngày lễ là ngày làm việc", "sel": "-", "kind": "label", "trig": "view", "detail": ["【任意】はい／いいえ（新規の既定：いいえ）。", "[Tùy chọn] Có／không (mặc định khi mới: không)."]},
    {"no": "2.7", "ja": "発注方法", "vi": "Phương thức đặt hàng", "sel": "-", "kind": "label", "trig": "view", "detail": ["【任意】ESステーション／メール／外部（新規の既定：ESステーション）。", "[Tùy chọn] ESステーション／email／bên ngoài (mặc định khi mới: ESステーション)."]},
    {"no": "2.8", "ja": "ステータス", "vi": "Trạng thái", "sel": "-", "kind": "label", "trig": "view", "detail": ["【読取専用】書いても無視（新規は未発行）。", "[Chỉ đọc] Có ghi cũng bị bỏ qua (khi mới là chưa cấp)."]},
    {"no": "2.9", "ja": "アカウントの状態", "vi": "Trạng thái tài khoản", "sel": "-", "kind": "label", "trig": "view", "detail": ["【読取専用】書いても無視（未取得は「未発行」）。", "[Chỉ đọc] Có ghi cũng bị bỏ qua (nếu chưa lấy được thì là 「未発行」)."]},
]

I5 = [
    {"no": "1", "ja": "ヘッダー", "vi": "Header", "sel": "-", "kind": "area", "trig": "view", "detail": ["パンくず：マスタ管理 ＞ 仕入先 ＞ 仕入先詳細。タイトル「仕入先詳細 ID」。右に「削除」「パスワード送信」「編集」（権限のある役割だけ。削除済の仕入先には出さない）。", "Breadcrumb: Quản lý master ＞ Nhà cung cấp ＞ Chi tiết nhà cung cấp. Tiêu đề 「仕入先詳細 ID」. Bên phải có 「削除」「パスワード送信」「編集」 (chỉ vai trò có quyền; không hiển thị với nhà cung cấp đã xóa)."]},
    {"no": "1.1", "ja": "削除", "vi": "Xóa", "sel": "-", "kind": "button", "trig": "click", "pattern": "P-DEL", "err": ["Q01", "S02", "E30"], "detail": ["削除の確認（Q01）→ 論理削除（P-DEL）。使用中は削除できない。削除すると、この仕入先のアカウントはログインできなくなる。", "Xác nhận xóa (Q01) → xóa logic (P-DEL). Đang sử dụng thì không xóa được. Sau khi xóa, tài khoản của nhà cung cấp này không đăng nhập được."]},
    {"no": "1.2", "ja": "パスワード送信", "vi": "Gửi mật khẩu", "sel": "-", "kind": "button", "trig": "click", "err": ["Q173", "S173", "E30"], "cond": ["アカウントが有効（または発行済・ログイン前）のとき", "Khi tài khoản có hiệu lực (hoặc đã cấp・chưa đăng nhập)"], "detail": ["メイン担当者のメールアドレスへ、パスワード設定のご案内を送る（仕入先・委託配送先は Mail List No.30。配送スタッフはドライバーアプリの再設定と同じ認証コード＝No.3）。押すと確認（Q173）→ 送ったら S173。アカウントが「未発行」「無効」「削除済」のときは押せない。", "Gửi hướng dẫn đặt mật khẩu tới email người phụ trách chính (nhà cung cấp・đơn vị vận chuyển ủy thác dùng Mail List No.30; nhân viên giao hàng dùng mã xác thực giống đặt lại mật khẩu trên app tài xế = No.3). Nhấn thì hiện xác nhận (Q173) → gửi xong hiện S173. Không nhấn được khi tài khoản là 「未発行」「無効」「削除済」."]},
    {"no": "1.3", "ja": "編集", "vi": "Sửa", "sel": "-", "kind": "button", "trig": "click", "detail": ["登録・編集の画面（編集）へ。編集の権限がない役割には出さない。", "Chuyển sang màn hình đăng ký・sửa (sửa). Không hiển thị với vai trò không có quyền sửa."]},
    {"no": "2", "ja": "タブ", "vi": "Tab", "sel": "-", "kind": "tab", "trig": "click", "pattern": "P-TAB", "detail": ["タブ：基本情報・変更履歴。初期は「基本情報」。", "Tab: Thông tin cơ bản・Lịch sử thay đổi. Mặc định là 「基本情報」."]},
    {"no": "3", "ja": "基本情報（表示）", "vi": "Thông tin cơ bản (hiển thị)", "sel": "-", "kind": "area", "trig": "view", "detail": ["仕入先ID・仕入先名・カナ・ステータス・作れる商品（チップ）・仕入れ先区分・土日祝を営業日・発注方法・備考。すべて表示だけ。", "ID nhà cung cấp・tên nhà cung cấp・kana・trạng thái・sản phẩm có thể làm (chip)・phân loại nhà cung cấp・ngày làm việc thứ 7/CN/lễ・phương thức đặt hàng・ghi chú. Tất cả chỉ hiển thị."]},
    {"no": "4", "ja": "住所（表示）", "vi": "Địa chỉ (hiển thị)", "sel": "-", "kind": "area", "trig": "view", "detail": ["本社・製造場所の行（区分・郵便番号・都道府県・市区町村・町域・番地・建物・部屋番号・電話番号・Fax番号）。", "Các dòng trụ sở chính・nơi sản xuất (phân loại・mã bưu điện・tỉnh/thành・quận/huyện・phường/xã・số nhà・tòa nhà・số phòng・số điện thoại・số Fax)."]},
    {"no": "5", "ja": "担当者（表示）", "vi": "Người phụ trách (hiển thị)", "sel": "-", "kind": "area", "trig": "view", "detail": ["メイン担当者・サブ担当者の行（区分・担当者名・フリガナ・メールアドレス・TEL）。", "Các dòng người phụ trách chính・phụ (phân loại・tên người phụ trách・furigana・email・TEL)."]},
    {"no": "6", "ja": "申込の内容（表示）", "vi": "Nội dung đơn (hiển thị)", "sel": "-", "kind": "area", "trig": "view", "detail": ["申込から登録した仕入先だけ。受付番号・申込日時・代表者・許可・認証・取扱・得意分野・申込時のメモ。表示だけ（変えるのは仕入先Web の申込フォーム。承認したあとは運営の編集で直す）。", "Chỉ với nhà cung cấp được đăng ký từ đơn. Số tiếp nhận・ngày giờ đăng ký・người đại diện・giấy phép・chứng nhận・ngành kinh doanh・sở trường・ghi chú khi đăng ký. Chỉ hiển thị (nội dung thay đổi ở form đăng ký của Web nhà cung cấp; sau khi duyệt thì sửa bằng chức năng sửa của bộ phận vận hành)."]},
    {"no": "7", "ja": "アカウントの状態", "vi": "Trạng thái tài khoản", "sel": "-", "kind": "area", "trig": "view", "detail": ["アカウントの状態（未発行・有効・無効・削除済）。状態が「無効」「削除済」のときはログインできない。", "Trạng thái tài khoản (chưa cấp・có hiệu lực・vô hiệu・đã xóa). Khi trạng thái là 「無効」「削除済」 thì không đăng nhập được."]},
]

I6 = [
    {"no": "1", "ja": "登録・編集の画面", "vi": "Màn hình đăng ký・sửa", "sel": "-", "kind": "area", "trig": "view", "pattern": "P-FORM", "err": ["Q02", "S01", "E30", "E31"], "detail": ["タイトル「仕入先の登録」「仕入先の編集」。一覧の「新規登録」と、詳細の「編集」（一覧の鉛筆）から開く。タブは置かない（詳細だけ）。保存は画面の 登録／保存 の1つだけ。入力を変えてキャンセルしたら Q02。成功したら S01 を出して詳細へ戻る（新規は登録した ID の詳細）。", "Tiêu đề 「仕入先の登録」「仕入先の編集」. Mở từ 「新規登録」 ở danh sách và 「編集」 ở chi tiết (biểu tượng bút chì ở danh sách). Không đặt tab (chỉ có ở chi tiết). Lưu chỉ bằng 1 nút trên màn hình: Đăng ký / Lưu. Nếu đã thay đổi nhập liệu rồi hủy thì hiện Q02. Thành công thì hiện S01 và quay về chi tiết (đăng ký mới thì về chi tiết của ID vừa đăng ký)."]},
    {"no": "2", "ja": "基本情報", "vi": "Thông tin cơ bản", "sel": "-", "kind": "area", "trig": "view", "detail": ["基本情報のカード。", "Thẻ thông tin cơ bản."]},
    {"no": "2.1", "ja": "仕入先ID", "vi": "ID nhà cung cấp", "sel": "-", "kind": "label", "trig": "view", "detail": ["SP＋5桁（システムが採番）。登録のときは表示しない。", "SP + 5 chữ số (hệ thống tự cấp số). Không hiển thị khi đăng ký."]},
    {"no": "2.2", "ja": "仕入先名", "vi": "Tên nhà cung cấp", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E04"], "req": "○", "len": "文字列 60", "ex": ["株式会社エービーシー食品", "Ví dụ của mục 'Tên nhà cung cấp': tên công ty (dạng 'công ty cổ phần + tên')."], "detail": ["仕入先の名前。", "Tên của nhà cung cấp."]},
    {"no": "2.3", "ja": "カナ", "vi": "Kana", "sel": "-", "kind": "text", "trig": "input", "err": ["E03", "E04"], "req": "－", "len": "文字列 60", "ex": ["カブシキガイシャエービーシーショクヒン", "Kabushiki Gaisha ABC Shokuhin"], "detail": ["全角カタカナ。", "Katakana toàn chiều rộng."]},
    {"no": "2.4", "ja": "ステータス", "vi": "Trạng thái", "sel": "-", "kind": "select", "trig": "select", "open": ["仕入先の状態に「無効」を足すか（無効＝ログイン不可・新規発注なし。参考画面のステータスは「有効」）", "hong"], "err": ["E01"], "req": "○", "len": ["選択（本登録／未発行）", "Chọn (đăng ký chính thức / chưa cấp)"], "ex": ["本登録", "Đăng ký chính thức"], "detail": ["新規は「未発行」。申込中・却下は申込の確認で処理する（ここでは選べない）。「本登録」「未発行」以外にする「無効」を足すかは open。", "Đăng ký mới mặc định là 「未発行」. Đang đăng ký・từ chối được xử lý ở màn hình xác nhận đơn (không chọn được ở đây). Có thêm trạng thái 「無効」 ngoài 「本登録」「未発行」 hay không là open."]},
    {"no": "2.5", "ja": "作れる商品", "vi": "Sản phẩm có thể làm", "sel": "-", "kind": "check", "trig": "check", "err": ["E02"], "req": "○", "len": ["選択（複数：冷蔵・冷凍・資材 など）", "Chọn (nhiều: lạnh, đông, vật tư…)"], "ex": ["冷蔵・冷凍", "Lạnh・đông lạnh"], "detail": ["仕入先が作れる商品の区分。複数選べる（チップで表示）。1つ以上必須。", "Phân loại sản phẩm mà nhà cung cấp có thể làm. Chọn được nhiều (hiển thị dạng chip). Bắt buộc từ 1 mục trở lên."]},
    {"no": "2.6", "ja": "仕入れ先区分", "vi": "Phân loại nhà cung cấp", "sel": "-", "kind": "select", "trig": "select", "err": ["E01"], "req": "○", "len": ["選択（通常商品／短消費期限商品／資材）", "Chọn (hàng thường / hàng hạn dùng ngắn / vật tư)"], "ex": ["通常商品", "Loại hàng chính nhà cung cấp xử lý (hàng thường)"], "detail": ["主に扱う区分。仕入先Web の申込フォームと同じ固定の3つ。", "Phân loại chủ yếu xử lý. 3 giá trị cố định, giống form đăng ký của Web nhà cung cấp."]},
    {"no": "2.7", "ja": "土日祝を営業日", "vi": "Thứ Bảy, Chủ nhật, ngày lễ là ngày làm việc", "sel": "-", "kind": "select", "trig": "select", "err": ["E01"], "req": "○", "len": ["選択（はい／いいえ）", "Chọn (có / không)"], "ex": ["いいえ", "Ví dụ của mục 'Thứ Bảy・Chủ Nhật・ngày lễ là ngày làm việc': giá trị chọn có/không, ở đây là 「いいえ」 (không)."], "detail": ["新規の既定は「いいえ」。参考画面にはないが、既存の項目なので残す。", "Mặc định khi đăng ký mới là 「いいえ」. Không có trong màn hình tham khảo nhưng là mục đã có nên giữ lại."]},
    {"no": "2.8", "ja": "発注方法", "vi": "Phương thức đặt hàng", "sel": "-", "kind": "select", "trig": "select", "err": ["E01"], "req": "○", "len": ["選択（ESステーション／メール／外部）", "Chọn (ES station / email / bên ngoài)"], "ex": ["ESステーション", "Ví dụ của mục 'Phương thức đặt hàng': giá trị chọn phương thức đặt hàng, ở đây là 「ESステーション」 (đặt hàng qua ES STATION)."], "detail": ["新規の既定は「ESステーション」。申込を承認したあと、ここで決める。参考画面にはないが、既存の項目なので残す。", "Mặc định khi đăng ký mới là 「ESステーション」. Quyết định tại đây sau khi duyệt đơn. Không có trong màn hình tham khảo nhưng là mục đã có nên giữ lại."]},
    {"no": "2.9", "ja": "備考", "vi": "Ghi chú", "sel": "-", "kind": "textarea", "trig": "input", "err": ["E04"], "req": "－", "len": "文字列 500", "ex": ["納品は午前のみ", "Chỉ giao hàng buổi sáng"], "detail": ["運営だけが見るメモ。複数行。", "Ghi chú chỉ bộ phận vận hành xem. Nhiều dòng."]},
    {"no": "3", "ja": "住所", "vi": "Địa chỉ", "sel": "-", "kind": "area", "trig": "view", "detail": ["住所を表で入れる。「本社」はちょうど1行（必須）、「製造場所」は0行以上（行を追加・削除）。", "Nhập địa chỉ dạng bảng. 「本社」 đúng 1 dòng (bắt buộc), 「製造場所」 từ 0 dòng trở lên (thêm・xóa dòng)."]},
    {"no": "3.1", "ja": "区分", "vi": "Phân loại", "sel": "-", "kind": "select", "trig": "select", "err": ["E01"], "req": "○", "len": ["選択（本社／製造場所）", "Chọn (trụ sở / nơi sản xuất)"], "ex": ["本社", "Trụ sở chính"], "detail": ["本社は1行だけ。", "Trụ sở chính chỉ có 1 dòng."]},
    {"no": "3.2", "ja": "郵便番号", "vi": "Mã bưu chính", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E05"], "req": "○", "len": "文字列 8", "ex": ["105-0011", "Ví dụ của mục 'Mã bưu điện': mã bưu điện 7 chữ số của Nhật, có dạng 3-4 chữ số cách nhau bằng gạch nối."], "detail": ["数字7桁。ハイフンは任意（保存は 123-4567）。", "7 chữ số. Dấu gạch nối là tùy chọn (khi lưu sẽ ở dạng 123-4567)."]},
    {"no": "3.3", "ja": "都道府県", "vi": "Tỉnh thành", "sel": "-", "kind": "select", "trig": "select", "err": ["E01"], "req": "○", "len": ["選択（47都道府県）", "Chọn (47 tỉnh)"], "ex": ["東京都", "Ví dụ của mục 'Tỉnh/thành phố (todofuken)': tên tỉnh/thành của Nhật (ở đây là một thành phố trực thuộc trung ương)."], "detail": ["", ""]},
    {"no": "3.4", "ja": "市区町村", "vi": "Quận huyện thành phố", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E04"], "req": "○", "len": "文字列 255", "ex": ["港区", "Ví dụ của mục 'Quận/huyện/thành phố': tên quận, thành phố hoặc thị trấn thuộc tỉnh/thành đã chọn."], "detail": ["", ""]},
    {"no": "3.5", "ja": "町域・番地", "vi": "Phường/xã・số nhà", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E04"], "req": "○", "len": "文字列 255", "ex": ["芝公園1-2-3", "Shibakoen 1-2-3"], "detail": ["", ""]},
    {"no": "3.6", "ja": "建物・部屋番号", "vi": "Tòa nhà・số phòng", "sel": "-", "kind": "text", "trig": "input", "err": ["E04"], "req": "－", "len": "文字列 255", "ex": ["〇〇ビル5F", "Tòa nhà XX tầng 5"], "detail": ["", ""]},
    {"no": "3.7", "ja": "電話番号", "vi": "Số điện thoại", "sel": "-", "kind": "text", "trig": "input", "err": ["E06"], "req": "－", "len": "文字列 20", "ex": ["03-1234-5678", "Ví dụ của mục 'Số điện thoại': số điện thoại cố định của Nhật, gồm chữ số và dấu gạch nối (mã vùng-số)."], "detail": ["数字とハイフン。", "Chữ số và dấu gạch nối."]},
    {"no": "3.8", "ja": "Fax番号", "vi": "Số Fax", "sel": "-", "kind": "text", "trig": "input", "err": ["E06"], "req": "－", "len": "文字列 20", "ex": ["03-1234-5679", "03-1234-5679"], "detail": ["数字とハイフン。", "Chữ số và dấu gạch nối."]},
    {"no": "3.9", "ja": "行を追加／行を削除", "vi": "Thêm dòng / Xóa dòng", "sel": "-", "kind": "button", "trig": "click", "detail": ["製造場所の行を足す・消す（本社の行は消せない）。", "Thêm/xóa dòng nơi sản xuất (không xóa được dòng trụ sở chính)."]},
    {"no": "4", "ja": "担当者（表）", "vi": "Người phụ trách (dạng bảng)", "sel": "-", "kind": "area", "trig": "view", "detail": ["担当者を表で入れる。「メイン担当者」はちょうど1行（必須）、「サブ担当者」は0行以上（「行を追加」「行を削除」）。メイン担当者のメールアドレスがログイン案内・パスワード送信の宛先。", "Nhập người phụ trách dạng bảng. 「メイン担当者」 đúng 1 dòng (bắt buộc), 「サブ担当者」 từ 0 dòng trở lên (「行を追加」「行を削除」). Email của người phụ trách chính là địa chỉ nhận hướng dẫn đăng nhập và gửi mật khẩu."]},
    {"no": "4.1", "ja": "区分", "vi": "Phân loại", "sel": "-", "kind": "select", "trig": "select", "err": ["E01"], "req": "○", "len": ["選択（メイン担当者／サブ担当者）", "Chọn (người phụ trách chính / phụ)"], "ex": ["メイン担当者", "Người phụ trách chính"], "detail": ["メイン担当者は1行だけ。2行目からはサブ担当者。", "Người phụ trách chính chỉ có 1 dòng. Từ dòng thứ 2 là người phụ trách phụ."]},
    {"no": "4.2", "ja": "担当者名", "vi": "Tên người phụ trách", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E04"], "req": "○", "len": "文字列 60", "ex": ["担当 太郎", "Tanto Taro"], "detail": ["担当者の名前。", "Tên của người phụ trách."]},
    {"no": "4.3", "ja": "フリガナ", "vi": "Furigana", "sel": "-", "kind": "text", "trig": "input", "err": ["E03", "E04"], "req": "－", "len": "文字列 60", "ex": ["タントウ タロウ", "Tantou Tarou"], "detail": ["全角カタカナ。", "Katakana toàn chiều rộng."]},
    {"no": "4.4", "ja": "メールアドレス", "vi": "Địa chỉ email", "sel": "-", "kind": "text", "trig": "input", "err": ["E01", "E07"], "req": "○", "len": "文字列 160", "ex": ["sample@example.jp", "sample@example.jp"], "detail": ["メール形式。メイン担当者のメールがアカウント案内の宛先。", "Định dạng email. Email của người phụ trách chính là địa chỉ nhận thông báo tài khoản."]},
    {"no": "4.5", "ja": "TEL", "vi": "TEL", "sel": "-", "kind": "text", "trig": "input", "err": ["E06"], "req": "－", "len": "文字列 20", "ex": ["012-345-6789", "012-345-6789"], "detail": ["数字とハイフン。", "Chữ số và dấu gạch nối."]},
    {"no": "4.6", "ja": "行を追加／行を削除", "vi": "Thêm dòng / Xóa dòng", "sel": "-", "kind": "button", "trig": "click", "detail": ["サブ担当者の行を足す・消す（メイン担当者の行は消せない）。", "Thêm/xóa dòng người phụ trách phụ (không xóa được dòng người phụ trách chính)."]},
    {"no": "5", "ja": "キャンセル", "vi": "Hủy bỏ", "sel": "-", "kind": "button", "trig": "click", "err": ["Q02"], "detail": ["一覧へ戻る（編集のときは詳細へ）。入力を変えていたら Q02（キャンセル／破棄）。", "Quay về danh sách (khi đang sửa thì quay về chi tiết). Nếu đã thay đổi nội dung nhập thì hiển thị Q02 (Hủy / Bỏ thay đổi)."]},
    {"no": "6", "ja": "登録・保存", "vi": "Đăng ký・Lưu", "sel": "-", "kind": "button", "trig": "click", "err": ["S01", "E30", "E31"], "detail": ["押すとまとめてチェック（項目の下にエラー・赤枠。保存ボタンの横に「保存できません（n件）」）。エラーがなければ保存して S01。ボタンは押したら無効にする。ほかの人が先に保存していたら E31（P-FORM）。", "Khi bấm sẽ kiểm tra toàn bộ cùng lúc (lỗi và viền đỏ bên dưới từng mục; bên cạnh nút lưu hiển thị 「保存できません（n件）」). Nếu không có lỗi thì lưu và hiển thị S01. Nút bị vô hiệu hóa sau khi bấm. Nếu người khác đã lưu trước thì hiển thị E31 (P-FORM)."]},
]

I7 = [
    {"no": "1", "ja": "削除の確認", "vi": "Xác nhận xóa", "sel": ".modal", "kind": "modal", "trig": "click", "pattern": "P-DEL", "err": ["Q01", "S02", "E30"], "detail": ["タイトル「削除」。「キャンセル」「削除する」。「削除する」で論理削除（状態＝削除済）して S02。一覧から外れ、検索条件で「削除済」を選ぶと表示される。削除すると、この仕入先のアカウントはログインできなくなる。", "Tiêu đề 「削除」. Có 「キャンセル」「削除する」. Khi nhấn 「削除する」 thì xóa logic (trạng thái = đã xóa) và hiện S02. Bị loại khỏi danh sách; chọn 「削除済」 ở điều kiện tìm kiếm thì sẽ hiển thị. Khi xóa, tài khoản của nhà cung cấp này không thể đăng nhập."]},
]

I8 = [
    {"no": "1", "ja": "削除できない", "vi": "Không thể xóa", "sel": ".ov .mbox", "kind": "modal", "trig": "click", "err": ["E241"], "detail": ["進行中の発注が n件あるとき（E241）は削除できない。モーダルの「閉じる」で閉じる。条件は hong 確認済み（2026-10-06）。", "Khi còn n đơn đặt hàng đang xử lý (E241) thì không xóa được. Đóng modal bằng 「閉じる」. Điều kiện đã được hong xác nhận (2026-10-06)."]},
]

I9 = [
    {"no": "1", "ja": "タブ", "vi": "Tab", "sel": "-", "kind": "tab", "trig": "click", "pattern": "P-TAB", "detail": ["詳細の上のタブ。「基本情報」「変更履歴」。初期は「基本情報」。", "Tab phía trên chi tiết. 「基本情報」「変更履歴」. Mặc định là 「基本情報」."]},
    {"no": "2", "ja": "変更履歴の表", "vi": "Bảng lịch sử thay đổi", "sel": "-", "kind": "table", "trig": "view", "pattern": "P-HIST", "err": ["I01"], "detail": ["列：変更日時・変更内容・変更者。新しい順。1ページ 10件。0件は I01。履歴に「影響した拠点数」「バージョン」は持たない（P-HIST）。変更者＝運営のアカウント名／「CSV取込」／仕入先（プロフィールの変更）。表示だけ（直せない）。", "Cột: ngày giờ thay đổi・nội dung thay đổi・người thay đổi. Mới nhất trước. 10 dòng mỗi trang. 0 bản ghi hiện I01. Lịch sử không có 「影響した拠点数」「バージョン」 (P-HIST). Người thay đổi = tên tài khoản vận hành / 「CSV取込」 / nhà cung cấp (thay đổi hồ sơ). Chỉ hiển thị (không sửa được)."]},
]

I10 = [
    {"no": "1", "ja": "申込の内容（承認・却下の画面）", "vi": "Nội dung đơn (màn hình duyệt・từ chối)", "sel": ".ov .mbox", "kind": "modal", "trig": "click", "err": ["S170", "S171", "E30"], "detail": ["1件の申込の内容。申込の表（AW_SUPP_002）の「内容を見る」から開く。仕入先Web の申込フォームに入れた項目を**全部**表示する（表示だけ）。", "Nội dung của 1 đơn đăng ký. Mở từ 「内容を見る」 ở bảng đơn (AW_SUPP_002). Hiển thị **toàn bộ** mục đã nhập ở form đăng ký của Web nhà cung cấp (chỉ hiển thị)."]},
    {"no": "1.1", "ja": "申込の項目（表示）", "vi": "Các mục của đơn (hiển thị)", "sel": "-", "kind": "label", "trig": "view", "detail": ["受付番号・申込日時／会社名・会社名カナ／郵便番号・本社住所／代表電話／代表者／担当者名・担当者カナ・担当者メール・担当者の電話番号／土日祝を営業日／仕入れ先区分／作れる商品（複数）／許可・認証／取扱・得意分野／申込時のメモ（空は「—」）。", "Số tiếp nhận・ngày giờ đăng ký / tên công ty・kana tên công ty / mã bưu điện・địa chỉ trụ sở / điện thoại đại diện / người đại diện / tên người phụ trách・kana・email・số điện thoại người phụ trách / ngày làm việc thứ 7/CN/lễ / phân loại nhà cung cấp / sản phẩm có thể làm (nhiều) / giấy phép・chứng nhận / ngành kinh doanh・sở trường / ghi chú khi đăng ký (trống hiển thị 「—」)."]},
    {"no": "1.2", "ja": "却下する", "vi": "Từ chối", "sel": "-", "kind": "button", "trig": "click", "cond": ["承認（approve）の権限がある役割で、状態が「申込中」のとき", "Vai trò có quyền phê duyệt (approve), khi trạng thái là 「申込中」"], "err": ["S171"], "detail": ["押すと却下の理由を入れる画面（AW_SUPP_003）。", "Nhấn để mở màn hình nhập lý do từ chối (AW_SUPP_003)."]},
    {"no": "1.3", "ja": "承認してアカウントを発行", "vi": "Duyệt và cấp tài khoản", "sel": "-", "kind": "button", "trig": "click", "err": ["S170", "E30"], "cond": ["承認（approve）の権限がある役割で、状態が「申込中」のとき", "Vai trò có quyền phê duyệt (approve), khi trạng thái là 「申込中」"], "detail": ["押すと状態を「本登録」にし、アカウント（ログインID＝仕入先ID）を発行して、担当者にメールで知らせる（Mail List No.26）。成功 S170。", "Nhấn để chuyển trạng thái sang 「本登録」, cấp tài khoản (ID đăng nhập = ID nhà cung cấp) và thông báo cho người phụ trách qua email (Mail List No.26). Thành công hiện S170."]},
    {"no": "1.4", "ja": "一覧へ戻る", "vi": "Quay về danh sách", "sel": "-", "kind": "button", "trig": "click", "detail": ["申込の表（AW_SUPP_002）へ戻る。", "Quay về bảng đơn đăng ký (AW_SUPP_002)."]},
]

I11 = [
    {"no": "1", "ja": "0件の表示", "vi": "Hiển thị 0 bản ghi", "sel": ".tbl, .empty", "kind": "area", "trig": "view", "pattern": "P-LIST", "err": ["I01"], "detail": ["検索条件に合う仕入先がないとき、一覧の中に I01「表示するデータがありません。」を出す（P-LIST）。ページ送りは出さない。条件は「クリア」で戻せる。", "Khi không có nhà cung cấp nào khớp điều kiện tìm kiếm, hiển thị I01「表示するデータがありません。」trong danh sách (P-LIST). Không hiển thị phân trang. Có thể khôi phục điều kiện bằng 「クリア」."]},
]

I12 = [
    {"no": "1", "ja": "参照のみ（権限が閲覧だけの役割）", "vi": "Chỉ xem (vai trò chỉ có quyền xem)", "sel": ".ph", "kind": "area", "trig": "view", "cond": ["経理（仕入先は閲覧のみ）", "Kế toán (「経理」) (nhà cung cấp chỉ được xem)"], "detail": ["経理（仕入先は閲覧のみ）。「新規登録」「CSV取込」「アカウント一括発行」は出さない。CSV出力は出す（P-LIST・権限表）。", "Kế toán (「経理」) (nhà cung cấp chỉ được xem). Không hiển thị 「新規登録」「CSV取込」「アカウント一括発行」. Vẫn hiển thị xuất CSV (P-LIST・bảng quyền)."]},
    {"no": "2", "ja": "一覧の操作の列", "vi": "Cột thao tác của danh sách", "sel": ".tbl", "kind": "table", "trig": "view", "detail": ["行の鉛筆（編集）・ごみ箱（削除）・「契約の一括変更」は出さない。名前のリンクで詳細は開ける（詳細も「編集」「削除」を出さない）。", "Không hiển thị biểu tượng bút chì (sửa), thùng rác (xóa) ở từng dòng và 「契約の一括変更」. Vẫn mở được chi tiết bằng liên kết tên (trong chi tiết cũng không hiển thị 「編集」「削除」)."]},
]

I13 = [
    {"no": "1", "ja": "必須の入力エラー", "vi": "Lỗi nhập bắt buộc", "sel": ".emsg", "kind": "label", "trig": "view", "pattern": "P-FORM", "err": ["E01", "E04"], "detail": ["何も入れずに「登録」を押すと、必須の項目の下に E01 を出して赤枠にする（保存しない）。形式・文字数のエラーも同じ並びで項目の下に出す。最初のエラーの項目へスクロールする。保存ボタンの横に「保存できません（n件）」を出す。", "Nếu bấm 「登録」 khi chưa nhập gì, hiển thị E01 bên dưới các mục bắt buộc và tô viền đỏ (không lưu). Lỗi về định dạng・số ký tự cũng hiển thị bên dưới từng mục theo cùng thứ tự. Cuộn đến mục lỗi đầu tiên. Bên cạnh nút lưu hiển thị 「保存できません（n件）」."]},
]

I14 = [
    {"no": "1", "ja": "取り込みの手順（ステップ）", "vi": "Các bước nhập (bước)", "sel": ".steps", "kind": "area", "trig": "view", "pattern": "P-CSV", "detail": ["上に ①ファイルを選ぶ ②確認・登録 の2ステップ。いまは ② 。「ファイルを選び直す」で ① へ戻る（取り込んだ内容は捨てる）。", "Phía trên có 2 bước: ① Chọn file ② Xác nhận・đăng ký. Hiện đang ở bước ②. Nhấn 「ファイルを選び直す」 để quay lại ① (bỏ nội dung đã nhập)."]},
    {"no": "2", "ja": "ファイル名・件数", "vi": "Tên file・số bản ghi", "sel": ".badge", "kind": "label", "trig": "view", "detail": ["ファイル名と全体の件数。バッジで 新規／更新／変更なし／エラー の件数を出す。", "Tên file và tổng số bản ghi. Badge hiển thị số lượng Mới / Cập nhật / Không đổi / Lỗi."]},
    {"no": "3", "ja": "エラーの行（通知と表）", "vi": "Dòng lỗi (thông báo và bảng)", "sel": ".notice.ng", "kind": "area", "trig": "view", "err": ["E34"], "detail": ["エラーの行がある間は赤の通知「エラーの行 n件は取り込みません（行番号と内容は下の表）。ほかの行は「登録」で登録します。」と、エラー一覧（行番号・キー・列名・内容）を出す。エラー一覧は CSV でも出せる（「エラー一覧CSV」）。エラーの行は取り込まない（hong 2026/10/05）。", "Khi còn dòng lỗi, hiển thị thông báo đỏ 「エラーの行 n件は取り込みません（行番号と内容は下の表）。ほかの行は「登録」で登録します。」 và danh sách lỗi (số dòng・khóa・tên cột・nội dung). Danh sách lỗi cũng xuất được ra CSV (「エラー一覧CSV」). Dòng lỗi không được nhập (hong 2026/10/05)."]},
    {"no": "4", "ja": "登録する内容（前 → 後）", "vi": "Nội dung sẽ đăng ký (trước → sau)", "sel": ".tbl", "kind": "table", "trig": "view", "pattern": "P-LIST", "detail": ["列：行番号・区分（新規／更新）・キー・名前・変わる項目（前 → 後）。変わらない行は出さない。1ページ 10件。", "Cột: số dòng・phân loại (mới/cập nhật)・khóa・tên・mục thay đổi (trước → sau). Dòng không thay đổi thì không hiển thị. 10 dòng mỗi trang."]},
    {"no": "5", "ja": "登録", "vi": "Đăng ký", "sel": ".btn.pri.lg", "kind": "button", "trig": "click", "err": ["S03", "E34"], "cond": ["取り込めるデータが1行以上あるとき", "Khi có từ 1 dòng dữ liệu nhập được trở lên"], "detail": ["エラー以外の行を登録する。成功したら S03「n件を登録しました」を出して一覧へ。登録できる行が0件のときは押せない。取り込むとき変更履歴に「CSV取込」の名前で残る。", "Đăng ký các dòng không lỗi. Thành công thì hiện S03 「n件を登録しました」 và chuyển về danh sách. Không nhấn được khi số dòng có thể đăng ký là 0. Khi nhập, lịch sử thay đổi ghi lại với tên 「CSV取込」."]},
    {"no": "6", "ja": "ファイルを選び直す", "vi": "Chọn lại file", "sel": ".btn.out", "kind": "button", "trig": "click", "detail": ["① へ戻る。", "Quay lại ①."]},
]

VIEWS = [
    V("001", "AW_SUPP_001", "初期表示", "Hiển thị ban đầu", "/ops/masters/suppliers", I1),
    V("002", "AW_SUPP_002", "申込の確認（モーダル）", "Xác nhận đơn đăng ký (modal)", "/ops/masters/suppliers", I2, setup="clickText('button','申込を確認する'); await sleep(500);"),
    V("003", "AW_SUPP_003", "申込の却下（モーダル）", "Từ chối đơn đăng ký (modal)", "/ops/masters/suppliers", I3, setup="clickText('button','申込を確認する'); await sleep(500); clickText('.mbox button','内容を見る'); await sleep(700); clickText('.mbox button','却下する'); await sleep(500);"),
    V("004", "AW_SUPP_004", "初期表示（ステップ1 ファイルを選ぶ）", "Hiển thị ban đầu (Bước 1 Chọn tệp)", "/ops/masters/suppliers/import", I4),
    V("005", "AW_SUPP_005", "詳細", "Chi tiết", "/ops/masters/suppliers/SP00001", I5),
    V("006", "AW_SUPP_006", "登録・編集", "Đăng ký・sửa", "/ops/masters/suppliers/new", I6),
    V("007", "AW_SUPP_001", "削除の確認", "Xác nhận xóa", "/ops/masters/suppliers", I7, setup="document.querySelector('.tbl tbody tr .act button:last-child')?.click(); await sleep(300);"),
    V("008", "AW_SUPP_001", "削除できない（進行中の発注あり）", "Không thể xóa (có đơn đặt hàng đang tiến hành)", "/ops/masters/suppliers", I8, setup="document.querySelector('.tbl tbody tr .act button:last-child')?.click(); await sleep(300); [...document.querySelectorAll('.modal button')].find(b=>(b.textContent||'').includes('削除する'))?.click(); await sleep(500);"),
    V("012", "AW_SUPP_005", "詳細（変更履歴のタブ）", "Chi tiết (tab lịch sử thay đổi)", "/ops/masters/suppliers/SP00001?tab=hist", I9),
    V("013", "AW_SUPP_007", "申込の内容（承認・却下）", "Nội dung đơn (duyệt・từ chối)", "/ops/masters/suppliers", I10, setup="clickText('button','申込を確認する'); await sleep(500); clickText('.mbox button','内容を見る'); await sleep(700);"),
    V("009", "AW_SUPP_001", "0件（検索結果なし）", "0 bản ghi (không có kết quả tìm kiếm)", "/ops/masters/suppliers", I11, setup="const kw=document.querySelector('.es-search input'); if(kw){Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(kw,'zzzzzz'); kw.dispatchEvent(new Event('input',{bubbles:true})); await sleep(200); clickText('button','検索'); await sleep(600);}"),
    V("010", "AW_SUPP_001", "参照のみ（閲覧の権限だけ）", "Chỉ xem (chỉ có quyền xem)", "/ops/masters/suppliers", I12, login="Ad00012"),
    V("011", "AW_SUPP_006", "入力エラー", "Lỗi nhập", "/ops/masters/suppliers/new", I13, setup="clickText('.ph button','登録'); await sleep(500);"),
    V("014", "AW_SUPP_004", "確認・登録（ステップ2）", "Xác nhận・đăng ký (bước 2)", "/ops/masters/suppliers/import", I14, setup="const res=await fetch('/api/domain/csv/export',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','x-es-site':'ops'},body:JSON.stringify({args:{entity:'suppliers',scope:{site:'ops'}}})});const t=await res.json();const esc=v=>'\"'+String(v??'').replace(/\"/g,'\"\"')+'\"';const rows=[t.head,...t.rows];const r0=t.rows[0];const ni=t.head.findIndex(h=>/仕入先名/.test(h));if(ni>=0)r0[ni]=r0[ni]+' X';const bad=t.rows[0].slice();bad[0]='XX999999';rows.push(bad);const text='\\ufeff'+rows.map(r=>r.map(esc).join(',')).join('\\r\\n');const inp=document.querySelector('input[type=file]');const dt=new DataTransfer();dt.items.add(new File([text],'取込テスト.csv',{type:'text/csv'}));inp.files=dt.files;inp.dispatchEvent(new Event('change',{bubbles:true}));await sleep(2500);", note=["ファイルを選んだ直後。見本は今のデータの CSV出力に、1行目の仕入先名を変えた（更新の見本）と、キーが誤りの行を1つ足したもの（エラーの行の見本）。", "Ngay sau khi chọn file. File mẫu là CSV xuất từ dữ liệu hiện tại, đổi tên nhà cung cấp ở dòng 1 (mẫu cập nhật) và thêm 1 dòng có khóa sai (mẫu dòng lỗi)."]),
]
