# -*- coding: utf-8 -*-
"""
法人Web 棚卸報告（CW_STOCK）の画面設計書データ。元：本物の Web（app/corp/stock/page.tsx・lib/corp/docs/{logic,types,fromDomain}.ts・lib/corp/areas/corp-docs.ts・lib/domain/areas/report.ts）。
決定：docs/決定台帳.md E（2026-10-05：画面名「棚卸報告」・未報告の判定 25日・7列・今回＋過去3か月・数の桁は 台帳 N「数量の桁」＝棚卸数 0〜999,999（UI/UX レビュー #2 で 4桁の切り詰めを直した）・拠点ごとの状況＝拠点ID 昇順・参照のみでも報告できる）。
コードがまだ決定に追いついていないところは demo_ok（受付簿 No.78・73）。
版 1.1（2026-10-05・hong の版 1.0 レビュー、台帳 E「法人Web 版 1.0 のレビュー（棚卸報告・請求書）」①〜⑦）：棚卸一覧（CW_STOCK_002）を分ける・「在庫点検」を使わない・
報告した方の既定＝メイン担当者・棚卸用の表（PDF）・商品を追加（JAN スキャン／商品名）・「大きく増えた」の警告をなくす・確認モーダルを簡単に。コードは 版 1.1 に合わせた（受付簿 No.153 実装済）。
版 1.4（2026-10-05・hong 承認、台帳 E「法人Web 版 1.1 のレビュー 2回目」、受付簿 No.157）：「点検」→「棚卸」の言い方・demo_ok を見本データで置き換え（横浜営業所の 2026-09 未報告・お届け中の追加配送・代替品のお知らせをデータから）・画面状態 026（行のエラー）を追加・読み込めなかったときの表示 E346。
URL：棚卸一覧＝/corp/stock、棚卸報告＝/corp/stock/<拠点ID>/<月度 YYYY-MM>（元：app/corp/stock/page.tsx・app/corp/stock/[site]/[m]/page.tsx）。
"""

TITLE = ["棚卸報告（CW_STOCK）", "Báo cáo kiểm kê (CW_STOCK)"]
SHEET = ["棚卸報告", "Báo cáo kiểm kê"]
BASENAME = "画面設計書_CW_STOCK_棚卸報告"
IMG_PREFIX = "CW_STOCK"
OUT_DIR = "CW_STOCK_棚卸報告"
CODE_NOTE = ["Screen Code は台帳 E 2026-10-05 の決まり：CW_<機能略>_<3桁>", "Screen Code theo 台帳 E 2026-10-05: CW_<機能略>_<3 chữ số>"]
SITE = "corp"
SYSTEM = {"ja": "法人Web", "vi": "Web pháp nhân (法人Web)"}
AUTHOR = "Claude／確認：hong"
CREATED = "2026-10-05"
DEMO_FILE = "http://localhost:3000"
LOGIN = {"site": "corp", "loginId": "CU00001"}

DECISIONS = [
    {"date": "2026-10-05", "target": "CW_STOCK_001 No.3.6・CW_STOCK_002 No.35.3・36.5",
     "q": ["棚卸の状態名「報告済」は「〜済」の書き方に揃えるか", "Có thống nhất tên trạng thái kiểm kê \"報告済\" theo kiểu \"〜済み\" không"],
     "a": ["「報告済」に統一（一覧・報告の画面とも。お届け済み・請求済みと同じ書き方）。「在庫点検」という語はコード・画面に残さない", "Thống nhất \"報告済み\" (cả danh sách và màn báo cáo; cùng kiểu với お届け済み・請求済み). Không để từ \"在庫点検\" trong code / màn hình"],
     "src": "hong 回答 2026-10-05 版1.1レビュー ③（受付簿 No.156・台帳 F）"},
    {"date": "2026-10-05", "target": "CW_STOCK_001 No.1.1",
     "q": ["画面名・メニュー名は「在庫点検」か「棚卸報告」か", "Tên màn hình / menu là \"在庫点検\" hay \"棚卸報告\""],
     "a": ["「棚卸報告」（メニュー名・画面名とも。「在庫点検」は使わない）", "\"棚卸報告\" cho cả menu và tên màn hình (không dùng \"在庫点検\")"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-S1）"},
    {"date": "2026-10-05", "target": "CW_STOCK_001 No.3.5",
     "q": ["未報告（事務手数料 ¥3,000）の判定は 20日か 25日か", "Mốc xác định chưa báo cáo (phí hành chính ¥3,000) là ngày 20 hay 25"],
     "a": ["判定は 25日時点。お客様の入力期限は 20日のまま（21〜25日は運営が代理で追加・修正）", "Xác định tại ngày 25. Hạn nhập của khách vẫn là ngày 20 (21〜25 運営 nhập thay)"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-S2）"},
    {"date": "2026-10-05", "target": "CW_STOCK_001 No.3.11",
     "q": ["棚卸の表の列と、一覧にない商品の追加", "Các cột của bảng kiểm kê và việc thêm sản phẩm ngoài danh sách"],
     "a": ["商品・前回の棚卸・お届け中・廃棄する・今ある数・捨てた数・届いた数の7列。この拠点に関係する商品だけ。法人は一覧にない商品を足せない", "7 cột: 商品・前回の棚卸・お届け中・廃棄する・今ある数・捨てた数・届いた数. Chỉ sản phẩm liên quan đến chi nhánh. Pháp nhân không thêm sản phẩm ngoài danh sách"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-S3）"},
    {"date": "2026-10-05", "target": "CW_STOCK_001 No.3.2",
     "q": ["見られる月の範囲と「拠点ごとの状況」の月", "Số tháng xem được và tháng của \"拠点ごとの状況\""],
     "a": ["今回＋過去3か月。「拠点ごとの状況」も選んだ月に合わせる", "Tháng này + 3 tháng trước. \"拠点ごとの状況\" cũng theo tháng đã chọn"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-S4）"},
    {"date": "2026-10-05", "target": "CW_STOCK_001 No.3.11.5",
     "q": ["在庫の数量の上限", "Giới hạn số lượng tồn kho"],
     "a": ["0〜9999 の整数（4桁）。全角は半角に直す（input_standard に追加）", "Số nguyên 0〜9999 (4 chữ số). Đổi toàn góc sang nửa góc (đã thêm vào input_standard)"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-S5）。2026-10-07 以降は台帳 N「数量の桁」（棚卸数 999,999）が正"},
    {"date": "2026-10-07", "target": "CW_STOCK_001 No.3.11.5〜3.11.7・8.1",
     "q": ["棚卸の数の桁と、入力のエラーの出し方", "Số chữ số của số kiểm kê và cách hiển thị lỗi nhập"],
     "a": ["0〜999,999 の整数（台帳 N「数量の桁」）。超えたら切り詰めず、欄の下に E12。空は欄の下に E01（赤枠・aria-invalid・aria-describedby）。トーストは補助", "Số nguyên 0〜999,999 (台帳 N). Vượt thì không cắt, hiện E12 dưới ô. Để trống hiện E01 dưới ô (viền đỏ, aria-invalid, aria-describedby). Toast chỉ là phụ"],
     "src": "台帳 N「数量の桁」・input_standard「切り詰めない」・UI/UX レビュー（2026-10-07）#2・#3"},
    {"date": "2026-10-05", "target": "CW_STOCK_001 No.2",
     "q": ["「拠点ごとの状況」の初期の並び", "Thứ tự ban đầu của \"拠点ごとの状況\""],
     "a": ["未報告 → 報告済 → 棚卸なし・休止中、その中は拠点ID の昇順（B-20 で変更）", "未報告 → 報告済 → 棚卸なし・休止中, trong nhóm theo 拠点ID (đổi ở B-20)"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-O9）"},
    {"date": "2026-10-05", "target": "CW_STOCK_001 No.3.13",
     "q": ["解約後（参照のみ）のアカウントは棚卸報告できるか", "Tài khoản sau khi hủy hợp đồng (chỉ xem) có báo cáo kiểm kê được không"],
     "a": ["できる（最終請求書の在庫差額のため）。お届け日の変更申請・資材注文・商品注文はできない", "Được (để tính chênh lệch tồn kho cho hóa đơn cuối). Không được đổi ngày giao, đặt vật tư, đặt sản phẩm"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-C2）"},
    {"date": "2026-10-05", "target": "CW_STOCK_001 No.1.3",
     "q": ["CSV出力ボタンを棚卸報告に置くか", "Có đặt nút CSV出力 ở 棚卸報告 không"],
     "a": ["置く（ホーム・棚卸報告・請求書・注文履歴。CSV入出力_定義どおり）", "Có (ホーム・棚卸報告・請求書・注文履歴, theo CSV入出力_定義)"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-C3）"},
    {"date": "2026-10-05", "target": "CW_STOCK_001 全体",
     "q": ["文言の中の「ESキッチン」「ES STATION」の使い分け", "Cách dùng \"ESキッチン\" và \"ES STATION\" trong câu chữ"],
     "a": ["「ESキッチン」＝お客様（運営会社）の名前、「ES STATION」＝システムの名前", "\"ESキッチン\" = tên khách hàng (công ty vận hành), \"ES STATION\" = tên hệ thống"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-C1）"},
    # ---- 版 1.1（hong の版 1.0 レビュー 2026-10-05）
    {"date": "2026-10-05", "target": "CW_STOCK_002 全体",
     "q": ["「拠点ごとの状況」を報告の画面の上に置いたままにするか、一覧の画面に分けるか", "Giữ \"拠点ごとの状況\" ở trên màn báo cáo hay tách thành màn danh sách riêng"],
     "a": ["「棚卸一覧」（CW_STOCK_002）に分ける。月度×拠点の一覧（月度・拠点・配送の方法・状態・報告日・報告者）、絞り込みは 月度（今回＋過去3か月）・拠点・状態。行から報告の画面へ。メニュー「棚卸報告」は一覧を開く。報告の画面（CW_STOCK_001）は選んだ拠点・月度だけ",
           "Tách thành \"棚卸一覧\" (CW_STOCK_002): danh sách tháng × chi nhánh (月度・拠点・配送の方法・状態・報告日・報告者), lọc theo 月度 (tháng này + 3 tháng trước)・拠点・状態. Bấm dòng để sang màn báo cáo. Menu \"棚卸報告\" mở danh sách. Màn báo cáo (CW_STOCK_001) chỉ còn chi nhánh / tháng đã chọn"],
     "src": "hong 回答 2026-10-05 版1.0レビュー ①"},
    {"date": "2026-10-05", "target": "CW_STOCK_001 全体",
     "q": ["文言に残っている「在庫点検」", "Từ \"在庫点検\" còn sót trong câu chữ"],
     "a": ["「在庫点検」という語は使わない（「棚卸報告」「棚卸」に揃える。「在庫を数えて」はそのまま）", "Không dùng từ \"在庫点検\" (thống nhất \"棚卸報告\" / \"棚卸\"; \"在庫を数えて\" giữ nguyên)"],
     "src": "hong 回答 2026-10-05 版1.0レビュー ②"},
    {"date": "2026-10-05", "target": "CW_STOCK_001 No.10.4",
     "q": ["報告した方の既定", "Giá trị mặc định của người báo cáo"],
     "a": ["その拠点のメイン担当者を選んだ状態で開く（変えられる）。メイン担当者がない拠点は未選択", "Mở với người phụ trách chính (メイン担当者) của chi nhánh đã được chọn sẵn (đổi được). Chi nhánh không có メイン担当者 thì chưa chọn"],
     "src": "hong 回答 2026-10-05 版1.0レビュー ③"},
    {"date": "2026-10-05", "target": "CW_STOCK_001 No.1.4",
     "q": ["数えるときに使う紙の表", "Bảng giấy dùng khi đếm"],
     "a": ["「棚卸用の表（PDF）」を出せる：商品・前回の数・今ある数（空欄）・捨てた数（空欄）・届いた数（空欄）の表。拠点・月度・報告期限を頭に。A4", "Xuất được \"棚卸用の表（PDF）\": bảng 商品・前回の数・今ある数 (trống)・捨てた数 (trống)・届いた数 (trống). Đầu trang có chi nhánh, tháng, hạn báo cáo. Khổ A4"],
     "src": "hong 回答 2026-10-05 版1.0レビュー ④"},
    {"date": "2026-10-05", "target": "CW_STOCK_001 No.3.15",
     "q": ["一覧にない商品を法人が足せるか（Q-S3 の見直し）", "Pháp nhân có thêm được sản phẩm ngoài danh sách không (xem lại Q-S3)"],
     "a": ["足せる。JAN のスキャン（スマホのカメラ）か商品名の検索で商品を選び、表に行を足す（前回の数 0）。Q-S3「法人は一覧にない商品を足せない」を置き換え", "Được. Quét JAN (camera điện thoại) hoặc tìm theo tên sản phẩm rồi thêm dòng vào bảng (số lần trước = 0). Thay thế Q-S3 \"pháp nhân không thêm được\""],
     "src": "hong 回答 2026-10-05 版1.0レビュー ⑤"},
    {"date": "2026-10-05", "target": "CW_STOCK_001 No.10",
     "q": ["「前回から大きく増えた」の警告（C-g ②）", "Cảnh báo \"tăng nhiều so với lần trước\" (C-g ②)"],
     "a": ["出さない（W206 は使わない）。C-g ② を置き換え", "Không hiện (không dùng W206). Thay thế C-g ②"],
     "src": "hong 回答 2026-10-05 版1.0レビュー ⑥"},
    {"date": "2026-10-05", "target": "CW_STOCK_001 No.10",
     "q": ["報告の確認モーダルの中身", "Nội dung modal xác nhận báo cáo"],
     "a": ["簡単に：拠点・月度・報告する商品の件数と、報告した方（既定＝メイン担当者）だけ。商品ごとの一覧は出さない", "Đơn giản: chỉ chi nhánh, tháng, số sản phẩm báo cáo và người báo cáo (mặc định = メイン担当者). Không hiện danh sách từng sản phẩm"],
     "src": "hong 回答 2026-10-05 版1.0レビュー ⑦"},
    {"date": "2026-10-05", "target": "CW_STOCK_001／002 全体",
     "q": ["法人Web の棚卸報告の画面・文言で「点検」と「棚卸」のどちらを使うか", "Màn hình / câu chữ 法人Web dùng \"点検\" hay \"棚卸\""],
     "a": ["「棚卸」（棚卸なし・前回の棚卸・棚卸した数・棚卸する人・棚卸する商品・棚卸します）。「点検」は使わない（在庫点検も使わない）", "\"棚卸\" (棚卸なし・前回の棚卸・棚卸した数・棚卸する人・棚卸する商品・棚卸します). Không dùng \"点検\" (cũng không dùng \"在庫点検\")"],
     "src": "hong 回答 2026-10-05（台帳 E「法人Web 版 1.1 のレビュー 2回目」・受付簿 No.157）"},
    {"date": "2026-10-05", "target": "CW_STOCK_001 No.22・29・3.11.8",
     "q": ["見本データにない状態（未報告（事務手数料あり）・お届け中・行のエラー）を demo_ok の注記で済ませてよいか", "Có thể xử lý các trạng thái không có trong dữ liệu mẫu (未報告（事務手数料あり）・đang giao・lỗi theo dòng) bằng ghi chú demo_ok không"],
     "a": ["済ませない。見本データと撮影の手順で作る（横浜営業所＝2026-09 未報告・追加配送（出荷済）・画面状態 026）。作れないものだけ注記を残す", "Không. Tạo bằng dữ liệu mẫu và thủ tục chụp (横浜営業所 = 2026-09 chưa báo cáo, đơn giao bổ sung (出荷済), trạng thái màn hình 026). Chỉ giữ ghi chú cho thứ không thể tạo"],
     "src": "hong 回答 2026-10-05（台帳 E「法人Web 版 1.1 のレビュー 2回目」・受付簿 No.157）"},
]

CHANGES = [
    {"ver": "1.4", "date": "2026-10-05", "no": ["1.3", "1.4", "3.6", "3.9", "3.10", "3.11", "3.11.2", "3.11.6", "3.13", "3.14", "3.15", "10.1", "14.1", "15", "19", "24", "28", "30", "35.3", "36", "36.5", "36.8", "40", "41", "41.4", "41.5", "42"], "type": "変更",
     "before": ["「点検」の言い方：点検なし・前回の点検・点検した数・点検する人・点検する商品・点検の表・点検します", "Cách nói \"点検\": 点検なし・前回の点検・点検した数・点検する人・点検する商品・点検の表・点検します"],
     "after": ["「棚卸」に統一：棚卸なし・前回の棚卸・棚卸した数・棚卸する人・棚卸する商品・棚卸の表・棚卸します。状態の名前も「棚卸なし」「棚卸なし（休止中）」。「在庫点検」は引き続き使わない", "Thống nhất 「棚卸」: 棚卸なし・前回の棚卸・棚卸した数・棚卸する人・棚卸する商品・棚卸の表・棚卸します. Tên trạng thái cũng thành 「棚卸なし」「棚卸なし（休止中）」. Vẫn không dùng \"在庫点検\""],
     "reason": ["hong 回答 2026-10-05（版 1.1 のレビュー 2回目・受付簿 No.157）：法人Web の画面は「点検」でなく「棚卸」", "hong trả lời 2026-10-05 (review bản 1.1 lần 2, 受付簿 No.157): màn hình 法人Web dùng 「棚卸」 thay vì 「点検」"],
     "impact": ["コードの文言を変更（lib/corp/docs/logic.ts の STOCK_WAY・STOCK_STATES・stockStat、棚卸一覧・棚卸報告の列名・案内・CSV の「棚卸する人」、docs.css の列見出し、棚卸の API のエラー文）。状態の絞り込み・バッジ・CSV の値が「棚卸なし」になる。画面状態の ID は変えない", "Đổi câu chữ trong code (STOCK_WAY・STOCK_STATES・stockStat trong lib/corp/docs/logic.ts, tên cột và thông báo ở 棚卸一覧・棚卸報告, cột 「棚卸する人」 của CSV, tiêu đề cột trong docs.css, câu lỗi của API). Giá trị lọc trạng thái, badge, CSV thành 「棚卸なし」. Không đổi ID trạng thái màn hình"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "22", "type": "変更",
     "before": ["未報告（事務手数料あり）の案内は、見本データに該当の拠点がなく画像なし（demo_ok）", "Thông báo 未報告（事務手数料あり） không có ảnh vì dữ liệu mẫu không có chi nhánh nào như vậy (demo_ok)"],
     "after": ["見本データの横浜営業所（CU00950）が 2026-09 の棚卸報告を25日までにしなかった拠点になり、/corp/stock/CU00950/2026-09 で E322 と状態「未報告（事務手数料あり）」が出る。注記（demo_ok）を削除", "横浜営業所 (CU00950) trong dữ liệu mẫu là chi nhánh không báo cáo kiểm kê 2026-09 đến ngày 25, nên /corp/stock/CU00950/2026-09 hiện E322 và trạng thái 「未報告（事務手数料あり）」. Xóa ghi chú demo_ok"],
     "reason": ["hong 回答 2026-10-05：「demo_ok で逃げず、見本データを作る」（受付簿 No.157）", "hong trả lời 2026-10-05: \"không né bằng demo_ok, hãy tạo dữ liệu mẫu\" (受付簿 No.157)"],
     "impact": ["共通データの見本（lib/domain/seed/report.ts）で横浜営業所の 2026-09 の棚卸報告の記録を作らない。横浜営業所は報告の記録が1つもないため、棚卸一覧に「最初の棚卸報告をしてください」（受付簿 No.134）も出る。運営Web の実績精算でも未報告の拠点になる", "Trong dữ liệu mẫu chung (lib/domain/seed/report.ts) không tạo bản ghi báo cáo 2026-09 của 横浜営業所. Vì chưa có bản ghi nào nên 棚卸一覧 cũng hiện \"最初の棚卸報告をしてください\" (受付簿 No.134). Ở 実績精算 của 運営Web cũng là chi nhánh chưa báo cáo"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "29", "type": "変更",
     "before": ["お届け中の商品の案内は、見本にお届け中（出荷済）の便がなく画像なし（demo_ok）", "Thông báo sản phẩm đang giao không có ảnh vì dữ liệu mẫu không có chuyến đang giao (出荷済) (demo_ok)"],
     "after": ["見本データに横浜営業所の追加配送（9/29 の冷蔵の便に追加で手配した4食・10/02 出荷・10/06 お届け予定・出荷済）を入れ、画面状態 017 で案内と「届いた数」が出る。注記を削除", "Thêm vào dữ liệu mẫu một đơn giao bổ sung của 横浜営業所 (4 phần bổ sung cho chuyến lạnh 9/29, xuất 10/02, dự kiến giao 10/06, trạng thái 出荷済); ở trạng thái màn hình 017 hiện thông báo và ô 「届いた数」. Xóa ghi chú"],
     "reason": ["hong 回答 2026-10-05（版 1.1 のレビュー 2回目・受付簿 No.157）", "hong trả lời 2026-10-05 (review bản 1.1 lần 2, 受付簿 No.157)"],
     "impact": ["共通データの配送の見本（lib/domain/seed/delivery.ts）に子の配送 DL-260928-0001-1 を追加（運営Web・委託配送先の配送一覧にも1件増える）。整合の確認（check.run）は問題なし", "Thêm đơn con DL-260928-0001-1 vào dữ liệu mẫu giao hàng (lib/domain/seed/delivery.ts); danh sách giao hàng của 運営Web / đơn vị vận chuyển cũng tăng 1 dòng. Kiểm tra nhất quán (check.run) không có vấn đề"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "3.11.8", "type": "変更",
     "before": ["行のエラー（E321・E327）は画面状態 001 の項目で、「数をまちがえて入れたときだけ出る。最初の画面には出ない」という注記（demo_ok）つき", "Lỗi theo dòng (E321・E327) là mục của trạng thái màn hình 001, kèm ghi chú \"chỉ hiện khi nhập sai số, màn hình ban đầu không có\" (demo_ok)"],
     "after": ["行のエラーは新しい画面状態 026（横浜営業所 2026-10・数をまちがえて入れた状態）の項目にした。注記を削除。項目の内容は変えない", "Lỗi theo dòng chuyển sang trạng thái màn hình mới 026 (横浜営業所 2026-10, trạng thái nhập sai số). Xóa ghi chú. Nội dung mục không đổi"],
     "reason": ["hong 回答 2026-10-05（版 1.1 のレビュー 2回目・受付簿 No.157）", "hong trả lời 2026-10-05 (review bản 1.1 lần 2, 受付簿 No.157)"],
     "impact": ["画面の動きは変わらない（設計書の画像の取り方だけ）", "Hành vi màn hình không đổi (chỉ cách chụp ảnh trong tài liệu)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "3.11.8", "type": "追加",
     "after": ["画面状態 026「入力エラー（行のエラー・届いた数と合計）」：撮影の手順（setup の JS）で、お届け中がある行の「届いた数」に 99、ほかの1行の「今ある数」に 9999 を入れ、E321・E327 の行のエラーを出す", "Trạng thái màn hình mới 026 \"Lỗi nhập liệu (lỗi theo dòng)\": qua JS setup nhập 99 vào 「届いた数」 của dòng đang giao và 9999 vào 「今ある数」 của một dòng khác để hiện lỗi theo dòng E321・E327"],
     "reason": ["hong 回答 2026-10-05（版 1.1 のレビュー 2回目・受付簿 No.157）", "hong trả lời 2026-10-05 (review bản 1.1 lần 2, 受付簿 No.157)"],
     "impact": ["画面状態の ID は末尾に追加（001〜025 は変えない）。画面の動きは変わらない", "Thêm ID trạng thái ở cuối (001〜025 không đổi). Hành vi màn hình không đổi"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["18", "27"], "type": "変更",
     "before": ["「コードは見るだけ→直す宿題」（18）、「コードは『ES配送便ドライバー（法人アカウント）』と表示することがある→直す宿題」（27）という注記（demo_ok）", "Ghi chú demo_ok: \"code chỉ xem → sửa sau\" (18), \"code có thể hiện 『ES配送便ドライバー（法人アカウント）』 → sửa sau\" (27)"],
     "after": ["注記を削除。コードは直っている（ES配送便の拠点も法人・拠点が入力・報告し直せる。報告者・報告の方法は最後に報告した方に合わせる）", "Xóa ghi chú. Code đã sửa (chi nhánh ES配送便 cũng nhập / báo cáo lại được; người báo cáo và cách báo cáo theo người báo cáo cuối)"],
     "reason": ["注記が古い（コードは直っている）。hong 回答 2026-10-05（受付簿 No.157）：demo_ok を残さない", "Ghi chú đã cũ (code đã sửa). hong trả lời 2026-10-05 (受付簿 No.157): không để lại demo_ok"],
     "impact": ["画面設計書の注記だけ。コードの変更なし", "Chỉ sửa ghi chú trong tài liệu thiết kế. Không đổi code"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "14.1", "type": "変更",
     "before": ["運営が確認済みの報告でも「数え直して報告し直す」ボタンを出し、保存で止めていた（コードを直す宿題）", "Báo cáo đã được 運営 xác nhận vẫn hiện nút 「数え直して報告し直す」 và chỉ chặn khi lưu (việc sửa code còn tồn)"],
     "after": ["運営が確認済みの報告（今回の月度）にはボタンを出さず、案内の中に「ESキッチンが確認済みのため、報告し直すことはできません。」（E326）を出す", "Báo cáo (tháng này) đã được 運営 xác nhận thì không hiện nút mà hiện câu 「ESキッチンが確認済みのため、報告し直すことはできません。」 (E326) trong thông báo"],
     "reason": ["hong 回答 2026-10-05（版 1.1 のレビュー 2回目・受付簿 No.157）", "hong trả lời 2026-10-05 (review bản 1.1 lần 2, 受付簿 No.157)"],
     "impact": ["コード：StockRec に confirmed を追加（lib/corp/docs/types.ts・fromDomain.ts）、棚卸報告の案内で確認済みのときボタンを出さない。この状態の画像は撮れない（見本データの今回の月度に確認済みの報告がない）", "Code: thêm confirmed vào StockRec, không hiện nút khi đã xác nhận. Không có ảnh cho trạng thái này (dữ liệu mẫu tháng này không có báo cáo đã xác nhận)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "31", "type": "変更",
     "before": ["代替品の回収のお知らせはコードが大阪支店 2026-10 に直書き（demo_ok）", "Thông báo thu hồi hàng thay thế được code ghi cứng cho 大阪支店 2026-10 (demo_ok)"],
     "after": ["お知らせは代替品の設定のデータから出す（今回の月度・この拠点に回収・廃棄する商品があるとき）。COOL便の拠点には「お客様で廃棄して、棚卸報告の「捨てた数」にご入力ください。」を案内する（見本では千葉営業所にも出る）。注記を削除", "Thông báo lấy từ dữ liệu thiết lập hàng thay thế (khi tháng này chi nhánh có sản phẩm cần thu hồi / bỏ). Chi nhánh COOL便 được hướng dẫn \"お客様で廃棄して、棚卸報告の「捨てた数」にご入力ください。\" (ở dữ liệu mẫu 千葉営業所 cũng hiện). Xóa ghi chú"],
     "reason": ["決定_代替品 Q-ALT8（お知らせは代替品の設定のデータから出す）。hong 回答 2026-10-05（受付簿 No.157）：demo_ok を残さない", "決定_代替品 Q-ALT8 (thông báo lấy từ dữ liệu thiết lập hàng thay thế). hong trả lời 2026-10-05 (受付簿 No.157): không để lại demo_ok"],
     "impact": ["コード：corp-docs.stock が alts（代替品の設定の廃棄の分）を返し、棚卸報告の画面がそれで案内を出す（拠点・月度の直書きをやめた）。千葉営業所の棚卸報告にもお知らせが出る", "Code: corp-docs.stock trả alts (phần bỏ trong thiết lập hàng thay thế) và màn hình báo cáo hiển thị theo đó (bỏ ghi cứng chi nhánh / tháng). 千葉営業所 cũng hiện thông báo"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["3", "36"], "type": "追加",
     "after": ["読み込めなかったとき（通信・サーバーのエラー）の表示：白い画面にせず、E346「読み込めませんでした。／時間をおいて再度お試しください。」と「再読み込み」ボタンを出す（棚卸一覧・棚卸報告）。読み込み中は「読み込み中…」", "Hiển thị khi không tải được dữ liệu (lỗi mạng / máy chủ): không để trắng màn hình mà hiện E346 \"読み込めませんでした。\" kèm nút 「再読み込み」 (棚卸一覧・棚卸報告). Khi đang tải hiện 「読み込み中…」"],
     "reason": ["QA レビュー（API エラーのとき白い画面になる）。hong 回答 2026-10-05（受付簿 No.157）", "Review QA (lỗi API làm trắng màn hình). hong trả lời 2026-10-05 (受付簿 No.157)"],
     "impact": ["コード：app/corp/_docs/ds.tsx に LoadingState・LoadError を追加。E346 は共通メッセージの既存の文言を使う。画像はない（見本データではエラーを起こせない）", "Code: thêm LoadingState・LoadError vào app/corp/_docs/ds.tsx. Dùng câu E346 có sẵn trong thông điệp chung. Không có ảnh (dữ liệu mẫu không tạo được lỗi)"]},
    {"ver": "1.3", "date": "2026-10-05", "no": "14.1", "type": "変更",
     "before": ["条件：「…報告済・運営が確認済みでないとき」", "Điều kiện: 「…報告済・運営が確認済みでないとき」"],
     "after": ["条件：「…報告済み・運営が確認済みでないとき」（状態名を「報告済」に統一）", "Điều kiện: 「…報告済み・運営が確認済みでないとき」 (thống nhất tên trạng thái là 「報告済」)"],
     "reason": ["hong 回答 2026-10-05（版 1.1 のレビュー・受付簿 No.156）", "hong trả lời 2026-10-05 (review bản 1.1, 受付簿 No.156)"],
     "impact": ["画面の動きは変わらない（状態名の表記だけ）", "Hành vi không đổi (chỉ cách ghi tên trạng thái)"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["1.4", "3.6", "3.10", "10.7", "14", "16", "19", "20", "35.3", "36", "36.5"], "type": "変更",
     "before": ["状態の名前は「報告済」", "Tên trạng thái là \"報告済\""],
     "after": ["状態の名前は「報告済」（棚卸一覧の絞り込みの選択肢・バッジ・CSV の「状態」の値・並び順の説明とも）。状態の ID（画面状態 008・011 など）は変えない", "Tên trạng thái là \"報告済み\" (lựa chọn lọc ở danh sách, badge, giá trị cột \"状態\" của CSV, mô tả thứ tự sắp xếp). Không đổi ID trạng thái màn hình (008, 011…)"],
     "reason": ["hong 回答 2026-10-05 版1.1レビュー ③（受付簿 No.156）", "hong trả lời 2026-10-05 (review bản 1.1) ③ (受付簿 No.156)"],
     "impact": ["コードの状態名（STOCK_STATES・stockStat・stockRank）を「報告済」に。並び順は 未報告 → 報告済 → 点検なし・休止中・ご契約前 のまま", "Đổi tên trạng thái trong code (STOCK_STATES・stockStat・stockRank) thành \"報告済み\". Thứ tự giữ nguyên: 未報告 → 報告済 → 点検なし・休止中・ご契約前"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["3.5", "3.6", "3.10", "12", "36.5"], "type": "変更",
     "before": ["「コードは20日で判定し、文言も『期限までに報告がない場合』のまま。コードを直す宿題」という注記（demo_ok）", "Ghi chú (demo_ok): \"code xét ngày 20, câu chữ vẫn ghi 『期限までに報告がない場合』; việc sửa code còn tồn\""],
     "after": ["注記を削除。コードは 25日（lib/corp/docs/logic.ts の judge）で判定し、文言も判定日まで（I215 など）に直っている", "Xóa ghi chú. Code đã xét ngày 25 (judge trong lib/corp/docs/logic.ts) và câu chữ nói tới ngày xét (I215…)"],
     "reason": ["注記が古い（コードは直っている）", "Ghi chú đã cũ (code đã sửa)"],
     "impact": ["画面設計書の注記だけ。コードの変更なし", "Chỉ sửa ghi chú trong tài liệu thiết kế. Không đổi code"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["1.4", "3.11", "3.13", "23", "24"], "type": "変更",
     "before": ["ご契約前・休止中の月度でも、コードは報告できる状態（canIn）の判定がご契約前を見ておらず、棚卸用の表（PDF）ボタンと空の表が出ていた。No.23 は「表は出すが商品はない」", "Ở tháng trước hợp đồng / tạm dừng, code không xét \"trước hợp đồng\" khi tính canIn, và vẫn hiện nút \"棚卸用の表（PDF）\" cùng bảng trống. No.23 ghi \"hiện bảng nhưng không có sản phẩm\""],
     "after": ["ご契約前の月度は報告できない（入力・報告するを出さない）。ご契約前・休止中・点検なしの月度は、報告する表と「棚卸用の表（PDF）」を出さない", "Tháng trước hợp đồng không báo cáo được (không hiện ô nhập, nút \"報告する\"). Tháng trước hợp đồng / tạm dừng / không kiểm kê: không hiện bảng kiểm kê và nút \"棚卸用の表（PDF）\""],
     "reason": ["QA レビュー：設計書どおりに動かない不具合（ご契約前に入力できてしまう・PDF が出る）。設計書の説明も「表は出すが商品はない」から直す", "Review QA: lỗi chạy không đúng thiết kế (nhập được ở tháng trước hợp đồng, hiện PDF). Sửa cả mô tả \"hiện bảng nhưng không có sản phẩm\""],
     "impact": ["コード：canIn に「ご契約の開始より前の月度は不可」を追加し、表・PDF ボタンの出す条件に 休止中・ご契約前 を加えた", "Code: thêm điều kiện \"tháng trước ngày bắt đầu hợp đồng thì không\" vào canIn; thêm tạm dừng / trước hợp đồng vào điều kiện hiện bảng và nút PDF"]},
    {"ver": "1.3", "date": "2026-10-05", "no": "3.11.8", "type": "追加",
     "before": ["（なし）届いた数・合計の誤りは、「報告する」を押したときのトーストだけ", "(Không có) Lỗi 届いた数 / tổng chỉ báo bằng toast khi bấm \"報告する\""],
     "after": ["誤りのある行に、赤枠と行の中のメッセージ（E321 届いた数＞お届け中／E327 今ある数＋捨てた数＞前回の数＋届けた数）を出す。式はサーバーの確認と同じ。「商品を追加」の行は E327 の対象外", "Dòng sai hiện viền đỏ và thông báo ngay trong dòng (E321 届いた数 > đang giao / E327 今ある数 + 捨てた数 > 前回の数 + 届けた数). Công thức giống kiểm tra phía server. Dòng thêm bằng \"商品を追加\" không áp dụng E327"],
     "reason": ["QA レビュー：どの行がまちがっているか、押す前に分かるようにする", "Review QA: để người dùng biết dòng nào sai trước khi bấm"],
     "impact": ["コード：棚卸報告の行ごとの確認（rowErr）を追加。「報告する」でも E327 を確かめてからモーダルへ（3.11.5・3.11.6・3.11.7・3.13 の err に E327 を足した）", "Code: thêm kiểm tra theo dòng (rowErr). \"報告する\" cũng kiểm tra E327 trước khi mở modal (đã thêm E327 vào err của 3.11.5・3.11.6・3.11.7・3.13)"]},
    {"ver": "1.3", "date": "2026-10-05", "no": "3.13", "type": "変更",
     "before": ["解約後（参照のみ）の帯が「編集・お申し込みはできません」と書くだけで、棚卸報告ができることを案内していなかった", "Dải thông báo sau hủy hợp đồng (chỉ xem) chỉ ghi \"không sửa / đăng ký được\", không nói báo cáo kiểm kê vẫn làm được"],
     "after": ["帯に「棚卸報告は最終請求書のためにご入力いただけます」を足す（台帳 行185）", "Thêm vào dải \"棚卸報告 vẫn nhập được để phục vụ hóa đơn cuối\" (台帳 dòng 185)"],
     "reason": ["QA レビュー：台帳「解約後にできること＝棚卸報告だけ」と帯の文が食い違っていた", "Review QA: dải thông báo mâu thuẫn với 台帳 \"sau hủy hợp đồng chỉ làm được 棚卸報告\""],
     "impact": ["コード：app/corp/_docs/ds.tsx の帯の文を直した。_DEMO_RO の注記も書き換え", "Code: sửa câu trong dải ở app/corp/_docs/ds.tsx. Viết lại ghi chú _DEMO_RO"]},
    {"ver": "1.3", "date": "2026-10-05", "no": "10.7", "type": "変更",
     "before": ["トースト S208 をコードが「…反映します（報告期限までは最後の報告が有効）。」と出していた", "Code hiện toast S208 là \"…反映します（報告期限までは最後の報告が有効）。\""],
     "after": ["S208 は _共通_メッセージ.py どおり「棚卸を報告しました。ESキッチンの在庫管理に反映します。」", "S208 theo đúng _共通_メッセージ.py: \"棚卸を報告しました。ESキッチンの在庫管理に反映します。\""],
     "reason": ["メッセージ一覧とコードの文を同じにする（最後の報告が有効という案内は S209・No.14 にある）", "Thống nhất câu trong danh sách thông báo và code (nội dung \"báo cáo cuối có hiệu lực\" đã có ở S209・No.14)"],
     "impact": ["コードの文言を一覧に合わせた", "Đã sửa câu trong code cho khớp danh sách"]},
    {"ver": "1.3", "date": "2026-10-05", "no": "33", "type": "変更",
     "before": ["本文・メモに S210（CSV出力の完了）と書いていた", "Phần mô tả và note ghi S210 (hoàn tất xuất CSV)"],
     "after": ["S12（CSVを出力しました（{n}行）。）に直す。err はもともと S12", "Sửa thành S12 (CSVを出力しました（{n}行）。). Cột err vốn đã là S12"],
     "reason": ["_共通_メッセージ.py の CSV出力の完了は S12。S210 は別のメッセージ", "Thông báo hoàn tất xuất CSV trong _共通_メッセージ.py là S12; S210 là thông báo khác"],
     "impact": ["設計書の参照番号だけの修正。コードの変更なし", "Chỉ sửa số tham chiếu trong tài liệu. Không đổi code"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["1.1", "3", "10.7"], "type": "削除",
     "before": ["画面・案内・オプションの備考などに「在庫点検」という語が残っていた", "Từ \"在庫点検\" còn sót trong màn hình, thông báo, ghi chú option…"],
     "after": ["「在庫点検」を使わない（通知の本文は「棚卸報告の『捨てた数』にご入力ください」。オプション OP000016 の備考は「棚卸報告」）", "Không dùng \"在庫点検\" (nội dung thông báo: \"棚卸報告の『捨てた数』にご入力ください\"; ghi chú option OP000016 dùng \"棚卸報告\")"],
     "reason": ["台帳 270 ②：メニュー名・画面名は「棚卸報告」。コードと画面から「在庫点検」をなくす", "台帳 270 ②: tên menu / màn hình là \"棚卸報告\". Bỏ \"在庫点検\" khỏi code và màn hình"],
     "impact": ["コード：代替品のお知らせの本文・不良品の扱いの値（法人が廃棄して棚卸報告で申告）・seed のオプション備考を直した。運営Web・ドライバーアプリの一部はまだ残っている", "Code: sửa nội dung thông báo hàng thay thế, giá trị cách xử lý hàng lỗi (法人が廃棄して棚卸報告で申告), ghi chú option trong seed. Một phần 運営Web / app tài xế vẫn còn"]},
    {"ver": "1.2", "date": "2026-10-05", "no": "1.1", "type": "変更",
     "before": ["見出し・パンくずの説明のみ", "Chỉ mô tả tiêu đề và breadcrumb"],
     "after": ["URL を追記：/corp/stock/<拠点ID>/<月度>", "Bổ sung URL: /corp/stock/<拠点ID>/<月度>"],
     "reason": ["版 1.1 で一覧（CW_STOCK_002）と分けたため、この画面の URL を明記", "Vì đã tách khỏi danh sách (CW_STOCK_002) ở bản 1.1 nên ghi rõ URL màn này"],
     "impact": ["ルーティングは /corp/stock/<拠点ID>/<月度>", "Routing là /corp/stock/<拠点ID>/<月度>"]},
    {"ver": "1.2", "date": "2026-10-05", "no": "41.1", "type": "変更",
     "before": ["スマホ（カメラのあるブラウザ）だけ出す。PC では出さない。許可・カメラがないときは I226", "Chỉ hiện trên điện thoại (trình duyệt có camera), PC không hiện. Không cấp quyền / không có camera: I226"],
     "after": ["カメラのあるブラウザだけ出す（カメラがなければ出さない）。許可・カメラ・バーコードを読む機能がないブラウザでは I226", "Chỉ hiện ở trình duyệt có camera (không có thì ẩn). Không có quyền / camera / chức năng đọc mã vạch: I226"],
     "reason": ["コードの実際の判定（カメラの有無とバーコード読み取りの対応）に合わせる", "Khớp cách kiểm tra thực tế trong code (có camera và hỗ trợ đọc mã vạch)"],
     "impact": ["表示条件を「カメラの有無」で判定し、読めないブラウザは I226", "Điều kiện hiển thị theo \"có camera\"; trình duyệt không đọc được thì I226"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["34", "34.1", "34.2", "35", "35.1", "35.2", "35.3", "35.4", "36", "36.1", "36.2", "36.3", "36.4", "36.5", "36.6", "36.7", "36.8", "36.9", "37", "38"], "type": "追加",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー ①：「棚卸一覧」の画面（CW_STOCK_002）を分ける。月度×拠点の一覧、絞り込み（月度・拠点・状態）、行から報告の画面へ。メニュー「棚卸報告」は一覧を開く",
                "hong trả lời 2026-10-05 (review bản 1.0) ①: tách màn \"棚卸一覧\" (CW_STOCK_002). Danh sách tháng × chi nhánh, lọc (月度・拠点・状態), bấm dòng sang màn báo cáo. Menu \"棚卸報告\" mở danh sách"],
     "impact": ["新しい画面 /corp/stock（一覧）を作り、いまの報告の画面を /corp/stock/{拠点ID}/{月度} などに移す。サイドメニュー「棚卸報告」のリンク先を一覧にする（受付簿 No.153）",
                "Tạo màn mới /corp/stock (danh sách), chuyển màn báo cáo hiện tại sang /corp/stock/{拠点ID}/{月度} (hoặc tương tự). Menu \"棚卸報告\" trỏ tới danh sách (受付簿 No.153)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["2", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "5", "21", "25"], "type": "削除",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー ①：「拠点ごとの状況」は棚卸一覧（CW_STOCK_002 No.36）に移す。報告の画面は選んだ拠点・月度だけにする",
                "hong trả lời 2026-10-05 (review bản 1.0) ①: \"拠点ごとの状況\" chuyển sang 棚卸一覧 (CW_STOCK_002 No.36). Màn báo cáo chỉ còn chi nhánh / tháng đã chọn"],
     "impact": ["報告の画面から「拠点ごとの状況」の表（table.sk-st）を外す。拠点・対象月の選択（No.3.1・3.2）は残す", "Bỏ bảng \"拠点ごとの状況\" (table.sk-st) khỏi màn báo cáo. Giữ chọn chi nhánh / tháng (No.3.1・3.2)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["1.1", "1.2", "3.1", "3.2", "3.6", "16", "24"], "type": "変更",
     "before": ["「拠点ごとの状況」の表を前提にした説明（選択行・同じバッジ・行の変化）", "Mô tả dựa trên bảng \"拠点ごとの状況\" (dòng chọn, badge giống, dòng đổi)"],
     "after": ["棚卸一覧（CW_STOCK_002）を前提にした説明。パンくずは「棚卸一覧 / 棚卸報告」", "Mô tả dựa trên 棚卸一覧 (CW_STOCK_002). Breadcrumb \"棚卸一覧 / 棚卸報告\""],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー ①（一覧の画面を分けたため）", "hong trả lời 2026-10-05 (review bản 1.0) ① (do tách màn danh sách)"],
     "impact": ["パンくずと説明文を直す。拠点・月度を変えたときの一覧との連動はなくなる", "Sửa breadcrumb và câu chữ. Không còn liên động với bảng khi đổi chi nhánh / tháng"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["28"], "type": "変更",
     "before": ["状態の名前は「点検なし」のまま、説明に「在庫点検」", "Trạng thái \"点検なし\", giải thích có \"在庫点検\""],
     "after": ["「在庫点検」という語を使わない（状態の名前「点検なし」は残す）。運営Web の設定の呼び方も「棚卸報告：なし」", "Không dùng \"在庫点検\" (giữ tên trạng thái \"点検なし\"). Thiết lập trên 運営Web gọi là \"棚卸報告：なし\""],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー ②：「在庫点検」という語は使わない", "hong trả lời 2026-10-05 (review bản 1.0) ②: không dùng từ \"在庫点検\""],
     "impact": ["画面・案内・トーストの文言から「在庫点検」をなくす（見出し「{拠点名} の在庫点検」→「の棚卸報告」、S208 の文言など）", "Bỏ \"在庫点検\" khỏi mọi câu chữ trên màn hình, thông báo, toast (tiêu đề \"{拠点名} の在庫点検\" → \"の棚卸報告\", câu S208…)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["10", "10.1", "10.3", "10.4", "10.5", "13"], "type": "変更",
     "before": ["幅 800px。報告する数の一覧（商品ごと）＋報告した方の表（ラジオ・未選択）", "Rộng 800px. Danh sách số theo sản phẩm + bảng chọn người báo cáo (radio, chưa chọn)"],
     "after": ["幅 560px。拠点・月度・報告する商品の件数＋報告した方の選択（プルダウン・既定＝この拠点のメイン担当者）", "Rộng 560px. Chi nhánh, tháng, số sản phẩm + chọn người báo cáo (dropdown, mặc định = メイン担当者 của chi nhánh)"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー ③⑦：報告した方の既定はメイン担当者。確認モーダルは簡単に（件数と報告した方だけ）", "hong trả lời 2026-10-05 (review bản 1.0) ③⑦: mặc định người báo cáo = メイン担当者. Modal xác nhận đơn giản (chỉ số lượng và người báo cáo)"],
     "impact": ["モーダルを作り直す：商品ごとの一覧と担当者の表をやめ、件数の表示とプルダウンにする。拠点のメイン担当者を既定で選ぶ", "Làm lại modal: bỏ danh sách sản phẩm và bảng người phụ trách, thay bằng số lượng và dropdown. Chọn sẵn メイン担当者 của chi nhánh"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["10.2", "11", "12"], "type": "削除",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー ⑥⑦：商品ごとの一覧と「前回から大きく増えた」の警告（W206）は出さない", "hong trả lời 2026-10-05 (review bản 1.0) ⑥⑦: không hiện danh sách từng sản phẩm và cảnh báo \"tăng nhiều\" (W206)"],
     "impact": ["モーダルの ul.cb-ul・li.rv-skwarn・W206 の枠と、3倍かつ＋20 の判定を外す", "Bỏ ul.cb-ul, li.rv-skwarn, khung W206 và logic ≥3 lần & +20 khỏi modal"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["1.4", "39", "40"], "type": "追加",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー ④：数えるときに使う「棚卸用の表（PDF）」を出せる", "hong trả lời 2026-10-05 (review bản 1.0) ④: xuất được \"棚卸用の表（PDF）\" để dùng khi đếm"],
     "impact": ["PDF の作成（A4 縦・商品ごとの空欄の表）とボタンを足す。S220", "Thêm tạo PDF (A4 dọc, bảng ô trống theo sản phẩm) và nút. S220"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["3.15", "41", "41.1", "41.2", "41.3", "41.4", "41.5", "41.6", "41.7", "42", "42.1"], "type": "追加",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー ⑤：一覧にない商品を足せる（JAN のスキャン（カメラ）か商品名の検索）。Q-S3 を置き換え", "hong trả lời 2026-10-05 (review bản 1.0) ⑤: thêm được sản phẩm ngoài danh sách (quét JAN bằng camera hoặc tìm theo tên). Thay thế Q-S3"],
     "impact": ["「商品を追加」のモーダル（カメラでの JAN 読み取り・JAN 入力・商品名の検索）と、足した行（前回 0）の保存を足す。E329・S219・I224〜I226・W211", "Thêm modal \"商品を追加\" (đọc JAN bằng camera, nhập JAN, tìm theo tên) và lưu dòng đã thêm (lần trước = 0). E329・S219・I224〜I226・W211"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["3.11", "3.11.2", "3.11.5"], "type": "変更",
     "before": ["法人は一覧にない商品を足せない。前回の点検にない商品は「—」", "Pháp nhân không thêm được sản phẩm ngoài danh sách. Không có lần trước thì \"—\""],
     "after": ["一覧にない商品は「商品を追加」（No.3.15）で足せる（前回の数 0）。足した商品は E327 の確認の対象外", "Thêm được sản phẩm ngoài danh sách bằng \"商品を追加\" (No.3.15), lần trước = 0. Sản phẩm đã thêm không áp dụng kiểm tra E327"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー ⑤", "hong trả lời 2026-10-05 (review bản 1.0) ⑤"],
     "impact": ["表に足した行を受け付け、E327（今ある数＋捨てた数 ≦ 前回＋届けた数）はその行に掛けない", "Nhận dòng đã thêm; không áp dụng E327 (今ある数＋捨てた数 ≦ 前回＋届けた数) cho dòng đó"]},
]

HIDE_ALWAYS = [".es-demo-bar", ".es-chatbot", ".es-chatbot__fab", "#es-review"]
STATIC_CSS = ".corp{height:auto!important}.corp-main{overflow:visible!important}.es-sidenav{height:auto!important;min-height:100vh}"
VIEWER_CSS = STATIC_CSS

SCREENS = [
    {"code": "CW_STOCK_001", "ja": "棚卸報告", "vi": "Báo cáo kiểm kê"},
    {"code": "CW_STOCK_002", "ja": "棚卸一覧", "vi": "Danh sách kiểm kê"},
]

# ---- setup の部品（本物の Web：React の select・input に値を入れる）
# 拠点・月度は URL で開く（/corp/stock/<拠点ID>/<月度>）。プルダウンを変えると URL が変わる
_JS_SEL = ("const sel=document.querySelector('%s'); if(sel){Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(sel,'%s'); sel.dispatchEvent(new Event('change',{bubbles:true}));} "
           "await new Promise(r=>setTimeout(r,500)); ")
_JS_FILL = ("const setV=(el,v)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,v); el.dispatchEvent(new Event('input',{bubbles:true}));}; "
            "document.querySelectorAll('table.sk-in input[aria-label$=\"の今ある数\"]').forEach((el,i)=>setV(el,%s)); await new Promise(r=>setTimeout(r,300)); ")
_JS_CLICK_FILE = "const fb=[...document.querySelectorAll('.rv-skact button')].find(b=>b.textContent.includes('報告する')); fb&&fb.click(); await new Promise(r=>setTimeout(r,500)); "
_JS_MODAL_OK = "const okb=[...document.querySelectorAll('.es-dialog__foot button')].find(b=>b.textContent.includes('報告する')); okb&&okb.click(); await new Promise(r=>setTimeout(r,800)); "
# 報告した方を未選択にする（既定はメイン担当者が選ばれている）
_JS_CLEAR_WHO = _JS_SEL % ('#sk-who', '')
_JS_CLICK_BTN = "{const bb=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='%s'); bb&&bb.click();} await new Promise(r=>setTimeout(r,600)); "

# 行のエラー（E321・E327）：届いた数の入力欄がある行（お届け中がある行）に 99、それ以外の最初の行の今ある数に 9999、残りの行の今ある数に 1
_JS_ROW_ERR = ("const setV=(el,v)=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,v); el.dispatchEvent(new Event('input',{bubbles:true}));}; "
               "let big=false; document.querySelectorAll('table.sk-in tbody tr').forEach(tr=>{const n=tr.querySelector('input[aria-label$=\"の今ある数\"]'); const a=tr.querySelector('input[aria-label$=\"の届いた数\"]'); if(!n) return; "
               "if(a){setV(n,'1'); setV(a,'99');} else if(!big){setV(n,'9999'); big=true;} else {setV(n,'1');}}); await new Promise(r=>setTimeout(r,400)); ")

_DEMO_RO = ["台帳 E 2026-10-05（行185）：解約後（参照のみ）でも棚卸報告はできる。コードの参照のみの帯には「棚卸報告は入力できる」と案内した。お届け日の変更申請・資材注文・商品注文のボタンを出さないのは、ほかの画面のコードの宿題（受付簿 No.78）",
            "Theo 台帳 E 2026-10-05 (dòng 185): sau hủy hợp đồng (chỉ xem) vẫn báo cáo kiểm kê được. Dải thông báo chỉ xem trong code đã ghi \"棚卸報告 vẫn nhập được\". Việc ẩn nút đổi ngày giao / đặt vật tư / đặt sản phẩm là việc sửa code ở các màn khác (受付簿 No.78)"]
_DEMO_ES = ["台帳 E 2026-10-05：「ESキッチン」＝お客様の名前、「ES STATION」＝システムの名前。コードの文言は混在。コードを直す宿題（受付簿 No.78）",
            "Theo 台帳 E 2026-10-05: \"ESキッチン\" = tên khách hàng, \"ES STATION\" = tên hệ thống. Câu chữ trong code đang lẫn. Code sẽ sửa sau (受付簿 No.78)"]

VIEWS = [
    # ------------------------------------------------------------ 001 法人アカウント
    {"id": "001", "code": "CW_STOCK_001", "state": ["法人アカウント（選んだ拠点・月度の報告）", "Tài khoản pháp nhân (báo cáo của chi nhánh / tháng đã chọn)"],
     "url": "/corp/stock/CU00961/2026-10", "full": True, "wait": 600, "setup": "",
     "note": ["法人アカウント（CU00001）で、棚卸一覧（CW_STOCK_002）の行から千葉営業所（COOL便・企業担当者が入力する拠点）の今回の月度（2026-10）を開いた状態。選んだ拠点・月度の報告だけを出す（版 1.1：「拠点ごとの状況」の表は棚卸一覧へ移した）。",
              "Tài khoản pháp nhân (CU00001) mở từ dòng của 棚卸一覧 (CW_STOCK_002): 千葉営業所 (COOL便, người phụ trách công ty nhập), tháng này (2026-10). Chỉ hiện báo cáo của chi nhánh / tháng đã chọn (bản 1.1: bảng \"拠点ごとの状況\" chuyển sang 棚卸一覧)."],
     "items": [
         {"no": "1", "ja": "ページ見出し", "vi": "Tiêu đề trang", "sel": ".es-pagehead", "kind": "area", "trig": "view"},
         {"no": "1.1", "ja": "画面名", "vi": "Tên màn hình", "sel": "h1.es-pagehead__title", "kind": "label", "trig": "view",
          "init": ["棚卸報告", "\"棚卸報告\""],
          "detail": ["見出しは「棚卸報告」、パンくずは「棚卸一覧 / 棚卸報告」（「棚卸一覧」を押すと一覧 CW_STOCK_002 へ戻る）。サイドメニュー「棚卸報告」は棚卸一覧を開き、この画面は一覧の行から開く（URL /corp/stock/<拠点ID>/<月度>）。", "Tiêu đề \"棚卸報告\", breadcrumb \"棚卸一覧 / 棚卸報告\" (bấm \"棚卸一覧\" quay về danh sách CW_STOCK_002). Menu \"棚卸報告\" mở danh sách; màn này mở từ dòng của danh sách (URL /corp/stock/<拠点ID>/<月度>)."]},
         {"no": "1.2", "ja": "法人名・権限", "vi": "Tên pháp nhân, quyền", "sel": ".es-pagehead .stat", "kind": "label", "trig": "view",
          "init": ["株式会社サンプル　権限 法人アカウント（自社のすべての拠点）", "株式会社サンプル, quyền: tài khoản pháp nhân (mọi chi nhánh của công ty)"],
          "detail": ["ログイン中のアカウントの法人名と、見られる範囲（法人アカウント＝自社のすべての拠点／拠点アカウント＝この拠点だけ）。棚卸一覧（CW_STOCK_002 No.34.2）と同じ。",
                     "Tên pháp nhân của tài khoản đang đăng nhập và phạm vi xem (tài khoản pháp nhân = mọi chi nhánh / tài khoản chi nhánh = chỉ chi nhánh đó). Giống 棚卸一覧 (CW_STOCK_002 No.34.2)."]},
         {"no": "1.3", "ja": "CSV出力", "vi": "Nút \"CSV出力\"", "sel": "button::CSV出力", "kind": "button", "trig": "click", "pattern": "P-CSV-OUT", "err": ["S12"],
          "detail": ["見てよい拠点の、選んでいる月度の棚卸報告を CSV に出す（1行＝1拠点×1商品）。列：拠点ID・拠点名・配送の方法・棚卸する人・状態・報告日時・報告者＋商品ごとの 商品ID・商品名・前回の棚卸・届けた数・お届け中・廃棄する・今ある数・捨てた数・届いた数（CSV入出力_定義）。",
                     "Xuất CSV báo cáo kiểm kê của các chi nhánh được xem, theo tháng đang chọn (1 dòng = 1 chi nhánh × 1 sản phẩm). Cột: 拠点ID・拠点名・配送の方法・棚卸する人・状態・報告日時・報告者 + theo sản phẩm: 商品ID・商品名・前回の棚卸・届けた数・お届け中・廃棄する・今ある数・捨てた数・届いた数 (CSV入出力_定義)."]},
         {"no": "1.4", "ja": "棚卸用の表（PDF）", "vi": "Nút \"棚卸用の表（PDF）\"", "sel": "button::棚卸用の表（PDF）", "kind": "button", "trig": "click", "err": ["S220"],
          "cond": ["棚卸の表（No.3.11）に商品があるときだけ押せる（ご契約前・休止中・棚卸なしの月度は出さない）", "Chỉ bấm được khi bảng kiểm kê (No.3.11) có sản phẩm (tháng trước hợp đồng, tạm dừng, không kiểm kê thì không hiện)"],
          "detail": ["選んでいる拠点・月度の「棚卸用の表」を PDF で下ろす（No.40。数えるときに手で書き込む表）。報告済みの月度でも出せる（数え直し用）。終わったら S220。ファイル名は 棚卸用の表_<拠点ID>_<yyyymm>.pdf。",
                     "Tải PDF \"棚卸用の表\" của chi nhánh / tháng đang chọn (No.40; bảng để viết tay khi đếm). Tháng đã báo cáo cũng xuất được (để đếm lại). Xong thì S220. Tên file 棚卸用の表_<拠点ID>_<yyyymm>.pdf."]},
         {"no": "3", "err": ["E346"], "ja": "{拠点名} の棚卸報告", "vi": "Báo cáo kiểm kê của {tên chi nhánh}", "sel": "h2::の棚卸報告^2", "kind": "area", "trig": "view",
          "detail": ["選んだ拠点・月度の報告。見出しは「{拠点名} の棚卸報告」。 読み込めなかったとき（通信・サーバーのエラー）は白い画面にせず、E346「読み込めませんでした。／時間をおいて再度お試しください。」と「再読み込み」ボタンを出す（画像なし：見本データではエラーを起こせない）。", "Báo cáo của chi nhánh / tháng đã chọn. Tiêu đề \"{拠点名} の棚卸報告\". Khi không tải được dữ liệu (lỗi mạng / máy chủ) thì không để trắng màn hình mà hiện E346 \"読み込めませんでした。\" kèm nút \"再読み込み\" (không có ảnh: dữ liệu mẫu không tạo được lỗi)."]},
         {"no": "3.1", "ja": "拠点", "vi": "Chi nhánh", "sel": "#sk-site", "kind": "select", "trig": "select", "req": "○", "fid": "sk-site", "len": "選択",
          "init": ["見られる拠点の先頭（拠点ID の昇順）", "Chi nhánh đầu tiên được xem (拠点ID tăng dần)"],
          "ex": ["株式会社サンプル 千葉営業所", "Tên chi nhánh (giá trị là 拠点ID, ví dụ CU00961)"],
          "cond": ["法人アカウントで拠点が2つ以上あるときだけ出す", "Chỉ hiện khi tài khoản pháp nhân có từ 2 chi nhánh"],
          "detail": ["棚卸一覧（CW_STOCK_002）で押した拠点が選ばれている。ほかの拠点に切り替えるためのプルダウン（一覧へ戻らずに変えられる）。変えると下の報告の内容が変わる。入力中の数は拠点ごとに残す。", "Chi nhánh đã bấm ở 棚卸一覧 (CW_STOCK_002) được chọn sẵn. Dropdown để chuyển nhanh sang chi nhánh khác (không cần về danh sách). Đổi thì nội dung báo cáo đổi theo. Số đang nhập được giữ theo từng chi nhánh."]},
         {"no": "3.2", "ja": "対象月", "vi": "Tháng đối tượng", "sel": "#sk-m", "kind": "select", "trig": "select", "req": "○", "fid": "sk-m", "len": ["選択（今回＋過去3か月）", "Chọn (tháng này + 3 tháng trước)"],
          "init": ["今回の月度（「（今回）」付き）", "Tháng này (có chữ \"（今回）\")"],
          "ex": ["2026-10（今回）", "Tháng kiểm kê YYYY-MM; tháng này có đuôi \"（今回）\""],
          "detail": ["棚卸一覧で押した行の月度が選ばれている。今回の月度と過去3か月に切り替えられる（一覧へ戻らずに変えられる）。過去の月は見るだけ（入力できない）。", "Tháng của dòng đã bấm ở 棚卸一覧 được chọn sẵn. Chuyển nhanh được sang tháng này và 3 tháng trước (không cần về danh sách). Tháng trước chỉ xem (không nhập được)."]},
         {"no": "3.3", "ja": "対象期間", "vi": "Kỳ đối tượng", "sel": "label.es-field__label::対象期間^", "kind": "label", "trig": "view",
          "init": ["2026-09-21〜10-20", "2026-09-21〜10-20"],
          "detail": ["前月21日〜当月20日。", "Từ ngày 21 tháng trước đến ngày 20 tháng này."]},
         {"no": "3.4", "ja": "在庫を数える基準日", "vi": "Ngày chuẩn để đếm tồn kho", "sel": "label.es-field__label::在庫を数える基準日^", "kind": "label", "trig": "view",
          "init": ["2026-10-20（対象期間の最終日）", "2026-10-20 (ngày cuối của kỳ)"]},
         {"no": "3.5", "ja": "報告期限", "vi": "Hạn báo cáo", "sel": "label.es-field__label::報告期限^", "kind": "label", "trig": "view",
          "init": ["2026-10-20（21日以降はESキッチンが追加・修正）", "2026-10-20 (từ ngày 21 ESキッチン thêm / sửa)"],
          "detail": ["お客様の入力期限は毎月20日。21〜25日はESキッチンが代理で追加・修正する。25日時点で報告がない拠点に事務手数料（3,000円・税抜。オプション OP000016）がかかる。",
                     "Hạn nhập của khách là ngày 20 hằng tháng. Ngày 21〜25 ESキッチン thêm / sửa thay. Chi nhánh chưa có báo cáo tại ngày 25 bị tính phí hành chính (3,000円 chưa thuế, option OP000016)."]},
         {"no": "3.6", "ja": "状態", "vi": "Trạng thái", "sel": "label.es-field__label::状態^", "kind": "label", "trig": "view",
          "init": ["未報告", "\"未報告\" (chưa báo cáo)"],
          "detail": ["バッジ：未報告（黄）／報告済（緑）／未報告（事務手数料あり）（赤・25日を過ぎても報告がない）／ご契約前（灰）／棚卸なし（休止中）（灰）／棚卸なし（灰）。棚卸一覧（CW_STOCK_002 No.36.5）と同じ。",
                     "Badge: 未報告 (vàng) / 報告済み (xanh) / 未報告（事務手数料あり） (đỏ, quá ngày 25 chưa báo cáo) / ご契約前 (xám) / 棚卸なし（休止中） (xám) / 棚卸なし (xám). Giống 棚卸一覧 (CW_STOCK_002 No.36.5)."]},
         {"no": "3.7", "ja": "報告日", "vi": "Ngày báo cáo", "sel": "label.es-field__label::報告日^", "kind": "label", "trig": "view",
          "init": ["—", "—"],
          "detail": ["最後の報告の日。", "Ngày của báo cáo cuối."]},
         {"no": "3.8", "ja": "報告者", "vi": "Người báo cáo", "sel": "label.es-field__label::報告者^", "kind": "label", "trig": "view",
          "init": ["—", "—"],
          "detail": ["報告した方の氏名と、使ったアカウント（法人アカウント／拠点アカウント）。ドライバーの報告は「ES配送便ドライバー」。",
                     "Họ tên người báo cáo và tài khoản đã dùng (法人アカウント / 拠点アカウント). Tài xế báo cáo thì \"ES配送便ドライバー\"."]},
         {"no": "3.9", "ja": "報告の方法", "vi": "Cách báo cáo", "sel": "label.es-field__label::報告の方法^", "kind": "label", "trig": "view",
          "init": ["企業担当者（法人Webの棚卸報告）", "企業担当者 (báo cáo kiểm kê trên 法人Web)"],
          "detail": ["企業担当者（法人Webの棚卸報告）／ES配送便ドライバー（ドライバーアプリ）／なし（休止中は棚卸報告をしません。休止の始めと再開のときに棚卸します）／棚卸報告なし（この拠点は棚卸報告をしません）。",
                     "企業担当者 (báo cáo trên 法人Web) / ES配送便ドライバー (app tài xế) / なし (tạm dừng không báo cáo; kiểm kê khi bắt đầu tạm dừng và khi mở lại) / 棚卸報告なし (chi nhánh không báo cáo kiểm kê)."]},
         {"no": "3.10", "ja": "状態の案内", "vi": "Thông báo theo trạng thái", "sel": ".es-inline strong::までに在庫を数えて^2", "kind": "label", "trig": "view",
          "err": ["I215", "S209", "E322", "I211", "I212", "I213", "I214", "W207"],
          "detail": ["拠点と月度の状態に合わせて1つ出す：今回・未報告＝I215／報告済＝S209／過去の月・未報告＝E322／ご契約前＝I211／休止中＝I212／ES配送便の拠点＝I213／棚卸なし＝I214。休止の前の最後のお届けの月は W207 も出す。この状態では I215。",
                     "Hiện 1 thông báo theo trạng thái của chi nhánh và tháng: tháng này chưa báo cáo = I215 / đã báo cáo = S209 / tháng trước chưa báo cáo = E322 / trước hợp đồng = I211 / tạm dừng = I212 / tài xế kiểm kê = I213 / không kiểm kê = I214. Tháng giao cuối trước tạm dừng hiện thêm W207. Trạng thái này là I215."]},
         {"no": "3.11", "ja": "棚卸の表", "vi": "Bảng kiểm kê", "sel": "table.sk-in", "kind": "table", "trig": "view", "pattern": "P-FORM",
          "detail": ["この拠点に関係する商品だけを出す（前回の棚卸にある・この締めで届けた・お届け中・廃棄する商品）。一覧にない商品は「商品を追加」（No.3.15）で足せる（前回の数 0・行の最後に足す）。行の並びは商品マスタの並び。入力できるのは 企業担当者が棚卸する拠点・今回の月度・未報告（または数え直し中）のときだけ。それ以外は「棚卸した数」として報告した数を表示だけする。商品が1つもない月度は「この月度に棚卸する商品はありません」を表の中に出す。ご契約前・休止中・棚卸なしの月度は表そのものを出さない。P-FORM と違うところ：保存の前に確認モーダル（No.10）を出す。保存のエラーはトーストに出す。",
                     "Chỉ hiện sản phẩm liên quan đến chi nhánh (có ở lần kiểm kê trước, đã giao trong kỳ này, đang giao, cần bỏ). Sản phẩm ngoài danh sách thêm được bằng \"商品を追加\" (No.3.15; lần trước = 0, thêm vào cuối bảng). Thứ tự dòng theo master sản phẩm. Chỉ nhập được khi: chi nhánh do người phụ trách công ty kiểm kê, tháng này, chưa báo cáo (hoặc đang đếm lại). Ngoài ra chỉ hiển thị số đã báo cáo ở cột \"棚卸した数\". Tháng không có sản phẩm nào thì hiện \"この月度に棚卸する商品はありません\" trong bảng. Tháng trước hợp đồng / tạm dừng / không kiểm kê thì không hiện bảng. Khác P-FORM: có modal xác nhận (No.10) trước khi lưu; lỗi khi lưu hiện bằng toast."]},
         {"no": "3.11.1", "ja": "商品", "vi": "Sản phẩm", "sel": "table.sk-in th::商品", "kind": "label", "trig": "view",
          "detail": ["商品名（商品マスタ）。。商品名（英語）も商品名の下に小さく出す（台帳 F「商品名（英語）」）", "Tên sản phẩm (master sản phẩm).. Tên tiếng Anh của sản phẩm cũng hiển thị dưới tên (chữ nhỏ) (台帳 F「商品名（英語）」)"]},
         {"no": "3.11.2", "ja": "前回の棚卸（{前の月度}）", "vi": "Lần kiểm kê trước ({tháng trước})", "sel": "table.sk-in th::前回の棚卸", "kind": "label", "trig": "view",
          "detail": ["前回の報告の「今ある数」（個）。前回の棚卸にない商品は「—」。「商品を追加」で足した商品は 0。", "\"今ある数\" của báo cáo trước (cái). Sản phẩm không có ở lần trước thì \"—\". Sản phẩm thêm bằng \"商品を追加\" là 0."]},
         {"no": "3.11.3", "ja": "お届け中", "vi": "Đang giao", "sel": "table.sk-in th::お届け中", "kind": "label", "trig": "view",
          "detail": ["出荷したがまだ納品していないお届けの数（基準日までのお届け分）。なければ「—」。", "Số lượng của đơn đã xuất kho nhưng chưa giao xong (giao đến ngày chuẩn). Không có thì \"—\"."]},
         {"no": "3.11.4", "ja": "廃棄する", "vi": "Cần bỏ", "sel": "table.sk-in th::廃棄する", "kind": "label", "trig": "view",
          "detail": ["代替品の設定で廃棄する数と、ES の期限を過ぎた見込みの数（「期限切れの見込み n個」）。どちらかがある行は色を付ける（No.32）。なければ「—」。",
                     "Số cần bỏ theo thiết lập hàng thay thế và số dự kiến quá hạn ES (\"期限切れの見込み n個\"). Dòng có một trong hai thì tô màu (No.32). Không có thì \"—\"."]},
         {"no": "3.11.5", "ja": "今ある数", "vi": "Số hiện có", "sel": "table.sk-in input[aria-label$=\"の今ある数\"]", "kind": "text", "trig": "input", "req": "○",
          "len": "整数 0〜999,999", "init": ["空（プレースホルダー「—」）", "Trống (placeholder \"—\")"],
          "ex": ["12", "Số nguyên 0〜999,999 (cái); sản phẩm không còn thì nhập 0"],
          "valid": ["必須（ない商品は 0）。数字だけ・0〜999,999（6桁。超えても切り詰めず E12）。全角の数字は半角に直し、数字以外は入力時に取り除く。今ある数＋捨てた数が前回の数＋届けた数（届いた数を含む）を超えると報告できない（E327。「商品を追加」で足した商品は対象外）",
                    "Bắt buộc (không còn thì 0). Chỉ số, 0〜999,999 (6 chữ số; vượt thì không cắt mà hiện E12). Số toàn góc đổi sang nửa góc; ký tự không phải số bị bỏ khi nhập. 今ある数 + 捨てた数 vượt quá 前回の数 + 届けた数 (gồm 届いた数) thì không báo cáo được (E327; sản phẩm thêm bằng \"商品を追加\" không áp dụng)"],
          "err": ["E01", "E12", "E320", "E327"],
          "detail": ["単位「個」を欄の右に出す。右寄せ。冷蔵庫・棚にある数を入れる（賞味期限切れで捨てた分は含めない）。空のまま「報告する」を押すと赤枠＋欄の下に E01（トースト E320 も出す）。999,999 を超えると欄の下に E12（No.8.1）。",
                     "Hiện đơn vị \"個\" bên phải ô. Căn phải. Nhập số trong tủ lạnh / kệ (không gồm số đã bỏ vì hết hạn). Để trống mà bấm \"報告する\" thì viền đỏ + E01 dưới ô (kèm toast E320). Vượt 999,999 thì E12 dưới ô (No.8.1)."]},
         {"no": "3.11.6", "ja": "捨てた数", "vi": "Số đã bỏ", "sel": "table.sk-in input[aria-label$=\"の捨てた数\"]", "kind": "text", "trig": "input", "req": "－",
          "len": "整数 0〜999,999", "init": ["空（プレースホルダー「0」）", "Trống (placeholder \"0\")"],
          "ex": ["2", "Số nguyên 0〜999,999 (cái) đã bỏ từ sau lần kiểm kê trước; trống = 0"],
          "valid": ["数字だけ・0〜999,999（超えても切り詰めず E12）。全角は半角に直す。空は 0", "Chỉ số, 0〜999,999 (vượt thì không cắt mà hiện E12). Toàn góc đổi sang nửa góc. Trống = 0"],
          "err": ["E12", "E327"],
          "detail": ["前回の棚卸のあとに捨てた数（廃棄する商品の分を入れる）。ESキッチンの計算上の在庫から引き、在庫差額にはしない。",
                     "Số đã bỏ sau lần kiểm kê trước (nhập cho sản phẩm cần bỏ). Trừ khỏi tồn kho tính toán của ESキッチン, không tính vào chênh lệch tồn kho."]},
         {"no": "3.11.7", "ja": "届いた数", "vi": "Số đã nhận", "sel": "table.sk-in th::届いた数", "kind": "text", "trig": "input", "req": "－",
          "len": "整数 0〜999,999", "init": ["空（プレースホルダー「0」）", "Trống (placeholder \"0\")"],
          "ex": ["5", "Số (cái) trong hàng đang giao đã đến nơi và đã tính vào 今ある数; trống = 0"],
          "cond": ["「お届け中」がある行だけ入力できる。ない行は「—」", "Chỉ nhập được ở dòng có \"お届け中\". Dòng không có thì \"—\""],
          "valid": ["数字だけ・0〜999,999（超えても切り詰めず E12）。お届け中の数まで", "Chỉ số, 0〜999,999 (vượt thì không cắt mà hiện E12). Không vượt quá số đang giao"],
          "err": ["E12", "E321"],
          "detail": ["お届け中の商品が届いていれば、その数を入れ、今ある数にも含める。お届け中の数を超えると E321。", "Nếu hàng đang giao đã đến, nhập số đó và cộng vào 今ある数. Vượt quá số đang giao thì E321."]},
         {"no": "3.12", "ja": "クリア", "vi": "Nút \"クリア\"", "sel": "button::クリア", "kind": "button", "trig": "click",
          "cond": ["入力できるときだけ出す", "Chỉ hiện khi nhập được"],
          "detail": ["この拠点・月度の入力中の数をすべて消す（確認なし。保存はしていないため）。", "Xóa toàn bộ số đang nhập của chi nhánh / tháng này (không hỏi, vì chưa lưu)."]},
         {"no": "3.13", "ja": "報告する", "vi": "Nút \"報告する\"", "sel": ".rv-skact button::報告する", "kind": "button", "trig": "click",
          "cond": ["入力できるときだけ出す（企業担当者が棚卸する拠点・今回の月度・ご契約の開始より後・休止中でない・未報告か数え直し中）。解約後（参照のみ）のアカウントでも出す", "Chỉ hiện khi nhập được (chi nhánh do người phụ trách công ty kiểm kê, tháng này, không trước ngày bắt đầu hợp đồng, không tạm dừng, chưa báo cáo hoặc đang đếm lại). Tài khoản sau hủy hợp đồng (chỉ xem) vẫn hiện"],
          "err": ["E01", "E12", "E320", "E321", "E327", "E323", "Q207"],
          "detail": ["入力をまとめて確かめ（今ある数が空＝欄の下に E01＋トースト E320、999,999 を超える＝欄の下に E12、届いた数がお届け中を超える＝E321、今ある数＋捨てた数が前回の数＋届けた数を超える＝E327、商品がない＝E323。エラーの欄があれば最初の欄まで画面を動かして焦点を移す）、問題がなければ報告の確認モーダル（No.10）を開く。スマホ幅ではクリアと一緒に画面の下に固定する。入力を残したまま別の画面へ移ると Q02。",
                     "Kiểm tra cả bảng (今ある数 trống = E01 dưới ô + toast E320, vượt 999,999 = E12 dưới ô, 届いた数 vượt đang giao = E321, 今ある数 + 捨てた数 vượt 前回の数 + 届けた数 = E327, không có sản phẩm = E323); có ô lỗi thì cuộn tới ô đầu tiên và đặt focus vào đó; không lỗi thì mở modal xác nhận (No.10). Trên điện thoại, cố định cùng \"クリア\" ở đáy màn hình. Rời sang màn khác khi còn số đang nhập thì Q02."],
          "demo_ok": _DEMO_RO},
         {"no": "3.14", "ja": "在庫差額の説明", "vi": "Giải thích chênh lệch tồn kho", "sel": "p.note::数えるのは", "kind": "label", "trig": "view",
          "detail": ["数えるのは冷蔵庫・棚にある商品（賞味期限切れで捨てた分は含めない）。報告した数と、ESキッチンが計算した在庫（前回の棚卸＋お届け−販売−廃棄）との差が在庫差額。許容範囲を超えた在庫差額はご利用実績の精算として請求書に載る（例：計算上10個・報告8個 → 差2個）。",
                     "Đếm sản phẩm trong tủ lạnh / kệ (không gồm đã bỏ vì hết hạn). Chênh lệch giữa số báo cáo và tồn kho ESキッチン tính (lần trước + giao − bán − bỏ) là chênh lệch tồn kho. Vượt mức cho phép thì đưa vào hóa đơn ở phần thanh toán thực tế (ví dụ: tính 10, báo 8 → chênh 2)."],
          "open": ["在庫差額の許容範囲（免責の数・プランごと）を案内に出すか、出すなら値", "Có ghi mức cho phép của chênh lệch tồn kho (miễn trừ theo gói) vào thông báo không, nếu có thì giá trị"],
          "ask": "お客様（営業）"},
         {"no": "3.15", "ja": "商品を追加", "vi": "Nút \"商品を追加\"", "sel": "button::商品を追加", "kind": "button", "trig": "click",
          "cond": ["入力できるときだけ出す（No.3.13 と同じ条件）", "Chỉ hiện khi nhập được (cùng điều kiện với No.3.13)"],
          "detail": ["棚卸の表の下（クリアの左）。一覧にない商品を表に足すモーダル（No.41）を開く：スマホはカメラで JAN コードを読み取る、PC は JAN コードの入力か商品名の検索。足した商品は表の最後に前回の数 0 で入る（No.42）。",
                     "Dưới bảng kiểm kê (bên trái \"クリア\"). Mở modal thêm sản phẩm ngoài danh sách (No.41): điện thoại quét mã JAN bằng camera, PC nhập mã JAN hoặc tìm theo tên. Sản phẩm thêm vào cuối bảng với số lần trước = 0 (No.42)."]},
     ]},
    # ------------------------------------------------------------ 002 拠点アカウント
    {"id": "002", "code": "CW_STOCK_001", "state": ["拠点アカウント", "Tài khoản chi nhánh"],
     "url": "/corp/stock/CU00961/2026-10", "full": True, "login": "CU00961", "wait": 600, "setup": "",
     "note": ["拠点アカウント（CU00961 千葉営業所）で開いた状態。自分の拠点だけ見える。拠点の選択（No.3.1）は出ない。報告した方の候補（No.10.4）はこの拠点のご担当者だけ。",
              "Mở bằng tài khoản chi nhánh (CU00961 千葉営業所). Chỉ thấy chi nhánh của mình. Không hiện chọn chi nhánh (No.3.1). Ứng viên người báo cáo (No.10.4) chỉ gồm người phụ trách của chi nhánh này."],
     "items": [
         {"no": "4", "ja": "拠点名・権限（拠点アカウント）", "vi": "Tên chi nhánh, quyền (tài khoản chi nhánh)", "sel": ".es-pagehead .stat", "kind": "label", "trig": "view",
          "init": ["株式会社サンプル　権限 拠点アカウント（この拠点だけ）", "株式会社サンプル, quyền: tài khoản chi nhánh (chỉ chi nhánh này)"],
          "detail": ["拠点アカウントは見られる範囲が「この拠点だけ」。", "Tài khoản chi nhánh chỉ xem được \"chi nhánh này\"."]},
     ]},
    # ------------------------------------------------------------ 003 入力中
    {"id": "003", "code": "CW_STOCK_001", "state": ["入力中（企業担当者・今回）", "Đang nhập (người phụ trách công ty, tháng này)"],
     "url": "/corp/stock/CU00961/2026-10", "full": True, "wait": 600,
     "setup": _JS_FILL % "String(i+3)",
     "note": ["千葉営業所の今回の月度で、今ある数を入れている途中。", "Đang nhập 今ある数 cho tháng này của 千葉営業所."],
     "items": [
         {"no": "6", "ja": "入力中の数", "vi": "Số đang nhập", "sel": "table.sk-in input[aria-label$=\"の今ある数\"]", "kind": "label", "trig": "view",
          "detail": ["入力した数は拠点・月度ごとにブラウザの中に残す（拠点や月を切り替えても消えない。再読み込みで消える）。全角の数字は入力時に半角に直す。",
                     "Số đã nhập được giữ trong trình duyệt theo chi nhánh / tháng (đổi chi nhánh hay tháng không mất; tải lại trang thì mất). Số toàn góc đổi sang nửa góc ngay khi nhập."]},
         {"no": "7", "ja": "操作ボタン（スマホでは画面の下に固定）", "vi": "Nút thao tác (điện thoại: cố định ở đáy)", "sel": ".rv-skact", "kind": "area", "trig": "view",
          "detail": ["クリアと報告する。スマホ幅では画面の下に固定して、表が長くても押せるようにする。固定している間は、AIチャットの丸ボタン（と開いた枠）を固定バーの上へ上げ、「報告する」と重ならないようにする（隠さない。UI/UX レビュー #5）。", "\"クリア\" và \"報告する\". Trên điện thoại cố định ở đáy để bảng dài vẫn bấm được. Khi đang cố định, nút tròn AI chat (và khung chat khi mở) được nâng lên phía trên thanh để không đè \"報告する\" (không ẩn; UI/UX レビュー #5)."]},
     ]},
    # ------------------------------------------------------------ 004 入力エラー
    {"id": "004", "code": "CW_STOCK_001", "state": ["入力エラー", "Lỗi nhập liệu"],
     "url": "/corp/stock/CU00961/2026-10", "full": True, "wait": 300,
     "setup": _JS_CLICK_FILE,
     "note": ["今ある数が空のまま「報告する」を押した状態。空の欄が赤枠になり、欄の下に E01、トースト E320 も出る。", "Bấm \"報告する\" khi 今ある数 còn trống. Ô trống viền đỏ, hiện E01 dưới ô và toast E320."],
     "items": [
         {"no": "8", "ja": "エラーの欄（赤枠）", "vi": "Ô lỗi (viền đỏ)", "sel": ".es-input--error", "kind": "label", "trig": "view",
          "detail": ["今ある数が空の欄をすべて赤枠にし、aria-invalid を付ける。数を入れると枠が戻る。999,999 を超えた欄も赤枠にする。", "Mọi ô 今ある数 trống đều viền đỏ và có aria-invalid. Nhập số thì hết viền đỏ. Ô vượt 999,999 cũng viền đỏ."]},
         {"no": "8.1", "ja": "欄の下のエラー", "vi": "Lỗi dưới ô nhập", "sel": ".sk-fld .es-field__msg--error", "kind": "label", "trig": "view", "err": ["E01", "E12"],
          "detail": ["空の今ある数＝E01「今ある数をご入力ください。」。今ある数・捨てた数・届いた数が 999,999 を超える＝E12「{項目名}は0〜999,999の範囲でご入力ください。」。欄の aria-describedby がこの文言を指す。報告するを押すと最初のエラー欄へ画面を動かして焦点を移す。",
                     "Ô 今ある数 trống = E01. Ô vượt 999,999 = E12. aria-describedby của ô trỏ tới dòng này. Khi bấm 報告する thì cuộn và đặt focus vào ô lỗi đầu tiên."]},
         {"no": "9", "ja": "エラーのトースト", "vi": "Toast lỗi", "sel": ".hd-toast", "kind": "toast", "trig": "show", "err": ["E320", "E321", "E323"],
          "detail": ["画面の下に約2.6秒出す。欄の下のエラー（No.8.1）の補助で、消えても欄にエラーが残る。", "Hiện ở đáy màn hình khoảng 2,6 giây. Chỉ bổ trợ cho lỗi dưới ô (No.8.1); toast mất thì lỗi vẫn còn ở ô."]},
     ]},
    # ------------------------------------------------------------ 005 報告の確認モーダル
    {"id": "005", "code": "CW_STOCK_001", "state": ["報告の確認モーダル", "Modal xác nhận báo cáo"],
     "url": "/corp/stock/CU00961/2026-10", "full": True, "wait": 500,
     "setup": _JS_FILL % "\"0\"" + _JS_CLICK_FILE,
     "note": ["すべての今ある数を入れて「報告する」を押した状態。拠点・月度・報告する商品の件数と、報告した方（既定＝この拠点のメイン担当者）だけの簡単なモーダル（版 1.1）。", "Đã nhập đủ 今ある数 và bấm \"報告する\". Modal đơn giản (bản 1.1): chi nhánh, tháng, số sản phẩm và người báo cáo (mặc định = メイン担当者 của chi nhánh)."],
     "items": [
         {"no": "10", "ja": "報告の確認モーダル", "vi": "Modal xác nhận báo cáo", "sel": ".es-dialog__panel", "kind": "modal", "trig": "show", "err": ["Q207"],
          "detail": ["タイトル「棚卸を報告しますか？」（Q207）。幅 560px。中身は 拠点・月度・報告する商品の件数（No.10.1）と報告した方（No.10.3〜10.5）だけ。商品ごとの数の一覧は出さない。外側を押すか × か Esc で閉じる（入力は残る）。", "Tiêu đề \"棚卸を報告しますか？\" (Q207). Rộng 560px. Chỉ gồm chi nhánh, tháng, số sản phẩm (No.10.1) và người báo cáo (No.10.3〜10.5). Không hiện danh sách số theo sản phẩm. Bấm ngoài, × hoặc Esc để đóng (số đã nhập vẫn còn)."]},
         {"no": "10.1", "ja": "拠点・月度・報告する商品の件数", "vi": "Chi nhánh, tháng, số sản phẩm báo cáo", "sel": ".cb-mh::報告期限", "kind": "label", "trig": "view",
          "init": ["株式会社サンプル 千葉営業所・2026-10（報告期限 2026-10-20）／報告する商品 12件", "株式会社サンプル 千葉営業所・2026-10 (hạn 2026-10-20) / 12 sản phẩm"],
          "detail": ["件数は棚卸の表の行数（「商品を追加」で足した行を含む）。", "Số sản phẩm = số dòng của bảng kiểm kê (gồm dòng thêm bằng \"商品を追加\")."]},
         {"no": "10.3", "ja": "報告した方", "vi": "Người báo cáo", "sel": ".cb-mh::報告した方", "kind": "label", "trig": "view",
          "detail": ["必須（*）。No.10.4 のプルダウンで1人。", "Bắt buộc (*). Chọn 1 người ở dropdown No.10.4."]},
         {"no": "10.4", "ja": "報告した方の選択", "vi": "Chọn người báo cáo", "sel": "#sk-who", "kind": "select", "trig": "select", "req": "○", "len": ["選択（1人）", "Chọn (1 người)"],
          "init": ["この拠点のメイン担当者（メイン担当者がない拠点は未選択）", "メイン担当者 của chi nhánh này (chi nhánh không có メイン担当者 thì chưa chọn)"],
          "ex": ["木下 翼（千葉営業所・メイン担当者）", "Chọn 1 người phụ trách đã đăng ký; hiển thị \"{担当者名}（{所属}・{区分}）\", giá trị là email (không có email thì tên)"],
          "valid": ["必須。未選択で「報告する」を押すと E02（項目名＝報告した方）", "Bắt buộc. Chưa chọn mà bấm \"報告する\" thì E02 (項目名 = 報告した方)"],
          "err": ["E02"],
          "detail": ["プルダウン。候補は登録済みのご担当者：法人アカウント＝法人のご担当者＋この拠点のご担当者／拠点アカウント＝この拠点のご担当者。表示は「{担当者名}（{所属：法人／拠点名}・{区分}）」、この拠点のメイン担当者を先頭にして既定で選ぶ。選んだ方の氏名を報告の記録に残し、運営Web にも出す（受付簿 No.44）。",
                     "Dropdown. Ứng viên là người phụ trách đã đăng ký: tài khoản pháp nhân = người phụ trách của pháp nhân + của chi nhánh này / tài khoản chi nhánh = của chi nhánh này. Hiển thị \"{担当者名}（{所属: pháp nhân / tên chi nhánh}・{区分}）\", メイン担当者 của chi nhánh đứng đầu và được chọn sẵn. Họ tên người đã chọn lưu vào bản ghi báo cáo và hiện ở 運営Web (受付簿 No.44)."]},
         {"no": "10.5", "ja": "報告した方の注記", "vi": "Ghi chú về người báo cáo", "sel": ".es-dialog p.note", "kind": "label", "trig": "view",
          "detail": ["「ログインは{法人アカウント／拠点アカウント}（共有）なので、報告した方をご確認ください（違う方なら選び直してください）。報告の記録に残り、ESキッチンからのご連絡はこの方へお送りします。」",
                     "\"ログインは{法人アカウント／拠点アカウント}（共有）なので、報告した方をご確認ください（違う方なら選び直してください）。報告の記録に残り、ESキッチンからのご連絡はこの方へお送りします。\""]},
         {"no": "10.6", "ja": "キャンセル", "vi": "Nút \"キャンセル\"", "sel": ".es-dialog__foot button::キャンセル", "kind": "button", "trig": "click",
          "detail": ["モーダルを閉じる。入力した数は残る。", "Đóng modal. Số đã nhập vẫn còn."]},
         {"no": "10.7", "ja": "報告する（確定）", "vi": "Nút \"報告する\" (xác nhận)", "sel": ".es-dialog__foot button::報告する", "kind": "button", "trig": "click",
          "err": ["E02", "S208", "E30", "E324", "E326", "E327"],
          "detail": ["報告した方が未選択なら E02。報告を保存し（サーバー側でも 月度が今回か・この拠点が法人Web で報告する拠点か・運営が確認済みでないか・数の範囲 を確かめる）、モーダルを閉じて S208。入力中の数は消し、状態を「報告済」にする。押したら二重送信を防ぐために無効にする。",
                     "Chưa chọn người báo cáo thì E02. Lưu báo cáo (server cũng kiểm tra: tháng này không, chi nhánh báo cáo trên 法人Web không, 運営 đã xác nhận chưa, phạm vi số), đóng modal và hiện S208. Xóa số đang nhập, trạng thái thành \"報告済み\". Khóa nút sau khi bấm để tránh gửi 2 lần."]},
         {"no": "10.8", "ja": "閉じる（×）", "vi": "Đóng (×)", "sel": ".es-dialog__close", "kind": "button", "trig": "click",
          "detail": ["キャンセルと同じ。", "Giống \"キャンセル\"."]},
         {"no": "10.9", "ja": "キーボードと焦点", "vi": "Bàn phím và focus", "sel": ".es-dialog__panel[role=\"dialog\"]", "kind": "label", "trig": "view",
          "detail": ["開いたら焦点を最初の入力欄（報告した方）へ移す。Esc＝キャンセル（No.10.6）。Tab・Shift+Tab はモーダルの中で循環し、背後の画面へ出ない。閉じたら焦点を「報告する」ボタン（開いたボタン）へ戻す。全サイト共通の動き（ダイアログ共通）。",
                     "Khi mở, focus chuyển vào ô nhập đầu tiên (報告した方). Esc = キャンセル (No.10.6). Tab / Shift+Tab xoay vòng trong modal, không ra màn hình phía sau. Khi đóng, focus trả về nút \"報告する\" đã mở. Hành vi chung cho mọi dialog của hệ thống."]},
     ]},
    # ------------------------------------------------------------ 007 報告した方 未選択
    {"id": "007", "code": "CW_STOCK_001", "state": ["報告した方 未選択", "Chưa chọn người báo cáo"],
     "url": "/corp/stock/CU00961/2026-10", "full": True, "wait": 400,
     "setup": _JS_FILL % "\"0\"" + _JS_CLICK_FILE + _JS_CLEAR_WHO + _JS_MODAL_OK,
     "note": ["報告した方が未選択のままモーダルの「報告する」を押した状態（メイン担当者がない拠点だけ起きる。既定で選ばれていれば起きない。撮影のときは選択を外す）。プルダウンの下に E02 を出す。", "Bấm \"報告する\" trong modal khi chưa chọn người báo cáo (chỉ xảy ra với chi nhánh không có メイン担当者; có chọn sẵn thì không xảy ra; khi chụp thì bỏ chọn). Hiện E02 dưới dropdown."],
     "items": [
         {"no": "13", "ja": "未選択のエラー", "vi": "Lỗi chưa chọn", "sel": ".es-dialog .es-field__msg--error", "kind": "label", "trig": "show", "err": ["E02"],
          "detail": ["項目名＝報告した方。メイン担当者がない拠点で、選ばずに押したときだけ。選ぶと消える。", "項目名 = 報告した方. Chỉ khi chi nhánh không có メイン担当者 và bấm mà chưa chọn. Chọn xong thì mất."]},
     ]},
    # ------------------------------------------------------------ 008 報告済み
    {"id": "008", "code": "CW_STOCK_001", "state": ["報告済（数え直せる）", "Đã báo cáo (có thể đếm lại)"],
     "url": "/corp/stock/CU00961/2026-10", "full": True, "wait": 600,
     "setup": _JS_FILL % "\"0\"" + _JS_CLICK_FILE + _JS_MODAL_OK,
     "note": ["報告した方を選んで報告した直後。緑の案内（S209）と「数え直して報告し直す」、表は報告した数の表示だけ。※この状態を撮ると見本データに千葉営業所 2026-10 の報告が残る（以後の千葉の状態は報告済みになる）。",
              "Ngay sau khi chọn người báo cáo và báo cáo. Thông báo xanh (S209), nút \"数え直して報告し直す\", bảng chỉ hiển thị số đã báo cáo. ※Chụp trạng thái này sẽ lưu báo cáo 2026-10 của 千葉営業所 vào dữ liệu mẫu (các trạng thái sau của 千葉 thành đã báo cáo)."],
     "items": [
         {"no": "14", "ja": "報告済みの案内", "vi": "Thông báo đã báo cáo", "sel": ".es-inline--success", "kind": "label", "trig": "view", "err": ["S209"],
          "detail": ["S209。タイトルに報告日と報告した方。今回の月度（報告期限前）のときだけ本文の後半と No.14.1 を出す。", "S209. Tiêu đề có ngày báo cáo và người báo cáo. Chỉ tháng này (trước hạn) mới hiện nửa sau nội dung và No.14.1."]},
         {"no": "14.1", "ja": "数え直して報告し直す", "vi": "Nút \"数え直して報告し直す\"", "sel": "button::数え直して報告し直す", "kind": "button", "trig": "click",
          "cond": ["今回の月度・報告期限前・報告済み・運営が確認済みでないとき", "Tháng này, trước hạn, đã báo cáo, 運営 chưa xác nhận"],
          "detail": ["表を入力できる状態に戻す（No.17）。報告期限までは何度でも報告し直せ、最後の報告が有効。運営が確認済みにした報告は直せない（ボタンを出さず、案内の中に E326 の文言「ESキッチンが確認済みのため、報告し直すことはできません。」を出す。押せた場合は E326 のトースト）。",
                     "Đưa bảng về trạng thái nhập được (No.17). Đến hạn có thể báo cáo lại nhiều lần, báo cáo cuối có hiệu lực. Báo cáo 運営 đã xác nhận thì không sửa được (không hiện nút mà hiện câu E326 \"ESキッチンが確認済みのため、報告し直すことはできません。\" trong thông báo; nếu bấm được thì toast E326)."],
          "demo_ok": ["この状態（今回の月度で運営が確認済みの報告）の画像はない。確認済みにするのは運営Web の操作で、見本データの今回の月度には確認済みの報告がない。動きはコード対応済み（受付簿 No.157）",
                      "Không có ảnh cho trạng thái này (báo cáo tháng này đã được 運営 xác nhận): xác nhận là thao tác trên 運営Web, dữ liệu mẫu tháng này không có báo cáo đã xác nhận. Hành vi đã có trong code (受付簿 No.157)"]},
         {"no": "15", "ja": "報告した数の表示", "vi": "Hiển thị số đã báo cáo", "sel": "table.sk-in th::棚卸した数", "kind": "label", "trig": "view",
          "detail": ["列名が「棚卸した数」になり、今ある数・捨てた数・届いた数を「n個」で表示だけする。", "Tên cột thành \"棚卸した数\"; chỉ hiển thị 今ある数・捨てた数・届いた数 dạng \"n個\"."]},
         {"no": "16", "ja": "報告日・報告者", "vi": "Ngày báo cáo, người báo cáo", "sel": "label.es-field__label::報告者^", "kind": "label", "trig": "view",
          "init": ["木下 翼（法人アカウント）", "木下 翼 (tài khoản pháp nhân)"],
          "detail": ["報告した方の氏名と使ったアカウント。棚卸一覧（CW_STOCK_002 No.36）の行も 報告済み・報告日・報告者に変わる。", "Họ tên người báo cáo và tài khoản đã dùng. Dòng ở 棚卸一覧 (CW_STOCK_002 No.36) cũng đổi thành 報告済み với ngày và người báo cáo."]},
     ]},
    # ------------------------------------------------------------ 009 数え直し
    {"id": "009", "code": "CW_STOCK_001", "state": ["数え直し", "Đếm lại"],
     "url": "/corp/stock/CU00961/2026-10", "full": True, "wait": 500,
     "setup": "const rb=[...document.querySelectorAll('button')].find(b=>b.textContent.includes('数え直して報告し直す')); rb&&rb.click(); await new Promise(r=>setTimeout(r,400)); ",
     "note": ["報告済みの月度で「数え直して報告し直す」を押した状態。入力欄が戻り、クリア・報告するが出る。", "Bấm \"数え直して報告し直す\" ở tháng đã báo cáo. Ô nhập trở lại, hiện \"クリア\" và \"報告する\"."],
     "items": [
         {"no": "17", "ja": "数え直しの入力欄", "vi": "Ô nhập khi đếm lại", "sel": "table.sk-in input[aria-label$=\"の今ある数\"]", "kind": "label", "trig": "view",
          "detail": ["前回の報告の数は入れない（空から入れ直す）。報告すると前の報告を置き換える（最後の報告が有効）。拠点や月を変えると数え直しをやめる。",
                     "Không điền sẵn số của báo cáo trước (nhập lại từ trống). Báo cáo sẽ thay thế báo cáo trước (báo cáo cuối có hiệu lực). Đổi chi nhánh hay tháng thì thoát đếm lại."]},
     ]},
    # ------------------------------------------------------------ 010 ドライバーが棚卸する拠点
    {"id": "010", "code": "CW_STOCK_001", "state": ["ES配送便の拠点（ドライバーの報告を表示・法人も入力できる）", "Chi nhánh ES配送便 (hiện báo cáo của tài xế, pháp nhân cũng nhập được)"],
     "url": "/corp/stock/CU00871/2026-10", "full": True, "wait": 600, "setup": "",
     "note": ["ES配送便の拠点（大阪支店）。ドライバーがアプリで報告するが、法人・拠点も最終確認のために入力できる（最後の報告が有効。hong 2026-10-05 B-21）。", "Chi nhánh ES配送便 (大阪支店). Tài xế báo cáo từ app, nhưng pháp nhân/chi nhánh cũng nhập được để kiểm tra cuối (báo cáo sau cùng có hiệu lực, hong 2026-10-05 B-21)."],
     "items": [
         {"no": "18", "ja": "ドライバーも報告する案内", "vi": "Thông báo tài xế cũng báo cáo", "sel": ".es-inline strong::ドライバーも棚卸を報告します^2", "kind": "label", "trig": "view", "err": ["I213"],
          "detail": ["I213。ドライバーの報告があれば数を表示し、法人・拠点はそのまま、または数え直して報告し直せる（入力欄は No.3 と同じ）。報告の方法は最後に報告した方（企業担当者／ES配送便ドライバー）。報告期限（20日）までは最後の報告が有効、21日以降は運営（hong 2026-10-05 B-21）", "I213. Có báo cáo của tài xế thì hiện số; pháp nhân/chi nhánh có thể giữ nguyên hoặc đếm lại và báo cáo lại (ô nhập như No.3). Cách báo cáo = người báo cáo sau cùng (企業担当者／ES配送便ドライバー). Đến hạn (20日) báo cáo sau cùng có hiệu lực, từ 21日 là 運営 (hong 2026-10-05 B-21)"]},
         {"no": "19", "ja": "表（参照のみ）", "vi": "Bảng (chỉ xem)", "sel": "table.sk-in", "kind": "label", "trig": "view",
          "detail": ["入力欄・クリア・報告するは出さない。ドライバーが報告した数を「棚卸した数」として表示する。報告前は「—」。", "Không hiện ô nhập, \"クリア\", \"報告する\". Hiển thị số tài xế đã báo cáo ở \"棚卸した数\". Trước khi báo cáo thì \"—\"."]},
     ]},
    # ------------------------------------------------------------ 011 過去の月 報告済み
    {"id": "011", "code": "CW_STOCK_001", "state": ["過去の月 報告済", "Tháng trước, đã báo cáo"],
     "url": "/corp/stock/CU00961/2026-09", "full": True, "wait": 600, "setup": "",
     "note": ["千葉営業所の前の月度（2026-09・報告済み・運営が確認済み）。見るだけ。", "Tháng trước của 千葉営業所 (2026-09, đã báo cáo, 運営 đã xác nhận). Chỉ xem."],
     "items": [
         {"no": "20", "ja": "過去の月の報告済みの案内", "vi": "Thông báo đã báo cáo (tháng trước)", "sel": ".es-inline--success", "kind": "label", "trig": "view", "err": ["S209"],
          "detail": ["S209 の前半だけ（報告し直しの案内と No.14.1 は出さない）。", "Chỉ nửa đầu của S209 (không hiện phần báo cáo lại và No.14.1)."]},
     ]},
    # ------------------------------------------------------------ 012 過去の月 未報告
    {"id": "012", "code": "CW_STOCK_001", "state": ["過去の月 未報告（事務手数料）", "Tháng trước, chưa báo cáo (phí hành chính)"],
     "url": "/corp/stock/CU00950/2026-09", "full": True, "wait": 600, "setup": "",
     "note": ["報告期限（25日）を過ぎても報告がなかった月度。赤の案内（E322）と状態「未報告（事務手数料あり）」。見本データの横浜営業所は 2026-09 の棚卸報告を25日までにしなかった拠点（共通データの見本に報告の記録を入れていない：受付簿 No.157）。",
              "Tháng đã quá hạn (ngày 25) mà không có báo cáo. Thông báo đỏ (E322) và trạng thái \"未報告（事務手数料あり）\". Trong dữ liệu mẫu, 横浜営業所 là chi nhánh không báo cáo kiểm kê 2026-09 đến ngày 25 (không có bản ghi báo cáo trong dữ liệu chung: 受付簿 No.157)."],
     "items": [
         {"no": "22", "ja": "未報告の案内", "vi": "Thông báo chưa báo cáo", "sel": ".es-inline--negative", "kind": "label", "trig": "view", "err": ["E322"],
          "detail": ["E322。事務手数料（3,000円・税抜）はオプション OP000016 の金額。数はESキッチンが確認して入力する。", "E322. Phí hành chính (3,000円 chưa thuế) là số tiền của option OP000016. ESキッチン kiểm tra và nhập số."]},
     ]},
    # ------------------------------------------------------------ 013 ご契約前
    {"id": "013", "code": "CW_STOCK_001", "state": ["ご契約前", "Trước khi hợp đồng bắt đầu"],
     "url": "/corp/stock/CU00975/2026-09", "full": True, "login": "CU00071", "wait": 600, "setup": "",
     "note": ["お試しの法人（CU00071 みちのく商事・仙台本社は 2026-10 から）で、ご契約の前の月度（2026-09）を選んだ状態。", "Pháp nhân dùng thử (CU00071 みちのく商事, 仙台本社 từ 2026-10) chọn tháng trước khi hợp đồng bắt đầu (2026-09)."],
     "items": [
         {"no": "23", "ja": "ご契約前の案内", "vi": "Thông báo trước hợp đồng", "sel": ".es-inline strong::ご契約の前の月です^2", "kind": "label", "trig": "view", "err": ["I211"],
          "detail": ["I211（{年月}＝親契約の開始サイクル月）。状態は「ご契約前」（灰）。報告する表と「棚卸用の表（PDF）」は出さない（入力もできない）。", "I211 ({年月} = tháng bắt đầu của hợp đồng mẹ). Trạng thái \"ご契約前\" (xám). Không hiện bảng kiểm kê và nút \"棚卸用の表（PDF）\" (không nhập được)."]},
     ]},
    # ------------------------------------------------------------ 014 休止中
    {"id": "014", "code": "CW_STOCK_001", "state": ["休止中", "Đang tạm dừng"],
     "url": "/corp/stock/CU00902/2026-10", "full": True, "today": "2026/10/13", "wait": 600, "setup": "",
     "note": ["名古屋営業所（2026-10 サイクルから休止）。デモの今日を 2026/10/13 にして、日次バッチ（10/12）で休止中になった状態。", "名古屋営業所 (tạm dừng từ chu kỳ 2026-10). Đặt ngày demo 2026/10/13 để batch ngày (10/12) đã chuyển sang tạm dừng."],
     "items": [
         {"no": "24", "ja": "休止中の案内", "vi": "Thông báo đang tạm dừng", "sel": ".es-inline strong::休止中は^2", "kind": "label", "trig": "view", "err": ["I212"],
          "detail": ["I212。状態は「棚卸なし（休止中）」（灰）、報告の方法は「なし（休止中は棚卸報告をしません…）」。棚卸一覧の行（CW_STOCK_002 No.36）は 配送の方法「—」・状態「棚卸なし（休止中）」・報告の方法「なし」。報告する表と「棚卸用の表（PDF）」は出さない。設備を置いたままの拠点では休止中も社員の方がアプリで購入でき、その差は再開（または解約）のときの棚卸で精算する。",
                     "I212. Trạng thái \"棚卸なし（休止中）\" (xám), cách báo cáo \"なし（休止中は…）\". Dòng ở 棚卸一覧 (CW_STOCK_002 No.36): 配送の方法 \"—\", 状態 \"棚卸なし（休止中）\", 報告の方法 \"なし\". Không hiện bảng kiểm kê và nút \"棚卸用の表（PDF）\". Chi nhánh giữ thiết bị thì nhân viên vẫn mua được trên app trong thời gian tạm dừng; chênh lệch thanh toán khi mở lại (hoặc hủy)."]},
     ]},
    # ------------------------------------------------------------ 015 休止の始めの棚卸報告
    {"id": "015", "code": "CW_STOCK_001", "state": ["休止の始めの棚卸報告", "Báo cáo kiểm kê khi bắt đầu tạm dừng"],
     "url": "/corp/stock/CU00902/2026-09", "full": True, "wait": 600, "setup": "",
     "note": ["名古屋営業所（ES配送便）の 2026-09＝休止の前の最後のお届けの月。ES配送便の拠点でもお客様が報告するので、棚卸する人は「企業担当者」になり W207 を出す。", "2026-09 của 名古屋営業所 (ES配送便) = tháng giao cuối trước khi tạm dừng. Chi nhánh ES配送便 vẫn do khách báo cáo nên 棚卸する人 thành \"企業担当者\" và hiện W207."],
     "items": [
         {"no": "26", "ja": "休止の始めの案内", "vi": "Thông báo bắt đầu tạm dừng", "sel": ".es-inline strong::休止の始めの^2", "kind": "label", "trig": "view", "err": ["W207"],
          "detail": ["W207。この月度だけ ES配送便の拠点も入力できる（今回の月度なら）。この分までのご利用実績を精算する。", "W207. Chỉ tháng này chi nhánh ES配送便 cũng nhập được (nếu là tháng hiện tại). Thanh toán thực tế đến thời điểm này."]},
         {"no": "27", "ja": "報告の方法（休止の始め）", "vi": "Cách báo cáo (bắt đầu tạm dừng)", "sel": "label.es-field__label::報告の方法^", "kind": "label", "trig": "view",
          "init": ["企業担当者（法人Webの棚卸報告）", "企業担当者 (báo cáo trên 法人Web)"],
          "detail": ["ドライバーが報告済みの月度なら、報告者は「ES配送便ドライバー」のまま表示する。", "Nếu tháng này tài xế đã báo cáo thì người báo cáo vẫn hiện \"ES配送便ドライバー\"."]},
     ]},
    # ------------------------------------------------------------ 016 棚卸なし
    {"id": "016", "code": "CW_STOCK_001", "state": ["棚卸なし", "Không kiểm kê"],
     "url": "/corp/stock/CU00961/2026-10", "full": True, "wait": 600, "setup": "",
     "note": ["運営Web で拠点の棚卸報告を「なし」にした拠点（noStockCheck）。案内 I214 だけで、表と入力欄は出さない。見本データにこの設定の拠点がないため、画像は通常の拠点の画面になる（撮影のときは運営Web で拠点詳細の棚卸報告を「なし」にする）。",
              "Chi nhánh được 運営Web đặt báo cáo kiểm kê = \"なし\" (noStockCheck). Chỉ hiện I214, không hiện bảng và ô nhập. Dữ liệu mẫu không có chi nhánh như vậy nên ảnh sẽ là màn hình chi nhánh bình thường (khi chụp cần đặt 棚卸報告 = なし ở chi tiết chi nhánh trên 運営Web)."],
     "items": [
         {"no": "28", "ja": "棚卸なしの案内", "vi": "Thông báo không kiểm kê", "sel": "h2::の棚卸報告^2", "kind": "label", "trig": "view", "err": ["I214"],
          "detail": ["I214。運営Web の拠点詳細で棚卸報告を「なし」にした拠点。状態は「棚卸なし」（灰）、報告の方法「棚卸報告なし」。表・入力欄・棚卸用の表（PDF）・商品を追加は出さない。CSV の棚卸する人は「なし（棚卸なし）」。「在庫点検」という語はどこにも出さない。",
                     "I214. Chi nhánh được đặt báo cáo kiểm kê = \"なし\" ở chi tiết chi nhánh trên 運営Web. Trạng thái \"棚卸なし\" (xám), cách báo cáo \"棚卸報告なし\". Không hiện bảng, ô nhập, 棚卸用の表（PDF）, 商品を追加. Cột 棚卸する人 trong CSV là \"なし（棚卸なし）\". Không dùng từ \"在庫点検\" ở bất kỳ đâu."]},
     ]},
    # ------------------------------------------------------------ 017 お届け中の商品あり
    {"id": "017", "code": "CW_STOCK_001", "state": ["お届け中の商品あり", "Có sản phẩm đang giao"],
     "url": "/corp/stock/CU00950/2026-10", "full": True, "wait": 600, "setup": "",
     "note": ["横浜営業所（COOL便）の今回の月度で、出荷したがまだ納品していないお届けがある状態。案内と「お届け中」列に数が入り、「届いた数」が入力できる。見本データの追加配送（9/29 の冷蔵の便に追加で手配した4食・10/02 出荷・10/06 お届け予定・出荷済。受付簿 No.157）。",
              "Tháng này của 横浜営業所 (COOL便) có đơn đã xuất kho nhưng chưa giao xong. Hiện thông báo, cột \"お届け中\" có số và nhập được \"届いた数\". Là đơn giao bổ sung trong dữ liệu mẫu (4 phần bổ sung cho chuyến lạnh 9/29, xuất 10/02, dự kiến giao 10/06, trạng thái 出荷済; 受付簿 No.157)."],
     "items": [
         {"no": "29", "ja": "お届け中の商品の案内", "vi": "Thông báo sản phẩm đang giao", "sel": ".es-inline strong::お届け中の商品があります^2", "kind": "label", "trig": "view",
          "detail": ["「お届け中の商品があります」：お届けごとに「{お届け日} のお届け（{状態}）：{商品名} {n}個・…」を並べ、「届いていれば「届いた数」に入れてください。」と案内する。入力できるときだけ出す。",
                     "\"お届け中の商品があります\": liệt kê theo từng đơn \"{お届け日} のお届け（{状態}）：{商品名} {n}個・…\" và hướng dẫn \"届いていれば「届いた数」に入れてください。\". Chỉ hiện khi nhập được."]},
         {"no": "30", "ja": "届いた数（活性）", "vi": "届いた数 (nhập được)", "sel": "table.sk-in th::届いた数", "kind": "label", "trig": "view",
          "detail": ["お届け中がある行だけ入力欄になる。届いた分は今ある数にも含める。報告すると、そのお届けは次の棚卸で「届けた数」に数えない（二重に数えない）。",
                     "Chỉ dòng có đang giao mới thành ô nhập. Phần đã nhận cũng cộng vào 今ある数. Sau khi báo cáo, đơn đó không tính vào \"届けた数\" ở lần kiểm kê sau (không đếm 2 lần)."]},
     ]},
    # ------------------------------------------------------------ 018 廃棄する・期限切れ見込みの行
    {"id": "018", "code": "CW_STOCK_001", "state": ["廃棄する・期限切れ見込みの行", "Dòng cần bỏ / dự kiến quá hạn"],
     "url": "/corp/stock/CU00871/2026-10", "full": True, "wait": 600, "setup": "",
     "note": ["大阪支店の今回の月度。代替品の設定で廃棄する商品（デミグラスハンバーグ）があり、行に色が付く。代替品の回収のお知らせも出る。",
              "Tháng này của 大阪支店. Có sản phẩm cần bỏ theo thiết lập hàng thay thế (デミグラスハンバーグ), dòng được tô màu. Hiện thêm thông báo thu hồi hàng thay thế."],
     "items": [
         {"no": "31", "ja": "代替品の回収のお知らせ", "vi": "Thông báo thu hồi hàng thay thế", "sel": ".es-inline strong::代替品の回収^2", "kind": "label", "trig": "view",
          "detail": ["代替品の設定（運営Web）のデータで、この拠点に回収・廃棄する商品があるとき、今回の月度だけ出す（拠点・月度の直書きはしない：決定_代替品 Q-ALT8）。受付番号・お届けした日・商品・数・回収のお届け日（ES配送便＝ドライバーが回収）を出す。COOL便の拠点は「お客様で廃棄して、棚卸報告の「捨てた数」にご入力ください。」と案内する（回収のお届け日はない）。廃棄した分は計算上の在庫から引き、在庫差額にしない。",
                     "Khi có sản phẩm thu hồi / bỏ theo thiết lập hàng thay thế (運営Web): hiện số tiếp nhận, ngày giao, sản phẩm, số lượng, ngày giao thu hồi. Phần đã bỏ trừ khỏi tồn kho tính toán, không tính chênh lệch."]},
         {"no": "32", "ja": "色を付けた行", "vi": "Dòng được tô màu", "sel": "table.sk-in tr.rv-skwarn", "kind": "label", "trig": "view",
          "detail": ["「廃棄する」に数がある行（代替品の廃棄、または ES の期限を過ぎた見込み）。捨てた数に入れるよう促す。", "Dòng có số ở \"廃棄する\" (bỏ theo hàng thay thế hoặc dự kiến quá hạn ES). Nhắc nhập vào 捨てた数."]},
     ]},
    # ------------------------------------------------------------ 019 CSV出力
    {"id": "019", "code": "CW_STOCK_001", "state": ["CSV出力", "Xuất CSV"],
     "url": "/corp/stock/CU00961/2026-10", "full": True, "wait": 400,
     "setup": "const cb=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='CSV出力'); cb&&cb.click(); await new Promise(r=>setTimeout(r,800)); ",
     "note": ["「CSV出力」を押した直後。ファイルを下ろし、トースト S12 を出す。", "Ngay sau khi bấm \"CSV出力\". Tải file và hiện toast S12."],
     "items": [
         {"no": "33", "ja": "CSV出力のトースト", "vi": "Toast xuất CSV", "sel": ".hd-toast", "kind": "toast", "trig": "show", "err": ["S12"],
          "detail": ["S12（行数とファイル名）。ファイル名は 棚卸報告_<yyyymmdd_hhmm>.csv。0件なら I01 を出して押せない（P-CSV-OUT）。", "S12 (số dòng và tên file). Tên file 棚卸報告_<yyyymmdd_hhmm>.csv. 0 dòng thì hiện I01 và không bấm được (P-CSV-OUT)."]},
     ]},
    # ============================================================ CW_STOCK_002 棚卸一覧（版 1.1 で分けた画面。/corp/stock）
    {"id": "020", "code": "CW_STOCK_002", "state": ["棚卸一覧（法人アカウント）", "Danh sách kiểm kê (tài khoản pháp nhân)"],
     "url": "/corp/stock", "full": True, "wait": 600, "setup": "",
     "note": ["サイドメニュー「棚卸報告」を押して開く画面。自社のすべての拠点×月度（今回＋過去3か月）の報告の状況を一覧にし、行を押すと棚卸報告（CW_STOCK_001）へ。報告する商品が1つもない過去の月度（見本データは 2026-09 の締めから）は「棚卸なし」（要確認）。",
              "Màn hình mở khi bấm menu \"棚卸報告\". Danh sách tình trạng báo cáo của mọi chi nhánh × tháng (tháng này + 3 tháng trước); bấm dòng sang 棚卸報告 (CW_STOCK_001). Tháng trước không có sản phẩm nào để báo cáo (dữ liệu mẫu bắt đầu từ kỳ 2026-09) thì \"棚卸なし\" (cần xác nhận)."],
     "items": [
         {"no": "34", "ja": "ページ見出し", "vi": "Tiêu đề trang", "sel": ".es-pagehead", "kind": "area", "trig": "view"},
         {"no": "34.1", "ja": "画面名", "vi": "Tên màn hình", "sel": "h1.es-pagehead__title", "kind": "label", "trig": "view",
          "init": ["棚卸一覧", "\"棚卸一覧\""],
          "detail": ["パンくずと見出しは「棚卸一覧」。サイドメニューの名前は「棚卸報告」（メニューを押すとこの画面）。", "Breadcrumb và tiêu đề \"棚卸一覧\". Tên trên menu bên là \"棚卸報告\" (bấm menu thì ra màn này)."]},
         {"no": "34.2", "ja": "法人名・権限", "vi": "Tên pháp nhân, quyền", "sel": ".es-pagehead .stat", "kind": "label", "trig": "view",
          "init": ["株式会社サンプル　権限 法人アカウント（自社のすべての拠点）", "株式会社サンプル, quyền: tài khoản pháp nhân (mọi chi nhánh của công ty)"],
          "detail": ["CW_STOCK_001 No.1.2 と同じ。", "Giống CW_STOCK_001 No.1.2."]},
         {"no": "35", "ja": "絞り込み", "vi": "Lọc", "sel": ".sk-filter", "kind": "area", "trig": "view", "pattern": "P-LIST",
          "detail": ["月度・拠点・状態で絞り込む。「検索」か Enter で反映（P-LIST）。P-LIST と違うところ：月度の既定は「指定なし」ではなく今回の月度。",
                     "Lọc theo 月度・拠点・状態. Áp dụng khi bấm \"検索\" hoặc Enter (P-LIST). Khác P-LIST: mặc định của 月度 là tháng này, không phải \"không chỉ định\"."]},
         {"no": "35.1", "ja": "月度", "vi": "Tháng kiểm kê", "sel": "#sk-m", "kind": "select", "trig": "select", "req": "－", "len": ["選択（すべて／今回＋過去3か月）", "Chọn (tất cả / tháng này + 3 tháng trước)"],
          "init": ["今回の月度（「（今回）」付き）", "Tháng này (có chữ \"（今回）\")"],
          "ex": ["2026-10（今回）", "Tháng kiểm kê YYYY-MM; tháng này có đuôi \"（今回）\"; \"すべて\" = 4 tháng"],
          "detail": ["「すべて」を選ぶと今回＋過去3か月の全部の行（拠点×4か月）。", "Chọn \"すべて\" thì hiện mọi dòng của tháng này + 3 tháng trước (chi nhánh × 4 tháng)."]},
         {"no": "35.2", "ja": "拠点", "vi": "Chi nhánh", "sel": "#sk-site", "kind": "select", "trig": "select", "req": "－", "len": "選択",
          "init": ["すべて", "Tất cả"],
          "ex": ["株式会社サンプル 千葉営業所", "Chọn: すべて / từng chi nhánh được xem (giá trị là 拠点ID, ví dụ CU00961)"],
          "cond": ["法人アカウントで拠点が2つ以上あるときだけ出す", "Chỉ hiện khi tài khoản pháp nhân có từ 2 chi nhánh"]},
         {"no": "35.3", "ja": "状態", "vi": "Trạng thái", "sel": "#sk-st", "kind": "select", "trig": "select", "req": "－", "len": "選択",
          "init": ["すべて", "Tất cả"],
          "ex": ["未報告", "Chọn: すべて / 未報告 / 報告済み / 未報告（事務手数料あり） / ご契約前 / 棚卸なし（休止中） / 棚卸なし"]},
         {"no": "35.4", "ja": "検索", "vi": "Nút \"検索\"", "sel": ".sk-filter button::検索", "kind": "button", "trig": "click", "err": ["I01"],
          "detail": ["条件を反映して1ページ目へ。0件は I01（No.38）。", "Áp dụng điều kiện và về trang 1. 0 dòng: I01 (No.38)."]},
         {"no": "36", "err": ["E346"], "ja": "棚卸一覧", "vi": "Danh sách kiểm kê", "sel": "table.sk-st", "kind": "table", "trig": "view", "pattern": "P-LIST",
          "init": ["未報告 → 報告済 → 棚卸なし・休止中・ご契約前 の順、その中は拠点ID の昇順、同じ拠点は月度の降順", "未報告 → 報告済 → 棚卸なし・休止中・ご契約前, trong mỗi nhóm theo 拠点ID tăng dần, cùng chi nhánh thì 月度 giảm dần"],
          "detail": ["1行＝1拠点×1月度。見られる拠点（法人アカウント＝自社のすべての拠点／拠点アカウント＝この拠点）を「やることがある順」に並べる：未報告（事務手数料ありを含む）→ 報告済 → 棚卸なし・休止中・ご契約前、その中は拠点ID の昇順（hong 2026-10-05 B-20）。行を押すと、その拠点・月度の棚卸報告（CW_STOCK_001）を開く（No.36.9）。1ページ 10件、「並べ替え」あり（P-LIST）。 読み込めなかったとき（通信・サーバーのエラー）は白い画面にせず、E346「読み込めませんでした。／時間をおいて再度お試しください。」と「再読み込み」ボタンを出す（画像なし：見本データではエラーを起こせない）。",
                     "1 dòng = 1 chi nhánh × 1 tháng. Các chi nhánh được xem (tài khoản pháp nhân = mọi chi nhánh / tài khoản chi nhánh = chi nhánh mình) xếp theo việc cần làm: 未報告 (gồm có phí hành chính) → 報告済 → 棚卸なし・休止中・ご契約前, trong mỗi nhóm theo 拠点ID tăng dần (hong 2026-10-05 B-20). Bấm dòng mở 棚卸報告 (CW_STOCK_001) của chi nhánh / tháng đó (No.36.9). 10 dòng / trang, có \"並べ替え\" (P-LIST). Khi không tải được dữ liệu (lỗi mạng / máy chủ) thì không để trắng màn hình mà hiện E346 \"読み込めませんでした。\" kèm nút \"再読み込み\" (không có ảnh: dữ liệu mẫu không tạo được lỗi)."]},
         {"no": "36.1", "ja": "月度", "vi": "Tháng kiểm kê", "sel": "table.sk-st th::月度", "kind": "label", "trig": "view",
          "detail": ["YYYY-MM。今回の月度は「（今回）」を添える。", "YYYY-MM. Tháng này có thêm \"（今回）\"."]},
         {"no": "36.2", "ja": "拠点ID", "vi": "Mã chi nhánh", "sel": "table.sk-st th::拠点ID", "kind": "label", "trig": "view",
          "detail": ["拠点の ID（CU + 5桁）。", "ID chi nhánh (CU + 5 chữ số)."]},
         {"no": "36.3", "ja": "拠点名", "vi": "Tên chi nhánh", "sel": "table.sk-st th::拠点名", "kind": "label", "trig": "view"},
         {"no": "36.4", "ja": "配送の方法", "vi": "Phương thức giao hàng", "sel": "table.sk-st th::配送の方法", "kind": "label", "trig": "view",
          "detail": ["子契約の配送の方法（ES配送便／COOL便）。休止中は「—」。", "Phương thức giao của hợp đồng con (ES配送便 / COOL便). Đang tạm dừng thì \"—\"."]},
         {"no": "36.5", "ja": "状態", "vi": "Trạng thái", "sel": "table.sk-st th::状態", "kind": "label", "trig": "view",
          "detail": ["バッジ：未報告（黄）／報告済（緑）／未報告（事務手数料あり）（赤・25日を過ぎても報告がない）／ご契約前（灰）／棚卸なし（休止中）（灰）／棚卸なし（灰）。CW_STOCK_001 No.3.6 と同じ。",
                     "Badge: 未報告 (vàng) / 報告済み (xanh) / 未報告（事務手数料あり） (đỏ, quá ngày 25 chưa báo cáo) / ご契約前 (xám) / 棚卸なし（休止中） (xám) / 棚卸なし (xám). Giống CW_STOCK_001 No.3.6."]},
         {"no": "36.6", "ja": "報告日", "vi": "Ngày báo cáo", "sel": "table.sk-st th::報告日", "kind": "label", "trig": "view",
          "detail": ["最後の報告の日（YYYY-MM-DD）。報告がなければ「—」。", "Ngày của báo cáo cuối (YYYY-MM-DD). Chưa có thì \"—\"."]},
         {"no": "36.7", "ja": "報告者", "vi": "Người báo cáo", "sel": "table.sk-st th::報告者", "kind": "label", "trig": "view",
          "detail": ["報告した方の氏名（企業担当者）または「ES配送便ドライバー」。報告がなければ「—」。", "Họ tên người báo cáo (người phụ trách công ty) hoặc \"ES配送便ドライバー\". Chưa có thì \"—\"."]},
         {"no": "36.8", "ja": "報告の方法", "vi": "Cách báo cáo", "sel": "table.sk-st th::報告の方法", "kind": "label", "trig": "view",
          "detail": ["企業担当者（法人Web）／ES配送便ドライバー（アプリ）／なし（休止中・棚卸なし・ご契約前）。CW_STOCK_001 No.3.9 の短い形。", "企業担当者 (法人Web) / ES配送便ドライバー (app) / なし (tạm dừng, không kiểm kê, trước hợp đồng). Dạng ngắn của CW_STOCK_001 No.3.9."]},
         {"no": "36.9", "ja": "行の選択", "vi": "Chọn dòng", "sel": "table.sk-st tbody tr", "kind": "link", "trig": "click",
          "detail": ["行のどこを押しても、その拠点・月度の棚卸報告（CW_STOCK_001）を開く。戻ると絞り込みとページを戻す（P-LIST）。", "Bấm bất kỳ chỗ nào trên dòng để mở 棚卸報告 (CW_STOCK_001) của chi nhánh / tháng đó. Quay lại thì khôi phục điều kiện lọc và trang (P-LIST)."]},
     ]},
    {"id": "021", "code": "CW_STOCK_002", "state": ["棚卸一覧（拠点アカウント）", "Danh sách kiểm kê (tài khoản chi nhánh)"],
     "url": "/corp/stock", "full": True, "login": "CU00961", "wait": 600, "setup": "",
     "note": ["拠点アカウント（CU00961 千葉営業所）。自分の拠点の行だけ（月度ごとに1行）。拠点の絞り込み（No.35.2）は出ない。", "Tài khoản chi nhánh (CU00961 千葉営業所). Chỉ các dòng của chi nhánh mình (1 dòng / tháng). Không hiện lọc chi nhánh (No.35.2)."],
     "items": [
         {"no": "37", "ja": "拠点アカウントの一覧", "vi": "Danh sách với tài khoản chi nhánh", "sel": "table.sk-st", "kind": "label", "trig": "view",
          "init": ["株式会社サンプル　権限 拠点アカウント（この拠点だけ）", "株式会社サンプル, quyền: tài khoản chi nhánh (chỉ chi nhánh này)"],
          "detail": ["見出しの権限は「拠点アカウント（この拠点だけ）」。行は自分の拠点だけ（月度「すべて」で4行）。", "Quyền ở tiêu đề là \"拠点アカウント（この拠点だけ）\". Chỉ dòng của chi nhánh mình (chọn 月度 \"すべて\" thì 4 dòng)."]},
     ]},
    {"id": "022", "code": "CW_STOCK_002", "state": ["0件", "0 dòng"],
     "url": "/corp/stock", "full": True, "wait": 600, "setup": _JS_SEL % ('#sk-st', '未報告（事務手数料あり）') + _JS_CLICK_BTN % '検索',
     "note": ["絞り込みに合う行がない状態（例：今回の月度で状態「未報告（事務手数料あり）」は該当なし。月度を「すべて」にすると横浜営業所 2026-09 が出る）。一覧の中に I01。", "Không có dòng nào khớp điều kiện lọc (ví dụ: tháng này không có dòng nào ở trạng thái \"未報告（事務手数料あり）\"; chọn 月度 \"すべて\" thì hiện 横浜営業所 2026-09). Hiện I01 trong danh sách."],
     "items": [
         {"no": "38", "ja": "0件の表示", "vi": "Hiển thị 0 dòng", "sel": "table.sk-st", "kind": "label", "trig": "view", "err": ["I01"],
          "detail": ["I01 を一覧の中に出す。", "Hiện I01 trong danh sách."]},
     ]},
    # ============================================================ 版 1.1 で足した状態（CW_STOCK_001）
    {"id": "023", "code": "CW_STOCK_001", "state": ["棚卸用の表（PDF）", "Bảng kiểm kê (PDF)"],
     "url": "/corp/stock/CU00961/2026-10", "full": True, "wait": 400,
     "setup": _JS_CLICK_BTN % '棚卸用の表（PDF）',
     "note": ["「棚卸用の表（PDF）」（No.1.4）を押した直後。ブラウザの印刷（別のタブ・A4 縦）で PDF にし、トースト S220。", "Ngay sau khi bấm \"棚卸用の表（PDF）\" (No.1.4). In bằng trình duyệt (tab khác, A4 dọc) để ra PDF, hiện toast S220."],
     "items": [
         {"no": "39", "ja": "PDF 出力のトースト", "vi": "Toast xuất PDF", "sel": ".hd-toast", "kind": "toast", "trig": "show", "err": ["S220"],
          "detail": ["S220。画面の下に約2.6秒出す。", "S220. Hiện ở đáy màn hình khoảng 2,6 giây."]},
         {"no": "40", "ja": "棚卸用の表（PDF の内容）", "vi": "Bảng kiểm kê (nội dung PDF)", "sel": "-", "kind": "label", "trig": "view",
          "detail": ["A4 縦。頭に 見出し「棚卸用の表」・法人名・拠点名（拠点ID）・月度・対象期間・報告期限・出力日時。表の列：No・商品名・前回の数（前回の報告の今ある数。なければ「—」）・今ある数（空欄）・捨てた数（空欄）・届いた数（お届け中がある行だけ空欄、ほかは斜線）。行は棚卸の表（No.3.11）と同じ商品・同じ並び。最後に空の行を3行（一覧にない商品を書くため）。表が1ページに収まらなければ改ページし、各ページに見出しの行とページ番号。注記「数えたら、法人Web の棚卸報告に入力してください（報告期限 {日付}）」。。商品名（英語）も商品名の下に出す（PDF にも載せる）（台帳 F「商品名（英語）」）",
                     "A4 dọc. Đầu trang: tiêu đề \"棚卸用の表\", tên pháp nhân, tên chi nhánh (拠点ID), tháng, kỳ, hạn báo cáo, ngày giờ xuất. Cột: No・商品名・前回の数 (今ある数 của báo cáo trước; không có thì \"—\")・今ある数 (trống)・捨てた数 (trống)・届いた数 (chỉ dòng có đang giao để trống, dòng khác gạch chéo). Dòng = cùng sản phẩm, cùng thứ tự với bảng kiểm kê (No.3.11). Cuối bảng 3 dòng trống (để ghi sản phẩm ngoài danh sách). Không vừa 1 trang thì sang trang, mỗi trang lặp dòng tiêu đề và có số trang. Ghi chú \"数えたら、法人Web の棚卸報告に入力してください（報告期限 {日付}）\".. Tên tiếng Anh của sản phẩm cũng hiển thị dưới tên (cũng in trên PDF) (台帳 F「商品名（英語）」)"],
          "demo_ok": ["ページ番号はブラウザの印刷の「ヘッダーとフッター」で付く（PDF の中には作らない）", "Số trang do \"Header và footer\" của trình duyệt khi in (không tạo trong PDF)"]},
     ]},
    {"id": "024", "code": "CW_STOCK_001", "state": ["商品を追加（モーダル）", "Thêm sản phẩm (modal)"],
     "url": "/corp/stock/CU00961/2026-10", "full": True, "wait": 500,
     "setup": _JS_CLICK_BTN % '商品を追加',
     "note": ["「商品を追加」（No.3.15）を押した状態。スマホはカメラで JAN コードを読み取り、PC は JAN コードの入力か商品名の検索（カメラのあるブラウザでは PC でも「JANをスキャン」を出す）。", "Bấm \"商品を追加\" (No.3.15). Điện thoại quét mã JAN bằng camera, PC nhập mã JAN hoặc tìm theo tên (trình duyệt có camera thì PC cũng hiện \"JANをスキャン\")."],
     "items": [
         {"no": "41", "ja": "商品を追加モーダル", "vi": "Modal thêm sản phẩm", "sel": ".es-dialog__panel", "kind": "modal", "trig": "show", "err": ["I224"],
          "detail": ["タイトル「商品を追加」。幅 560px。上に案内 I224。候補はESキッチンの商品マスタで販売中の商品（この拠点の棚卸の表にない商品）。外側を押すか × で閉じる。",
                     "Tiêu đề \"商品を追加\". Rộng 560px. Trên cùng là thông báo I224. Ứng viên là sản phẩm đang bán trong master sản phẩm của ESキッチン (chưa có trong bảng kiểm kê của chi nhánh). Bấm ngoài hoặc × để đóng."]},
         {"no": "41.1", "ja": "JANをスキャン", "vi": "Nút \"JANをスキャン\"", "sel": ".es-dialog button::JANをスキャン", "kind": "button", "trig": "click", "err": ["I226", "E329", "W211"],
          "cond": ["カメラのあるブラウザ（スマホ）だけ出す。カメラがなければ出さない", "Chỉ hiện ở trình duyệt có camera (điện thoại). Không có camera thì không hiện"],
          "detail": ["ブラウザのカメラを開き、バーコード（JAN-13・JAN-8）を読み取る（初回はカメラの許可を求める）。読み取れたら JAN コード（No.41.2）に入れて候補（No.41.4）を出す。許可がない・カメラがない・バーコードを読む機能のないブラウザでは I226。",
                     "Mở camera của trình duyệt và đọc mã vạch (JAN-13, JAN-8) (lần đầu xin quyền camera). Đọc được thì điền vào mã JAN (No.41.2) và hiện ứng viên (No.41.4). Không có quyền / không có camera / trình duyệt không đọc được mã vạch thì I226."],
          "demo_ok": ["バーコードの読み取りはブラウザの BarcodeDetector（Chrome・Android・iOS 17 以降の Safari）を使う。ない環境では I226 を出して JAN の入力へ", "Đọc mã vạch bằng BarcodeDetector của trình duyệt (Chrome, Android, Safari iOS 17+). Môi trường không có thì hiện I226 và nhập JAN"]},
         {"no": "41.2", "ja": "JANコード", "vi": "Mã JAN", "sel": ".es-dialog input[aria-label=\"JANコード\"]", "kind": "text", "trig": "input", "req": "－", "len": ["数字 8桁または13桁", "Số, 8 hoặc 13 chữ số"],
          "init": ["空", "Trống"],
          "ex": ["4901234567894", "Mã JAN-13 (hoặc JAN-8) của sản phẩm trong master; số toàn góc đổi sang nửa góc"],
          "valid": ["数字だけ。全角は半角に直す。8桁か13桁でないときは候補を出さない", "Chỉ số. Toàn góc đổi sang nửa góc. Không phải 8 hoặc 13 chữ số thì không hiện ứng viên"],
          "err": ["E329"],
          "detail": ["入力が 8桁か13桁になった時点で商品マスタの JAN と突き合わせ、一致した商品を候補（No.41.4）に出す。一致がなければ E329。", "Khi đủ 8 hoặc 13 chữ số thì đối chiếu với JAN trong master sản phẩm và hiện sản phẩm khớp ở ứng viên (No.41.4). Không khớp thì E329."]},
         {"no": "41.3", "ja": "商品名で探す", "vi": "Tìm theo tên sản phẩm", "sel": ".es-dialog input[aria-label=\"商品名で探す\"]", "kind": "text", "trig": "input", "req": "－", "len": "文字列 60",
          "init": ["空", "Trống"],
          "ex": ["ハンバーグ", "Một phần tên sản phẩm (khớp một phần, không phân biệt toàn góc / nửa góc, hiragana / katakana)"],
          "valid": ["60文字まで（E04）。2文字以上で候補を出す", "Tối đa 60 ký tự (E04). Từ 2 ký tự trở lên mới hiện ứng viên"],
          "err": ["E04", "E329"],
          "detail": ["商品名の部分一致（商品カナも対象）。入力するたびに候補（No.41.4）を最大 20件。一致がなければ E329 を候補の場所に出す。", "Khớp một phần tên sản phẩm (cả カナ). Mỗi lần nhập hiện tối đa 20 ứng viên (No.41.4). Không khớp thì hiện E329 ở chỗ ứng viên."]},
         {"no": "41.4", "ja": "候補の一覧", "vi": "Danh sách ứng viên", "sel": ".es-dialog table", "kind": "table", "trig": "view",
          "detail": ["列：商品名・JAN・温度帯。1行押すと選ばれる（ラジオ）。すでに棚卸の表にある商品は候補に出さず、JAN で一致したときは W211。。商品名（英語）も商品名の下に出す（台帳 F「商品名（英語）」）", "Cột: 商品名・JAN・温度帯. Bấm 1 dòng để chọn (radio). Sản phẩm đã có trong bảng kiểm kê không hiện ở ứng viên; khớp bằng JAN thì W211.. Tên tiếng Anh của sản phẩm cũng hiển thị dưới tên (台帳 F「商品名（英語）」)"]},
         {"no": "41.5", "ja": "追加する", "vi": "Nút \"追加する\"", "sel": ".es-dialog__foot button::追加する", "kind": "button", "trig": "click", "err": ["S219", "W211"],
          "cond": ["候補を1つ選んだときだけ押せる", "Chỉ bấm được khi đã chọn 1 ứng viên"],
          "detail": ["選んだ商品を棚卸の表の最後に足し（No.42）、モーダルを閉じて S219。足した行の今ある数に合わせて画面を動かす。すでにある商品なら W211（足さない）。", "Thêm sản phẩm đã chọn vào cuối bảng kiểm kê (No.42), đóng modal và hiện S219. Cuộn tới ô 今ある数 của dòng vừa thêm. Sản phẩm đã có thì W211 (không thêm)."]},
         {"no": "41.6", "ja": "キャンセル", "vi": "Nút \"キャンセル\"", "sel": ".es-dialog__foot button::キャンセル", "kind": "button", "trig": "click",
          "detail": ["何もせずに閉じる。", "Đóng mà không làm gì."]},
         {"no": "41.7", "ja": "閉じる（×）", "vi": "Đóng (×)", "sel": ".es-dialog__close", "kind": "button", "trig": "click",
          "detail": ["キャンセルと同じ。カメラを開いていれば止める。", "Giống \"キャンセル\". Đang mở camera thì tắt."]},
     ]},
    {"id": "025", "code": "CW_STOCK_001", "state": ["追加した商品の行", "Dòng sản phẩm đã thêm"],
     "url": "/corp/stock/CU00961/2026-10", "full": True, "wait": 500,
     "setup": _JS_CLICK_BTN % '商品を追加' + "const ni=document.querySelector('.es-dialog input[aria-label=\"商品名で探す\"]'); if(ni){Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(ni,'からあげ'); ni.dispatchEvent(new Event('input',{bubbles:true}));} await new Promise(r=>setTimeout(r,400)); "
              "const cr=document.querySelector('.es-dialog table.sk-cand tbody tr'); cr&&cr.click(); await new Promise(r=>setTimeout(r,200)); " + _JS_CLICK_BTN % '追加する',
     "note": ["「商品を追加」で商品（鶏の唐揚げ）を足した直後。表の最後に前回の数 0 の行が入り、I225 を添える。", "Ngay sau khi thêm sản phẩm (鶏の唐揚げ) bằng \"商品を追加\". Cuối bảng có dòng với số lần trước = 0 kèm I225."],
     "items": [
         {"no": "42", "ja": "追加した商品の行", "vi": "Dòng sản phẩm đã thêm", "sel": "table.sk-in tr.sk-added", "kind": "label", "trig": "view", "err": ["I225"],
          "detail": ["前回の棚卸 0、お届け中「—」、廃棄する「—」、今ある数（必須）、捨てた数、届いた数「—」。商品名の下に I225。足した行は拠点・月度ごとに入力中の数と一緒にブラウザに残す（再読み込みで消える）。報告すると、この商品はこの拠点の棚卸の商品になる（次の月度からは通常の行）。E327 の確認はこの行に掛けない。",
                     "前回の棚卸 0, お届け中 \"—\", 廃棄する \"—\", 今ある数 (bắt buộc), 捨てた数, 届いた数 \"—\". Dưới tên sản phẩm có I225. Dòng đã thêm được giữ trong trình duyệt cùng số đang nhập theo chi nhánh / tháng (tải lại thì mất). Sau khi báo cáo, sản phẩm này thành sản phẩm kiểm kê của chi nhánh (từ tháng sau là dòng bình thường). Không áp dụng kiểm tra E327 cho dòng này."]},
         {"no": "42.1", "ja": "行を外す（×）", "vi": "Bỏ dòng (×)", "sel": "table.sk-in tr.sk-added button", "kind": "button", "trig": "click",
          "detail": ["足した行だけに出す。押すとその行を表から外す（確認なし。保存はしていないため）。", "Chỉ hiện ở dòng đã thêm. Bấm thì bỏ dòng khỏi bảng (không hỏi, vì chưa lưu)."]},
     ]},
    # ------------------------------------------------------------ 026 入力エラー（行のエラー）
    {"id": "026", "code": "CW_STOCK_001", "state": ["入力エラー（行のエラー・届いた数と合計）", "Lỗi nhập liệu (lỗi theo dòng: số đã nhận / tổng)"],
     "url": "/corp/stock/CU00950/2026-10", "full": True, "wait": 600,
     "setup": _JS_ROW_ERR,
     "note": ["横浜営業所の今回の月度で、数をまちがえて入れた状態：お届け中がある行の「届いた数」をお届け中の数より多く（E321）、ほかの1行の「今ある数」を前回の数＋届けた数より多く（E327）入れた。まちがえた行だけに赤枠と行のエラーが出る（「報告する」を押す前から分かる）。見本データの追加配送（出荷済）でお届け中の行がある（受付簿 No.157）。",
              "Trạng thái nhập sai số ở tháng này của 横浜営業所: nhập \"届いた数\" lớn hơn số đang giao ở dòng có hàng đang giao (E321) và \"今ある数\" lớn hơn 前回の数 + 届けた数 ở một dòng khác (E327). Chỉ dòng sai hiện viền đỏ và lỗi theo dòng (biết ngay trước khi bấm \"報告する\"). Dòng đang giao lấy từ đơn giao bổ sung (出荷済) trong dữ liệu mẫu (受付簿 No.157)."],
     "items": [
         {"no": "3.11.8", "ja": "行のエラー（届いた数・合計）", "vi": "Lỗi theo dòng (số đã nhận / tổng)", "sel": "table.sk-in .es-field__msg--error", "kind": "label", "trig": "view", "err": ["E321", "E327"],
          "cond": ["入力できるときだけ。入れた数がまちがっている行だけに出す（「報告する」を押す前から、その行で分かる）", "Chỉ khi nhập được. Chỉ hiện ở dòng có số sai (biết ngay trên dòng, trước khi bấm \"報告する\")"],
          "detail": ["届いた数がお届け中の数を超える行は、届いた数の欄を赤枠にして行の中に E321 の文言を出す。今ある数＋捨てた数が、前回の数＋届けた数（届いた数を含む。サーバーの確認と同じ式）を超える行は、今ある数・捨てた数の欄を赤枠にして行の中に E327 の文言（行の中では{商品名}は省く）を出す。「商品を追加」で足した行は E327 の対象外。直すと赤枠と文言が消える。この状態で「報告する」を押すとトーストにも同じ文言を出し、確認モーダルへは進まない。",
                     "Dòng có 届いた数 vượt số đang giao: viền đỏ ô 届いた数 và hiện câu E321 ngay trong dòng. Dòng có 今ある数 + 捨てた数 vượt 前回の数 + 届けた数 (gồm 届いた数; cùng công thức với kiểm tra phía server): viền đỏ ô 今ある数 / 捨てた数 và hiện câu E327 trong dòng (trong dòng bỏ {tên sản phẩm}). Dòng thêm bằng \"商品を追加\" không áp dụng E327. Sửa đúng thì hết viền đỏ và câu. Bấm \"報告する\" khi còn lỗi thì toast cũng hiện câu đó và không mở modal xác nhận."]},
     ]},
]
