# -*- coding: utf-8 -*-
"""
画面設計書のデータ：運営管理者Web「子契約一覧」（AW_CONT）。
元は本物の Web（このリポジトリのコード app/ops/contracts/**・app/ops/_ui/BulkChangeModal.tsx・lib/ops/contracts/forms.ts の CHILD_FORM）。決定は docs/決定台帳.md（B・E・F・K）、項目は docs/01_仕様/20_法人・拠点・契約/契約仕様/契約_02・契約_05 が正。
洗い出し・確認の記録は docs/05_画面設計書/確認メモ_AW_運営A_申請・法人・契約.md（Q＝hong 回答済み・受付簿 No.184、H＝宿題、O＝open）。

画面：AW_CONT_001 子契約一覧／002 子契約詳細／003 子契約編集／004 価格世代を一括切替（モーダル）／005 子契約CSV取込（画面コード規約 2026-10-05）
一括変更のモーダル（BulkChangeModal）は1つの部品で2つのモード：価格世代＝この設計書（AW_CONT_004）／ルート（倉庫・委託配送先マスタの「この倉庫／配送先の契約を一括変更」）＝運営H の設計書（ここでは参照だけ）。
見本のデータ（今日＝2026-10-05）：72件の子契約。CP0000001-202703（自販機・最新月）／CP0000002-202702（承認待ちの申請 CH-20260925-0001）／CP0000004-202702（後ろに生成済みの子契約あり）／CP0000001-202610（請求済）／CP0000012-202612（手動生成）／CP0000021-202611（仮登録）

コードと決定が違うところ（demo_ok＝決定が正・コードを直す宿題）：
  ・（解消済み 2026-10-08）並べ替え（全列）・初期の並び＝更新日時の降順・更新日時の列・「未適用」の印を外した・同時編集（I02・E31）・文字数の上限（E04）
  ・カナ・絵文字の入力チェック
  ・価格世代の一括切替は フル権限・システム管理だけ（コードは子契約の編集権限＝CS の R/U も押せる）
  ・確定・請求済の子契約は金額に効く変更ができない（コードは保存でき、適用範囲「以降すべて」のときだけ直さない）
  ・請求ステータスの値（検索は5段階・データは未確定／確定／請求済の3値）／惣菜買取の項目がない
撮れない状態（見本のデータで出せない。demo_ok に理由）：100件超の打ち直し・注意の確認（一括変更）
"""

TITLE = ["子契約一覧（AW_CONT）", "Danh sách hợp đồng con (AW_CONT)"]
SHEET = ["子契約一覧", "Danh sách hợp đồng con"]
BASENAME = "画面設計書_AW_CONT_子契約一覧"
IMG_PREFIX = "AW_CONT"
OUT_DIR = "運営管理者Web_申請・契約"
CODE_NOTE = ["画面コード規約（docs/01_仕様/画面コード規約_20261005.md）：<Module(2)>_<Feature(4)>_<Seq(3)>。AW＝Admin Web、CONT＝子契約", "Quy ước mã màn hình (画面コード規約_20261005): <Module(2)>_<Feature(4)>_<Seq(3)>. AW = Admin Web, CONT = hợp đồng con"]
SITE = "ops"
SYSTEM = {"ja": "運営管理者Web", "vi": "Web quản trị vận hành"}
AUTHOR = "Claude（cloud）／確認：hong"
CREATED = "2026-10-07"
DEMO_FILE = "http://localhost:3000"
LOGIN = {"site": "ops", "loginId": "Ad00010"}
CODE_PATHS = ["app/ops/contracts", "app/ops/corps/_components", "app/ops/_ui", "lib/ops/contracts", "lib/ops/areas/contracts.ts", "lib/domain/bulk.ts", "lib/domain/areas/bulk.ts", "lib/csv", "lib/domain/seed"]

DECISIONS = [
    {"date": "2026-10-07", "target": "AW_CONT_004 価格世代を一括切替の権限",
     "q": ["「価格世代を一括切替」を誰が実行できるか", "Ai được thực hiện \"価格世代を一括切替\""],
     "a": ["子契約の作成と同じ：フル権限・システム管理だけ（B）。数百件の請求の費目を作り直す操作なので、CS（R/U）には出さない。個別の子契約は CS も直せる", "Giống quyền tạo hợp đồng con: chỉ フル権限・システム管理 (B). Vì là thao tác dựng lại hạng mục hóa đơn của hàng trăm hợp đồng nên không hiện với CS (R/U). Từng hợp đồng con riêng lẻ CS vẫn sửa được"], "src": "hong 回答 2026-10-07（確認メモ_AW_運営A Q2＝B・台帳 F・受付簿 No.184）"},
    {"date": "2026-10-05", "target": "AW_CONT_004（置き場所）",
     "q": ["価格世代の一括切替の置き場所", "Vị trí đặt chức năng đổi hàng loạt thế hệ giá"],
     "a": ["プランマスタには置かない。契約の側（子契約一覧）から、プラン・価格の世代を条件にして未確定の子契約に当てる（B 案）", "Không đặt ở プランマスタ. Làm từ phía hợp đồng (danh sách hợp đồng con), áp dụng cho hợp đồng con chưa xác định theo điều kiện gói / thế hệ giá (phương án B)"], "src": "台帳 F「価格世代を一括切替の置き場所」・受付簿 #96"},
    {"date": "2026-10-07", "target": "AW_CONT 全体（CSV取込）",
     "q": ["法人一覧・拠点一覧・子契約一覧に CSV取込を置くか", "Có đặt nhập CSV ở danh sách pháp nhân / cơ sở / hợp đồng con không"],
     "a": ["3 画面とも置く（A）。子契約は 親契約番号＋適用開始 がキー（その月から後ろの未確定の月に当てる。確定・請求済は行エラー）。子契約は CSV で作れない（拠点の「子契約を先まで作る」を使う）。取込はフル権限・システム管理だけ", "Đặt cả 3 màn hình (A). Hợp đồng con: khóa = 親契約番号 + 適用開始 (áp dụng cho các tháng chưa xác định từ tháng đó trở đi; tháng đã chốt / đã xuất hóa đơn là lỗi dòng). Không tạo hợp đồng con bằng CSV (dùng \"子契約を先まで作る\" của cơ sở). Nhập CSV chỉ フル権限・システム管理"], "src": "hong 回答 2026-10-07（確認メモ_AW_運営A Q5＝A・台帳 F・受付簿 No.184）"},
    {"date": "2026-10-07", "target": "AW_CONT_002 変更履歴の列",
     "q": ["契約系（法人・拠点・子契約）の変更履歴の列", "Các cột lịch sử thay đổi của nhóm hợp đồng"],
     "a": ["P-HIST の列に、契約だけの 適用範囲・承認者・通知の有無 を足す（C）。変更区分（手入力／CSV取込／自動生成バッチ／変更申請の承認）も残す", "Cột của P-HIST cộng thêm 適用範囲・承認者・通知の有無 riêng của hợp đồng (C). Cũng giữ 変更区分 (nhập tay / nhập CSV / batch tự sinh / duyệt đơn thay đổi)"], "src": "hong 回答 2026-10-07（確認メモ_AW_運営A Q6＝C・台帳 F・受付簿 No.184）"},
    {"date": "2026-09-29", "target": "AW_CONT_003 変更の適用範囲",
     "q": ["子契約を保存するとき、後ろの月の子契約にも当てるか", "Khi lưu hợp đồng con có áp dụng cho các hợp đồng con tháng sau không"],
     "a": ["この子契約より後に生成済みの子契約があるときだけ、保存のダイアログで「この子契約だけ／この子契約以降すべて」を選ぶ。以降すべては生成元の設定も更新し、生成済みで未確定の子契約も直す（確定・請求済は直さない）。後ろがまだ生成されていないときは確認を出さずに保存する（適用範囲は「以降すべて」で残す）", "Chỉ khi có hợp đồng con đã sinh sau hợp đồng con này mới hiện dialog chọn \"この子契約だけ / この子契約以降すべて\" lúc lưu. \"以降すべて\" cập nhật cả thiết lập nguồn sinh và sửa cả hợp đồng con đã sinh chưa xác định (không sửa tháng đã chốt / đã xuất hóa đơn). Khi phía sau chưa sinh thì lưu không hỏi (phạm vi áp dụng ghi là \"以降すべて\")"], "src": "決定 28-144（契約_00 §0.2・契約_01 §1・契約_05）"},
    {"date": "2026-10-03", "target": "AW_CONT_004 実行のあと",
     "q": ["一括変更の結果と取り消し", "Kết quả và hủy bỏ của đổi hàng loạt"],
     "a": ["結果（変更・スキップ・失敗とその理由）を出す。元に戻す操作はない（履歴は残る）。100件を超えるときは件数の打ち直しを求める。確定・請求済の子契約は変えない（請求調整）", "Hiện kết quả (thay đổi / bỏ qua / lỗi và lý do). Không có thao tác hoàn tác (lịch sử vẫn còn). Quá 100 dòng thì yêu cầu nhập lại số lượng. Không đổi hợp đồng con đã chốt / đã xuất hóa đơn (điều chỉnh hóa đơn)"], "src": "課題 7-2・4b-8（BulkChangeModal の決まり）"},
]

CHANGES = []

HIDE_ALWAYS = []
STATIC_CSS = ""
VIEWER_CSS = ""

SCREENS = [
    {"code": "AW_CONT_001", "ja": "子契約一覧", "vi": "Danh sách hợp đồng con"},
    {"code": "AW_CONT_002", "ja": "子契約詳細", "vi": "Chi tiết hợp đồng con"},
    {"code": "AW_CONT_003", "ja": "子契約編集", "vi": "Sửa hợp đồng con"},
    {"code": "AW_CONT_004", "ja": "価格世代を一括切替（モーダル）", "vi": "Đổi hàng loạt thế hệ giá (modal)"},
    {"code": "AW_CONT_005", "ja": "子契約CSV取込", "vi": "Nhập CSV hợp đồng con"},
]

# ---------------------------------------------------------------- 小さな関数
H = (
    "const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));const q=(s)=>document.querySelector(s);"
    "const setv=(el,v)=>{if(!el)return;const p=el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;"
    "Object.getOwnPropertyDescriptor(p,'value').set.call(el,v);el.dispatchEvent(new Event('input',{bubbles:true}));};"
    "const setsel=(el,v)=>{if(!el)return;Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(el,v);el.dispatchEvent(new Event('change',{bubbles:true}));};"
    "const btn=(t,root)=>[...(root||document).querySelectorAll('button')].find(b=>(b.textContent||'').trim().includes(t));"
    "const tab=(t)=>[...document.querySelectorAll('[role=tab]')].find(b=>(b.textContent||'').trim()===t);"
    "const fld=(t)=>[...document.querySelectorAll('.f')].find(f=>((f.querySelector('label')||{}).textContent||'').startsWith(t));"
    "const ctl=(t)=>fld(t).querySelector('input,select,textarea');"
    "const search=()=>{btn('検索',q('.es-search')).click();};"
    "const M=()=>q('.mbox');const mf=(t)=>[...M().querySelectorAll('.fld')].find(f=>((f.querySelector('label')||{}).textContent||'').includes(t));"
    "const openBulk=async()=>{btn('価格世代を一括切替').click();await sleep(2000);};"
    "const fillBulk=async()=>{setsel(mf('プラン').querySelector('select'),'ES000004');await sleep(800);const tg=mf('切り替える価格の世代').querySelector('select');setsel(tg,tg.options[3].value);await sleep(300);};"
    "const upload=async(text,name)=>{const inp=document.querySelector('input[type=file]');const dt=new DataTransfer();dt.items.add(new File([text],name||'取込テスト.csv',{type:'text/csv'}));inp.files=dt.files;inp.dispatchEvent(new Event('change',{bubbles:true}));await sleep(2000);};"
    "const csvText=async(entity,fn)=>{const res=await fetch('/api/domain/csv/export',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','x-es-site':'ops'},body:JSON.stringify({args:{entity:entity,scope:{site:'ops'}}})});"
    "const t=await res.json();const esc=v=>'\"'+String(v==null?'':v).replace(/\"/g,'\"\"')+'\"';const rows=[t.head].concat(t.rows);fn(t,rows);return '\\ufeff'+rows.map(r=>r.map(esc).join(',')).join('\\r\\n');};"
)
TRIG = {"button": "click", "link": "click", "text": "input", "textarea": "input", "select": "select", "month": "input", "date": "input", "check": "check", "radio": "check", "tab": "click", "file": "upload"}
ITEMS = {}
_N = {"n": 0, "m": 0}

LENVI = {
    "文字列 8（数字7桁）": "Chuỗi 8 (7 chữ số)", "文字列 20（数字・ハイフン）": "Chuỗi 20 (số và gạch nối)", "文字列 CU＋連番": "Chuỗi CU + số thứ tự",
    "選択（可／不可）": "Chọn (được / không)", "選択（利用しない／利用する）": "Chọn (không dùng / dùng)", "選択（利用しない／利用する（月額料金あり））": "Chọn (không dùng / dùng (có phí hằng tháng))",
    "選択（COOL便／ES配送便）": "Chọn (giao lạnh / giao ES)", "選択（前倒す／後ろ倒す）": "Chọn (dời sớm / dời muộn)", "選択（ON／OFF）": "Chọn (ON / OFF)",
    "選択（プラン）": "Chọn (gói)", "選択（コース）": "Chọn (course)", "選択（価格プランの世代）": "Chọn (thế hệ giá của gói)",
    "選択（なし／値上げ／値下げ／無料提供）＋金額": "Chọn (không / tăng giá / giảm giá / cung cấp miễn phí) + số tiền",
    "整数 0〜999,999,999（円）": "Số nguyên 0–999.999.999 (yên)", "整数 0〜9,999（食／日）": "Số nguyên 0–9.999 (suất/ngày)", "整数 0〜999,999,999（円／月）": "Số nguyên 0–999.999.999 (yên/tháng)",
    "年月（yyyy-mm）": "Năm-tháng (yyyy-mm)", "選択（月〜日・祝日・複数）": "Chọn (Hai đến CN, ngày lễ, nhiều)", "日付": "Ngày",
    "選択（法人／この拠点）": "Chọn (pháp nhân / cơ sở này)", "選択（年月）": "Chọn (năm-tháng)", "選択（法人マスタ）": "Chọn (danh sách pháp nhân)",
}
INITVI = {"可": "Được", "不可": "Không", "利用しない": "Không dùng", "前倒す": "Dời sớm", "OFF（既定 OFF）": "OFF (mặc định OFF)", "なし": "Không", "ES配送便": "ES配送便 (chuyển bằng xe ES)"}

def _add(key, no, ja, vi, sel, kind, d, kw):
    r = {"no": no, "ja": ja, "vi": vi, "sel": sel, "kind": kind, "trig": kw.pop("trig", TRIG.get(kind, "view"))}
    if d: r["detail"] = d
    r.update(kw)
    if isinstance(r.get("len"), str) and r["len"] in LENVI: r["len"] = [r["len"], LENVI[r["len"]]]
    if isinstance(r.get("init"), (list, tuple)) and len(r["init"]) == 2 and r["init"][0] == r["init"][1] and r["init"][0] in INITVI:
        r["init"] = [r["init"][0], INITVI[r["init"][0]]]
    assert key not in ITEMS, key
    ITEMS[key] = r
    return r

def big(key, ja, vi, sel, kind="area", d=None, **kw):
    _N["n"] += 1; _N["m"] = 0
    return _add(key, str(_N["n"]), ja, vi, sel, kind, d, kw)

def sub(key, ja, vi, sel, kind="label", d=None, **kw):
    _N["m"] += 1
    return _add(key, "%d.%d" % (_N["n"], _N["m"]), ja, vi, sel, kind, d, kw)

def P(*keys):
    return [ITEMS[k] for k in keys]

def LK(ent, id, key, label, other="伊藤 美咲"):
    """他のユーザーが編集中（I02）＋先に保存された（E31）の状態を作る（API で他人の編集中の記録を入れ、画面で直したあとに版を2回進める）"""
    ap = ("const ap=async(op,args)=>{const r=await fetch('/api/ops/area/contracts/'+op,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','x-es-site':'ops'},body:JSON.stringify({args})});return r.json();};")
    return (ap +
        "await ap('presence',{entity:'%s',id:'%s',accountId:'Ad00011',name:'%s'});" % (ent, id, other) +
        "btn('編集').click();await sleep(1800);" +
        "setv(ctl('%s'),'（別の人が保存する前に画面で直した内容）');await sleep(200);" % label +
        "const d=await ap('%s',{id:'%s'});const o=d.values['%s']||'';" % (ent, id, key) +
        "const v=Object.assign({},d.values);v['%s']=o+'*';await ap('save',{entity:'%s',id:'%s',values:v,tables:d.tables,baseVersion:d.version});" % (key, ent, id) +
        "const d2=await ap('%s',{id:'%s'});const w=Object.assign({},d2.values);w['%s']=o;await ap('save',{entity:'%s',id:'%s',values:w,tables:d2.tables,baseVersion:d2.version});" % (ent, id, key, ent, id) +
        "q('.pbtn button.save').click();await sleep(900);")

def V(id, code, ja, vi, url, keys, setup="", note=None, full=True, wait=None, **kw):
    v = {"id": id, "code": code, "state": [ja, vi], "url": url, "setup": (H + setup) if setup else "", "full": full, "note": note or ["", ""], "items": P(*keys)}
    if wait is not None: v["wait"] = wait
    v.update(kw)
    return v

U = lambda ja, vi: [ja, vi]
CSVIN = ["子契約一覧の CSV取込 の権限（フル権限・システム管理だけ）", "Quyền CSV取込 của 子契約一覧 (chỉ フル権限・システム管理)"]
EDIT = ["子契約一覧の 編集 の権限（フル権限・システム管理・CS）", "Quyền 編集 của 子契約一覧 (フル権限・システム管理・CS)"]
BULKP = ["価格世代の一括切替の権限（フル権限・システム管理だけ。子契約の「作成」と同じ扱い）", "Quyền đổi hàng loạt thế hệ giá (chỉ フル権限・システム管理; xử lý như quyền \"tạo\" hợp đồng con)"]
INIT_BLANK = ["空欄（更新の行は今の値のまま）", "Trống (dòng cập nhật giữ giá trị cũ)"]
SCOPE_NOTE = ["保存のとき「この子契約だけ／この子契約以降すべて」を選ぶ（サイクル月ごと＝子契約が持つ）。", "Khi lưu chọn \"この子契約だけ / この子契約以降すべて\" (giữ theo tháng chu kỳ = do hợp đồng con giữ)."]

# ================================================================ AW_CONT_001 一覧
big("l_head", "ヘッダー", "Đầu trang", ".es-pagehead", "area", ["パンくず（法人・契約管理 / 子契約）・画面名・操作ボタン（価格世代を一括切替・CSV取込・CSV出力）。権限がないボタンは出さない。", "Breadcrumb (法人・契約管理 / 子契約), tên màn hình, nút thao tác (価格世代を一括切替・CSV取込・CSV出力). Nút không có quyền thì không hiện."])
sub("l_crumb", "パンくず", "Breadcrumb", ".es-breadcrumb", "label", ["「法人・契約管理 / 子契約」。リンクは動かない（表示だけ）。", "「法人・契約管理 / 子契約」. Liên kết không hoạt động (chỉ hiển thị)."])
sub("l_title", "画面名", "Tên màn hình", ".es-pagehead__title", "label", ["「子契約一覧」", "Tiêu đề 「子契約一覧」"])
sub("l_bulk", "価格世代を一括切替", "Đổi hàng loạt thế hệ giá", ".es-pagehead__actions button::価格世代を一括切替", "button", ["押すと「価格世代を一括切替」のモーダル（AW_CONT_004）を開く。プラン・いま使っている価格の世代を条件に、未確定の子契約の ① 費目を別の価格の世代で作り直す。フル権限・システム管理だけに出す（確認メモ Q2＝B）。", "Mở modal \"価格世代を一括切替\" (AW_CONT_004). Theo điều kiện gói / thế hệ giá đang dùng, dựng lại hạng mục ① của hợp đồng con chưa xác định theo thế hệ giá khác. Chỉ hiện với フル権限・システム管理 (確認メモ Q2 = B)."], cond=BULKP,
    demo_ok=["コードは子契約の編集権限があれば出す（CS の R/U も押せる）。フル権限・システム管理だけに絞る宿題（domain:bulk.start の権限・Q2＝B）", "Code hiện nếu có quyền sửa hợp đồng con (CS R/U cũng bấm được). Việc phải sửa: giới hạn cho フル権限・システム管理 (quyền domain:bulk.start; Q2 = B)"])
sub("l_csvin", "CSV取込", "Nhập CSV", ".es-pagehead__actions button::CSV取込", "button", ["子契約CSV取込（AW_CONT_005）へ。キーは 親契約番号＋適用開始（その月から後ろの未確定の月に当てる）。子契約は CSV では作れない。", "Mở 子契約CSV取込 (AW_CONT_005). Khóa = 親契約番号 + 適用開始 (áp dụng cho các tháng chưa xác định từ tháng đó trở đi). Không tạo hợp đồng con bằng CSV."], cond=CSVIN, pattern="P-CSV")
sub("l_csvout", "CSV出力", "Xuất CSV", ".es-pagehead__actions button::CSV出力", "button", ["検索条件のとおりの全件・システムにある項目すべて。閲覧できる役割すべてに出す。", "Toàn bộ theo điều kiện tìm kiếm, mọi mục có trong hệ thống. Hiện với mọi vai trò xem được."], pattern="P-CSV-OUT", err=["S12"])
big("l_search", "検索条件", "Điều kiện tìm kiếm", ".es-search", "area", ["検索条件は「検索」か Enter で反映する。「未適用」の印は出さない。", "Điều kiện chỉ áp dụng khi nhấn \"検索\" hoặc Enter. Không hiện dấu \"未適用\"."], pattern="P-LIST",
    )
sub("l_kw", "キーワード", "Từ khóa", ".es-search input[aria-label='子契約ID、拠点名、法人名']", "text", ["子契約ID・拠点名・法人名の部分一致。", "Khớp một phần với 子契約ID・拠点名・法人名."], req="－", len="文字列 60", ex=["CP0000001", "Một phần ID, tên cơ sở hoặc pháp nhân"])
sub("l_month", "契約・サイクル月", "Tháng chu kỳ hợp đồng", ".es-search select[aria-label='契約・サイクル月']", "select", ["一覧にあるサイクル月（新しい月が上）から選ぶ。", "Chọn từ các tháng chu kỳ có trong danh sách (tháng mới ở trên)."], req="－", len=U("選択（年月）", "Chọn (năm-tháng)"), init=U("契約・サイクル月（すべて）", "Tháng chu kỳ (tất cả)"), ex=["2026-11", "Chọn 1 tháng"])
sub("l_kind", "契約種別", "Loại hợp đồng", ".es-search select[aria-label='契約種別']", "select", ["選択肢：本導入／お試しキャンペーン。", "Lựa chọn: 本導入 / お試しキャンペーン."], req="－", len=U("選択（本導入／お試しキャンペーン）", "Chọn (chính thức / chiến dịch dùng thử)"), init=U("契約種別（すべて）", "Loại hợp đồng (tất cả)"), ex=["お試しキャンペーン", "Chọn 1 loại"])
sub("l_plan", "プラン", "Gói", ".es-search select[aria-label='プラン']", "select", ["一覧にあるプランから選ぶ。", "Chọn từ các gói có trong danh sách."], req="－", len=U("選択（プラン）", "Chọn (gói)"), init=U("プラン（すべて）", "Gói (tất cả)"), ex=["ES000004 100プラン", "Chọn 1 gói"])
sub("l_ship", "配送区分", "Loại giao hàng", ".es-search select[aria-label='配送区分']", "select", ["選択肢：ES配送便／COOL便。", "Lựa chọn: ES配送便 / COOL便."], req="－", len=U("選択（COOL便／ES配送便）", "Chọn (giao lạnh / giao ES)"), init=U("配送区分（すべて）", "Loại giao hàng (tất cả)"), ex=["COOL便", "Chọn 1 loại"])
sub("l_bst", "請求ステータス（前払い）", "Trạng thái hóa đơn (trả trước)", ".es-search select[aria-label='請求ステータス（前払い）']", "select", ["選択肢：生成済／① 確定／拠点確定／法人確定／請求済（運営は5段階。法人Webは 未確定／確定／請求済）。", "Lựa chọn: 生成済 / ① 確定 / 拠点確定 / 法人確定 / 請求済 (vận hành 5 bậc; 法人Web gồm 未確定 / 確定 / 請求済)."], req="－", len=U("選択（5段階）", "Chọn (5 bậc)"), init=U("請求ステータス（前払い）（すべて）", "Trạng thái hóa đơn (trả trước) (tất cả)"), ex=["請求済", "Chọn 1 trạng thái"],
    open=["請求ステータスの値：検索の選択肢は5段階、一覧の値は 未確定／確定／請求済 の3値（運営E の設計書と合わせて決める）", "Giá trị trạng thái hóa đơn: lựa chọn tìm kiếm có 5 bậc, giá trị ở danh sách chỉ 3 (未確定 / 確定 / 請求済) (quyết cùng thiết kế của 運営E)"], ask="運営E の確認メモ・phiên gộp")
sub("l_gen", "生成方法", "Cách sinh", ".es-search select[aria-label='生成方法']", "select", ["選択肢：日次バッチ／手動生成／年一括。手で作った行は「手動生成」の印で見分ける。", "Lựa chọn: 日次バッチ / 手動生成 / 年一括. Dòng tạo bằng tay phân biệt bằng dấu \"手動生成\"."], req="－", len=U("選択（日次バッチ／手動生成／年一括）", "Chọn (batch hằng ngày / tạo tay / gộp năm)"), init=U("生成方法（すべて）", "Cách sinh (tất cả)"), ex=["手動生成", "Chọn 1 cách"])
sub("l_clear", "クリア", "Xóa điều kiện", ".es-search button::クリア", "button", ["条件を初期値に戻し、一覧も初期の表示に戻す。", "Đưa điều kiện về ban đầu và hiển thị lại danh sách ban đầu."])
sub("l_go", "検索", "Tìm kiếm", ".es-search button[type=submit]", "button", ["条件を一覧に反映し、1ページ目に戻る。", "Áp dụng điều kiện vào danh sách và về trang 1."])
sub("l_sort", "並べ替え", "Sắp xếp", ".es-search select[aria-label='並べ替え']", "select", ["並べ替える列（一覧の全列）と、昇順／降順の2つの選択。列の見出しを押しても切り替わる（昇順 ⇄ 降順。▲▼で向きを出す）。初期の並びは更新日時の降順（台帳 一覧の初期の並び）。並べ替えは「検索」を押さなくても効き、1ページ目に戻る。", "Hai ô chọn: cột sắp xếp (mọi cột của danh sách) và tăng / giảm. Nhấn tiêu đề cột cũng đổi được (tăng ⇄ giảm, hiện ▲▼). Thứ tự ban đầu: 更新日時 giảm dần (台帳 一覧の初期の並び). Sắp xếp có hiệu lực ngay không cần nhấn \"検索\" và quay về trang 1."], req="－", len=["選択（列）＋昇順／降順", "Chọn (cột) + tăng / giảm"], init=["更新日時の降順", "更新日時 giảm dần"], ex=["子契約ID・昇順", "Chọn cột rồi đổi tăng / giảm"])
big("l_table", "子契約の一覧", "Bảng hợp đồng con", ".es-table", "table", ["1ページ 10件（10／20／50）。子契約は削除しないので「削除」の列は置かない。0件のときは I01 を表の中に出す。", "10 dòng/trang (10/20/50). Hợp đồng con không xóa nên không có cột \"削除\". Khi 0 dòng hiện I01 trong bảng."], pattern="P-LIST", err=["I01"],
    demo_ok=["コードの 0件の文言は「条件に一致するデータがありません。条件を変えるか「クリア」を押してください。」（I01 に揃える・H1）", "Câu 0 dòng trong code là \"条件に一致するデータがありません。条件を変えるか「クリア」を押してください。\" (đồng nhất với I01; H1)"])
sub("l_id", "子契約ID", "ID hợp đồng con", ".es-table th::子契約ID", "link", ["CP＋7桁−yyyymm（例：CP0000001-202610）。押すと子契約詳細（AW_CONT_002）へ。仮登録の行は「仮登録」のバッジが付く。", "CP + 7 số - yyyymm (vd CP0000001-202610). Bấm để mở 子契約詳細 (AW_CONT_002). Dòng 仮登録 có badge \"仮登録\"."], open=["親契約・子契約の ID の桁（台帳 B の記載は CP＋6桁、基本設計・コード・契約_00 は CP＋7桁）", "Số chữ số ID hợp đồng cha / con (台帳 B ghi CP + 6 số, 基本設計・code・契約_00 ghi CP + 7 số)"], ask="hong（台帳の書き間違いか）")
sub("l_m", "契約・サイクル月（列）", "Tháng chu kỳ hợp đồng (cột)", ".es-table th::契約・サイクル月", "label", ["yyyy-mm。初期の並びはこの列の降順。", "yyyy-mm. Nhấn tiêu đề cột để sắp xếp."])
sub("l_br", "拠点", "Cơ sở", ".es-table th::拠点", "label", ["拠点名。", "Tên cơ sở."])
sub("l_corp", "所属法人", "Pháp nhân trực thuộc", ".es-table th::所属法人", "label", ["法人名。", "Tên pháp nhân."])
sub("l_kind_c", "契約種別（列）", "Loại hợp đồng (cột)", ".es-table th::契約種別", "label", ["本導入／お試しキャンペーン。", "本導入 / お試しキャンペーン."])
sub("l_plan_c", "プラン（列）", "Gói (cột)", ".es-table th::プラン", "label", ["「プランID プラン名」。", "\"プランID プラン名\"."])
sub("l_ship_c", "配送区分・納品回数", "Loại giao hàng・số lần giao", ".es-table th::配送区分・納品回数", "label", ["「ES配送便 月2回」「COOL便 冷蔵2回・冷凍2回・資材0回」。", "\"ES配送便 月2回\", \"COOL便 冷蔵2回・冷凍2回・資材0回\"."])
sub("l_bm", "請求月（前払い）", "Tháng hóa đơn (trả trước)", ".es-table th::請求月（前払い）", "label", ["サイクル月＋請求書発行リードタイム（例：2026-10）。「〜分」は付けない。", "Tháng chu kỳ + lead time phát hành hóa đơn (vd 2026-10). Không thêm \"〜分\"."])
sub("l_amt", "当月請求額（税抜）", "Số tiền hóa đơn tháng này (chưa thuế)", ".es-table th::当月請求額（税抜）", "label", ["金額の列は右寄せ。「66,000円」の形（税抜）。", "Cột số tiền căn phải. Dạng \"66,000円\" (chưa thuế)."], pattern="P-LIST")
sub("l_bst_c", "請求ステータス", "Trạng thái hóa đơn", ".es-table th::請求ステータス", "label", ["「前払い ／ 後払い」の2つの状態（例：未確定 ／ —）。", "2 trạng thái \"trả trước ／ trả sau\" (vd 未確定 ／ —)."])
sub("l_gen_c", "生成方法（列）", "Cách sinh (cột)", ".es-table th::生成方法", "label", ["日次バッチ／手動生成／年一括。手で作った行は「手動生成」。誰がいつ作ったかは変更履歴に残る。法人Webには出さない。", "日次バッチ / 手動生成 / 年一括. Dòng tạo bằng tay là \"手動生成\". Ai tạo và khi nào lưu ở lịch sử. Không hiện ở 法人Web."])
sub("l_act", "操作（編集）", "Thao tác (sửa)", ".es-table th::操作", "button", ["鉛筆を押すと子契約編集（AW_CONT_003）へ。編集の権限がある役割だけに出す。仮登録の行は鉛筆の代わりに「申請で編集」。", "Bấm bút để mở 子契約編集 (AW_CONT_003). Chỉ hiện với vai trò có quyền sửa. Dòng 仮登録 hiện \"申請で編集\" thay cho bút."], cond=EDIT)
sub("l_apply", "申請で編集", "Sửa ở đơn", ".es-table button::申請で編集", "button", ["仮登録の拠点の子契約の行だけ。契約申請管理の申請詳細へ（決定 28-146）。", "Chỉ ở dòng hợp đồng con của cơ sở 仮登録. Mở 申請詳細 của 契約申請管理 (quyết định 28-146)."])
sub("l_upd", "更新日時", "Ngày giờ cập nhật", ".es-table th::更新日時", "label", ["yyyy-mm-dd HH:MM。保存・承認・CSV取込などで書き換わった日時（同時更新の版と一緒に進む）。初期の並びはこの列の降順（台帳 一覧の初期の並び）。列の見出しを押すと並べ替え。", "yyyy-mm-dd HH:MM. Ngày giờ dữ liệu bị ghi đổi do lưu / duyệt / nhập CSV (tăng cùng phiên bản đồng thời). Thứ tự ban đầu: cột này giảm dần (台帳 一覧の初期の並び). Nhấn tiêu đề cột để sắp xếp."])
big("l_pager", "ページ送り", "Phân trang", ".es-pagination", "area", ["「n件中 a–b件」・前後のページ・ページ番号・表示件数（10／20／50件／ページ）。", "\"n件中 a–b件\", trang trước/sau, số trang, số dòng (10/20/50 件／ページ)."], pattern="P-LIST")

# ================================================================ AW_CONT_002 詳細
big("d_head", "ヘッダー", "Đầu trang", ".phead", "area", ["パンくず・画面名＋子契約ID・要約（子契約ID・拠点・契約・サイクル月・契約種別・契約ステータス・① 前払い・② 実績精算・合計（参考））・ボタン。入力欄はすべて読むだけ。", "Breadcrumb, tên màn hình + ID hợp đồng con, tóm tắt (ID, cơ sở, tháng chu kỳ, loại hợp đồng, trạng thái, ① trả trước, ② quyết toán thực tế, tổng (tham khảo)), nút. Mọi ô chỉ xem."], pattern="P-FORM")
sub("d_crumb", "パンくず", "Breadcrumb", ".phead .crumb", "label", ["「法人・契約管理 / 子契約一覧 / 子契約詳細」。", "「法人・契約管理 / 子契約一覧 / 子契約詳細」."])
sub("d_title", "画面名・子契約ID", "Tên màn hình・ID hợp đồng con", ".phead h2", "label", ["「子契約詳細 CP0000001-202703」。", "「子契約詳細 CP0000001-202703」."])
sub("d_sum", "要約", "Tóm tắt", ".sumbar", "label", ["どのタブでも見える。① 前払い・② 実績精算は「請求月／状態」で出す（運営だけ）。", "Thấy ở mọi tab. ① trả trước và ② quyết toán thực tế hiện dạng \"tháng hóa đơn／trạng thái\" (chỉ vận hành)."])
sub("d_edit", "編集", "Sửa", ".pbtn button.save", "button", ["子契約編集（AW_CONT_003）へ。", "Mở 子契約編集 (AW_CONT_003)."], cond=EDIT)
sub("d_apply", "申請詳細で編集", "Sửa ở 申請詳細", ".pbtn button::申請詳細で編集", "button", ["仮登録のとき「編集」の代わりに出す。", "Khi 仮登録, hiện thay cho \"編集\"."])
big("d_prov", "仮登録中の帯", "Dải đang đăng ký tạm", ".provbar", "area", ["仮登録の拠点の子契約だけ。I105 と、編集は契約申請管理の申請詳細で行うことを案内する。", "Chỉ với hợp đồng con của cơ sở 仮登録. Hiện I105 và hướng dẫn sửa ở 申請詳細 của 契約申請管理."], err=["I105"],
    demo_ok=["コードの帯の文言は I105 と少し違う。I105 に揃える", "Câu trong dải của code hơi khác I105. Đồng nhất với I105"])
big("d_pend", "承認待ちの申請の帯", "Dải có đơn chờ duyệt", ".provbar.pendnote", "area", ["承認待ちの申請（CH-…）があるとき出す：「承認待ちの申請 CH-…（プランの変更）があります。申請の対象の項目（…）は、承認後に変えられます」。承認すると申請の内容で書き換わる。対象の項目は編集画面で入力できず、項目の下に I104 が出る。", "Hiện khi có đơn chờ duyệt (CH-…): \"承認待ちの申請 CH-…（プランの変更）があります。申請の対象の項目（…）は、承認後に変えられます\". Khi duyệt sẽ ghi đè theo nội dung đơn. Mục đối tượng không nhập được ở màn sửa và hiện I104 dưới mục."], err=["I104"])
big("d_stick", "タブ・項目の検索", "Tab・tìm mục", ".stick", "area", ["タブ（契約／料金・請求／設備・オプション／変更履歴）。タブは URL（?tab=）に持つ。項目の検索（「/」）・すべて閉じる／開く・入力する項目だけ・カードの目次。", "Tab (契約 / 料金・請求 / 設備・オプション / 変更履歴). Tab giữ ở URL (?tab=). Tìm mục (\"/\"), đóng/mở tất cả, chỉ các mục nhập, mục lục thẻ."], pattern="P-TAB",
    demo_ok=["4タブは仕様（契約_00 §0.1）と同じ（確認メモ H11 は解消済み）。タブは URL の ?tab= で最初に開くタブを受けるが、タブを切り替えても URL は変わらない（再読み込みで最初のタブに戻る）。P-TAB（タブを URL に持つ）に合わせる", "4 tab giống spec (契約_00 §0.1) (H11 đã xong). Tab ban đầu nhận từ ?tab= trên URL nhưng khi chuyển tab URL không đổi (tải lại thì về tab đầu). Cần theo P-TAB (giữ tab trên URL)"])
sub("d_tabs", "タブ", "Tab", ".tabs[role=tablist]", "tab", ["契約／料金・請求／設備・オプション／変更履歴（料金・請求と変更履歴は運営だけ見る）。", "契約 / 料金・請求 / 設備・オプション / 変更履歴 (料金・請求 và 変更履歴 chỉ vận hành xem)."], pattern="P-TAB")
sub("d_search", "項目を検索", "Tìm mục", ".tools input[type=search]", "text", ["項目名・値・説明に含まれる文字で絞り込む。「/」キーで入力欄へ。", "Lọc theo chữ trong tên mục / giá trị / giải thích. Phím \"/\" để vào ô."], req="－", len="文字列 60", ex=["配送", "Chữ trong tên hoặc giá trị mục"])
sub("d_fold", "すべて閉じる／すべて開く", "Đóng tất cả / mở tất cả", ".tools button.linkbtn", "button", ["今のタブのカードをまとめて閉じる／開く。", "Đóng / mở cùng lúc các thẻ của tab hiện tại."])
sub("d_editonly", "入力する項目だけ", "Chỉ các mục nhập", ".tools label::入力する項目だけ", "check", ["チェックすると読むだけの項目を隠す。", "Tích thì ẩn các mục chỉ xem."], req="－", init=U("チェックなし", "Không tích"), ex=["チェックする", "Tích để ẩn mục chỉ xem"])
sub("d_idx", "カードの目次", "Mục lục thẻ", ".idx", "label", ["カード名と項目数。押すとそのカードへ移る。", "Tên thẻ và số mục. Bấm để chuyển tới thẻ đó."])
big("d_child", "カード「子契約」", "Thẻ \"子契約\"", ".ch::子契約^", "area", ["子契約ID・契約・サイクル月・親契約番号（契約ID）。子契約IDは 親契約番号＋「-yyyymm」。1サイクル＝1子契約（サイクル月＝14番目の枠 B7 が属する月）。", "ID hợp đồng con, tháng chu kỳ, số hợp đồng cha. ID hợp đồng con = số hợp đồng cha + \"-yyyymm\". 1 chu kỳ = 1 hợp đồng con (tháng chu kỳ = tháng chứa ô thứ 14 là B7)."])
sub("d_scopebtn", "変更の適用範囲（保存時に確認）", "Phạm vi áp dụng thay đổi (xác nhận khi lưu)", ".f button::変更の適用範囲（保存時に確認）", "button", ["項目としては画面に置かない（仕様）。保存ボタンを押したとき、後ろの子契約が生成済みのときだけダイアログで選ばせる。", "Không đặt thành mục trên màn hình (spec). Chỉ khi bấm lưu và có hợp đồng con phía sau đã sinh thì mới hiện dialog để chọn."],
    demo_ok=["コードにはこの名前のボタンが「子契約」カードにある（押すと保存の処理）。仕様では置かない（契約_05 契約 No.4）", "Code có nút tên này ở thẻ \"子契約\" (bấm thì xử lý lưu). Spec không đặt (契約_05 mục 4)"])
big("d_contract", "カード「契約」", "Thẻ \"契約\"", ".ch::契約^", "area", ["プランID・メニュー種別（コース）・適用開始月・適用終了月・解約時の回収額（上書き）・適用された価格プラン・企業負担額・税率（プランから）。惣菜買取（運営のみ）・基準数のパターンは仕様にあるが、いまの画面にない（基準数のパターンは拠点の画面：AW_BRAN）。", "プランID・メニュー種別（コース）・適用開始月・適用終了月・解約時の回収額（上書き）・適用された価格プラン・企業負担額・税率（プランから）. 惣菜買取 (chỉ vận hành) và 基準数のパターン có trong spec nhưng màn hình hiện chưa có (基準数のパターン nằm ở màn cơ sở: AW_BRAN)."])
sub("d_plan", "プランID", "ID gói", ".f::プランID*", "label", ["「プランID プラン名」（例：ES000004　100プラン）。プラン変更はこの子契約（翌月分）で行う。法人Webからの変更は運営の承認が必須。", "\"プランID tên gói\" (vd ES000004　100プラン). Đổi gói làm ở hợp đồng con này (phần tháng sau). Thay đổi từ 法人Web bắt buộc vận hành duyệt."])
sub("d_price", "適用された価格プラン", "Gói giá được áp dụng", ".f::適用された価格プラン*", "label", ["プランマスタの価格プランの世代（元の料金／改訂第一回目／第二回目／第三回目…）。子契約ごと（毎月）に選べる（決定 28-181）。初期値：自動生成は前の子契約と同じ世代、新規・プラン変更は公開用の世代。① の請求が確定したあとは変えられない。選んだ世代の金額は子契約に固める。", "Thế hệ giá-gói của プランマスタ (giá gốc / lần sửa 1 / 2 / 3...). Chọn được theo từng hợp đồng con (hằng tháng) (quyết định 28-181). Mặc định: tự sinh dùng cùng thế hệ với hợp đồng con trước; đăng ký mới / đổi gói dùng thế hệ công khai. Sau khi hóa đơn ① đã chốt thì không đổi được. Số tiền của thế hệ đã chọn được cố định vào hợp đồng con."])
sub("d_subsidy", "企業負担額・税率（プランから）", "Mức công ty chịu・thuế suất (từ gói)", ".f::企業負担額・税率（プランから）*", "label", ["生成時にプランマスタから固める：企業負担額（既定100円税込・1食）／企業負担分の税率（既定 軽減8%）／基本料金の税率（既定 標準10%）。① のプラン料金の2行はこの値から立てる。読むだけ。", "Cố định từ プランマスタ khi sinh: mức công ty chịu (mặc định 100 yên đã thuế/suất) / thuế suất phần công ty chịu (mặc định giảm 8%) / thuế suất phí cơ bản (mặc định chuẩn 10%). 2 dòng phí gói của ① dựng từ giá trị này. Chỉ xem."])
sub("d_buyout", "惣菜買取", "Mua đứt món ăn kèm", "-", "label", ["運営だけ。ON の契約は在庫管理の対象外とし、棚卸・事務手数料・管理ロスの対象にしない（請求ルール 2-13・REQ-CT-305）。", "Chỉ vận hành. Hợp đồng ON không thuộc đối tượng quản lý tồn kho, không tính kiểm kê・phí thủ tục・hao hụt quản lý (請求ルール 2-13・REQ-CT-305)."],
    demo_ok=["コードの画面にこの項目がない（仕様の契約_05 契約 No.8。足す宿題）", "Màn hình code chưa có mục này (契約_05 mục 8 của spec. Việc phải thêm)"])
big("d_app", "カード「アプリの利用設定（このサイクル月）」", "Thẻ \"アプリの利用設定 (tháng chu kỳ này)\"", ".ch::アプリの利用設定^", "area", ["ユーザー現金利用・1日上限数（1人あたり）・1ヶ月上限金額（1人あたり）・ゲストモード・ES-QR。持ち主は子契約（サイクル月ごと）。法人Webの拠点の「編集」で直すと今のサイクル以降のすべての子契約に効く（運営は保存時に「この子契約だけ」も選べる）。料金のある設定（ゲストモード・ES-QR）は、オーダー締切で決まるサイクルから効く。", "ユーザー現金利用・1日上限数（1人あたり）・1ヶ月上限金額（1人あたり）・ゲストモード・ES-QR. Người giữ là hợp đồng con (theo tháng chu kỳ). Sửa ở \"編集\" của cơ sở trên 法人Web thì có hiệu lực với mọi hợp đồng con từ chu kỳ hiện tại trở đi (vận hành lúc lưu cũng chọn được \"この子契約だけ\"). Thiết lập có phí (ゲストモード・ES-QR) có hiệu lực từ chu kỳ quyết theo hạn chót đặt hàng."])
big("d_ship", "カード「配送・納品スケジュール」", "Thẻ \"配送・納品スケジュール\"", ".ch::配送・納品スケジュール^", "area", ["配送区分・配送番号・納品不可曜日・納品予定日になった場合・配送備考・設置フロア。", "配送区分・配送番号・納品不可曜日・納品予定日になった場合・配送備考・設置フロア."])
sub("d_vm", "自販機の拠点の配送区分", "Loại giao hàng của cơ sở máy bán hàng", ".vmfix", "label", ["設備が自販機の拠点（コース＝ESライト（自販機））は、配送区分を ES配送便に固定して表示し、選択肢は出さない（運営・法人とも変えられない・決定 28-19）。注記「設備が自販機の拠点のため、配送区分は ES配送便に固定です（決定 28-19）。」", "Cơ sở có thiết bị là máy bán hàng tự động (course = ESライト（自販機）) cố định 配送区分 là ES配送便 và không hiện lựa chọn (cả vận hành và pháp nhân đều không đổi được; quyết định 28-19). Chú thích \"設備が自販機の拠点のため、配送区分は ES配送便に固定です（決定 28-19）。\"."], err=[],
    demo_ok=["コードは注記に「決定 28-19」と書く。設計書の注記の文言は決定番号を外す案（phiên gộp で確認）", "Code ghi \"決定 28-19\" trong chú thích. Phương án: bỏ số quyết định khỏi chú thích của thiết kế (xác nhận ở phiên gộp)"])
big("d_route", "カード「配送ルート設定（テーブル）」", "Thẻ \"配送ルート設定\"", ".ch::配送ルート設定（テーブル）^", "area", ["配送種別（冷蔵配送／冷凍配送／資材配送）ごとに1行：ピッキング倉庫・運送会社・納品会社・途中経由1・リードタイム・配送回数・配送パターン・納品サイクル・問い合わせ確認URL。納品会社は必須（中継しないときは運送会社と同じ会社）・途中経由1も必須（中継しないときは「なし」）。配送回数は種別ごと・0回は保存できない。申込ではお客様が希望できず、受付の詳細情報設定で運営が設定する。", "Mỗi 配送種別 (冷蔵配送 / 冷凍配送 / 資材配送) 1 dòng: kho lấy hàng, công ty vận chuyển, công ty giao, điểm trung chuyển 1, lead time, số lần giao, mẫu giao, chu kỳ giao, URL tra cứu. 納品会社 bắt buộc (nếu không trung chuyển thì dùng cùng công ty với vận chuyển), 途中経由1 cũng bắt buộc (không trung chuyển thì chọn \"なし\"). Số lần giao theo từng loại, không lưu được 0 lần. Khách không chọn được khi đăng ký, vận hành thiết lập ở 詳細情報設定 của tiếp nhận."])
big("d_slot", "カード「回ごとのルート（この回だけ変える）」", "Thẻ \"回ごとのルート (chỉ đổi lần này)\"", ".ch::回ごとのルート^", "area", ["案B（2026/10/03）：その回だけ、上の行（温度帯ごとの標準のルート）と違うピッキング倉庫・配送会社・中継先で運ぶ。回は上の行の納品サイクルから選ぶ。入れない回は上の行のルート。一括変更はこの回を変えない。", "Phương án B (2026/10/03): chỉ lần đó dùng kho / công ty giao / điểm trung chuyển khác với dòng trên (lộ trình chuẩn theo vùng nhiệt). Chọn lần từ chu kỳ giao của dòng trên. Lần không nhập dùng lộ trình dòng trên. Đổi hàng loạt không đổi các lần này."])
big("d_memo", "カード「メモ」", "Thẻ \"メモ\"", ".ch::メモ^", "area", ["運営メモ（内部メモ）・プラン外の備考（申込時）。運営メモは運営だけが見る（法人画面には出さない）。", "運営メモ（内部メモ）・プラン外の備考（申込時）. 運営メモ chỉ vận hành xem (không hiện ở màn pháp nhân)."])
big("d_pay", "カード「支払情報」", "Thẻ \"支払情報\"", ".ch::支払情報^", "area", ["支払方法・支払サイクル・請求先・請求書発行リードタイム（スナップショット）。請求先が指す側（法人または拠点）の設定を生成時に引き継いで固める。ここでは編集しない。変更は「まだ作っていないサイクル月から」。", "支払方法・支払サイクル・請求先・請求書発行リードタイム (snapshot). Cố định từ thiết lập của phía mà nơi nhận hóa đơn chỉ tới (pháp nhân hoặc cơ sở) khi sinh. Không sửa ở đây. Thay đổi áp dụng \"từ tháng chu kỳ chưa tạo\"."],
    demo_ok=["コードの支払情報は「支払方法」「支払サイクル」の2項目。請求先・請求書発行リードタイムの2項目を足す宿題（契約_05 の追加）", "Thông tin thanh toán của code chỉ có 2 mục \"支払方法\" \"支払サイクル\". Việc phải thêm 2 mục: nơi nhận hóa đơn・lead time phát hành hóa đơn (bổ sung ở 契約_05)"])
big("d_billcard", "カード「請求」", "Thẻ \"請求\"", ".ch::請求^", "area", ["請求詳細を開く：請求 ＞ 請求の確定・請求書 の、この子契約の請求詳細（① 固定額・② 実績精算・③ 調整）へ。調整（今月だけ・毎月続く費用）の登録もそちら。", "Mở chi tiết hóa đơn: tới chi tiết hóa đơn của hợp đồng con này ở 請求 ＞ 請求の確定・請求書 (① số tiền cố định・② quyết toán thực tế・③ điều chỉnh). Đăng ký điều chỉnh (chi phí 1 tháng / kéo dài hằng tháng) cũng ở đó."])
big("d_welfare", "カード「値引き・負担額」", "Thẻ \"値引き・負担額\"", ".ch::値引き・負担額^", "area", ["福利厚生の適用（ON／OFF・既定 OFF）・価格調整の適用（なし／値上げ／値下げ／無料提供（企業負担）＋金額・10円単位）。福利厚生の適用は ON にすると請求書でプラン料金を2行（基本料金10%／福利厚生〈企業負担分〉8%）に分けて出すだけで、金額と消費税は変わらない。システム管理だけに見せる（台帳 E 2026-10-05）。価格調整は無料提供も運営承認が必須。", "福利厚生の適用 (ON / OFF, mặc định OFF)・価格調整の適用 (không / tăng giá / giảm giá / cung cấp miễn phí (công ty chịu) + số tiền, đơn vị 10 yên). Bật 福利厚生の適用 chỉ làm hóa đơn tách phí gói thành 2 dòng (phí cơ bản 10% / phúc lợi (phần công ty chịu) 8%), số tiền và thuế không đổi. Chỉ hiện với システム管理 (台帳 E 2026-10-05). 価格調整 kể cả cung cấp miễn phí đều bắt buộc vận hành duyệt."])
sub("d_welf", "福利厚生の適用", "Áp dụng phúc lợi", ".f::福利厚生の適用*", "label", ["システム管理（権限付与を編集できる人）だけに見せる。ほかの役割には項目ごと出さない。", "Chỉ hiện với システム管理 (người sửa được 権限付与). Vai trò khác không hiện cả mục."], cond=["システム管理の役割", "Vai trò システム管理"])
big("d_loan", "カード「設備の異動（この子契約で登録）」", "Thẻ \"設備の異動\"", ".ch::設備の異動^", "area", ["貸出・追加・回収・機種変更の登録はここで行う。ここで登録した行が拠点の「設備・オプション」タブの貸出一覧に反映される（新規貸出＝行を起こす／追加貸出＝貸出数を増やす／回収＝返却済数を増やす／機種変更＝旧を回収して新を起こす）。表：異動区分・対象の貸出ID・設備区分・機種・個体番号・数量・予定日・実施日・理由・備考。「拠点の貸出一覧に反映」で書き込む。確定後（請求済）は追加のみで、反映済みの行は消せない。", "Đăng ký cho mượn / thêm / thu hồi / đổi máy làm ở đây. Dòng đăng ký ở đây được phản ánh vào danh sách cho mượn của tab \"設備・オプション\" của cơ sở (cho mượn mới = tạo dòng / thêm = tăng số lượng cho mượn / thu hồi = tăng số lượng đã trả / đổi máy = thu hồi máy cũ và tạo máy mới). Bảng: loại di chuyển, ID cho mượn, loại thiết bị, máy, số máy, số lượng, ngày dự kiến, ngày thực hiện, lý do, ghi chú. \"拠点の貸出一覧に反映\" để ghi. Sau khi chốt (đã xuất hóa đơn) chỉ thêm được, dòng đã phản ánh không xóa được."])
big("d_optcard", "カード「オプション・割引（このサイクル月）」", "Thẻ \"オプション・割引 (tháng chu kỳ này)\"", ".ch::オプション・割引（このサイクル月）^", "area", ["表：異動区分（追加／変更／終了）・区分（オプション／値引き）・コード・名称・数量・金額・率・適用開始月・適用終了月・理由・備考。このサイクル月にかかるオプション・値引きは子契約が持つ。連動タイプAのオプション（配送回数・ES-QR など）は契約の項目から自動で立ち、ここでは直せない。金額は初期値がマスタの標準金額で、契約ごと・機種参照・ES-QR のオプションは子契約ごとに上書きできる（上書きした行は色を変えて目立たせる）。", "Bảng: loại di chuyển (thêm / sửa / kết thúc), 区分 (オプション / 値引き), mã・tên, số lượng, số tiền・tỷ lệ, tháng bắt đầu, tháng kết thúc, lý do, ghi chú. Tùy chọn / giảm giá áp dụng cho tháng chu kỳ này do hợp đồng con giữ. Tùy chọn loại A liên động (số lần giao, ES-QR...) tự dựng từ mục hợp đồng và không sửa được ở đây. Số tiền mặc định là số tiền chuẩn của master; tùy chọn theo hợp đồng / tham chiếu máy / ES-QR ghi đè được theo hợp đồng con (dòng ghi đè được tô màu nổi bật)."])
big("d_sched", "カード「設置・引揚の予定」", "Thẻ \"設置・引揚の予定\"", ".ch::設置・引揚の予定^", "area", ["設備の引揚希望日／搬入希望日／設置予定日。設備入替・再設置があるときは必須（設備手配のリードタイムは1週間程度）。「引き当てを設備の異動に取り込む」で、自動引き当ての結果を「新規貸出」の行として設備の異動に起こす（すでに貸出中のものは起こさない）。", "Ngày mong muốn thu hồi / lắp / dự kiến lắp đặt thiết bị. Bắt buộc khi đổi / lắp lại thiết bị (lead time chuẩn bị thiết bị khoảng 1 tuần). \"引き当てを設備の異動に取り込む\" tạo kết quả phân bổ tự động thành dòng \"cho mượn mới\" ở 設備の異動 (không tạo cho thiết bị đang cho mượn)."])
big("d_hist", "カード「履歴（子契約）」", "Thẻ \"履歴 (hợp đồng con)\"", ".ch::履歴（子契約）^", "area", ["子契約の変更を見るだけ。列は変更履歴の共通の決まり（日時・操作した人・操作・項目・変更前・変更後・理由）に、契約だけの 変更区分（手入力／CSV取込／自動生成バッチ／変更申請の承認）・適用範囲・承認者・通知の有無 を足す（Q6＝C）。適用範囲は「2026-07 のみ」＝この子契約だけ／「2026-07 以降すべて」＝生成元の設定も更新（後ろが未生成で確認を出さなかった保存も「以降すべて」）。新しい順・直せない・消せない。", "Chỉ xem thay đổi của hợp đồng con. Cột theo quy tắc chung của lịch sử (ngày giờ, người thao tác, thao tác, mục, trước, sau, lý do) cộng thêm 変更区分 (nhập tay / nhập CSV / batch tự sinh / duyệt đơn thay đổi)・適用範囲・承認者・通知の有無 riêng của hợp đồng (Q6 = C). 適用範囲 \"2026-07 のみ\" = chỉ hợp đồng con này / \"2026-07 以降すべて\" = cập nhật cả thiết lập nguồn sinh (lưu mà phía sau chưa sinh nên không hỏi cũng ghi \"以降すべて\"). Mới nhất trước, không sửa / xóa được."], pattern="P-HIST",
    demo_ok=["コードの履歴の列は 変更日時・変更内容・変更者・変更区分・適用範囲・承認者・通知の有無（変更内容は1列）。項目・変更前・変更後・理由に分ける宿題（Q6＝C）", "Cột lịch sử của code: 変更日時, 変更内容, 変更者, 変更区分, 適用範囲, 承認者, 通知の有無 (変更内容 là 1 cột). Việc phải sửa: tách mục / trước / sau / lý do (Q6 = C)"])
big("d_diff", "カード「前月からの差分」", "Thẻ \"前月からの差分\"", ".ch::前月からの差分^", "area", ["前の子契約との差分：適用プラン／コース／配送便／料金改定／単価／免責／月次提供数上限／リードタイム／費目の増減。なぜ金額が変わったかの説明になる。前の子契約から契約の項目が1つでも変わったときは、一覧・詳細にアラートを出す（手で直した箇所の確認漏れを防ぐ・REQ-CT-276）。", "Chênh lệch với hợp đồng con trước: gói áp dụng / course / loại giao / sửa giá / đơn giá / miễn trách / giới hạn suất hằng tháng / lead time / tăng giảm hạng mục. Giải thích vì sao số tiền đổi. Khi có ≥ 1 mục hợp đồng đổi so với hợp đồng con trước thì hiện cảnh báo ở danh sách / chi tiết (tránh quên kiểm tra chỗ sửa tay; REQ-CT-276)."],
    demo_ok=["コードに「変更のアラート」（一覧・詳細に出す印）がない（契約_05 履歴 No.2。足す宿題）", "Code chưa có \"変更のアラート\" (dấu hiện ở danh sách / chi tiết) (契約_05 lịch sử mục 2. Việc phải thêm)"])
big("d_locked", "確定・請求済の子契約", "Hợp đồng con đã chốt / đã xuất hóa đơn", ".phead", "area", ["① の請求が確定・請求済になった子契約は、金額に効く変更（プラン・価格の世代・オプション・価格調整など）ができない。保存しようとすると E113 を出す（請求の調整は請求の画面で）。金額に効かない項目（配送備考・運営メモなど）は直せる。", "Hợp đồng con có hóa đơn ① đã chốt / đã xuất không thể thay đổi ảnh hưởng đến số tiền (gói, thế hệ giá, tùy chọn, điều chỉnh giá...). Khi lưu sẽ hiện E113 (điều chỉnh hóa đơn làm ở màn hóa đơn). Mục không ảnh hưởng số tiền (ghi chú giao hàng, ghi chú vận hành...) vẫn sửa được."], err=["E113"],
    demo_ok=["コードは請求済の子契約も編集・保存できる（適用範囲「以降すべて」のときに直さないだけ）。金額に効く項目の保存を止める宿題（契約_01 §1）", "Code vẫn cho sửa / lưu hợp đồng con đã xuất hóa đơn (chỉ không sửa khi phạm vi là \"以降すべて\"). Việc phải sửa: chặn lưu mục ảnh hưởng số tiền (契約_01 §1)"])
big("d_nf", "見つからないとき", "Khi không tìm thấy", ".empty", "label", ["URL の子契約IDが存在しないとき、I10（対象＝子契約（CP…））を出す。", "Khi ID hợp đồng con trên URL không tồn tại, hiện I10 (対象 = 子契約（CP…）)."], err=["I10"],
    demo_ok=["コードの文言は「子契約（…）が見つかりません」（句点なし）。I10 に揃える", "Câu trong code là \"子契約（…）が見つかりません\" (không có dấu chấm). Đồng nhất với I10"])

# ================================================================ AW_CONT_003 編集
big("e_head", "ヘッダー", "Đầu trang", ".phead", "area", ["パンくず・画面名＋子契約ID・要約・キャンセル／保存。仮登録の拠点の子契約は編集画面を開いても詳細（参照）が出る（決定 28-146）。", "Breadcrumb, tên màn hình + ID hợp đồng con, tóm tắt, hủy / lưu. Với hợp đồng con của cơ sở 仮登録, dù mở màn sửa vẫn hiện chi tiết (chỉ xem; quyết định 28-146)."], pattern="P-FORM")
sub("e_cancel", "キャンセル", "Hủy", ".pbtn button.cancel", "button", ["詳細（または一覧）へ戻る。入力を変えていたら Q02。", "Quay lại chi tiết (hoặc danh sách). Nếu đã đổi nhập thì hiện Q02."], err=["Q02"])
sub("e_save", "保存", "Lưu", ".pbtn button.save", "button", ["全項目をまとめてチェックし、後ろの子契約が生成済みなら適用範囲のダイアログ（No.下記）、未生成なら確認なしで保存して S01 のトースト（適用範囲の記録つき）を出し詳細へ。押したら二重に押せなくする。承認待ちの申請の対象項目・確定・請求済の金額に効く項目は保存できない。", "Kiểm tra gộp mọi mục; nếu hợp đồng con phía sau đã sinh thì hiện dialog phạm vi áp dụng (xem bên dưới), chưa sinh thì lưu không hỏi, hiện toast S01 (kèm ghi phạm vi áp dụng) và về chi tiết. Bấm xong khóa nút. Không lưu được mục đối tượng của đơn chờ duyệt và mục ảnh hưởng số tiền của tháng đã chốt / đã xuất hóa đơn."], err=["S01", "E30", "E31", "E113"], pattern="P-FORM",
    demo_ok=["コードの入力チェックの文言は直書きで ID がない（H5）。同時更新の検知（E31）は実装済み。カナ・絵文字のチェックと、金額に効く変更の確定・請求済チェック（E113）はまだない。設計書の「文字列 n」と、コードの上限（DB の varchar に合わせた値）が違う項目がある：法人名・拠点名・フリガナ 120（設計書 60）、市区町村 60（255）、町名・番地・建物 120（255）、配送番号 40（60）、設置フロア 100（60）", "Câu kiểm tra trong code viết thẳng, không có ID (H5). Phát hiện cập nhật đồng thời (E31) đã làm. Chưa có kiểm tra katakana / emoji và kiểm tra tháng đã chốt / đã xuất khi đổi mục ảnh hưởng số tiền (E113). Có mục giới hạn trong code (theo varchar của DB) khác \"文字列 n\" của 設計書: 法人名・拠点名・フリガナ 120 (設計書 60), 市区町村 60 (255), 町名・番地・建物 120 (255), 配送番号 40 (60), 設置フロア 100 (60)"])
big("e_lock", "編集中の人がいるとき・先に保存されていたとき", "Khi có người đang sửa / đã lưu trước", ".provbar.pendnote", "area", ["ほかの人が開いていれば I02、あとから保存した方は E31（上書きして保存）。", "Nếu người khác đang mở thì I02, người lưu sau nhận E31 (上書きして保存)."], err=["I02", "E31"], pattern="P-FORM",)

def _f(key, ja, vi, lab, mark, kind, ln, init, ex, valid, detail, err=None, **kw):
    return dict(key=key, ja=ja, vi=vi, lab=lab, mark=mark, kind=kind, len=ln, init=init, ex=ex, valid=valid, detail=detail, err=err or [], kw=kw)

LOCKED = ["承認待ちの申請があるとき、その申請の対象の項目は入力できない（I104）。確定・請求済のときは金額に効く変更ができない（E113）。", "Khi có đơn chờ duyệt thì mục đối tượng của đơn không nhập được (I104). Khi đã chốt / đã xuất hóa đơn thì không đổi được thứ ảnh hưởng số tiền (E113)."]
FIELDS = [
    ("子契約", "子契約", "Hợp đồng con", [
        _f("f_id", "子契約ID", "ID hợp đồng con", "子契約ID", "*", "label", None, None, None, None, ["親契約番号＋「-yyyymm」。システムが決め、直せない。", "Số hợp đồng cha + \"-yyyymm\". Hệ thống quyết định, không sửa được."], [], ro=True),
        _f("f_m", "契約・サイクル月", "Tháng chu kỳ hợp đồng", "契約・サイクル月", "*", "label", None, None, None, None, ["この子契約が担当する納品サイクルの月。直せない。重複防止のキー（拠点＋サイクル月）。", "Tháng chu kỳ giao hàng mà hợp đồng con này phụ trách. Không sửa được. Là khóa chống trùng (cơ sở + tháng chu kỳ)."], [], ro=True),
        _f("f_cp", "親契約番号（契約ID）", "Số hợp đồng cha", "親契約番号（契約ID）", "*", "label", None, None, None, None, ["親へのリンク。不変。", "Liên kết tới hợp đồng cha. Bất biến."], [], ro=True),
    ]),
    ("契約", "契約", "Hợp đồng", [
        _f("f_plan", "プランID", "ID gói", "プランID", "*", "select", "選択（プラン）", None, ["ES000004　100プラン", "Chọn 1 gói (ID + tên gói)"], ["必須。プランマスタから選ぶ（プランID・プラン名で絞り込み検索できる）。", "Bắt buộc. Chọn từ プランマスタ (tìm lọc theo ID / tên gói)."], ["プラン変更はこの子契約（翌月分）で行う。変えるとコースの料金が決まる（コース × 配送区分）。別のプランへ変えるときは公開用の価格の世代になる。" + LOCKED[0], "Đổi gói làm ở hợp đồng con này (phần tháng sau). Đổi thì giá course được quyết (course × loại giao). Khi đổi sang gói khác thì dùng thế hệ giá công khai. Khi có đơn chờ duyệt thì mục đối tượng của đơn không nhập được (I104)."], ["E02", "I104", "E113"], **{"pending": True}),
        _f("f_course", "メニュー種別（コース）", "Loại menu (course)", "メニュー種別（コース）", "*", "select", "選択（コース）", None, ["ESライト（冷蔵庫）", "Chọn 1 course"], ["必須。選択：ESスタンダード／ESライト（冷蔵庫）／ESライト（自販機）。", "Bắt buộc. Chọn: ESスタンダード / ESライト（冷蔵庫）/ ESライト（自販機）."], ["ESライト（自販機）の拠点のプラン料金はプランマスタの ESライト（自販機）の価格プラン（ES配送便）で、配送区分は ES配送便に固定（決定 28-184）。標準の設備は 自販機＋資材ボックス。" + LOCKED[0], "Phí gói của cơ sở ESライト（自販機） lấy từ giá gói ESライト（自販機） (ES配送便) của プランマスタ, 配送区分 cố định ES配送便 (quyết định 28-184). Thiết bị chuẩn: máy bán hàng + hộp vật tư. Khi có đơn chờ duyệt thì mục đối tượng của đơn không nhập được (I104)."], ["E02", "I104", "E113"], **{"pending": True}),
        _f("f_from", "適用開始月", "Tháng bắt đầu áp dụng", "適用開始月", "*", "text", U("年月（yyyy-mm）", "Năm-tháng (yyyy-mm)"), None, ["2026-10", "Tháng bắt đầu của kỳ hợp đồng con phụ trách"], ["必須。年月。", "Bắt buộc. Năm-tháng."], ["この子契約が担当する期間の開始。契約全体の開始日は親契約が持つ。", "Bắt đầu của kỳ mà hợp đồng con này phụ trách. Ngày bắt đầu toàn hợp đồng do hợp đồng cha giữ."], ["E01"]),
        _f("f_to", "適用終了月", "Tháng kết thúc áp dụng", "適用終了月", "*", "text", U("年月（yyyy-mm）", "Năm-tháng (yyyy-mm)"), None, ["2026-10", "Tháng kết thúc của kỳ hợp đồng con phụ trách"], ["必須。年月。適用開始月以降。", "Bắt buộc. Năm-tháng. Từ tháng bắt đầu trở đi."], ["この子契約が担当する期間の終了。", "Kết thúc của kỳ mà hợp đồng con này phụ trách."], ["E01", "E08"]),
        _f("f_cancel", "解約時の回収額（上書き）", "Số tiền thu hồi khi hủy (ghi đè)", "解約時の回収額（上書き）", "△", "text", "整数 0〜999,999,999（円）", None, ["24000", "Số yên, nửa góc; trống thì dùng số chuẩn của master máy"], ["任意。0以上の整数（円）。", "Tùy chọn. Số nguyên từ 0 (yên)."], ["空欄なら機種マスタの「解約時の回収額」（標準額）を使う。入っていればこちらを優先する。自販機のように設置条件で撤去費が変わる機種のため、契約ごとに入れられる（設備ごとに持つ）。別途見積の機種は契約を作るときに必ず入れる（空欄のまま解約すると違約金が0円になるため）。金額の欄は右寄せ。", "Để trống thì dùng \"解約時の回収額\" (số chuẩn) của master máy. Nếu có giá trị thì ưu tiên giá trị này. Dành cho máy mà phí tháo dỡ đổi theo điều kiện lắp (như máy bán hàng), nhập theo từng hợp đồng (giữ theo từng thiết bị). Máy báo giá riêng thì bắt buộc nhập khi tạo hợp đồng (nếu để trống mà hủy thì tiền phạt = 0). Ô số tiền căn phải."], ["E14", "E12"]),
        _f("f_priceplan", "適用された価格プラン", "Gói giá được áp dụng", "適用された価格プラン", "*", "select", U("選択（価格プランの世代）", "Chọn (thế hệ giá của gói)"), None, ["改訂第三回目（2026-04-01〜・公開用）", "Chọn 1 thế hệ giá"], ["必須。プランマスタの価格プランの世代から選ぶ。①の請求が確定したあとは変えられない。", "Bắt buộc. Chọn từ các thế hệ giá của プランマスタ. Sau khi hóa đơn ① chốt thì không đổi được."], ["初期値：自動生成の子契約は前の子契約と同じ世代、新規・プラン変更は公開用の世代。変えたときは保存のダイアログで「この子契約だけ／この子契約以降すべて」を選ぶ。プラン料金とスタンダードアップ差額（DC000021）はこの世代の料金で計算する。選んだ世代の金額は子契約に固める（あとでプランマスタの金額を直しても変わらない）。", "Mặc định: hợp đồng con tự sinh dùng cùng thế hệ với hợp đồng con trước; đăng ký mới / đổi gói dùng thế hệ công khai. Khi đổi thì chọn \"この子契約だけ / この子契約以降すべて\" ở dialog lưu. Phí gói và chênh lệch nâng lên Standard (DC000021) tính theo giá của thế hệ này. Số tiền của thế hệ đã chọn được cố định vào hợp đồng con (sau đó sửa số tiền ở プランマスタ cũng không đổi)."], ["E02", "E113"]),
        _f("f_subsidy", "企業負担額・税率（プランから）", "Mức công ty chịu・thuế suất (từ gói)", "企業負担額・税率（プランから）", "*", "label", None, None, None, None, ["生成時にプランマスタから固める。読むだけ。", "Cố định từ プランマスタ khi sinh. Chỉ xem."], [], ro=True),
        _f("f_buyout", "惣菜買取", "Mua đứt món ăn kèm", "惣菜買取", "△", "select", U("選択（ON／OFF）", "Chọn (ON / OFF)"), None, ["OFF", "Chọn ON hoặc OFF"], ["任意。運営だけが変えられる。", "Tùy chọn. Chỉ vận hành đổi được."], ["ON の契約は在庫管理の対象外とし、棚卸・事務手数料・管理ロスの対象にしない（請求ルール 2-13）。", "Hợp đồng ON không thuộc đối tượng quản lý tồn kho, không tính kiểm kê・phí thủ tục・hao hụt quản lý (請求ルール 2-13)."], [],
           demo_ok=["コードの画面にこの項目がない（足す宿題・契約_05 契約 No.8）。ラベルの場所を探す sel は '-'", "Màn hình code chưa có mục này (việc phải thêm; 契約_05 mục 8). sel tìm vị trí nhãn là '-'"]),
    ]),
    ("アプリ", "アプリの利用設定（このサイクル月）", "Thiết lập dùng app (tháng chu kỳ này)", [
        _f("f_cash", "ユーザー現金利用", "Người dùng trả tiền mặt", "ユーザー現金利用", "*", "select", "選択（可／不可）", ["不可", "Không"], ["不可", "Chọn được hoặc không"], ["必須。選択：可／不可。", "Bắt buộc. Chọn: 可 / 不可."], ["既定は不可。現金分はアプリ決済に載らないため販売実績額に含まれない。既存拠点のみ。" + SCOPE_NOTE[0], "Mặc định là không. Phần tiền mặt không đi qua thanh toán app nên không tính vào số liệu bán hàng. Chỉ cơ sở hiện có. Khi lưu chọn \"この子契約だけ / この子契約以降すべて\" (giữ theo tháng chu kỳ = do hợp đồng con giữ)."], ["E02"]),
        _f("f_daily", "1日上限数（1人あたり）", "Giới hạn mỗi ngày (mỗi người)", "1日上限数（1人あたり）", "△", "text", "整数 0〜9,999（食／日）", None, ["3", "Số suất mỗi ngày; 0 = không giới hạn"], ["任意。0以上の整数（食／日）。", "Tùy chọn. Số nguyên từ 0 (suất/ngày)."], ["0＝制限なし。法人Webの拠点の「編集」から直せる（承認不要）。" + SCOPE_NOTE[0], "0 = không giới hạn. Sửa được từ \"編集\" của cơ sở trên 法人Web (không cần duyệt). Khi lưu chọn \"この子契約だけ / この子契約以降すべて\"."], ["E12", "E14"]),
        _f("f_monthly", "1ヶ月上限金額（1人あたり）", "Giới hạn tiền mỗi tháng (mỗi người)", "1ヶ月上限金額（1人あたり）", "△", "text", "整数 0〜999,999,999（円／月）", None, ["0", "Số yên mỗi tháng; 0 = không giới hạn"], ["任意。0以上の整数（円／月）。金額の欄は右寄せ。", "Tùy chọn. Số nguyên từ 0 (yên/tháng). Ô số tiền căn phải."], ["0＝制限なし。" + SCOPE_NOTE[0], "0 = không giới hạn. Khi lưu chọn \"この子契約だけ / この子契約以降すべて\"."], ["E12", "E14"]),
        _f("f_guest", "ゲストモード", "Chế độ khách", "ゲストモード", "△", "select", "選択（利用しない／利用する）", ["利用しない", "Không dùng"], ["利用する", "Chọn dùng hoặc không dùng"], ["任意。選択：利用しない／利用する。", "Tùy chọn. Chọn: 利用しない / 利用する."], ["既定は利用しない。社員登録のない来訪者でも購入可（食事補助の対象外）。法人Webからすぐ変更できる（承認不要・運営へ通知）。保存した時点で使え、料金の開始月はオーダー締切のルールで決まる（保存時に確認のダイアログ）。", "Mặc định không dùng. Khách chưa đăng ký nhân viên vẫn mua được (không thuộc đối tượng hỗ trợ bữa ăn). Đổi được ngay từ 法人Web (không cần duyệt, thông báo cho vận hành). Dùng được ngay khi lưu, tháng bắt đầu tính phí theo quy tắc hạn chót đặt hàng (dialog xác nhận khi lưu)."], []),
        _f("f_esqr", "ES-QR", "ES-QR", "ES-QR", "△", "select", U("選択（利用しない／利用する（月額料金あり））", "Chọn (không dùng / dùng (có phí hằng tháng))"), ["利用しない", "Không dùng"], ["利用する（月額料金あり）", "Chọn không dùng hoặc dùng (có phí hằng tháng)"], ["任意。選択：利用しない／利用する（月額料金あり）。運営だけが変えられる。", "Tùy chọn. Chọn: 利用しない / 利用する（月額料金あり）. Chỉ vận hành đổi được."], ["ES-QR コードによる決済。利用すると月額料金が発生し、A型オプション『ES-QR 利用料』として子契約の ① に自動で立てる（前払い・前払いに間に合わない分は次の請求書に繰り越す）。法人Webは表示のみ。", "Thanh toán bằng mã ES-QR. Khi dùng sẽ phát sinh phí hằng tháng và tự dựng thành tùy chọn loại A \"ES-QR 利用料\" ở ① của hợp đồng con (trả trước; phần không kịp trả trước sẽ chuyển sang hóa đơn sau). 法人Web chỉ hiển thị."], []),
    ]),
    ("配送", "配送・納品スケジュール", "Giao hàng・lịch giao", [
        _f("f_ship", "配送区分", "Loại giao hàng", "配送区分", "*", "select", "選択（COOL便／ES配送便）", ["ES配送便", "ES配送便"], ["ES配送便", "Chọn COOL便 hoặc ES配送便"], ["必須。選択：COOL便／ES配送便。", "Bắt buộc. Chọn: COOL便 / ES配送便."], ["プランマスタの価格はこの配送区分別（料金に効く軸）。設備が自販機の拠点（コース＝ESライト（自販機））は ES配送便に固定し、選択肢は出さない。法人Webからの変更は運営の承認が必須。", "Giá của プランマスタ phân theo loại giao hàng này (trục ảnh hưởng giá). Cơ sở có máy bán hàng (course = ESライト（自販機）) cố định ES配送便 và không hiện lựa chọn. Thay đổi từ 法人Web bắt buộc vận hành duyệt."], ["E02"]),
        _f("f_dno", "配送番号", "Số giao hàng", "配送番号", "△", "text", "文字列 60", None, ["DN-0643-01", "Số giao hàng"], ["任意。最大60文字。", "Tùy chọn. Tối đa 60 ký tự."], ["配送の番号。", "Số của lần giao hàng."], ["E04", "E13"]),
        _f("f_ng", "納品不可曜日", "Ngày không giao được", "納品不可曜日", "△", "check", U("選択（月〜日・祝日・複数）", "Chọn (Hai đến CN, ngày lễ, nhiều)"), ["チェックなし", "Không tích"], ["土・日・祝日", "Tích nhiều ngày; không tích = không có ngày không giao được"], ["任意。月・火・水・木・金・土・日・祝日 から複数選ぶ（どれにもチェックしない＝納品不可曜日なし）。", "Tùy chọn. Chọn nhiều trong Hai・Ba・Tư・Năm・Sáu・Bảy・CN・ngày lễ (không tích gì = không có ngày không giao được)."], ["法人Webからの変更は運営の承認が必須。設備の希望日の変更・納品不可曜日の変更は「拠点情報の変更」の1つで受ける（配送の変更と二重にしない）。", "Thay đổi từ 法人Web bắt buộc vận hành duyệt. Đổi ngày mong muốn thiết bị và ngày không giao được nhận bằng 1 đơn \"拠点情報の変更\" (không làm trùng với đổi giao hàng)."], []),
        _f("f_shift", "納品予定日になった場合", "Khi đến ngày giao dự kiến", "納品予定日になった場合", "*", "select", U("選択（前倒す／後ろ倒す）", "Chọn (dời sớm / dời muộn)"), ["前倒す", "Dời sớm"], ["前倒す", "Chọn dời sớm hoặc dời muộn"], ["必須。選択：前倒す／後ろ倒す。", "Bắt buộc. Chọn: 前倒す / 後ろ倒す."], ["納品予定日が納品不可曜日・休日に当たるときに前の日へずらすか後ろの日へずらすか。", "Khi ngày giao dự kiến trúng ngày không giao được / ngày nghỉ thì dời lên ngày trước hay ngày sau."], ["E02"]),
        _f("f_dnote", "配送備考", "Ghi chú giao hàng", "配送備考", "△", "textarea", U("文字列 500（複数行）", "Chuỗi 500 (nhiều dòng)"), None, ["1F 守衛室で受付後、8F 社員食堂へ", "Ghi chú giao nhận / vận chuyển"], ["任意。最大500文字。絵文字は不可。", "Tùy chọn. Tối đa 500 ký tự. Không dùng emoji."], ["受け渡し・搬入の注意など。複数行の欄は3列分の幅で、セクションの最後に置く。", "Lưu ý giao nhận / vận chuyển... Ô nhiều dòng rộng 3 cột, đặt cuối khu vực."], ["E04", "E13"]),
        _f("f_floor", "設置フロア", "Tầng lắp đặt", "設置フロア", "△", "text", "文字列 60", None, ["2F 給湯室", "Tầng / vị trí lắp đặt"], ["任意（自販機の拠点は必須）。最大60文字。", "Tùy chọn (bắt buộc với cơ sở máy bán hàng). Tối đa 60 ký tự."], ["申込で聞く。自販機は必須・冷蔵庫は任意（台帳 2026/10/03）。", "Hỏi khi đăng ký. Máy bán hàng bắt buộc, tủ lạnh tùy chọn (台帳 2026/10/03)."], ["E01", "E04"]),
    ]),
    ("メモ", "メモ", "Ghi chú", [
        _f("f_imemo", "運営メモ（内部メモ）", "Ghi chú vận hành (nội bộ)", "運営メモ（内部メモ）", "", "textarea", U("文字列 500（複数行）", "Chuỗi 500 (nhiều dòng)"), None, ["紹介元パートナーズ経由。初回設置時に搬入口が狭く時間超過。", "Ghi chú tự do chỉ vận hành xem"], ["任意。最大500文字。絵文字は不可。", "Tùy chọn. Tối đa 500 ký tự. Không dùng emoji."], ["運営だけが見る自由記述。法人画面には出さない。", "Văn bản tự do chỉ vận hành xem. Không hiện ở màn pháp nhân."], ["E04", "E13"]),
        _f("f_appnote", "プラン外の備考（申込時）", "Ghi chú ngoài gói (khi đăng ký)", "プラン外の備考（申込時）", "△", "label", None, None, None, None, ["申込フォームの自由記述を引き継いで表示する。読むだけ。", "Hiển thị kế thừa phần văn bản tự do của form đăng ký. Chỉ xem."], [], ro=True),
    ]),
    ("料金", "値引き・負担額", "Giảm giá・mức chịu", [
        _f("f_welfare", "福利厚生の適用", "Áp dụng phúc lợi", "福利厚生の適用", "*", "select", U("選択（ON／OFF）", "Chọn (ON / OFF)"), ["OFF（既定 OFF）", "OFF (mặc định OFF)"], ["ON", "Chọn ON hoặc OFF"], ["必須。選択：ON／OFF（既定 OFF）。システム管理だけに出す。", "Bắt buộc. Chọn: ON / OFF (mặc định OFF). Chỉ hiện với システム管理."], ["ON にすると請求書でプラン料金を2行（基本料金10%／福利厚生〈企業負担分〉8%）に分けて出す。OFF のときは1行にまとめる。金額と消費税は ON・OFF で変わらない。企業負担額はプランマスタが持つので、ここでは金額を選ばない。" + SCOPE_NOTE[0], "Bật ON thì hóa đơn tách phí gói thành 2 dòng (phí cơ bản 10% / phúc lợi (phần công ty chịu) 8%). OFF thì gộp 1 dòng. Số tiền và thuế không đổi giữa ON và OFF. Mức công ty chịu do プランマスタ giữ nên không chọn số tiền ở đây. Khi lưu chọn \"この子契約だけ / この子契約以降すべて\"."], ["E02", "E113"]),
        _f("f_adj", "価格調整の適用", "Áp dụng điều chỉnh giá", "価格調整の適用", "△", "select", U("選択（なし／値上げ／値下げ／無料提供）＋金額", "Chọn (không / tăng giá / giảm giá / cung cấp miễn phí) + số tiền"), ["なし", "Không"], ["値下げ", "Chọn loại điều chỉnh, rồi nhập số tiền (bội số 10 yên)"], ["任意。なし／値上げ／値下げ／無料提供（企業負担）を選ぶ。なし・無料提供のとき以外は金額（10円単位の半角数字）が必須。", "Tùy chọn. Chọn không / tăng giá / giảm giá / cung cấp miễn phí (công ty chịu). Ngoài trường hợp không / miễn phí thì bắt buộc nhập số tiền (số nửa góc, bội số 10 yên)."], ["拠点ごとの一品ものの調整（値引きマスタには持たせない）。無料提供も運営承認が必須。金額の欄は右寄せ。" + SCOPE_NOTE[0], "Điều chỉnh riêng từng cơ sở (không đặt ở master giảm giá). Cung cấp miễn phí cũng bắt buộc vận hành duyệt. Ô số tiền căn phải. Khi lưu chọn \"この子契約だけ / この子契約以降すべて\"."], ["E14", "E113"]),
    ]),
]

CARDSEL = {"子契約": "子契約", "契約": "契約", "アプリ": "アプリの利用設定", "配送": "配送・納品スケジュール", "メモ": "メモ", "料金": "値引き・負担額"}
for _tab, _card, _cardvi, _fs in FIELDS:
    big("e_" + _tab, "カード「%s」" % _card, "Thẻ \"%s\"" % _cardvi, ".ch::%s^" % CARDSEL[_tab], "area",
        ["このカードの入力項目。保存はヘッダーの「保存」1つ（カードごとの保存ボタンはない）。", "Các mục nhập của thẻ này. Lưu bằng 1 nút \"保存\" ở đầu màn hình (không có nút lưu riêng từng thẻ)."])
    for _x in _fs:
        _sel = ".f::" + _x["lab"] + _x["mark"] if _x["mark"] else ".f::" + _x["lab"]
        if _x["key"] == "f_buyout": _sel = "-"
        _kw = dict(_x["kw"]); _kw.pop("ro", None); _kw.pop("pending", None)
        _it = {}
        if _x["kind"] in ("text", "textarea", "select", "date", "file", "check"):
            _it = dict(req="○" if _x["mark"] == "*" else "－", len=_x["len"], ex=_x["ex"], valid=_x["valid"])
            if _x["init"]: _it["init"] = _x["init"]
        if _x["err"]: _it["err"] = _x["err"]
        _it.update(_kw)
        sub(_x["key"], _x["ja"], _x["vi"], _sel, _x["kind"], _x["detail"], **_it)

big("e_adjamt", "価格調整の金額", "Số tiền điều chỉnh giá", ".stack input.r", "text", ["価格調整の適用が「なし」「無料提供」以外のときに入れる金額（10円単位の半角数字）。10円単位でない・数字でないときは E14 の形で止める。", "Số tiền nhập khi 価格調整の適用 không phải \"なし\" hay \"無料提供\" (số nửa góc, bội số 10 yên). Không phải bội số 10 yên / không phải số thì chặn bằng dạng E14."], req="△", len="整数 0〜999,999,999（円）", ex=["500", "Số tiền điều chỉnh (bội số 10 yên)"], valid=["「なし」「無料提供」のとき以外は必須。10円単位の半角数字。", "Bắt buộc trừ khi \"なし\" / \"無料提供\". Số nửa góc, bội số 10 yên."], err=["E01", "E14"],
    demo_ok=["コードの文言は「金額は10円単位の半角数字で入力してください」（ID がない）。E14 などに揃える（H5）", "Câu của code là \"金額は10円単位の半角数字で入力してください\" (không có ID). Đồng nhất với E14... (H5)"])
big("e_route_tbl", "配送ルート設定（テーブル）", "Bảng 配送ルート設定", ".pane table", "table", ["配送種別ごとの行。ピッキング倉庫（倉庫マスタ）・運送会社・納品会社（配送会社マスタの全件）・途中経由1（倉庫マスタ 区分＝中継・HU／なし）・リードタイム（0〜7日）・配送回数・配送パターン（ESサイクル／スペシャル／都度配送）・納品サイクル（A1〜D7など。都度配送は空欄）・問い合わせ確認URL。行の追加・削除ができる。", "Mỗi 配送種別 một dòng. Kho lấy hàng (master kho), công ty vận chuyển, công ty giao (toàn bộ master công ty giao hàng), điểm trung chuyển 1 (master kho, loại trung chuyển / HU / なし), lead time (0〜7 ngày), số lần giao, mẫu giao (ES chu kỳ / đặc biệt / giao theo đơn), chu kỳ giao (A1〜D7...; giao theo đơn để trống), URL tra cứu. Thêm / xóa dòng được."],
    demo_ok=["選択肢（倉庫・運送会社・中継）は見本のマスタ。運営H（倉庫・委託配送先マスタ）の設計書と合わせる", "Lựa chọn (kho, công ty vận chuyển, trung chuyển) là master mẫu. Thống nhất với thiết kế của 運営H (master kho / công ty giao ủy thác)"])
sub("e_route_add", "行を追加（配送ルート）", "Thêm dòng (lộ trình giao)", ".pane button::行を追加", "button", ["配送種別の行を1行足す。", "Thêm 1 dòng loại giao hàng."])
sub("e_route_del", "行の削除（配送ルート）", "Xóa dòng (lộ trình giao)", ".pane span.del", "button", ["その行を削除する（保存するまで確定しない）。冷蔵配送は必ず1行以上。", "Xóa dòng đó (chưa xác định đến khi lưu). 冷蔵配送 phải có ≥ 1 dòng."])
big("e_scope", "変更の適用範囲（ダイアログ）", "Phạm vi áp dụng thay đổi (dialog)", ".ovl .dlg", "modal", ["この子契約より後に、生成済みの子契約があるときだけ、保存のとき出す。タイトル「変更の適用範囲を選んでください」。「この子契約だけ（yyyy-mm のみ）」：この子契約のレコードだけ直し、後ろの生成済みと翌月以降に生成する分は元の設定のまま。「この子契約以降すべて」：生成元の設定（拠点・親契約・プラン）も同じ値に更新し、生成済みで未確定の n件も直す（確定・請求済 n件は直さない）。後ろがまだ生成されていないときは出さずに保存する。", "Chỉ hiện khi lưu nếu có hợp đồng con đã sinh sau hợp đồng con này. Tiêu đề \"変更の適用範囲を選んでください\". \"この子契約だけ (chỉ yyyy-mm)\": chỉ sửa bản ghi hợp đồng con này, phần đã sinh phía sau và phần sẽ sinh từ tháng sau giữ thiết lập cũ. \"この子契約以降すべて\": cập nhật cả thiết lập nguồn sinh (cơ sở, hợp đồng cha, gói) cùng giá trị và sửa cả n hợp đồng con đã sinh chưa xác định (không sửa n hợp đồng đã chốt / đã xuất hóa đơn). Chưa sinh phía sau thì lưu không hỏi."], pattern="P-FORM")
sub("e_scope_only", "この子契約だけ", "Chỉ hợp đồng con này", ".ovl .dlg label.op::この子契約だけ", "radio", ["既定。変更履歴の適用範囲は「yyyy-mm のみ」で残す。", "Mặc định. Phạm vi áp dụng ở lịch sử ghi \"yyyy-mm のみ\"."], req="○", init=U("選択あり", "Đang chọn"), ex=["この子契約だけ", "Chọn 1 trong 2 phạm vi"])
sub("e_scope_after", "この子契約以降すべて", "Từ hợp đồng con này trở đi", ".ovl .dlg label.op::以降すべて", "radio", ["変更履歴の適用範囲は「yyyy-mm 以降すべて」。", "Phạm vi áp dụng ở lịch sử ghi \"yyyy-mm 以降すべて\"."], req="○", init=U("選択なし", "Không chọn"), ex=["この子契約以降すべて", "Chọn 1 trong 2 phạm vi"])
sub("e_scope_save", "保存（ダイアログ）", "Lưu (dialog)", ".ovl .dlg .ft button.ok", "button", ["選んだ範囲で保存し、S01 のトースト（適用範囲の記録つき：未確定の子契約 n件も直した旨）を出して詳細へ。", "Lưu theo phạm vi đã chọn, hiện toast S01 (kèm ghi phạm vi áp dụng: đã sửa cả n hợp đồng con chưa xác định) và về chi tiết."], err=["S01"])
sub("e_scope_cancel", "キャンセル（ダイアログ）", "Hủy (dialog)", ".ovl .dlg .ft button.cx", "button", ["閉じる（保存しない）。", "Đóng (không lưu)."])
big("e_opt_amt", "オプションの金額（契約ごと・機種参照・ES-QR）", "Số tiền tùy chọn (theo hợp đồng・tham chiếu máy・ES-QR)", ".pane table input.r", "text", ["オプション・割引の表の「金額・率」の入力欄。契約ごと・機種参照・ES-QR のオプション（と、すでに上書きがあるもの）だけ、子契約ごとに金額（税抜・整数の円）を上書きできる。マスタの標準金額と同じなら上書きを外す。0以上の整数でないと保存できない。ES-QR の既存顧客の無料は、オプション1つのまま金額を0円に上書きして表す。価格世代の一括切替では上書きした金額を残し、一覧に「上書きあり」と出す。", "Ô nhập \"金額・率\" của bảng tùy chọn / giảm giá. Chỉ tùy chọn theo hợp đồng / tham chiếu máy / ES-QR (và những dòng đã có ghi đè) mới ghi đè được số tiền (chưa thuế, số nguyên yên) theo từng hợp đồng con. Bằng số tiền chuẩn của master thì bỏ ghi đè. Không phải số nguyên từ 0 thì không lưu được. Khách hàng cũ miễn phí ES-QR thể hiện bằng ghi đè số tiền 0 yên của đúng 1 tùy chọn. Khi đổi hàng loạt thế hệ giá giữ nguyên số tiền ghi đè và hiện \"上書きあり\" ở danh sách."], req="－", len="整数 0〜999,999,999（円）", ex=["0", "Số yên chưa thuế; 0 = miễn phí"], valid=["任意。0以上の整数（円）。", "Tùy chọn. Số nguyên từ 0 (yên)."], err=["E14", "E12"])
big("e_discard", "編集内容の破棄（確認）", "Hủy nội dung đang sửa (xác nhận)", ".es-modal", "modal", ["Q02。入力を変えたあとに「キャンセル」・ほかの画面への移動・ブラウザを閉じる／再読み込みをしたとき。「破棄」で捨てて移動、「キャンセル」で編集を続ける。", "Q02. Hiện khi đã đổi nhập rồi bấm \"キャンセル\", chuyển màn hình khác, đóng trình duyệt / tải lại. \"破棄\" bỏ và chuyển trang, \"キャンセル\" tiếp tục sửa."], err=["Q02"], pattern="P-FORM")
sub("e_disc_cancel", "キャンセル", "Hủy", ".es-modal__actions button::キャンセル", "button", ["閉じて編集を続ける。", "Đóng, tiếp tục sửa."])
sub("e_disc_ok", "破棄", "Bỏ", ".es-modal__actions button::破棄", "button", ["入力を捨てて移動する。", "Bỏ nội dung đã nhập và chuyển trang."])
big("e_saved", "保存完了（トースト）", "Lưu xong (toast)", ".toast", "toast", ["S01「保存しました。」に、変更履歴の適用範囲の記録を添えて出す：後ろの子契約がないとき「…より後の子契約はまだ生成されていないため、適用範囲の確認は出しません（翌月以降はこの内容で生成されます。変更履歴の適用範囲：yyyy-mm 以降すべて）」、「この子契約だけ」のとき「変更履歴の適用範囲：yyyy-mm のみ」、「以降すべて」のとき「未確定の子契約 n件も直しました…」。", "Hiện S01 \"保存しました。\" kèm ghi phạm vi áp dụng lịch sử: khi không có hợp đồng con phía sau \"…より後の子契約はまだ生成されていないため、適用範囲の確認は出しません（… 以降すべて）\", khi \"この子契約だけ\" thì \"変更履歴の適用範囲：yyyy-mm のみ\", khi \"以降すべて\" thì \"未確定の子契約 n件も直しました…\"."], err=["S01"],
    demo_ok=["コードのトーストは「保存しました。…」（句点の位置が S01 と違う）。S01 に適用範囲の記録を添える形に揃える", "Toast của code là \"保存しました。…\" (vị trí dấu chấm khác S01). Đồng nhất thành S01 kèm ghi phạm vi áp dụng"])

# ================================================================ AW_CONT_004 価格世代を一括切替（モーダル）
big("b_modal", "価格世代を一括切替（モーダル）", "Đổi hàng loạt thế hệ giá (modal)", ".ov .mbox", "modal", ["子契約一覧の「価格世代を一括切替」で開く（フル権限・システム管理だけ）。別の画面は作らない。流れ：① 条件と切替後の世代 → ② 対象 → ③ 確認 → ④ 実行と結果。タブ「一括変更」「履歴」。部品 BulkChangeModal は 倉庫・委託配送先マスタの「契約の一括変更」（ルートのモード・運営H）と同じ部品で、ここは価格世代のモードだけを書く。", "Mở bằng \"価格世代を一括切替\" ở danh sách hợp đồng con (chỉ フル権限・システム管理). Không tạo màn hình riêng. Luồng: ① điều kiện và thế hệ sau khi đổi → ② đối tượng → ③ xác nhận → ④ thực hiện và kết quả. Tab \"一括変更\" \"履歴\". Thành phần BulkChangeModal dùng chung với \"契約の一括変更\" của master kho / công ty giao ủy thác (chế độ lộ trình; 運営H), ở đây chỉ ghi chế độ thế hệ giá."], pattern="P-BULK", err=["Q11", "S11", "W10", "S107"],
    demo_ok=["コードのモーダルは ③ 確認を自分の画面で出し、Q11（確認のモーダル）は使わない。実行の結果のトースト（変更・スキップ・失敗）は S107（S11／W10 は使わない）。P-BULK の「確認のモーダル」との整合は phiên gộp で確認", "Modal của code tự hiện bước ③ xác nhận và không dùng Q11 (modal xác nhận). Toast kết quả thực hiện (thay đổi・bỏ qua・lỗi) là S107 (không dùng S11 / W10). Việc đồng nhất với \"modal xác nhận\" của P-BULK xác nhận ở phiên gộp"])
sub("b_title", "モーダルの見出し", "Tiêu đề modal", ".mbox-h h3", "label", ["「価格世代を一括切替」。×で閉じる（途中の入力は捨てる）。", "\"価格世代を一括切替\". Bấm × để đóng (bỏ nội dung đang nhập)."])
sub("b_tabs", "タブ（一括変更／履歴）", "Tab (đổi hàng loạt / lịch sử)", ".mbox .tabs", "tab", ["「一括変更」（①〜④）と「履歴（n）」。履歴＝これまでの一括変更の一覧。", "\"一括変更\" (①〜④) và \"履歴 (n)\". 履歴 = danh sách các lần đổi hàng loạt trước đây."])
sub("b_note", "説明", "Giải thích", ".mbox .notice", "label", ["「適用開始のサイクル月から、未確定の子契約の ① 費目をプランの価格世代（その月の価格）で作り直します。確定・請求済の子契約は変えません（請求調整）。」", "\"適用開始のサイクル月から、未確定の子契約の ① 費目をプランの価格世代（その月の価格）で作り直します。確定・請求済の子契約は変えません（請求調整）。\""])
big("b_cond", "① 対象の条件", "① Điều kiện đối tượng", ".mbox .sec-h::① 対象の条件", "area", ["プラン（必須）・いま使っている価格の世代（空＝そのプランの子契約すべて）・法人・拠点・コース・温度帯・市区町村・郵便番号（頭）・都道府県（複数）。条件に合う子契約が対象になる。", "Gói (bắt buộc), thế hệ giá đang dùng (trống = mọi hợp đồng con của gói), pháp nhân, cơ sở, course, vùng nhiệt, quận/huyện, mã bưu chính (đầu), tỉnh thành (nhiều). Hợp đồng con phù hợp điều kiện là đối tượng."])
sub("b_plan", "プラン", "Gói", ".mbox .fld::プラン*", "select", ["切り替えるプランを選ぶ（削除済みを除くプランマスタ）。選ぶと「いま使っている価格の世代」と「切り替える価格の世代」の選択肢がそのプランのものになる。", "Chọn gói cần đổi (プランマスタ trừ gói đã xóa). Chọn xong thì lựa chọn \"いま使っている価格の世代\" và \"切り替える価格の世代\" là của gói đó."], req="○", len=U("選択（プラン）", "Chọn (gói)"), init=U("選んでください", "Hãy chọn"), ex=["ES000004 100プラン", "Chọn 1 gói"], valid=["必須。", "Bắt buộc."], err=["E02"])
sub("b_gen", "いま使っている価格の世代", "Thế hệ giá đang dùng", ".mbox .fld::いま使っている価格の世代", "select", ["空＝そのプランの子契約すべて。「世代ID メモ（適用開始〜・使っている子契約の件数）」から選ぶ。", "Trống = mọi hợp đồng con của gói. Chọn từ \"ID thế hệ ghi chú (bắt đầu áp dụng〜・số hợp đồng con đang dùng)\"."], req="－", len=U("選択（価格プランの世代）", "Chọn (thế hệ giá của gói)"), init=U("すべて", "Tất cả"), ex=["PG-ES000004-04 改訂第三回目", "Chọn 1 thế hệ giá"])
sub("b_corp", "法人", "Pháp nhân", ".mbox .fld::法人", "select", ["法人で絞る。変えたら拠点は選び直し。", "Lọc theo pháp nhân. Đổi pháp nhân thì chọn lại cơ sở."], req="－", len=U("選択（法人マスタ）", "Chọn (danh sách pháp nhân)"), init=U("すべて", "Tất cả"), ex=["CU00001 株式会社サンプル", "Chọn 1 pháp nhân"])
sub("b_br", "拠点", "Cơ sở", ".mbox .fld::拠点", "select", ["拠点で絞る（選んだ法人の拠点だけ）。", "Lọc theo cơ sở (chỉ cơ sở của pháp nhân đã chọn)."], req="－", len=U("選択（拠点）", "Chọn (cơ sở)"), init=U("すべて", "Tất cả"), ex=["CU00643 株式会社サンプル 本社", "Chọn 1 cơ sở"])
sub("b_course", "コース", "Course", ".mbox .fld::コース", "select", ["ESスタンダード／ESライト（冷蔵庫）／ESライト（自販機）で絞る。", "Lọc theo ESスタンダード / ESライト（冷蔵庫）/ ESライト（自販機）."], req="－", len=U("選択（コース）", "Chọn (course)"), init=U("すべて", "Tất cả"), ex=["ESスタンダード", "Chọn 1 course"])
sub("b_temp", "温度帯", "Vùng nhiệt", ".mbox .fld::温度帯", "select", ["冷蔵／冷凍で絞る。", "Lọc theo lạnh / đông."], req="－", len=U("選択（冷蔵／冷凍）", "Chọn (lạnh / đông)"), init=U("すべて", "Tất cả"), ex=["冷凍", "Chọn 1 vùng nhiệt"])
sub("b_city", "市区町村", "Quận / huyện", ".mbox .fld::市区町村", "text", ["拠点の市区町村の部分一致。", "Khớp một phần quận/huyện của cơ sở."], req="－", len="文字列 60", ex=["港区", "Quận/huyện"])
sub("b_zip", "郵便番号（頭）", "Mã bưu chính (đầu)", ".mbox .fld::郵便番号（頭）", "text", ["拠点の郵便番号の頭の数字（前方一致）。", "Chữ số đầu của mã bưu chính cơ sở (khớp đầu)."], req="－", len="文字列 8", ex=["105", "Vài chữ số đầu của mã bưu chính"])
sub("b_prefs", "都道府県（複数）", "Tỉnh thành (nhiều)", ".mbox .fld::都道府県（複数）", "check", ["拠点の住所にある都道府県をチェックで複数選ぶ。選ばなければ全部。", "Tích chọn nhiều tỉnh thành có trong địa chỉ cơ sở. Không chọn là tất cả."], req="－", len=U("選択（複数）", "Chọn (nhiều)"), init=U("チェックなし", "Không tích"), ex=["東京都・神奈川県", "Tích nhiều tỉnh thành"])
big("b_to", "② 適用開始", "② Bắt đầu áp dụng", ".mbox .sec-h::② 適用開始", "area", ["切り替える価格の世代と、適用開始のサイクル。未確定の子契約だけが対象で、確定・請求済は変えない。", "Thế hệ giá cần đổi sang và chu kỳ bắt đầu áp dụng. Chỉ hợp đồng con chưa xác định là đối tượng, tháng đã chốt / đã xuất hóa đơn không đổi."])
sub("b_togen", "切り替える価格の世代", "Thế hệ giá cần đổi sang", ".mbox .fld::切り替える価格の世代", "select", ["子契約の「適用された価格プラン」に書く（決定 28-181）。空＝サイクル月の世代（適用開始 ≦ サイクル月のいちばん新しい世代）。選んだ世代の金額で ① の費目を作り直す。上書きした金額（オプションなど）は残し、対象の一覧に「上書きあり」と出す。", "Ghi vào \"適用された価格プラン\" của hợp đồng con (quyết định 28-181). Trống = thế hệ theo tháng chu kỳ (thế hệ mới nhất có bắt đầu áp dụng ≦ tháng chu kỳ). Dựng lại hạng mục ① theo số tiền của thế hệ đã chọn. Số tiền đã ghi đè (tùy chọn...) giữ nguyên và hiện \"上書きあり\" ở danh sách đối tượng."], req="－", len=U("選択（価格プランの世代）", "Chọn (thế hệ giá của gói)"), init=U("サイクル月の世代", "Thế hệ theo tháng chu kỳ"), ex=["PG-ES000004-03 改訂第二回目", "Chọn 1 thế hệ giá"],
    demo_ok=["コードの一覧に「上書きあり」の表示がない（契約_05 の料金の上書き。足す宿題）", "Danh sách của code chưa hiển thị \"上書きあり\" (ghi đè giá ở 契約_05. Việc phải thêm)"])
sub("b_cycle", "適用開始のサイクル", "Chu kỳ bắt đầu áp dụng", ".mbox .fld::適用開始のサイクル", "select", ["「yyyy-mm（未確定 n件・確定/請求済 n件は変えない）」から選ぶ。初期は最初のサイクル。", "Chọn từ \"yyyy-mm (chưa xác định n件・đã chốt / đã xuất n件 không đổi)\". Mặc định là chu kỳ đầu tiên."], req="○", len=U("選択（年月）", "Chọn (năm-tháng)"), init=U("最初のサイクル月", "Tháng chu kỳ đầu tiên"), ex=["2026-12", "Chọn 1 tháng chu kỳ"])
sub("b_cancel", "キャンセル", "Hủy", ".mbox-f button::キャンセル", "button", ["閉じる（何も変えない）。", "Đóng (không đổi gì)."])
sub("b_next", "対象を見る", "Xem đối tượng", ".mbox-f button::対象を見る", "button", ["② へ進む。プランが空のときは押せない。", "Sang ②. Không bấm được khi gói trống."])
big("b_rows", "② 対象（比較の列）", "② Đối tượng (cột so sánh)", ".mbox .sec-h::対象（", "area", ["「対象（n件・選択 m件）」。表：チェック・契約・拠点（法人・都道府県市区町村・コース・温度帯）・コース・請求の差（月額・税抜）・子契約（サイクル月ごとの 変更／スキップ〈請求済（請求調整）など〉）・注意。既定で全部選ぶ。「全て選ぶ」は表の全件。選べない・変えない子契約は理由つきでスキップとして出す。条件に合う契約がなければ「条件に合う契約はありません」。", "\"対象（n件・選択 m件）\". Bảng: ô tích, hợp đồng, cơ sở (pháp nhân・tỉnh quận・course・vùng nhiệt), course, chênh lệch hóa đơn (hằng tháng・chưa thuế), hợp đồng con (từng tháng chu kỳ: thay đổi / bỏ qua <đã xuất hóa đơn (điều chỉnh hóa đơn)...>), lưu ý. Mặc định chọn tất cả. \"全て選ぶ\" áp dụng toàn bộ bảng. Hợp đồng con không chọn / không đổi được hiện là bỏ qua kèm lý do. Nếu không có hợp đồng phù hợp thì hiện \"条件に合う契約はありません\"."], pattern="P-BULK")
sub("b_all", "全て選ぶ", "Chọn tất cả", ".mbox thead input[type=checkbox]", "check", ["表の全件を選ぶ／外す。", "Chọn / bỏ chọn toàn bảng."], req="－", init=U("チェックあり", "Có tích"), ex=["チェックを外す", "Bỏ tích để bỏ chọn tất cả"])
sub("b_diff", "請求の差（月額・税抜）", "Chênh lệch hóa đơn (hằng tháng・chưa thuế)", ".mbox th.num", "label", ["切り替えたあとの月額（税抜）と今の月額の差。金額の列は右寄せ。", "Chênh lệch giữa số tiền hằng tháng (chưa thuế) sau khi đổi và hiện tại. Cột số tiền căn phải."])
sub("b_back2", "戻る", "Quay lại", ".mbox-f button::戻る", "button", ["① へ戻る（条件を残したまま）。", "Về ① (giữ nguyên điều kiện)."])
sub("b_next2", "確認へ（n件）", "Sang xác nhận (n)", ".mbox-f button::確認へ", "button", ["③ へ進む。選択が0件のときは押せない。", "Sang ③. Không bấm được khi chọn 0 dòng."])
big("b_confirm", "③ 確認（後ろの流れへの影響）", "③ Xác nhận (ảnh hưởng đến luồng phía sau)", ".mbox .sec-h::後ろの流れへの影響", "area", ["「後ろの流れへの影響（yyyy-mm サイクルから・n件）」：変える契約・子契約（変える）・子契約（変えない：確定・請求済）・請求の差（月額・税抜の合計）・金額が変わる子契約。注意があるときは「確かめてください（n件）」の一覧と「注意を確かめたうえで実行する」のチェック（チェックしないと実行できない）。「法人に通知する」のチェック。対象が100件を超えるときは件数の打ち直し。「実行すると元に戻せません（履歴は残ります）。」", "\"後ろの流れへの影響（từ chu kỳ yyyy-mm・n件）\": hợp đồng sẽ đổi, hợp đồng con (đổi), hợp đồng con (không đổi: đã chốt / đã xuất hóa đơn), chênh lệch hóa đơn (tổng hằng tháng chưa thuế), hợp đồng con thay đổi số tiền. Khi có lưu ý thì hiện danh sách \"確かめてください（n件）\" và ô tích \"注意を確かめたうえで実行する\" (không tích thì không thực hiện được). Ô tích \"法人に通知する\". Khi đối tượng quá 100 thì nhập lại số lượng. \"実行すると元に戻せません（履歴は残ります）。\""], pattern="P-BULK")
sub("b_impact", "後ろの流れへの影響", "Ảnh hưởng đến luồng phía sau", ".mbox .kvgrid", "label", ["変える契約・子契約（変える）・子契約（変えない：確定・請求済）・請求の差・金額が変わる子契約の件数。", "Số hợp đồng sẽ đổi, hợp đồng con (đổi), hợp đồng con (không đổi: đã chốt / đã xuất), chênh lệch hóa đơn, hợp đồng con thay đổi số tiền."],
    demo_ok=["コードは価格世代のモードでも「子契約（変えない：オーダー締切後で新しい倉庫にない商品の注文あり）」の行を出す（ルートのモードの項目。価格世代では出さない宿題）", "Code ở chế độ thế hệ giá vẫn hiện dòng \"子契約（変えない：オーダー締切後で新しい倉庫にない商品の注文あり）\" (mục của chế độ lộ trình. Việc phải sửa: không hiện ở thế hệ giá)"])
sub("b_alerts", "注意の確認", "Xác nhận lưu ý", ".mbox .notice.warn b", "check", ["注意（上書きした金額がある・日付やリードタイムの注意など）があるときだけ出す。チェックすると実行できる。確かめた記録を一括変更の履歴に残す。", "Chỉ hiện khi có lưu ý (có số tiền ghi đè, lưu ý về ngày / lead time...). Tích thì thực hiện được. Ghi lại việc đã xác nhận vào lịch sử đổi hàng loạt."], req="○", init=U("チェックなし", "Không tích"), ex=["チェックする", "Tích sau khi xác nhận lưu ý"], cond=["注意があるとき", "Khi có lưu ý"],
    demo_ok=["コードの「注意の確認」（上書き・日付・リードタイムの注意）は「ルート」モード（倉庫マスタなどから開く一括変更）の確認だけで出す。この画面（子契約一覧）の「価格世代を一括切替」では出ない。設計書の置き場（この画面の確認）と合わない。撮るには倉庫の画面から開く一括変更が要る", "\"注意の確認\" (ghi đè / ngày / lead time) trong code chỉ hiện ở bước xác nhận của chế độ \"ルート\" (đổi hàng loạt mở từ 倉庫マスタ...). Ở màn này (子契約一覧) \"価格世代を一括切替\" không hiện. Không khớp với chỗ đặt trong 設計書 (xác nhận của màn này). Muốn chụp cần mở đổi hàng loạt từ màn kho"])
sub("b_notify", "法人に通知する", "Thông báo cho pháp nhân", ".mbox label::法人に通知する", "check", ["変わる拠点の法人・拠点アカウントへ通知する。既定はチェックなし。", "Thông báo cho tài khoản pháp nhân / cơ sở của cơ sở có thay đổi. Mặc định không tích."], req="－", init=U("チェックなし", "Không tích"), ex=["チェックする", "Tích để thông báo cho pháp nhân"])
sub("b_retype", "件数の打ち直し", "Nhập lại số lượng", ".mbox .fld::確認のため件数を入れてください", "text", ["対象が100件を超えるときだけ出す。対象の件数を打ち直さないと実行できない（誤操作の防止）。", "Chỉ hiện khi đối tượng quá 100. Phải nhập lại số lượng đối tượng mới thực hiện được (phòng thao tác nhầm)."], req="○", len=U("整数（件数）", "Số nguyên (số lượng)"), ex=["120", "Gõ lại số lượng đối tượng"], valid=["必須。対象の件数と同じ数字。", "Bắt buộc. Cùng số với số lượng đối tượng."], cond=["対象が100件を超えるとき", "Khi đối tượng quá 100"],
    demo_ok=["件数の打ち直しは「変える契約（親契約）」が100件を超えるときに出る（子契約の数ではない）。見本の親契約は3件で、子契約を増やしても（実際に144件にして確認）出ない。撮るには親契約が101件以上のデータが要る", "Nhập lại số lượng hiện khi \"変える契約\" (hợp đồng cha) vượt 100 (không phải số hợp đồng con). Dữ liệu mẫu có 3 hợp đồng cha, tăng hợp đồng con (đã thử lên 144) cũng không hiện. Muốn chụp cần dữ liệu có từ 101 hợp đồng cha trở lên"])
sub("b_back3", "戻る（確認）", "Quay lại (xác nhận)", ".mbox-f button::戻る", "button", ["② へ戻る。", "Về ②."])
sub("b_run", "一括変更を実行（n件）", "Thực hiện đổi hàng loạt (n)", ".mbox-f button::一括変更を実行", "button", ["実行する。注意の確認・件数の打ち直しが必要なときは、済むまで押せない。押したら二重に押せなくする。フル権限・システム管理だけに出す。", "Thực hiện. Khi cần xác nhận lưu ý / nhập lại số lượng thì không bấm được cho đến khi xong. Bấm xong khóa nút. Chỉ hiện với フル権限・システム管理."], cond=BULKP)
big("b_result", "④ 実行（進み具合）と結果", "④ Thực hiện (tiến độ) và kết quả", ".mbox .sec-h::結果", "area", ["分けて進める（進み具合のバー）。「結果（一括変更の番号）」：進み具合・変更・スキップ・失敗・子契約の件数、表（契約・結果・理由・スキップした子契約）。スキップ・失敗がなければ「スキップ・失敗はありません」。終わったら「一括変更 ID が終わりました（変更 n件・スキップ m件・失敗 k件）。」のトースト（S107）。元に戻す操作はない（履歴は残る）。「閉じる」で閉じる（実行中は押せない）。", "Chạy chia nhỏ (thanh tiến độ). \"結果 (số đổi hàng loạt)\": tiến độ, thay đổi, bỏ qua, lỗi, số hợp đồng con, bảng (hợp đồng, kết quả, lý do, hợp đồng con bị bỏ qua). Không có bỏ qua / lỗi thì hiện \"スキップ・失敗はありません\". Xong hiện toast \"一括変更 ID が終わりました（変更 n件・スキップ m件・失敗 k件）。\" (S107). Không có thao tác hoàn tác (lịch sử vẫn còn). Bấm \"閉じる\" để đóng (không bấm được khi đang chạy)."], pattern="P-BULK", err=["S107", "W10"])
sub("b_meter", "進み具合", "Tiến độ", ".mbox .meter", "label", ["「進み具合 n / m」のバー。", "Thanh \"進み具合 n / m\"."])
sub("b_kv", "結果の件数", "Số lượng kết quả", ".mbox .kvgrid", "label", ["進み具合・変更・スキップ・失敗・子契約・配送データ・出荷指示の再送・注文をデフォルトに。価格世代では配送データ以降は0件。", "Tiến độ, thay đổi, bỏ qua, lỗi, hợp đồng con, dữ liệu giao hàng, gửi lại chỉ thị xuất hàng, đưa đơn về mặc định. Ở thế hệ giá thì từ dữ liệu giao hàng trở đi là 0."])
sub("b_rtable", "結果の表", "Bảng kết quả", ".mbox table", "table", ["契約・結果（変更／スキップ／失敗）・理由・スキップした子契約（ID：理由）。", "Hợp đồng, kết quả (thay đổi / bỏ qua / lỗi), lý do, hợp đồng con bị bỏ qua (ID: lý do)."])
sub("b_close", "閉じる", "Đóng", ".mbox-f button::閉じる", "button", ["モーダルを閉じる（実行が終わるまで押せない）。", "Đóng modal (không bấm được cho đến khi thực hiện xong)."])
sub("b_toast", "実行の終了（トースト）", "Kết thúc thực hiện (toast)", ".toast", "toast", ["終わったら S107 を出す。", "Xong thì hiện S107."], err=["S107"])
big("b_hist", "履歴タブ（これまでの一括変更）", "Tab lịch sử (các lần đổi hàng loạt trước)", ".mbox .tbl-wrap", "table", ["番号・実行日時・種類（価格世代・世代→ID・注意 n件を確認済）・適用開始・件数・結果（変更・スキップ・失敗）・状態。新しい順。ない間は「まだありません」。", "Số, ngày giờ thực hiện, loại (thế hệ giá・thế hệ→ID・đã xác nhận n lưu ý), bắt đầu áp dụng, số lượng, kết quả (thay đổi・bỏ qua・lỗi), trạng thái. Mới nhất trước. Chưa có thì hiện \"まだありません\"."], pattern="P-HIST",
    demo_ok=["コードの履歴の列は P-HIST（日時・操作した人・操作・項目・変更前・変更後・理由）と違い、一括変更の1行1件。操作した人の列がない（足す宿題）", "Cột lịch sử của code khác P-HIST (ngày giờ, người thao tác, thao tác, mục, trước, sau, lý do), là mỗi dòng một lần đổi hàng loạt. Chưa có cột người thao tác (việc phải thêm)"])

# ================================================================ AW_CONT_005 CSV取込
big("c_head", "ヘッダー", "Đầu trang", ".es-pagehead", "area", ["パンくず（法人・契約管理 / 子契約一覧 / 子契約一覧 CSV取込）・画面名・キャンセル。フル権限・システム管理だけが開ける。モーダルではなく画面。", "Breadcrumb (法人・契約管理 / 子契約一覧 / 子契約一覧 CSV取込), tên màn hình, hủy. Chỉ フル権限・システム管理 mở được. Là màn hình, không phải modal."], pattern="P-CSV")
sub("c_cancel", "キャンセル", "Hủy", ".es-pagehead__actions button::キャンセル", "button", ["子契約一覧へ戻る（何も登録しない）。", "Về danh sách hợp đồng con (không đăng ký gì)."])
big("c_step1", "ステップ1 ファイルを選ぶ", "Bước 1: chọn tệp", ".es-card", "area", ["手順の表示・説明・ファイルを選ぶ（ドラッグ＆ドロップも可）。キーは 親契約番号（契約ID）＋適用開始（yyyy-mm）。その月から後ろの未確定の月の子契約にも同じ変更を当てる。確定・請求済の月は変えられず行エラー（E118）。仮登録の拠点の子契約も行エラー。子契約は CSV では作れない（拠点の「子契約を先まで作る」を使う）。空欄のセルは今の値のまま、消すときは「-」。", "Hiển thị các bước, giải thích, chọn tệp (kéo thả được). Khóa = 親契約番号（契約ID） + 適用開始 (yyyy-mm). Áp dụng cùng thay đổi cho hợp đồng con các tháng chưa xác định từ tháng đó trở đi. Tháng đã chốt / đã xuất hóa đơn không đổi được và là lỗi dòng (E118). Hợp đồng con của cơ sở 仮登録 cũng lỗi dòng. Không tạo hợp đồng con bằng CSV (dùng \"子契約を先まで作る\" của cơ sở). Ô trống giữ giá trị cũ, ghi \"-\" để xóa."], pattern="P-CSV")
sub("c_steps", "手順", "Các bước", ".es-card ol.steps", "label", ["「1 ファイルを選ぶ」「2 確認・登録」。", "\"1 ファイルを選ぶ\" \"2 確認・登録\"."])
sub("c_hint", "説明", "Giải thích", ".es-card .hint", "label", ["キー（親契約番号＋適用開始）・列は詳細・編集の項目と同じ・UTF-8・行数の上限。", "Khóa (số hợp đồng cha + 適用開始), cột giống mục ở chi tiết / sửa, UTF-8, giới hạn số dòng."])
sub("c_pick", "ファイルを選ぶ", "Chọn tệp", ".es-card button::ファイルを選ぶ", "file", ["CSV（UTF-8、BOM あり・なし）を選ぶ。5,000行まで。選ぶとすぐステップ2へ。読み込めないファイルは E51。", "Chọn CSV (UTF-8, có hoặc không BOM). Tối đa 5.000 dòng. Chọn xong chuyển ngay sang bước 2. Tệp không đọc được thì E51."], req="○", len=U("CSV（UTF-8・5,000行まで）", "CSV (UTF-8, tối đa 5.000 dòng)"), ex=["keiyaku_20261005.csv", "Tệp CSV do hệ thống xuất ra rồi sửa"], err=["E51"])
big("c_cols", "CSVテンプレートの列（定義。画面には出さない）", "Các cột của CSV template (định nghĩa; không hiện trên màn hình)", "-", "area", ["取り込むファイルの列の定義（1行目の見出し・この順。CSV出力と同じ列）。キー＝親契約番号（契約ID）＋適用開始（yyyy-mm）。UTF-8（BOM 可）・5,000行まで。空欄のセルは今の値のまま、「-」で消す。必須・長さ・チェックは入力画面（AW_CONT_003）の項目と同じ（違うところだけ書く）。読むだけの列（子契約ID・拠点ID・拠点名・法人名・請求の状態・当月請求額など）は値を入れても取り込まない。配送ルート設定・回ごとのルート・設備の異動・オプション・割引の表は CSV に含めない。画面には出さない（hong 2026/10/05）。", "Định nghĩa cột của tệp nhập (dòng 1 = tiêu đề, theo thứ tự này; cùng cột với CSV出力). Khóa = 親契約番号（契約ID） + 適用開始 (yyyy-mm). UTF-8 (có BOM được), tối đa 5.000 dòng. Ô trống giữ giá trị cũ, \"-\" để xóa. Bắt buộc / độ dài / kiểm tra giống mục ở màn nhập (AW_CONT_003) (chỉ ghi chỗ khác). Cột chỉ đọc (子契約ID・拠点ID・拠点名・法人名・請求の状態・当月請求額...) có điền cũng không nhập. Bảng lộ trình giao・lộ trình theo lần・di chuyển thiết bị・tùy chọn・giảm giá không đưa vào CSV. Không hiện trên màn hình (hong 2026/10/05)."], pattern="P-CSV")

def csvcol(key, ja, vi, ref, kind="text", req="－", ln=None, ex=None, extra=None, ro=False, err=None):
    d = ["画面の項目「%s」（No.%s）と同じ。" % (ja, ITEMS[ref]["no"]) if ref else (extra[0] if extra else ""), "Giống mục 「%s」 (No.%s) trên màn hình." % (ja, ITEMS[ref]["no"]) if ref else (extra[1] if extra else "")]
    kw = dict(req=req, len=ln or "文字列 60", init=INIT_BLANK)
    if kind in ("text", "textarea", "select"): kw["ex"] = ex
    if ro: kw["valid"] = ["読むだけの列。値を入れても取り込まない（無視する）。", "Cột chỉ đọc. Có điền giá trị cũng không nhập (bỏ qua)."]
    else: kw["valid"] = ["新規の行で必須の列は更新の行では空欄＝今の値のまま。「-」で消せる（必須の項目は消せない）。", "Cột bắt buộc ở dòng mới thì ở dòng cập nhật để trống = giữ giá trị cũ. Ghi \"-\" để xóa (mục bắt buộc không xóa được)."]
    if err: kw["err"] = err
    return sub(key, ja, vi, "-", kind, d, **kw)

csvcol("k_cp", "親契約番号（契約ID）", "Số hợp đồng cha", None, "text", "○", U("文字列 CP＋連番", "Chuỗi CP + số thứ tự"), ["CP0000001", "Số hợp đồng cha hiện có"], ["キー（1つ目）。存在しない親契約番号・空欄の行はエラー。", "Khóa (thứ nhất). Dòng có số hợp đồng cha không tồn tại / trống là lỗi."], err=["E01"])
csvcol("k_start", "適用開始", "Bắt đầu áp dụng", None, "text", "○", U("年月（yyyy-mm）", "Năm-tháng (yyyy-mm)"), ["2026-12", "Tháng bắt đầu áp dụng thay đổi"], ["キー（2つ目）。この月から後ろの未確定の月の子契約に同じ変更を当てる。確定・請求済の月は E118。子契約のない月（未生成）は行エラー。", "Khóa (thứ hai). Áp dụng cùng thay đổi cho hợp đồng con các tháng chưa xác định từ tháng này trở đi. Tháng đã chốt / đã xuất hóa đơn là E118. Tháng chưa có hợp đồng con (chưa sinh) là lỗi dòng."], err=["E01", "E118"])
for _c, _v, _e in [("子契約ID", "ID hợp đồng con", "CP0000001-202612"), ("拠点ID", "Mã cơ sở", "CU00643"), ("拠点名", "Tên cơ sở", "株式会社サンプル 本社"), ("法人名", "Tên pháp nhân", "株式会社サンプル"), ("請求の状態", "Trạng thái hóa đơn", "未確定"), ("当月請求額", "Số tiền hóa đơn tháng này", "66000")]:
    csvcol("k_ro_" + _c, _c, _v, None, "text", "－", "文字列 60", [_e, "Chỉ đọc"], ["読むだけ。", "Chỉ đọc."], ro=True)
_ORDER = ["f_plan", "f_course", "f_from", "f_to", "f_cancel", "f_priceplan", "f_subsidy", "f_cash", "f_daily", "f_monthly", "f_guest", "f_esqr", "f_ship", "f_dno", "f_ng", "f_shift", "f_dnote", "f_floor", "f_imemo", "f_appnote", "f_welfare", "f_adj"]
_FBY = {x["key"]: x for _t, _c, _cv, _fs in FIELDS for x in _fs}
for _k in _ORDER:
    _x = _FBY[_k]
    _ro = _x["kw"].get("ro", False)
    _csvkind = "select" if _x["kind"] in ("select", "check") else ("textarea" if _x["kind"] == "textarea" else "text")
    _ln = _x["len"] if _x["len"] else "文字列 60"
    _req = "○" if (_x["mark"] == "*" and not _ro) else "－"
    _ex = _x["ex"] or ["—", "Chỉ đọc"]
    csvcol("k" + _k[1:], _x["ja"], _x["vi"], _k, _csvkind, _req, _ln, _ex, ro=_ro, err=_x["err"][:3] if not _ro else None)
csvcol("k_sched", "設備の引揚希望日／搬入希望日／設置予定日", "Ngày mong muốn thu hồi / lắp / dự kiến lắp đặt thiết bị", None, "text", "－", "文字列 60", ["2026-12-10", "Ngày dự kiến"], ["設備入替・再設置があるときは必須（設備手配のリードタイムは1週間程度）。3つの日付を1列で「引揚 ／ 搬入 ／ 設置」の形に書く。", "Bắt buộc khi đổi / lắp lại thiết bị (lead time chuẩn bị thiết bị khoảng 1 tuần). Ghi 3 ngày trong 1 cột dạng \"thu hồi ／ lắp ／ lắp đặt\"."], err=["E04"])
csvcol("k_diff", "前の子契約との差分", "Chênh lệch với hợp đồng con trước", None, "text", "－", "文字列 255", ["資材ボックスの追加貸出 1箱", "Chỉ đọc"], ["前の子契約との差の説明。読むだけ。", "Giải thích chênh lệch với hợp đồng con trước. Chỉ đọc."], ro=True)
big("c_step2", "ステップ2 確認・登録", "Bước 2: xác nhận・đăng ký", ".es-card", "area", ["ファイル名・件数（更新／変更なし／エラー）と、行ごとの結果。「登録」でエラー以外の行（更新）を登録する（エラーの行は取り込まない・hong 2026/10/05）。登録すると、適用開始の月から後ろの未確定の子契約にも同じ変更を当て、配送の流れ・プランの変更は出荷の前の配送・注文にも反映する（契約の画面の保存と同じ）。", "Tên tệp, số dòng (cập nhật / không đổi / lỗi) và kết quả từng dòng. \"登録\" thì đăng ký các dòng không lỗi (cập nhật) (dòng lỗi bỏ qua; hong 2026/10/05). Khi đăng ký, áp dụng cùng thay đổi cho hợp đồng con chưa xác định từ tháng bắt đầu áp dụng trở đi, thay đổi luồng giao hàng / gói cũng phản ánh vào giao hàng / đơn hàng trước khi xuất (giống lưu ở màn hợp đồng)."], pattern="P-CSV", err=["Q10", "S10", "S03", "E34"])
sub("c_count", "件数", "Số lượng", ".es-card .badge", "label", ["更新／変更なし／エラー の件数（バッジ）。子契約は新規がない。", "Số dòng cập nhật / không đổi / lỗi (badge). Hợp đồng con không có dòng mới."])
sub("c_errs", "エラーの行", "Dòng lỗi", ".es-card .notice", "label", ["「エラーの行 n件は取り込みません…」と、行番号・キー・列名・内容の表。確定・請求済の月は E118、ほかは E52 と各列のチェックの文言。", "\"エラーの行 n件は取り込みません…\" và bảng số dòng, khóa, tên cột, nội dung. Tháng đã chốt / đã xuất hóa đơn là E118, còn lại là E52 và câu kiểm tra của từng cột."], err=["E52", "E118"], cond=["エラーの行があるとき", "Khi có dòng lỗi"])
sub("c_errcsv", "エラー一覧CSV", "Xuất CSV lỗi", ".es-card button::エラー一覧CSV", "button", ["エラーの行だけを、元の列＋エラーの内容で書き出す。", "Xuất riêng các dòng lỗi với cột gốc + nội dung lỗi."])
sub("c_diff", "登録する内容（前 → 後）", "Nội dung sẽ đăng ký (trước → sau)", ".es-card b::登録する内容", "label", ["行番号・キー・名前・変わる項目（前 → 後）・影響（適用開始の月から後ろの未確定の月にも当てる）。", "Số dòng, khóa, tên, các mục thay đổi (trước → sau), ảnh hưởng (áp dụng cho cả các tháng chưa xác định từ tháng bắt đầu trở đi)."], cond=["更新の行があるとき", "Khi có dòng cập nhật"])
sub("c_reselect", "ファイルを選び直す", "Chọn lại tệp", ".es-pagehead__actions button::ファイルを選び直す", "button", ["ステップ1に戻る。何も登録しない。", "Về bước 1. Không đăng ký gì."])
sub("c_go", "登録", "Đăng ký", ".es-pagehead__actions button.pri", "button", ["確認（Q10）のあと、エラー以外の行を登録し、S10 のトースト（更新 n件）を出して一覧へ戻る。取込の記録と、行ごとの変更履歴「CSV取込で更新」（変更区分＝CSV取込・適用範囲＝以降すべて）を残す。", "Sau xác nhận (Q10), đăng ký các dòng không lỗi, hiện toast S10 (cập nhật n件) rồi về danh sách. Ghi lại lịch sử nhập và lịch sử từng bản ghi \"CSV取込で更新\" (変更区分 = nhập CSV・phạm vi áp dụng = 以降すべて)."], err=["Q10", "S10", "E34"], cond=["ファイル全体のエラーがなく、更新の行が1つ以上あるとき", "Khi không có lỗi toàn tệp và có ≥ 1 dòng cập nhật"])
big("c_fileerr", "ファイル全体のエラー", "Lỗi toàn tệp", ".es-card .notice", "label", ["CSV として読めない・文字コードが違う・列の見出しが違う・行数の上限を超えるときは、ステップ2に進まず E51 を出す。", "Khi không đọc được như CSV, sai mã hóa, sai tiêu đề cột, hoặc vượt số dòng thì không sang bước 2 mà hiện E51."], err=["E51"])

# ---------------------------------------------------------------- 状態
L_KW = "setv(q('.es-search input[aria-label=\"子契約ID、拠点名、法人名\"]'),%s);"
CSV_BAD = ("const text=await csvText('contracts',(t,rows)=>{const ci=t.head.findIndex(h=>/^親契約番号/.test(h));const si=t.head.findIndex(h=>/^適用開始(【|$)/.test(h));const di=t.head.findIndex(h=>/^配送備考$/.test(h));"
           "const ok=rows.findIndex((r,i)=>i>0&&r[ci]==='CP0000004'&&r[si]==='2026-12');const lk=rows.findIndex((r,i)=>i>0&&r[ci]==='CP0000001'&&r[si]==='2026-11');"
           "if(di>=0&&ok>0)rows[ok][di]='納品は午前中にお願いします。';if(di>=0&&lk>0)rows[lk][di]='搬入口の変更';const bad=t.rows[0].slice();bad[ci]='CP9999999';rows.push(bad);});"
           "await upload(text,'子契約取込テスト.csv');")
FILE_ERR = ("const inp=q('input[type=file]');const dt=new DataTransfer();dt.items.add(new File([new Uint8Array([255,254,0,1,2,3,200,201])],'壊れたファイル.csv',{type:'text/csv'}));inp.files=dt.files;inp.dispatchEvent(new Event('change',{bubbles:true}));await sleep(1500);")
LIST_HEADK = ["l_head", "l_crumb", "l_title", "l_bulk", "l_csvin", "l_csvout"]
SEARCHK = ["l_search", "l_kw", "l_month", "l_kind", "l_plan", "l_ship", "l_bst", "l_gen", "l_clear", "l_go", "l_sort"]
TABLEK = ["l_table", "l_id", "l_m", "l_br", "l_corp", "l_kind_c", "l_plan_c", "l_ship_c", "l_bm", "l_amt", "l_bst_c", "l_gen_c", "l_act"]
DETAIL_HEAD = ["d_head", "d_crumb", "d_title", "d_sum", "d_edit"]
DETAIL_STICK = ["d_stick", "d_tabs", "d_search", "d_fold", "d_editonly", "d_idx"]
EDIT_HEAD = ["e_head", "e_cancel", "e_save"]
def FK(i): return [x["key"] for x in FIELDS[i][3]]
TAB = lambda name: "tab('%s').click();await sleep(400);" % name
TABURL = lambda path, name: path + "?tab=" + __import__("urllib.parse", fromlist=["quote"]).quote(name)
DET = "/ops/contracts/CP0000001-202703"

VIEWS = [
    # ---- 一覧
    V("001", "AW_CONT_001", "初期表示", "Hiển thị ban đầu", "/ops/contracts", LIST_HEADK + SEARCHK + TABLEK + ["l_pager"], note=["契約・サイクル月の降順（新しい月が上）。新規登録・削除のボタンはない。「価格世代を一括切替」はフル権限・システム管理だけ。", "Tháng chu kỳ giảm dần (tháng mới ở trên). Không có nút đăng ký mới / xóa. \"価格世代を一括切替\" chỉ フル権限・システム管理."]),
    V("002", "AW_CONT_001", "検索（条件・並べ替え）→ 結果", "Tìm kiếm (điều kiện・sắp xếp) → kết quả", "/ops/contracts", ["l_search", "l_kw", "l_month", "l_ship", "l_go", "l_table", "l_id", "l_bst_c"],
      setup=L_KW % "'大阪'" + "setsel(q('.es-search select[aria-label=\"契約・サイクル月\"]'),'2026-11');await sleep(200);search();await sleep(500);", note=["キーワード「大阪」・契約・サイクル月＝2026-11で検索した状態。", "Trạng thái tìm với từ khóa \"大阪\" và tháng chu kỳ = 2026-11."]),
    V("003", "AW_CONT_001", "0件", "0 dòng", "/ops/contracts", ["l_kw", "l_table"], setup=L_KW % "'存在しない拠点'" + "search();await sleep(500);", note=["該当する子契約がないとき I01 を表の中に出す。", "Khi không có hợp đồng con phù hợp thì hiện I01 trong bảng."]),
    V("004", "AW_CONT_001", "仮登録の行（申請で編集）", "Dòng đăng ký tạm (sửa ở đơn)", "/ops/contracts", ["l_id", "l_apply", "l_act"], setup=L_KW % "'あおば'" + "search();await sleep(500);", note=["仮登録の拠点（あおば仙台工場）の子契約は「仮登録」のバッジと「申請で編集」。", "Hợp đồng con của cơ sở đăng ký tạm (あおば仙台工場) có badge \"仮登録\" và \"申請で編集\"."]),
    V("005", "AW_CONT_001", "手動生成の行", "Dòng tạo bằng tay", "/ops/contracts", ["l_gen", "l_gen_c"], setup="setsel(q('.es-search select[aria-label=\"生成方法\"]'),'手動生成');await sleep(200);search();await sleep(500);", note=["生成方法＝手動生成で検索した状態（拠点の「子契約を先まで作る」で作った行）。", "Trạng thái tìm với cách sinh = 手動生成 (dòng tạo bằng \"子契約を先まで作る\" của cơ sở)."]),
    V("006", "AW_CONT_001", "ページ送り（2ページ目）", "Phân trang (trang 2)", "/ops/contracts", ["l_pager", "l_table"], setup="[...document.querySelectorAll('.es-pagination .es-page')].find(b=>b.textContent.trim()==='2').click();await sleep(400);", note=["見本は72件。1ページ10件で8ページ。", "Dữ liệu mẫu 72 dòng. 10 dòng/trang, 8 trang."]),
    V("007", "AW_CONT_001", "CSV出力（トースト）", "Xuất CSV (toast)", "/ops/contracts", ["l_csvout"], setup="btn('CSV出力').click();await sleep(1500);", note=["検索条件のとおりの全件を出し、終わったら S12 のトースト。", "Xuất toàn bộ theo điều kiện, xong hiện toast S12."]),
    V("008", "AW_CONT_001", "参照のみの権限（営業）", "Quyền chỉ xem (営業)", "/ops/contracts", ["l_head", "l_csvout", "l_table", "l_act"], login="Ad00001", note=["営業（Ad00001・R）でログインした状態。価格世代を一括切替・CSV取込・鉛筆が出ない。CSV出力は出る。", "Trạng thái đăng nhập bằng 営業 (Ad00001・R). Không hiện 価格世代を一括切替・CSV取込・bút. CSV出力 vẫn hiện."]),
    V("009", "AW_CONT_001", "CS（R/U）の権限", "Quyền CS (R/U)", "/ops/contracts", ["l_head", "l_bulk", "l_act"], login="Ad00002", note=["CS（Ad00002・R/U）でログインした状態。鉛筆（編集）は出る。決定は価格世代を一括切替を出さない（フル権限・システム管理だけ）。コードは出る（l_bulk の demo_ok）。", "Trạng thái đăng nhập bằng CS (Ad00002・R/U). Có hiện bút (sửa). Theo quyết định không hiện 価格世代を一括切替 (chỉ フル権限・システム管理). Code vẫn hiện (demo_ok của l_bulk)."]),
    # ---- 詳細
    V("010", "AW_CONT_002", "タブ「契約」", "Tab \"契約\"", DET, DETAIL_HEAD + DETAIL_STICK + ["d_child", "d_scopebtn", "d_contract", "d_plan", "d_price", "d_subsidy", "d_buyout", "d_app", "d_ship", "d_route", "d_slot", "d_memo"], login="Ad00010", note=["自販機の拠点（CP0000001）の最新の月。入力欄はすべて読むだけ。", "Tháng mới nhất của cơ sở máy bán hàng (CP0000001). Mọi ô chỉ xem."]),
    V("011", "AW_CONT_002", "タブ「料金・請求」", "Tab \"料金・請求\"", TABURL(DET, "料金・請求"), ["d_tabs", "d_pay", "d_billcard", "d_welfare", "d_welf"], note=["支払情報（スナップショット）・請求詳細を開く・値引き・負担額。", "Thông tin thanh toán (snapshot), mở chi tiết hóa đơn, giảm giá・mức chịu."]),
    V("012", "AW_CONT_002", "タブ「設備・オプション」", "Tab \"設備・オプション\"", TABURL(DET, "設備・オプション"), ["d_tabs", "d_loan", "d_optcard", "d_sched"], note=["設備の異動・オプション・割引・設置・引揚の予定。", "Di chuyển thiết bị, tùy chọn・giảm giá, lịch lắp đặt / thu hồi."]),
    V("013", "AW_CONT_002", "タブ「変更履歴」", "Tab \"変更履歴\"", TABURL(DET, "変更履歴"), ["d_tabs", "d_hist", "d_diff"], note=["変更区分・適用範囲・承認者・通知の有無つき。前月からの差分。", "Kèm 変更区分・phạm vi áp dụng・người duyệt・có thông báo. Chênh lệch so với tháng trước."]),
    V("014", "AW_CONT_002", "承認待ちの申請があるため項目がロック", "Mục bị khóa vì có đơn chờ duyệt", "/ops/contracts/CP0000002-202702", ["d_pend"], note=["承認待ちの申請（CH-20260925-0001 プランの変更）がある拠点（CU00871 大阪支店）。", "Cơ sở có đơn chờ duyệt (CH-20260925-0001 đổi gói) (CU00871 大阪支店)."]),
    V("015", "AW_CONT_002", "仮登録中の帯", "Dải đang đăng ký tạm", "/ops/contracts/CP0000021-202611", ["d_apply", "d_prov", "d_edit"], note=["仮登録の拠点の子契約（CP0000021-202611）。「編集」の代わりに「申請詳細で編集」。", "Hợp đồng con của cơ sở đăng ký tạm (CP0000021-202611). \"申請詳細で編集\" thay cho \"編集\"."]),
    V("016", "AW_CONT_002", "自販機の拠点（配送区分の固定）", "Cơ sở máy bán hàng (cố định loại giao)", "/ops/contracts/CP0000001-202703/edit", ["d_vm"], note=["ESライト（自販機）の拠点は配送区分が ES配送便に固定（選択肢は出ない）。編集画面で注記が出る。", "Cơ sở ESライト（自販機） cố định 配送区分 là ES配送便 (không hiện lựa chọn). Chú thích hiện ở màn sửa."]),
    V("017", "AW_CONT_002", "福利厚生の適用（システム管理だけ）", "Áp dụng phúc lợi (chỉ システム管理)", TABURL(DET, "料金・請求"), ["d_welf"], login="Ad00008", note=["フル権限（Ad00008）でログインした状態。福利厚生の適用は、システム管理（権限付与を編集できる人）にだけ出る。", "Trạng thái đăng nhập bằng フル権限 (Ad00008). 福利厚生の適用 chỉ hiện với システム管理 (người sửa được 権限付与)."]),
    V("018", "AW_CONT_002", "配送ルート設定・回ごとのルート", "Lộ trình giao・lộ trình theo lần", "/ops/contracts/CP0000004-202702", ["d_route", "d_slot"], login="Ad00010", note=["横浜営業所（冷蔵・冷凍の2種）。「この回だけルートを変える」の行は入っていないとき「まだ記録はありません」。", "横浜営業所 (2 loại lạnh / đông). Khi chưa có dòng \"この回だけルートを変える\" thì hiện \"まだ記録はありません\"."]),
    V("019", "AW_CONT_002", "確定・請求済の子契約", "Hợp đồng con đã chốt / đã xuất hóa đơn", "/ops/contracts/CP0000001-202610", ["d_locked", "d_sum"], note=["請求済の子契約（CP0000001-202610）。金額に効く変更はできない（E113）。コードは保存できる。", "Hợp đồng con đã xuất hóa đơn (CP0000001-202610). Không đổi được thứ ảnh hưởng số tiền (E113). Code vẫn lưu được."]),
    V("020", "AW_CONT_002", "見つからない", "Không tìm thấy", "/ops/contracts/CP9999999-202601", ["d_nf"], note=["存在しない子契約ID。", "ID hợp đồng con không tồn tại."]),
    # ---- 編集
    V("021", "AW_CONT_003", "編集 初期（子契約・契約）", "Sửa ban đầu (hợp đồng con・hợp đồng)", "/ops/contracts/CP0000004-202702/edit", EDIT_HEAD + ["e_子契約"] + FK(0) + ["d_scopebtn", "e_契約"] + FK(1), note=["サイクル月（2027-02）の後ろ（2027-03）に生成済みの子契約がある月。", "Tháng chu kỳ (2027-02) có hợp đồng con đã sinh phía sau (2027-03)."]),
    V("022", "AW_CONT_003", "アプリの利用設定・配送・メモ", "Thiết lập app・giao hàng・ghi chú", "/ops/contracts/CP0000004-202702/edit", ["e_アプリ"] + FK(2) + ["e_配送"] + FK(3) + ["e_route_tbl", "e_route_add", "e_route_del", "e_メモ"] + FK(4), note=["各カードの項目。納品不可曜日はチェックを複数選ぶ。", "Các mục của từng thẻ. Ngày không giao được tích chọn nhiều."]),
    V("023", "AW_CONT_003", "タブ「料金・請求」（値引き・負担額）", "Tab \"料金・請求\" (giảm giá・mức chịu)", "/ops/contracts/CP0000004-202702/edit", ["e_料金"] + FK(5) + ["e_adjamt"], setup=TAB("料金・請求"), note=["福利厚生の適用はシステム管理だけに出る。価格調整は種類と金額（10円単位）。", "福利厚生の適用 chỉ hiện với システム管理. 価格調整 gồm loại và số tiền (bội số 10 yên)."]),
    V("024", "AW_CONT_003", "変更の適用範囲（ダイアログ）", "Phạm vi áp dụng thay đổi (dialog)", "/ops/contracts/CP0000004-202702/edit", ["e_scope", "e_scope_only", "e_scope_after", "e_scope_save", "e_scope_cancel"],
      setup="setv(ctl('配送備考△'),'搬入は裏口からお願いします。');await sleep(200);q('.pbtn button.save').click();await sleep(600);", full=False, note=["後ろに生成済みの子契約がある月で配送備考を変えて「保存」を押した状態。「この子契約だけ」が既定。", "Trạng thái đổi 配送備考 ở tháng có hợp đồng con đã sinh phía sau rồi bấm \"保存\". Mặc định \"この子契約だけ\"."]),
    V("025", "AW_CONT_003", "後ろの子契約がない月の保存（確認なし）", "Lưu tháng không có hợp đồng con phía sau (không hỏi)", "/ops/contracts/CP0000004-202703/edit", ["e_saved"],
      setup="setv(ctl('配送備考△'),'搬入は裏口からお願いします。');await sleep(200);q('.pbtn button.save').click();await sleep(600);", wait=200, note=["最新の月（2027-03）で「保存」を押した状態。適用範囲の確認は出さず、トーストに適用範囲の記録を添える。", "Trạng thái bấm \"保存\" ở tháng mới nhất (2027-03). Không hỏi phạm vi áp dụng, toast kèm ghi phạm vi áp dụng."]),
    V("026", "AW_CONT_003", "入力エラー（価格調整の金額）", "Lỗi nhập (số tiền điều chỉnh giá)", "/ops/contracts/CP0000004-202703/edit", ["e_save", "f_adj", "e_adjamt"],
      setup=TAB("料金・請求") + "setsel(ctl('価格調整の適用'),'値上げ');await sleep(300);setv(fld('価格調整の適用').querySelector('input.r'),'15');await sleep(200);q('.pbtn button.save').click();await sleep(500);", note=["価格調整を「値上げ」・金額 15 で「保存」を押した状態。10円単位でないのでエラー（E14 の形）。", "Trạng thái đặt 価格調整 \"値上げ\", số tiền 15 rồi bấm \"保存\". Không phải bội số 10 yên nên báo lỗi (dạng E14)."]),
    V("027", "AW_CONT_003", "オプションの金額の上書き", "Ghi đè số tiền tùy chọn", "/ops/contracts/CP0000004-202703/edit", ["e_opt_amt"], setup=TAB("設備・オプション") + "const el=q('.pane table input.r');if(el){setv(el,'0');await sleep(200);}", note=["タブ「設備・オプション」のオプション・割引の表で金額欄を直した状態（契約ごと・機種参照・ES-QR のオプションだけ入力できる）。", "Trạng thái sửa ô số tiền ở bảng tùy chọn / giảm giá của tab \"設備・オプション\" (chỉ tùy chọn theo hợp đồng / tham chiếu máy / ES-QR nhập được)."]),
    V("028", "AW_CONT_003", "保存できない（確定・請求済・承認待ちのロック）", "Không lưu được (khóa do đã chốt / đã xuất / chờ duyệt)", "/ops/contracts/CP0000002-202702/edit", ["e_契約", "f_plan", "f_course"], note=["承認待ちの申請がある拠点（CP0000002）。申請の対象のプランID・コースは入力できず、項目の下に I104。確定・請求済の子契約の金額に効く変更は E113（コードにない）。", "Cơ sở có đơn chờ duyệt (CP0000002). Plan ID・course của đơn không nhập được, dưới mục có I104. Thay đổi ảnh hưởng số tiền của hợp đồng con đã chốt / đã xuất là E113 (code chưa có)."]),
    V("029", "AW_CONT_003", "編集内容の破棄（確認）", "Hủy nội dung đang sửa (xác nhận)", "/ops/contracts/CP0000004-202703/edit", ["e_discard", "e_disc_cancel", "e_disc_ok"], setup="setv(ctl('配送備考△'),'修正');await sleep(200);q('.pbtn button.cancel').click();await sleep(500);", full=False, note=["配送備考を変えて「キャンセル」を押した状態（Q02）。", "Trạng thái đổi 配送備考 rồi bấm \"キャンセル\" (Q02)."]),
    V("030", "AW_CONT_003", "他のユーザーが編集中・先に更新された", "Người khác đang sửa / đã cập nhật trước", "/ops/contracts/CP0000004-202703", ["e_lock"], setup=LK("child", "CP0000004-202703", "配送備考", "配送備考△"), full=False, note=["伊藤 美咲さんが同じ子契約を編集中（I02：画面の上）。自分の編集中に別の人が先に保存したので、「保存」を押すと E31（内容が更新されています・キャンセル／上書きして保存）を出した状態。", "伊藤 美咲 đang sửa cùng hợp đồng con (I02: đầu màn hình). Trong lúc mình sửa, người khác đã lưu trước nên khi nhấn \"保存\" hiện E31 (nội dung đã được cập nhật・キャンセル / 上書きして保存)."]),
    V("031", "AW_CONT_003", "保存完了（この子契約以降すべて）", "Lưu xong (từ hợp đồng con này trở đi)", "/ops/contracts/CP0000004-202702/edit", ["e_saved"],
      setup="setv(ctl('配送備考△'),'搬入は裏口からお願いします。');await sleep(200);q('.pbtn button.save').click();await sleep(600);btn('保存',q('.ovl .dlg .ft')).click();await sleep(600);", wait=200, note=["適用範囲のダイアログで「この子契約だけ」のまま保存した状態。S01 に「変更履歴の適用範囲：yyyy-mm のみ」を添える。", "Trạng thái lưu với \"この子契約だけ\" mặc định ở dialog phạm vi áp dụng. S01 kèm \"変更履歴の適用範囲：yyyy-mm のみ\"."]),
    # ---- 一括切替（モーダル）
    V("032", "AW_CONT_004", "① 対象の条件（初期）", "① Điều kiện đối tượng (ban đầu)", "/ops/contracts", ["b_modal", "b_title", "b_tabs", "b_note", "b_cond", "b_plan", "b_gen", "b_corp", "b_br", "b_course", "b_temp", "b_city", "b_zip", "b_prefs", "b_to", "b_togen", "b_cycle", "b_cancel", "b_next"],
      setup="await openBulk();", full=False, note=["「価格世代を一括切替」を押した状態。プランが空なので「対象を見る」は押せない。", "Trạng thái sau khi bấm \"価格世代を一括切替\". Gói trống nên không bấm được \"対象を見る\"."]),
    V("033", "AW_CONT_004", "① プランと世代を選んだ", "① Đã chọn gói và thế hệ", "/ops/contracts", ["b_plan", "b_gen", "b_togen", "b_cycle", "b_next"],
      setup="await openBulk();await fillBulk();", full=False, note=["プラン＝ES000004 100プラン、切り替える価格の世代＝改訂第二回目を選んだ状態。いま使っている価格の世代の選択肢に 使っている子契約の件数（18件）が出る。", "Trạng thái chọn gói = ES000004 100プラン, thế hệ giá cần đổi = lần sửa 2. Lựa chọn \"いま使っている価格の世代\" hiện số hợp đồng con đang dùng (18)."]),
    V("034", "AW_CONT_004", "② 対象（比較の列）", "② Đối tượng (cột so sánh)", "/ops/contracts", ["b_rows", "b_all", "b_diff", "b_back2", "b_next2"],
      setup="await openBulk();await fillBulk();btn('対象を見る',M()).click();await sleep(2000);", full=False, note=["対象の子契約（3件）が既定で全部選ばれる。請求済の月は「スキップ（請求済（請求調整））」。", "Hợp đồng con đối tượng (3) được chọn hết theo mặc định. Tháng đã xuất hóa đơn là \"スキップ（請求済（請求調整））\"."]),
    V("035", "AW_CONT_004", "③ 確認（後ろの流れへの影響）", "③ Xác nhận (ảnh hưởng đến luồng phía sau)", "/ops/contracts", ["b_confirm", "b_impact", "b_alerts", "b_notify", "b_retype", "b_back3", "b_run"],
      setup="await openBulk();await fillBulk();btn('対象を見る',M()).click();await sleep(2000);btn('確認へ',M()).click();await sleep(2000);", full=False, note=["「確認へ（3件）」を押した状態。注意（上書き・日付の注意）は、この画面からの価格世代の一括切替では出ない。100件超の打ち直しは親契約が100件を超える条件が要り、見本のデータでは出ない。", "Trạng thái sau khi bấm \"確認へ（3件）\". Lưu ý (ghi đè / ngày) không phát sinh khi đổi thế hệ giá từ màn này. Nhập lại số lượng khi quá 100 cần điều kiện có hơn 100 hợp đồng cha, dữ liệu mẫu không có."]),
    V("036", "AW_CONT_004", "④ 実行と結果", "④ Thực hiện và kết quả", "/ops/contracts", ["b_result", "b_meter", "b_kv", "b_rtable", "b_close", "b_toast"],
      setup="await openBulk();await fillBulk();btn('対象を見る',M()).click();await sleep(2000);btn('確認へ',M()).click();await sleep(2000);btn('一括変更を実行',M()).click();for(let i=0;i<60&&!q('.toast');i++)await sleep(100);await sleep(300);", full=False, wait=100, note=["「一括変更を実行（3件）」を押した状態。変更・スキップ・失敗の件数と結果の表（スキップ・失敗した契約があれば理由つきで出る。見本では契約ごとのスキップ・失敗はなく「スキップ・失敗はありません」）。実行すると元に戻せない（履歴は残る）。", "Trạng thái sau khi bấm \"一括変更を実行（3件）\". Số thay đổi・bỏ qua・lỗi và bảng kết quả (nếu có hợp đồng bị bỏ qua / lỗi thì hiện kèm lý do; ở dữ liệu mẫu không có nên hiện \"スキップ・失敗はありません\"). Thực hiện xong không hoàn tác được (lịch sử vẫn còn)."]),
    V("037", "AW_CONT_004", "履歴タブ（これまでの一括変更）", "Tab lịch sử (các lần đổi hàng loạt trước)", "/ops/contracts", ["b_hist", "b_tabs"], setup="await openBulk();tab('履歴')?.click();[...M().querySelectorAll('.tabs button')].find(b=>b.textContent.includes('履歴')).click();await sleep(500);", full=False, note=["直前の状態で実行したので1件の履歴が出る（実行した番号・日時・種類・件数・結果）。実行前は「まだありません」。", "Sau khi thực hiện hiện 1 lịch sử (số, ngày giờ, loại, số lượng, kết quả). Ở trạng thái đầu của dữ liệu mẫu hiện \"まだありません\"."]),
    # ---- CSV取込
    V("038", "AW_CONT_005", "ステップ1 ファイルを選ぶ", "Bước 1: chọn tệp", "/ops/contracts/import", ["c_head", "c_cancel", "c_step1", "c_steps", "c_hint", "c_pick", "c_cols"] + [k for k in ITEMS if k.startswith("k_")], wait=800, note=["フル権限（CSV取込の権限）だけが開ける。列の定義は画面には出さない（hong 2026/10/05）。", "Chỉ vai trò có quyền CSV取込 mở được. Định nghĩa cột không hiện trên màn hình (hong 2026/10/05)."]),
    V("039", "AW_CONT_005", "ステップ2 確認・登録", "Bước 2: xác nhận・đăng ký", "/ops/contracts/import", ["c_step2", "c_count", "c_errs", "c_errcsv", "c_diff", "c_reselect", "c_go"], setup=CSV_BAD, wait=800, note=["CSV出力のデータの、後ろに子契約のある月の配送備考を変え（更新の見本）、請求済の月の行（E118）と存在しない親契約番号の行を足したファイルを選んだ状態。", "Trạng thái chọn tệp từ dữ liệu CSV出力 với 配送備考 của tháng có hợp đồng con phía sau đã đổi (mẫu cập nhật), thêm dòng của tháng đã xuất hóa đơn (E118) và dòng có số hợp đồng cha không tồn tại."]),
    V("040", "AW_CONT_005", "ファイル全体のエラー", "Lỗi toàn tệp", "/ops/contracts/import", ["c_fileerr"], setup=FILE_ERR, wait=600, note=["UTF-8 でないファイルを選んだ状態（E51）。", "Trạng thái chọn tệp không phải UTF-8 (E51)."]),
]
