# -*- coding: utf-8 -*-
"""
法人Web お届け詳細（CW_DLV）。元は本物の Web（app/corp/deliveries/[id]/page.tsx・app/corp/deliveries/_components/ChangeRequestModal.tsx・
lib/corp/areas/corp-delivery.ts・lib/corp/delivery/{types,logic,fromDomain}.ts・lib/domain/areas/delivery.ts）。
決定の正：docs/決定台帳.md E（2026-10-05 法人Web お届け詳細の細かい点・解約後にできること・名前の使い分け）、決定_v2.3追補_法人ホームカレンダー_20260929（#56〜#62）。版 1.1（2026-10-05）：台帳 E「法人Web 版 1.0 のレビュー（ホーム・お届け詳細）」⑤〜⑨・「納品書のテンプレート」（受付簿 No.153）。版 1.4（2026-10-05）：台帳「法人Web 版 1.1 のレビュー 2回目」（受付簿 No.157）＝開いた元に合わせたサイドメニュー・パンくず・戻る、解約後（参照のみ）、納品書の発行元は会社マスタ、見本データ（変更申請）、不具合修正。
確認メモ：docs/05_画面設計書/確認メモ_法人A_注文・在庫・請求.md 1-2・Q-C1・Q-C2・Q-D1〜D4・宿題 D1〜D6・C1。
"""

TITLE = ["お届け詳細（CW_DLV）", "Chi tiết đơn giao hàng (CW_DLV)"]
SHEET = ["お届け詳細", "Chi tiết giao hàng"]
BASENAME = "画面設計書_CW_DLV_お届け詳細"
IMG_PREFIX = "CW_DLV"
OUT_DIR = "CW_DLV_お届け詳細"
CODE_NOTE = ["Screen Code は台帳 E 2026-10-05 の決まり：CW_<機能略>_<3桁>", "Screen Code theo 台帳 E 2026-10-05: CW_<機能略>_<3 chữ số>"]
SITE = "corp"
SYSTEM = {"ja": "法人Web", "vi": "Web pháp nhân (法人Web)"}
AUTHOR = "Claude／確認：hong"
CREATED = "2026-10-05"
DEMO_FILE = "http://localhost:3000"
LOGIN = {"site": "corp", "loginId": "CU00001"}

DECISIONS = [
    {"date": "2026-10-05", "target": "CW_DLV_001 No.6.1・No.10.5・No.22.2",
     "q": ["画面の文言で「ESキッチン」と「ES STATION」のどちらを使うか", "Trong câu chữ màn hình dùng \"ESキッチン\" hay \"ES STATION\""],
     "a": ["「ESキッチン」＝お客様（運営会社）の名前、「ES STATION」＝システムの名前。運営へ連絡する文は「ESキッチンへお問い合わせください」", "\"ESキッチン\" = tên công ty vận hành, \"ES STATION\" = tên hệ thống. Câu liên hệ vận hành: \"ESキッチンへお問い合わせください\""],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-C1）"},
    {"date": "2026-10-05", "target": "CW_DLV_001 No.1.6",
     "q": ["解約後（参照のみ）のアカウントはお届け日の変更を申請できるか", "Tài khoản sau giải ước (chỉ xem) có xin đổi ngày giao được không"],
     "a": ["できない。「お届け日の変更を申請」のボタンを出さない", "Không. Không hiện nút \"お届け日の変更を申請\""],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-C2）"},
    {"date": "2026-10-05", "target": "CW_DLV_001 No.14.2",
     "q": ["送り状の追跡ページのリンクに運送会社名（ヤマト運輸）を書いてよいか（決定 #56「配送会社名の欄は作らない」）", "Link trang theo dõi có được ghi tên hãng vận chuyển (ヤマト運輸) không (quyết định #56: không làm cột tên hãng)"],
     "a": ["書いてよい（リンクの文字「{運送会社}の追跡ページ」）。配送会社の欄は作らない", "Được (chữ link \"{運送会社}の追跡ページ\"). Không làm cột riêng cho hãng vận chuyển"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-D1）"},
    {"date": "2026-10-05", "target": "CW_DLV_001 No.8.1",
     "q": ["法人は申請中の変更申請を取り下げられるか（決定 #59 では【案】）", "Pháp nhân có rút lại yêu cầu đổi ngày đang 申請中 được không (quyết định #59 còn là phương án)"],
     "a": ["取り下げられる。申請中（ご提案・処理の前）だけ。ボタンは申請の履歴の行。拠点アカウントは法人アカウントの申請を取り下げられない（H2）", "Được. Chỉ khi 申請中 (trước đề xuất / xử lý). Nút ở dòng lịch sử yêu cầu. Tài khoản 拠点 không rút yêu cầu do tài khoản pháp nhân tạo (H2)"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-D2）"},
    {"date": "2026-10-05", "target": "CW_DLV_001 No.17",
     "q": ["お届け詳細に「納品書（PDF）」のボタンを置くか", "Có đặt nút \"納品書（PDF）\" ở chi tiết đơn giao không"],
     "a": ["置かない。納品書は注文履歴の行（拠点×対象月）だけ → 2026-10-05 版1.0レビューで置き換え（便ごとにお届け詳細からも出せる。下の行）", "Không. 納品書 chỉ ở dòng 注文履歴 (拠点 × tháng) → bị thay thế ở review 版1.0 2026-10-05 (xuất được từng chuyến ở chi tiết; xem dòng dưới)"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-D3）"},
    {"date": "2026-10-05", "target": "CW_DLV_001 No.22.4",
     "q": ["変更申請で選べない日の決め方（コードは土日＋今のお届け日。注記は「祝日・月曜」）", "Cách xác định ngày không chọn được trong yêu cầu đổi ngày (code: T7, CN + ngày giao hiện tại; chú thích ghi \"祝日・月曜\")"],
     "a": ["全社の休日マスタ＋拠点のお届けできない曜日（配送ルート設定）＋今のお届け日。「月曜」を決め打ちしない", "Master ngày nghỉ toàn công ty + thứ không giao được của 拠点 (cài đặt tuyến giao) + ngày giao hiện tại. Không cố định \"thứ Hai\""],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-D4）"},
    # ---- 版 1.0 のレビュー（hong 回答 2026-10-05・台帳 E「法人Web 版 1.0 のレビュー（ホーム・お届け詳細）」「納品書のテンプレート」）
    {"date": "2026-10-05", "target": "CW_DLV_001 No.2.2・No.2.3",
     "q": ["お届けの予定に「受取時間帯」「到着予定」を出すか", "Có hiện 「受取時間帯」 và 「到着予定」 ở lịch giao không"],
     "a": ["出さない（時間の指定は受けられないため）。ドライバーアプリの到着予定の報告も不要", "Không hiện (vì không nhận chỉ định giờ). Tài xế cũng không cần báo giờ đến dự kiến"],
     "src": "hong 回答 2026-10-05 版1.0レビュー"},
    {"date": "2026-10-05", "target": "CW_DLV_001 No.5",
     "q": ["送り状の枠の見出し（コードは「送り状」）", "Tiêu đề khung phiếu gửi (code: 「送り状」)"],
     "a": ["「送り状番号」", "「送り状番号」 (Số phiếu gửi)"],
     "src": "hong 回答 2026-10-05 版1.0レビュー"},
    {"date": "2026-10-05", "target": "CW_DLV_001 No.8・No.8.2〜8.8",
     "q": ["申請中（申請の履歴）の枠の形（コードは番号・日・状態の1行）", "Dạng khung yêu cầu đang xử lý / lịch sử (code: 1 dòng số, ngày, trạng thái)"],
     "a": ["表で全項目：申請番号・申請日・第一希望・第二希望・理由・状態・ご返事の期限", "Bảng đủ cột: 申請番号, 申請日, 第一希望, 第二希望, 理由, 状態, ご返事の期限"],
     "src": "hong 回答 2026-10-05 版1.0レビュー"},
    {"date": "2026-10-05", "target": "CW_DLV_001 No.22〜22.14・No.23",
     "q": ["変更申請のモーダルの形（コードは同じ半分の14日のボタン＋理由を1画面）", "Dạng modal xin đổi ngày (code: 14 nút ngày của cùng nửa + lý do trên 1 màn)"],
     "a": ["月のカレンダーから日を押す2ステップ：①ご利用月（サイクル）のカレンダーで日を選ぶ（選べる日を目立たせ、選べない日は灰色。1つ目＝第一希望、2つ目＝第二希望。または「希望日なし」） ②理由（500文字）と確認。選べる範囲（同じ半分・休日・曜日）は #57・Q-D4 のまま", "2 bước chọn ngày trên lịch tháng: ① lịch của tháng sử dụng (chu kỳ), ngày chọn được nổi bật, ngày không chọn được màu xám (bấm 1 = NV1, bấm 2 = NV2; hoặc 「希望日なし」) ② lý do (500 ký tự) và xác nhận. Phạm vi chọn (cùng nửa, ngày nghỉ, thứ) giữ theo #57, Q-D4"],
     "src": "hong 回答 2026-10-05 版1.0レビュー"},
    {"date": "2026-10-05", "target": "CW_DLV_001 No.1.6・No.17",
     "q": ["お届け詳細に「納品書（PDF）」のボタンを置くか（Q-D3 では置かない）", "Có đặt nút 「納品書（PDF）」 ở chi tiết không (Q-D3: không)"],
     "a": ["置く（Q-D3・B-D3 を置き換え）。確定（出荷待）以降の便ごとに出せる。資材便は出さない。注文履歴の納品書は月・拠点ごと", "Đặt (thay thế Q-D3, B-D3). Xuất được từng chuyến từ khi chốt (出荷待) trở đi. Chuyến vật tư không có. 納品書 ở 注文履歴 là theo tháng, 拠点"],
     "src": "hong 回答 2026-10-05 版1.0レビュー"},
    {"date": "2026-10-05", "target": "CW_DLV_001 No.25〜25.9",
     "q": ["納品書（PDF）の中身（要件は「現行テンプレートを踏襲」だけで定義なし）", "Nội dung 納品書 (PDF) (yêu cầu chỉ ghi \"theo mẫu hiện hành\", chưa định nghĩa)"],
     "a": ["Claude が決める：A4 縦。見出し「納品書」・発行日・納品書番号（お届け番号）／宛先／発行元／お届け日・温度帯・お届け方法／明細（No・商品名・ご注文数・お届け数・備考）／数量の合計／注記／ページ番号。金額は載せない。資材は載せない。現行の納品書との差はお客様（運営）に確認（OPEN）", "Claude quyết: A4 dọc. Tiêu đề 「納品書」, ngày phát hành, số phiếu (số đơn giao) / người nhận / nơi phát hành / ngày giao, 温度帯, cách giao / chi tiết (No, tên sản phẩm, số đặt, số giao, ghi chú) / tổng số lượng / chú thích / số trang. Không ghi tiền. Không ghi vật tư. Khác biệt với phiếu hiện hành: hỏi khách hàng (vận hành) (OPEN)"],
     "src": "hong「Claude が決める」（チャット 2026-10-05）・台帳 E「納品書のテンプレート」"},
    # ---- 版 1.4：法人Web 版 1.1 のレビュー 2回目（hong 回答 2026-10-05・台帳・受付簿 No.157）
    {"date": "2026-10-05", "target": "CW_DLV_001 No.1.1・No.1.5・No.24.1",
     "q": ["お届け詳細のサイドメニュー・パンくず・戻るボタンは、どこから開いても「ホーム」でよいか", "Menu bên, breadcrumb, nút quay lại của chi tiết đơn giao: mở từ đâu cũng là \"ホーム\" được không"],
     "a": ["開いた元の項目を光らせる。元は ?from=（home／requests／news）で渡す。サイドメニュー・パンくず・戻るボタン（「カレンダーへ戻る」「申請の一覧へ戻る」「お知らせ一覧へ戻る」）は元に従う。なし・不明はホーム", "Sáng đúng mục nơi mở ra. Nơi mở truyền bằng ?from= (home／requests／news). Menu bên, breadcrumb, nút quay lại (\"カレンダーへ戻る\" \"申請の一覧へ戻る\" \"お知らせ一覧へ戻る\") theo nơi mở. Không có / không rõ thì là trang chủ"],
     "src": "hong 回答 2026-10-05（台帳「法人Web 版 1.1 のレビュー 2回目」・受付簿 No.157）"},
    {"date": "2026-10-05", "target": "CW_DLV_001 No.1.6・No.1.7・No.6.2・No.8.1・No.10.6〜10.8・No.11.2",
     "q": ["解約後（参照のみ）のお届け詳細でできること", "Chi tiết đơn giao sau giải ước (chỉ xem) làm được gì"],
     "a": ["見るだけ。取り下げる・受ける・お断りする・お届け日の変更を申請は出さない。黄色い参照のみの帯を出す。サーバーも断る（E345）。納品書（PDF）は出せる", "Chỉ xem. Không hiện 取り下げる, 受ける, お断りする, お届け日の変更を申請. Hiện dải vàng \"chỉ xem\". Server cũng từ chối (E345). Vẫn xuất được 納品書 (PDF)"],
     "src": "hong 回答 2026-10-05（台帳「法人Web 版 1.1 のレビュー 2回目」・受付簿 No.157）"},
    {"date": "2026-10-05", "target": "CW_DLV_001 No.25.3",
     "q": ["納品書の発行元（会社名・住所・電話）はどこの値か", "Tên công ty, địa chỉ, điện thoại nơi phát hành 納品書 lấy từ đâu"],
     "a": ["会社マスタの値（運営の会社情報＝共通データの ESキッチンの会社。旧・月ごとの納品書と同じ元）。マスタにないときだけ見本の値", "Giá trị trong master công ty (thông tin công ty vận hành = công ty ESキッチン trong dữ liệu chung; cùng nguồn với 納品書 theo tháng cũ). Chỉ khi master không có mới dùng giá trị mẫu"],
     "src": "hong 回答 2026-10-05（台帳「法人Web 版 1.1 のレビュー 2回目」・受付簿 No.157）"},
    {"date": "2026-10-05", "target": "CW_DLV_001 No.10〜11.2・No.23.1",
     "q": ["見本データで作れない状態を「デモでは作れない」（demo_ok）で済ませてよいか", "Trạng thái dữ liệu mẫu không tạo được có được ghi \"demo_ok\" cho xong không"],
     "a": ["済ませない。見本データを作る（共通の見本の変更申請：DD-20261005-0095＝別の日のご提案（大阪支店 11/10）、DD-20261005-0096＝申請中（12/08）、DD-20260930-0001＝否認（12/22））。画面の入力エラーなどは撮影の設定（setup）で出す", "Không. Tạo dữ liệu mẫu (yêu cầu đổi ngày mẫu chung: DD-20261005-0095 = đề xuất ngày khác (大阪支店 11/10), DD-20261005-0096 = đang xử lý (12/08), DD-20260930-0001 = 否認 (12/22)). Lỗi nhập trên màn hình… thì dùng thiết lập chụp (setup)"],
     "src": "hong 回答 2026-10-05（「demo_ok で逃げず、見本データを作る」・受付簿 No.157）"},
]

CHANGES = [
    {"ver": "1.4", "date": "2026-10-05", "no": "1.8", "type": "追加",
     "reason": ["hong 回答 2026-10-05 版1.1 レビュー2回目（受付簿 No.157）：開いた元の項目を光らせる", "hong trả lời 2026-10-05 review 版1.1 lần 2 (受付簿 No.157): sáng đúng mục nơi mở ra"],
     "impact": ["サイドメニューの光らせ方の定義を足す。状態 020（申請の一覧から開いた）を追加", "Thêm định nghĩa cách sáng menu bên. Thêm trạng thái 020 (mở từ danh sách yêu cầu)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["1.1", "1.5", "24.1"], "type": "変更",
     "before": ["お届け詳細を開くと、サイドメニューは常に「ホーム」。パンくずは「ホーム ／ お届け詳細」、戻るボタンは「カレンダーへ戻る」だけ", "Mở chi tiết đơn giao thì menu bên luôn là \"ホーム\". Breadcrumb \"ホーム ／ お届け詳細\", nút quay lại chỉ \"カレンダーへ戻る\""],
     "after": ["開いた元（?from=）の項目を光らせる。ホーム：「ホーム ／ お届け詳細」・「カレンダーへ戻る」／申請の一覧：「申請 ／ お届け日の変更申請 ／ お届け詳細」・「申請の一覧へ戻る」／お知らせ一覧：「ホーム ／ お知らせ一覧 ／ お届け詳細」・「お知らせ一覧へ戻る」。なし・不明はホーム", "Sáng mục nơi mở ra (?from=). Trang chủ: \"ホーム ／ お届け詳細\", \"カレンダーへ戻る\" / danh sách yêu cầu: \"申請 ／ お届け日の変更申請 ／ お届け詳細\", \"申請の一覧へ戻る\" / danh sách thông báo: \"ホーム ／ お知らせ一覧 ／ お届け詳細\", \"お知らせ一覧へ戻る\". Không có / không rõ thì là trang chủ"],
     "reason": ["hong 回答 2026-10-05 版1.1 レビュー2回目（受付簿 No.157）：開いた元の項目を光らせる", "hong trả lời 2026-10-05 review 版1.1 lần 2 (受付簿 No.157): sáng đúng mục nơi mở ra"],
     "impact": ["お届け詳細を開くリンク（ホームのマス・一覧・「ご確認ください」の行、申請の一覧）に ?from=home／requests を付ける。サイドメニュー（lib/corp/menu.ts の corpActive）・パンくず・戻るボタンを元に合わせる。「見つからない」の戻るリンクも同じ", "Gắn ?from=home／requests vào link mở chi tiết (ô, danh sách, dòng 「ご確認ください」 ở trang chủ; danh sách yêu cầu). Menu bên (corpActive trong lib/corp/menu.ts), breadcrumb, nút quay lại theo nơi mở. Link quay lại ở màn \"không tìm thấy\" cũng vậy"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["1.6", "6.1", "8.1", "10.6", "10.7", "11.2"], "type": "変更",
     "before": ["解約後（参照のみ）：申請ボタンだけ出さない。取り下げる・受ける・お断りするは画面の判断だけで、サーバーは断らない", "Sau giải ước (chỉ xem): chỉ ẩn nút xin đổi. 取り下げる, 受ける, お断りする chỉ do màn hình quyết định, server không từ chối"],
     "after": ["解約後（参照のみ）：取り下げる・受ける・お断りする・お届け日の変更を申請をすべて出さない。サーバーも、申請・取り下げ・ご提案へのご返事を断る（E345）", "Sau giải ước (chỉ xem): ẩn tất cả 取り下げる, 受ける, お断りする, お届け日の変更を申請. Server cũng từ chối xin đổi / rút lại / trả lời đề xuất (E345)"],
     "reason": ["hong 回答 2026-10-05 版1.1 レビュー2回目（受付簿 No.157）：解約後は見るだけ。サーバーも断る", "hong trả lời 2026-10-05 review 版1.1 lần 2 (受付簿 No.157): sau giải ước chỉ xem. Server cũng từ chối"],
     "impact": ["画面から ro（参照のみ）を渡し、corp-delivery の requestDateChange・withdrawDateChange・acceptProposal・declineProposal が ro のとき 403（E345）を返す（請求書の ro と同じ作り）", "Màn hình truyền ro (chỉ xem), requestDateChange・withdrawDateChange・acceptProposal・declineProposal của corp-delivery trả 403 (E345) khi ro (cùng cách làm với ro của 請求書)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["1.7", "6.2", "10.8"], "type": "追加",
     "reason": ["hong 回答 2026-10-05 版1.1 レビュー2回目（受付簿 No.157）：解約後（参照のみ）のお届け詳細に黄色い参照のみの帯を出す", "hong trả lời 2026-10-05 review 版1.1 lần 2 (受付簿 No.157): chi tiết đơn giao sau giải ước (chỉ xem) hiện dải vàng \"chỉ xem\""],
     "impact": ["見出しの下に参照のみの帯（roTitle）を出す。解約後の申請の案内（6.2）・ご返事の案内（10.8）を足す。状態 018・019 を追加", "Hiện dải \"chỉ xem\" (roTitle) dưới tiêu đề. Thêm hướng dẫn xin đổi (6.2) và hướng dẫn trả lời (10.8) sau giải ước. Thêm trạng thái 018, 019"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "25.3", "type": "変更",
     "before": ["発行元の会社名・住所・電話はコードに固定の見本（「ESキッチン」「東京都（本社）」「03-0000-0001」）", "Tên công ty, địa chỉ, điện thoại nơi phát hành là giá trị mẫu cố định trong code (\"ESキッチン\" \"東京都（本社）\" \"03-0000-0001\")"],
     "after": ["会社マスタの値（共通データのESキッチンの会社の名前・住所・電話。旧・月ごとの納品書と同じ元）。マスタにないときだけ見本の値", "Giá trị trong master công ty (tên, địa chỉ, điện thoại của công ty ESキッチン trong dữ liệu chung; cùng nguồn với 納品書 theo tháng cũ). Chỉ khi master không có mới dùng giá trị mẫu"],
     "reason": ["hong 回答 2026-10-05 版1.1 レビュー2回目（受付簿 No.157）：発行元は会社マスタの値", "hong trả lời 2026-10-05 review 版1.1 lần 2 (受付簿 No.157): nơi phát hành lấy từ master công ty"],
     "impact": ["お届け詳細の問い合わせ（delivery）が issuer を返し、納品書（PDF）に使う", "Truy vấn chi tiết đơn giao (delivery) trả về issuer và dùng cho 納品書 (PDF)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "4.1", "type": "変更",
     "before": ["お届け完了の前は常に「まだお届けしていません」＋「お届け日（{MM-DD}）に、担当者の報告で表示されます。」", "Trước khi giao xong luôn \"まだお届けしていません\" + \"お届け日（{MM-DD}）に、担当者の報告で表示されます。\""],
     "after": ["状態で変える。お届け中止：「お届けしません」＋「このお届けは中止になりました。ご不明な点はESキッチンへお問い合わせください。」／確認中：「お届けの状況を確認しています」／再配送準備中：ESキッチンが再配送の日を調整している旨。ほかは今までどおり", "Đổi theo trạng thái. お届け中止: \"お届けしません\" + \"このお届けは中止になりました。…\" / 確認中: \"お届けの状況を確認しています\" / 再配送準備中: ES Kitchen đang điều chỉnh ngày giao lại. Còn lại như cũ"],
     "reason": ["QA レビュー（受付簿 No.157）：お届け中止のお届けに「お届け日に表示されます」と出ていた", "Review QA (受付簿 No.157): đơn お届け中止 mà vẫn hiện \"sẽ hiển thị vào ngày giao\""],
     "impact": ["お届け詳細の問い合わせ（delivery）が状態ごとの見出し・説明（noResultTitle・noResultText）を返す", "Truy vấn delivery trả về tiêu đề / giải thích theo trạng thái (noResultTitle, noResultText)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "19", "type": "変更",
     "before": ["関連するお届けの状態をそのまま出す（取消した便は「取消」と出る）", "Hiện nguyên trạng thái đơn liên quan (đơn đã hủy hiện \"取消\")"],
     "after": ["取消した便は出さない。取消した便のお届け詳細を開いても「見つかりません」（I204）", "Không hiện đơn đã hủy. Mở chi tiết của đơn đã hủy cũng ra \"見つかりません\" (I204)"],
     "reason": ["QA レビュー（受付簿 No.157）：運営の状態名「取消」を法人にそのまま見せない", "Review QA (受付簿 No.157): không cho pháp nhân thấy nguyên tên trạng thái nội bộ \"取消\""],
     "impact": ["関連するお届けから取消の便を除き、お届け詳細の問い合わせも取消の便は null にする", "Loại đơn hủy khỏi đơn liên quan, truy vấn chi tiết trả null cho đơn hủy"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["22.4", "22.7"], "type": "変更",
     "before": ["理由は500文字を超えると入力できなくなる（切り捨て）ので E04 が出ない。日を選べる範囲がないとき、カレンダーが空のまま", "Lý do quá 500 ký tự thì không gõ thêm được (cắt bỏ) nên E04 không hiện. Khi không có phạm vi chọn ngày, lịch để trống"],
     "after": ["入力は止めず、500文字を超えて「申請する」を押すと E04。日を選べる範囲がないときは「日を選べる範囲がありません。」の案内を出し、「希望日なし」で申請できる", "Không chặn khi gõ, quá 500 ký tự rồi bấm 「申請する」 thì hiện E04. Khi không có phạm vi chọn ngày thì hiện \"日を選べる範囲がありません。\" và vẫn xin được bằng 「希望日なし」"],
     "reason": ["QA レビュー（受付簿 No.157）：切り捨てで E04 が出ない／空のカレンダー", "Review QA (受付簿 No.157): bị cắt nên không có E04 / lịch trống"],
     "impact": ["理由の textarea の maxLength を外す。モーダルで cal が空のときの案内を足す", "Bỏ maxLength của textarea lý do. Thêm hướng dẫn khi cal rỗng trong modal"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["24", "8.1", "10.7", "17"], "type": "変更",
     "before": ["読み込めなかった（通信の失敗）ときも「お届けが見つかりません」。URL の % が壊れていると画面が落ちる。取り下げる・お断りの二重実行の防ぎは取り下げるの確認だけ", "Lỗi tải (mạng) cũng ra \"お届けが見つかりません\". URL có % hỏng thì màn hình lỗi. Chống chạy 2 lần chỉ có ở nút xác nhận 取り下げる"],
     "after": ["読み込めなかったときは E346（「再読み込み」つき）で、I204 とは別。壊れた URL でも落ちない。取り下げる・お断りする・受けるは実行中は重ねて押せない（納品書（PDF）も実行中は押せない）", "Lỗi tải thì hiện E346 (có 「再読み込み」), tách khỏi I204. URL hỏng cũng không lỗi. 取り下げる・お断りする・受ける không bấm chồng khi đang chạy (納品書 (PDF) cũng vậy)"],
     "reason": ["QA レビュー（受付簿 No.157）", "Review QA (受付簿 No.157)"],
     "impact": ["お届け詳細で error と null を見分け、decodeURIComponent を try で囲む。busy で二重実行を防ぐ", "Phân biệt error và null ở chi tiết, bọc decodeURIComponent trong try. Chống chạy 2 lần bằng busy"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["10", "10.1", "10.2", "10.3", "10.4", "10.5", "10.6", "10.7", "11", "11.1", "11.2"], "type": "変更",
     "before": ["「見本データでは作れない状態（demo_ok）」として項目だけ書いていた（撮影は通常の画面）", "Chỉ ghi mục dưới dạng \"trạng thái dữ liệu mẫu không tạo được (demo_ok)\" (ảnh là màn thường)"],
     "after": ["見本データの変更申請 DD-20261005-0095（大阪支店 11/10・ESキッチンが 11/13 を提案）で実際の画面を撮る（状態 004・005）。申請中の見本は DD-20261005-0096（大阪支店 12/08）に移す（状態 002）", "Chụp màn thật với yêu cầu mẫu DD-20261005-0095 (大阪支店 11/10, ES Kitchen đề xuất 11/13) (trạng thái 004, 005). Yêu cầu mẫu đang xử lý chuyển sang DD-20261005-0096 (大阪支店 12/08) (trạng thái 002)"],
     "reason": ["hong 回答 2026-10-05（受付簿 No.157）：demo_ok で逃げず、見本データを作る", "hong trả lời 2026-10-05 (受付簿 No.157): không dùng demo_ok để cho qua, hãy tạo dữ liệu mẫu"],
     "impact": ["共通の見本データ（lib/domain/seed/delivery.ts）の DD-20261005-0095 を「別の日のご提案」にし、DD-20261005-0096（申請中）・DD-20260930-0001（否認）を足した。状態 002・004・005 を撮り直す", "Đổi DD-20261005-0095 trong dữ liệu mẫu chung (lib/domain/seed/delivery.ts) thành \"別の日のご提案\", thêm DD-20261005-0096 (đang xử lý), DD-20260930-0001 (否認). Chụp lại trạng thái 002, 004, 005"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "23.1", "type": "変更",
     "before": ["状態 013（ステップ①の日のエラー）の項目として書き、「同時に写らない」（demo_ok）", "Ghi như mục của trạng thái 013 (lỗi ngày ở bước ①) và \"không chụp cùng lúc\" (demo_ok)"],
     "after": ["新しい状態 017（ステップ②で理由を空のまま「申請する」を押した）に移し、実際の画面を撮る", "Chuyển sang trạng thái mới 017 (bước ②, lý do trống, bấm 「申請する」) và chụp màn thật"],
     "reason": ["hong 回答 2026-10-05（受付簿 No.157）：demo_ok で逃げない", "hong trả lời 2026-10-05 (受付簿 No.157): không dùng demo_ok"],
     "impact": ["撮影の設定（setup）で、日を2つ選んで「次へ」→ 理由を空のまま「申請する」を押す", "Thiết lập chụp (setup): chọn 2 ngày, 「次へ」, rồi bấm 「申請する」 khi lý do trống"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["22.3", "22.4", "25.8"], "type": "変更",
     "before": ["demo_ok：希望日なしの申請が共通データで受け付けられない／拠点のお届けできない曜日を見ていない／ページ番号と見出しの繰り返しはブラウザの印刷でできない", "demo_ok: yêu cầu không có nguyện vọng chưa nhận ở dữ liệu chung / chưa xét thứ không giao của 拠点 / số trang và lặp tiêu đề không làm được bằng in của trình duyệt"],
     "after": ["いずれも解消済み（共通データは希望日なしを受け付ける。拠点のお届けできない曜日は配送ルート設定（sites の見本）から見る。納品書は PDF を直接出し、ページ番号「n / 総ページ」と表の見出しの行の繰り返しをする。2ページ目に見出し（25.1）を小さく繰り返すことはしない）。demo_ok をなくした", "Đều đã giải quyết (dữ liệu chung nhận yêu cầu không nguyện vọng; thứ không giao của 拠点 lấy từ cài đặt tuyến giao (dữ liệu mẫu sites); 納品書 xuất PDF trực tiếp, có số trang \"n / tổng\" và lặp dòng tiêu đề của bảng. Không lặp tiêu đề 25.1 cỡ nhỏ ở trang 2). Đã bỏ demo_ok"],
     "reason": ["hong 回答 2026-10-05（受付簿 No.157）：demo_ok で逃げない。コードは今の作りに合っていた", "hong trả lời 2026-10-05 (受付簿 No.157): không dùng demo_ok. Code đã khớp cách làm hiện tại"],
     "impact": ["項目定義の注記だけを直す（コードの変更なし）", "Chỉ sửa ghi chú trong định nghĩa mục (không đổi code)"]},
    {"ver": "1.3", "date": "2026-10-05", "no": "17", "type": "変更",
     "before": ["納品書（PDF）を新しいタブで開き、ブラウザの印刷で PDF に保存する。注文履歴にも月・拠点ごとの納品書がある", "Mở 納品書 (PDF) ở tab mới, lưu PDF bằng chức năng in của trình duyệt. 注文履歴 cũng có 納品書 theo tháng·chi nhánh"],
     "after": ["PDF ファイルとして直接ダウンロード（印刷画面を経由しない）。明細は行の切れ目で改ページし見出しの行を繰り返す。ページ番号を出す。納品書は注文履歴からは出さない（この画面だけ）", "Tải trực tiếp thành file PDF (không qua màn hình in). Ngắt trang ở ranh giới dòng, lặp dòng tiêu đề, có số trang. 納品書 không xuất từ 注文履歴 (chỉ ở màn này)"],
     "reason": ["hong 回答 2026-10-05（版 1.1 のレビュー・受付簿 No.156）", "hong trả lời 2026-10-05 (review bản 1.1, 受付簿 No.156)"],
     "impact": ["ボタンは PDF を保存する処理に変える。納品書の確認用の別ページ（/corp/deliveries/<ID>/note）は廃止", "Nút đổi thành xử lý lưu PDF. Bỏ trang xem riêng 納品書 (/corp/deliveries/<ID>/note)"]},
    {"ver": "1.3", "date": "2026-10-05", "no": "8.7", "type": "変更",
     "before": ["提案中（別の日のご提案）・お断り済の申請は、上の枠だけで表には出ない（ほかに申請がないと「申請はありません」）", "Yêu cầu đang được đề xuất (別の日のご提案) / đã từ chối chỉ nằm ở khung phía trên, không có trong bảng (nếu không có yêu cầu khác thì hiện \"申請はありません\")"],
     "after": ["申請の表にも全件を出す（提案中・お断り済を含む）。状態は 申請中／別の日のご提案／承認／否認／お断り済／取り下げ", "Bảng yêu cầu hiển thị đủ mọi yêu cầu (gồm đang đề xuất / đã từ chối). Trạng thái: 申請中／別の日のご提案／承認／否認／お断り済／取り下げ"],
     "reason": ["台帳 267⑦「申請中の枠は表で全項目」。上の枠と表で食い違わないようにする", "台帳 267⑦ \"khung yêu cầu hiển thị đầy đủ trong bảng\". Tránh lệch giữa khung trên và bảng"],
     "impact": ["表の行に提案中・お断り済の申請を含める（取り下げるは申請中の行だけ）", "Thêm yêu cầu đang đề xuất / đã từ chối vào các dòng của bảng (「取り下げる」 chỉ ở dòng 申請中)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["2.2", "2.3"], "type": "削除",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：受取時間帯・到着予定は出さない（お届けの時間の指定は受けられないため）", "hong trả lời 2026-10-05 review 版1.0: không hiện 受取時間帯, 到着予定 (vì không nhận chỉ định giờ giao)"],
     "impact": ["お届けの予定から2つの欄を外す。ドライバーアプリの到着予定の報告も不要（受付簿 No.153）", "Bỏ 2 ô khỏi khung lịch giao. Tài xế cũng không cần báo giờ đến dự kiến (受付簿 No.153)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "5", "type": "変更",
     "before": ["見出し「送り状」", "Tiêu đề 「送り状」"], "after": ["見出し「送り状番号」", "Tiêu đề 「送り状番号」"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：見出しは「送り状番号」", "hong trả lời 2026-10-05 review 版1.0: tiêu đề là 「送り状番号」"],
     "impact": ["枠の見出しの文字を変える", "Đổi chữ tiêu đề khung"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "8", "type": "変更",
     "before": ["1行：申請番号・「{今のお届け日} → {第一希望}・{第二希望}」・状態のバッジ", "1 dòng: số yêu cầu, \"{ngày hiện tại} → {NV1}・{NV2}\", badge trạng thái"],
     "after": ["表：申請番号・申請日・第一希望・第二希望・理由・状態・ご返事の期限（No.8.2〜8.8）", "Bảng: 申請番号, 申請日, 第一希望, 第二希望, 理由, 状態, ご返事の期限 (No.8.2〜8.8)"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：申請中の枠は表で全項目", "hong trả lời 2026-10-05 review 版1.0: khung yêu cầu là bảng đủ cột"],
     "impact": ["申請の履歴を表（7列）にし、申請日・理由・ご返事の期限を出す。「取り下げる」（8.1）は表の行の右端", "Đổi lịch sử yêu cầu thành bảng (7 cột), thêm 申請日, 理由, ご返事の期限. Nút 「取り下げる」 (8.1) ở cuối dòng của bảng"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["8.2", "8.3", "8.4", "8.5", "8.6", "8.7", "8.8"], "type": "追加",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：申請の履歴の表の列", "hong trả lời 2026-10-05 review 版1.0: các cột của bảng lịch sử yêu cầu"],
     "impact": ["表の列を7つ作る（申請日・理由・ご返事の期限は今の画面にない）", "Tạo 7 cột (申請日, 理由, ご返事の期限 chưa có trên màn hình hiện tại)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["1.6", "17"], "type": "変更",
     "before": ["「納品書（PDF）」のボタンは置かない（Q-D3）", "Không đặt nút 「納品書（PDF）」 (Q-D3)"],
     "after": ["確定（出荷待）以降の便（資材便を除く）に「納品書（PDF）」のボタンを置く。中身は No.25", "Đặt nút 「納品書（PDF）」 cho chuyến từ 出荷待 trở đi (trừ chuyến vật tư). Nội dung xem No.25"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：納品書（PDF）は便ごとにお届け詳細からも出せる（Q-D3・B-D3 を置き換え）", "hong trả lời 2026-10-05 review 版1.0: 納品書 (PDF) xuất được từng chuyến từ chi tiết (thay thế Q-D3, B-D3)"],
     "impact": ["見出しの右に「納品書（PDF）」ボタン（出荷待以降・資材便は出さない）。便ごとの PDF（A4・No.25 の形）を作る処理を足す。出せたら S207、失敗は E306", "Thêm nút 「納品書（PDF）」 bên phải tiêu đề (từ 出荷待, chuyến vật tư không có). Thêm xử lý tạo PDF từng chuyến (A4, dạng No.25). Xong: S207, lỗi: E306"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["25", "25.1", "25.2", "25.3", "25.4", "25.5", "25.5.1", "25.5.2", "25.5.3", "25.5.4", "25.5.5", "25.6", "25.7", "25.8", "25.9"], "type": "追加",
     "reason": ["台帳 E 2026-10-05「納品書のテンプレート」（hong「Claude が決める」）：納品書（PDF）の中身を決めた。現行の納品書との差はお客様（運営）に確認（OPEN）", "台帳 E 2026-10-05 「納品書のテンプレート」 (hong: \"Claude quyết\"): đã định nội dung 納品書 (PDF). Khác biệt với phiếu hiện hành: hỏi khách hàng (vận hành) (OPEN)"],
     "impact": ["便ごとの納品書 PDF のテンプレートを作る（A4 縦・金額なし・明細が収まらなければ改ページ）。注文履歴の月・拠点ごとの納品書も同じ便の表を縦に並べる", "Tạo mẫu PDF 納品書 từng chuyến (A4 dọc, không tiền, chi tiết không vừa thì sang trang). 納品書 theo tháng, 拠点 ở 注文履歴 cũng xếp dọc các bảng chuyến theo mẫu này"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["22", "22.3", "22.4", "22.5", "22.7", "22.8", "22.9", "22.10"], "type": "変更",
     "before": ["1画面：「変更のしかた」のラジオ＋同じ半分の14日のボタン＋理由を同じ画面で入れて「申請する」", "1 màn: radio 「変更のしかた」 + 14 nút ngày của cùng nửa + lý do trên cùng màn, bấm 「申請する」"],
     "after": ["2ステップ：①ご利用月（サイクル）の月のカレンダーで日を押す（選べる日を目立たせ、選べない日は灰色）か「希望日なし」→「次へ」 ②理由と確認 →「申請する」。理由・申請するはステップ②（状態 015）", "2 bước: ① bấm ngày trên lịch tháng của tháng sử dụng (chu kỳ) (ngày chọn được nổi bật, không chọn được màu xám) hoặc 「希望日なし」 → 「次へ」 ② lý do và xác nhận → 「申請する」. Lý do, 申請する ở bước ② (trạng thái 015)"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：変更申請のモーダルは月のカレンダーから日を押す2ステップ", "hong trả lời 2026-10-05 review 版1.0: modal xin đổi ngày là 2 bước chọn ngày trên lịch tháng"],
     "impact": ["モーダルを2ステップにする。14日のボタンを月のカレンダー（週ごと7列）に変え、ラジオを「希望日なし」のチェックに変える。理由と「申請する」はステップ②に移す。選べる日の判定（同じ半分・休日・曜日・今のお届け日）とエラー（E02・E300・E301・E304・E305）は変えない", "Đổi modal thành 2 bước. Đổi 14 nút ngày thành lịch tháng (7 cột theo tuần), đổi radio thành ô check 「希望日なし」. Chuyển lý do và 「申請する」 sang bước ②. Giữ nguyên cách xét ngày chọn được (cùng nửa, ngày nghỉ, thứ, ngày hiện tại) và lỗi (E02, E300, E301, E304, E305)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["22.11", "22.12", "22.13", "22.14"], "type": "追加",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：2ステップのモーダルに必要なもの（ステップの表示・次へ・戻る・選んだ日の確認）", "hong trả lời 2026-10-05 review 版1.0: phần cần cho modal 2 bước (hiển thị bước, 次へ, 戻る, xác nhận ngày đã chọn)"],
     "impact": ["ステップの表示・「次へ」（ステップ①の入力チェック）・「戻る」・ステップ②の確認の枠を作る", "Tạo phần hiển thị bước, nút 「次へ」 (kiểm tra nhập bước ①), nút 「戻る」, khung xác nhận ở bước ②"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["23", "23.1"], "type": "変更",
     "before": ["「申請する」で日と理由のエラーを同時に出す", "Bấm 「申請する」 hiện lỗi ngày và lý do cùng lúc"],
     "after": ["日のエラー（23）はステップ①の「次へ」、理由のエラー（23.1）はステップ②の「申請する」で出す", "Lỗi ngày (23) hiện khi bấm 「次へ」 ở bước ①, lỗi lý do (23.1) hiện khi bấm 「申請する」 ở bước ②"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：モーダルが2ステップになったため", "hong trả lời 2026-10-05 review 版1.0: do modal thành 2 bước"],
     "impact": ["入力チェックをステップごとに分ける", "Tách kiểm tra nhập theo từng bước"]},
]

HIDE_ALWAYS = [".es-demo-bar", ".es-chatbot", ".es-chatbot__fab", "#es-review"]
STATIC_CSS = ".corp{height:auto!important}.corp-main{overflow:visible!important}.es-sidenav{height:auto!important;min-height:100vh}"
VIEWER_CSS = STATIC_CSS

SCREENS = [
    {"code": "CW_DLV_001", "ja": "お届け詳細", "vi": "Chi tiết đơn giao hàng"},
]

_OPEN_MODAL = "const a=document.querySelector('.es-pagehead__actions a.es-btn--solid');a&&a.click();await new Promise(r=>setTimeout(r,600));"
_OPEN_DECLINE = "const b=[...document.querySelectorAll('button')].find(x=>x.textContent.includes('お断りする'));b&&b.click();await new Promise(r=>setTimeout(r,500));"

# デモの表示を「解約後（参照のみ）」にする（デモ帯の選択。以降の状態も同じタブで参照のみのままなので、解約後の状態は VIEWS の最後に置く）
_SET_RO = ("const s=[...document.querySelectorAll('select')].find(x=>[...x.options].some(o=>o.value==='ro'));"
          "if(s){const set=Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set;set.call(s,'ro');s.dispatchEvent(new Event('change',{bubbles:true}));}"
          "await new Promise(r=>setTimeout(r,1200));")

# デモの表示を「アカウントの状態のまま」に戻す（_SET_RO のあと、ふつうの表示で撮る状態用）
_SET_DATA = _SET_RO.replace("'ro'", "'data'").replace("o.value==='data'", "o.value==='ro'")

VIEWS = [
    # ------------------------------------------------------------ 001 予定（申請できる）
    {"id": "001", "code": "CW_DLV_001", "state": ["予定（申請できる）", "Dự kiến (có thể xin đổi ngày)"],
     "url": "/corp/deliveries/DL-261123-0001", "setup": "", "full": True, "wait": 1200,
     "note": ["大阪支店 11/24 のお届け（11月分・受付中・締切 10/15 まで）。予定のお届けは、ご注文・変更の締切までお届け日の変更を申請できる（決定 #57）", "Đơn giao 大阪支店 11/24 (tháng 11, đang nhận đơn, hạn 10/15). Đơn dự kiến có thể xin đổi ngày giao đến hạn đặt/đổi (quyết định #57)"],
     "items": [
         {"no": "1", "ja": "見出し", "vi": "Tiêu đề trang", "sel": "header.es-pagehead", "kind": "area", "trig": "view"},
         {"no": "1.1", "ja": "パンくず", "vi": "Breadcrumb", "sel": ".es-breadcrumb", "kind": "label", "trig": "view",
          "detail": ["開いた元（?from=）で変わる。ホーム（なし・不明も）：「ホーム ／ お届け詳細」（「ホーム」はリンク /corp）。申請の一覧から（?from=requests）：「申請 ／ お届け日の変更申請 ／ お届け詳細」（「お届け日の変更申請」はリンク /corp/requests）。お知らせ一覧から（?from=news）：「ホーム ／ お知らせ一覧 ／ お届け詳細」。サイドメニューは開いた元の項目（ホーム／申請 ＞ お届け日の変更）を光らせる", "Đổi theo nơi mở (?from=). Trang chủ (kể cả không có / không rõ): \"ホーム ／ お届け詳細\" (\"ホーム\" là link /corp). Từ danh sách yêu cầu (?from=requests): \"申請 ／ お届け日の変更申請 ／ お届け詳細\" (\"お届け日の変更申請\" là link /corp/requests). Từ danh sách thông báo (?from=news): \"ホーム ／ お知らせ一覧 ／ お届け詳細\". Menu bên sáng đúng mục nơi mở (ホーム／申請 ＞ お届け日の変更)"]},
         {"no": "1.2", "ja": "画面名・お届け番号", "vi": "Tên màn hình, số đơn giao", "sel": "h1.es-pagehead__title", "kind": "label", "trig": "view",
          "detail": ["「お届け詳細 {配送ID}」。配送ID は DL-YYMMDD-NNNN（出荷日で採番。再配送の子は末尾 -1）", "\"お届け詳細 {配送ID}\". 配送ID dạng DL-YYMMDD-NNNN (đánh số theo ngày xuất kho; đơn giao bù thêm -1)"]},
         {"no": "1.3", "ja": "拠点・ご利用月", "vi": "拠点, tháng sử dụng", "sel": "header.es-pagehead .stat", "kind": "label", "trig": "view",
          "detail": ["「{拠点名} ・ {n}月分」。資材のお届けは「{拠点名} ・ 資材」", "\"{tên 拠点} ・ {n}月分\". Đơn vật tư: \"{tên 拠点} ・ 資材\""]},
         {"no": "1.4", "ja": "状態", "vi": "Trạng thái", "sel": "header.es-pagehead .stat .es-badge", "kind": "label", "trig": "view",
          "detail": ["お届けの状態（#42 の法人向けの表示名）：予定（青）／出荷待（青）／配送中（青。出荷済・ドライバー受取済）／お届け済み（緑）／一部お届け済み（黄）／再配送準備中（黄）／配送状況を確認中です（黄）／お届け中止（赤）。別の日のご提案があるときはバッジ「別の日のご提案」（黄）を足す", "Trạng thái đơn giao (tên hiển thị cho pháp nhân #42): 予定 (xanh dương) / 出荷待 (xanh dương) / 配送中 (xanh dương; đã xuất kho, tài xế đã nhận) / お届け済み (xanh lá) / 一部お届け済み (vàng) / 再配送準備中 (vàng) / 配送状況を確認中です (vàng) / お届け中止 (đỏ). Có đề xuất ngày khác thêm badge \"別の日のご提案\" (vàng)"]},
         {"no": "1.5", "ja": "カレンダーへ戻る", "vi": "Về lịch", "sel": "a::カレンダーへ戻る", "kind": "link", "trig": "click",
          "detail": ["開いた元へ戻る。ホームから（既定）：「カレンダーへ戻る」→ ホーム（/corp）。見ていた月・拠点のまま戻る。申請の一覧から：「申請の一覧へ戻る」→ /corp/requests。お知らせ一覧から：「お知らせ一覧へ戻る」→ /corp/news", "Quay về nơi mở. Từ trang chủ (mặc định): \"カレンダーへ戻る\" → trang chủ (/corp), giữ tháng và 拠点 đang xem. Từ danh sách yêu cầu: \"申請の一覧へ戻る\" → /corp/requests. Từ danh sách thông báo: \"お知らせ一覧へ戻る\" → /corp/news"]},
         {"no": "1.6", "ja": "お届け日の変更を申請", "vi": "Xin đổi ngày giao", "sel": ".es-pagehead__actions a.es-btn--solid", "kind": "button", "trig": "click",
          "cond": ["予定のお届けで、ご注文・変更の締切の日まで、まだ決まっていない申請（申請中・別の日のご提案・お断り済）がないとき。解約後（参照のみ）のアカウントには出さない（Q-C2。サーバーも断る：E345）。出さないときは No.6.1 に理由", "Đơn dự kiến, đến ngày hạn đặt/đổi, và không có yêu cầu chưa xử lý (申請中・別の日のご提案・お断り済). Tài khoản sau giải ước (chỉ xem) không hiện (Q-C2; server cũng từ chối: E345). Không hiện thì ghi lý do ở No.6.1"],
          "detail": ["申請モーダル（No.22）を開く。同じボタンを「お届け日の変更申請」のカード（No.6）にも置く。確定（出荷待）以降の便では、代わりに「納品書（PDF）」のボタン（No.17）を見出しの右に出す（予定の便には出さない）", "Mở modal yêu cầu (No.22). Nút này cũng đặt ở thẻ \"お届け日の変更申請\" (No.6). Với chuyến đã chốt (từ 出荷待) thì thay bằng nút 「納品書（PDF）」 (No.17) bên phải tiêu đề (chuyến dự kiến không có)"]},
         {"no": "2", "ja": "お届けの予定", "vi": "Lịch giao", "sel": "h2::お届けの予定^2", "kind": "area", "trig": "view"},
         {"no": "2.1", "ja": "お届け日（着予定日）", "vi": "Ngày giao (ngày đến dự kiến)", "sel": "label::お届け日（着予定日）^", "kind": "label", "trig": "view",
          "detail": ["YYYY-MM-DD（曜）。変更申請が承認されたら新しい日", "YYYY-MM-DD（thứ）. Yêu cầu đổi ngày được duyệt thì hiện ngày mới"]},
         {"no": "2.4", "ja": "温度帯・お届け方法", "vi": "温度帯, cách giao", "sel": "label::温度帯・お届け方法^", "kind": "label", "trig": "view",
          "detail": ["「{温度帯} ・ {配送区分}」。ES配送便は「ES配送便（陳列まで）」、クール便は「クール便（宅配便）」、資材は「資材 ・ 資材便」。倉庫・配送会社・ドライバーは出さない（#56）", "\"{温度帯} ・ {配送区分}\". ES配送便: \"ES配送便（陳列まで）\", クール便: \"クール便（宅配便）\", vật tư: \"資材 ・ 資材便\". Không hiện kho, hãng vận chuyển, tài xế (#56)"]},
         {"no": "3", "ja": "お届けする商品", "vi": "Sản phẩm sẽ giao", "sel": "h2::お届けする商品^2", "kind": "area", "trig": "view",
          "detail": ["見出しはお届け前「お届けする商品」、お届け後「お届けした商品」。予定（ご注文・変更の締切の前）は商品・数量を出さず「数量はまだ決まっていません」と「ご注文・変更の締切の後に表示されます。」（#56）。確定（出荷待）から表（No.3.1〜3.5）", "Tiêu đề: trước khi giao \"お届けする商品\", sau khi giao \"お届けした商品\". Đơn dự kiến (trước hạn đặt/đổi) không hiện sản phẩm và số lượng, chỉ \"数量はまだ決まっていません\" và \"ご注文・変更の締切の後に表示されます。\" (#56). Từ khi chốt (出荷待) hiện bảng (No.3.1〜3.5)"]},
         {"no": "4", "ja": "お届けの状況", "vi": "Tình trạng giao", "sel": "h2::お届けの状況^2", "kind": "area", "trig": "view"},
         {"no": "4.1", "ja": "まだお届けしていません", "vi": "Chưa giao", "sel": ".es-empty", "kind": "label", "trig": "view",
          "cond": ["お届け完了の前", "Trước khi giao xong"],
          "detail": ["状態で変わる。予定・出荷待：「まだお届けしていません」＋「お届け日（{MM-DD}）に、担当者の報告で表示されます。」。配送中：同じ見出し＋ES配送便は同じ説明、クール便は「お届けが完了すると表示されます。」。再配送準備中：「まだお届けしていません」＋「ESキッチンが再配送の日を調整しています。決まりしだいご連絡します。」。配送状況を確認中：「お届けの状況を確認しています」＋「確認が済みしだい、ESキッチンからご連絡します。」。お届け中止：「お届けしません」＋「このお届けは中止になりました。ご不明な点はESキッチンへお問い合わせください。」", "Đổi theo trạng thái. 予定・出荷待: \"まだお届けしていません\" + \"お届け日（{MM-DD}）に、担当者の報告で表示されます。\". Đang giao: cùng tiêu đề; ES配送便 cùng giải thích, クール便 \"お届けが完了すると表示されます。\". 再配送準備中: \"まだお届けしていません\" + \"ESキッチンが再配送の日を調整しています。決まりしだいご連絡します。\". Đang xác nhận: \"お届けの状況を確認しています\" + \"確認が済みしだい、ESキッチンからご連絡します。\". お届け中止: \"お届けしません\" + \"このお届けは中止になりました。ご不明な点はESキッチンへお問い合わせください。\""]},
         {"no": "5", "ja": "送り状番号", "vi": "Số phiếu gửi", "sel": "h2::送り状番号^2", "kind": "area", "trig": "view",
          "detail": ["見出し「送り状番号」。クール便・資材便の送り状番号（No.14）か、番号がないときの説明（No.5.1）", "Tiêu đề 「送り状番号」. Số phiếu gửi của クール便 / 資材便 (No.14) hoặc ghi chú khi chưa có số (No.5.1)"]},
         {"no": "5.1", "ja": "送り状の説明（番号なし）", "vi": "Ghi chú phiếu gửi (chưa có số)", "sel": ".note::送り状番号", "kind": "label", "trig": "view",
          "detail": ["ES配送便：「ES配送便は送り状番号がありません。」。クール便・資材便の出荷前：「出荷すると送り状番号が表示されます。」。配送会社の欄は作らない（#56）", "ES配送便: \"ES配送便は送り状番号がありません。\". クール便 / 資材便 trước khi xuất kho: \"出荷すると送り状番号が表示されます。\". Không có cột hãng vận chuyển (#56)"]},
         {"no": "6", "ja": "お届け日の変更申請", "vi": "Yêu cầu đổi ngày giao", "sel": "h2::お届け日の変更申請^2", "kind": "area", "trig": "view"},
         {"no": "6.1", "ja": "申請の案内", "vi": "Hướng dẫn yêu cầu", "sel": ".note::お届け日の変更を申請できます", "kind": "label", "trig": "view",
          "detail": ["申請できるとき：「このお届けは予定です。ご注文・変更の締切（{MM-DD}）まで、お届け日の変更を申請できます。ESキッチンが確認して、承認・別の日のご提案・お断りのいずれかでお返事します。」＋ボタン「お届け日の変更を申請」。申請できないときは理由を常時表示（#57）：お届け済み「お届け済みのため、変更は申請できません。」／確定「確定したお届けのため、日付の変更は申請できません。」／ご返事が必要な申請あり「このお届けには、ご返事が必要な申請があります（上の枠）。申請は1件ずつです。」／確認中の申請あり「このお届けには、ESキッチンが確認している申請があります（下の申請）。申請は1件ずつです。」／締切を過ぎた「ご注文・変更の締切（{MM-DD}）を過ぎたため、日付の変更は申請できません。お急ぎの場合はESキッチンへお問い合わせください。」",
                     "Khi xin được: \"このお届けは予定です。ご注文・変更の締切（{MM-DD}）まで、お届け日の変更を申請できます。ESキッチンが確認して、承認・別の日のご提案・お断りのいずれかでお返事します。\" + nút \"お届け日の変更を申請\". Không xin được thì luôn hiện lý do (#57): đã giao / đã chốt / có yêu cầu cần trả lời (khung trên) / có yêu cầu đang xác nhận (bên dưới) / quá hạn (\"ご注文・変更の締切（{MM-DD}）を過ぎたため…ESキッチンへお問い合わせください。\")"]},
     ]},
    # ------------------------------------------------------------ 002 予定（申請中）
    {"id": "002", "code": "CW_DLV_001", "state": ["予定（申請中）", "Dự kiến (đang có yêu cầu đổi ngày)"],
     "url": "/corp/deliveries/DL-261207-0001", "setup": "", "full": True, "wait": 1200,
     "note": ["大阪支店 12/08 のお届け。変更申請 DD-20261005-0096（12/08 → 第一希望 12/10・第二希望 12/11）が申請中（見本データ・版1.4：11/10 の見本は別の日のご提案に変えたため、申請中の見本は 12/08 に移した）。申請は1件ずつなので新しい申請はできない。申請の履歴に行が出る", "Đơn giao 大阪支店 12/08. Yêu cầu DD-20261005-0096 (12/08 → NV1 12/10, NV2 12/11) đang 申請中 (dữ liệu mẫu, 版1.4: vì mẫu 11/10 đã đổi thành đề xuất ngày khác nên mẫu đang xử lý chuyển sang 12/08). Mỗi lần 1 yêu cầu nên không tạo yêu cầu mới. Lịch sử yêu cầu có 1 dòng"],
     "items": [
         {"no": "7", "ja": "申請できない理由（申請中）", "vi": "Lý do không xin được (đang có yêu cầu)", "sel": ".note::申請は1件ずつです", "kind": "label", "trig": "view",
          "detail": ["「このお届けには、ESキッチンが確認している申請があります（下の申請）。申請は1件ずつです。」。ボタンは出ない", "\"このお届けには、ESキッチンが確認している申請があります（下の申請）。申請は1件ずつです。\". Không có nút"]},
         {"no": "8", "ja": "申請の履歴（表）", "vi": "Lịch sử yêu cầu (bảng)", "sel": "table.crt", "kind": "table", "trig": "view",
          "detail": ["このお届けの申請（新しい順）を表で出す。列：申請番号・申請日・第一希望・第二希望・理由・状態・ご返事の期限（No.8.2〜8.8）。申請中の行は上に、終わった申請（承認・否認・取り下げ・お断り済）はその下。否認の行は理由の列の下に「お断りの理由：{理由}です。」。「取り下げる」（No.8.1）は申請中の行の右端。0件のときは表を出さず「申請はありません」", "Hiện các yêu cầu của đơn này (mới nhất trước) dạng bảng. Cột: 申請番号, 申請日, 第一希望, 第二希望, 理由, 状態, ご返事の期限 (No.8.2〜8.8). Dòng 申請中 ở trên, yêu cầu đã xong (承認, 否認, 取り下げ, お断り済) ở dưới. Dòng 否認 có \"お断りの理由：{lý do}です。\" dưới cột lý do. 「取り下げる」 (No.8.1) ở cuối dòng 申請中. 0 mục thì không hiện bảng mà ghi \"申請はありません\""]},
         {"no": "8.1", "ja": "取り下げる", "vi": "Rút lại yêu cầu", "sel": "table.crt button::取り下げる", "kind": "button", "trig": "click", "err": ["Q201", "S211"],
          "cond": ["状態が「申請中」（ESキッチンの提案・処理の前）の行だけ。拠点アカウントには、法人アカウントが出した申請の「取り下げる」を出さない（H2）。解約後（参照のみ）のアカウントには出さない（サーバーも断る：E345）", "Chỉ ở dòng \"申請中\" (trước khi ES Kitchen đề xuất / xử lý). Tài khoản 拠点 không thấy nút ở yêu cầu do tài khoản pháp nhân tạo (H2). Không hiện với tài khoản sau giải ước (chỉ xem) (server cũng từ chối: E345)"],
          "detail": ["行の右の小さなボタン（実行中は重ねて押せない）。Q201 で確認して「取り下げる」→ 状態を「取り下げ」にし、このお届けは再び申請できる（締切まで）。運営Web の申請も「取り下げ」になる", "Nút nhỏ bên phải dòng. Xác nhận bằng Q201, \"取り下げる\" → trạng thái thành \"取り下げ\", đơn này lại xin đổi được (đến hạn). Yêu cầu ở 運営Web cũng thành \"取り下げ\""]},
         {"no": "8.2", "ja": "申請番号", "vi": "Số yêu cầu", "sel": "th::申請番号", "kind": "label", "trig": "view",
          "detail": ["DD-YYYYMMDD-NNNN（申請した日で採番）。等幅", "DD-YYYYMMDD-NNNN (đánh số theo ngày yêu cầu). Font đơn cách"]},
         {"no": "8.3", "ja": "申請日", "vi": "Ngày yêu cầu", "sel": "th::申請日", "kind": "label", "trig": "view",
          "detail": ["申請した日 YYYY-MM-DD", "Ngày gửi yêu cầu YYYY-MM-DD"]},
         {"no": "8.4", "ja": "第一希望", "vi": "Nguyện vọng 1", "sel": "th::第一希望", "kind": "label", "trig": "view",
          "detail": ["YYYY-MM-DD（曜）。希望日なしの申請は「希望日なし」", "YYYY-MM-DD（thứ）. Yêu cầu không có nguyện vọng: \"希望日なし\""]},
         {"no": "8.5", "ja": "第二希望", "vi": "Nguyện vọng 2", "sel": "th::第二希望", "kind": "label", "trig": "view",
          "detail": ["YYYY-MM-DD（曜）。ないときは「—」", "YYYY-MM-DD（thứ）. Không có: \"—\""]},
         {"no": "8.6", "ja": "理由", "vi": "Lý do", "sel": "th::理由", "kind": "label", "trig": "view",
          "detail": ["申請のときに入れた理由（No.22.7）。長いときは2行で切り、ツールチップに全文", "Lý do đã nhập khi yêu cầu (No.22.7). Dài thì cắt 2 dòng, tooltip hiện đủ"]},
         {"no": "8.7", "ja": "状態", "vi": "Trạng thái", "sel": "th::状態", "kind": "label", "trig": "view",
          "detail": ["バッジ：申請中（青）／別の日のご提案（黄）／承認（緑）／否認（灰）／取り下げ（灰）／お断り済（ESキッチンで調整中）（灰）", "Badge: 申請中 (xanh dương) / 別の日のご提案 (vàng) / 承認 (xanh lá) / 否認 (xám) / 取り下げ (xám) / お断り済（ESキッチンで調整中） (xám)"]},
         {"no": "8.8", "ja": "ご返事の期限", "vi": "Hạn trả lời", "sel": "th::ご返事の期限", "kind": "label", "trig": "view",
          "detail": ["ESキッチンの処理期限（＝そのご利用月のご注文・変更の締切）YYYY-MM-DD。別の日のご提案のときは法人がご返事する期限（同じ日）。終わった申請は「—」", "Hạn xử lý của ES Kitchen (= hạn đặt/đổi của tháng sử dụng) YYYY-MM-DD. Khi có đề xuất ngày khác là hạn pháp nhân trả lời (cùng ngày). Yêu cầu đã xong: \"—\""]},
     ]},
    # ------------------------------------------------------------ 003 予定（締切を過ぎた）
    {"id": "003", "code": "CW_DLV_001", "state": ["締切を過ぎた（確定済み・申請できない）", "Đã quá hạn (đã xác định, không xin đổi ngày được)"],
     "url": "/corp/deliveries/DL-261123-0001", "today": "2026/10/16", "setup": "", "full": True, "wait": 1200,
     "note": ["デモの今日を 2026/10/16（11月分の締切 10/15 の翌日）にした状態。まだ予定だが申請できない。理由を常時表示（#57）", "Đặt \"hôm nay\" = 2026/10/16 (ngày sau hạn 10/15 của tháng 11). Vẫn là dự kiến nhưng không xin đổi được. Luôn hiện lý do (#57)"],
     "items": [
         {"no": "9", "ja": "申請できない理由（締切を過ぎた）", "vi": "Lý do không xin được (quá hạn)", "sel": "*::日付の変更は申請できません", "kind": "label", "trig": "view",
          "detail": ["「ご注文・変更の締切（{MM-DD}）を過ぎたため、日付の変更は申請できません。お急ぎの場合はESキッチンへお問い合わせください。」。見出しのボタンも出ない", "\"ご注文・変更の締切（{MM-DD}）を過ぎたため、日付の変更は申請できません。お急ぎの場合はESキッチンへお問い合わせください。\". Nút ở tiêu đề cũng không hiện"]},
     ]},
    # ------------------------------------------------------------ 004 別の日のご提案あり
    {"id": "004", "code": "CW_DLV_001", "state": ["別の日のご提案あり（受ける／お断りする）", "Có đề xuất ngày khác (nhận / từ chối)"],
     "url": "/corp/deliveries/DL-261109-0001", "setup": "", "full": True, "wait": 1200,
     "note": ["大阪支店 11/10 のお届け。共通の見本データの変更申請 DD-20261005-0095（11/10 → 第一希望 11/12・第二希望 11/17）に、ESキッチンが 11/13 を提案している状態（見本データ・版1.4）。見出しの下に申請の枠（#62）：今のお届け日 → ご希望の日 → ESキッチンからのご提案、「お断りする」「{日} で受ける」", "Đơn giao 大阪支店 11/10. Yêu cầu đổi ngày mẫu chung DD-20261005-0095 (11/10 → NV1 11/12, NV2 11/17) đang được ES Kitchen đề xuất 11/13 (dữ liệu mẫu, 版1.4). Dưới tiêu đề là khung yêu cầu (#62): ngày hiện tại → ngày mong muốn → đề xuất của ES Kitchen, \"お断りする\" \"{日} で受ける\""],
     "items": [
         {"no": "10", "ja": "申請の枠（別の日のご提案）", "vi": "Khung yêu cầu (đề xuất ngày khác)", "sel": ".crb", "kind": "area", "trig": "view",
          "cond": ["変更申請が「別の日のご提案」または「お断り済（ESキッチンで調整中）」のとき", "Khi yêu cầu ở trạng thái \"別の日のご提案\" hoặc \"お断り済（ESキッチンで調整中）\""],
          "detail": ["見出し「お届け日の変更申請 {申請番号}」・状態のバッジ・「申請日 {YYYY-MM-DD（曜）} ・ ご返事の期限 {期限}」（期限＝ご注文・変更の締切）。見出しの状態にもバッジ「別の日のご提案」", "Tiêu đề \"お届け日の変更申請 {申請番号}\", badge trạng thái, \"申請日 {YYYY-MM-DD（曜）} ・ ご返事の期限 {期限}\" (hạn = hạn đặt/đổi). Trạng thái ở tiêu đề trang cũng có badge \"別の日のご提案\""]},
         {"no": "10.1", "ja": "今のお届け日", "vi": "Ngày giao hiện tại", "sel": ".crb__box::今のお届け日", "kind": "label", "trig": "view",
          "detail": ["YYYY-MM-DD（曜）＋「ご返事までは、この日のままです」", "YYYY-MM-DD（thứ） + \"ご返事までは、この日のままです\""]},
         {"no": "10.2", "ja": "ご希望の日", "vi": "Ngày mong muốn", "sel": ".crb__box::ご希望の日", "kind": "label", "trig": "view",
          "detail": ["第一希望の日（希望日なしは「希望日なし」）＋「お受けできませんでした」", "Ngày nguyện vọng 1 (không có: \"希望日なし\") + \"お受けできませんでした\""]},
         {"no": "10.3", "ja": "ESキッチンからのご提案", "vi": "Đề xuất của ES Kitchen", "sel": ".crb__box.is-new", "kind": "label", "trig": "view",
          "detail": ["提案の日 YYYY-MM-DD（曜）＋運営の理由。青い枠", "Ngày đề xuất YYYY-MM-DD（thứ） + lý do của vận hành. Viền xanh dương"]},
         {"no": "10.4", "ja": "ESキッチンから", "vi": "Lời nhắn của ES Kitchen", "sel": ".crb__row", "kind": "label", "trig": "view",
          "detail": ["「{提案の日}でいかがでしょうか」", "\"{ngày đề xuất}でいかがでしょうか\""]},
         {"no": "10.5", "ja": "ご返事の説明", "vi": "Giải thích về trả lời", "sel": ".crb__f .note", "kind": "label", "trig": "view",
          "detail": ["「ご返事がない場合は、期限の後にESキッチンが決めてご連絡します。お断りの場合も、ESキッチンからご連絡します。」。お断りした後：「ご提案をお断りしました（{日時}）。ESキッチンが別の日を調整して、ご返事の期限（{期限}）までにご連絡します。それまでのお届け日は {今の日} のままです。」でボタンは出ない", "\"ご返事がない場合は、期限の後にESキッチンが決めてご連絡します。お断りの場合も、ESキッチンからご連絡します。\". Sau khi từ chối: \"ご提案をお断りしました（{日時}）。ESキッチンが別の日を調整して、ご返事の期限（{期限}）までにご連絡します。それまでのお届け日は {今の日} のままです。\" và không có nút"]},
         {"no": "10.6", "cond": ["解約後（参照のみ）のアカウントには出さない（サーバーも断る：E345）。ご返事ができない旨は No.10.8", "Không hiện với tài khoản sau giải ước (chỉ xem) (server cũng từ chối: E345). Câu báo không trả lời được: No.10.8"], "ja": "お断りする", "vi": "Từ chối", "sel": "button::お断りする", "kind": "button", "trig": "click", "err": ["Q200"],
          "detail": ["確認モーダル（No.11）を開く", "Mở modal xác nhận (No.11)"]},
         {"no": "10.7", "cond": ["解約後（参照のみ）のアカウントには出さない（サーバーも断る：E345）。ご返事ができない旨は No.10.8", "Không hiện với tài khoản sau giải ước (chỉ xem) (server cũng từ chối: E345). Câu báo không trả lời được: No.10.8"], "ja": "{日} で受ける", "vi": "Nhận ngày {日}", "sel": "button::で受ける", "kind": "button", "trig": "click", "err": ["S201", "E30"],
          "detail": ["ボタンの文字は「{MM-DD} で受ける」。押すとすぐに受ける（確認なし）：申請は承認、お届け日は提案の日（配送データも動く・同じ日の冷凍・冷蔵は一緒に動く）。S201 を出して申請の一覧（/corp/requests）へ。押したら二重送信を防ぐために無効にする", "Chữ nút \"{MM-DD} で受ける\". Bấm là nhận ngay (không hỏi lại): yêu cầu thành 承認, ngày giao = ngày đề xuất (dữ liệu giao hàng cũng đổi; 冷凍・冷蔵 cùng ngày đổi cùng). Hiện S201 rồi sang danh sách yêu cầu (/corp/requests). Khóa nút sau khi bấm để tránh gửi 2 lần"]},
     ]},
    # ------------------------------------------------------------ 005 お断りの確認モーダル
    {"id": "005", "code": "CW_DLV_001", "state": ["お断りの確認モーダル", "Modal xác nhận từ chối"],
     "url": "/corp/deliveries/DL-261109-0001", "setup": _OPEN_DECLINE, "full": True, "wait": 300,
     "note": ["004 で「お断りする」を押した（見本データの DD-20261005-0095 のご提案を対象にした確認モーダル）。「お断りする（実行）」は押さずに撮る（押すと見本データが変わる）", "Bấm \"お断りする\" ở 004 (modal xác nhận cho đề xuất của DD-20261005-0095 trong dữ liệu mẫu). Chụp mà không bấm \"お断りする（実行）\" (bấm thì dữ liệu mẫu đổi)"],
     "items": [
         {"no": "11", "ja": "ご提案をお断りしますか？", "vi": "Từ chối đề xuất?", "sel": ".rv-dlg", "kind": "modal", "trig": "show", "err": ["Q200"],
          "detail": ["Q200。本文にご提案の日（YYYY-MM-DD（曜））・ご返事の期限・今のお届け日を差し込む。外を押すか Esc で閉じる（キャンセルと同じ）", "Q200. Nội dung chèn ngày đề xuất (YYYY-MM-DD（thứ）), hạn trả lời, ngày giao hiện tại. Bấm ra ngoài hoặc Esc để đóng (như キャンセル)"]},
         {"no": "11.1", "ja": "キャンセル", "vi": "Hủy", "sel": ".rv-dlg button::キャンセル", "kind": "button", "trig": "click",
          "detail": ["閉じる。何も変えない", "Đóng. Không đổi gì"]},
         {"no": "11.2", "cond": ["解約後（参照のみ）のアカウントには出さない（サーバーも断る：E345）。モーダル自体が開かない", "Không hiện với tài khoản sau giải ước (chỉ xem) (server cũng từ chối: E345). modal cũng không mở được"], "ja": "お断りする（実行）", "vi": "Từ chối (thực hiện)", "sel": ".rv-dlg button::お断りする", "kind": "button", "trig": "click", "err": ["S202", "E30"],
          "detail": ["申請を「お断り済（ESキッチンで調整中）」にし、S202 をトースト。画面は上に戻り、枠が「お断り済」の形（No.10.5）になる。運営Web に「法人の返事：断る」が届く", "Chuyển yêu cầu thành \"お断り済（ESキッチンで調整中）\", toast S202. Cuộn lên đầu, khung chuyển sang dạng \"お断り済\" (No.10.5). 運営Web nhận \"法人の返事：断る\""]},
     ]},
    # ------------------------------------------------------------ 006 確定（出荷待・商品の表）
    {"id": "006", "code": "CW_DLV_001", "state": ["確定（出荷待・商品の表）", "Đã chốt (出荷待, bảng sản phẩm)"],
     "url": "/corp/deliveries/DL-261012-0011", "setup": "", "full": True, "wait": 1200,
     "note": ["大阪支店 10/13 のお届け（10月分・締切済み・出荷待）。商品の表にご注文数。商品の不良（ALT-2610-0001）の代替品の行は備考に「代替品（元：デミグラスハンバーグ）・補償（0円）」。確定したお届けは申請できない。出荷待から見出しの右に「納品書（PDF）」（No.17・版1.1）", "Đơn giao 大阪支店 10/13 (tháng 10, đã chốt, 出荷待). Bảng sản phẩm có số đặt. Dòng sản phẩm thay thế (lỗi ALT-2610-0001) ghi chú \"代替品（元：デミグラスハンバーグ）・補償（0円）\". Đơn đã chốt không xin đổi được. Từ 出荷待 có nút 「納品書（PDF）」 bên phải tiêu đề (No.17, 版1.1; code chỉ hiện khi đã giao nên sẽ chụp lại)"],
     "items": [
         {"no": "12", "ja": "商品の表（確定）", "vi": "Bảng sản phẩm (đã chốt)", "sel": "table.es-table", "kind": "table", "trig": "view",
          "detail": ["確定（出荷待）から出す。お届け数・差は「—」「」のまま。並びはご注文の並び（代替品・除外の行は最後）", "Hiện từ khi chốt (出荷待). Số giao, chênh lệch còn \"—\" / trống. Thứ tự theo đơn hàng (dòng thay thế / loại trừ ở cuối)"]},
         {"no": "12.1", "ja": "備考（代替品）", "vi": "Ghi chú (sản phẩm thay thế)", "sel": "td.w::代替品", "kind": "label", "trig": "view",
          "detail": ["「代替品（元：{元の商品名}）・補償（0円）」。ご請求の扱いを含めて書く", "\"代替品（元：{tên gốc}）・補償（0円）\". Ghi cả cách tính tiền"]},
         {"no": "13", "ja": "申請できない理由（確定）", "vi": "Lý do không xin được (đã chốt)", "sel": ".note::確定したお届けのため", "kind": "label", "trig": "view",
          "detail": ["「確定したお届けのため、日付の変更は申請できません。」。日付を変えたいときは ESキッチンへ（ホームの月の説明）", "\"確定したお届けのため、日付の変更は申請できません。\". Muốn đổi ngày thì liên hệ ES Kitchen (ghi chú tháng ở trang chủ)"]},
         {"no": "3.1", "ja": "商品名", "vi": "Tên sản phẩm", "sel": "th::商品名", "kind": "label", "trig": "view",
          "detail": ["お届けした明細はお届けしたときの商品名（名前が変わっていれば「旧名（現：新名）」）", "Dòng đã giao hiện tên sản phẩm lúc giao (đổi tên thì \"tên cũ（現：tên mới）\")"]},         {"no": "3.2", "ja": "ご注文数", "vi": "Số lượng đặt", "sel": "th::ご注文数", "kind": "label", "trig": "view",
          "detail": ["「{n}個」。右寄せ", "\"{n}個\". Căn phải"]},         {"no": "3.3", "ja": "お届け数", "vi": "Số lượng giao", "sel": "th::お届け数", "kind": "label", "trig": "view",
          "detail": ["お届け後「{n}個」、お届け前「—」。右寄せ", "Sau khi giao \"{n}個\", trước khi giao \"—\". Căn phải"]},         {"no": "3.4", "ja": "差", "vi": "Chênh lệch", "sel": "th::差", "kind": "label", "trig": "view",
          "detail": ["お届け数－ご注文数（お届け後だけ）。マイナスは「−{n}」で赤字", "Số giao − số đặt (chỉ sau khi giao). Âm ghi \"−{n}\" màu đỏ"]},         {"no": "3.5", "ja": "備考", "vi": "Ghi chú", "sel": "th::備考", "kind": "label", "trig": "view",
          "detail": ["代替品の行：「代替品（元：{元の商品名}）・補償（0円）」など（請求の扱いを含む）。届けない不良商品：「{代替の説明}（{n}個）」でご注文数 0個", "Dòng sản phẩm thay thế: \"代替品（元：{tên gốc}）・補償（0円）\"… (gồm cách tính tiền). Sản phẩm lỗi không giao: \"{giải thích}（{n}個）\" với số đặt 0個"]},
     ]},
    # ------------------------------------------------------------ 007 クール便（送り状あり）
    {"id": "007", "code": "CW_DLV_001", "state": ["配送中（送り状あり・クール便）", "Đang giao (có phiếu gửi, クール便)"],
     "url": "/corp/deliveries/DL-260915-0004", "setup": "", "full": True, "wait": 1200,
     "note": ["千葉営業所 9/16 のクール便（宅配便）。送り状番号・コピー・運送会社の追跡ページへのリンク。見本データには「出荷済（配送中）」のまま残っているお届けがない（共通データの出荷は見本の今日 2026/10/05 までにすべて届いた形）ので、お届け済みの便で送り状の部分を撮る（配送中の便を作ると運営・ドライバーの画面の見本が変わるため作っていない）。配送中は状態が「配送中」で、お届けの状況は「まだお届けしていません」", "クール便 (bưu kiện) 千葉営業所 9/16. Số phiếu gửi, nút copy, link trang theo dõi của hãng. Dữ liệu mẫu không có đơn nào còn ở trạng thái đang giao (出荷済) (đơn xuất kho trong dữ liệu chung đều đã giao đến ngày hôm nay 2026/10/05 của bản mẫu) nên chụp phần phiếu gửi bằng đơn đã giao (không tạo đơn đang giao vì sẽ đổi dữ liệu mẫu của màn hình vận hành / tài xế). Khi đang giao: trạng thái \"配送中\", tình trạng giao \"まだお届けしていません\""],
     "items": [
         {"no": "14", "ja": "送り状の行", "vi": "Dòng phiếu gửi", "sel": ".rv", "kind": "label", "trig": "view",
          "cond": ["クール便・資材便で出荷したあと（送り状が有効なもの）。箱ごとに1行", "Sau khi xuất kho với クール便 / 資材便 (phiếu gửi còn hiệu lực). Mỗi thùng 1 dòng"],
          "detail": ["送り状番号（例 4471-0915-0007）・「コピー」・「{運送会社}の追跡ページ ↗」・「箱 {n}/{総数}」", "Số phiếu gửi (ví dụ 4471-0915-0007), \"コピー\", \"{運送会社}の追跡ページ ↗\", \"箱 {n}/{総数}\""]},
         {"no": "14.1", "ja": "コピー", "vi": "Copy", "sel": "button::コピー", "kind": "button", "trig": "click",
          "detail": ["送り状番号をクリップボードにコピーし、1.6秒だけ「コピーしました」に変わる", "Copy số phiếu gửi vào clipboard, nút đổi thành \"コピーしました\" trong 1,6 giây"]},
         {"no": "14.2", "ja": "追跡ページ", "vi": "Trang theo dõi", "sel": "a::の追跡ページ", "kind": "link", "trig": "click",
          "detail": ["「{運送会社}の追跡ページ ↗」（Q-D1：運送会社名を書いてよい。配送会社の欄は作らない）。新しいタブで開く。ヤマト運輸は番号（12桁）を入れた URL、番号の形が違うときは追跡ページだけ。ほかの会社は委託配送先マスタの追跡URL（なければリンクなし）", "\"{運送会社}の追跡ページ ↗\" (Q-D1: được ghi tên hãng; không làm cột riêng). Mở tab mới. ヤマト運輸: URL có sẵn số (12 chữ số); số khác dạng thì chỉ mở trang theo dõi. Hãng khác: URL theo dõi trong master 委託配送先 (không có thì không link)"]},
         {"no": "14.3", "ja": "追跡ページの説明", "vi": "Ghi chú về trang theo dõi", "sel": ".note::追跡ページで確認できます", "kind": "label", "trig": "view",
          "detail": ["「配送の途中の状況は、運送会社（{運送会社}）の追跡ページで確認できます。追跡ページに番号が入っていないときは、コピーした送り状番号を貼り付けてください。」", "\"配送の途中の状況は、運送会社（{運送会社}）の追跡ページで確認できます。追跡ページに番号が入っていないときは、コピーした送り状番号を貼り付けてください。\""]},
     ]},
    # ------------------------------------------------------------ 008 お届け済み（ES配送便）
    {"id": "008", "code": "CW_DLV_001", "state": ["お届け済み（ES配送便：受け取った方・集金）", "Đã giao (ES配送便: người nhận, thu tiền)"],
     "url": "/corp/deliveries/DL-260928-0014", "setup": "", "full": True, "wait": 1200,
     "note": ["大阪支店 9/29 のお届け（ES配送便・お届け済み）。お届けの状況にお届け完了・受け取った方・集金、商品の表にお届け数と差。写真・在庫と廃棄・5ステップは出さない（#60）", "Đơn giao 大阪支店 9/29 (ES配送便, đã giao). Tình trạng giao có giờ giao xong, người nhận, tiền thu; bảng sản phẩm có số giao và chênh lệch. Không hiện ảnh, tồn kho/hủy, 5 bước (#60)"],
     "items": [
         {"no": "15", "ja": "お届け完了", "vi": "Giao xong", "sel": "label::お届け完了^", "kind": "label", "trig": "view",
          "detail": ["YYYY-MM-DD（曜）HH:MM。ES配送便はドライバーの報告の日時、クール便は配達の推定（お届け日 18:00）", "YYYY-MM-DD（thứ）HH:MM. ES配送便: giờ tài xế báo cáo; クール便: ước tính (ngày giao 18:00)"]},
         {"no": "15.1", "ja": "受け取った方", "vi": "Người nhận", "sel": "label::受け取った方^", "kind": "label", "trig": "view",
          "detail": ["ES配送便：拠点のメイン担当者の氏名。クール便（宅配便）は空", "ES配送便: tên người phụ trách chính của 拠点. クール便 (bưu kiện): để trống"]},
         {"no": "15.2", "ja": "集金", "vi": "Tiền thu", "sel": "label::集金^", "kind": "label", "trig": "view",
          "detail": ["ドライバーが集金した金額「{n}円」（集金のある拠点だけ）。ないときは空", "Số tiền tài xế thu \"{n}円\" (chỉ 拠点 có thu tiền). Không có thì trống"]},
         {"no": "16", "ja": "お届けした商品（お届け数・差）", "vi": "Sản phẩm đã giao (số giao, chênh lệch)", "sel": "td.es-num", "kind": "label", "trig": "view",
          "detail": ["お届け後は お届け数「{n}個」・差「0」「−{n}」。見出しは「お届けした商品」", "Sau khi giao: số giao \"{n}個\", chênh lệch \"0\" / \"−{n}\". Tiêu đề \"お届けした商品\""]},
         {"no": "17", "ja": "納品書（PDF）", "vi": "Phiếu giao hàng (PDF)", "sel": "a::納品書（PDF）", "kind": "button", "trig": "click", "err": ["S207", "E306"],
          "cond": ["確定（出荷待）以降の便：出荷待／配送中／お届け済み／一部お届け済み／再配送準備中／配送状況を確認中／お届け中止。予定の便・資材便には出さない。解約後（参照のみ）のアカウントにも出す", "Chuyến từ khi chốt (出荷待) trở đi: 出荷待／配送中／お届け済み／一部お届け済み／再配送準備中／配送状況を確認中／お届け中止. Chuyến dự kiến và chuyến vật tư không có. Tài khoản sau giải ước (chỉ xem) vẫn có"],
          "detail": ["見出しの右のボタン。この便の納品書（A4 縦・PDF・金額なし。中身は No.25）を PDF ファイルとして直接ダウンロードする（ブラウザの印刷画面は経由しない）。ファイル名 納品書_{納品書番号}.pdf。明細が1ページに収まらないときは表の行の切れ目で改ページし、見出しの行を各ページに繰り返す。ページ番号「n / 全ページ数」を下に出す（文字は画像で、選択・検索はできない）。お届け前は予定数で作り、お届け数は「—」。お届け後はお届け数・代替品・不足を反映。出せたら S207（トースト）。作れなかったときは E306。納品書は注文履歴からは出さない（この画面だけ）", "Nút bên phải tiêu đề. Mở 納品書 của chuyến này (A4 dọc, PDF, không có tiền; nội dung No.25) thành file PDF, tải trực tiếp (không qua màn hình in của trình duyệt). Tên file 納品書_{số phiếu}.pdf. Nếu chi tiết không vừa 1 trang thì ngắt trang ở ranh giới dòng và lặp lại dòng tiêu đề bảng ở mỗi trang; ghi số trang \"n / tổng\" ở dưới (chữ là ảnh nên không chọn / tìm kiếm được). Trước khi giao: tạo theo số dự kiến, số giao là \"—\". Sau khi giao: phản ánh số giao, sản phẩm thay thế, thiếu. Xuất xong: S207 (toast). Không tạo được: E306. 納品書 không xuất từ 注文履歴 (chỉ ở màn này)"]},
     ]},
    # ------------------------------------------------------------ 009 一部お届け済み
    {"id": "009", "code": "CW_DLV_001", "state": ["一部お届け済み（不足・関連するお届け）", "Giao thiếu (thiếu hàng, đơn liên quan)"],
     "url": "/corp/deliveries/DL-260914-0001", "setup": "", "full": True, "wait": 1200,
     "note": ["大阪支店 9/15 のお届け（箱数不足で 5食が足りず一部お届け済み）。見出しの下に不足の案内、差の列にマイナス、関連するお届けに残りの再配送（9/17）", "Đơn giao 大阪支店 9/15 (thiếu 1 thùng, thiếu 5 suất → giao thiếu). Dưới tiêu đề có cảnh báo thiếu, cột chênh lệch âm, đơn liên quan là giao bù phần còn lại (9/17)"],
     "items": [
         {"no": "18", "ja": "不足の案内", "vi": "Cảnh báo thiếu hàng", "sel": ".es-inline--warning", "kind": "label", "trig": "view", "err": ["W201"],
          "cond": ["お届け数が予定数より少ないお届け", "Đơn có số giao ít hơn số dự kiến"],
          "detail": ["W201。再配送の子のお届けがあれば「残りは {MM-DD（曜）} 残り {n}食の再配送 でお届けします。」、なければ「ESキッチンからご連絡します。」", "W201. Có đơn giao bù: \"残りは {MM-DD（曜）} 残り {n}食の再配送 でお届けします。\"; không có: \"ESキッチンからご連絡します。\""]},
         {"no": "18.1", "ja": "差（マイナス）", "vi": "Chênh lệch (âm)", "sel": "td.ua", "kind": "label", "trig": "view",
          "detail": ["足りなかった行は差「−{n}」を赤字", "Dòng thiếu: chênh lệch \"−{n}\" màu đỏ"]},
         {"no": "19", "ja": "関連するお届け", "vi": "Đơn giao liên quan", "sel": "h2::関連するお届け^2", "kind": "area", "trig": "view",
          "cond": ["再配送の子のお届けがあるとき、または自分が再配送の子のとき", "Khi có đơn giao bù, hoặc chính đơn này là đơn giao bù"],
          "detail": ["行：配送ID・「{MM-DD（曜）} 残り {n}食の再配送」（子）または「{MM-DD（曜）} 元のお届け」（親）・状態のバッジ。押せない（番号で探す）。取消した便は出さない（運営の状態名「取消」を法人に見せない）。", "Dòng: 配送ID, \"{MM-DD（曜）} 残り {n}食の再配送\" (con) hoặc \"{MM-DD（曜）} 元のお届け\" (cha), badge trạng thái. Không bấm được (tìm theo số)"]},
     ]},
    # ------------------------------------------------------------ 010 配送状況を確認中
    {"id": "010", "code": "CW_DLV_001", "state": ["配送状況を確認中", "Đang xác nhận tình trạng giao"],
     "url": "/corp/deliveries/DL-260918-0003", "login": "CU00031", "setup": "", "full": True, "wait": 1200,
     "note": ["株式会社ひかり物産（CU00031）でログイン。川崎工場 9/19 のお届けに未解決のトラブル（遅延）がある。見出しの下に確認中の案内、状態は「配送状況を確認中です」", "Đăng nhập 株式会社ひかり物産 (CU00031). Đơn 川崎工場 9/19 có sự cố chưa giải quyết (trễ). Dưới tiêu đề có hướng dẫn đang xác nhận, trạng thái \"配送状況を確認中です\""],
     "items": [
         {"no": "20", "ja": "確認中の案内", "vi": "Hướng dẫn đang xác nhận", "sel": ".es-inline--warning", "kind": "label", "trig": "view",
          "cond": ["未解決のトラブルがあるお届け（解決すると消える）", "Đơn có sự cố chưa giải quyết (giải quyết xong thì mất)"],
          "detail": ["「配送状況を確認しています」＋「このお届けで確認が必要なことがありました。ESキッチンからご連絡します。」。トラブルの中身（種類・メモ）は法人に出さない", "\"配送状況を確認しています\" + \"このお届けで確認が必要なことがありました。ESキッチンからご連絡します。\". Không hiện nội dung sự cố (loại, memo) cho pháp nhân"]},
     ]},
    # ------------------------------------------------------------ 011 資材便
    {"id": "011", "code": "CW_DLV_001", "state": ["資材便", "Đơn giao vật tư"],
     "url": "/corp/deliveries/DL-261005-0003", "setup": "", "full": True, "wait": 1200,
     "note": ["本社 10/07 の資材便（資材注文 MO-2610-0012・出荷待）。ご利用月は「資材」、温度帯・お届け方法は「資材 ・ 資材便」。商品の表の代わりに資材の案内", "Đơn vật tư 本社 10/07 (đơn 資材注文 MO-2610-0012, 出荷待). Tháng sử dụng \"資材\", cách giao \"資材 ・ 資材便\". Thay bảng sản phẩm bằng hướng dẫn vật tư"],
     "items": [
         {"no": "21", "ja": "資材のお届けの案内", "vi": "Hướng dẫn đơn vật tư", "sel": "h2::お届けする商品^2", "kind": "area", "trig": "view",
          "detail": ["「お届けする商品」の中に表を出さず「資材のお届けです（中身は資材のご注文をご覧ください）」。資材便は申請できない（「確定したお届けのため…」）。送り状はヤマト運輸（出荷後）", "Trong \"お届けする商品\" không hiện bảng mà ghi \"資材のお届けです（中身は資材のご注文をご覧ください）\". Đơn vật tư không xin đổi ngày (\"確定したお届けのため…\"). Phiếu gửi ヤマト運輸 (sau xuất kho)"]},
     ]},
    # ------------------------------------------------------------ 012 お届け日の変更を申請（モーダル・ステップ①）
    {"id": "012", "code": "CW_DLV_001", "state": ["お届け日の変更を申請（モーダル・ステップ①：日を選ぶ）", "Modal xin đổi ngày giao (bước ①: chọn ngày)"],
     "url": "/corp/deliveries/DL-261123-0001", "setup": _OPEN_MODAL, "full": True, "wait": 300,
     "note": ["001 で「お届け日の変更を申請」を押した。版1.1：2ステップのモーダル。ステップ①＝ご利用月（サイクル）の月のカレンダーから日を押す（選べる日を目立たせ、選べない日は灰色。1つ目＝第一希望、2つ目＝第二希望）か「希望日なし」→「次へ」。選べる範囲は同じ半分（前半＝第1・第2週／後半＝第3・第4週・#57）のまま", "Bấm \"お届け日の変更を申請\" ở 001. 版1.1: modal 2 bước. Bước ① = bấm ngày trên lịch tháng của tháng sử dụng (chu kỳ) (ngày chọn được nổi bật, không chọn được màu xám; bấm 1 = NV1, bấm 2 = NV2) hoặc 「希望日なし」 → 「次へ」. Phạm vi chọn vẫn là cùng nửa (nửa đầu = tuần 1-2 / nửa sau = tuần 3-4, #57). Code đang là 14 nút ngày + lý do trên 1 màn nên sẽ chụp lại"],
     "items": [
         {"no": "22", "ja": "お届け日の変更を申請（モーダル）", "vi": "Modal xin đổi ngày giao", "sel": ".es-dialog__panel", "kind": "modal", "trig": "show", "pattern": "P-FORM",
          "detail": ["見出し「お届け日の変更を申請 {配送ID}」。2ステップ：①日を選ぶ（カレンダー No.22.4 か「希望日なし」No.22.3 →「次へ」No.22.12） ②理由と確認（状態 015：No.22.14・22.7 →「申請する」No.22.10）。ステップの位置は No.22.11。「戻る」（No.22.13）で①に戻っても選んだ日は残る。入力を変えたあとに閉じる・外を押す・Esc は Q02（P-FORM）", "Tiêu đề \"お届け日の変更を申請 {配送ID}\". 2 bước: ① chọn ngày (lịch No.22.4 hoặc 「希望日なし」 No.22.3 → 「次へ」 No.22.12) ② lý do và xác nhận (trạng thái 015: No.22.14, 22.7 → 「申請する」 No.22.10). Vị trí bước ở No.22.11. Bấm 「戻る」 (No.22.13) về ① vẫn giữ ngày đã chọn. Đã nhập mà đóng / bấm ra ngoài / Esc thì hiện Q02 (P-FORM)"]},
         {"no": "22.1", "ja": "閉じる", "vi": "Đóng", "sel": ".es-dialog__close", "kind": "button", "trig": "click",
          "detail": ["キャンセルと同じ。送信中は閉じない", "Như キャンセル. Đang gửi thì không đóng"]},
         {"no": "22.2", "ja": "申請の案内", "vi": "Hướng dẫn", "sel": ".es-inline--info", "kind": "label", "trig": "view",
          "detail": ["「承認されるまでは、今のお届け日（{MM-DD}）のままです」＋「ESキッチンが確認して、承認・別の日のご提案・お断りのいずれかでお返事します（処理期限：ご注文・変更の締切 {MM-DD}）。同じ日に冷凍・常温のお届けがある場合は、一緒に動きます。」（#57）", "\"承認されるまでは、今のお届け日（{MM-DD}）のままです\" + \"ESキッチンが確認して、承認・別の日のご提案・お断りのいずれかでお返事します（処理期限：ご注文・変更の締切 {MM-DD}）。同じ日に冷凍・常温のお届けがある場合は、一緒に動きます。\" (#57)"]},
         {"no": "22.3", "ja": "希望日なし（ESキッチンにおまかせ）", "vi": "Không có nguyện vọng (nhờ ES Kitchen chọn)", "sel": "*::希望日なし^", "kind": "check", "trig": "check", "req": "－", "fid": "how",
          "len": "選択", "init": ["チェックなし（日を選ぶ）", "Không check (tự chọn ngày)"], "ex": ["チェックあり", "Check = không có nguyện vọng, nhờ ES Kitchen chọn ngày; không check = tự chọn ngày trên lịch"],
          "detail": ["カレンダーの上のチェック。チェックすると選んでいた日を外し、カレンダーの日を押せなくして、希望日なしで「次へ」に進める（#57）。チェックを外すとカレンダーが押せる", "Ô check phía trên lịch. Check thì bỏ ngày đã chọn, khóa các ngày trên lịch và bấm 「次へ」 được với không có nguyện vọng (#57). Bỏ check thì lịch bấm được lại"]},
         {"no": "22.4", "ja": "カレンダー（変更したい日）", "vi": "Lịch (ngày muốn đổi)", "sel": ".es-slot", "kind": "button", "trig": "click", "req": "条件付き", "err": ["E02", "E300", "E301", "E304", "E305"],
          "cond": ["「希望日なし」（No.22.3）でないとき必須（第一希望）。第二希望は任意", "Bắt buộc (NV1) khi không check 「希望日なし」 (No.22.3). NV2 tùy chọn"],
          "detail": ["見出し「変更したい日（1つ目を押すと第一希望、2つ目で第二希望）」。ご利用月（サイクル）の全日を月のカレンダー（月曜始まり・7列・週ごとの行）で出し、月の見出し「{n}月分（{A1}〜{最終日}）」。選べる日＝今のお届け日と同じ半分（前半＝第1・第2週／後半＝第3・第4週・#57）で、全社の休日マスタ・拠点のお届けできない曜日（配送ルート設定）・今のお届け日のどれでもない日（Q-D4）。選べる日は白地で太い数字・押せる、選べない日は灰色で押せない（ツールチップに理由：「別の半分」「休日」「受け取れない曜日」「今のお届け日」）。今のお届け日は枠を強調。1つ目＝第一希望（青）、2つ目＝第二希望（黒）、もう一度押すと外す。3つ目を押すと第二希望が入れ替わる。「次へ」での確認：未選択 E02、選べない日 E300、同じ日 E301。サーバー（申請する）：お届けできない日 E304・同じ半分の外 E305。日を選べる範囲がない（ご利用月の情報がない）ときはカレンダーを出さず「日を選べる範囲がありません。」「「希望日なし」で申請するか、ESキッチンへお問い合わせください。」を出す",
                     "Tiêu đề \"変更したい日（1つ目を押すと第一希望、2つ目で第二希望）\". Hiện toàn bộ ngày của tháng sử dụng (chu kỳ) dạng lịch tháng (bắt đầu thứ Hai, 7 cột, mỗi tuần 1 hàng), tiêu đề tháng \"{n}月分（{A1}〜{ngày cuối}）\". Ngày chọn được = cùng nửa với ngày giao hiện tại (nửa đầu = tuần 1-2 / nửa sau = tuần 3-4, #57) và không phải ngày nghỉ toàn công ty, thứ không giao được của 拠点 (cài đặt tuyến), ngày giao hiện tại (Q-D4). Ngày chọn được: nền trắng, số đậm, bấm được; ngày không chọn được: xám, khóa (tooltip ghi lý do: \"別の半分\", \"休日\", \"受け取れない曜日\", \"今のお届け日\"). Ngày giao hiện tại viền nổi bật. Bấm 1 = NV1 (xanh dương), bấm 2 = NV2 (đen), bấm lại để bỏ. Bấm ngày thứ 3 thì thay NV2. Kiểm tra khi 「次へ」: chưa chọn E02, ngày không chọn được E300, trùng ngày E301. Server (申請する): ngày không giao E304, ngoài cùng nửa E305. Không có phạm vi chọn ngày (không có thông tin tháng sử dụng): ẩn lịch và hiện \"日を選べる範囲がありません。\" (xin bằng 「希望日なし」 hoặc liên hệ ES Kitchen)"]},
         {"no": "22.5", "ja": "凡例", "vi": "Chú giải", "sel": ".es-dialog__panel .legend", "kind": "label", "trig": "view",
          "detail": ["第一希望（{MM-DD}）・第二希望（{MM-DD}）・今のお届け日・選べない日（灰色：別の半分・休日・お届けできない曜日）", "第一希望（{MM-DD}）, 第二希望（{MM-DD}）, ngày giao hiện tại, ngày không chọn được (xám: nửa khác, ngày nghỉ, thứ không giao được)"]},
         {"no": "22.6", "ja": "範囲の説明", "vi": "Giải thích phạm vi", "sel": ".note::同じご利用月の同じ半分", "kind": "label", "trig": "view",
          "detail": ["「同じご利用月の同じ半分の中で選べます。前半と後半をまたぐ日はESキッチンにご相談ください。」（#57）", "\"同じご利用月の同じ半分の中で選べます。前半と後半をまたぐ日はESキッチンにご相談ください。\" (#57)"]},
         {"no": "22.8", "ja": "対象のお届け", "vi": "Đơn giao đang xin đổi", "sel": ".es-dialog__foot b", "kind": "label", "trig": "view",
          "detail": ["「{拠点名} ・ {MM-DD（曜）}{温度帯} ・ {n}月分」。ステップ①・②の両方の下に出す", "\"{tên 拠点} ・ {MM-DD（thứ）}{温度帯} ・ {n}月分\". Hiện ở cuối cả bước ① và ②"]},
         {"no": "22.9", "ja": "キャンセル", "vi": "Hủy", "sel": ".es-dialog__foot button::キャンセル", "kind": "button", "trig": "click", "err": ["Q02"],
          "detail": ["閉じる。入力を変えていれば Q02。ステップ①・②の両方にある", "Đóng. Đã sửa nội dung thì hiện Q02. Có ở cả bước ① và ②"]},
         {"no": "22.11", "ja": "ステップの表示", "vi": "Hiển thị bước", "sel": ".es-dialog__panel .steps", "kind": "label", "trig": "view",
          "detail": ["見出しの下に「① 日を選ぶ → ② 理由と確認」。今のステップを強調", "Dưới tiêu đề: \"① 日を選ぶ → ② 理由と確認\". Bước hiện tại được tô đậm"]},
         {"no": "22.12", "ja": "次へ", "vi": "Tiếp theo", "sel": ".es-dialog__foot button::次へ", "kind": "button", "trig": "click", "err": ["E02", "E300", "E301"],
          "detail": ["ステップ①の右下の主ボタン。押すと日の確認（No.22.4：未選択 E02、選べない日 E300、同じ日 E301。「希望日なし」なら確認なし）をしてステップ②（状態 015）へ。エラーはカレンダーの下に出す", "Nút chính ở góc phải dưới bước ①. Bấm thì kiểm tra ngày (No.22.4: chưa chọn E02, ngày không chọn được E300, trùng ngày E301; 「希望日なし」 thì không kiểm tra) rồi sang bước ② (trạng thái 015). Lỗi hiện dưới lịch"]},
     ]},
    # ------------------------------------------------------------ 013 申請の入力エラー
    {"id": "013", "code": "CW_DLV_001", "state": ["申請の入力エラー", "Lỗi nhập của yêu cầu"],
     "url": "/corp/deliveries/DL-261123-0001", "setup": _OPEN_MODAL + "const b=[...document.querySelectorAll('button')].find(x=>x.textContent.includes('次へ'))||[...document.querySelectorAll('button')].find(x=>x.textContent.includes('申請する'));b&&b.click();await new Promise(r=>setTimeout(r,300));", "full": True, "wait": 300,
     "note": ["版1.1：ステップ①で日を選ばずに「次へ」を押した → 日のエラー（No.23）をカレンダーの下に出す。ステップ②で理由を空のまま「申請する」を押したときの理由のエラー（No.23.1）は状態 017", "版1.1: ở bước ① bấm 「次へ」 mà chưa chọn ngày → lỗi ngày (No.23) dưới lịch. Ở bước ② bấm 「申請する」 mà lý do trống → lỗi lý do (No.23.1) dưới ô, focus vào lý do (chụp riêng). Code đang hiện cả 2 lỗi trên 1 màn nên sẽ chụp lại"],
     "items": [
         {"no": "23", "ja": "エラー（変更したい日）", "vi": "Lỗi (ngày muốn đổi)", "sel": ".es-field__msg--error::変更したい日", "kind": "label", "trig": "show", "err": ["E02"],
          "detail": ["ステップ①で「次へ」を押したとき、E02（項目名＝変更したい日）をカレンダーの下に出す。日を押すか「希望日なし」をチェックすると消える", "Khi bấm 「次へ」 ở bước ①: E02 (tên mục = 変更したい日) dưới lịch. Bấm chọn ngày hoặc check 「希望日なし」 thì mất"]},
     ]},
    # ------------------------------------------------------------ 014 見つからない
    {"id": "014", "code": "CW_DLV_001", "state": ["見つからない（他拠点の ID）", "Không tìm thấy (ID của 拠点 khác)"],
     "url": "/corp/deliveries/DL-261110-0001", "login": "CU00871", "setup": "", "full": True, "wait": 1200,
     "note": ["拠点アカウント（大阪支店 CU00871）で本社のお届け DL-261110-0001 を開いた。見られる範囲の外・ない番号は同じ表示（決定 #55：API で絞る）", "Tài khoản 拠点 (大阪支店 CU00871) mở đơn của 本社 DL-261110-0001. Ngoài phạm vi được xem và số không tồn tại hiện giống nhau (quyết định #55: lọc ở API)"],
     "items": [
         {"no": "24", "ja": "見つからない表示", "vi": "Hiển thị không tìm thấy", "sel": ".es-empty", "kind": "label", "trig": "view", "err": ["I204", "E346"],
          "detail": ["I204 と戻るリンク（開いた元に従う：No.24.1）。他拠点のものかどうかは分からないようにする（同じ文）。取消した便・壊れた URL も同じ。通信に失敗して読み込めなかったときは I204 ではなく E346（「読み込めませんでした。時間をおいて再度お試しください。」＋「再読み込み」ボタン）", "I204 và link quay lại (theo nơi mở: No.24.1). Không cho biết có phải của 拠点 khác hay không (cùng câu). Đơn đã hủy và URL hỏng cũng vậy. Khi lỗi mạng không tải được thì hiện E346 (\"読み込めませんでした。時間をおいて再度お試しください。\" + nút 「再読み込み」) thay vì I204"]},
         {"no": "24.1", "ja": "カレンダーへ戻る", "vi": "Về lịch", "sel": ".es-empty a::カレンダーへ戻る", "kind": "link", "trig": "click",
          "detail": ["開いた元へ（ホーム：/corp、申請の一覧：「申請の一覧へ戻る」→ /corp/requests、お知らせ一覧：「お知らせ一覧へ戻る」→ /corp/news）。文字は No.1.5 と同じ", "Về nơi mở (trang chủ: /corp; danh sách yêu cầu: \"申請の一覧へ戻る\" → /corp/requests; danh sách thông báo: \"お知らせ一覧へ戻る\" → /corp/news). Chữ như No.1.5"]},
     ]},
    # ------------------------------------------------------------ 015 お届け日の変更を申請（モーダル・ステップ②）
    {"id": "015", "code": "CW_DLV_001", "state": ["お届け日の変更を申請（モーダル・ステップ②：理由と確認）", "Modal xin đổi ngày giao (bước ②: lý do và xác nhận)"],
     "url": "/corp/deliveries/DL-261123-0001", "setup": _OPEN_MODAL + "const d=[...document.querySelectorAll('.es-slot')].filter(x=>!x.disabled);d[0]&&d[0].click();await new Promise(r=>setTimeout(r,300));d[1]&&d[1].click();await new Promise(r=>setTimeout(r,300));const b=[...document.querySelectorAll('button')].find(x=>x.textContent.includes('次へ'));b&&b.click();await new Promise(r=>setTimeout(r,400));", "full": True, "wait": 300,
     "note": ["版1.1：012 で日を2つ選んで「次へ」を押した。ステップ②＝選んだ日の確認（今のお届け日 → 第一希望・第二希望）と理由の入力 →「申請する」", "版1.1: ở 012 chọn 2 ngày rồi bấm 「次へ」. Bước ② = xác nhận ngày đã chọn (ngày hiện tại → NV1, NV2) và nhập lý do → 「申請する」. Code chưa có (1 màn) nên chụp sau khi sửa code"],
     "items": [
         {"no": "22.14", "ja": "選んだ日の確認", "vi": "Xác nhận ngày đã chọn", "sel": ".es-dialog__panel .confirm", "kind": "label", "trig": "view",
          "detail": ["ステップ②の上の枠：「今のお届け日 {YYYY-MM-DD（曜）} → 第一希望 {YYYY-MM-DD（曜）}・第二希望 {YYYY-MM-DD（曜）}」（第二希望がなければ省く。希望日なしは「希望日なし（ESキッチンにおまかせ）」）＋「処理期限：ご注文・変更の締切 {MM-DD}」。日を変えたいときは「戻る」（No.22.13）", "Khung trên cùng của bước ②: \"今のお届け日 {YYYY-MM-DD（thứ）} → 第一希望 {YYYY-MM-DD（thứ）}・第二希望 {YYYY-MM-DD（thứ）}\" (không có NV2 thì bỏ; không có nguyện vọng: \"希望日なし（ESキッチンにおまかせ）\") + \"処理期限：ご注文・変更の締切 {MM-DD}\". Muốn đổi ngày thì bấm 「戻る」 (No.22.13)"]},
         {"no": "22.7", "ja": "理由", "vi": "Lý do", "sel": "#r1", "kind": "textarea", "trig": "input", "req": "○", "fid": "r1",
          "len": "文字列 500", "init": ["（空）", "(trống)"], "ex": ["11-24 は全館の設備点検で、荷受けができないため", "Lý do xin đổi ngày (văn bản tự do, nhiều dòng, tối đa 500 ký tự)"],
          "valid": ["必須（空白だけは不可）。500文字まで（入力は止めず、超えて「申請する」を押すと E04）。絵文字不可（E13）", "Bắt buộc (chỉ khoảng trắng không được). Tối đa 500 ký tự (không chặn khi gõ, quá thì bấm 「申請する」 sẽ hiện E04). Không emoji (E13)"], "err": ["E01", "E04", "E13"],
          "detail": ["ステップ②の入力欄（複数行）。プレースホルダー「例）{MM-DD} は全館の設備点検で、荷受けができないため」。補足「ESキッチンからお電話で確認することがあります（申請者：{メイン担当者の氏名} ・ {電話}）」。理由は運営Web の申請と申請の履歴の表（No.8.6）に出る。「戻る」で①に戻っても入力は残る", "Ô nhập ở bước ② (nhiều dòng). Placeholder \"例）{MM-DD} は全館の設備点検で、荷受けができないため\". Ghi chú \"ESキッチンからお電話で確認することがあります（申請者：{tên người phụ trách chính} ・ {điện thoại}）\". Lý do hiện ở yêu cầu trên 運営Web và bảng lịch sử (No.8.6). Bấm 「戻る」 về ① vẫn giữ nội dung"]},
         {"no": "22.13", "ja": "戻る", "vi": "Quay lại", "sel": ".es-dialog__foot button::戻る", "kind": "button", "trig": "click",
          "detail": ["ステップ②の左下の副ボタン。ステップ①に戻る（選んだ日・理由は残る）", "Nút phụ ở góc trái dưới bước ②. Về bước ① (giữ ngày đã chọn và lý do)"]},
         {"no": "22.10", "ja": "申請する", "vi": "Gửi yêu cầu", "sel": "button::申請する", "kind": "button", "trig": "click", "err": ["S200", "E302", "E303", "E30"],
          "detail": ["ステップ②の右下の主ボタン。理由の確認（No.22.7）→ 申請番号 DD-YYYYMMDD-NNNN で申請を作り、お届けの変更申請の状態を「申請中」にし、運営（配送担当）にお知らせ。モーダルを閉じて S200。押したら無効（二重送信を防ぐ）。サーバーで申請できない：E302、申請中あり：E303、日の確認：E304・E305（No.22.4）、通信：E30", "Nút chính ở góc phải dưới bước ②. Kiểm tra lý do (No.22.7) → tạo yêu cầu số DD-YYYYMMDD-NNNN, trạng thái đổi ngày của đơn thành \"申請中\", thông báo cho vận hành (phụ trách giao). Đóng modal, hiện S200. Khóa nút sau khi bấm. Server: không xin được E302, đang có yêu cầu E303, kiểm tra ngày E304, E305 (No.22.4), lỗi mạng E30"]},
     ]},
    # ------------------------------------------------------------ 016 納品書（PDF）の内容
    {"id": "016", "code": "CW_DLV_001", "state": ["納品書（PDF）の内容", "Nội dung 納品書 (PDF)"],
     "url": "/corp/deliveries/DL-261012-0011", "setup": "", "full": True, "wait": 1200,
     "note": ["版1.1：「納品書（PDF）」（No.17）で出る便ごとの納品書の形（台帳 E「納品書のテンプレート」）。A4 縦・金額なし。画面ではなく PDF なので、番号は「納品書（PDF）」のボタンに置き、項目定義で中身を書く。現行の納品書との差はお客様（運営）に確認（OPEN）", "版1.1: dạng 納品書 từng chuyến xuất từ 「納品書（PDF）」 (No.17) (台帳 E 「納品書のテンプレート」). A4 dọc, không có tiền. Là PDF chứ không phải màn hình nên số đặt ở nút 「納品書（PDF）」, nội dung ghi ở định nghĩa mục. Khác biệt với phiếu hiện hành: hỏi khách hàng (vận hành) (OPEN)"],
     "items": [
         {"no": "25", "ja": "納品書（PDF・A4 縦）", "vi": "納品書 (PDF, A4 dọc)", "sel": "a::納品書（PDF）", "kind": "area", "trig": "view",
          "detail": ["便ごとの納品書。A4 縦・1便＝1通。上から 見出し（No.25.1）／宛先（25.2）・発行元（25.3）／お届け日・温度帯・お届け方法（25.4）／明細の表（25.5）／数量の合計（25.6）／注記（25.7）／ページ番号（25.8）。金額（単価・金額・税）は載せない（25.9）。資材便の納品書は作らない。注文履歴の月・拠点ごとの納品書は、この便ごとの表を縦に並べ、最後に月の合計を出す", "納品書 từng chuyến. A4 dọc, 1 chuyến = 1 bản. Từ trên xuống: tiêu đề (No.25.1) / người nhận (25.2), nơi phát hành (25.3) / ngày giao, 温度帯, cách giao (25.4) / bảng chi tiết (25.5) / tổng số lượng (25.6) / chú thích (25.7) / số trang (25.8). Không ghi tiền (đơn giá, thành tiền, thuế) (25.9). Không tạo 納品書 cho chuyến vật tư. 納品書 theo tháng, 拠点 ở 注文履歴 xếp dọc các bảng chuyến này và tổng tháng ở cuối"],
          "open": ["現行の納品書との差（運営・お客様に確認）：今お客様に渡している納品書の項目・並び・ロゴ・社印と、この形との違い", "Khác biệt với 納品書 hiện hành (hỏi vận hành / khách hàng): mục, thứ tự, logo, con dấu của phiếu đang phát cho khách so với dạng này"], "ask": "お客様（運営）"},
         {"no": "25.1", "ja": "見出し", "vi": "Tiêu đề phiếu", "sel": "a::納品書（PDF）", "kind": "label", "trig": "view",
          "detail": ["中央に「納品書」。右上に「発行日 YYYY-MM-DD」（PDF を出した日）と「納品書番号 {配送ID}」（お届け番号と同じ。再配送の子は末尾 -1 のまま）", "Giữa: \"納品書\". Góc phải trên: \"発行日 YYYY-MM-DD\" (ngày xuất PDF) và \"納品書番号 {配送ID}\" (= số đơn giao; chuyến giao bù giữ đuôi -1)"]},
         {"no": "25.2", "ja": "宛先", "vi": "Người nhận", "sel": "a::納品書（PDF）", "kind": "label", "trig": "view",
          "detail": ["左上：「{法人名}」「{拠点名} 御中」「〒{郵便番号} {住所}」（拠点の納品先住所）", "Góc trái trên: \"{法人名}\", \"{拠点名} 御中\", \"〒{mã bưu chính} {địa chỉ}\" (địa chỉ giao của 拠点)"]},
         {"no": "25.3", "ja": "発行元", "vi": "Nơi phát hành", "sel": "a::納品書（PDF）", "kind": "label", "trig": "view",
          "detail": ["右上（見出しの下）：ESキッチンの会社名・住所・電話番号（会社マスタの値＝共通データのESキッチンの会社。旧・月ごとの納品書と同じ元。マスタにないときだけ見本の値）", "Góc phải trên (dưới tiêu đề): tên công ty, địa chỉ, điện thoại của ES Kitchen (giá trị trong master công ty = công ty ESキッチン trong dữ liệu chung; cùng nguồn với 納品書 theo tháng cũ. Chỉ khi master không có mới dùng giá trị mẫu)"]},
         {"no": "25.4", "ja": "お届け日・温度帯・お届け方法", "vi": "Ngày giao, 温度帯, cách giao", "sel": "a::納品書（PDF）", "kind": "label", "trig": "view",
          "detail": ["「お届け日 YYYY-MM-DD（曜）」「{温度帯} ・ {配送区分}」（No.2.4 と同じ文字）「ご利用月 {n}月分」。お届け前に出したときは「お届け予定日」", "\"お届け日 YYYY-MM-DD（thứ）\", \"{温度帯} ・ {配送区分}\" (cùng chữ với No.2.4), \"ご利用月 {n}月分\". Xuất trước khi giao thì ghi \"お届け予定日\""]},
         {"no": "25.5", "ja": "明細", "vi": "Chi tiết", "sel": "a::納品書（PDF）", "kind": "table", "trig": "view",
          "detail": ["列：No・商品名・ご注文数・お届け数・備考（No.25.5.1〜25.5.5）。並びは画面の商品の表（No.12）と同じ（代替品・除外の行は最後）。1ページに収まらなければ改ページし、見出しの行を各ページに繰り返す（REQ-DL-316）", "Cột: No, 商品名, ご注文数, お届け数, 備考 (No.25.5.1〜25.5.5). Thứ tự như bảng sản phẩm trên màn hình (No.12) (dòng thay thế / loại trừ ở cuối). Không vừa 1 trang thì sang trang, lặp dòng tiêu đề mỗi trang (REQ-DL-316)"]},
         {"no": "25.5.1", "ja": "No", "vi": "No", "sel": "a::納品書（PDF）", "kind": "label", "trig": "view",
          "detail": ["1 からの連番", "Số thứ tự từ 1"]},
         {"no": "25.5.2", "ja": "商品名", "vi": "Tên sản phẩm", "sel": "a::納品書（PDF）", "kind": "label", "trig": "view",
          "detail": ["お届けしたときの商品名（No.3.1 と同じ）。代替品の行は実際に渡した商品名", "Tên sản phẩm lúc giao (như No.3.1). Dòng thay thế ghi tên sản phẩm thực tế đã giao"]},
         {"no": "25.5.3", "ja": "ご注文数", "vi": "Số lượng đặt", "sel": "a::納品書（PDF）", "kind": "label", "trig": "view",
          "detail": ["「{n}」（単位は列の見出しに「（個）」）。右寄せ", "\"{n}\" (đơn vị \"（個）\" ghi ở tiêu đề cột). Căn phải"]},
         {"no": "25.5.4", "ja": "お届け数", "vi": "Số lượng giao", "sel": "a::納品書（PDF）", "kind": "label", "trig": "view",
          "detail": ["お届け後「{n}」、お届け前「—」。右寄せ。不足の行は太字", "Sau khi giao \"{n}\", trước khi giao \"—\". Căn phải. Dòng thiếu in đậm"]},
         {"no": "25.5.5", "ja": "備考", "vi": "Ghi chú", "sel": "a::納品書（PDF）", "kind": "label", "trig": "view",
          "detail": ["代替品「代替品（元：{元の商品名}）」・補償「補償（0円）」・不足「不足 {n}個」（画面の備考 No.3.5 と同じ内容。金額は補償の「0円」だけ）", "Thay thế: \"代替品（元：{tên gốc}）\", bồi thường: \"補償（0円）\", thiếu: \"不足 {n}個\" (cùng nội dung với 備考 No.3.5 trên màn hình; tiền chỉ có \"0円\" của bồi thường)"]},
         {"no": "25.6", "ja": "数量の合計", "vi": "Tổng số lượng", "sel": "a::納品書（PDF）", "kind": "label", "trig": "view",
          "detail": ["表の最後の行「合計」：ご注文数の合計・お届け数の合計（個）。金額の合計は出さない", "Dòng cuối bảng \"合計\": tổng số đặt, tổng số giao (個). Không có tổng tiền"]},
         {"no": "25.7", "ja": "注記", "vi": "Chú thích", "sel": "a::納品書（PDF）", "kind": "label", "trig": "view",
          "detail": ["表の下。該当するときだけ：代替品「※ 商品の不良のため、{元の商品名} は {代替品名} でお届けしました。ご請求は元の商品の料金です。」／不足「※ {n}個が足りませんでした。残りは {MM-DD} にお届けします。」（再配送がなければ「ESキッチンからご連絡します。」）／再配送の子「※ {MM-DD} のお届け（{元の配送ID}）の残りのお届けです。」", "Dưới bảng, chỉ khi có: thay thế \"※ 商品の不良のため、{tên gốc} は {tên thay thế} でお届けしました。ご請求は元の商品の料金です。\" / thiếu \"※ {n}個が足りませんでした。残りは {MM-DD} にお届けします。\" (không có giao bù: \"ESキッチンからご連絡します。\") / chuyến giao bù \"※ {MM-DD} のお届け（{配送ID gốc}）の残りのお届けです。\""]},
         {"no": "25.8", "ja": "ページ番号", "vi": "Số trang", "sel": "a::納品書（PDF）", "kind": "label", "trig": "view",
          "detail": ["各ページの下中央「{n} / {総ページ}」。2ページ目からは表の見出しの行（No.25.5）を繰り返す（見出し No.25.1 は繰り返さない）", "Giữa cuối mỗi trang \"{n} / {tổng}\". Từ trang 2 lặp lại dòng tiêu đề của bảng (No.25.5) (không lặp tiêu đề No.25.1)"]},
         {"no": "25.9", "ja": "金額（載せない）", "vi": "Tiền (không ghi)", "sel": "a::納品書（PDF）", "kind": "label", "trig": "view",
          "detail": ["単価・金額・税・合計金額は載せない（台帳 E「納品書のテンプレート」）。金額は請求書で", "Không ghi đơn giá, thành tiền, thuế, tổng tiền (台帳 E 「納品書のテンプレート」). Tiền xem ở 請求書"]},
     ]},
    # ------------------------------------------------------------ 017 申請の入力エラー（ステップ②・理由）
    {"id": "017", "code": "CW_DLV_001", "state": ["申請の入力エラー（ステップ②：理由が空）", "Lỗi nhập của yêu cầu (bước ②: lý do trống)"],
     "url": "/corp/deliveries/DL-261123-0001", "setup": _OPEN_MODAL + "const d=[...document.querySelectorAll('.es-slot')].filter(x=>!x.disabled);d[0]&&d[0].click();await new Promise(r=>setTimeout(r,300));d[1]&&d[1].click();await new Promise(r=>setTimeout(r,300));const b=[...document.querySelectorAll('button')].find(x=>x.textContent.includes('次へ'));b&&b.click();await new Promise(r=>setTimeout(r,400));const g=[...document.querySelectorAll('button')].find(x=>x.textContent.includes('申請する'));g&&g.click();await new Promise(r=>setTimeout(r,300));", "full": True, "wait": 300,
     "note": ["版1.4：012 で日を2つ選んで「次へ」→ ステップ②で理由を空のまま「申請する」を押した。理由のエラー（No.23.1）を欄の下に出し、欄は赤枠、理由にフォーカス。ステップ①の日のエラー（No.23）は状態 013", "版1.4: ở 012 chọn 2 ngày → 「次へ」 → ở bước ② bấm 「申請する」 khi lý do trống. Lỗi lý do (No.23.1) hiện dưới ô, ô viền đỏ, focus vào lý do. Lỗi ngày ở bước ① (No.23) xem trạng thái 013"],
     "items": [
         {"no": "23.1", "ja": "エラー（理由）", "vi": "Lỗi (lý do)", "sel": ".es-field__msg--error::理由", "kind": "label", "trig": "show", "err": ["E01"],
          "detail": ["ステップ②で「申請する」を押したとき、E01（項目名＝理由）。欄は赤枠。入力すると消える", "Khi bấm 「申請する」 ở bước ②: E01 (tên mục = 理由). Ô viền đỏ. Nhập thì mất"]},
     ]},
    # ------------------------------------------------------------ 018 解約後（参照のみ）・別の日のご提案
    {"id": "018", "code": "CW_DLV_001", "state": ["解約後（参照のみ）：別の日のご提案", "Sau giải ước (chỉ xem): đề xuất ngày khác"],
     "url": "/corp/deliveries/DL-261109-0001", "setup": _SET_RO, "full": True, "wait": 600,
     "note": ["004 と同じお届け（大阪支店 11/10・ESキッチンが 11/13 を提案）を、デモ帯の「デモの表示」を「解約後（参照のみ）」にして開いた（版1.4）。見出しの下に黄色い参照のみの帯。申請の枠には「お断りする」「{日} で受ける」を出さず、ご返事できない旨だけ出す。見出しの「お届け日の変更を申請」も出ない。ほかの状態は同じタブで参照のみのままになるため、解約後の状態は最後に撮る", "Mở cùng đơn với 004 (大阪支店 11/10, ES Kitchen đề xuất 11/13) sau khi chọn 「デモの表示」 ở thanh demo là 「解約後（参照のみ）」 (版1.4). Dưới tiêu đề có dải vàng \"chỉ xem\". Khung yêu cầu không hiện \"お断りする\" \"{日} で受ける\", chỉ ghi không trả lời được. Nút 「お届け日の変更を申請」 ở tiêu đề cũng không hiện. Các trạng thái khác cùng tab vẫn ở chế độ chỉ xem nên trạng thái sau giải ước chụp cuối cùng"],
     "items": [
         {"no": "1.7", "ja": "参照のみの帯", "vi": "Dải \"chỉ xem\"", "sel": ".es-inline--warning::ご契約は", "kind": "label", "trig": "view",
          "cond": ["解約後（参照のみ）のアカウントだけ", "Chỉ tài khoản sau giải ước (chỉ xem)"],
          "detail": ["見出しの下の黄色い帯（ほかの法人Web の画面と同じ文）。見出し：「ご契約は {終了日} に終了しました。{入金期限}（最後のご請求の入金期限）まで参照のみでご利用いただけます。」。本文：「参照のみの期間は、お届け日の変更の申請・ご提案へのご返事はできません。お届けの確認はできます。」。お届けの確認・納品書（PDF）は使える", "Dải vàng dưới tiêu đề (cùng câu với các màn 法人Web khác). Tiêu đề: \"ご契約は {終了日} に終了しました。{hạn thanh toán}（最後のご請求の入金期限）まで参照のみでご利用いただけます。\". Nội dung: \"参照のみの期間は、お届け日の変更の申請・ご提案へのご返事はできません。お届けの確認はできます。\". Vẫn xem được đơn giao và xuất 納品書 (PDF)"]},
         {"no": "10.8", "ja": "ご返事の案内（解約後）", "vi": "Hướng dẫn trả lời (sau giải ước)", "sel": ".crb__f .note", "kind": "label", "trig": "view",
          "cond": ["別の日のご提案（申請の枠）がある解約後（参照のみ）のアカウント", "Tài khoản sau giải ước (chỉ xem) có đề xuất ngày khác (khung yêu cầu)"],
          "detail": ["「ご契約が終了しているため、この画面からはご返事できません。ESキッチンへお問い合わせください。」。「お断りする」「{日} で受ける」は出さない。サーバーも、受ける・お断りするを断る（E345）", "\"ご契約が終了しているため、この画面からはご返事できません。ESキッチンへお問い合わせください。\". Không hiện \"お断りする\" \"{日} で受ける\". Server cũng từ chối nhận / từ chối đề xuất (E345)"]},
     ]},
    # ------------------------------------------------------------ 019 解約後（参照のみ）・申請できる予定
    {"id": "019", "code": "CW_DLV_001", "state": ["解約後（参照のみ）：予定（申請できない）", "Sau giải ước (chỉ xem): dự kiến (không xin đổi được)"],
     "url": "/corp/deliveries/DL-261123-0001", "setup": "", "full": True, "wait": 600,
     "note": ["001 と同じお届け（大阪支店 11/24・予定）を、018 のまま参照のみで開いた（版1.4）。ふつうは「お届け日の変更を申請」のボタンが出るお届けだが、見出しにも枠にも出さず、理由を常時表示する", "Mở cùng đơn với 001 (大阪支店 11/24, dự kiến) khi vẫn ở chế độ chỉ xem như 018 (版1.4). Đơn bình thường có nút 「お届け日の変更を申請」 nhưng ở đây không hiện ở tiêu đề lẫn khung, luôn hiện lý do"],
     "items": [
         {"no": "6.2", "ja": "申請の案内（解約後）", "vi": "Hướng dẫn xin đổi (sau giải ước)", "sel": ".note::ご契約が終了しているため", "kind": "label", "trig": "view",
          "cond": ["予定のお届けで、解約後（参照のみ）のアカウント", "Đơn dự kiến, tài khoản sau giải ước (chỉ xem)"],
          "detail": ["「ご契約が終了しているため、お届け日の変更は申請できません。」。ボタンは出ない（見出し・カード とも）。サーバーも申請を断る（E345）", "\"ご契約が終了しているため、お届け日の変更は申請できません。\". Không có nút (cả tiêu đề lẫn thẻ). Server cũng từ chối yêu cầu (E345)"]},
     ]},
    # ------------------------------------------------------------ 020 申請の一覧から開いた（サイドメニュー・パンくず・戻る）
    {"id": "020", "code": "CW_DLV_001", "state": ["申請の一覧から開いた", "Mở từ danh sách yêu cầu"],
     "url": "/corp/deliveries/DL-261109-0001?from=requests", "setup": _SET_DATA, "full": True, "wait": 600,
     "note": ["申請 ＞ お届け日の変更の一覧（/corp/requests）の申請番号から開いた（?from=requests・版1.4）。サイドメニューは「申請 ＞ お届け日の変更」を光らせる（ホームではない）。パンくずは「申請 ／ お届け日の変更申請 ／ お届け詳細」、戻るボタンは「申請の一覧へ戻る」。018・019 で参照のみにしたデモの表示を「アカウントの状態のまま」に戻してから撮る", "Mở từ số yêu cầu ở danh sách 申請 ＞ お届け日の変更 (/corp/requests) (?from=requests, 版1.4). Menu bên sáng \"申請 ＞ お届け日の変更\" (không phải trang chủ). Breadcrumb \"申請 ／ お届け日の変更申請 ／ お届け詳細\", nút quay lại \"申請の一覧へ戻る\". Đưa 「デモの表示」 đã đặt chỉ xem ở 018, 019 về 「アカウントの状態のまま」 rồi mới chụp"],
     "items": [
         {"no": "1.8", "ja": "サイドメニュー（開いた元の項目）", "vi": "Menu bên (mục nơi mở)", "sel": ".es-subitem.is-active", "kind": "label", "trig": "view",
          "detail": ["開いた元の項目を光らせる。ホームから（?from=home・なし・不明）：「ホーム」。申請の一覧から（?from=requests）：「申請 ＞ お届け日の変更」（グループを開き、子の「お届け日の変更」を光らせる）。お知らせ一覧から（?from=news）：「ホーム」（お知らせはメニューにないため、お知らせ一覧と同じ）", "Sáng mục nơi mở ra. Từ trang chủ (?from=home・không có・không rõ): \"ホーム\". Từ danh sách yêu cầu (?from=requests): \"申請 ＞ お届け日の変更\" (mở nhóm, sáng mục con \"お届け日の変更\"). Từ danh sách thông báo (?from=news): \"ホーム\" (thông báo không có trong menu nên giống danh sách thông báo)"]},
     ]},
]
