# -*- coding: utf-8 -*-
"""
法人Web ホーム（CW_HOME）。元は本物の Web（app/corp/page.tsx・lib/corp/areas/corp-delivery.ts・lib/corp/delivery/*）。
決定の正：docs/決定台帳.md E（2026-10-05 法人Web ホームの細かい点・ご注文がまだの警告・名前の使い分け・解約後にできること）、
決定_v2.3追補_法人ホームカレンダー_20260929（#54〜#62）。版 1.1（2026-10-05）：台帳 E「法人Web 版 1.0 のレビュー（ホーム・お届け詳細）」①〜④（受付簿 No.153）。版 1.4（2026-10-05）：台帳「法人Web 版 1.1 のレビュー 2回目」（受付簿 No.157）＝お届け詳細へ開いた元・解約後（参照のみ）・見本データ・不具合修正。確認メモ：docs/05_画面設計書/確認メモ_法人A_注文・在庫・請求.md 1-1・Q-C1〜C3・Q-H1〜H3・宿題 H1〜H6・C1。
共通の枠（サイドメニュー・ヘッダー・アカウントメニュー・パスワード変更・ログアウト）はこの機能に書かない（法人B ログイン／共通の機能）。
"""

TITLE = ["ホーム（CW_HOME）", "Trang chủ (CW_HOME)"]
SHEET = ["ホーム", "Trang chủ"]
BASENAME = "画面設計書_CW_HOME_ホーム"
IMG_PREFIX = "CW_HOME"
OUT_DIR = "CW_HOME_ホーム"
CODE_NOTE = ["Screen Code は台帳 E 2026-10-05 の決まり：CW_<機能略>_<3桁>", "Screen Code theo 台帳 E 2026-10-05: CW_<機能略>_<3 chữ số>"]
SITE = "corp"
SYSTEM = {"ja": "法人Web", "vi": "Web pháp nhân (法人Web)"}
AUTHOR = "Claude／確認：hong"
CREATED = "2026-10-05"
DEMO_FILE = "http://localhost:3000"
LOGIN = {"site": "corp", "loginId": "CU00001"}

DECISIONS = [
    {"date": "2026-10-05", "target": "CW_HOME_001 No.3.6・No.5.2",
     "q": ["画面の文言で「ESキッチン」と「ES STATION」のどちらを使うか", "Trong câu chữ màn hình dùng \"ESキッチン\" hay \"ES STATION\""],
     "a": ["「ESキッチン」＝お客様（運営会社）の名前、「ES STATION」＝システムの名前。運営へ連絡する文は「ESキッチンへお問い合わせください」。「ESSTATION」「ESステーション」は使わない",
           "\"ESキッチン\" = tên công ty vận hành (khách hàng), \"ES STATION\" = tên hệ thống. Câu liên hệ vận hành: \"ESキッチンへお問い合わせください\". Không dùng \"ESSTATION\", \"ESステーション\""],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-C1）"},
    {"date": "2026-10-05", "target": "CW_HOME_001 No.2.5",
     "q": ["解約後（参照のみ）のアカウントは資材注文・お届け日の変更申請ができるか", "Tài khoản sau giải ước (chỉ xem) có đặt vật tư / xin đổi ngày giao được không"],
     "a": ["できない（棚卸報告だけできる）。ボタンを出さない", "Không (chỉ 棚卸報告 làm được). Không hiện nút"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-C2）"},
    {"date": "2026-10-05", "target": "CW_HOME_001 No.2.4",
     "q": ["ホームの「CSV出力」（お届け・18列）をこのまま置くか", "Giữ nút \"CSV出力\" (giao hàng, 18 cột) trên trang chủ không"],
     "a": ["置く（CSV入出力_定義どおり。ホーム・棚卸報告・請求書・注文履歴）。列は今の18列のまま → 2026-10-05 版1.0レビューで置き換え（ホームには置かない。下の行）", "Giữ (theo CSV入出力_定義: trang chủ, 棚卸報告, 請求書, 注文履歴). 18 cột giữ nguyên → bị thay thế ở review 版1.0 2026-10-05 (không đặt ở trang chủ; xem dòng dưới)"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-C3）"},
    {"date": "2026-10-05", "target": "CW_HOME_001 No.2.3",
     "q": ["見出しの「最終更新 {日付} 03:00」を出すか", "Có hiện \"最終更新 {日付} 03:00\" ở tiêu đề không"],
     "a": ["出さない（データは都度の表示。ホームに 03:00 のバッチはない）", "Không hiện (dữ liệu hiển thị theo thời gian thực; không có batch 03:00 cho trang chủ)"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-H1）"},
    {"date": "2026-10-05", "target": "CW_HOME_001 No.3.8・No.14",
     "q": ["同じ日に複数のお届けがあるマス（法人アカウント・全拠点）を押したときの動き", "Bấm ô ngày có nhiều đơn giao (tài khoản pháp nhân, tất cả 拠点) thì làm gì"],
     "a": ["その日のお届けの一覧（拠点・温度帯・状態）を出し、選んで詳細へ", "Hiện danh sách đơn giao trong ngày (拠点, 温度帯, trạng thái), chọn 1 để mở chi tiết"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-H2）"},
    {"date": "2026-10-05", "target": "CW_HOME_001 No.5・No.11",
     "q": ["「確認が必要なお届け」に出す種類（決定 #58 の4種類か、コードの2種類か）", "\"確認が必要なお届け\" gồm 4 loại theo quyết định #58 hay 2 loại như code"],
     "a": ["4種類：①別の日のご提案 ②届かなかった・遅れたお届け ③申請の結果（14日間） ④申請できる予定（締切の3週間前から）",
           "4 loại: ① đề xuất ngày khác ② giao thiếu / trễ ③ kết quả yêu cầu (14 ngày) ④ lịch có thể xin đổi (từ 3 tuần trước hạn)"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-H3）"},
    # ---- 版 1.0 のレビュー（hong 回答 2026-10-05・台帳 E「法人Web 版 1.0 のレビュー（ホーム・お届け詳細）」）
    {"date": "2026-10-05", "target": "CW_HOME_001 No.3・No.4・No.17",
     "q": ["カレンダーとお知らせの枠の幅（コードはカレンダーが広い）", "Độ rộng khung lịch và khung thông báo (code: lịch rộng hơn)"],
     "a": ["半々にする。「広く／狭く」のボタンで幅を切り替えられ、利用者ごとに覚える（ブラウザの localStorage）", "Chia đôi. Có nút 「広く／狭く」 để đổi độ rộng, nhớ theo từng người dùng (localStorage của trình duyệt)"],
     "src": "hong 回答 2026-10-05 版1.0レビュー"},
    {"date": "2026-10-05", "target": "CW_HOME_001 No.2.4・No.16",
     "q": ["ホームに「CSV出力」を置くか（Q-C3 では置く）", "Có đặt 「CSV出力」 ở trang chủ không (Q-C3: có)"],
     "a": ["置かない（Q-C3 を置き換え）。CSV出力は棚卸報告・請求書・注文履歴だけ", "Không đặt (thay thế Q-C3). CSV出力 chỉ ở 棚卸報告, 請求書, 注文履歴"],
     "src": "hong 回答 2026-10-05 版1.0レビュー"},
    {"date": "2026-10-05", "target": "CW_HOME_001 No.2.5",
     "q": ["ホームに「資材を注文」のボタンを置くか（B-6 では一部に出す）", "Có đặt nút 「資材を注文」 ở trang chủ không (B-6: hiện với một số tài khoản)"],
     "a": ["置かない（B-6 を置き換え）。資材注文はサイドメニューから", "Không đặt (thay thế B-6). Đặt vật tư đi từ menu bên"],
     "src": "hong 回答 2026-10-05 版1.0レビュー"},
    {"date": "2026-10-05", "target": "CW_HOME_001 No.5・No.10・No.11・No.15",
     "q": ["締切の警告（ご注文がまだ）と「確認が必要なお届け」の枠を分けたままにするか", "Giữ cảnh báo hạn chót (chưa nhập đơn) và khung 「確認が必要なお届け」 tách riêng không"],
     "a": ["1つの枠「ご確認ください」にまとめる。締切の警告を先頭の行に、その下に #58 の4種類（台帳 177・#58「枠は別」を置き換え）", "Gộp thành 1 khung 「ご確認ください」. Cảnh báo hạn chót là dòng đầu, bên dưới là 4 loại của #58 (thay thế 台帳 177・#58 \"khung riêng\")"],
     "src": "hong 回答 2026-10-05 版1.0レビュー"},
    # ---- 版 1.4：法人Web 版 1.1 のレビュー 2回目（hong 回答 2026-10-05・台帳・受付簿 No.157）
    {"date": "2026-10-05", "target": "CW_HOME_001 No.3.8・No.11・No.14.1",
     "q": ["お届け詳細のサイドメニュー・パンくず・戻るボタンは、どこから開いても「ホーム」でよいか", "Menu bên, breadcrumb, nút quay lại của chi tiết đơn giao: mở từ đâu cũng là \"ホーム\" được không"],
     "a": ["開いた元に合わせる。ホームから開くリンクには ?from=home を付ける（なしもホーム）。申請の一覧から開けば「申請 ＞ お届け日の変更」を光らせる（CW_DLV No.1.1・1.5）", "Theo nơi mở ra. Link mở từ trang chủ gắn ?from=home (không có cũng là trang chủ). Mở từ danh sách yêu cầu thì sáng \"申請 ＞ お届け日の変更\" (CW_DLV No.1.1, 1.5)"],
     "src": "hong 回答 2026-10-05（台帳「法人Web 版 1.1 のレビュー 2回目」・受付簿 No.157）"},
    {"date": "2026-10-05", "target": "CW_HOME_001 No.3.6・No.5.2・No.10・No.11.4・No.18・No.19",
     "q": ["解約後（参照のみ）のホームに出すもの", "Trang chủ sau giải ước (chỉ xem) hiện gì"],
     "a": ["ご注文がまだの警告（W200）・④申請できる予定・お届け日の変更を申請できるという説明を出さない。黄色い参照のみの帯を出す。サーバーも、申請・取り下げ・ご返事を断る（E345）", "Không hiện cảnh báo chưa nhập đơn (W200), ④ lịch có thể xin đổi, câu giải thích về xin đổi ngày. Hiện dải vàng \"chỉ xem\". Server cũng từ chối xin đổi / rút lại / trả lời (E345)"],
     "src": "hong 回答 2026-10-05（台帳「法人Web 版 1.1 のレビュー 2回目」・受付簿 No.157）"},
    {"date": "2026-10-05", "target": "CW_HOME_001 No.11・11.1〜11.3・11.5・9",
     "q": ["見本データで作れない状態を「デモでは作れない」（demo_ok）で済ませてよいか", "Trạng thái dữ liệu mẫu không tạo được có được ghi \"demo_ok\" cho xong không"],
     "a": ["済ませない。見本データを作る（共通の見本の変更申請：DD-20261005-0095＝別の日のご提案、DD-20261005-0096＝申請中、DD-20260930-0001＝否認）。ほかは撮影の設定（setup）で出す", "Không. Tạo dữ liệu mẫu (yêu cầu đổi ngày mẫu chung: DD-20261005-0095 = đề xuất ngày khác, DD-20261005-0096 = đang xử lý, DD-20260930-0001 = 否認). Còn lại thì dùng thiết lập chụp (setup)"],
     "src": "hong 回答 2026-10-05（「demo_ok で逃げず、見本データを作る」・受付簿 No.157）"},
    {"date": "2026-10-05", "target": "CW_HOME_001 No.10",
     "q": ["「おまかせ注文」「デフォルト注文」「自動注文」の呼び方", "Cách gọi 「おまかせ注文」 「デフォルト注文」 「自動注文」"],
     "a": ["「自動注文」に統一（法人Web の画面）", "Thống nhất 「自動注文」 (màn hình 法人Web)"],
     "src": "hong 回答 2026-10-05（台帳「法人Web 版 1.1 のレビュー 2回目」・受付簿 No.157）"},
]

CHANGES = [
    {"ver": "1.6", "date": "2026-10-06", "no": "3.9", "type": "変更",
     "before": ["凡例に「日付調整中」がある", "Chú giải có 「日付調整中」"],
     "after": ["「日付調整中」を外す（3.8.4 と同じ）", "Bỏ 「日付調整中」 (giống 3.8.4)"],
     "reason": ["hong 回答 2026-10-06（受付簿 No.160）", "hong trả lời 2026-10-06 (受付簿 No.160)"],
     "impact": ["凡例から1項目なくす", "Bỏ 1 mục khỏi chú giải"]},
    {"ver": "1.6", "date": "2026-10-06", "no": "9", "type": "変更",
     "before": ["トーストは約2.6秒で消える（撮影用の保持なし）", "Toast tự tắt sau 2,6 giây (không có chế độ giữ khi chụp)"],
     "after": ["設計書の撮影では ?toastHold=1 で消さずに残す（DEMO のみ。画面の動きは変わらない）", "Khi chụp thiết kế dùng ?toastHold=1 để giữ toast (chỉ DEMO; hành vi màn hình không đổi)"],
     "reason": ["撮影の安定のため（画面の仕様は変更なし）", "Để chụp ổn định (đặc tả màn hình không đổi)"],
     "impact": ["開発の作業なし（撮影用）", "Dev không cần làm gì (chỉ phục vụ chụp)"]},
    {"ver": "1.6", "date": "2026-10-06", "no": "11.2", "type": "変更",
     "before": ["解約後（参照のみ）の説明がない", "Chưa mô tả trường hợp sau khi hủy hợp đồng"],
     "after": ["撮影の位置（②の1行目）を合わせた。内容は変更なし", "Chỉnh lại vị trí chụp (dòng 1 của ②). Nội dung không đổi"],
     "reason": ["②の行が増えたため撮影位置を調整", "Dòng ② tăng nên chỉnh vị trí chụp"],
     "impact": ["開発の作業なし", "Dev không cần làm gì"]},
    {"ver": "1.6", "date": "2026-10-06", "no": "5.3", "type": "削除",
     "before": ["「ご確認ください」が6件以上のとき、先頭5行＋「ほか n件を表示」", "Khi 「ご確認ください」 từ 6 dòng, hiện 5 dòng đầu + 「ほか n件を表示」"],
     "after": ["削除（④を締切ごとに1行にまとめたので、行が6件を超えない）", "Xóa (đã gộp ④ theo hạn nên không vượt 6 dòng)"],
     "reason": ["hong 回答 2026-10-06（受付簿 No.160）：④を締切ごとにまとめる", "hong trả lời 2026-10-06 (受付簿 No.160): gộp ④ theo hạn"],
     "impact": ["「ほか n件を表示」のボタンをなくす。「ご確認ください」の行はそのまま全部出す", "Bỏ nút 「ほか n件を表示」. Các dòng 「ご確認ください」 hiện đầy đủ"]},
    {"ver": "1.6", "date": "2026-10-06", "no": "3.8.4", "type": "変更",
     "before": ["バッジの一覧に「配送日調整中（日付調整中）」がある", "Danh sách badge có 「配送日調整中（日付調整中）」"],
     "after": ["「配送日調整中」を外す（共通データに対応する状態がない）", "Bỏ 「配送日調整中」 (dữ liệu chung không có trạng thái tương ứng)"],
     "reason": ["hong 回答 2026-10-06（受付簿 No.160）", "hong trả lời 2026-10-06 (受付簿 No.160)"],
     "impact": ["凡例と状態の表から「日付調整中」を外す。運営が状態を決めたら足し直す", "Bỏ 「日付調整中」 khỏi chú giải và bảng trạng thái. Khi 運営 định nghĩa trạng thái sẽ thêm lại"]},
    {"ver": "1.6", "date": "2026-10-06", "no": "11.4", "type": "変更",
     "before": ["④ 申請できる予定：お届けごとに1行（同じ文言が11行続く）", "④ Lịch dự kiến có thể xin đổi: mỗi đơn 1 dòng (11 dòng cùng chữ)"],
     "after": ["締切ごとに1行にまとめる（「…のお届けが {n}件 あります（締切 …）」）。押すとその月のカレンダー", "Gộp 1 dòng theo hạn (「…のお届けが {n}件 あります（締切 …）」). Bấm mở lịch tháng đó"],
     "reason": ["hong 回答 2026-10-06（受付簿 No.160）", "hong trả lời 2026-10-06 (受付簿 No.160)"],
     "impact": ["④ の行をまとめる。（?ym= でホームの月を開けるようにする）", "Gộp các dòng ④ (cho phép mở tháng của Home bằng ?ym=)"]},
    {"ver": "1.6", "date": "2026-10-06", "no": "11.1", "type": "変更",
     "before": ["解約後（参照のみ）でも「ご返事ください」の行が出る", "Sau khi hủy hợp đồng vẫn hiện dòng 「ご返事ください」"],
     "after": ["解約後は「…のご提案があります（解約後はご返事できません。ESキッチンへお問い合わせください）」に変わる", "Sau hủy hợp đồng đổi thành 「…のご提案があります（解約後はご返事できません。ESキッチンへお問い合わせください）」"],
     "reason": ["hong 回答 2026-10-06（受付簿 No.160）", "hong trả lời 2026-10-06 (受付簿 No.160)"],
     "impact": ["解約後の行の文言だけ変える", "Chỉ đổi câu chữ của dòng khi đã hủy hợp đồng"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["3.8", "11", "14.1"], "type": "変更",
     "before": ["お届け詳細のリンク：/corp/deliveries/{配送ID}?from=home（開いた先のサイドメニューは常に「ホーム」）", "Link tới chi tiết: /corp/deliveries/{配送ID}?from=home (menu bên ở trang đích luôn là \"ホーム\")"],
     "after": ["/corp/deliveries/{配送ID}?from=home?from=home（開いた元＝ホームを渡す。なしもホーム）", "/corp/deliveries/{配送ID}?from=home?from=home (truyền nơi mở = trang chủ; không có cũng là trang chủ)"],
     "reason": ["hong 回答 2026-10-05 版1.1 レビュー2回目（受付簿 No.157）：お届け詳細は開いた元の項目を光らせる", "hong trả lời 2026-10-05 review 版1.1 lần 2 (受付簿 No.157): chi tiết đơn giao sáng đúng mục nơi mở ra"],
     "impact": ["ホームの日付のマス・一覧・「ご確認ください」の行のリンクに ?from=home を付ける", "Gắn ?from=home vào link của ô ngày, danh sách và dòng 「ご確認ください」 ở trang chủ"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["3.6", "5.2", "10", "11.4"], "type": "変更",
     "before": ["解約後（参照のみ）でも、ご注文がまだの警告・④申請できる予定・「申請できます」の説明を出す", "Sau giải ước (chỉ xem) vẫn hiện cảnh báo chưa nhập đơn, ④ lịch có thể xin đổi, câu \"xin đổi được\""],
     "after": ["解約後（参照のみ）は出さない（月の説明は「{n}月分（{A1}〜）は予定です。」だけ）", "Sau giải ước (chỉ xem) không hiện (ghi chú tháng chỉ \"{n}月分（{A1}〜）は予定です。\")"],
     "reason": ["hong 回答 2026-10-05 版1.1 レビュー2回目（受付簿 No.157）：解約後はお届け日の変更を申請できない", "hong trả lời 2026-10-05 review 版1.1 lần 2 (受付簿 No.157): sau giải ước không xin đổi ngày được"],
     "impact": ["ホームの問い合わせ（home）に ro を渡し、サーバーが警告・④の行・申請の案内を作らない。画面は No.5.2 の文も出さない", "Truyền ro vào truy vấn trang chủ (home), server không tạo cảnh báo, dòng ④, hướng dẫn xin đổi. Màn hình cũng không hiện câu ở No.5.2"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "10", "type": "変更",
     "before": ["「おまかせ注文（…）でお届けします」「（デフォルトのまま）」", "\"おまかせ注文（…）でお届けします\" \"（デフォルトのまま）\""],
     "after": ["「自動注文（…）でお届けします」「（自動注文のまま）」", "\"自動注文（…）でお届けします\" \"（còn ở 自動注文）\""],
     "reason": ["hong 回答 2026-10-05 版1.1 レビュー2回目（受付簿 No.157）：呼び方は「自動注文」", "hong trả lời 2026-10-05 review 版1.1 lần 2 (受付簿 No.157): cách gọi là 「自動注文」"],
     "impact": ["警告の本文の言葉を変える", "Đổi từ trong nội dung cảnh báo"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["18", "19"], "type": "追加",
     "reason": ["hong 回答 2026-10-05 版1.1 レビュー2回目（受付簿 No.157）：解約後（参照のみ）のホームに黄色い参照のみの帯を出す", "hong trả lời 2026-10-05 review 版1.1 lần 2 (受付簿 No.157): trang chủ sau giải ước (chỉ xem) hiện dải vàng \"chỉ xem\""],
     "impact": ["見出しの下に参照のみの帯（ほかの法人Web の画面と同じ roTitle）を出す。状態 012（解約後）を追加", "Hiện dải \"chỉ xem\" dưới tiêu đề (cùng roTitle với các màn 法人Web khác). Thêm trạng thái 012 (sau giải ước)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "3", "type": "変更",
     "before": ["読み込めないとき、骨組みの表示（ぐるぐる）のまま止まる", "Khi không tải được, màn hình dừng mãi ở khung chờ"],
     "after": ["エラー（E346）と「再読み込み」ボタンを出す", "Hiện lỗi (E346) và nút 「再読み込み」"],
     "reason": ["QA レビュー（受付簿 No.157）：通信に失敗しても骨組みのまま止まる", "Review QA (受付簿 No.157): lỗi mạng mà vẫn dừng ở khung chờ"],
     "impact": ["読み込みのエラーを見分けて表示する", "Phân biệt và hiển thị lỗi tải"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "3.6", "type": "変更",
     "before": ["休止中の拠点の説明は、法人アカウントがその拠点を絞り込んだときだけ", "Giải thích 拠点 tạm dừng chỉ hiện khi tài khoản pháp nhân lọc đúng 拠点 đó"],
     "after": ["拠点アカウント（と拠点が1つの法人）は、自分の拠点が休止中なら常に出す", "Tài khoản 拠点 (và pháp nhân chỉ có 1 拠点) luôn hiện nếu 拠点 của mình đang tạm dừng"],
     "reason": ["QA レビュー（受付簿 No.157）：拠点アカウントには絞り込みがなく、休止の説明が出なかった", "Review QA (受付簿 No.157): tài khoản 拠点 không có bộ lọc nên không thấy giải thích tạm dừng"],
     "impact": ["ホームの問い合わせ（home）で、絞り込みがないときは唯一の拠点の休止の説明を使う", "Ở truy vấn trang chủ (home), khi không có bộ lọc thì dùng giải thích tạm dừng của 拠点 duy nhất"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["11", "11.1", "11.2", "11.3", "11.5"], "type": "変更",
     "before": ["「見本データでは作れない状態（demo_ok）」として項目だけ書いていた（撮影は通常の画面）", "Chỉ ghi mục dưới dạng \"trạng thái dữ liệu mẫu không tạo được (demo_ok)\" (ảnh là màn thường)"],
     "after": ["見本データに変更申請を追加し、実際の画面を撮る（DD-20261005-0095＝別の日のご提案 11/13、DD-20260930-0001＝否認、9/15 の一部お届け）", "Thêm yêu cầu đổi ngày vào dữ liệu mẫu và chụp màn thật (DD-20261005-0095 = đề xuất ngày khác 11/13, DD-20260930-0001 = 否認, giao thiếu 9/15)"],
     "reason": ["hong 回答 2026-10-05（受付簿 No.157）：demo_ok で逃げず、見本データを作る", "hong trả lời 2026-10-05 (受付簿 No.157): không dùng demo_ok để cho qua, hãy tạo dữ liệu mẫu"],
     "impact": ["共通の見本データ（lib/domain/seed/delivery.ts）に変更申請 3 件を追加（大阪支店 11/10 は「別の日のご提案」、12/08 は申請中、12/22 は否認）。状態 007 を撮り直す", "Thêm 3 yêu cầu đổi ngày vào dữ liệu mẫu chung (lib/domain/seed/delivery.ts): 大阪支店 11/10 đề xuất ngày khác, 12/08 đang xử lý, 12/22 否認. Chụp lại trạng thái 007"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "9", "type": "変更",
     "before": ["「トーストは 2.6 秒で消えるため撮影に写らないことがある」（demo_ok）", "\"Toast tắt sau 2,6 giây nên có thể không chụp được\" (demo_ok)"],
     "after": ["撮影の設定（setup）を、最後の「前の月」から約1秒で撮る形に直して demo_ok をなくす", "Sửa thiết lập chụp (setup) để chụp khoảng 1 giây sau lần bấm 「前の月」 cuối và bỏ demo_ok"],
     "reason": ["hong 回答 2026-10-05（受付簿 No.157）：demo_ok で逃げない", "hong trả lời 2026-10-05 (受付簿 No.157): không dùng demo_ok"],
     "impact": ["状態 005 の setup を変える（トーストは 2.6 秒表示のため、撮影は約1秒後）", "Đổi setup của trạng thái 005 (toast hiện 2,6 giây nên chụp sau khoảng 1 giây)"]},
    {"ver": "1.3", "date": "2026-10-05", "no": "5.3", "type": "追加",
     "before": ["「ご確認ください」の行を全部出す（多いと11行以上で縦に長い）", "Hiện toàn bộ dòng của 「ご確認ください」 (nhiều thì 11 dòng trở lên, rất dài)"],
     "after": ["先頭の5行＋「ほか n件を表示」ボタン", "5 dòng đầu + nút 「ほか n件を表示」"],
     "reason": ["UI の見直し（同じ文言の行が続いて縦に長くなり、締切の警告が埋もれる）", "Rà soát UI (nhiều dòng cùng nội dung làm trang dài, cảnh báo hạn chót bị chìm)"],
     "impact": ["6件以上のとき先頭5行だけを出し、ボタンで残りを開く。行の中身・順番は変えない", "Từ 6 dòng chỉ hiện 5 dòng đầu, nút mở phần còn lại. Không đổi nội dung / thứ tự dòng"]},
    {"ver": "1.2", "date": "2026-10-05", "no": "3.9", "type": "変更",
     "before": ["凡例のバッジ名「再配送」", "Tên badge trong chú giải: \"再配送\""],
     "after": ["「再配送準備」（実際のバッジの名前・色と同じ）", "\"再配送準備\" (cùng tên, màu với badge thật)"],
     "reason": ["実際に出るバッジの名前に合わせる（状態名は「再配送準備中」）", "Khớp tên badge thực tế (tên trạng thái là \"再配送準備中\")"],
     "impact": ["凡例の文言を「再配送準備」にする", "Đổi chữ trong chú giải thành \"再配送準備\""]},
    {"ver": "1.1", "date": "2026-10-05", "no": "17", "type": "追加",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：カレンダーとお知らせは半々にし、幅を「広く／狭く」で切り替えて利用者ごとに覚える", "hong trả lời 2026-10-05 review 版1.0: lịch và thông báo chia đôi, có nút 「広く／狭く」 đổi độ rộng và nhớ theo người dùng"],
     "impact": ["ホームの2列を 1:1 にし、カレンダーの見出しに切替ボタンを足す。選んだ幅を localStorage（ログインIDごと）に保存して次回も使う", "Đổi 2 cột trang chủ thành 1:1, thêm nút đổi độ rộng ở tiêu đề lịch. Lưu độ rộng đã chọn vào localStorage (theo login ID) để lần sau dùng lại"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["3", "4"], "type": "変更",
     "before": ["左＝カレンダー（広い）、右＝お知らせ（幅の説明なし）", "Trái = lịch (rộng), phải = thông báo (không ghi độ rộng)"],
     "after": ["カレンダーとお知らせは半々。No.17 の「広く／狭く」で切り替えられる", "Lịch và thông báo chia đôi. Đổi được bằng 「広く／狭く」 (No.17)"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：枠は半々", "hong trả lời 2026-10-05 review 版1.0: chia đôi khung"],
     "impact": ["2列の幅の既定を 1:1 に変える（切替は No.17）", "Đổi mặc định độ rộng 2 cột thành 1:1 (đổi độ rộng xem No.17)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["2.4", "16"], "type": "削除",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：ホームに CSV出力は置かない（Q-C3 を置き換え）。CSV出力は棚卸報告・請求書・注文履歴だけ", "hong trả lời 2026-10-05 review 版1.0: không đặt CSV出力 ở trang chủ (thay thế Q-C3). CSV出力 chỉ ở 棚卸報告, 請求書, 注文履歴"],
     "impact": ["見出しの「CSV出力」ボタンと、お届け CSV（18列）の出力処理・トーストをホームから外す", "Bỏ nút 「CSV出力」 ở tiêu đề và xử lý xuất CSV đơn giao (18 cột), toast khỏi trang chủ"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "2.5", "type": "削除",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：ホームに「資材を注文」のボタンは置かない（B-6 を置き換え）", "hong trả lời 2026-10-05 review 版1.0: không đặt nút 「資材を注文」 ở trang chủ (thay thế B-6)"],
     "impact": ["見出しの「資材を注文」ボタンを外す。資材注文はサイドメニューから開く", "Bỏ nút 「資材を注文」 ở tiêu đề. 資材注文 mở từ menu bên"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["5", "10", "11", "15"], "type": "変更",
     "before": ["締切の警告（W200）は見出しの下の別の枠。右下の枠の名前は「確認が必要なお届け」", "Cảnh báo hạn chót (W200) là khung riêng dưới tiêu đề. Khung phải dưới tên 「確認が必要なお届け」"],
     "after": ["1つの枠「ご確認ください」。先頭の行が締切の警告（W200）、その下に #58 の4種類。警告も行もないときだけ I202", "1 khung 「ご確認ください」. Dòng đầu là cảnh báo hạn chót (W200), dưới là 4 loại của #58. Chỉ khi không có cảnh báo lẫn dòng mới hiện I202"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：締切の警告と確認が必要なお届けは1つの枠「ご確認ください」にまとめ、警告を先頭に（台帳 177・#58「枠は別」を置き換え）", "hong trả lời 2026-10-05 review 版1.0: gộp cảnh báo hạn chót và đơn cần xác nhận vào 1 khung 「ご確認ください」, cảnh báo ở đầu (thay thế 台帳 177・#58)"],
     "impact": ["見出しの下の警告の枠をなくし、右の枠の見出しを「ご確認ください」に変える。枠の先頭に W200 の行（リンク「商品注文を開く」つき）を出し、その下に4種類の行。0件の判定は警告と行の両方がないとき", "Bỏ khung cảnh báo dưới tiêu đề, đổi tiêu đề khung phải thành 「ご確認ください」. Dòng đầu khung là W200 (kèm link 「商品注文を開く」), dưới là 4 loại dòng. 0 mục = không có cả cảnh báo lẫn dòng"]},
]

HIDE_ALWAYS = [".es-demo-bar", ".es-chatbot", ".es-chatbot__fab", "#es-review"]
STATIC_CSS = ".corp{height:auto!important}.corp-main{overflow:visible!important}.es-sidenav{height:auto!important;min-height:100vh}"
VIEWER_CSS = STATIC_CSS

SCREENS = [
    {"code": "CW_HOME_001", "ja": "ホーム", "vi": "Trang chủ"},
]

# ---- 画面の中で使う JavaScript（setup）
_SEL_SITE = ("const s=document.querySelector('select[aria-label=\"拠点で絞り込み\"]');"
             "if(s){const set=Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set;set.call(s,'%s');s.dispatchEvent(new Event('change',{bubbles:true}));}"
             "await new Promise(r=>setTimeout(r,800));")
_PREV = "{const t=[...document.querySelectorAll('button')].find(x=>x.textContent.trim()==='今月');t&&t.click();}await new Promise(r=>setTimeout(r,600));document.querySelector('button[aria-label=\"前の月\"]').click();await new Promise(r=>setTimeout(r,800));"
# デモの表示を「解約後（参照のみ）」にする（デモ帯の選択。以降の状態も同じタブで参照のみのままなので、解約後の状態は VIEWS の最後に置く）
_SET_RO = ("const s=[...document.querySelectorAll('select')].find(x=>[...x.options].some(o=>o.value==='ro'));"
          "if(s){const set=Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set;set.call(s,'ro');s.dispatchEvent(new Event('change',{bubbles:true}));}"
          "await new Promise(r=>setTimeout(r,1200));")
_NEXT = "{const t=[...document.querySelectorAll('button')].find(x=>x.textContent.trim()==='今月');t&&t.click();}await new Promise(r=>setTimeout(r,600));document.querySelector('button[aria-label=\"次の月\"]').click();await new Promise(r=>setTimeout(r,800));"

VIEWS = [
    # ------------------------------------------------------------ 001 法人アカウント・全拠点（今月）
    {"id": "001", "code": "CW_HOME_001", "state": ["法人アカウント・全拠点（今月）", "Tài khoản pháp nhân, tất cả 拠点 (tháng này)"],
     "url": "/corp", "setup": "", "full": True, "wait": 1200,
     "note": ["ログイン後の最初の画面。左＝今月のお届け（カレンダー）、右＝お知らせ・ご確認ください（決定 #54）。左右は半々で、「広く／狭く」で切り替えられる（版1.1）。法人アカウントは自社のすべての拠点のお届けを出す（マスの頭に拠点名）。見出しに CSV出力・資材を注文のボタンは置かない（版1.1）",
              "Màn hình đầu tiên sau đăng nhập. Trái = lịch giao hàng tháng này, phải = thông báo và 「ご確認ください」 (quyết định #54). Trái phải chia đôi, đổi được bằng 「広く／狭く」 (版1.1). Tài khoản pháp nhân thấy mọi 拠点 của công ty (đầu ô ghi tên 拠点). Tiêu đề không có nút CSV出力, 資材を注文 (版1.1)"],
     "items": [
         {"no": "1", "ja": "共通の枠（サイドメニュー・ヘッダー）", "vi": "Khung chung (menu bên, header)", "sel": ".es-sidenav", "kind": "area", "trig": "view",
          "detail": ["法人Web の全画面で共通。サイドメニュー（ホーム／月次注文／棚卸報告／請求書／申請／拠点・法人情報／購入・ユーザー管理／レビュー／お問い合わせ）・ヘッダー（お知らせ・アカウントメニュー：法人情報・拠点管理・パスワードの変更・ログアウト）の項目は、機能「ログイン／共通」（法人B）の画面設計書に書く。拠点アカウントには「法人情報」を出さない",
                     "Dùng chung cho mọi màn hình 法人Web. Các mục của menu bên (ホーム／月次注文／棚卸報告／請求書／申請／拠点・法人情報／購入・ユーザー管理／レビュー／お問い合わせ) và header (thông báo, menu tài khoản: 法人情報, 拠点管理, đổi mật khẩu, đăng xuất) ghi ở thiết kế của chức năng \"ログイン／共通\" (法人B). Tài khoản 拠点 không thấy \"法人情報\""]},
         {"no": "2", "ja": "見出し", "vi": "Tiêu đề trang", "sel": "header.es-pagehead", "kind": "area", "trig": "view"},
         {"no": "2.1", "ja": "パンくず", "vi": "Breadcrumb", "sel": ".es-breadcrumb", "kind": "label", "trig": "view",
          "detail": ["「ホーム」だけ", "Chỉ \"ホーム\""]},
         {"no": "2.2", "ja": "画面名", "vi": "Tên màn hình", "sel": "h1.es-pagehead__title", "kind": "label", "trig": "view",
          "detail": ["「ホーム」", "\"ホーム\""]},
         {"no": "2.3", "ja": "法人名・権限", "vi": "Tên pháp nhân, quyền", "sel": "header.es-pagehead .stat", "kind": "label", "trig": "view",
          "detail": ["法人アカウント：「{法人名}　権限　法人アカウント（自社のすべての拠点のお届けを表示）」。拠点アカウント：「{法人名} {拠点名}　権限　拠点アカウント（この拠点のお届けだけ表示）」。「最終更新 {日付} 03:00」は出さない（Q-H1）",
                     "Tài khoản pháp nhân: \"{tên pháp nhân}　権限　法人アカウント（自社のすべての拠点のお届けを表示）\". Tài khoản 拠点: \"{tên pháp nhân} {tên 拠点}　権限　拠点アカウント（この拠点のお届けだけ表示）\". Không hiện \"最終更新 {日付} 03:00\" (Q-H1)"]},
         {"no": "3", "ja": "今月のお届け（カレンダー）", "vi": "Lịch giao hàng tháng này", "sel": ".es-cal^", "kind": "area", "trig": "view", "err": ["E346"],
          "detail": ["暦月のカレンダー（月曜始まり）。先は予定を作ってある月まで（最大6か月先）、前はお届けのある月まで。見ていた月・拠点は、お届け詳細から戻ったときのために同じタブの間だけ覚えておく（別のアカウントでログインしたら今月に戻る）。枠の幅は右のお知らせ・ご確認くださいと半々（1:1）が既定。No.17 の「広く／狭く」で切り替えられる。読み込めなかったとき（通信の失敗）は、骨組みのまま止めずに E346 と「再読み込み」ボタンを出す",
                     "Lịch theo tháng dương (bắt đầu thứ Hai). Tới = tháng xa nhất đã tạo lịch (tối đa 6 tháng), lui = tháng xa nhất có đơn giao. Tháng và 拠点 đang xem được nhớ trong cùng tab để quay lại từ chi tiết (đăng nhập tài khoản khác thì về tháng này). Độ rộng mặc định chia đôi (1:1) với khung thông báo / ご確認ください bên phải. Đổi được bằng 「広く／狭く」 (No.17). Không tải được (lỗi mạng): thay khung chờ bằng lỗi E346 và nút 「再読み込み」"]},
         {"no": "3.1", "ja": "カレンダーの見出し", "vi": "Tiêu đề lịch", "sel": ".es-section-title h2::のお届け", "kind": "label", "trig": "view",
          "detail": ["今月：「今月のお届け（YYYY-MM）」。ほかの月：「YYYY-MM のお届け」", "Tháng này: \"今月のお届け（YYYY-MM）\". Tháng khác: \"YYYY-MM のお届け\""]},
         {"no": "3.2", "ja": "拠点で絞り込み", "vi": "Lọc theo 拠点", "sel": "select[aria-label=\"拠点で絞り込み\"]", "kind": "select", "trig": "select", "req": "－",
          "len": "選択", "init": ["すべての拠点", "すべての拠点 (tất cả 拠点)"], "ex": ["大阪支店", "Tên ngắn của 拠点 (bỏ tên pháp nhân; 拠点 trùng tên pháp nhân hiện là 本社)"],
          "cond": ["法人アカウントで拠点が2つ以上あるときだけ出す。拠点アカウントには出さない（決定 #55）", "Chỉ hiện khi tài khoản pháp nhân có từ 2 拠点. Tài khoản 拠点 không có (quyết định #55)"],
          "detail": ["選択肢：「すべての拠点」＋自社の拠点（休止中の拠点は「{拠点名}（休止中）」で後ろに並べる）。選ぶとすぐにカレンダー・確認が必要なお届けがその拠点だけになる（お知らせは変わらない）。マスの頭の拠点名は「すべての拠点」のときだけ",
                     "Lựa chọn: \"すべての拠点\" + các 拠点 của công ty (拠点 đang tạm dừng ghi \"{tên}（休止中）\" và xếp cuối). Chọn xong lịch và đơn cần xác nhận đổi ngay theo 拠点 đó (thông báo không đổi). Tên 拠点 ở đầu ô chỉ hiện khi \"すべての拠点\""]},
         {"no": "3.3", "ja": "前の月", "vi": "Tháng trước", "sel": "button[aria-label=\"前の月\"]", "kind": "button", "trig": "click", "err": ["I200"],
          "detail": ["1つ前の月のカレンダーにする。お届けのある最初の月より前は I200（トースト）", "Chuyển sang tháng trước. Trước tháng đầu tiên có đơn giao: hiện I200 (toast)"]},
         {"no": "3.4", "ja": "次の月", "vi": "Tháng sau", "sel": "button[aria-label=\"次の月\"]", "kind": "button", "trig": "click", "err": ["I201"],
          "detail": ["1つ先の月のカレンダーにする。予定を作ってある最後の月より先は I201（トースト）", "Chuyển sang tháng sau. Sau tháng cuối đã tạo lịch: hiện I201 (toast)"]},
         {"no": "3.5", "ja": "今月", "vi": "Tháng này", "sel": "button::今月", "kind": "button", "trig": "click",
          "detail": ["今月のカレンダーに戻す", "Quay về lịch tháng này"]},
         {"no": "3.6", "ja": "月の説明", "vi": "Ghi chú của tháng", "sel": "div.note::のお届けは", "kind": "label", "trig": "view",
          "detail": ["その月のお届けの説明（締切済みの月：「{n}月のお届けはご注文・変更の締切（{締切}）で確定しています。日付を変えたいときはESキッチンへお問い合わせください。」、受付中の月：「{n}月分（{A1}〜）は予定です。ご注文・変更の締切 {締切} まで、お届け日の変更を申請できます。」）。法人アカウントで「すべての拠点」のときは「法人アカウントは自社のすべての拠点のお届けを出します（マスの頭に拠点）。」、休止中の拠点を選んだときは「{拠点名}は {n}年{m}月分（{A1}）から休止のため、お届けはありません。」を続ける（拠点アカウントは絞り込みがないので、自分の拠点が休止中なら常に続ける）。解約後（参照のみ）の受付中の月は「{n}月分（{A1}〜）は予定です。」だけ（申請の案内を出さない）",
                     "Giải thích đơn giao của tháng (tháng đã chốt: \"{n}月のお届けはご注文・変更の締切（{締切}）で確定しています。…\"; tháng đang nhận đơn: \"{n}月分（{A1}〜）は予定です。ご注文・変更の締切 {締切} まで、お届け日の変更を申請できます。\"). Tài khoản pháp nhân chọn \"すべての拠点\" thêm \"法人アカウントは自社のすべての拠点のお届けを出します（マスの頭に拠点）。\"; chọn 拠点 tạm dừng thêm \"{拠点名}は {n}年{m}月分（{A1}）から休止のため、お届けはありません。\" (tài khoản 拠点 không có bộ lọc nên luôn thêm nếu 拠点 của mình tạm dừng). Sau giải ước (chỉ xem), tháng đang nhận đơn chỉ ghi \"{n}月分（{A1}〜）は予定です。\" (không hiện hướng dẫn xin đổi)"]},
         {"no": "3.7", "ja": "曜日の見出し", "vi": "Tiêu đề thứ", "sel": ".es-cal__wd", "kind": "label", "trig": "view",
          "detail": ["月・火・水・木・金・土・日（月曜始まり）", "月・火・水・木・金・土・日 (bắt đầu thứ Hai)"]},
         {"no": "3.8", "ja": "日付のマス", "vi": "Ô ngày", "sel": ".es-calcell.is-clickable", "kind": "link", "trig": "click",
          "detail": ["1日＝1マス。今日のマスは枠を強調、先月・来月の日は灰色。お届けのある日にだけサイクル・お届けの行・バッジを出し、押せる。押すと：その日のお届けが1件ならお届け詳細（/corp/deliveries/{配送ID}?from=home）、2件以上ならその日のお届けの一覧（No.14）を出して選ぶ（Q-H2）",
                     "1 ngày = 1 ô. Ô hôm nay viền nổi bật, ngày của tháng trước/sau màu xám. Chỉ ngày có đơn giao mới hiện chu kỳ, dòng đơn giao, badge và bấm được. Bấm: 1 đơn → mở chi tiết (/corp/deliveries/{配送ID}?from=home); từ 2 đơn → hiện danh sách đơn giao trong ngày (No.14) để chọn (Q-H2)"]},
         {"no": "3.8.1", "ja": "日付・祝日", "vi": "Ngày, ngày lễ", "sel": ".es-calcell__date", "kind": "label", "trig": "view",
          "detail": ["日（1〜31）。全社の休日マスタにある日は祝日の名前を右に出す（例「スポーツの日」）", "Số ngày (1〜31). Ngày có trong master ngày nghỉ toàn công ty hiện tên ngày lễ bên phải (ví dụ \"スポーツの日\")"]},
         {"no": "3.8.2", "ja": "ご利用月（サイクル）", "vi": "Tháng sử dụng (chu kỳ)", "sel": ".es-calcell__cycle", "kind": "label", "trig": "view",
          "detail": ["お届けのある日に、そのお届けのご利用月（「10月分」など）。配送サイクル（A1 の日）で区切る", "Ở ngày có đơn giao: tháng sử dụng của đơn (\"10月分\"…). Chia theo chu kỳ giao hàng (ngày A1)"]},
         {"no": "3.8.3", "ja": "お届けの行", "vi": "Dòng đơn giao", "sel": ".es-calcell__line", "kind": "label", "trig": "view",
          "detail": ["お届け1件＝1行：「{拠点} {温度帯} {食数}」。拠点は「すべての拠点」のときだけ（本社・大阪・名古屋…）。温度帯は 冷蔵／冷凍／資材。食数は確定したお届けだけ（予定は空。資材は空）。お届け済みはお届け数、それ以外は予定数",
                     "1 đơn giao = 1 dòng: \"{拠点} {温度帯} {số suất}\". 拠点 chỉ hiện khi \"すべての拠点\" (本社・大阪・名古屋…). 温度帯: 冷蔵／冷凍／資材. Số suất chỉ với đơn đã chốt (dự kiến để trống; vật tư để trống). Đã giao = số đã giao, còn lại = số dự kiến"]},
         {"no": "3.8.4", "ja": "状態のバッジ", "vi": "Badge trạng thái", "sel": ".es-calcell__badges", "kind": "label", "trig": "view",
          "detail": ["お届けの状態（#42 の表示名）。予定＝「予定」（青）、出荷待（青）、配送中（青）、お届け済み（緑）、一部お届け済み（黄・マスでは「一部お届け」）、再配送準備中（黄・「再配送準備」）、配送状況を確認中です（黄・「確認中」）、お届け中止（赤）。別の日のご提案があるお届けは「ご提案あり」（黄）、ESキッチンが締切後にお届け日を変えたお届けは「日付変更」（青）を足す。同じ状態は1つにまとめる。マスでは折り返さず短い印、正式名はツールチップと詳細（#61）",
                     "Trạng thái đơn giao (tên hiển thị #42). 予定 (xanh dương), 出荷待 (xanh dương), 配送中 (xanh dương), お届け済み (xanh lá), 一部お届け済み (vàng, trong ô ghi \"一部お届け\"), 再配送準備中 (vàng, \"再配送準備\"), 配送状況を確認中です (vàng, \"確認中\"), お届け中止 (đỏ). Có đề xuất ngày khác thêm \"ご提案あり\" (vàng); ES Kitchen đổi ngày sau hạn thêm \"日付変更\" (xanh dương). Cùng trạng thái gộp 1 badge. Trong ô không xuống dòng, dùng tên ngắn; tên đầy đủ ở tooltip và chi tiết (#61)"]},
         {"no": "3.9", "ja": "凡例", "vi": "Chú giải", "sel": "span::日付を押すと^", "kind": "label", "trig": "view",
          "detail": ["マスの見方：予定（点線の枠・まだ確定していないお届け。数量はご注文・変更の締切の後）／確定したお届け（実線）／一部お届け／ご提案あり（ご返事が必要）／再配送準備／お届け中止／確認中／日付変更（ESキッチンがお届け日を変更）／先月・来月（灰色）／「日付を押すと、お届けの詳細を開きます」。実際に出るバッジと同じ名前・色にする",
                     "Cách đọc ô: 予定 (viền chấm, chưa chốt; số lượng sau hạn đặt/đổi), đơn đã chốt (viền liền), 一部お届け, ご提案あり (cần trả lời), 再配送準備, お届け中止, 確認中, 日付変更 (ES Kitchen đổi ngày giao), tháng trước/sau (xám), \"日付を押すと、お届けの詳細を開きます\". Tên và màu khớp badge thực tế"]},
         {"no": "4", "ja": "お知らせ", "vi": "Thông báo", "sel": "h2::お知らせ^2", "kind": "area", "trig": "view", "err": ["I203"],
          "detail": ["法人向けに配信中のお知らせ（公開日が今日まで）。重要なお知らせが上、次に新しい順。0件は I203。枠はカレンダーの右で、幅はカレンダーと半々（1:1）が既定（No.17 で切り替え）。その下に「ご確認ください」（No.5）", "Thông báo đang phát cho pháp nhân (ngày công khai đến hôm nay). Thông báo quan trọng lên trên, rồi mới nhất trước. 0 mục: I203. Khung ở bên phải lịch, độ rộng mặc định chia đôi (1:1) với lịch (đổi bằng No.17). Bên dưới là 「ご確認ください」 (No.5)"]},
         {"no": "4.1", "ja": "お知らせ一覧へ", "vi": "Tới danh sách thông báo", "sel": "a::お知らせ一覧へ", "kind": "link", "trig": "click",
          "detail": ["お知らせ一覧（/corp/news）を開く", "Mở danh sách thông báo (/corp/news)"]},
         {"no": "4.2", "ja": "お知らせの行", "vi": "Dòng thông báo", "sel": ".es-notice__item", "kind": "link", "trig": "click",
          "detail": ["日時（今日なら「今日・HH:MM」、ほかは「MM-DD・HH:MM」）・カテゴリのバッジ（お知らせ／メニュー など）・タイトル。押すとお知らせ詳細（/corp/news/{お知らせID}）", "Ngày giờ (hôm nay: \"今日・HH:MM\", khác: \"MM-DD・HH:MM\"), badge thể loại (お知らせ／メニュー…), tiêu đề. Bấm mở chi tiết thông báo (/corp/news/{ID})"]},
         {"no": "5", "ja": "ご確認ください", "vi": "Vui lòng kiểm tra (ご確認ください)", "sel": "h2::ご確認ください^2", "kind": "area", "trig": "view", "err": ["W200", "I202"],
          "detail": ["お知らせの下の枠。見出し「ご確認ください」。中身は上から ①締切の警告（ご注文がまだ・W200。No.10）を先頭の行に ②表示中の拠点（絞り込みに合わせる）の、ご返事・確認が必要なお届け（決定 #58 の4種類 No.11.1〜11.4、この順）。「すべての拠点」のときは行の頭に拠点名（「大阪：…」）。警告も行もないときは I202",
                     "Khung dưới thông báo. Tiêu đề 「ご確認ください」. Nội dung từ trên xuống: ① cảnh báo hạn chót (chưa nhập đơn, W200, No.10) ở dòng đầu ② đơn giao cần trả lời / xác nhận của 拠点 đang xem (theo bộ lọc), 4 loại theo quyết định #58 (No.11.1〜11.4, theo thứ tự đó). Khi \"すべての拠点\" đầu dòng ghi tên 拠点 (\"大阪：…\"). Không có cảnh báo lẫn dòng: I202"]},
         {"no": "5.1", "ja": "お届け日の変更申請の一覧へ", "vi": "Tới danh sách yêu cầu đổi ngày giao", "sel": "a::お届け日の変更申請の一覧へ", "kind": "link", "trig": "click",
          "detail": ["申請 ＞ お届け日の変更の一覧（/corp/requests）を開く。文言は「お届け日の変更申請の一覧へ」（hong 2026-10-05 B-5）", "Mở danh sách 申請 ＞ お届け日の変更 (/corp/requests). Chữ: 「お届け日の変更申請の一覧へ」 (hong 2026-10-05 B-5)"]},
         {"no": "5.2", "ja": "変更申請の案内", "vi": "Hướng dẫn xin đổi ngày", "sel": ".note::お届け日の変更を申請できるのは", "kind": "label", "trig": "view",
          "cond": ["解約後（参照のみ）のアカウントには出さない（申請できないため）", "Không hiện với tài khoản sau giải ước (chỉ xem) (vì không xin đổi được)"],
          "detail": ["「お届け日の変更を申請できるのは、翌月以降の「予定」のお届け（ご注文・変更の締切まで）です。今月・過去・確定したお届けはESキッチンへお問い合わせください。」", "\"お届け日の変更を申請できるのは、翌月以降の「予定」のお届け（ご注文・変更の締切まで）です。今月・過去・確定したお届けはESキッチンへお問い合わせください。\""]},
         {"no": "17", "ja": "幅の切替（広く／狭く）", "vi": "Đổi độ rộng (広く／狭く)", "sel": "button::広く", "kind": "button", "trig": "click",
          "init": ["半々（ボタンの文字は「広く」）", "Chia đôi (chữ nút là 「広く」)"],
          "cond": ["カレンダーとお知らせが2列に並ぶ幅のときだけ。1列（狭い画面）では出さない", "Chỉ khi lịch và thông báo xếp 2 cột. Màn hình hẹp (1 cột) không hiện"],
          "detail": ["カレンダーの見出しの右（月送りの横）の小さなボタン。既定は左右半々（1:1）で文字は「広く」。押すとカレンダー側を広く（2:1）して文字が「狭く」になり、もう一度押すと半々に戻る。選んだ幅はブラウザの localStorage にログインIDごとに保存し、次にホームを開いたときも同じ幅（別の端末・別のブラウザには引き継がない。保存できないときは半々）", "Nút nhỏ bên phải tiêu đề lịch (cạnh nút chuyển tháng). Mặc định chia đôi (1:1), chữ nút 「広く」. Bấm thì lịch rộng hơn (2:1) và chữ thành 「狭く」, bấm lại thì về chia đôi. Độ rộng đã chọn lưu vào localStorage của trình duyệt theo login ID; lần sau mở trang chủ vẫn giữ (không mang sang máy / trình duyệt khác; không lưu được thì chia đôi)"]},
     ]},
    # ------------------------------------------------------------ 002 1拠点に絞り込み
    {"id": "002", "code": "CW_HOME_001", "state": ["法人アカウント・1拠点に絞り込み", "Tài khoản pháp nhân, lọc 1 拠点"],
     "url": "/corp", "setup": _SEL_SITE % "CU00871", "full": True, "wait": 1200,
     "note": ["「拠点で絞り込み」で大阪支店を選んだ状態。マスの頭の拠点名が消え、確認が必要なお届けもその拠点だけになる", "Đã chọn 大阪支店 ở \"拠点で絞り込み\". Tên 拠点 ở đầu ô biến mất, đơn cần xác nhận cũng chỉ của 拠点 đó"],
     "items": [
         {"no": "6", "ja": "絞り込み後のカレンダー", "vi": "Lịch sau khi lọc", "sel": ".es-cal", "kind": "area", "trig": "view",
          "detail": ["選んだ拠点のお届けだけ。お届けの行は「{温度帯} {食数}」（拠点名なし）。同じ日に複数のお届けがなければ、マスを押すとすぐ詳細", "Chỉ đơn giao của 拠点 đã chọn. Dòng đơn giao \"{温度帯} {số suất}\" (không có tên 拠点). Nếu trong ngày chỉ 1 đơn, bấm ô mở ngay chi tiết"]},
         {"no": "6.1", "ja": "拠点で絞り込み（選択後）", "vi": "Lọc theo 拠点 (sau khi chọn)", "sel": "select[aria-label=\"拠点で絞り込み\"]", "kind": "select", "trig": "select", "req": "－",
          "len": "選択", "init": ["すべての拠点", "すべての拠点 (tất cả 拠点)"], "ex": ["大阪支店", "拠点 đã chọn (giữ lại khi đổi tháng và khi quay về từ chi tiết)"],
          "detail": ["選んだ拠点は月を変えても保たれる。お届け詳細から「カレンダーへ戻る」で戻っても同じ拠点・同じ月", "拠点 đã chọn giữ nguyên khi đổi tháng. Quay về từ chi tiết bằng \"カレンダーへ戻る\" vẫn cùng 拠点, cùng tháng"]},
     ]},
    # ------------------------------------------------------------ 003 拠点アカウント
    {"id": "003", "code": "CW_HOME_001", "state": ["拠点アカウント", "Tài khoản 拠点"],
     "url": "/corp", "login": "CU00871", "setup": "", "full": True, "wait": 1200,
     "note": ["拠点アカウント（大阪支店 CU00871）でログイン。その拠点のお届けだけ。「拠点で絞り込み」は出ない（決定 #55）", "Đăng nhập tài khoản 拠点 (大阪支店 CU00871). Chỉ đơn giao của 拠点 đó. Không có \"拠点で絞り込み\" (quyết định #55)"],
     "items": [
         {"no": "7", "ja": "法人名・権限（拠点アカウント）", "vi": "Tên pháp nhân, quyền (tài khoản 拠点)", "sel": "header.es-pagehead .stat", "kind": "label", "trig": "view",
          "detail": ["「{法人名} {拠点名}　権限　拠点アカウント（この拠点のお届けだけ表示）」", "\"{tên pháp nhân} {tên 拠点}　権限　拠点アカウント（この拠点のお届けだけ表示）\""]},
         {"no": "7.1", "ja": "月送り（絞り込みなし）", "vi": "Chuyển tháng (không có bộ lọc)", "sel": "button[aria-label=\"前の月\"]^", "kind": "area", "trig": "view",
          "detail": ["前の月・次の月・今月だけ。拠点で絞り込みは出さない。お届けの行に拠点名は付かない", "Chỉ có 前の月・次の月・今月. Không có lọc 拠点. Dòng đơn giao không có tên 拠点"]},
     ]},
    # ------------------------------------------------------------ 004 次の月（予定のマス）
    {"id": "004", "code": "CW_HOME_001", "state": ["次の月（予定のマス）", "Tháng sau (ô dự kiến)"],
     "url": "/corp", "setup": _NEXT, "full": True, "wait": 1200,
     "note": ["「次の月」で 2026-11（受付中のご利用月）を表示。まだ確定していないお届けは点線の枠と「予定」のバッジ、食数なし", "Bấm \"次の月\" để xem 2026-11 (tháng đang nhận đơn). Đơn chưa chốt có viền chấm, badge \"予定\", không có số suất"],
     "items": [
         {"no": "8", "ja": "予定のマス", "vi": "Ô dự kiến", "sel": ".es-calcell--draft", "kind": "link", "trig": "click",
          "detail": ["点線の枠。お届けの行は「{拠点} {温度帯}」だけ（数量はご注文・変更の締切の後）。バッジ「予定」（青・#61）。押すとお届け詳細（予定）。お届け日の変更を申請できるのは、この予定のお届けだけ", "Viền chấm. Dòng đơn giao chỉ \"{拠点} {温度帯}\" (số lượng sau hạn đặt/đổi). Badge \"予定\" (xanh dương, #61). Bấm mở chi tiết (dự kiến). Chỉ đơn dự kiến mới xin đổi ngày giao được"]},
         {"no": "8.1", "ja": "月の説明（受付中の月）", "vi": "Ghi chú (tháng đang nhận đơn)", "sel": "div.note", "kind": "label", "trig": "view",
          "detail": ["「{n}月分（{A1}〜）は予定です。ご注文・変更の締切 {締切} まで、お届け日の変更を申請できます。」", "\"{n}月分（{A1}〜）は予定です。ご注文・変更の締切 {締切} まで、お届け日の変更を申請できます。\""]},
     ]},
    # ------------------------------------------------------------ 005 範囲の外（トースト）
    {"id": "005", "code": "CW_HOME_001", "state": ["範囲の外（トースト）", "Ngoài phạm vi (toast)"],
     "url": "/corp?toastHold=1", "setup": "{const t=[...document.querySelectorAll('button')].find(x=>x.textContent.trim()==='今月');t&&t.click();}await new Promise(r=>setTimeout(r,600));for(let i=0;i<6;i++){document.querySelector('button[aria-label=\"前の月\"]').click();await new Promise(r=>setTimeout(r,500));}await new Promise(r=>setTimeout(r,300));", "full": True, "wait": 200,
     "note": ["お届けのある最初の月（見本データでは 2026-05。大阪支店の初回の資材のお届け）まで戻ってから、もう一度「前の月」を押した。月は変わらず I200 をトーストで出す。最後の月で「次の月」も同じ（I201）", "Lui về tháng đầu tiên có đơn giao (dữ liệu mẫu: 2026-05, đơn vật tư đầu tiên của 大阪支店) rồi bấm \"前の月\" thêm lần nữa. Tháng không đổi, hiện toast I200. Ở tháng cuối bấm \"次の月\" cũng vậy (I201)"],
     "items": [
         {"no": "9", "ja": "トースト（範囲の外）", "vi": "Toast (ngoài phạm vi)", "sel": ".hd-toast", "kind": "toast", "trig": "show", "err": ["I200", "I201"],
          "detail": ["約2.6秒で消える（設計書の撮影では URL に ?toastHold=1 を付けて消さずに残す）。前：I200、先：I201", "Tự tắt sau khoảng 2,6 giây. Lui: I200, tới: I201"]},
     ]},
    # ------------------------------------------------------------ 006 ご注文がまだの警告
    {"id": "006", "code": "CW_HOME_001", "state": ["ご注文がまだの警告", "Cảnh báo chưa nhập đơn hàng"],
     "url": "/corp", "today": "2026/10/10", "setup": "", "full": True, "wait": 1200,
     "note": ["デモの今日を 2026/10/10（11月分の締切 10/15 の5日前）にした状態。商品注文をまだ入れていない拠点（大阪支店・横浜営業所）があるので、「ご確認ください」の枠の先頭の行に締切の警告を出す（版1.1）", "Đặt \"hôm nay\" của demo = 2026/10/10 (5 ngày trước hạn 10/15 của tháng 11). Có 拠点 chưa nhập đơn (大阪支店・横浜営業所) nên dòng đầu của khung 「ご確認ください」 là cảnh báo hạn chót (版1.1)"],
     "items": [
         {"no": "10", "ja": "締切の警告（ご注文がまだ）", "vi": "Cảnh báo hạn chót (chưa nhập đơn hàng)", "sel": ".es-inline--warning", "kind": "label", "trig": "view", "err": ["W200"],
          "cond": ["受付中のメニューの締切の7日前から締切の日まで。表示中の拠点のうち、商品注文をまだ入れていない拠点（自動注文のまま）があるとき。お試し・休止中の拠点は数えない。解約後（参照のみ）のアカウントには出さない。法人の「ご注文のリマインド」の ON/OFF は通知・メールだけで、この警告は切らない（台帳 E 2026-10-05）",
                   "Từ 7 ngày trước hạn đến ngày hạn của menu đang nhận đơn, khi trong các 拠点 đang xem có 拠点 chưa nhập đơn (còn ở 自動注文). Không tính お試し và 拠点 tạm dừng. Không hiện với tài khoản sau giải ước (chỉ xem). ON/OFF \"ご注文のリマインド\" chỉ áp cho thông báo/email, không tắt cảnh báo này (台帳 E 2026-10-05)"],
          "detail": ["「ご確認ください」（No.5）の枠の先頭の行（黄色の警告の行。確認が必要なお届けの行より上）。見出し：W200（締切の日は「あと{n}日」の代わりに「本日まで」）。本文：法人アカウントは「{拠点名}・{拠点名}：」で始め、「締切までにご注文がない場合は、自動注文（「次回以降も適用」の AI（自動提案）があればその数）でお届けします。」。商品注文の画面にも同じ警告を出す（そちらは見出しの下）",
                     "Dòng đầu của khung 「ご確認ください」 (No.5) (dòng cảnh báo màu vàng, trên các dòng đơn cần xác nhận). Tiêu đề: W200 (ngày hạn ghi \"本日まで\" thay cho \"あと{n}日\"). Nội dung: tài khoản pháp nhân mở đầu \"{拠点名}・{拠点名}：\", rồi \"締切までにご注文がない場合は、自動注文（「次回以降も適用」の AI（自動提案）があればその数）でお届けします。\". Màn hình 商品注文 cũng hiện cảnh báo này (ở đó đặt dưới tiêu đề)"]},
         {"no": "10.1", "ja": "商品注文を開く", "vi": "Mở 商品注文", "sel": "a::商品注文を開く", "kind": "link", "trig": "click",
          "detail": ["商品注文（/corp/order）を開く", "Mở 商品注文 (/corp/order)"]},
     ]},
    # ------------------------------------------------------------ 007 確認が必要なお届け：ご提案あり
    {"id": "007", "code": "CW_HOME_001", "state": ["ご確認ください：ご提案あり", "ご確認ください: có đề xuất ngày khác"],
     "url": "/corp", "setup": _NEXT, "full": True, "wait": 1200,
     "note": ["共通の見本データの変更申請 DD-20261005-0095（大阪支店 11/10 → 第一希望 11/12・第二希望 11/17）に、ESキッチンが 11/13 を提案している状態（別の日のご提案）。「次の月」で 2026-11。「ご確認ください」の先頭に「ご返事」の行、続いて 9/15 の一部お届け（配送）・12/22 の否認（申請の結果・DD-20260930-0001）・申請できる予定の行。11/10 のマスに「ご提案あり」（版1.4：見本データに追加）",
              "Yêu cầu đổi ngày mẫu chung DD-20261005-0095 (大阪支店 11/10 → NV1 11/12, NV2 11/17) đang được ES Kitchen đề xuất 11/13 (別の日のご提案). Bấm \"次の月\" xem 2026-11. Đầu 「ご確認ください」 có dòng \"ご返事\", tiếp là dòng giao thiếu 9/15 (配送), 否認 12/22 (kết quả yêu cầu, DD-20260930-0001) và các dòng lịch có thể xin đổi. Ô 11/10 có \"ご提案あり\" (版1.4: thêm vào dữ liệu mẫu)"],
     "items": [
         {"no": "11", "ja": "確認が必要なお届けの行", "vi": "Dòng đơn cần xác nhận", "sel": ".es-notice__note^2", "kind": "link", "trig": "click",
          "detail": ["「ご確認ください」（No.5）の枠の中、締切の警告（No.10）の下の行。日付（MM-DD）・種類のバッジ・右端に補足・タイトル。押すとそのお届けの詳細（/corp/deliveries/{配送ID}?from=home）。「すべての拠点」のときはタイトルの頭に「{拠点}：」", "Dòng trong khung 「ご確認ください」 (No.5), dưới cảnh báo hạn chót (No.10). Ngày (MM-DD), badge loại, ghi chú ở phải, tiêu đề. Bấm mở chi tiết đơn giao (/corp/deliveries/{配送ID}?from=home). Khi \"すべての拠点\" tiêu đề mở đầu \"{拠点}：\""]},
         {"no": "11.1", "ja": "① 別の日のご提案（ご返事が必要）", "vi": "① Đề xuất ngày khác (cần trả lời)", "sel": ".es-notice__note::別の日のご提案^2", "kind": "label", "trig": "view",
          "cond": ["変更申請が「別の日のご提案」の間", "Khi yêu cầu đổi ngày đang ở trạng thái \"別の日のご提案\""],
          "detail": ["バッジ「ご返事」（黄）・補足「別の日のご提案」・日付＝提案した日。タイトル「{お届け日} のお届け：{提案の日} のご提案にご返事ください」。お届け詳細で「{日} で受ける」「お断りする」。解約後（参照のみ）はタイトルが「…のご提案があります（解約後はご返事できません。ESキッチンへお問い合わせください）」に変わり、お届け詳細でも「受ける／お断りする」は出ない", "Badge \"ご返事\" (vàng), ghi chú \"別の日のご提案\", ngày = ngày đề xuất. Tiêu đề \"{お届け日} のお届け：{提案の日} のご提案にご返事ください\". Ở chi tiết: \"{日} で受ける\" / \"お断りする\". Sau khi hủy hợp đồng (chỉ xem), tiêu đề đổi thành \"…のご提案があります（解約後はご返事できません。ESキッチンへお問い合わせください）\" và ở chi tiết cũng không có 「受ける／お断りする」"]},
         {"no": "11.2", "ja": "② 届かなかった・遅れたお届け", "vi": "② Đơn giao thiếu / trễ", "sel": ".es-notice__note::一部お届け^2", "kind": "label", "trig": "view",
          "cond": ["状態が 一部お届け済み／再配送準備中／お届け中止、または配送状況を確認中（未解決のトラブル）", "Trạng thái 一部お届け済み／再配送準備中／お届け中止, hoặc đang xác nhận tình trạng giao (sự cố chưa giải quyết)"],
          "detail": ["バッジ「配送」（黄）・補足＝状態（「確認中」など）・日付＝報告した日。タイトル「{お届け日} のお届け：配送状況を確認しています」など", "Badge \"配送\" (vàng), ghi chú = trạng thái (\"確認中\"…), ngày = ngày báo cáo. Tiêu đề \"{お届け日} のお届け：配送状況を確認しています\"…"]},
         {"no": "11.3", "ja": "③ 申請の結果", "vi": "③ Kết quả yêu cầu đổi ngày", "sel": ".es-notice__note::否認^2", "kind": "label", "trig": "view",
          "cond": ["変更申請が 承認・否認 になってから14日間", "Trong 14 ngày sau khi yêu cầu được 承認 / 否認"],
          "detail": ["バッジ「申請」・補足＝承認／否認・日付＝処理した日。タイトル「{お届け日} のお届け：変更申請 {申請番号} は{承認／否認}になりました」。押すとお届け詳細", "Badge \"申請\", ghi chú = 承認／否認, ngày = ngày xử lý. Tiêu đề \"{お届け日} のお届け：変更申請 {申請番号} は{承認／否認}になりました\". Bấm mở chi tiết"]},
         {"no": "11.4", "ja": "④ 申請できる予定", "vi": "④ Lịch dự kiến có thể xin đổi", "sel": ".es-notice__note::締切^2", "kind": "label", "trig": "view",
          "cond": ["お届け日の変更を申請できる予定のお届け（翌月以降）で、ご注文・変更の締切の3週間前になったもの（締切まで）。解約後（参照のみ）のアカウントには出さない", "Đơn dự kiến có thể xin đổi ngày (từ tháng sau), từ 3 tuần trước hạn đặt/đổi đến hạn. Không hiện với tài khoản sau giải ước (chỉ xem)"],
          "detail": ["バッジ「予定」（青）・補足「締切 {締切}」・日付＝いちばん早いお届け日。タイトル「お届け日の変更を申請できる予定のお届けが {n}件 あります（締切 {締切}）」。同じ締切のお届けは1行にまとめる（同じ文言の行が続くと縦に長くなり、締切の警告が埋もれるため・hong 2026-10-06）。押すとそのお届けの月のカレンダー（/corp?ym=…）を開き、「予定」のマスからお届け詳細（「お届け日の変更を申請」）へ進む", "Badge \"予定\" (xanh dương), ghi chú \"締切 {締切}\", ngày = ngày giao sớm nhất. Tiêu đề \"お届け日の変更を申請できる予定のお届けが {n}件 あります（締切 {締切}）\". Các đơn cùng hạn gộp 1 dòng (nhiều dòng cùng chữ làm trang dài, cảnh báo hạn chót bị chìm; hong 2026-10-06). Bấm mở lịch của tháng đó (/corp?ym=…), rồi từ ô 「予定」 vào chi tiết (「お届け日の変更を申請」)"]},
         {"no": "11.5", "ja": "マスのバッジ「ご提案あり」", "vi": "Badge \"ご提案あり\" trên ô", "sel": ".es-calcell__badges .es-badge::ご提案あり", "kind": "label", "trig": "view",
          "detail": ["別の日のご提案があるお届けの日のマスに「ご提案あり」（黄）。ツールチップ「別の日のご提案（ご返事が必要）」", "Ô ngày của đơn có đề xuất ngày khác hiện \"ご提案あり\" (vàng). Tooltip \"別の日のご提案（ご返事が必要）\""]},
     ]},
    # ------------------------------------------------------------ 008 確認が必要なお届け：配送状況を確認中
    {"id": "008", "code": "CW_HOME_001", "state": ["確認が必要なお届け：配送状況を確認中", "Đơn cần xác nhận: đang xác nhận tình trạng giao"],
     "url": "/corp", "login": "CU00031", "setup": _PREV, "full": True, "wait": 1200,
     "note": ["株式会社ひかり物産（CU00031）でログインし、「前の月」で 2026-09 を表示。川崎工場 9/19 のお届けに未解決のトラブル（遅延）があるので、右下に「配送・確認中」の行、マスに「確認中」のバッジ", "Đăng nhập 株式会社ひかり物産 (CU00031), bấm \"前の月\" để xem 2026-09. Đơn giao 川崎工場 9/19 có sự cố chưa giải quyết (trễ) nên góc phải dưới có dòng \"配送・確認中\", ô ngày có badge \"確認中\""],
     "items": [
         {"no": "12", "ja": "行（配送状況を確認中）", "vi": "Dòng (đang xác nhận tình trạng giao)", "sel": ".es-notice__note::確認中^2", "kind": "link", "trig": "click",
          "detail": ["バッジ「配送」（黄）・補足「確認中」・日付＝トラブルを報告した日。タイトル「{拠点}：{お届け日} のお届け：配送状況を確認しています」。押すとお届け詳細（確認中の案内あり）", "Badge \"配送\" (vàng), ghi chú \"確認中\", ngày = ngày báo sự cố. Tiêu đề \"{拠点}：{お届け日} のお届け：配送状況を確認しています\". Bấm mở chi tiết (có hướng dẫn đang xác nhận)"]},
         {"no": "12.1", "ja": "マスのバッジ「確認中」", "vi": "Badge \"確認中\" trên ô", "sel": ".es-calcell__badges .es-badge::確認中", "kind": "label", "trig": "view",
          "detail": ["未解決のトラブルがあるお届けの日に「確認中」（黄）。ツールチップ「配送状況を確認中です」。解決すると消える", "Ngày có đơn giao đang có sự cố chưa giải quyết hiện \"確認中\" (vàng). Tooltip \"配送状況を確認中です\". Giải quyết xong thì mất"]},
     ]},
    # ------------------------------------------------------------ 009 マスのバッジ（一部お届け ほか）
    {"id": "009", "code": "CW_HOME_001", "state": ["マスのバッジ（一部お届け・日付変更・ご提案あり）", "Badge trên ô (一部お届け・日付変更・ご提案あり)"],
     "url": "/corp", "setup": _PREV + (_SEL_SITE % "CU00871"), "full": True, "wait": 1200,
     "note": ["2026-09・大阪支店に絞り込み。9/15 は一部お届け済み（「一部お届け」）、9/17 はその残りの再配送（お届け済み）。「日付変更」「ご提案あり」は該当のお届けができたときに同じ場所に出る", "2026-09, lọc 大阪支店. 9/15 giao thiếu (\"一部お届け\"), 9/17 là giao bù phần còn lại (お届け済み). \"日付変更\", \"ご提案あり\" hiện cùng chỗ khi có đơn tương ứng"],
     "items": [
         {"no": "13", "ja": "バッジ付きのマス（一部お届け）", "vi": "Ô có badge (一部お届け)", "sel": ".es-calcell__badges^", "kind": "link", "trig": "click",
          "detail": ["一部お届け済みのお届け：食数はお届け数（例 20食）、バッジ「一部お届け」（黄・ツールチップ「一部お届け済み」）。押すとお届け詳細（不足の案内・関連するお届け）。再配送の子のお届けは別の日のマスに「お届け済み」などで出る", "Đơn giao thiếu: số suất = số đã giao (ví dụ 20食), badge \"一部お届け\" (vàng, tooltip \"一部お届け済み\"). Bấm mở chi tiết (cảnh báo thiếu, đơn liên quan). Đơn giao bù hiện ở ô ngày khác với \"お届け済み\"…"]},
         {"no": "13.1", "ja": "バッジ「日付変更」", "vi": "Badge \"日付変更\"", "sel": ".es-calcell__badges^", "kind": "label", "trig": "view",
          "cond": ["ESキッチンがご注文・変更の締切の後にお届け日を変えたお届け（変更申請の承認・ご提案を受けた・運営の移動）", "Đơn giao được ES Kitchen đổi ngày sau hạn đặt/đổi (duyệt yêu cầu, nhận đề xuất, vận hành dời lịch)"],
          "detail": ["新しいお届け日のマスに「日付変更」（青）。ツールチップ「お届け日の変更でこの日になりました」", "Ô ngày giao mới hiện \"日付変更\" (xanh dương). Tooltip \"お届け日の変更でこの日になりました\""]},
     ]},
    # ------------------------------------------------------------ 010 同じ日に複数のお届け
    {"id": "010", "code": "CW_HOME_001", "state": ["同じ日に複数のお届け（その日のお届けの一覧）", "Nhiều đơn giao cùng ngày (danh sách đơn trong ngày)"],
     "url": "/corp", "setup": "await new Promise(r=>setTimeout(r,1200));{const t=[...document.querySelectorAll('button')].find(x=>x.textContent.trim()==='今月');t&&t.click();await new Promise(r=>setTimeout(r,600));}" + (_SEL_SITE % "") + "const c=[...document.querySelectorAll('.es-calcell__line')].find(x=>x.textContent.includes('27食'));c&&c.parentElement.click();await new Promise(r=>setTimeout(r,300));", "full": True, "wait": 200,
     "note": ["法人アカウント・すべての拠点で 10/13 のマス（大阪 冷蔵・横浜 冷蔵・横浜 冷凍の3件）を押した。決定（Q-H2）：マスの下にその日のお届けの一覧（ポップオーバー）を出して選ぶ", "Tài khoản pháp nhân, tất cả 拠点, bấm ô 10/13 (3 đơn: 大阪 冷蔵・横浜 冷蔵・横浜 冷凍). Quyết định (Q-H2): hiện danh sách đơn trong ngày (popover) dưới ô để chọn"],
     "items": [
         {"no": "14", "ja": "その日のお届けの一覧", "vi": "Danh sách đơn giao trong ngày", "sel": ".es-calpop", "kind": "area", "trig": "show",
          "cond": ["押したマスの日に2件以上のお届けがあるとき（法人アカウント・すべての拠点）", "Khi ngày của ô vừa bấm có từ 2 đơn giao (tài khoản pháp nhân, tất cả 拠点)"],
          "detail": ["マスの近くに小さな一覧（ポップオーバー）を出す。見出し「{YYYY-MM-DD（曜）} のお届け」。外を押すか Esc で閉じる。1件のときは出さずに詳細へ", "Hiện danh sách nhỏ (popover) cạnh ô. Tiêu đề \"{YYYY-MM-DD（曜）} のお届け\". Bấm ra ngoài hoặc Esc để đóng. Chỉ 1 đơn thì không hiện mà mở thẳng chi tiết"]},
         {"no": "14.1", "ja": "一覧の行（拠点・温度帯・状態）", "vi": "Dòng danh sách (拠点, 温度帯, trạng thái)", "sel": ".es-calpop__item", "kind": "link", "trig": "click",
          "detail": ["1件＝1行：「{拠点} {温度帯} {食数}」＋状態のバッジ（マスと同じ）。並びは拠点ID の昇順、同じ拠点は 冷蔵→冷凍→資材。押すとそのお届けの詳細", "1 đơn = 1 dòng: \"{拠点} {温度帯} {số suất}\" + badge trạng thái (như trên ô). Sắp theo 拠点ID tăng dần, cùng 拠点 thì 冷蔵→冷凍→資材. Bấm mở chi tiết đơn đó"]},
     ]},
    # ------------------------------------------------------------ 011 確認が必要なお届け 0件
    {"id": "011", "code": "CW_HOME_001", "state": ["お知らせ 0件／ご確認ください 0件", "Thông báo 0 mục / ご確認ください 0 mục"],
     "url": "/corp", "setup": _SEL_SITE % "CU00902", "full": True, "wait": 1200,
     "note": ["株式会社サンプル（CU00001）で名古屋営業所（10月分から休止）に絞り込んだ状態。「ご確認ください」が0件（締切の警告も確認が必要なお届けもない）。「すべての拠点」では④申請できる予定（11月分・締切 10/15 の3週間前から）が出るので0件にならない。「お知らせ」が0件のときも同じ形（I203）で出す（見本データではお知らせが2件あるので撮れない）", "株式会社サンプル (CU00001) lọc 名古屋営業所 (tạm dừng từ tháng 10). 「ご確認ください」 0 mục (không có cảnh báo hạn chót lẫn đơn cần xác nhận). Với \"すべての拠点\" sẽ có ④ lịch có thể xin đổi (tháng 11, từ 3 tuần trước hạn 10/15) nên không về 0. \"お知らせ\" 0 mục cũng hiện cùng dạng (I203) (dữ liệu mẫu có 2 thông báo nên không chụp được)"],
     "items": [
         {"no": "15", "ja": "0件の表示（ご確認ください）", "vi": "Hiển thị 0 mục (ご確認ください)", "sel": ".es-empty", "kind": "label", "trig": "view", "err": ["I202", "I203"],
          "detail": ["「ご確認ください」に締切の警告（No.10）も確認が必要なお届けの行（No.11）もないとき、アイコン（ベル）と I202。警告だけがあるときは警告の行だけで I202 は出さない。お知らせが0件のときは同じ形で I203", "Khi 「ご確認ください」 không có cảnh báo hạn chót (No.10) lẫn dòng đơn cần xác nhận (No.11): icon (chuông) và I202. Chỉ có cảnh báo thì hiện mỗi dòng cảnh báo, không hiện I202. Thông báo 0 mục hiện cùng dạng với I203"]},
     ]},
    # ------------------------------------------------------------ 012 解約後（参照のみ）
    {"id": "012", "code": "CW_HOME_001", "state": ["解約後（参照のみ）", "Sau giải ước (chỉ xem)"],
     "url": "/corp", "today": "2026/10/10", "setup": _SET_RO + _NEXT, "full": True, "wait": 1200,
     "note": ["デモの今日を 2026/10/10（状態 006 と同じ。ふつうならご注文がまだの警告が出る日）にし、デモ帯の「デモの表示」を「解約後（参照のみ）」にして「次の月」を押した。ご注文がまだの警告・④申請できる予定の行・「申請できます」の説明は出ない。見出しの下に黄色い参照のみの帯が出る（版1.4）。ほかの状態は同じタブで参照のみのままになるため、この状態は最後に撮る",
              "Đặt \"hôm nay\" của demo = 2026/10/10 (như trạng thái 006, ngày bình thường có cảnh báo chưa nhập đơn), chọn 「デモの表示」 ở thanh demo là 「解約後（参照のみ）」 rồi bấm \"次の月\". Không hiện cảnh báo chưa nhập đơn, dòng ④ lịch có thể xin đổi, câu \"xin đổi được\". Dưới tiêu đề hiện dải vàng \"chỉ xem\" (版1.4). Các trạng thái khác cùng tab vẫn ở chế độ chỉ xem nên trạng thái này chụp cuối cùng"],
     "items": [
         {"no": "18", "ja": "参照のみの帯", "vi": "Dải \"chỉ xem\"", "sel": ".es-inline--warning::ご契約は", "kind": "label", "trig": "view",
          "cond": ["解約後（参照のみ）のアカウントだけ", "Chỉ tài khoản sau giải ước (chỉ xem)"],
          "detail": ["見出しの下の黄色い帯（ほかの法人Web の画面と同じ文）。見出し：「ご契約は {終了日} に終了しました。{入金期限}（最後のご請求の入金期限）まで参照のみでご利用いただけます。」。本文：「参照のみの期間は、お届け日の変更の申請・ご提案へのご返事はできません。お届けの確認はできます。」", "Dải vàng dưới tiêu đề (cùng câu với các màn 法人Web khác). Tiêu đề: \"ご契約は {終了日} に終了しました。{hạn thanh toán}（最後のご請求の入金期限）まで参照のみでご利用いただけます。\". Nội dung: \"参照のみの期間は、お届け日の変更の申請・ご提案へのご返事はできません。お届けの確認はできます。\""]},
         {"no": "19", "ja": "ご確認ください（解約後）", "vi": "ご確認ください (sau giải ước)", "sel": "h2::ご確認ください^2", "kind": "area", "trig": "view",
          "cond": ["解約後（参照のみ）のアカウント", "Tài khoản sau giải ước (chỉ xem)"],
          "detail": ["締切の警告（No.10）・④申請できる予定の行（No.11.4）・「お届け日の変更を申請できるのは…」の説明（No.5.2）を出さない。①ご返事・②届かなかった・③申請の結果の行は出す（押すとお届け詳細。そこでもご返事はできない：CW_DLV No.10.8）。月の説明（No.3.6）は「{n}月分（{A1}〜）は予定です。」だけ", "Không hiện cảnh báo hạn chót (No.10), dòng ④ lịch có thể xin đổi (No.11.4), câu \"お届け日の変更を申請できるのは…\" (No.5.2). Vẫn hiện dòng ① trả lời, ② giao thiếu / trễ, ③ kết quả yêu cầu (bấm mở chi tiết, ở đó cũng không trả lời được: CW_DLV No.10.8). Ghi chú tháng (No.3.6) chỉ \"{n}月分（{A1}〜）は予定です。\""]},
     ]},
]
