# -*- coding: utf-8 -*-
"""
法人Web 月次注文 ＞ 注文履歴（CW_HIST）。元：app/corp/order/history/page.tsx（一覧：商品注文／資材注文）・
app/corp/order/history/[site]/[ym]/page.tsx（詳細）・app/corp/order/_components/modals.tsx（変更履歴）・
lib/corp/order/{logic,fromDomain}.ts・lib/corp/areas/corp-order.ts・app/corp/_ui/csv.tsx。
決定：docs/決定台帳.md E 2026-10-05（注文履歴の並び＝対象年月の降順・納品書は注文履歴からは出さない（版 1.3・お届け詳細だけ）・CSV出力・参照のみは注文できない）、
決定_STEP5回答_法人Web_20261001 Q5（納品書は資材は除く。月・拠点ごとの納品書は版 1.3 で注文履歴から外した）。
版 1.1（hong 回答 2026-10-05・版1.0レビュー。台帳 E「法人Web 版 1.0 のレビュー（商品注文・資材注文・注文履歴）」⑥⑩・「法人Web 版 1.0 のレビュー（ホーム・お届け詳細）」⑨・「納品書のテンプレート」）：
メニューID／操作は受付中なら商品注文（編集）・締切後なら詳細（参照）、納品書は便ごとの表を縦に並べ最後に月の合計（金額・資材なし・改ページ・ページ番号）、便ごとの納品書はお届け詳細からも、
資材のお届け予定日・送り状番号は運営が資材注文管理で入れてから（受付簿 No.153・No.154）。
"""

TITLE = ["注文履歴（CW_HIST）", "Lịch sử đơn hàng (CW_HIST)"]
SHEET = ["注文履歴", "Lịch sử đơn hàng"]
BASENAME = "画面設計書_CW_HIST_注文履歴"
IMG_PREFIX = "CW_HIST"
OUT_DIR = "CW_HIST_注文履歴"
CODE_NOTE = ["Screen Code は台帳 E 2026-10-05 の決まり：CW_<機能略>_<3桁>", "Screen Code theo 台帳 E 2026-10-05: CW_<機能略>_<3 chữ số>"]
SITE = "corp"
SYSTEM = {"ja": "法人Web", "vi": "Web pháp nhân (法人Web)"}
AUTHOR = "Claude／確認：hong"
CREATED = "2026-10-05"
DEMO_FILE = "http://localhost:3000"
LOGIN = {"site": "corp", "loginId": "CU00001"}

DECISIONS = [
    {"date": "2026-10-05", "target": "CW_HIST_001 No.5.9",
     "q": ["画面の文言で「ESキッチン」「ES STATION」をどう使い分けるか（状態「ESキッチン入力済み」など）", "Dùng \"ESキッチン\" và \"ES STATION\" thế nào trong câu chữ (ví dụ trạng thái \"ESキッチン入力済み\")"],
     "a": ["「ESキッチン」＝お客様（運営会社）の名前、「ES STATION」＝システムの名前。「ESSTATION」「ESステーション」は使わない",
           "\"ESキッチン\" = tên công ty vận hành, \"ES STATION\" = tên hệ thống. Không dùng \"ESSTATION\", \"ESステーション\""],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-C1）"},
    {"date": "2026-10-05", "target": "CW_HIST_002 No.18",
     "q": ["解約後（参照のみ）のアカウントは受付中の月の注文を変更できるか", "Tài khoản sau khi hủy hợp đồng (chỉ xem) có sửa đơn của tháng đang nhận được không"],
     "a": ["できない。参照のみでできるのは棚卸報告だけ。「注文を変更」のボタンを出さない（一覧の鉛筆も同じ）",
           "Không. Chỉ xem thì chỉ làm được 棚卸報告. Không hiện nút \"注文を変更\" (biểu tượng bút chì ở danh sách cũng vậy)"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-C2）"},
    {"date": "2026-10-05", "target": "CW_HIST_001 No.2",
     "q": ["注文履歴に「CSV出力」を置くか（CSV入出力_定義 行148）", "Có đặt nút \"CSV出力\" ở 注文履歴 không (CSV入出力_定義 dòng 148)"],
     "a": ["置く。P-CSV-OUT のとおり（検索条件の全件・列は画面の一覧＋文書の全項目）", "Có. Theo P-CSV-OUT (toàn bộ dòng theo điều kiện tìm kiếm; cột = danh sách màn hình + mọi mục của văn bản)"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-C3）"},
    {"date": "2026-10-05", "target": "CW_HIST_001 No.5",
     "q": ["注文履歴の一覧の初期の並び", "Thứ tự ban đầu của danh sách 注文履歴"],
     "a": ["対象年月の降順（同じ月は拠点ID の昇順）。資材注文は注文日の降順", "対象年月 giảm dần (cùng tháng thì 拠点ID tăng dần). 資材注文: ngày đặt giảm dần"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-O9）"},
    {"date": "2026-10-05", "target": "CW_HIST_001 No.5.10",
     "q": ["納品書（PDF）のボタンをお届け詳細と注文履歴のどちらに置くか", "Nút 納品書 (PDF) đặt ở お届け詳細 hay 注文履歴"],
     "a": ["注文履歴の行（拠点×対象月）だけ。お届け詳細には置かない。月・拠点ごと・資材は除く",
           "Chỉ ở dòng 注文履歴 (chi nhánh × tháng). Không đặt ở お届け詳細. Theo tháng và chi nhánh, không gồm vật tư"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-D3）"},
    {"date": "2026-10-05", "target": "CW_HIST_001 No.5.2・No.5.11",
     "q": ["一覧のメニューID・操作（鉛筆）の押す先（版 1.0 はメニューID はいつも詳細、鉛筆は受付中だけ商品注文へ）", "Đích bấm của メニューID và thao tác (bút chì) ở danh sách (bản 1.0: メニューID luôn mở chi tiết, bút chì chỉ khi đang nhận đơn)"],
     "a": ["受付中の月は商品注文（編集）、締切後の月は注文履歴 詳細（参照）。締切後は商品注文の画面を出さない（注文履歴 詳細が締切後の唯一の参照の画面）。旧「受付中は鉛筆で商品注文へ」を置き換え", "Tháng đang nhận đơn: 商品注文 (sửa); tháng đã chốt: 注文履歴 詳細 (xem). Sau hạn chốt không hiện màn 商品注文 (注文履歴 詳細 là màn xem duy nhất). Thay quyết định cũ \"đang nhận thì bút chì sang 商品注文\""],
     "src": "hong 回答 2026-10-05 版1.0レビュー（台帳 E ⑥）"},
    {"date": "2026-10-05", "target": "CW_HIST_001 No.15",
     "q": ["月・拠点ごとの納品書の中身（版 1.0 は「今の納品書と同じ形式」で中身の定義なし）", "Nội dung phiếu giao hàng theo tháng, chi nhánh (bản 1.0: \"cùng mẫu hiện hành\", chưa định nghĩa)"],
     "a": ["台帳「納品書のテンプレート」のとおり：便ごとの表を縦に並べ、最後に月の合計。金額は載せない・資材は載せない。明細が収まらなければ改ページ・ページ番号。現行の納品書との差はお客様（運営）に確認（OPEN）", "Theo 台帳「納品書のテンプレート」: bảng theo chuyến xếp dọc, cuối cùng tổng của tháng. Không số tiền, không vật tư. Không vừa trang thì ngắt trang, có số trang. Khác biệt với mẫu hiện hành xác nhận với khách hàng (運営) (OPEN)"],
     "src": "hong「Claude が決める」2026-10-05・台帳「納品書のテンプレート」"},
    {"date": "2026-10-05", "target": "CW_HIST_001 No.5.10",
     "q": ["納品書は注文履歴の行だけか（2026/10/05 Q-D3）", "Phiếu giao hàng chỉ ở dòng 注文履歴 (2026/10/05 Q-D3)?"],
     "a": ["注文履歴は月・拠点ごと。便ごとの納品書（PDF）はお届け詳細からも出せる（Q-D3「お届け詳細には置かない」を置き換え）", "注文履歴 theo tháng, chi nhánh. Phiếu theo chuyến (PDF) xuất được cả từ お届け詳細 (thay Q-D3 \"không đặt ở お届け詳細\")"],
     "src": "hong 回答 2026-10-05 版1.0レビュー（台帳 E ホーム・お届け詳細 ⑨）"},
    {"date": "2026-10-05", "target": "CW_HIST_001 No.9.5・No.30",
     "q": ["資材注文のお届け予定日をいつ出すか（版 1.0 は登録日の2日後をいつも出す）", "Ngày giao dự kiến của đơn vật tư hiện khi nào (bản 1.0: luôn hiện ngày đăng ký + 2)"],
     "a": ["運営が資材注文管理で送り状番号・発送日を入れ、リードタイムから出せるときだけ。それまでは出さない（「—」）。送り状番号も列で出す。リードタイムの日数は運営Web 側で決める（受付簿 No.154）", "Chỉ khi 運営 đã nhập 送り状番号, 発送日 ở 資材注文管理 và tính được từ lead time. Trước đó không hiện (\"—\"). Thêm cột 送り状番号. Số ngày lead time quyết định ở phía 運営Web (受付簿 No.154)"],
     "src": "hong 回答 2026-10-05 版1.0レビュー（台帳 E ⑩）"},
    {"date": "2026-10-05", "target": "CW_HIST_001 No.5.10・旧 状態 005（納品書）",
     "q": ["納品書を注文履歴（月・拠点ごと）にも置くか", "Có đặt 納品書 ở 注文履歴 (theo tháng / chi nhánh) không"],
     "a": ["置かない。納品書はお届け詳細（便ごと）だけで出す。注文履歴の「納品書」の列・ボタン・モーダルは外す", "Không đặt. 納品書 chỉ xuất ở お届け詳細 (theo từng chuyến). Bỏ cột / nút / modal 「納品書」 ở 注文履歴"],
     "src": "hong 回答 2026/10/05（版 1.1 のレビュー・受付簿 No.156）。版 1.0 レビュー⑨（注文履歴は月・拠点ごと）を置き換え"},
    {"date": "2026-10-05", "target": "CW_HIST_002 No.17・No.34・No.29",
     "q": ["注文履歴 詳細の変更履歴を、モーダル（「変更履歴確認」ボタン）で見せるか、画面内のタブにするか", "Lịch sử thay đổi ở 注文履歴 詳細 hiện bằng modal (nút 「変更履歴確認」) hay tab trong màn hình"],
     "a": ["タブにする（商品注文・資材注文と同じ）。「注文」「変更履歴」の2つのタブ（P-TAB・URL ?tab=history）。「変更履歴確認」ボタンとモーダルはなくす", "Dùng tab (giống 商品注文, 資材注文). Hai tab 「注文」 「変更履歴」 (P-TAB, URL ?tab=history). Bỏ nút 「変更履歴確認」 và modal"],
     "src": "hong 回答 2026-10-05（版 1.1 のレビュー 2回目・受付簿 No.157）"},
    {"date": "2026-10-05", "target": "CW_HIST_002 No.22・No.22.1",
     "q": ["資材の表の見本データが0件で、設計書に「見本がない」と注記していた件", "Dữ liệu mẫu bảng vật tư là 0 dòng, tài liệu ghi chú \"không có mẫu\""],
     "a": ["注記で逃げず、見本データを作る：大阪支店に 2026-11 分の資材注文（MO-2610-0014）を入れ、詳細に資材の表が出るようにする", "Không né bằng ghi chú; tạo dữ liệu mẫu: thêm đơn vật tư của 大阪支店 cho 2026-11 (MO-2610-0014) để màn chi tiết hiện bảng vật tư"],
     "src": "hong 回答 2026-10-05（版 1.1 のレビュー 2回目・受付簿 No.157）"},
]

# 版 1.1 のコードの直し（受付簿 No.153・No.154 の法人Web 側）は 2026-10-05 実装済：app/corp/order/history/**（納品書は _components/MonthlyNote.tsx）・lib/corp/order/**
CHANGES = [
    {"ver": "1.5", "date": "2026-10-06", "no": "9.5", "type": "変更",
     "before": ["お届け予定日＝発送日＋リードタイム。日数は運営Web 側で決める（未決・コードは仮に 2日。OPEN）", "Ngày giao dự kiến = 発送日 + lead time. Số ngày do 運営Web quyết định (chưa chốt, code tạm 2 ngày; OPEN)"],
     "after": ["リードタイムは契約の配送区分「資材」の日数（0〜7日・既定 2日）。OPEN を外す", "Lead time là số ngày của 配送区分 「資材」 trong hợp đồng (0〜7 ngày, mặc định 2). Bỏ OPEN"],
     "reason": ["hong 回答 2026-10-06（受付簿 No.158）", "hong trả lời 2026-10-06 (受付簿 No.158)"],
     "impact": ["お届け予定日の計算で、拠点の契約の配送区分「資材」の日数を使う（lib/domain/materialLead.ts）", "Dùng số ngày của 配送区分 「資材」 trong hợp đồng của chi nhánh để tính ngày giao dự kiến (lib/domain/materialLead.ts)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "34", "type": "追加",
     "before": ["（なし）", "(không có)"],
     "after": ["見出しの下に「注文」「変更履歴」のタブ。URL の ?tab=（history）で持つ", "Dưới tiêu đề có tab 「注文」 「変更履歴」, lưu trong URL ?tab= (history)"],
     "reason": ["hong 回答 2026-10-05（版 1.1 のレビュー 2回目・受付簿 No.157）：変更履歴は注文履歴 詳細でもタブにする", "hong trả lời 2026-10-05 (review bản 1.1 lần 2, 受付簿 No.157): 変更履歴 ở 注文履歴 詳細 cũng là tab"],
     "impact": ["タブ部品を足す。「注文」のタブに注文の情報・商品・資材、「変更履歴」のタブに変更履歴の表", "Thêm thành phần tab. Tab 「注文」 chứa thông tin đơn, sản phẩm, vật tư; tab 「変更履歴」 chứa bảng lịch sử"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "17", "type": "削除",
     "before": ["見出しの「変更履歴確認」ボタン（変更履歴のモーダルを開く）", "Nút 「変更履歴確認」 ở tiêu đề (mở modal lịch sử thay đổi)"],
     "after": ["削除（変更履歴は画面内のタブ・No.34）", "Xóa (変更履歴 là tab trong màn hình, No.34)"],
     "reason": ["hong 回答 2026-10-05（受付簿 No.157）", "hong trả lời 2026-10-05 (受付簿 No.157)"],
     "impact": ["ボタンとモーダル（LogDialog）をなくす", "Bỏ nút và modal (LogDialog)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["23", "25"], "type": "変更",
     "before": ["操作ボタンは「変更履歴確認」「戻る」だけ", "Nút thao tác chỉ có 「変更履歴確認」 và 「戻る」"],
     "after": ["操作ボタンは「戻る」だけ（変更履歴は画面内のタブ・No.34）。受付中で変更できるときだけ「注文を変更」が加わる", "Nút thao tác chỉ còn 「戻る」 (lịch sử thay đổi là tab trong màn hình, No.34). Chỉ khi đang nhận đơn và sửa được mới có thêm 「注文を変更」"],
     "reason": ["変更履歴確認ボタンの廃止（受付簿 No.157）", "Bỏ nút 変更履歴確認 (受付簿 No.157)"],
     "impact": ["なし（説明の直しのみ）", "Không (chỉ sửa mô tả)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["29", "29.1"], "type": "変更",
     "before": ["変更履歴のモーダル（見出しに「拠点名・対象年月」・閉じる）。表の説明は7列だがコードは4列", "Modal lịch sử (tiêu đề có 「tên chi nhánh・対象年月」, nút 閉じる). Bảng mô tả 7 cột nhưng code 4 cột"],
     "after": ["画面内のタブ「変更履歴」の中身（状態 010）。表は P-HIST の7列（コードも7列に直した）。0件は I01", "Nội dung tab 「変更履歴」 trong màn hình (trạng thái 010). Bảng 7 cột của P-HIST (code cũng đã sửa 7 cột). 0 dòng: I01"],
     "reason": ["モーダルをやめてタブにする（受付簿 No.157）。コードは P-HIST の列に直してあり、デモ注記は不要になった", "Bỏ modal chuyển sang tab (受付簿 No.157). Code đã sửa theo cột P-HIST nên không cần ghi chú demo"],
     "impact": ["状態 010 を「変更履歴（タブ・過去の月）」に変える（日本語の説明の「おまかせ注文（基準数）」は「自動注文（基準数）」に統一）", "Đổi trạng thái 010 thành 「変更履歴（タブ・過去の月）」 (câu mô tả 「おまかせ注文（基準数）」 thống nhất thành 「自動注文（基準数）」)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "29.2", "type": "削除",
     "before": ["モーダルの「閉じる」ボタン", "Nút 「閉じる」 của modal"],
     "after": ["削除（タブにはない）", "Xóa (tab không có)"],
     "reason": ["hong 回答 2026-10-05（受付簿 No.157）", "hong trả lời 2026-10-05 (受付簿 No.157)"],
     "impact": ["なし", "Không"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["22", "22.1"], "type": "変更",
     "before": ["資材の表の見本がなく（0件）、デモ注記で「空表示になる」と書いていた。説明は「列：No・資材注文No・資材名・注文数量」", "Không có dữ liệu mẫu cho bảng vật tư (0 dòng), tài liệu ghi chú \"hiện trạng thái trống\". Mô tả: \"Cột: No, 資材注文No, 資材名, 注文数量\""],
     "after": ["見本データに大阪支店 2026-11 分の資材注文 MO-2610-0014 を入れ、表が出る。資材注文ごとに見出しの行（資材注文No・区分・注文日・お届け予定日・状態）と表（No・資材名・注文数量）。0件は I01", "Thêm đơn vật tư MO-2610-0014 của 大阪支店 cho 2026-11 vào dữ liệu mẫu nên bảng hiện ra. Mỗi đơn vật tư có dòng tiêu đề (資材注文No, loại, ngày đặt, ngày giao dự kiến, trạng thái) và bảng (No, 資材名, 注文数量). 0 dòng: I01"],
     "reason": ["hong 回答 2026-10-05（受付簿 No.157）：「demo_ok で逃げず、見本データを作る」。説明も実際の画面（資材注文No は見出しの行）に合わせた", "hong trả lời 2026-10-05 (受付簿 No.157): \"không né bằng demo_ok, hãy tạo dữ liệu mẫu\". Mô tả cũng chỉnh theo màn hình thực (資材注文No ở dòng tiêu đề)"],
     "impact": ["共通データ（delivery.materialOrders）に MO-2610-0014 を足した（2026-11 のサイクル月を決め打ち）。デモ注記を削除。0件のときの文は I01「表示するデータがありません。」に統一（旧：「資材のご注文はありません」）", "Thêm MO-2610-0014 vào dữ liệu chung (delivery.materialOrders) (cố định tháng chu kỳ 2026-11). Bỏ ghi chú demo. Câu khi 0 dòng thống nhất thành I01 「表示するデータがありません。」 (cũ: 「資材のご注文はありません」)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["3", "11", "21.2"], "type": "変更",
     "before": ["デモ注記あり：切替の URL・資材注文のページ送り・価格の列名「定価（税込）」はコードが未対応", "Có ghi chú demo: URL chuyển đổi, phân trang của 資材注文, tên cột giá 「定価（税込）」 code chưa làm"],
     "after": ["コードも対応済み。切替は URL の ?tab=mat（P-TAB）、資材注文は10件ずつのページ送り、詳細の価格の列名は「定価（税込）」", "Code đã làm. Chuyển đổi bằng URL ?tab=mat (P-TAB), 資材注文 phân trang 10 dòng, tên cột giá ở chi tiết là 「定価（税込）」"],
     "reason": ["コードが台帳 E 2026-10-05 に追いついた（受付簿 No.77・No.83・No.157）。デモ注記だけを外す", "Code đã theo kịp 台帳 E 2026-10-05 (受付簿 No.77, No.83, No.157). Chỉ bỏ ghi chú demo"],
     "impact": ["旧 URL（?kind=mat）は ?tab=mat に変えた（古い URL も開ける）", "URL cũ (?kind=mat) đổi thành ?tab=mat (URL cũ vẫn mở được)"]},
    {"ver": "1.3", "date": "2026-10-05", "no": "5.10", "type": "削除",
     "before": ["一覧の「納品書」の列（ボタンで納品書モーダルを開く）", "Cột 「納品書」 trong danh sách (nút mở modal 納品書)"],
     "after": ["列ごと外す（一覧は 11列 → 10列）", "Bỏ cả cột (danh sách 11 cột → 10 cột)"],
     "reason": ["hong 回答 2026-10-05（版 1.1 のレビュー・受付簿 No.156）：納品書はお届け詳細だけで出す", "hong trả lời 2026-10-05 (review bản 1.1, 受付簿 No.156): 納品書 chỉ xuất ở お届け詳細"],
     "impact": ["注文履歴の「納品書」の列・ボタン・モーダルと、月・拠点ごとの納品書の作成（dnote）を削除。S207・E318 は注文履歴では使わない", "Xóa cột / nút / modal 「納品書」 và việc tạo 納品書 theo tháng·chi nhánh (dnote) ở 注文履歴. 注文履歴 không dùng S207・E318"]},
    {"ver": "1.3", "date": "2026-10-05", "no": ["15", "15.1", "15.2", "15.3", "15.4", "15.5", "31", "32"], "type": "削除",
     "before": ["納品書のモーダル（状態 005）：見出し・注記・便ごとの表・PDF・便の見出し・月の合計", "Modal 納品書 (trạng thái 005): tiêu đề, ghi chú, bảng theo chuyến, PDF, tiêu đề chuyến, tổng tháng"],
     "after": ["削除（状態 005 は欠番）", "Xóa (trạng thái 005 để trống số)"],
     "reason": ["納品書は注文履歴から出さない（台帳 F・版 1.1 のレビュー①）", "Không xuất 納品書 từ 注文履歴 (台帳 F, review bản 1.1 ①)"],
     "impact": ["便ごとの納品書（PDF）は お届け詳細 CW_DLV の No.17・25 を使う", "Dùng 納品書 từng chuyến (PDF) ở CW_DLV No.17・25 của お届け詳細"]},
    {"ver": "1.2", "date": "2026-10-05", "no": "9.5", "type": "変更",
     "before": ["受付簿 No.136（リードタイムは運営Web 側で決める）", "受付簿 No.136 (lead time do 運営Web quyết định)"],
     "after": ["受付簿 No.154。リードタイムの日数は未決（コードは仮に 2日）で、OPEN に追加", "受付簿 No.154. Số ngày lead time chưa chốt (code tạm 2 ngày), thêm vào OPEN"],
     "reason": ["受付簿の番号の付け直し（No.136 → No.154）。リードタイムの日数が未決のため OPEN に記録", "Đánh số lại 受付簿 (No.136 → No.154). Lead time chưa chốt nên ghi vào OPEN"],
     "impact": ["画面の動きは変わらない。日数が決まったら MATERIAL_LEAD_DAYS を直す", "Hành vi màn hình không đổi. Khi chốt số ngày thì sửa MATERIAL_LEAD_DAYS"]},
    {"ver": "1.2", "date": "2026-10-05", "no": "33", "type": "追加",
     "before": ["（なし）", "(không có)"],
     "after": ["資材便の「発送日」の列（注文日の右）。運営Web の資材注文管理で発送日を入れた行だけ表示、それまでは「—」", "Cột \"発送日\" của 資材便 (bên phải 注文日). Chỉ hiện ở dòng đã nhập 発送日 trong 資材注文管理 của 運営Web, trước đó \"—\""],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー ⑩（受付簿 No.154）", "hong trả lời 2026-10-05 review bản 1.0 ⑩ (受付簿 No.154)"],
     "impact": ["資材便の行に発送日の列を足し、お届け予定日は発送日＋リードタイムで出す", "Thêm cột 発送日 cho dòng 資材便; ngày giao dự kiến = 発送日 + lead time"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "5.2", "type": "変更",
     "before": ["押すと注文履歴 詳細（CW_HIST_002）へ", "Bấm thì mở 注文履歴 詳細 (CW_HIST_002)"],
     "after": ["受付中の月で変更できる行は商品注文（CW_ORDER_001・編集）へ、締切後の月と変更できない行は注文履歴 詳細（参照）へ", "Tháng đang nhận và sửa được thì mở 商品注文 (CW_ORDER_001, sửa); tháng đã chốt và dòng không sửa được thì mở 注文履歴 詳細 (xem)"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：メニューID は受付中なら商品注文（編集）、締切後なら詳細", "hong trả lời 2026-10-05 (review bản 1.0): メニューID đang nhận thì 商品注文 (sửa), đã chốt thì chi tiết"],
     "impact": ["メニューID のリンク先を行の状態で分ける（受付簿 No.153）", "Tách đích link của メニューID theo trạng thái dòng (受付簿 No.153)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "5.11", "type": "変更",
     "before": ["受付中の行だけ鉛筆 → 商品注文へ。締切後は空", "Chỉ dòng đang nhận có bút chì → 商品注文. Sau hạn để trống"],
     "after": ["受付中で変更できる行は鉛筆（商品注文・編集）、それ以外は目のアイコン（注文履歴 詳細・参照）。休止中は空", "Đang nhận và sửa được: bút chì (商品注文, sửa); còn lại: biểu tượng mắt (注文履歴 詳細, xem). 休止中 để trống"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：受付中なら商品注文（編集）、締切後なら詳細（参照）。旧「受付中は鉛筆で商品注文へ」を置き換え", "hong trả lời 2026-10-05 (review bản 1.0): đang nhận thì 商品注文 (sửa), đã chốt thì chi tiết (xem). Thay quyết định cũ"],
     "impact": ["操作の列に参照のアイコンを足し、締切後の行は詳細へ。項目名を「操作（注文を変更／参照）」に（受付簿 No.153）", "Thêm biểu tượng xem ở cột thao tác; dòng đã chốt sang chi tiết. Đổi tên mục thành \"操作（注文を変更／参照）\" (受付簿 No.153)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "5.10", "type": "変更",
     "before": ["月・拠点ごと・資材は載せない（納品書は注文履歴の行だけ）", "Theo tháng, chi nhánh, không gồm vật tư (phiếu chỉ ở dòng 注文履歴)"],
     "after": ["月・拠点ごと（便ごとの表を縦に並べ、最後に月の合計）・金額と資材は載せない。便ごとの納品書はお届け詳細（CW_DLV）から出す", "Theo tháng, chi nhánh (bảng theo chuyến xếp dọc, cuối cùng tổng tháng), không số tiền, không vật tư. Phiếu theo chuyến xuất từ お届け詳細 (CW_DLV)"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：納品書は便ごとにお届け詳細からも出せる（Q-D3 を置き換え）・台帳「納品書のテンプレート」", "hong trả lời 2026-10-05 (review bản 1.0): phiếu theo chuyến xuất được từ お届け詳細 (thay Q-D3); 台帳「納品書のテンプレート」"],
     "impact": ["この画面は変わらない（お届け詳細 CW_DLV に便ごとの納品書を足す）。説明の追記だけ", "Màn này không đổi (thêm phiếu theo chuyến ở お届け詳細 CW_DLV). Chỉ bổ sung mô tả"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "7", "type": "変更",
     "before": ["列：資材注文No・注文区分・拠点ID・拠点名・注文日・お届け予定日・資材・配送状態＋文書の全項目", "Cột: 資材注文No, 注文区分, 拠点ID, 拠点名, 注文日, お届け予定日, 資材, 配送状態 + mọi mục của văn bản"],
     "after": ["発送日・送り状番号の列を足す（運営がまだ入れていなければ空）", "Thêm cột 発送日, 送り状番号 (để trống nếu 運営 chưa nhập)"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：運営が資材注文管理で送り状番号・発送日を入れる", "hong trả lời 2026-10-05 (review bản 1.0): 運営 nhập 送り状番号, 発送日 ở 資材注文管理"],
     "impact": ["CSV の列に 発送日・送り状番号 を足す（受付簿 No.154）", "Thêm cột 発送日, 送り状番号 vào CSV (受付簿 No.154)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "9.5", "type": "変更",
     "before": ["登録日の2日後（日曜・配送休日は翌日へ）をいつも出す", "Luôn hiện ngày đăng ký + 2 (Chủ nhật / ngày nghỉ giao thì lùi)"],
     "after": ["運営が資材注文管理で送り状番号・発送日を入れ、発送日＋リードタイムで出せる行だけ。それまでは「—」（ツールチップ I223）", "Chỉ dòng 運営 đã nhập 送り状番号, 発送日 và tính được 発送日 + lead time. Trước đó \"—\" (tooltip I223)"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：お届け予定日は送り状番号・発送日とリードタイムから出せるときだけ", "hong trả lời 2026-10-05 (review bản 1.0): ngày giao dự kiến chỉ hiện khi có 送り状番号, 発送日 và lead time"],
     "impact": ["dueOn を登録で決めず、資材注文管理の発送日＋リードタイムから出す。ない行は「—」とツールチップ I223。メッセージ I223 を足す（受付簿 No.154）", "Không gán dueOn khi đăng ký; tính từ 発送日 + lead time ở 資材注文管理. Dòng chưa có: \"—\" và tooltip I223. Thêm message I223 (受付簿 No.154)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "10", "type": "変更",
     "before": ["「配送状態は、ESキッチンが資材便の配送データから反映します。資材はいつでも注文でき、同じご利用月の2回目以降は資材の追加配送（OP000036）がかかります。」", "Câu cũ (không có お届け予定日, 送り状番号; ghi OP000036)"],
     "after": ["「…お届け予定日と送り状番号は、ESキッチンが発送の手配をすると出ます。資材はいつでも注文でき、同じご利用月の2回目以降は資材の追加配送の料金（{金額}）がかかります。」", "Thêm câu về お届け予定日, 送り状番号; cách nói về phí thống nhất với CW_MAT No.8"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：お届け予定日は発送の手配のあと・案内の言い方を資材注文と揃える", "hong trả lời 2026-10-05 (review bản 1.0): お届け予定日 sau khi sắp xếp gửi hàng; thống nhất câu với 資材注文"],
     "impact": ["注記の文言を変える（受付簿 No.153・No.154）", "Đổi câu ghi chú (受付簿 No.153, No.154)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "15", "type": "変更",
     "before": ["月・拠点ごとの数量（便ごとに分けない）", "Số lượng theo tháng, chi nhánh (không tách chuyến)"],
     "after": ["台帳「納品書のテンプレート」の形：便ごとの見出し（No.31）と表（No.15.3）を縦に並べ、最後に月の合計（No.32）。金額なし・資材なし。現行の納品書との差は OPEN（お客様（運営））", "Theo 台帳「納品書のテンプレート」: tiêu đề chuyến (No.31) và bảng (No.15.3) xếp dọc, cuối cùng tổng tháng (No.32). Không số tiền, không vật tư. Khác biệt với mẫu hiện hành: OPEN (khách hàng (運営))"],
     "reason": ["台帳「納品書のテンプレート」2026-10-05（hong「Claude が決める」）", "台帳「納品書のテンプレート」2026-10-05 (hong: Claude quyết định)"],
     "impact": ["モーダルの中身を便ごとの表＋月の合計に作り直す（受付簿 No.153）", "Làm lại nội dung modal thành bảng theo chuyến + tổng tháng (受付簿 No.153)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "15.1", "type": "変更",
     "before": ["「月・拠点ごとの納品書です（今の納品書と同じ形式・資材は載せません）。その月の納品が始まると出せます。」", "Câu cũ (\"cùng mẫu hiện hành\")"],
     "after": ["「月・拠点ごとの納品書です（便ごとの表のあとに月の合計を出します。金額と資材は載せません）。便ごとの納品書はお届け詳細から出せます。」", "Câu mới (bảng theo chuyến + tổng tháng; không số tiền, vật tư; phiếu theo chuyến ở お届け詳細)"],
     "reason": ["台帳「納品書のテンプレート」・台帳 E ⑨（便ごとはお届け詳細）", "台帳「納品書のテンプレート」, 台帳 E ⑨ (theo chuyến ở お届け詳細)"],
     "impact": ["注記の文言を変える（受付簿 No.153）", "Đổi câu ghi chú (受付簿 No.153)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "15.3", "type": "変更",
     "before": ["1つの表。列：No・商品名・保存方法・数量（月の全便の合計）", "1 bảng. Cột: No, 商品名, 保存方法, 数量 (tổng mọi chuyến trong tháng)"],
     "after": ["便ごとに1つの表。列：No・商品名・ご注文数・お届け数・備考（代替品（元：〇〇）／補償／不足）。表の下に数量の合計と注記。保存方法・金額の列はない", "Mỗi chuyến 1 bảng. Cột: No, 商品名, ご注文数, お届け数, 備考 (代替品（元：〇〇）／補償／不足). Dưới bảng: tổng số lượng và ghi chú. Không có cột 保存方法, số tiền"],
     "reason": ["台帳「納品書のテンプレート」2026-10-05（hong「Claude が決める」）", "Theo 台帳「納品書のテンプレート」2026-10-05 (hong: Claude quyết định)"],
     "impact": ["表の列を変え、便ごとに分ける。項目名を「納品書の表（便ごと）」に（受付簿 No.153）", "Đổi cột và tách bảng theo chuyến. Đổi tên mục thành \"納品書の表（便ごと）\" (受付簿 No.153)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "15.5", "type": "変更",
     "before": ["今の納品書のテンプレート（現行の様式）で PDF。拠点ごとに改ページ", "PDF theo mẫu hiện hành. Ngắt trang theo chi nhánh"],
     "after": ["台帳「納品書のテンプレート」の PDF（A4 縦・見出し・発行日・納品書番号・宛先・発行元・便ごとの表・月の合計・金額なし・資材なし・改ページとページ番号）。失敗は E318", "PDF theo 台帳「納品書のテンプレート」(A4 dọc, tiêu đề, ngày phát hành, số phiếu, người nhận, người phát hành, bảng theo chuyến, tổng tháng, không số tiền, không vật tư, ngắt trang và số trang). Lỗi: E318"],
     "reason": ["台帳「納品書のテンプレート」2026-10-05（hong「Claude が決める」）", "Theo 台帳「納品書のテンプレート」2026-10-05 (hong: Claude quyết định)"],
     "impact": ["PDF をテンプレートの形で作る（改ページ・ページ番号 REQ-DL-316）。メッセージ E318 を足す（受付簿 No.153）", "Tạo PDF theo mẫu (ngắt trang, số trang REQ-DL-316). Thêm message E318 (受付簿 No.153)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "23", "type": "変更",
     "before": ["変更履歴確認・戻る だけ", "Chỉ có 変更履歴確認 và 戻る"],
     "after": ["同上。締切後は商品注文の画面は開かず、この画面が締切後の唯一の参照の画面", "Như cũ. Sau hạn chốt không mở 商品注文; màn này là màn xem duy nhất"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：締切後は商品注文の画面を出さず、注文履歴 詳細（参照）へ", "hong trả lời 2026-10-05 (review bản 1.0): sau hạn chốt không hiện 商品注文 mà về 注文履歴 詳細 (xem)"],
     "impact": ["締切後に商品注文の URL を開いたら注文履歴 詳細へ移す（商品注文側の直し・受付簿 No.153）", "Mở URL 商品注文 sau hạn chốt thì chuyển sang 注文履歴 詳細 (sửa ở phía 商品注文, 受付簿 No.153)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "30", "type": "追加",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：運営が資材注文管理で送り状番号・発送日を入れる → 法人Web に出す", "hong trả lời 2026-10-05 (review bản 1.0): 運営 nhập 送り状番号, 発送日 ở 資材注文管理 → hiện trên 法人Web"],
     "impact": ["資材注文の一覧に「送り状番号」の列を足す（お届け予定日の右。ないときは「—」）（受付簿 No.154）", "Thêm cột \"送り状番号\" vào danh sách đơn vật tư (bên phải お届け予定日; chưa có thì \"—\") (受付簿 No.154)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "33", "type": "追加",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー ⑩：運営が資材注文管理で入れた発送日を法人Web に出す（No.7 の CSV と同じ列を表にも）", "hong trả lời 2026-10-05 (review bản 1.0) ⑩: hiện 発送日 do 運営 nhập ở 資材注文管理 (cột như CSV No.7 cũng ở bảng)"],
     "impact": ["資材注文の一覧に「発送日」の列を足す（注文日の右。ないときは「—」）（受付簿 No.154）", "Thêm cột \"発送日\" vào danh sách đơn vật tư (bên phải 注文日; chưa có thì \"—\") (受付簿 No.154)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": ["31", "32"], "type": "追加",
     "reason": ["台帳「納品書のテンプレート」2026-10-05：便ごとの表を縦に並べ、最後に月の合計", "台帳「納品書のテンプレート」2026-10-05: bảng theo chuyến xếp dọc, cuối cùng tổng tháng"],
     "impact": ["納品書モーダル・PDF に便ごとの見出し（お届け日・温度帯・お届け方法・納品書番号）と月の合計を足す（受付簿 No.153）", "Thêm tiêu đề theo chuyến (ngày giao, nhiệt độ, cách giao, số phiếu) và tổng tháng vào modal, PDF phiếu giao hàng (受付簿 No.153)"]},
]

HIDE_ALWAYS = [".es-demo-bar", ".es-chatbot", ".es-chatbot__fab", ".od-aboutlink", "#es-review"]
STATIC_CSS = ".corp{height:auto!important}.corp-main{overflow:visible!important}.es-sidenav{height:auto!important;min-height:100vh}"
VIEWER_CSS = STATIC_CSS

SCREENS = [
    {"code": "CW_HIST_001", "ja": "注文履歴", "vi": "Lịch sử đơn hàng"},
    {"code": "CW_HIST_002", "ja": "注文履歴 詳細", "vi": "Chi tiết lịch sử đơn hàng"},
]

_WAIT = " await new Promise(r=>setTimeout(r,600));"
_CLICK_MAT = "const b=[...document.querySelectorAll('button')].find(x=>x.textContent.trim()==='資材注文'); b&&b.click();" + _WAIT
_SEARCH_NONE = ("const i=document.querySelector('.es-search input[type=text]'); if(i){const s=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set; s.call(i,'ないもの'); i.dispatchEvent(new Event('input',{bubbles:true}));}"
                + _WAIT + " const b=[...document.querySelectorAll('.es-search button')].find(x=>x.textContent.trim()==='検索'); b&&b.click();" + _WAIT)

VIEWS = [
    # ---------------------------------------------------------------- CW_HIST_001 一覧
    {"id": "001", "code": "CW_HIST_001", "state": ["商品注文（法人アカウント・初期表示）", "Đơn sản phẩm (tài khoản pháp nhân, hiển thị ban đầu)"],
     "url": "/corp/order/history", "full": True, "wait": 800,
     "note": ["株式会社サンプル（法人アカウント）。拠点×対象年月の1行。受付中の月（2026-11）が先頭。初期の並びは対象年月の降順",
              "Công ty Sample (tài khoản pháp nhân). Mỗi dòng = chi nhánh × tháng. Tháng đang nhận đơn (2026-11) ở đầu. Thứ tự ban đầu: 対象年月 giảm dần"],
     "items": [
         {"no": "1", "ja": "パンくず・タイトル", "vi": "Breadcrumb và tiêu đề", "sel": ".es-pagehead__text", "kind": "label", "trig": "view",
          "detail": ["「月次注文 / 注文履歴」・タイトル「注文履歴」", "\"月次注文 / 注文履歴\", tiêu đề \"注文履歴\""]},
         {"no": "2", "ja": "CSV出力", "vi": "Nút \"CSV出力\"", "sel": ".es-pagehead__actions button::CSV出力", "kind": "button", "trig": "click", "pattern": "P-CSV-OUT",
          "detail": ["いま適用している検索条件の全件（ページ送りの前）。商品注文：1行＝注文の1行（品番×便）。列：メニューID・対象年月・拠点ID・拠点名・ご注文の受付開始日・ご注文の締切日・自販機（あり／空）・ご注文の状態＋注文の文書（dm.order.orders）の全項目。画面名「注文履歴（商品注文）」。終わるとトースト「CSVを出力しました（{n}行・ファイル名）」。資材注文の切替中は No.7",
                     "Toàn bộ dòng theo điều kiện đang áp dụng (trước phân trang). 商品注文: 1 dòng = 1 dòng đơn (mã SP × chuyến). Cột: メニューID, 対象年月, 拠点ID, 拠点名, ご注文の受付開始日, ご注文の締切日, 自販機 (あり / trống), ご注文の状態 + mọi mục của văn bản đơn (dm.order.orders). Tên màn hình \"注文履歴（商品注文）\". Xong hiện toast \"CSVを出力しました（{n}行・tên file）\". Khi đang ở 資材注文 thì theo No.7"]},
         {"no": "3", "ja": "切替（商品注文／資材注文）", "vi": "Chuyển đổi (商品注文 / 資材注文)", "sel": ".es-card button::商品注文^", "kind": "tab", "trig": "click", "pattern": "P-TAB",
          "detail": ["押した方を塗りつぶし。切り替えると1ページ目に戻る。検索条件は切替ごとに別。URL（?tab=mat。商品注文は ?tab= なし）に持つ",
                     "Nút đang chọn tô đậm. Đổi thì về trang 1. Điều kiện tìm kiếm riêng cho từng loại. Giữ trong URL (?tab=mat; 商品注文 không có ?tab=)"]},
         {"no": "3.1", "ja": "商品注文", "vi": "Nút \"商品注文\"", "sel": ".es-card button::商品注文", "kind": "button", "trig": "click",
          "detail": ["拠点×対象年月の注文の一覧（初期）", "Danh sách đơn theo chi nhánh × tháng (mặc định)"]},
         {"no": "3.2", "ja": "資材注文", "vi": "Nút \"資材注文\"", "sel": ".es-card button::資材注文", "kind": "button", "trig": "click",
          "detail": ["資材注文（資材便）の一覧（No.8〜）", "Danh sách đơn vật tư (資材便) (No.8〜)"]},
         {"no": "4", "ja": "検索", "vi": "Khu vực tìm kiếm", "sel": ".es-search", "kind": "area", "trig": "view", "pattern": "P-LIST",
          "detail": ["「検索」か Enter で反映。「クリア」で条件を消して1ページ目へ", "Áp dụng khi nhấn \"検索\" hoặc Enter. \"クリア\" xóa điều kiện và về trang 1"]},
         {"no": "4.1", "ja": "商品名", "vi": "Tên sản phẩm", "sel": ".es-search input[type=text]", "kind": "text", "trig": "input", "req": "－",
          "len": "文字列 60", "init": ["空", "Trống"],
          "ex": ["チキンのチーズソテー", "Tên sản phẩm (khớp một phần). Hiện các tháng mà chi nhánh đã đặt sản phẩm đó với số lượng ≥ 1"],
          "valid": ["前後の空白を取る。60文字を超えたら E04", "Bỏ khoảng trắng đầu/cuối. Quá 60 ký tự thì E04"], "err": ["E04"],
          "detail": ["プレースホルダー「商品名（その商品を注文した月を探します）」。部分一致。その商品を 1 以上注文した拠点×月の行だけ残す（休止中の行は外す）",
                     "Placeholder \"商品名（その商品を注文した月を探します）\". Khớp một phần. Chỉ giữ dòng chi nhánh × tháng có đặt sản phẩm đó ≥ 1 (bỏ dòng 休止中)"]},
         {"no": "4.2", "ja": "対象年月", "vi": "Tháng đối tượng", "sel": "select[aria-label=\"対象年月\"]", "kind": "select", "trig": "select", "req": "－",
          "len": ["選択（年月 yyyy-mm）", "Chọn (năm-tháng yyyy-mm)"], "init": ["未選択（すべての月）", "Chưa chọn (mọi tháng)"],
          "ex": ["2026-10", "Tháng của menu (tháng chu kỳ). Lựa chọn = các tháng có 月間メニュー mà công ty có 子契約, mới nhất ở trên"],
          "detail": ["選択肢は、この法人（拠点アカウントはその拠点）の子契約がある月間メニューの月（新しい順）", "Lựa chọn là các tháng 月間メニュー mà pháp nhân (hoặc chi nhánh, với tài khoản chi nhánh) có 子契約, mới nhất ở trên"],
          "demo_ok": ["台帳 E 2026-10-05：選択肢はメニュー・契約から作る（コードは 2026-04〜11 を固定）。コードを直す宿題（確認メモ_法人A 宿題 T2）",
                      "Theo 台帳 E 2026-10-05: lựa chọn tạo từ menu và hợp đồng (code ghi cứng 2026-04〜11). Code sẽ sửa sau (確認メモ_法人A 宿題 T2)"]},
         {"no": "4.3", "ja": "拠点名", "vi": "Chi nhánh", "sel": "select[aria-label=\"拠点名\"]", "kind": "select", "trig": "select", "req": "－",
          "len": ["選択（自社の拠点）", "Chọn (chi nhánh của công ty)"], "init": ["未選択（すべての拠点）", "Chưa chọn (mọi chi nhánh)"],
          "ex": ["大阪支店", "Chi nhánh (lưu 拠点ID, ví dụ CU00871; hiển thị tên ngắn)"],
          "cond": ["法人アカウント（見られる拠点が2つ以上）のときだけ出す", "Chỉ hiện với tài khoản pháp nhân (xem được từ 2 chi nhánh trở lên)"],
          "detail": ["選択肢＝今のサイクルの子契約がある拠点と休止中の拠点（拠点ID 昇順）", "Lựa chọn = chi nhánh có 子契約 chu kỳ hiện tại và chi nhánh đang tạm dừng (拠点ID tăng dần)"]},
         {"no": "4.4", "ja": "クリア", "vi": "Nút \"クリア\"", "sel": ".es-search button::クリア", "kind": "button", "trig": "click",
          "detail": ["条件を消して全件・1ページ目", "Xóa điều kiện, hiện tất cả, về trang 1"]},
         {"no": "4.5", "ja": "検索", "vi": "Nút \"検索\"", "sel": ".es-search button[type=submit]", "kind": "button", "trig": "click",
          "detail": ["条件を反映して1ページ目へ。0件は I01（No.12）", "Áp dụng điều kiện, về trang 1. 0 dòng thì I01 (No.12)"], "err": ["I01"]},
         {"no": "5", "ja": "注文の一覧（商品注文）", "vi": "Danh sách đơn (商品注文)", "sel": ".es-table-wrap", "kind": "table", "trig": "view", "pattern": "P-LIST",
          "detail": ["1行＝拠点×対象年月（ご契約の最初のサイクル月から今のサイクル月まで。休止の期間は「休止中」の行）。初期の並び：対象年月の降順→拠点ID の昇順。並べ替えの選択はない（対象年月の降順で固定）",
                     "1 dòng = chi nhánh × tháng (từ tháng chu kỳ đầu của hợp đồng đến tháng hiện tại; kỳ tạm dừng là dòng \"休止中\"). Thứ tự ban đầu: 対象年月 giảm dần → 拠点ID tăng dần. Không có chọn sắp xếp (cố định theo 対象年月 giảm dần)"]},
         {"no": "5.1", "ja": "No", "vi": "Số thứ tự", "sel": ".es-table th::No", "kind": "label", "trig": "view", "detail": ["ページをまたいだ通し番号", "Số thứ tự liên tục qua các trang"]},
         {"no": "5.2", "ja": "メニューID", "vi": "Mã menu", "sel": ".es-table th::メニューID", "kind": "link", "trig": "click",
          "detail": ["その月の月間メニューの ID（yyyymm-nnnn）。押す先は行の状態で変わる：受付中の月（今のサイクル月・受付期間内）で注文を変更できる行（休止中・お試し・参照のみでない）は、その拠点を選んだ状態で商品注文（CW_ORDER_001・編集）へ。締切後の月と、受付中でも変更できない行（お試し・参照のみ）は注文履歴 詳細（CW_HIST_002・参照）へ。休止中の行はリンクにしない。操作（No.5.11）と同じ先",
                     "ID của 月間メニュー tháng đó (yyyymm-nnnn). Đích bấm tùy trạng thái dòng: tháng đang nhận đơn (tháng chu kỳ hiện tại, trong kỳ nhận) và sửa được (không 休止中 / dùng thử / chỉ xem) thì mở 商品注文 (CW_ORDER_001, sửa) với chi nhánh đó đang chọn. Tháng đã chốt, hoặc đang nhận nhưng không sửa được (dùng thử / chỉ xem) thì mở 注文履歴 詳細 (CW_HIST_002, xem). Dòng 休止中 không có link. Cùng đích với thao tác (No.5.11)"],
          "demo_ok": ["台帳 E 2026-10-05：メニューID は月間メニューの実データ（コードは計算式で作る）。コードを直す宿題（確認メモ_法人A 宿題 T2）。押す先（受付中＝商品注文・締切後＝詳細）は実装済",
                      "Theo 台帳 E 2026-10-05: メニューID lấy từ dữ liệu thật của 月間メニュー (code tính bằng công thức). Code sẽ sửa sau (確認メモ_法人A 宿題 T2). Đích bấm (đang nhận = 商品注文, sau hạn = chi tiết) đã làm"]},
         {"no": "5.3", "ja": "対象年月", "vi": "Tháng đối tượng", "sel": ".es-table th::対象年月", "kind": "label", "trig": "view", "detail": ["yyyy-mm", "yyyy-mm"]},
         {"no": "5.4", "ja": "拠点名", "vi": "Tên chi nhánh", "sel": ".es-table th::拠点名", "kind": "label", "trig": "view", "detail": ["法人名を除いた短い名前（例：大阪支店）", "Tên ngắn không gồm tên pháp nhân (ví dụ 大阪支店)"]},
         {"no": "5.5", "ja": "ご注文の受付開始日", "vi": "Ngày bắt đầu nhận đơn", "sel": ".es-table th::ご注文の受付開始日", "kind": "label", "trig": "view",
          "detail": ["月間メニューのオーダー開始日（既定は前月1日）。yyyy-mm-dd", "Ngày bắt đầu nhận đơn của 月間メニュー (mặc định ngày 1 tháng trước). yyyy-mm-dd"]},
         {"no": "5.6", "ja": "ご注文の締切日", "vi": "Hạn chốt đơn", "sel": ".es-table th::ご注文の締切日", "kind": "label", "trig": "view",
          "detail": ["月間メニューのオーダー締切日（既定は前月15日）。お試しは申込内容確認で決めた日", "Hạn chốt đơn của 月間メニュー (mặc định ngày 15 tháng trước). Dùng thử: ngày quyết định ở 申込内容確認"]},
         {"no": "5.7", "ja": "自販機", "vi": "Máy bán hàng", "sel": ".es-table th::自販機", "kind": "label", "trig": "view",
          "detail": ["コースが ESライト（自販機）なら「✓」、それ以外は空", "Khóa học ESライト（自販機） thì \"✓\", khác thì trống"]},
         {"no": "5.8", "ja": "メニューPDF", "vi": "PDF menu", "sel": ".es-table th::メニューPDF", "kind": "link", "trig": "click",
          "detail": ["運営がメニュー編集で載せた PDF のファイル名（ライト用／スタンダード用）。押すと開く。ESライトの拠点にはスタンダード用を出さない。なければ「未掲載」",
                     "Tên file PDF do 運営 đính kèm ở メニュー編集 (bản Light / bản Standard). Bấm để mở. Chi nhánh ESライト không hiện bản Standard. Không có thì \"未掲載\""],
          "demo_ok": ["台帳 F 2026-10-05：PDF はライト用／スタンダード用の2種類で、ライトにはスタンダード用を見せない（コードは1種類）。コードを直す宿題（受付簿 No.63）",
                      "Theo 台帳 F 2026-10-05: PDF có 2 loại Light / Standard, Light không thấy bản Standard (code chỉ 1 loại). Code sẽ sửa sau (受付簿 No.63)"]},
         {"no": "5.9", "ja": "ご注文の状態", "vi": "Trạng thái đơn", "sel": ".es-table th::ご注文の状態", "kind": "label", "trig": "view",
          "detail": ["バッジ：登録済（青）／ESキッチン入力済み（黄）／自動注文（緑・登録がなく標準数で確定）／お試し（自動）／休止中（灰）／受付前（灰）。受付中の月は右に「受付中」",
                     "Badge: 登録済 (xanh) / ESキッチン入力済み (vàng) / 自動注文 (xanh lá, không đăng ký nên chốt theo số chuẩn) / お試し（自動） / 休止中 (xám) / 受付前 (xám). Tháng đang nhận đơn có thêm \"受付中\" bên phải"]},
         {"no": "5.11", "ja": "操作（注文を変更／参照）", "vi": "Thao tác (sửa đơn / xem)", "sel": ".es-table th::操作", "kind": "button", "trig": "click",
          "cond": ["休止中の行以外に出す。受付中の月（今のサイクル月・受付期間内）で休止中・お試し・参照のみでない行は鉛筆（変更）、それ以外（締切後の月・受付中でもお試し・参照のみ）は目のアイコン（参照）", "Hiện ở mọi dòng trừ 休止中. Tháng đang nhận đơn (tháng chu kỳ hiện tại, trong kỳ nhận) và không 休止中 / dùng thử / chỉ xem thì bút chì (sửa); còn lại (tháng đã chốt; đang nhận nhưng dùng thử / chỉ xem) thì biểu tượng mắt (xem)"],
          "detail": ["鉛筆：その拠点を選んだ状態で商品注文（CW_ORDER_001・編集）へ移る。目：注文履歴 詳細（CW_HIST_002・参照）へ移る。締切後は商品注文の画面は開かず、詳細が参照の画面。マウスを乗せると「注文を変更」「参照」。メニューID（No.5.2）と同じ先", "Bút chì: sang 商品注文 (CW_ORDER_001, sửa) với chi nhánh đó đang chọn. Mắt: sang 注文履歴 詳細 (CW_HIST_002, xem). Sau hạn chốt không mở 商品注文; màn chi tiết là màn xem. Rê chuột: \"注文を変更\" / \"参照\". Cùng đích với メニューID (No.5.2)"]},
         {"no": "6", "ja": "ページ送り", "vi": "Phân trang", "sel": ".es-pagination", "kind": "area", "trig": "click", "pattern": "P-LIST",
          "detail": ["「{全件}件中 {from}–{to}件」・前へ／次へ・ページ番号・表示件数（10／20／50、初期 10）", "\"{tổng}件中 {from}–{to}件\", 前へ/次へ, số trang, số dòng mỗi trang (10/20/50, mặc định 10)"]},
     ]},
    {"id": "002", "code": "CW_HIST_001", "state": ["資材注文", "Đơn vật tư"],
     "url": "/corp/order/history", "full": True, "wait": 800, "setup": _CLICK_MAT,
     "note": ["「資材注文」に切り替えた状態。1行＝資材注文（資材便）。初期セットも出す。取消の注文は出さない", "Đã chuyển sang \"資材注文\". 1 dòng = 1 đơn vật tư (資材便). Hiện cả 初期セット. Không hiện đơn 取消"],
     "items": [
         {"no": "7", "ja": "CSV出力（資材注文）", "vi": "Nút \"CSV出力\" (đơn vật tư)", "sel": ".es-pagehead__actions button::CSV出力", "kind": "button", "trig": "click", "pattern": "P-CSV-OUT",
          "detail": ["列：資材注文No・注文区分・拠点ID・拠点名・注文日・発送日・お届け予定日・送り状番号・資材・配送状態＋資材注文の文書（dm.delivery.materialOrders・明細）の全項目。発送日・お届け予定日・送り状番号は運営がまだ入れていなければ空。画面名「注文履歴（資材注文）」",
                     "Cột: 資材注文No, 注文区分, 拠点ID, 拠点名, 注文日, 発送日, お届け予定日, 送り状番号, 資材, 配送状態 + mọi mục của văn bản đơn vật tư (dm.delivery.materialOrders, chi tiết). 発送日, お届け予定日, 送り状番号 để trống nếu 運営 chưa nhập. Tên màn hình \"注文履歴（資材注文）\""]},
         {"no": "8", "ja": "検索（拠点名）", "vi": "Tìm kiếm (chi nhánh)", "sel": ".es-search", "kind": "area", "trig": "view", "pattern": "P-LIST",
          "detail": ["条件は拠点名だけ（No.4.3 と同じ。拠点アカウントは出さない）", "Chỉ có điều kiện chi nhánh (giống No.4.3; tài khoản chi nhánh không hiện)"]},
         {"no": "9", "ja": "資材注文の一覧", "vi": "Danh sách đơn vật tư", "sel": ".es-table-wrap", "kind": "table", "trig": "view", "pattern": "P-LIST",
          "detail": ["見られる拠点の資材注文（取消を除く）。初期の並び：注文日の降順→資材注文No の降順。0件は I01",
                     "Đơn vật tư của các chi nhánh xem được (trừ 取消). Thứ tự ban đầu: 注文日 giảm dần → 資材注文No giảm dần. 0 dòng: I01"],
          "err": ["I01"]},
         {"no": "9.1", "ja": "資材注文No", "vi": "Số đơn vật tư", "sel": ".es-table th::資材注文No", "kind": "label", "trig": "view",
          "detail": ["MO-YYMM-NNNN（登録した年月＋連番）", "MO-YYMM-NNNN (năm-tháng đăng ký + số thứ tự)"]},
         {"no": "9.2", "ja": "注文区分", "vi": "Loại đơn", "sel": ".es-table th::注文区分", "kind": "label", "trig": "view",
          "detail": ["通常注文／初期セット（ご契約のはじめに自動で作る・回数に数えない）", "通常注文 / 初期セット (tự tạo khi bắt đầu hợp đồng, không tính số lần)"]},
         {"no": "9.3", "ja": "拠点名", "vi": "Tên chi nhánh", "sel": ".es-table th::拠点名", "kind": "label", "trig": "view", "detail": ["短い名前", "Tên ngắn"]},
         {"no": "9.4", "ja": "注文日", "vi": "Ngày đặt", "sel": ".es-table th::注文日", "kind": "label", "trig": "view", "detail": ["登録した日 yyyy-mm-dd", "Ngày đăng ký yyyy-mm-dd"]},
         {"no": "9.5", "ja": "お届け予定日", "vi": "Ngày giao dự kiến", "sel": ".es-table th::お届け予定日", "kind": "label", "trig": "view",
          "cond": ["ESキッチンが運営Web の資材注文管理で送り状番号・発送日を入れ、発送日にリードタイムを足して出せる行だけ。それまでは「—」（マウスを乗せると I223）", "Chỉ dòng ESキッチン đã nhập 送り状番号, 発送日 ở 資材注文管理 của 運営Web và tính được 発送日 + lead time. Trước đó hiện \"—\" (rê chuột: I223)"],
          "detail": ["資材便のお届け予定日 mm-dd（曜日）＝発送日にリードタイムの日数を足した日（リードタイムは契約の配送区分「資材」の日数＝0〜7日。配送仕様 配送_05・受付簿 No.154・No.158）。登録日からは決めない", "Ngày giao dự kiến của 資材便 mm-dd (thứ) = 発送日 + số ngày lead time (lead time là số ngày của 配送区分 「資材」 trong hợp đồng, 0〜7 ngày; 配送仕様 配送_05, 受付簿 No.154・No.158). Không tính từ ngày đăng ký"],
          "err": ["I223"]},
         {"no": "9.6", "ja": "資材", "vi": "Vật tư", "sel": ".es-table th::資材", "kind": "label", "trig": "view",
          "detail": ["「{種類数}種類・{合計}点」", "\"{số loại}種類・{tổng}点\""]},
         {"no": "9.7", "ja": "配送状態", "vi": "Trạng thái giao", "sel": ".es-table th::配送状態", "kind": "label", "trig": "view",
          "detail": ["資材便の配送データの状態をお客様向けの言い方で：出荷待（青）／出荷済（青）／お届け済み（緑）／再配送予定（黄）／お届け中止（灰）。配送のトラブルが未解決なら右に「配送状況を確認中」。ESキッチンが配送データから反映する",
                     "Trạng thái của dữ liệu giao 資材便 theo cách gọi với khách: 出荷待 (xanh) / 出荷済 (xanh) / お届け済み (xanh lá) / 再配送予定 (vàng) / お届け中止 (xám). Có sự cố giao chưa giải quyết thì thêm \"配送状況を確認中\" bên phải. ESキッチン cập nhật từ dữ liệu giao"]},
         {"no": "10", "ja": "注記", "vi": "Ghi chú dưới bảng", "sel": ".es-card > p.od-small", "kind": "label", "trig": "view",
          "detail": ["「配送状態は、ESキッチンが資材便の配送データから反映します。お届け予定日と送り状番号は、ESキッチンが発送の手配をすると出ます。資材はいつでも注文でき、同じご利用月の2回目以降は資材の追加配送の料金（{金額}）がかかります。」",
                     "\"配送状態は、ESキッチンが資材便の配送データから反映します。お届け予定日と送り状番号は、ESキッチンが発送の手配をすると出ます。資材はいつでも注文でき、同じご利用月の2回目以降は資材の追加配送の料金（{金額}）がかかります。\""],
          "open": ["資材の追加配送（OP000036）の金額（決定_STEP5 §2-5 の提案値 ¥2,000／回・税抜）。確定したら注記に入れる。「〔仮〕」は書かない",
                   "Số tiền 資材の追加配送 (OP000036) (giá đề xuất 決定_STEP5 §2-5: ¥2,000/lần, chưa thuế). Chốt xong thì ghi vào ghi chú. Không ghi \"〔仮〕\""],
          "ask": "お客様（営業）"},
         {"no": "11", "ja": "ページ送り（資材注文）", "vi": "Phân trang (đơn vật tư)", "sel": ".es-card", "kind": "area", "trig": "click", "pattern": "P-LIST",
          "detail": ["商品注文と同じ（10／20／50、初期 10）", "Giống 商品注文 (10/20/50, mặc định 10)"]},
         {"no": "30", "ja": "送り状番号", "vi": "Số vận đơn", "sel": ".es-table th::送り状番号", "kind": "label", "trig": "view",
          "cond": ["ESキッチンが運営Web の資材注文管理で送り状番号を入れた行だけ。それまでは「—」", "Chỉ dòng ESキッチン đã nhập 送り状番号 ở 資材注文管理 của 運営Web. Trước đó hiện \"—\""],
          "detail": ["資材便（宅配便）の送り状番号。お届け予定日（No.9.5）の右の列。見出しは「送り状番号」（お届け詳細と同じ言い方）。初期セットも同じ", "Số vận đơn của 資材便 (chuyển phát). Cột bên phải お届け予定日 (No.9.5). Tiêu đề \"送り状番号\" (cùng cách gọi với お届け詳細). 初期セット cũng vậy"],
          "demo_ok": ["法人Web は MaterialOrder の shippedOn・trackingNo を出す（見本は発送済みの注文に入れてある）。運営Web の資材注文管理で入れる画面は受付簿 No.154（運営Web 側）",
                      "法人Web hiện shippedOn, trackingNo của MaterialOrder (mẫu đã nhập cho đơn đã gửi). Màn nhập ở 資材注文管理 của 運営Web: 受付簿 No.154 (phía 運営Web)"]},
         {"no": "33", "ja": "発送日", "vi": "Ngày gửi", "sel": ".es-table th::発送日", "kind": "label", "trig": "view",
          "cond": ["ESキッチンが運営Web の資材注文管理で発送日を入れた行だけ。それまでは「—」", "Chỉ dòng ESキッチン đã nhập 発送日 ở 資材注文管理. Trước đó \"—\""],
          "detail": ["資材便の発送日 yyyy-mm-dd（注文日の右の列。版 1.1 で足した項目（番号は末尾）。hong 2026-10-05 版1.0レビュー ⑩・受付簿 No.154）", "Ngày gửi 資材便 yyyy-mm-dd (cột bên phải 注文日. hong 2026-10-05 版1.0レビュー ⑩, 受付簿 No.154)"]},
     ]},
    {"id": "003", "code": "CW_HIST_001", "state": ["検索 0件", "Tìm kiếm 0 kết quả"],
     "url": "/corp/order/history", "full": True, "wait": 800, "setup": _SEARCH_NONE,
     "note": ["商品名「ないもの」で検索した状態", "Đã tìm với tên sản phẩm \"ないもの\""],
     "items": [
         {"no": "12", "ja": "0件の表示", "vi": "Hiển thị 0 dòng", "sel": ".es-empty", "kind": "label", "trig": "view",
          "detail": ["一覧の場所に I01。ページ送り・CSV出力は押せない", "I01 ở vị trí danh sách. Phân trang và CSV出力 không bấm được"], "err": ["I01"]},
     ]},
    {"id": "004", "code": "CW_HIST_001", "state": ["拠点アカウント", "Tài khoản chi nhánh"],
     "url": "/corp/order/history", "login": "CU00961", "full": True, "wait": 800,
     "note": ["千葉営業所（拠点アカウント）。自分の拠点の行だけ。検索の「拠点名」はない", "Chi nhánh Chiba (tài khoản chi nhánh). Chỉ dòng của chi nhánh mình. Không có điều kiện \"拠点名\""],
     "items": [
         {"no": "13", "ja": "検索（拠点アカウント）", "vi": "Tìm kiếm (tài khoản chi nhánh)", "sel": ".es-search", "kind": "area", "trig": "view",
          "detail": ["商品名・対象年月だけ（拠点名は出さない）", "Chỉ có 商品名, 対象年月 (không có 拠点名)"]},
         {"no": "14", "ja": "一覧（自分の拠点）", "vi": "Danh sách (chi nhánh mình)", "sel": ".es-table-wrap", "kind": "table", "trig": "view",
          "detail": ["拠点アカウントはその拠点の行だけ（ほかの拠点は見られない）", "Tài khoản chi nhánh chỉ thấy dòng của chi nhánh mình (không thấy chi nhánh khác)"]},
     ]},
    # ---------------------------------------------------------------- CW_HIST_002 詳細
    {"id": "006", "code": "CW_HIST_002", "state": ["受付中の月（注文を変更できる）", "Tháng đang nhận đơn (sửa được)"],
     "url": "/corp/order/history/CU00871/2026-11", "full": True, "wait": 800,
     "note": ["大阪支店 2026-11（受付中）。法人アカウントで開いた状態。URL は /corp/order/history/{拠点ID}/{対象年月}。資材は 2026-11 分の資材注文 MO-2610-0014 の表が出る（見本データ）",
              "大阪支店 2026-11 (đang nhận đơn), mở bằng tài khoản pháp nhân. URL: /corp/order/history/{拠点ID}/{対象年月}. Phần vật tư hiện bảng của đơn vật tư 2026-11 MO-2610-0014 (dữ liệu mẫu)"],
     "items": [
         {"no": "16", "ja": "パンくず・タイトル", "vi": "Breadcrumb và tiêu đề", "sel": ".es-pagehead__text", "kind": "label", "trig": "view",
          "detail": ["「月次注文 / 注文履歴 / {メニューID}」（注文履歴は一覧へのリンク）。タイトル「注文履歴 詳細 {メニューID}」", "\"月次注文 / 注文履歴 / {メニューID}\" (注文履歴 là link về danh sách). Tiêu đề \"注文履歴 詳細 {メニューID}\""]},
         {"no": "34", "ja": "タブ（注文／変更履歴）", "vi": "Tab (注文 / 変更履歴)", "sel": ".od-subtabs", "kind": "area", "trig": "click", "pattern": "P-TAB",
          "detail": ["見出しの下に「注文」「変更履歴」の2つ。押したタブは URL の ?tab=（history）に持ち、再読み込み・戻るでも同じタブを開く。「注文」のタブに注文の情報（No.20）・商品（No.21）・資材（No.22）、「変更履歴」のタブに変更履歴の表（No.29）。変更履歴はモーダルをやめてこのタブに入れた（hong 2026-10-05・受付簿 No.157。商品注文 CW_ORDER No.3.9・資材注文 CW_MAT No.21 と同じ）",
                     "Dưới tiêu đề có 2 tab 「注文」 「変更履歴」. Tab được chọn lưu trong URL ?tab= (history); tải lại / Back vẫn mở đúng tab. Tab 「注文」 chứa thông tin đơn (No.20), sản phẩm (No.21), vật tư (No.22); tab 「変更履歴」 chứa bảng lịch sử (No.29). 変更履歴 bỏ modal, đưa vào tab này (hong 2026-10-05, 受付簿 No.157; giống 商品注文 CW_ORDER No.3.9 và 資材注文 CW_MAT No.21)"]},
         {"no": "18", "ja": "注文を変更", "vi": "Nút \"注文を変更\"", "sel": ".es-pagehead__actions button::注文を変更", "kind": "button", "trig": "click",
          "cond": ["受付中の月（今のサイクル月・受付期間内）で、休止中・お試し・解約後（参照のみ）でないときだけ", "Chỉ khi là tháng đang nhận đơn (trong kỳ nhận) và không 休止中 / dùng thử / chỉ xem"],
          "detail": ["その拠点を選んだ状態で商品注文（CW_ORDER_001）へ", "Sang 商品注文 (CW_ORDER_001) với chi nhánh đang chọn"],
          "demo_ok": ["台帳 E 2026-10-05：休止中の月は URL で直接開いても出さない（コードは今の子契約の休止で見る）。コードを直す宿題（確認メモ_法人A 宿題 T3）。参照のみ・お試し・締切後に出さないのは実装済",
                      "Theo 台帳 E 2026-10-05: tháng 休止中 mở thẳng bằng URL cũng không hiện (code xét theo tạm dừng của 子契約 hiện tại). Code sẽ sửa sau (確認メモ_法人A 宿題 T3). Chỉ xem / dùng thử / sau hạn không hiện: đã làm"]},
         {"no": "19", "ja": "戻る", "vi": "Nút \"戻る\"", "sel": ".es-pagehead__actions button::戻る", "kind": "button", "trig": "click",
          "detail": ["注文履歴の一覧へ（検索条件・ページは保ったまま）", "Về danh sách 注文履歴 (giữ điều kiện tìm kiếm và trang)"]},
         {"no": "20", "ja": "注文の情報", "vi": "Thông tin đơn", "sel": ".od-g4", "kind": "area", "trig": "view",
          "detail": ["参照だけ（4列）", "Chỉ xem (4 cột)"]},
         {"no": "20.1", "ja": "拠点名", "vi": "Tên chi nhánh", "sel": ".od-g4 label::拠点名^", "kind": "label", "trig": "view", "detail": ["短い名前", "Tên ngắn"]},
         {"no": "20.2", "ja": "対象年月", "vi": "Tháng đối tượng", "sel": ".od-g4 label::対象年月^", "kind": "label", "trig": "view", "detail": ["yyyy-mm", "yyyy-mm"]},
         {"no": "20.3", "ja": "プラン", "vi": "Gói (plan)", "sel": ".od-g4 label::プラン^", "kind": "label", "trig": "view",
          "detail": ["「{プランID} 月{n}個プラン（{コース}）」（その月の子契約）", "\"{プランID} 月{n}個プラン（{コース}）\" (子契約 của tháng đó)"]},
         {"no": "20.4", "ja": "ご注文の状態", "vi": "Trạng thái đơn", "sel": ".od-g4 label::ご注文の状態^", "kind": "label", "trig": "view",
          "detail": ["一覧 No.5.9 と同じ言い方", "Cùng cách gọi với No.5.9"]},
         {"no": "20.5", "ja": "ご注文の受付期間", "vi": "Kỳ nhận đơn", "sel": ".od-g4 label::ご注文の受付期間^", "kind": "label", "trig": "view",
          "detail": ["「{開始日}〜{締切日}」（月間メニューの受付開始日・締切日）", "\"{ngày bắt đầu}〜{hạn chốt}\" (theo 月間メニュー)"]},
         {"no": "20.6", "ja": "合計", "vi": "Tổng", "sel": ".od-g4 label::合計^", "kind": "label", "trig": "view",
          "detail": ["「{品数}品・{個数}個」（1 以上の商品の数と注文数の合計）", "\"{số SP}品・{số lượng}個\" (số sản phẩm ≥ 1 và tổng số lượng)"]},
         {"no": "20.7", "ja": "配送回ごと", "vi": "Theo từng chuyến", "sel": ".od-g4 label::配送回ごと^", "kind": "label", "trig": "view",
          "detail": ["便ごとの合計「第1便 {n}／第2便 {n}／冷凍 第1便 {n}」", "Tổng theo chuyến \"第1便 {n}／第2便 {n}／冷凍 第1便 {n}\""]},
         {"no": "20.8", "ja": "ご契約", "vi": "Hợp đồng", "sel": ".od-g4 label::ご契約^", "kind": "label", "trig": "view",
          "detail": ["その月の子契約の ID（例：CP0000002-202611）。なければ「—」", "ID của 子契約 tháng đó (ví dụ CP0000002-202611). Không có thì \"—\""],
          "demo_ok": ["台帳 E 2026-10-05：子契約 ID はその月の実データ（コードは今の子契約 ID の月の部分を置き換える）。コードを直す宿題（確認メモ_法人A 宿題 T2）",
                      "Theo 台帳 E 2026-10-05: ID 子契約 lấy từ dữ liệu thật của tháng đó (code thay phần tháng trong ID hiện tại). Code sẽ sửa sau (確認メモ_法人A 宿題 T2)"]},
         {"no": "21", "ja": "商品", "vi": "Sản phẩm", "sel": "h2::商品（^2", "kind": "area", "trig": "view",
          "detail": ["見出し「商品（{品数}品）」。注文数が 1 以上の商品だけをメニューの並びで出す", "Tiêu đề \"商品（{n}品）\". Chỉ hiện sản phẩm có số lượng ≥ 1, theo thứ tự menu"]},
         {"no": "21.1", "ja": "メニューPDF", "vi": "PDF menu", "sel": ".es-section-title > div", "kind": "link", "trig": "click",
          "detail": ["一覧 No.5.8 と同じ", "Giống No.5.8"]},
         {"no": "21.2", "ja": "商品の表", "vi": "Bảng sản phẩm", "sel": ".od-tbl", "kind": "label", "trig": "view",
          "detail": ["列：No・写真・商品名（押すとメニュー詳細 CW_ORDER_002）・カテゴリ・保存方法（冷蔵／常温／冷凍）・定価（税込）・便ごとの数（見出し「第1便」＋お届け日 mm-dd。冷凍の商品は冷凍の便だけ、ほかは「—」）・合計数「{n}個」",
                     "Cột: No, 写真, 商品名 (bấm mở メニュー詳細 CW_ORDER_002), カテゴリ, 保存方法 (冷蔵/常温/冷凍), 定価（税込）, số theo chuyến (tiêu đề \"第1便\" + ngày giao mm-dd; SP đông lạnh chỉ ở chuyến đông lạnh, chuyến khác \"—\"), 合計数 \"{n}個\""]},
         {"no": "22", "ja": "資材", "vi": "Vật tư", "sel": "h2::資材^2", "kind": "area", "trig": "view",
          "detail": ["見出し「資材（{年月}分に登録した資材注文・{n}件）」。この拠点がこのサイクル月に登録した資材注文（通常注文・取消を除く）を資材注文No ごとに出す。見出しの行は「{資材注文No}　通常注文　注文日 {yyyy-mm-dd}　お届け予定日 {mm-dd（曜）／—}　{状態のバッジ}」（お届け予定日は運営が発送日を入れたときだけ・それまでは「—」）。1件もなければ I01「表示するデータがありません。」",
                     "Tiêu đề \"資材（{năm-tháng}分に登録した資材注文・{n}件）\". Hiện đơn vật tư chi nhánh đã đăng ký trong tháng chu kỳ này (通常注文, trừ 取消), theo từng 資材注文No. Dòng tiêu đề: \"{資材注文No}　通常注文　注文日 {yyyy-mm-dd}　お届け予定日 {mm-dd（thứ）／—}　{badge trạng thái}\" (ngày giao dự kiến chỉ khi 運営 đã nhập 発送日, trước đó \"—\"). Không có đơn nào thì I01 「表示するデータがありません。」"],
          "err": ["I01"]},
         {"no": "22.1", "ja": "資材の表", "vi": "Bảng vật tư", "sel": ".od-mathist", "kind": "label", "trig": "view",
          "detail": ["資材注文ごとに1つの表。列：No・資材名・注文数量（「{n}{単位}」例：40膳）。見本は大阪支店 2026-11 分の資材注文 MO-2610-0014（割り箸 40膳・深皿 5枚・おしぼり 20個。出荷待）",
                     "Mỗi đơn vật tư 1 bảng. Cột: No, 資材名, 注文数量 (\"{n}{đơn vị}\", ví dụ 40膳). Mẫu là đơn vật tư MO-2610-0014 của 大阪支店 cho 2026-11 (出荷待)"]},
     ]},
    {"id": "007", "code": "CW_HIST_002", "state": ["過去の月（確定済み）", "Tháng đã qua (đã chốt)"],
     "url": "/corp/order/history/CU00871/2026-10", "full": True, "wait": 800,
     "note": ["大阪支店 2026-10。締切を過ぎた月は参照だけ（「注文を変更」なし）。数は確定した注文（代替品・欠品の変更も含む）",
              "大阪支店 2026-10. Tháng đã qua hạn chỉ xem (không có \"注文を変更\"). Số là đơn đã chốt (gồm cả thay đổi hàng thay thế, thiếu hàng)"],
     "items": [
         {"no": "23", "ja": "操作ボタン（過去の月）", "vi": "Nút thao tác (tháng đã qua)", "sel": ".es-pagehead__actions", "kind": "area", "trig": "view",
          "detail": ["「戻る」だけ（変更履歴は画面内のタブ・No.34）。締切後は商品注文（CW_ORDER_001）の画面は開かず、この画面が締切後の唯一の参照の画面（注文履歴のメニューID・操作、商品注文の URL を直接開いたときもここへ）",
                     "Chỉ có 戻る (lịch sử thay đổi là tab trong màn hình, No.34). Sau hạn chốt không mở màn 商品注文 (CW_ORDER_001); màn này là màn xem duy nhất sau hạn (メニューID, thao tác ở 注文履歴, và mở thẳng URL 商品注文 cũng về đây)"]},
         {"no": "24", "ja": "ご注文の状態（確定）", "vi": "Trạng thái đơn (đã chốt)", "sel": ".od-g4 label::ご注文の状態^", "kind": "label", "trig": "view",
          "detail": ["登録済／ESキッチン入力済み／自動注文 のどれか（締切時点で確定した状態）", "Một trong 登録済 / ESキッチン入力済み / 自動注文 (trạng thái chốt tại hạn)"]},
     ]},
    {"id": "008", "code": "CW_HIST_002", "state": ["お試しの拠点", "Chi nhánh dùng thử"],
     "url": "/corp/order/history/CU00975/2026-11", "login": "CU00071", "full": True, "wait": 800,
     "note": ["株式会社みちのく商事 仙台本社（お試し）。受付中でも「注文を変更」は出さない（お試しの注文はシステムが自動で作る）",
              "Công ty Michinoku, trụ sở Sendai (dùng thử). Đang nhận đơn vẫn không hiện \"注文を変更\" (đơn dùng thử do hệ thống tự tạo)"],
     "items": [
         {"no": "25", "ja": "操作ボタン（お試し）", "vi": "Nút thao tác (dùng thử)", "sel": ".es-pagehead__actions", "kind": "area", "trig": "view",
          "detail": ["「戻る」だけ（「注文を変更」なし。変更履歴は画面内のタブ・No.34）", "Chỉ có 戻る (không có \"注文を変更\"; lịch sử thay đổi là tab trong màn hình, No.34)"]},
         {"no": "26", "ja": "ご注文の状態（お試し）", "vi": "Trạng thái đơn (dùng thử)", "sel": ".od-g4 label::ご注文の状態^", "kind": "label", "trig": "view",
          "detail": ["「お試し（自動）」。すべての商品に均等に振り分けた数", "\"お試し（自動）\". Số lượng chia đều cho mọi sản phẩm"]},
     ]},
    {"id": "009", "code": "CW_HIST_002", "state": ["見られない（ほかの拠点・ない月）", "Không xem được (chi nhánh khác / tháng không có)"],
     "url": "/corp/order/history/CU00643/2026-11", "login": "CU00871", "full": True, "wait": 800,
     "note": ["大阪支店の拠点アカウントで本社の URL を開いた状態。見られない拠点・注文のない月は E317", "Tài khoản chi nhánh Osaka mở URL của 本社. Chi nhánh không được xem / tháng không có đơn thì E317"],
     "items": [
         {"no": "27", "ja": "見られない表示", "vi": "Hiển thị không xem được", "sel": ".es-empty", "kind": "label", "trig": "view",
          "cond": ["URL の拠点が見られる拠点にない、または対象年月の注文がない（今のサイクル月でもない）とき", "Khi chi nhánh trong URL không thuộc phạm vi xem được, hoặc tháng đó không có đơn (và không phải tháng chu kỳ hiện tại)"],
          "detail": ["E317 を一覧の場所に出す。注文の情報・商品・資材は出さない", "Hiện E317 ở vị trí nội dung. Không hiện 注文の情報, 商品, 資材"], "err": ["E317"]},
         {"no": "28", "ja": "戻る", "vi": "Nút \"戻る\"", "sel": ".es-pagehead__actions button::戻る", "kind": "button", "trig": "click",
          "detail": ["注文履歴の一覧へ", "Về danh sách 注文履歴"]},
     ]},
    {"id": "010", "code": "CW_HIST_002", "state": ["変更履歴（タブ・過去の月）", "Lịch sử thay đổi (tab, tháng đã qua)"],
     "url": "/corp/order/history/CU00871/2026-10?tab=history", "full": True, "wait": 1000,
     "note": ["大阪支店 2026-10 の「変更履歴」のタブ（URL ?tab=history）。過去の月はその月の注文の履歴（締切の行を含む）。注文の情報・商品・資材は「注文」のタブだけ（版 1.4）", "Tab 「変更履歴」 của 大阪支店 2026-10 (URL ?tab=history). Tháng đã qua hiện lịch sử đơn của tháng đó (gồm dòng chốt hạn). Thông tin đơn, sản phẩm, vật tư chỉ ở tab 「注文」 (bản 1.4)"],
     "items": [
         {"no": "29", "ja": "変更履歴のタブの中身", "vi": "Nội dung tab 変更履歴", "sel": ".od-log", "kind": "table", "trig": "show", "pattern": "P-HIST",
          "detail": ["拠点名・対象年月の変更履歴。受付中の月は資材注文の登録・注文の設定・アンケートも含む（CW_MAT No.18 と同じ）。過去の月は締切の行「ご注文・変更の締切」（詳細：登録内容で確定／登録がなかったため、自動注文（基準数）で確定）と、締切後に ESキッチンが変えた分。0件は I01「表示するデータがありません。」。モーダルではなく画面の中に出す",
                     "Lịch sử thay đổi của chi nhánh, tháng. Tháng đang nhận gồm cả đăng ký vật tư, 注文の設定, アンケート (giống CW_MAT No.18). Tháng đã qua có dòng chốt hạn \"ご注文・変更の締切\" (chi tiết: 登録内容で確定 / 登録がなかったため、自動注文（基準数）で確定) và các thay đổi của ESキッチン sau hạn. 0 dòng: I01 「表示するデータがありません。」. Hiện ngay trong màn hình, không dùng modal"],
          "err": ["I01"]},
         {"no": "29.1", "ja": "履歴の表", "vi": "Bảng lịch sử", "sel": ".od-log", "kind": "label", "trig": "view",
          "pattern": "P-HIST", "detail": ["列は P-HIST のとおり：日時・変更した人・操作・項目・変更前・変更後・理由（あれば）（hong 2026-10-05 B-2）。ESキッチンが変えた行は「操作」を黄色のバッジ", "Cột theo P-HIST: 日時, 変更した人, 操作, 項目, 変更前, 変更後, 理由 (nếu có) (hong 2026-10-05 B-2). Dòng do ESキッチン đổi thì \"操作\" hiện badge vàng"]},
     ]},
]
