# -*- coding: utf-8 -*-
"""
法人Web 月次注文 ＞ 資材注文（CW_MAT）。元：app/corp/order/materials/page.tsx・lib/corp/areas/corp-order.ts（registerMat）・
lib/corp/order/{logic,fromDomain}.ts・lib/ops/menu/data.ts（資材マスタ）。
決定：docs/決定台帳.md E 2026-10-05（資材注文の初期値 0・2回目以降の確認モーダル・お試しは資材注文できない・参照のみは資材注文できない）、
決定_STEP5回答_法人Web_20261001 Q2（資材は随時・月1回まで料金に含む・2回目以降 OP000036・初期セットは数えない）。
版 1.1（hong 回答 2026-10-05・版1.0レビュー。台帳 E「法人Web 版 1.0 のレビュー（商品注文・資材注文・注文履歴）」⑦〜⑩）：「今月 n回目のご注文」を登録ボタンの近くに・案内は2行・
コース名の列は出さない・お届け予定日は運営が資材注文管理で送り状番号・発送日を入れリードタイムから出せるときだけ（受付簿 No.153・No.154）。
コードは 版 1.1 に合わせた（受付簿 No.153 実装済。残り：資材便の dueOn を登録日＋2日で決めている共通データの delivery.placeMaterialOrder・変更履歴の P-HIST の列）。
"""

TITLE = ["資材注文（CW_MAT）", "Đặt vật tư (CW_MAT)"]
SHEET = ["資材注文", "Đặt vật tư"]
BASENAME = "画面設計書_CW_MAT_資材注文"
IMG_PREFIX = "CW_MAT"
OUT_DIR = "CW_MAT_資材注文"
CODE_NOTE = ["Screen Code は台帳 E 2026-10-05 の決まり：CW_<機能略>_<3桁>", "Screen Code theo 台帳 E 2026-10-05: CW_<機能略>_<3 chữ số>"]
SITE = "corp"
SYSTEM = {"ja": "法人Web", "vi": "Web pháp nhân (法人Web)"}
AUTHOR = "Claude／確認：hong"
CREATED = "2026-10-05"
DEMO_FILE = "http://localhost:3000"
LOGIN = {"site": "corp", "loginId": "CU00001"}

DECISIONS = [
    {"date": "2026-10-05", "target": "CW_MAT_001 No.8",
     "q": ["画面の文言で「ESキッチン」「ES STATION」をどう使い分けるか", "Trong câu chữ màn hình dùng \"ESキッチン\" và \"ES STATION\" thế nào"],
     "a": ["「ESキッチン」＝お客様（運営会社）の名前、「ES STATION」＝システムの名前。「ESSTATION」「ESステーション」は使わない",
           "\"ESキッチン\" = tên công ty vận hành (khách hàng), \"ES STATION\" = tên hệ thống. Không dùng \"ESSTATION\", \"ESステーション\""],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-C1）"},
    {"date": "2026-10-05", "target": "CW_MAT_001 No.7",
     "q": ["解約後（参照のみ）のアカウントは資材注文できるか", "Tài khoản sau khi hủy hợp đồng (chỉ xem) có đặt vật tư được không"],
     "a": ["できない。参照のみでできるのは棚卸報告だけ。「登録」「キャンセル」のボタンを出さない",
           "Không. Chỉ xem thì chỉ làm được 棚卸報告. Không hiện nút \"登録\", \"キャンセル\""],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-C2）"},
    {"date": "2026-10-05", "target": "CW_MAT_001 No.9.6",
     "q": ["資材注文の数量の初期値（コードは前回の注文の数、なければ資材マスタ×プランの数）", "Giá trị ban đầu của số lượng đặt vật tư (code: số của lần đặt trước, không có thì số theo 資材マスタ×プラン)"],
     "a": ["すべて 0（注文のたびに別の資材便になるため、前回の数を引き継がない）", "Tất cả = 0 (mỗi lần đặt là 1 chuyến 資材便 riêng, không kế thừa số lần trước)"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-O6）"},
    {"date": "2026-10-05", "target": "CW_MAT_001 No.16",
     "q": ["同じサイクル月の2回目以降の資材注文（OP000036 有料）は、登録の前に確認するか", "Lần đặt vật tư thứ 2 trở đi trong cùng tháng chu kỳ (OP000036 có phí) có cần xác nhận trước khi đăng ký không"],
     "a": ["確認モーダル（Q205）を出し、「注文する」で登録する", "Hiện modal xác nhận (Q205), nhấn \"注文する\" mới đăng ký"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-O7）"},
    {"date": "2026-10-05", "target": "CW_MAT_001 No.13",
     "q": ["お試しの拠点は資材注文できるか（コードは商品注文だけ止めている）", "Chi nhánh dùng thử có đặt vật tư được không (code chỉ chặn 商品注文)"],
     "a": ["できない（参照のみ）。資材が必要なときは ESキッチンへ連絡", "Không (chỉ xem). Cần vật tư thì liên hệ ES Kitchen"],
     "src": "hong 回答 2026/10/05（確認メモ_法人A Q-O8）"},
    {"date": "2026-10-05", "target": "CW_MAT_001 No.20",
     "q": ["今月の資材注文の回数をどこに・どう出すか（版 1.0 は案内の本文の中に文で）", "Số lần đặt vật tư trong tháng hiện ở đâu, thế nào (bản 1.0: trong câu của phần hướng dẫn)"],
     "a": ["「今月 n回目のご注文」を登録ボタンの近くに出す。1回目は「料金に含みます」、2回目以降は「追加配送の料金がかかります」", "Hiện \"今月 n回目のご注文\" gần nút 登録. Lần 1: \"料金に含みます\", lần 2 trở đi: \"追加配送の料金がかかります\""],
     "src": "hong 回答 2026-10-05 版1.0レビュー（台帳 E ⑦）"},
    {"date": "2026-10-05", "target": "CW_MAT_001 No.8",
     "q": ["資材注文の案内の長さ（版 1.0 は見出し＋本文に資材便・回数・初期セットの説明）", "Độ dài phần hướng dẫn đặt vật tư (bản 1.0: tiêu đề + nội dung dài)"],
     "a": ["2行だけ：いつでも注文できる／月1回までは料金に含み、2回目以降は資材の追加配送の料金がかかる", "Chỉ 2 dòng: đặt lúc nào cũng được / 1 lần mỗi tháng tính trong phí, lần 2 trở đi có phí giao bổ sung"],
     "src": "hong 回答 2026-10-05 版1.0レビュー（台帳 E ⑧）"},
    {"date": "2026-10-05", "target": "CW_MAT_001 No.9.4",
     "q": ["資材の表に「コース名」の列を出すか", "Bảng vật tư có cột \"コース名\" không"],
     "a": ["出さない（表は No・写真・資材名・単位・注文数量）", "Không (bảng chỉ còn No, 写真, 資材名, 単位, 注文数量)"],
     "src": "hong 回答 2026-10-05 版1.0レビュー（台帳 E ⑨）"},
    {"date": "2026-10-05", "target": "CW_MAT_001 No.7",
     "q": ["資材便のお届け予定日をいつ決めるか（版 1.0 は登録日の2日後）", "Ngày giao dự kiến của 資材便 quyết định khi nào (bản 1.0: ngày đăng ký + 2)"],
     "a": ["運営が資材注文管理で送り状番号・発送日を入れ、リードタイムから出せるときだけ出す。それまで出さない。リードタイムの日数は運営Web 側で決める（受付簿 No.154）", "Chỉ hiện khi 運営 đã nhập 送り状番号, 発送日 ở 資材注文管理 và tính được từ lead time. Trước đó không hiện. Số ngày lead time quyết định ở phía 運営Web (受付簿 No.154)"],
     "src": "hong 回答 2026-10-05 版1.0レビュー（台帳 E ⑩）"},
    {"date": "2026-10-05", "target": "CW_MAT_001 No.5・No.21・No.18",
     "q": ["変更履歴を資材注文でもモーダルで見せるか、画面内のタブにするか", "Lịch sử thay đổi ở 資材注文 cũng hiện bằng modal hay là tab trong màn hình"],
     "a": ["タブにする（商品注文と同じ）。「注文」「変更履歴」の2つのタブ（P-TAB・URL ?tab=）。「変更履歴確認」ボタンとモーダルはなくす", "Dùng tab (giống 商品注文). Hai tab 「注文」 「変更履歴」 (P-TAB, URL ?tab=). Bỏ nút 「変更履歴確認」 và modal"],
     "src": "hong 回答 2026-10-05（版 1.1 のレビュー 2回目・受付簿 No.157）"},
    {"date": "2026-10-05", "target": "CW_MAT_001 No.7・No.8・No.9・No.22",
     "q": ["解約後（参照のみ）の資材注文の画面に、注文の案内や編集のボタンを出すか。サーバーは書き込みを断るか", "Ở trạng thái sau hủy hợp đồng (chỉ xem), màn 資材注文 có hiện hướng dẫn đặt hàng và nút sửa không. Server có từ chối ghi không"],
     "a": ["出さない（編集のボタン・編集向けの案内・「注文数量」の列）。サーバー側でも、参照のみのアカウントからの登録は断る（画面を隠すだけにしない）", "Không hiện (nút sửa, hướng dẫn thiên về đặt hàng, cột 「注文数量」). Phía server cũng từ chối đăng ký từ tài khoản chỉ xem (không chỉ ẩn trên màn hình)"],
     "src": "hong 回答 2026-10-05（版 1.1 のレビュー 2回目・受付簿 No.157）"},
]

CHANGES = [
    {"ver": "1.4", "date": "2026-10-05", "no": ["6", "15"], "type": "変更",
     "before": ["確認モーダル Q02 のボタン名「破棄する」", "Tên nút của modal xác nhận Q02: 「破棄する」"],
     "after": ["「破棄」（共通メッセージ Q02 の文言どおり）", "「破棄」 (đúng câu của message chung Q02)"],
     "reason": ["hong 回答 2026-10-05（版 1.1 のレビューへの返事・受付簿 No.157）：表示の文言を共通メッセージ（Q02）と画面の言い方にそろえる", "hong trả lời 2026-10-05 (trả lời review bản 1.1, 受付簿 No.157): thống nhất câu chữ theo message chung (Q02) và cách gọi trên màn hình"],
     "impact": ["ボタン名だけ（動きは同じ）", "Chỉ tên nút (hành vi giống nhau)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "21", "type": "追加",
     "before": ["（なし）", "(không có)"],
     "after": ["見出しの下に「注文」「変更履歴」のタブ。URL の ?tab= で持つ", "Dưới tiêu đề có tab 「注文」 「変更履歴」, lưu trong URL ?tab="],
     "reason": ["hong 回答 2026-10-05（版 1.1 のレビュー 2回目・受付簿 No.157）：変更履歴は資材注文でもタブにする（商品注文と同じ）", "hong trả lời 2026-10-05 (review bản 1.1 lần 2, 受付簿 No.157): 変更履歴 ở 資材注文 cũng là tab (giống 商品注文)"],
     "impact": ["タブ部品を足す。入力中の数量はタブを変えても消さない。登録・キャンセルは画面全体で1つ", "Thêm thành phần tab. Số lượng đang nhập không mất khi đổi tab. 登録 / キャンセル là 1 cho cả màn hình"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "5", "type": "削除",
     "before": ["見出しの「変更履歴確認」ボタン（変更履歴のモーダルを開く）", "Nút 「変更履歴確認」 ở tiêu đề (mở modal lịch sử thay đổi)"],
     "after": ["削除（変更履歴は画面内のタブ・No.21）", "Xóa (変更履歴 là tab trong màn hình, No.21)"],
     "reason": ["hong 回答 2026-10-05（受付簿 No.157）", "hong trả lời 2026-10-05 (受付簿 No.157)"],
     "impact": ["ボタンとモーダル（LogDialog）をなくす", "Bỏ nút và modal (LogDialog)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["18", "18.1", "18.2"], "type": "変更",
     "before": ["変更履歴のモーダル（見出しに「拠点・サイクル月」・閉じる）。表の説明は4列（コードも4列）", "Modal lịch sử (tiêu đề có 「chi nhánh・tháng chu kỳ」, nút 閉じる). Bảng mô tả 4 cột (code cũng 4 cột)"],
     "after": ["画面内のタブ「変更履歴」の中身。表は P-HIST の列（日時・変更した人・操作・項目・変更前・変更後・理由）。0件は I01「表示するデータがありません。」", "Nội dung tab 「変更履歴」 trong màn hình. Bảng theo cột P-HIST (日時・変更した人・操作・項目・変更前・変更後・理由). 0 dòng: I01 「表示するデータがありません。」"],
     "reason": ["モーダルをやめてタブにする（受付簿 No.157）。コードは P-HIST の列に直してあり、18.1 の「コードは4列」の注記は不要になった", "Bỏ modal chuyển sang tab (受付簿 No.157). Code đã sửa theo cột P-HIST nên ghi chú \"code 4 cột\" ở 18.1 không còn cần"],
     "impact": ["状態 006 を「変更履歴（タブ・?tab=history）」に変える", "Đổi trạng thái 006 thành 「変更履歴（タブ・?tab=history）」"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "18.3", "type": "削除",
     "before": ["モーダルの「閉じる」ボタン", "Nút 「閉じる」 của modal"],
     "after": ["削除（タブにはない）", "Xóa (tab không có)"],
     "reason": ["hong 回答 2026-10-05（受付簿 No.157）", "hong trả lời 2026-10-05 (受付簿 No.157)"],
     "impact": ["なし", "Không"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "7", "type": "変更",
     "before": ["解約後（参照のみ）の拠点にはボタンを出さない（画面だけ）", "Với tài khoản sau hủy hợp đồng (chỉ xem) không hiện nút (chỉ trên màn hình)"],
     "after": ["画面のボタンを出さないことに加え、サーバーも参照のみのアカウントからの登録を断る（403）", "Ngoài việc không hiện nút trên màn hình, server cũng từ chối đăng ký từ tài khoản chỉ xem (403)"],
     "reason": ["hong 回答 2026-10-05（受付簿 No.157）：参照のみは画面を隠すだけでなくサーバーでも断る", "hong trả lời 2026-10-05 (受付簿 No.157): chỉ xem thì không chỉ ẩn màn hình mà server cũng từ chối"],
     "impact": ["corp-order の registerMat などの書き込みは Acc の ro（参照のみ）を見て断る（corp-docs と同じ作り）", "Các thao tác ghi như registerMat trong corp-order kiểm tra cờ ro (chỉ xem) của Acc và từ chối (cùng cách làm với corp-docs)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["8", "9", "9.6"], "type": "変更",
     "before": ["解約後（参照のみ）でも案内（2行）と「注文数量」の列（数量の欄は無効）を出す。資材が0件のときの表示の決まりなし", "Sau hủy hợp đồng (chỉ xem) vẫn hiện hướng dẫn (2 dòng) và cột 「注文数量」 (ô số lượng bị khóa). Chưa quy định hiển thị khi 0 vật tư"],
     "after": ["参照のみでは案内（No.8）と「注文数量」の列（No.9.6）を出さない（資材名・単位の一覧だけ）。資材が0件のときは I01", "Chỉ xem thì không hiện hướng dẫn (No.8) và cột 「注文数量」 (No.9.6) (chỉ danh sách tên vật tư, đơn vị). 0 vật tư thì I01"],
     "reason": ["hong 回答 2026-10-05（受付簿 No.157）：参照のみには編集向けの案内を出さない。0件の表示は I01", "hong trả lời 2026-10-05 (受付簿 No.157): chỉ xem thì không hiện hướng dẫn thiên về sửa. 0 dòng hiện I01"],
     "impact": ["案内と数量の列を ro で外す。表が空のときは EmptyState（I01）", "Bỏ hướng dẫn và cột số lượng khi ro. Bảng rỗng thì EmptyState (I01)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": "13", "type": "変更",
     "before": ["I210 のほか「変更履歴確認」だけ出す", "Ngoài I210 chỉ còn nút 「変更履歴確認」"],
     "after": ["I210 を表の場所に出す。変更履歴は画面内のタブ（No.21）", "I210 hiện ở vị trí bảng. Lịch sử thay đổi là tab trong màn hình (No.21)"],
     "reason": ["変更履歴確認ボタンの廃止（受付簿 No.157）", "Bỏ nút 変更履歴確認 (受付簿 No.157)"],
     "impact": ["なし（説明の直しのみ）", "Không (chỉ sửa mô tả)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["17", "17.2"], "type": "変更",
     "before": ["Q02 の文を「入力内容を破棄しますか？／保存していない内容は失われます。」、ボタンを「破棄する」と書いていた", "Ghi Q02 là 「入力内容を破棄しますか？／保存していない内容は失われます。」, nút 「破棄する」"],
     "after": ["共通メッセージ Q02 のとおり：「編集中の内容は保存されません。編集内容を破棄してもよろしいですか？」・ボタン「キャンセル」「破棄」", "Theo message chung Q02: 「編集中の内容は保存されません。編集内容を破棄してもよろしいですか？」, nút 「キャンセル」 「破棄」"],
     "reason": ["メッセージ一覧に文言をそろえる（コードは一覧どおり）", "Thống nhất câu chữ theo danh sách message (code đã đúng theo danh sách)"],
     "impact": ["なし（設計書の直しのみ）", "Không (chỉ sửa tài liệu)"]},
    {"ver": "1.4", "date": "2026-10-05", "no": ["22", "23"], "type": "追加",
     "before": ["（なし。解約後の画面の項目がなかった）", "(không có; trước đây chưa có mục cho màn sau hủy hợp đồng)"],
     "after": ["解約後（参照のみ）の画面：見出しに登録・キャンセル・今月 n回目を出さない（No.22）。資材の表は注文数量の列なし（No.23）", "Màn sau hủy hợp đồng (chỉ xem): tiêu đề không hiện 登録 / キャンセル / 今月 n回目 (No.22). Bảng vật tư không có cột số lượng (No.23)"],
     "reason": ["hong 回答 2026-10-05（受付簿 No.157）", "hong trả lời 2026-10-05 (受付簿 No.157)"],
     "impact": ["状態 008 を足す（デモの表示「解約後（参照のみ）」で撮る）", "Thêm trạng thái 008 (chụp với 「デモの表示」 = 解約後（参照のみ）)"]},

    {"ver": "1.2", "date": "2026-10-05", "no": "1", "type": "変更",
     "before": ["タイトル「資材注文」（コードは「資材注文 2026-11」で、直す宿題）", "Tiêu đề \"資材注文\" (code đang là \"資材注文 2026-11\", việc cần sửa)"],
     "after": ["タイトル「資材注文」（コードも直した）", "Tiêu đề \"資材注文\" (code đã sửa)"],
     "reason": ["コードが決定（hong 2026-10-05 B-16）に追いついた。設計書の注記だけを外す", "Code đã theo kịp quyết định (hong 2026-10-05 B-16). Chỉ bỏ ghi chú trong tài liệu"],
     "impact": ["なし（コードは対応済み）", "Không (code đã xử lý)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "20", "type": "追加",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：「今月 n回目のご注文」を登録ボタンの近くに出す（1回目は料金に含む・2回目以降は追加配送の料金）", "hong trả lời 2026-10-05 (review bản 1.0): hiện \"今月 n回目のご注文\" gần nút 登録 (lần 1 trong phí, lần 2 trở đi có phí giao bổ sung)"],
     "impact": ["登録ボタンの左にラベルを足す。サイクル月の資材注文の回数＋1 を出し、1回目は I222・2回目以降は W210。メッセージ I222・W210 を足す（受付簿 No.153）", "Thêm nhãn bên trái nút 登録: số đơn vật tư trong tháng chu kỳ + 1; lần 1 I222, lần 2 trở đi W210. Thêm message I222, W210 (受付簿 No.153)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "8", "type": "変更",
     "before": ["見出し「資材はいつでも注文できます（月1回までは料金に含みます）」＋本文（資材便・2回目以降の料金・今月の回数と資材注文No・初期セットの説明）", "Tiêu đề + nội dung dài (資材便, phí lần 2 trở đi, số lần và 資材注文No trong tháng, giải thích 初期セット)"],
     "after": ["2行だけ「資材はいつでも注文できます。」「月1回までは料金に含み、2回目以降は資材の追加配送の料金（{金額}）がかかります。」", "Chỉ 2 dòng \"資材はいつでも注文できます。\" \"月1回までは料金に含み、2回目以降は資材の追加配送の料金（{金額}）がかかります。\""],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：案内は2行", "hong trả lời 2026-10-05 (review bản 1.0): hướng dẫn chỉ 2 dòng"],
     "impact": ["案内の見出しをなくし本文を2行に。回数・資材注文No・初期セットの文を消す（回数は No.20 へ）（受付簿 No.153）", "Bỏ tiêu đề, rút nội dung còn 2 dòng. Bỏ câu về số lần, 資材注文No, 初期セット (số lần chuyển sang No.20) (受付簿 No.153)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "8.1", "type": "削除",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：2回目以降の料金の注意は「今月 n回目のご注文」（No.20・W210）で出すため、案内の下の W205 はなくす", "hong trả lời 2026-10-05 (review bản 1.0): cảnh báo phí lần 2 trở đi đã có ở \"今月 n回目のご注文\" (No.20, W210) nên bỏ W205 dưới phần hướng dẫn"],
     "impact": ["案内の下の警告（W205）を作らない。W205 は使わない", "Không làm cảnh báo W205 dưới phần hướng dẫn. Không dùng W205 nữa"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "9.4", "type": "削除",
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：コース名の列は出さない", "hong trả lời 2026-10-05 (review bản 1.0): không hiện cột コース名"],
     "impact": ["資材の表から「コース名」の列を外す（コードは出している・受付簿 No.153）", "Bỏ cột \"コース名\" khỏi bảng vật tư (code đang hiện; 受付簿 No.153)"]},
    {"ver": "1.1", "date": "2026-10-05", "no": "7", "type": "変更",
     "before": ["資材便のお届け予定日＝登録日の2日後（日曜・配送休日は翌日へ）", "Ngày giao dự kiến của 資材便 = ngày đăng ký + 2 (Chủ nhật / ngày nghỉ giao thì lùi)"],
     "after": ["お届け予定日は登録のときに決めない。運営が資材注文管理で送り状番号・発送日を入れ、リードタイムから出せるときに注文履歴（資材注文）に出る", "Không quyết định ngày giao dự kiến lúc đăng ký. Hiện ở 注文履歴 (資材注文) khi 運営 đã nhập 送り状番号, 発送日 ở 資材注文管理 và tính được từ lead time"],
     "reason": ["hong 回答 2026-10-05 版1.0レビュー：お届け予定日は送り状番号・発送日とリードタイムから出せるときだけ", "hong trả lời 2026-10-05 (review bản 1.0): ngày giao dự kiến chỉ hiện khi có 送り状番号, 発送日 và lead time"],
     "impact": ["登録で資材便の dueOn（登録日＋2日）を決めない。運営Web 資材注文管理に送り状番号・発送日・リードタイムを足し、そこから出す（受付簿 No.154）", "Khi đăng ký không gán dueOn (ngày đăng ký + 2). Thêm 送り状番号, 発送日, lead time ở 資材注文管理 của 運営Web và tính từ đó (受付簿 No.154)"]},
]

HIDE_ALWAYS = [".es-demo-bar", ".es-chatbot", ".es-chatbot__fab", ".od-aboutlink", "#es-review"]
STATIC_CSS = ".corp{height:auto!important}.corp-main{overflow:visible!important}.es-sidenav{height:auto!important;min-height:100vh}"
VIEWER_CSS = STATIC_CSS

SCREENS = [
    {"code": "CW_MAT_001", "ja": "資材注文", "vi": "Đặt vật tư"},
]

# 入力中にする（1行目の「増やす」を2回）
_SETUP_INPUT = ("const b=document.querySelector('.od-mat .od-step button[aria-label=\"増やす\"]'); "
                "if(b){b.click(); await new Promise(r=>setTimeout(r,150)); b.click();} await new Promise(r=>setTimeout(r,500));")

# デモの表示を「解約後（参照のみ）」にする（デモの帯の「デモの表示」の選択。以後の状態に残るので、この状態は最後に置く）
_SETUP_RO = ("const s=[...document.querySelectorAll('select')].find(x=>[...x.options].some(o=>o.value==='ro')); "
             "if(s){Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(s,'ro'); s.dispatchEvent(new Event('change',{bubbles:true}));} "
             "await new Promise(r=>setTimeout(r,800));")

VIEWS = [
    {"id": "001", "code": "CW_MAT_001", "state": ["初期表示（拠点アカウント・通常）", "Hiển thị ban đầu (tài khoản chi nhánh, bình thường)"],
     "url": "/corp/order/materials", "login": "CU00871", "full": True, "wait": 800,
     "note": ["大阪支店（ES配送便・ESライト（冷蔵庫））。数量はすべて 0 から入力する。登録すると資材便（1注文＝1便）が作られ、運営Web の資材注文管理に「出荷待」で出る",
              "Chi nhánh Osaka (ES配送便, ESライト（冷蔵庫）). Số lượng bắt đầu từ 0. Đăng ký xong sẽ tạo 1 chuyến 資材便 (1 đơn = 1 chuyến), hiện ở 運営Web 資材注文管理 với trạng thái \"出荷待\""],
     "items": [
         {"no": "1", "ja": "パンくず・タイトル", "vi": "Breadcrumb và tiêu đề", "sel": ".es-pagehead__text", "kind": "label", "trig": "view",
          "detail": ["「月次注文 / 資材注文」。タイトルは「資材注文」（サイクル月は付けない。hong 2026-10-05 B-16）。資材はいつでも注文できるため（今の受付のメニューの月）",
                     "\"月次注文 / 資材注文\". Tiêu đề \"資材注文\" (không kèm tháng chu kỳ, hong 2026-10-05 B-16). Vật tư đặt lúc nào cũng được nên tháng chu kỳ chỉ là tham khảo (tháng của menu đang nhận đơn)"]},
         {"no": "2", "ja": "拠点タブ", "vi": "Tab chi nhánh", "sel": ".od-sitetabs", "kind": "tab", "trig": "click", "pattern": "P-TAB",
          "detail": ["拠点名＋（資材注文の状態）。拠点アカウントは自分の拠点だけ（タブ1つ）。法人アカウントは自社の拠点（今のサイクルの子契約がある拠点と休止中の拠点）を並べる。状態＝登録済（このサイクル月に注文あり）／未注文／休止中。入力中に別の拠点を押すと Q02 を出す。URL（?tab=）は持たない（拠点の選択は商品注文と共有）",
                     "Tên chi nhánh + (trạng thái đặt vật tư). Tài khoản chi nhánh chỉ có 1 tab. Tài khoản pháp nhân: các chi nhánh của công ty (có 子契約 chu kỳ này và chi nhánh đang tạm dừng). Trạng thái = 登録済 (đã đặt trong tháng chu kỳ) / 未注文 / 休止中. Đang nhập mà bấm chi nhánh khác thì hiện Q02. Không giữ trong URL (?tab=): chi nhánh đang chọn dùng chung với 商品注文"],
          "err": ["Q02"]},
         {"no": "3", "ja": "プラン", "vi": "Gói (plan)", "sel": ".od-plan", "kind": "label", "trig": "view",
          "detail": ["子契約のプラン：プランID・月{n}個プラン（コース）・配送方法・貸出設備（例：ES000003 月50個プラン（ESライト（冷蔵庫））ES配送便・冷蔵庫）",
                     "Plan của 子契約: mã plan, 月{n}個プラン (khóa học), hình thức giao, thiết bị cho mượn (ví dụ: ES000003 月50個プラン（ESライト（冷蔵庫））ES配送便・冷蔵庫)"]},
         {"no": "4", "ja": "資材注文の状態", "vi": "Trạng thái đặt vật tư", "sel": ".od-status", "kind": "label", "trig": "view",
          "detail": ["バッジ：登録済（青）＝このサイクル月に資材注文あり／未注文（灰）／休止中（灰）",
                     "Badge: 登録済 (xanh) = tháng chu kỳ này đã có đơn vật tư / 未注文 (xám) / 休止中 (xám)"]},
         {"no": "21", "ja": "タブ（注文／変更履歴）", "vi": "Tab (注文 / 変更履歴)", "sel": ".od-subtabs", "kind": "area", "trig": "click", "pattern": "P-TAB",
          "detail": ["見出しの下に「注文」「変更履歴」の2つ。押したタブは URL の ?tab=（history）に持ち、再読み込み・戻るでも同じタブを開く。入力中の数量はタブを変えても消えない。「登録」「キャンセル」は画面全体で1つ。変更履歴はモーダルをやめてこのタブに入れた（hong 2026-10-05・受付簿 No.157。商品注文 CW_ORDER No.3.9 と同じ）",
                     "Dưới tiêu đề có 2 tab 「注文」 「変更履歴」. Tab được chọn lưu trong URL ?tab= (history); tải lại / Back vẫn mở đúng tab. Số lượng đang nhập không mất khi đổi tab. 「登録」 「キャンセル」 là 1 cho cả màn hình. 変更履歴 bỏ modal, đưa vào tab này (hong 2026-10-05, 受付簿 No.157; giống 商品注文 CW_ORDER No.3.9)"]},
         {"no": "6", "ja": "キャンセル", "vi": "Nút \"キャンセル\"", "sel": ".od-head__act button::キャンセル", "kind": "button", "trig": "click",
          "cond": ["数量を変えたときだけ押せる（初期表示は無効）", "Chỉ bấm được khi đã đổi số lượng (ban đầu bị khóa)"],
          "detail": ["Q02 を出し、「破棄」で入力中の数量を全部 0 に戻す", "Hiện Q02, nhấn \"破棄\" thì đưa toàn bộ số lượng đang nhập về 0"], "err": ["Q02"]},
         {"no": "7", "ja": "登録", "vi": "Nút \"登録\"", "sel": ".od-head__act button::登録", "kind": "button", "trig": "click", "pattern": "P-FORM",
          "cond": ["休止中・お試し・解約後（参照のみ）の拠点ではボタンを出さない", "Không hiện nút với chi nhánh đang tạm dừng, dùng thử, hoặc sau khi hủy hợp đồng (chỉ xem)"],
          "valid": ["注文数量が 1 以上の資材が1つもなければ E316（表の下）。このサイクル月に資材注文（通常注文・取消を除く）がすでにあれば Q205 を出し「注文する」で登録",
                    "Không có vật tư nào số lượng ≥ 1 thì E316 (dưới bảng). Tháng chu kỳ này đã có đơn vật tư (通常注文, trừ 取消) thì hiện Q205, nhấn \"注文する\" mới đăng ký"],
          "err": ["E316", "Q205", "S206", "E30"],
          "detail": ["数量 1 以上の資材だけで資材注文（資材注文No MO-YYMM-NNNN）と資材便（冷蔵・冷凍の便とは別・宅配便）を作る。お届け予定日は登録のときには決めない（ESキッチンが運営Web の資材注文管理で送り状番号・発送日を入れ、リードタイムから出せるようになったときに注文履歴（資材注文）に出る）。登録できたら S206 を出し、数量を 0 に戻す。2回目以降はオプション OP000036「資材の追加配送」を子契約に付ける。入力は P-FORM（押したら無効・失敗は E30）。解約後（参照のみ）のアカウントからの登録はサーバーも断る（403・画面のボタンを隠すだけにしない。hong 2026-10-05・受付簿 No.157）",
                     "Tạo đơn vật tư (資材注文No MO-YYMM-NNNN) và chuyến 資材便 (chuyến riêng, chuyển phát, khác chuyến lạnh/đông) chỉ với vật tư có số lượng ≥ 1. Ngày giao dự kiến không quyết định lúc đăng ký (chỉ hiện ở 注文履歴 (資材注文) khi ESキッチン đã nhập 送り状番号, 発送日 ở 資材注文管理 của 運営Web và tính được từ lead time). Thành công thì hiện S206 và đưa số lượng về 0. Lần 2 trở đi gắn option OP000036 \"資材の追加配送\" vào 子契約. Nhập theo P-FORM (khóa nút sau khi bấm, lỗi: E30). Đăng ký từ tài khoản sau hủy hợp đồng (chỉ xem) thì server cũng từ chối (403; không chỉ ẩn nút trên màn hình, hong 2026-10-05, 受付簿 No.157)"],
          "demo_ok": ["hong 2026-10-05 版1.0レビュー：お届け予定日を登録日＋2日で決めない（共通データの delivery.placeMaterialOrder は資材便の dueOn を登録日＋2日で作ったまま。法人Web の画面には出さない）。共通データを直す宿題（受付簿 No.154）",
                      "hong 2026-10-05 版1.0レビュー: không lấy ngày giao dự kiến = ngày đăng ký + 2 (dữ liệu chung delivery.placeMaterialOrder vẫn tạo dueOn = ngày đăng ký + 2; màn hình 法人Web không hiện). Sửa dữ liệu chung sau (受付簿 No.154)"]},
         {"no": "8", "ja": "資材注文の案内", "vi": "Hướng dẫn đặt vật tư", "sel": ".es-inline--info", "kind": "area", "trig": "view",
          "cond": ["解約後（参照のみ）の拠点には出さない（注文の案内のため）", "Không hiện với chi nhánh sau hủy hợp đồng (chỉ xem) (vì là hướng dẫn đặt hàng)"],
          "detail": ["2行だけ：1行目「資材はいつでも注文できます。」、2行目「月1回までは料金に含み、2回目以降は資材の追加配送の料金（{金額}）がかかります。」。見出し・今月の回数・資材注文No・資材便の説明・初期セットの説明は出さない（回数は No.20、注文の一覧は注文履歴の資材注文）",
                     "Chỉ 2 dòng: dòng 1 \"資材はいつでも注文できます。\", dòng 2 \"月1回までは料金に含み、2回目以降は資材の追加配送の料金（{金額}）がかかります。\". Không hiện tiêu đề, số lần trong tháng, 資材注文No, giải thích 資材便 và 初期セット (số lần xem No.20, danh sách đơn xem ở 注文履歴 tab 資材注文)"],
          "open": ["資材の追加配送（OP000036）の金額（決定_STEP5 §2-5 の提案値 ¥2,000／回・税抜）。確定したら本文・No.20（W210）・Q205 の {金額} に入れる。本文に「〔仮〕」は書かない",
                   "Số tiền của 資材の追加配送 (OP000036) (giá đề xuất trong 決定_STEP5 §2-5: ¥2,000/lần, chưa thuế). Chốt xong thì điền vào nội dung, No.20 (W210) và {金額} của Q205. Không ghi \"〔仮〕\" trên màn hình"],
          "ask": "お客様（営業）"},
         {"no": "9", "ja": "資材の一覧", "vi": "Bảng vật tư", "sel": ".od-mat", "kind": "table", "trig": "view",
          "detail": ["資材マスタのうち、この拠点のコース（ESスタンダード／ESライト（冷蔵庫）／ESライト（自販機））で使う資材だけを、資材マスタの並び（資材ID 昇順）で出す。検索・並べ替え・ページ送りはない（10件程度）。資材が0件のときは I01 を表の場所に出す。解約後（参照のみ）は「注文数量」の列を出さない（資材名・単位の一覧だけ。No.23）",
                     "Chỉ hiện vật tư trong 資材マスタ dùng cho khóa học của chi nhánh (ESスタンダード / ESライト（冷蔵庫） / ESライト（自販機）), theo thứ tự 資材マスタ (mã vật tư tăng dần). Không có tìm kiếm, sắp xếp, phân trang (khoảng 10 dòng). 0 vật tư thì hiện I01 ở vị trí bảng. Sau hủy hợp đồng (chỉ xem) không hiện cột 「注文数量」 (chỉ danh sách tên vật tư và đơn vị; No.23)"], "err": ["I01"]},
         {"no": "9.1", "ja": "No", "vi": "Số thứ tự", "sel": ".od-mat th::No", "kind": "label", "trig": "view", "detail": ["1 からの連番", "Đánh số từ 1"]},
         {"no": "9.2", "ja": "写真", "vi": "Ảnh", "sel": ".od-mat th::写真", "kind": "label", "trig": "view", "detail": ["資材マスタの写真（サムネイル）", "Ảnh thu nhỏ từ 資材マスタ"]},
         {"no": "9.3", "ja": "資材名", "vi": "Tên vật tư", "sel": ".od-mat th::資材名", "kind": "label", "trig": "view", "detail": ["例：割り箸・スプーン・深皿・おしぼり・ゴミ袋（45L）", "Ví dụ: 割り箸, スプーン, 深皿, おしぼり, ゴミ袋（45L）"]},
         {"no": "9.5", "ja": "単位", "vi": "Đơn vị", "sel": ".od-mat th::単位", "kind": "label", "trig": "view", "detail": ["膳・本・枚・個（資材マスタ）", "膳, 本, 枚, 個 (theo 資材マスタ)"]},
         {"no": "9.6", "ja": "注文数量", "vi": "Số lượng đặt", "sel": ".od-mat .od-step", "kind": "text", "trig": "input", "req": "条件付き",
          "cond": ["解約後（参照のみ）の拠点には列ごと出さない", "Không hiện cả cột với chi nhánh sau hủy hợp đồng (chỉ xem)"],
          "len": ["整数 0〜999（右寄せ・－／＋ボタンつき）", "Số nguyên 0–999 (căn phải, có nút －/＋)"],
          "init": ["0（すべての資材）", "0 (tất cả vật tư)"],
          "ex": ["80", "Số lượng vật tư muốn đặt (ví dụ 80 đôi đũa). Chỉ nhập số; chữ số toàn góc đổi sang nửa góc; để 0 nếu không đặt"],
          "valid": ["数字以外は取り除く。999 を超えたら 999 にする。登録のとき 1 以上の資材が1つもなければ E316",
                    "Bỏ ký tự không phải số. Quá 999 thì lấy 999. Khi đăng ký, không có vật tư nào ≥ 1 thì E316"],
          "err": ["E316"],
          "detail": ["少なくとも1つの資材に 1 以上を入れる（それ以外の行は 0 のままでよい）。「資材×プラン」の月の無料数量を超えた分は資材マスタの単価で請求する（運営の資材マスタ・受付簿 No.20）",
                     "Ít nhất 1 vật tư phải có số lượng ≥ 1 (dòng khác để 0). Phần vượt số lượng miễn phí tháng của \"資材×プラン\" sẽ tính theo đơn giá 資材マスタ (運営 資材マスタ, 受付簿 No.20)"]},
         {"no": "20", "ja": "今月 n回目のご注文", "vi": "Lần đặt thứ n trong tháng", "sel": ".od-head__act .od-count", "kind": "label", "trig": "view",
          "cond": ["「登録」ボタンを出すときだけ（休止中・お試し・解約後（参照のみ）の拠点では出さない）", "Chỉ khi hiện nút \"登録\" (không hiện với chi nhánh 休止中 / dùng thử / sau khi hủy hợp đồng (chỉ xem))"],
          "detail": ["「登録」ボタンの左に出す。n＝このサイクル月の資材注文（通常注文・取消を除く。初期セットは数えない）の回数＋1。1回目は I222「今月 1回目のご注文です。料金に含みます。」、2回目以降は W210「今月 {n}回目のご注文です。資材の追加配送の料金（{金額}）がかかります。」（黄色）。登録できたら n を1つ増やす。回数はサイクル月の資材便で数える（暦月ではない）",
                     "Hiện bên trái nút \"登録\". n = số đơn vật tư trong tháng chu kỳ (通常注文, trừ 取消; không đếm 初期セット) + 1. Lần 1: I222 \"今月 1回目のご注文です。料金に含みます。\"; lần 2 trở đi: W210 \"今月 {n}回目のご注文です。資材の追加配送の料金（{金額}）がかかります。\" (màu vàng). Đăng ký xong thì n tăng 1. Đếm theo 資材便 của tháng chu kỳ (không theo tháng lịch)"],
          "err": ["I222", "W210"],
          "open": ["W210 の {金額}＝資材の追加配送（OP000036）の金額（No.8 と同じ）", "{金額} trong W210 = số tiền 資材の追加配送 (OP000036) (giống No.8)"],
          "ask": "お客様（営業）"},
     ]},
    {"id": "002", "code": "CW_MAT_001", "state": ["休止中の拠点", "Chi nhánh đang tạm dừng"],
     "url": "/corp/order/materials", "login": "CU00902", "full": True, "wait": 800,
     "note": ["名古屋営業所（利用休止）。表・ボタンを出さず I209 だけ", "Chi nhánh Nagoya (tạm dừng). Không hiện bảng và nút, chỉ hiện I209"],
     "items": [
         {"no": "10", "ja": "拠点タブ（休止中）", "vi": "Tab chi nhánh (tạm dừng)", "sel": ".od-sitetabs", "kind": "tab", "trig": "view",
          "detail": ["状態は「休止中」", "Trạng thái \"休止中\""]},
         {"no": "11", "ja": "休止中の案内", "vi": "Thông báo tạm dừng", "sel": ".es-empty", "kind": "label", "trig": "view",
          "cond": ["拠点が利用休止中（契約の状態が利用休止、またはこのサイクル月が休止の期間）", "Chi nhánh đang tạm dừng (trạng thái hợp đồng 利用休止, hoặc tháng chu kỳ này nằm trong kỳ tạm dừng)"],
          "detail": ["I209 を一覧の場所に出す。登録・キャンセルのボタンは出さない", "Hiện I209 ở vị trí bảng. Không hiện nút 登録 / キャンセル"], "err": ["I209"]},
     ]},
    {"id": "003", "code": "CW_MAT_001", "state": ["お試しの拠点（参照のみ）", "Chi nhánh dùng thử (chỉ xem)"],
     "url": "/corp/order/materials", "login": "CU00071", "full": True, "wait": 800,
     "note": ["株式会社みちのく商事 仙台本社（お試しキャンペーン）。資材は初期セットを自動でお届けするため、法人Web からは注文できない",
              "Công ty Michinoku, trụ sở Sendai (chiến dịch dùng thử). Vật tư được giao tự động bằng 初期セット nên không đặt từ 法人Web"],
     "items": [
         {"no": "12", "ja": "拠点タブ（お試し）", "vi": "Tab chi nhánh (dùng thử)", "sel": ".od-sitetabs", "kind": "tab", "trig": "view",
          "detail": ["状態は「お試し」", "Trạng thái \"お試し\""]},
         {"no": "13", "ja": "お試しの案内", "vi": "Thông báo dùng thử", "sel": ".od-head", "kind": "label", "trig": "view",
          "cond": ["この拠点の子契約がお試しキャンペーンのとき", "Khi 子契約 của chi nhánh là chiến dịch dùng thử"],
          "detail": ["I210 を一覧の場所に出す。資材の表・登録・キャンセルは出さない（変更履歴は画面内のタブ・No.21）", "Hiện I210 ở vị trí bảng. Không hiện bảng vật tư, 登録, キャンセル (lịch sử thay đổi là tab trong màn hình, No.21)"],
          "err": ["I210"]},
     ]},
    {"id": "004", "code": "CW_MAT_001", "state": ["入力中（未登録）", "Đang nhập (chưa đăng ký)"],
     "url": "/corp/order/materials", "login": "CU00871", "full": True, "wait": 800, "setup": _SETUP_INPUT,
     "note": ["割り箸を 2 にした状態。キャンセルが押せるようになる。このサイクル月に注文済みのときは登録で Q205",
              "Đã đổi 割り箸 thành 2. Nút キャンセル bấm được. Tháng chu kỳ này đã có đơn thì 登録 sẽ hiện Q205"],
     "items": [
         {"no": "14", "ja": "数量（入力あり）", "vi": "Số lượng (đã nhập)", "sel": ".od-mat .od-step:not(.is-zero)", "kind": "label", "trig": "view",
          "detail": ["1 以上の行は数量を濃く表示（0 の行は薄い）", "Dòng ≥ 1 hiện đậm (dòng 0 hiện nhạt)"]},
         {"no": "15", "ja": "キャンセル（活性）", "vi": "キャンセル (bấm được)", "sel": ".od-head__act button::キャンセル", "kind": "button", "trig": "click",
          "detail": ["Q02 → 「破棄」で数量を 0 に戻す（No.17）", "Q02 → \"破棄\" đưa số lượng về 0 (No.17)"], "err": ["Q02"]},
         {"no": "16", "ja": "2回目以降の確認モーダル", "vi": "Modal xác nhận lần đặt thứ 2 trở đi", "sel": ".od-head__act button::登録", "kind": "modal", "trig": "click",
          "cond": ["「登録」を押したとき、このサイクル月にすでに資材注文（通常注文・取消を除く）があるとき", "Khi bấm \"登録\" mà tháng chu kỳ này đã có đơn vật tư (通常注文, trừ 取消)"],
          "detail": ["Q205（タイトル「資材を注文しますか？」・本文に追加配送の料金）。ボタン「キャンセル」「注文する」。「注文する」で No.7 の登録を続ける。1回目は出さずにそのまま登録",
                     "Q205 (tiêu đề \"資材を注文しますか？\", nội dung nêu phí giao bổ sung). Nút \"キャンセル\" / \"注文する\". \"注文する\" thì tiếp tục đăng ký như No.7. Lần đầu thì không hiện, đăng ký luôn"],
          "err": ["Q205"],
          "open": ["Q205 の {金額}＝資材の追加配送（OP000036）の金額（No.8 と同じ）", "{金額} trong Q205 = số tiền 資材の追加配送 (OP000036) (giống No.8)"],
          "ask": "お客様（営業）"},
     ]},
    {"id": "005", "code": "CW_MAT_001", "state": ["破棄の確認（モーダル）", "Xác nhận hủy nội dung (modal)"],
     "url": "/corp/order/materials", "login": "CU00871", "full": True, "wait": 800,
     "setup": _SETUP_INPUT + " const c=[...document.querySelectorAll('.od-head__act button')].find(x=>x.textContent.includes('キャンセル')); c&&c.click(); await new Promise(r=>setTimeout(r,500));",
     "note": ["入力中にキャンセル・別の拠点タブ・別の画面へ移るときに出す（Q02・システム全体）", "Hiện khi đang nhập mà bấm キャンセル, tab chi nhánh khác, hoặc rời màn hình (Q02, toàn hệ thống)"],
     "items": [
         {"no": "17", "ja": "破棄の確認", "vi": "Modal xác nhận hủy", "sel": ".es-modal__panel", "kind": "modal", "trig": "view", "pattern": "P-FORM",
          "detail": ["Q02「編集中の内容は保存されません。編集内容を破棄してもよろしいですか？」。サイドメニュー・ブラウザの戻るで離れるときも同じ",
                     "Q02 \"編集中の内容は保存されません。編集内容を破棄してもよろしいですか？\". Rời bằng menu bên hoặc nút Back cũng hiện như vậy"],
          "err": ["Q02"]},
         {"no": "17.1", "ja": "キャンセル", "vi": "Nút \"キャンセル\"", "sel": ".es-modal__actions button::キャンセル", "kind": "button", "trig": "click",
          "detail": ["閉じて入力を続ける", "Đóng modal, tiếp tục nhập"]},
         {"no": "17.2", "ja": "破棄", "vi": "Nút \"破棄\"", "sel": ".es-modal__actions button::破棄", "kind": "button", "trig": "click",
          "detail": ["入力中の数量を 0 に戻す。拠点タブ・別の画面へ移る途中なら、そのまま移る", "Đưa số lượng về 0. Nếu đang chuyển tab chi nhánh / màn hình khác thì chuyển tiếp"]},
     ]},
    {"id": "006", "code": "CW_MAT_001", "state": ["変更履歴（タブ）", "Lịch sử thay đổi (tab)"],
     "url": "/corp/order/materials?tab=history", "login": "CU00871", "full": True, "wait": 1200,
     "note": ["「変更履歴」のタブ（URL ?tab=history）。商品注文の変更履歴と同じ表（拠点・サイクル月）。資材注文の登録もここに残る。資材の表・登録・キャンセルの入力は「注文」のタブだけ（版 1.4）", "Tab 「変更履歴」 (URL ?tab=history). Cùng bảng với lịch sử của 商品注文 (chi nhánh, tháng chu kỳ). Đăng ký vật tư cũng ghi ở đây. Bảng vật tư và ô nhập chỉ ở tab 「注文」 (bản 1.4)"],
     "items": [
         {"no": "18", "ja": "変更履歴のタブの中身", "vi": "Nội dung tab 変更履歴", "sel": ".od-log", "kind": "table", "trig": "show", "pattern": "P-HIST",
          "detail": ["この拠点のこのサイクル月の商品注文の履歴、受付開始日以降の資材注文の登録（「資材注文を登録」・詳細に資材名と数量）、注文の設定・アンケートの履歴を新しい順に出す。0件は I01「表示するデータがありません。」。モーダルではなく画面の中に出す",
                     "Hiện theo thứ tự mới nhất: lịch sử 商品注文 của chi nhánh trong tháng chu kỳ, đăng ký vật tư từ ngày bắt đầu nhận đơn (\"資材注文を登録\", chi tiết ghi tên vật tư và số lượng), lịch sử 注文の設定 và アンケート. 0 dòng: I01 「表示するデータがありません。」. Hiện ngay trong màn hình, không dùng modal"],
          "err": ["I01"]},
         {"no": "18.1", "ja": "履歴の表", "vi": "Bảng lịch sử", "sel": ".od-log", "kind": "label", "trig": "view", "pattern": "P-HIST",
          "detail": ["列は P-HIST のとおり：日時・変更した人・操作・項目・変更前・変更後・理由（あれば）。変更した人はアカウント名（拠点名（拠点アカウント）／法人名（法人アカウント）／ESキッチン）。ESキッチンが変えた行は「操作」を黄色のバッジで出す",
                     "Cột theo P-HIST: 日時, 変更した人, 操作, 項目, 変更前, 変更後, 理由 (nếu có). Người thay đổi = tên tài khoản (tên chi nhánh (拠点アカウント) / tên pháp nhân (法人アカウント) / ESキッチン). Dòng do ESキッチン đổi thì \"操作\" hiện badge vàng"]},
         {"no": "18.2", "ja": "注記", "vi": "Ghi chú", "sel": "p.note::締切後に ES が変更した分", "kind": "label", "trig": "view",
          "detail": ["締切後に ESキッチンが変えた分（代替品・欠品など）も残ること、ログインは共有のため変更した人はアカウント名で出すこと",
                     "Thay đổi của ESキッチン sau hạn chốt (hàng thay thế, thiếu hàng…) cũng được giữ; đăng nhập dùng chung nên người thay đổi hiện bằng tên tài khoản"]},
     ]},
    {"id": "007", "code": "CW_MAT_001", "state": ["法人アカウント（拠点タブ）", "Tài khoản pháp nhân (tab nhiều chi nhánh)"],
     "url": "/corp/order/materials", "full": True, "wait": 800,
     "note": ["株式会社サンプル（法人アカウント）。本社・大阪支店・名古屋営業所・横浜営業所・千葉営業所のタブ。最初は一覧の先頭の拠点",
              "Công ty Sample (tài khoản pháp nhân). Tab 本社, 大阪支店, 名古屋営業所, 横浜営業所, 千葉営業所. Mặc định mở chi nhánh đầu danh sách"],
     "items": [
         {"no": "19", "ja": "拠点タブ（複数）", "vi": "Tab chi nhánh (nhiều)", "sel": ".od-sitetabs", "kind": "tab", "trig": "click",
          "detail": ["拠点を押すとその拠点の資材注文に切り替える。入力中の数量は拠点ごとに持ち、別の拠点を押すときは Q02（破棄すると 0 に戻る）。資材の表はその拠点のコースの資材に変わる（ESスタンダードは 深皿フタ（スタンダード）・保冷用ビニール袋 が足される）",
                     "Bấm chi nhánh để chuyển sang đơn vật tư của chi nhánh đó. Số lượng đang nhập giữ theo từng chi nhánh; bấm chi nhánh khác thì Q02 (hủy thì về 0). Bảng vật tư đổi theo khóa học của chi nhánh (ESスタンダード thêm 深皿フタ（スタンダード）, 保冷用ビニール袋)"],
          "err": ["Q02"]},
     ]},
    # ---- 版 1.4 で足した状態（受付簿 No.157）。デモの表示を「解約後（参照のみ）」にして撮る（以後の状態に影響するので最後に置く）
    {"id": "008", "code": "CW_MAT_001", "state": ["解約後（参照のみ）", "Sau hủy hợp đồng (chỉ xem)"],
     "url": "/corp/order/materials", "login": "CU00871", "full": True, "wait": 1000, "setup": _SETUP_RO,
     "note": ["デモの表示を「解約後（参照のみ）」にした状態。登録・キャンセル・「今月 n回目のご注文」・注文の案内を出さず、表は資材名と単位だけ。変更履歴のタブは見られる。サーバーも参照のみからの登録を断る（403）",
              "Trạng thái đã chọn 「デモの表示」 = 解約後（参照のみ）. Không hiện 登録, キャンセル, 「今月 n回目のご注文」 và hướng dẫn đặt hàng; bảng chỉ có tên vật tư và đơn vị. Vẫn xem được tab lịch sử thay đổi. Server cũng từ chối đăng ký từ tài khoản chỉ xem (403)"],
     "items": [
         {"no": "22", "ja": "解約後（参照のみ）の見出し", "vi": "Tiêu đề sau hủy hợp đồng (chỉ xem)", "sel": ".od-head", "kind": "area", "trig": "view",
          "cond": ["アカウントの状態が参照のみ（解約後・最後のご請求の入金期限まで）のとき", "Khi trạng thái tài khoản là chỉ xem (sau hủy hợp đồng, đến hạn thanh toán của hóa đơn cuối)"],
          "detail": ["拠点名・プラン・資材注文の状態のバッジだけ。「登録」「キャンセル」「今月 n回目のご注文」（No.20）を出さない（hong 2026-10-05・受付簿 No.157）。参照のみでできるのは棚卸報告だけ", "Chỉ còn tên chi nhánh, plan và badge trạng thái đặt vật tư. Không hiện 「登録」 「キャンセル」 「今月 n回目のご注文」 (No.20) (hong 2026-10-05, 受付簿 No.157). Chỉ xem thì chỉ làm được 棚卸報告"]},
         {"no": "23", "ja": "資材の一覧（参照のみ）", "vi": "Bảng vật tư (chỉ xem)", "sel": ".od-mat", "kind": "table", "trig": "view",
          "detail": ["列：No・写真・資材名・単位（「注文数量」の列と案内 No.8 は出さない）", "Cột: No, 写真, 資材名, 単位 (không hiện cột 「注文数量」 và hướng dẫn No.8)"]},
     ]},
]
